### ISSUE TITLE
Use anaconda on CircleCI

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1003]
I've heard rumors that anaconda on CircleCI could speed up very much run of the examples. We should give it a try. MNE-Python is trying too, maybe we can draw inspiration from there work:
https://github.com/mne-tools/mne-python/pull/2849/files

It would be interesting to see a before/after account of execution time.

This would be a first step in solving https://github.com/nilearn/nilearn/issues/1000

**Comment by aabadie** [comment]
@GaelVaroquaux, I'm on it !

**Comment by GaelVaroquaux** [comment]
Yeah!

**Comment by lesteve** [comment]
At one point I toyed with the idea of using continuous_integration/install.sh on CircleCI i.e. use the same install script on both CIs. In case this is of any use:

https://github.com/lesteve/nilearn/tree/use-install-sh-on-circleci

I don't remember why I stopped though, probably it wasn't working perfectly ...

**Comment by aabadie** [comment]
> I don't remember why I stopped though, probably it wasn't working perfectly

I gave a try at you branch which is a good starting point for this issue but it was not working at all :)
The problem comes the environment variables that are reset for each commands in circle ci unless they are set globally. I could make this work but then I had another issue with the default python virtualenv already installed.

In a summary, it's a bit a mess to set up conda on circleci but I nearly have something working: conda environment is set up and dependencies can be installed, nilearn is installed but the make html-strict is not working yet.

I can already say that the preliminary steps are way faster than the actual workflow.

**Comment by aabadie** [comment]
The unsolvable problem (from our code only) comes from an incompatibility with the version of Ubuntu on the build VM (which is 12.04 and provides libpng 1.2) and matplotlib 1.3.1 where pylab require libpng 1.5.

Circle ci seems to provide an experimental 14.04 ubuntu where this should be fixed.
See discussion here : https://discuss.circleci.com/t/when-are-we-going-to-get-ubuntu-14-04/331/5
There was also an announce 4 days ago about this : https://discuss.circleci.com/t/ubuntu-14-04-trusty-container/2260
So I decided to activate in the Experimental settings of the project on the web interface (at the very bottom) but it didn't make it either.

**Comment by aabadie** [comment]
@lesteve, you can have a look, the changes are here : https://github.com/aabadie/nilearn/tree/circle_ci_anaconda
(it's based on your initial branch and rebased with latest master)

**Comment by GaelVaroquaux** [comment]
Have you looked at the MNE Python PR that I mentionned in the issue?
https://github.com/mne-tools/mne-python/pull/2849/files

Did they get anaconda working on CircleCI? It seems so, no?

**Comment by aabadie** [comment]
> Did they get anaconda working on CircleCI? It seems so, no?

Thanks for the hint.
MNE python circleci setup seems to very close to what we do. They don't set a matplotlib version. I can try this.

**Comment by lesteve** [comment]
> They don't set a matplotlib version. I can try this.

Actually do we want to make sure the examples run with the minimum matplotlib advertised version, namely 1.1.1. Off the top of my head 1.1.1 is the version in Ubuntu 12.04 so you shouldn't have the problems you mentioned.

Side-comment: the conda env should have libpng installed so the problem you are describing is a bit surprising. Having said that from time to time conda does miss some dependency (like the libgfortran case that we saw for numpy some time ago) so it could well be the case here as well.

**Comment by aabadie** [comment]
> Actually do we want to make sure the examples run with the minimum matplotlib advertised version, namely 1.1.1

In fact, the circle ci setup file uses matplotlib 1.3.1 but I can change this (probably later).

**Comment by lesteve** [comment]
> In fact, the circle ci setup file uses matplotlib 1.3.1 but I can change this (probably later).

It does in your branch. I am guessing you (or I in my original experimental branch) took it from one of the distrib in .travis.yml. Basically 1.3.1 is completely arbitrary. 

All I was trying to say:
* using 1.1.1 would make sense to test that all the examples run with the minimal matplotlib version advertised in README.md
* potentially fix the problem you were reporting with the libpng incompatibilities.

**Comment by aabadie** [comment]
The 1.1.1 version is used with python 2.6 in the travis build matrix and it's not compatible with the version of numpy we use with python 2.7 here : 1.8.2.

**Comment by aabadie** [comment]
@GaelVaroquaux, @lesteve, after looking at the link to the PR on MNE python. Only forcing the python version is the way to go. Note that it uses the very last versions of other dependencies but it runs ok. Let's see if the documentation is correctly generated here : https://circleci.com/gh/aabadie/nilearn/252
If it's ok, the PR will come soon.

**Comment by lesteve** [comment]
Have you tried this?

> using 1.1.1 would make sense to test that all the examples run with the minimal matplotlib version advertised in README.md

**Comment by aabadie** [comment]
@lesteve, about using matplotlib 1.1.1, yes I tried last friday but it failed for the same reason.

**Comment by lesteve** [comment]
Same reason, meaning this?

> The 1.1.1 version is used with python 2.6 in the travis build matrix and it's not compatible with the version of numpy we use with python 2.7 here : 1.8.2.

You can find a numpy version compatible with matplotlib 1.1.1 inside conda. Just play locally with conda and you'll find one. I tried a few days ago and I am pretty sure numpy 1.6 worked.

Also, before doing that and now that it works, have you looked whether the running time of the examples has decreased, since that the prime motivation of this issue.

**Comment by aabadie** [comment]
> Also, before doing that and now that it works, have you looked whether the running time of the examples has decreased, since that the prime motivation of this issue.

Nope, the examples are still running

**Comment by aabadie** [comment]
The current run is not a good on for comparison as it doesn't use cached data (all have to be downloaded). At least the setup step is faster: less than 2 minutes whereas it takes more than 10 minutes when using pip.

**Comment by lesteve** [comment]
> At least the setup step is faster: less than 2 minutes whereas it takes more than 10 minutes when using pip.

As far as I remember that was the reason why I looked originally into using conda on CircleCI but then I realised that there were some virtualenv caching on CircleCI. I seem to remember sometimes the pip install step is super quick and it says "dependencies already satisfied". This is probably why I dropped the whole thing.

**Comment by aabadie** [comment]
> I seem to remember sometimes the pip install step is super quick and it says "dependencies already satisfied"

Yes, I also saw that but to me they are probably doing some VM caching as an optimisation on their side (just a supposition, this is not sure), so that if one updates a given PR that has just already been built, it reuses the same environment.

**Comment by aabadie** [comment]
By the way, the last build was successful but unfortunately the test script is not at the right splace in `circle.yml. I'll push an update.

**Comment by lesteve** [comment]
For the record virtualenv caching seems is using CircleCI cache (i.e. the same thing we are using for datasets):
https://circleci.com/docs/how-cache-works

**Comment by GaelVaroquaux** [comment]
> Closed #1003 via #1037.

OK, now we will need to add Python 3 support to the example and to
CircleCI.

**Comment by karkir0003** [comment]
I have a repository where there is a `/conda` directory. However, I want my `config.yml` in `/.circleci` directory of my repo to run `cd conda && conda env create -f environment.yml`. I get error message saying "conda: command not found". Can someone please share a sample yml that solved this issue?
