### ISSUE TITLE
Add a resample_to_img

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1004]
We already have 
```
resample_img(img, target_affine=None, target_shape=None, interpolation='continuous', copy=True, order='F')
```
http://nilearn.github.io/modules/generated/nilearn.image.resample_img.html

It would be nice to have a variant
```
resample_to_img(source_img, target_img, interpolation='continuous', copy=True, order='F')
```
that would take the shape and affine from "target_img".

It's just a simple helper function, but it would make the life of many non advanced users simpler.

We should reference each function in there respective seealso section of the docstrings.

**Comment by aabadie** [comment]
I can have a look at this one too :)

**Comment by AlexandreAbraham** [comment]
+1000

**Comment by bthirion** [comment]
+1

**Comment by banilo** [comment]
+1

**Comment by GaelVaroquaux** [comment]
It's been done! It's in the codebase!

**Comment by aabadie** [comment]
@GaelVaroquaux, @banilo, I'm actually working on an example based on mni152 template. The idea is resample a tmap (from localizer datasets, but maybe there are better ones). I'll create a PR soon
