### ISSUE TITLE
signals.clean: Consider filtering based on a cosine base

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1011]
According to @pbellec, this has two benefits compared to our butterworth filter:
- Not having ugly side effects at the beginning and of the acquisition (need to check this)
- Enabling missing data, as eg in a later possible implementation of scrubbing

**Comment by GaelVaroquaux** [comment]
@bthirion : what's your feeling on cosine-based signal cleaning with regards to butterworth?

**Comment by bthirion** [comment]
No strong feeling. I have always used cosine filters (DCT bases).
It would be great to document any bad behavior of butterworth (e.g. border effect).

**Comment by danlurie** [comment]
Just encountered the Butterworth border effects in some of my own analysis. Nasty surprise until I realized what was causing the issue. I'm happy to add a note to the docs warning users about this. Where would be the right place to put this? With signal.clean?

**Comment by bthirion** [comment]
This would be in signal.clean.
Can you show an exmaple of poor outcome of the Butterworth filter ?
Thanks,

**Comment by danlurie** [comment]
I haven't to dug into the issues comprehensively, but one thing I have been able to replicate on multiple datasets (my own data and HCP) is that the filtering with `signal.clean` results in artificially low signal standard deviation at the beginning and end of a time series.

![Butterworth weirdness](https://cloud.githubusercontent.com/assets/1873103/26084332/2d39f2ee-3990-11e7-8bfa-b1bddca16c04.jpg)

Here's the code I used to filter and regress out nuisance signals:
```
masker = input_data.NiftiLabelsMasker(labels_img=bna_img, background_label=0,
                mask_img=bold_T1w_brainmask, standardize=False, detrend=True, 
                low_pass=0.2, high_pass=0.01, t_r=2, resampling_target="data")
```

**Comment by jerdra** [comment]
> I haven't to dug into the issues comprehensively, but one thing I have been able to replicate on multiple datasets (my own data and HCP) is that the filtering with `signal.clean` results in artificially low signal standard deviation at the beginning and end of a time series.
> ...


Hey, sorry if necro-bump, but has anyone attempted to implement DCT-based cosine regressors in lieu of signal.clean's butterworth filter? I've recently attempted this (albeit I'm not a signal processing expert) and have run into the same issue @danlurie has noted for the butterworth implementation *but worse* with a DCT v1.1 implementation.

I used a bandpass of (0.009, 0.08) for both `signal.clean` and for my DCT implementation. Band-pass for DCT was done via excluding DCT bins with frequencies within the bandpass range, the remaining bins were included in the regression model.

Here are my results:

![example_signal](https://user-images.githubusercontent.com/21374425/106337648-ba2f2880-625f-11eb-997e-dc668e927aee.png)

![std_over_voxels](https://user-images.githubusercontent.com/21374425/106337664-c1563680-625f-11eb-9467-fa184403221a.png)

**Comment by danlurie** [comment]
I haven't heard any updates on this issue, but FMRIPREP outputs DCT basis function regressors as part of its confounds workflow. That could be a good start to test your results against.
  
  

  
>

**Comment by jerdra** [comment]
I think fMRIPrep outputs the DCT basis functions for performing high-pass with aCompCor does it not? Does it also output higher frequency basis functions?

**Comment by bthirion** [comment]
I think that the discussion converges toward the point that low-pass filtering without centering yields artefacts, for all implementations.  This being said, I think that it is good for people to use DCT or Butterworth as they fancy.

**Comment by htwangtw** [comment]
This issue has long been resolved. Cosine basis filtering is possible, along with scrubbing
