### ISSUE TITLE
Compute a scrubbing sample mask

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1013]
We need to compute frame displacement (FD) from the movement parameters: the work is to transform the rotation in displacement using the heuristic that a brain is 50cm length.

Typically, the FD is padded back (ie a value 0 is added at the back) and thresholded and 1 tr is removed before, and 2 after (a total of 4 frames).

@pbellec has some matlab code that implements this and should be converted to python and nilearn:

To build the sample mask:
https://github.com/SIMEXP/niak/blob/issue122/commands/SI_processing/niak_fd2mask.m

To compute FD:
https://github.com/SIMEXP/niak/blob/issue122/commands/SI_processing/niak_fd2mask.m

The reference paper, on scrubbing from which all the formulas come, is:
http://www.sciencedirect.com/science/article/pii/S1053811911011815

**Comment by sahmed95** [comment]
Hi, I am new to open-source and I was looking for projects to work on. I have converted matlab codes to python before in the context of clipping diffusion MRI images. If no-one is working on this PR, I would like to start.

**Comment by GaelVaroquaux** [comment]
Hey @sahmed95 : I did notice that you were a new name. Welcome, and thanks for pitching in.

This issue isn't the best one to start with, partly because it is a bit involved, and partly because it require #1011 and #1012 to be completed before we tackle it.

I suggest that you look at the issues marked "Easy": https://github.com/nilearn/nilearn/issues?q=is%3Aissue+is%3Aopen+label%3AEasy

**Comment by banilo** [comment]
> If no one is working on this PR, I would like to start.

+1

**Comment by AlexandreAbraham** [comment]
I've just seen this issue. FYI, a lot of fMRI QC / movement statistics / detection of offending timepoints are already implemented in the CPAC pipeline.

For example, to compute the FD: https://github.com/FCP-INDI/C-PAC/blob/7965125125319d895464f40db57b0eaba9c84da3/CPAC/generate_motion_statistics/generate_motion_statistics.py

**Comment by pausz** [comment]
Hi, I was wondering if this issue and related ones (#1011 & #1012) have moved further up on the dev team's priority list. 

Let me know if I can be of assistance and work towards implementing this feature.

**Comment by tsalo** [comment]
Can this be closed since `load_confounds` was added?

**Comment by pbellec** [comment]
`load_confounds` is not a native solution to nilearn, but it adds the
capacity of incorporating a scrubbing mask through dependency on
`fmriprep`.

I think it is the right move: it avoids duplicating efforts and
satisfactorily addresses the needs of users who would like to implement
scrubbing.

+1 for closing.

Pierre
