### ISSUE TITLE
Rename all the non-user facing methods in the Slicers to private functions

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1014]
Things like '_init_with_figure' should be private, to have lighter tab-completion.

**Comment by sahmed95** [comment]
Can you give an example. Couldn't figure out what Slicers mean. Do you mean functions like this - [Link1](https://github.com/nilearn/nilearn/blob/master/nilearn/decomposition/dict_learning.py#L31)

Or methods like this - [Link2](https://github.com/nilearn/nilearn/blob/master/nilearn/decomposition/dict_learning.py#L163)

I would like to work on this.

**Comment by Remi-Gau** [comment]
Tempted to close this given we have another more global issue regarding naming of private / public functions and methods.

**Comment by ymzayek** [comment]
Ok with me. Maybe you can just mention that issue here or there to link it

**Comment by Remi-Gau** [comment]
Closing in favor of the more generic: https://github.com/nilearn/nilearn/issues/3319
