### ISSUE TITLE
[discussion] manual positioning of cut_coords n plotting functions should accept only list

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#1017]
For example, it is key to find difference between (36) to (36, )

**Comment by GaelVaroquaux** [comment]
No, not "accept only list", but in all our tutorials and documentation,
which should only demo lists, ot tuples.

**Comment by KamalakerDadi** [comment]
>No, not "accept only list", but in all our tutorials and documentation, which should only demo lists, ot tuples.

Ok, noted.

**Comment by AlexandreAbraham** [comment]
Some time ago, I raised the same problem and advocated to stop using cut_coords as a holdall. I suggested to differentiate `cut_coords` from `n_cuts`.

**Comment by GaelVaroquaux** [comment]
> Some time ago, I raised the same problem and advocated to stop using
> cut_coords as a holdall. I suggested to differentiate cut_coords from
> n_cuts.

Right, that's also an option. But that's an API change, wich is a wider
issue than just making sure we don't unecessarily use tuples in the docs.

Because of the (a, ) != (a) behavior, avoiding the use of tuples in
documentation and examples is a general good practice.

**Comment by salma1601** [comment]
@KamalakerDadi draw my attention to use lists for cut coordinates, but that is not what is told in the docstring
https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/img_plotting.py#L410
 I also find it more intuitive to use tuples, and consistent with seeds in `NiftiSpheresMasker`

**Comment by AlexandreAbraham** [comment]
I think that this discussion is dead. We keep the status quo.

**Comment by KamalakerDadi** [comment]
>but that is not what is told in the docstring

Yes, but more particular of examples exposing to use list rather tuple. I agree doc is different and you use can tuple. But, point here is to teach users to give as list.

**Comment by salma1601** [comment]
So docstring is not meant to be updated ??

**Comment by KamalakerDadi** [comment]
>So docstring is not meant to be updated ??

Thats still in the discussion. But for now we new examples are meant to be seen as list.

**Comment by KamalakerDadi** [comment]
It is currently the case. Closing.
