### ISSUE TITLE
Put legends in plot_prob_atlas

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#1018]
![group_zmaps](https://cloud.githubusercontent.com/assets/634068/13346789/1dd4c692-dc69-11e5-9d35-21f605ef9a7e.png)

In the figure generated by `plot_prob_atlas`, It would be nice to know which color corresponds to which of the input 3D maps. This could be done on a legend plotted on a separate figure (and then merged ?), so as not to mess up the main figure.

**Comment by arthurmensch** [comment]
Just a colorbar beside with index numbers would be great. Actually I could
work on this.
Le 26 févr. 2016 09:13, "DOHMATOB Elvis" <notifications@github.com> a
écrit :

**Comment by dohmatob** [comment]
On Fri, Feb 26, 2016 at 9:17 AM, Arthur Mensch <notifications@github.com>
wrote:

> Just a colorbar beside with index numbers would be great.

This would be already much better than what we have, but I was thinking of
putting user-supplied labels.

> Actually I could
> work on this.
> Le 26 févr. 2016 09:13, "DOHMATOB Elvis" <notifications@github.com> a
> écrit :
>
> > [image: group_zmaps]
> > <
> https://cloud.githubusercontent.com/assets/634068/13346789/1dd4c692-dc69-11e5-9d35-21f605ef9a7e.png
> >
> >
> > In the figure generated by plot_prob_atlas, It would be nice to know
> > which color corresponds to which of the input 3D maps. This could be done
> > on a separate figure (and then merged ?), so as not to mess up the main
> > figure.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nilearn/nilearn/issues/1018>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/issues/1018#issuecomment-189157592>.
>



-- 
Elvis Dohmatob,
*sent from my  potato...*
http://dohmatob.blogspot.fr/, https://team.inria.fr/parietal/elvis/,
https://github.com/dohmatob

**Comment by arthurmensch** [comment]
Thanks Elvis for putting all the available tags to this issue, I am on it

**Comment by KamalakerDadi** [comment]
Closing this one. Having a colorbar with index numbers is addressed in #1026
