### ISSUE TITLE
add_sphere for slicers

### ISSUE THREAD

**Issue by fliem** [nilearn/nilearn#1019]
This came up in a conversation with @GaelVaroquaux at Brainhack Paris, 2016.

Would it be possible to add an add_sphere functionality to slicers? This could be used e.g. to overlay a seed sphere on top of a stats map (e.g., for seed-based correlation).

**Comment by AlexandreAbraham** [comment]
Hi fliem,

This is already in the pipeline (even though I can't find the related issue right now). We will add an `add_markers` functions that will displays markers of any shape (round, squares...) and of any color/size.

Would that suit your needs? It's just 5 lines of code away, maybe we can hack it now.

**Comment by fliem** [comment]
Sounds good. I am in the middle module.

**Comment by AlexandreAbraham** [comment]
@KamalakerDadi do you have time for that?

**Comment by fliem** [comment]
@AlexandreAbraham I already mentioned this in #1024, but forgot about it:

> A thing that's not too pretty yet, is that add_marker takes marker_size in points. Is there a way to give this in mm (as the MaskerSphere is also defined in mm)
