### ISSUE TITLE
automatically list clusters centers

### ISSUE THREAD

**Issue by fliem** [nilearn/nilearn#1020]
This came up in a conversation with @GaelVaroquaux at Brainhack Paris, 2016.

Would it be possible to identify clusters on a thresholded stats map and then automatically plot n_clusters plots with cut_coords at the center of each cluster?

**Comment by AlexandreAbraham** [comment]
For the moment, you can use `RegionExtraction` and `plot_stat_map` after it.

**Comment by GaelVaroquaux** [comment]
> For the moment, you can use RegionExtraction and plot_stat_map after it.

I think that the functionality wanted is more like find_xyz_coords:
return a list of coordinates. It's closer to finding peaks.

**Comment by crowledj** [comment]
I can tentatively have a look into this with possible assignment...? i must have a look through the library first...

**Comment by GaelVaroquaux** [comment]
@crowledj : that would be really great. Thank you very much!

**Comment by KamalakerDadi** [comment]
@crowledj May be this could help in getting started
https://github.com/nilearn/nilearn/pull/664/files

**Comment by tsalo** [comment]
Now that `nistats` has been merged into `nilearn`, I believe that [nilearn.reporting.glm_reporter.make_glm_report()](https://github.com/nilearn/nilearn/blob/b36df65af7cb9926f5e4abc9ba3787353c90c349/nilearn/reporting/glm_reporter.py#L45) does what is requested.

**Comment by bthirion** [comment]
Indeed (thx !). Closing
