### ISSUE TITLE
signal.clean t_r default value

### ISSUE THREAD

**Issue by fliem** [nilearn/nilearn#1021]
This came up in a conversation with @GaelVaroquaux at Brainhack Paris, 2016.

It seems that in the example http://nilearn.github.io/auto_examples/03_connectivity/plot_adhd_spheres.html#sphx-glr-auto-examples-03-connectivity-plot-adhd-spheres-py

the t_r is set to 2.5 seconds at masking. The time series’ header says tr = 2.0 s. Is the header wrong, or the example?

More generally, signal.clean has a t_r default value of 2.5. It would be more intuitive for the default to be None, and if no t_r is provided, it is fetched from the header. 
@GaelVaroquaux’s point on this: since the header info is often wrong, it would be best to set the default to None, and in the  case of bandpass filtering without explicitly providing a t_r raise an error and print the header t_r with a word of caution that the header info might be wrong.

**Comment by AlexandreAbraham** [comment]
+1, I've already raised this problem in the past.

**Comment by sahmed95** [comment]
If no t_r is provided by user, the script crashes rather than setting of default value of 2.5
```python
from nilearn import datasets
adhd_dataset = datasets.fetch_adhd(n_subjects=1)

from nilearn import input_data
masker = input_data.NiftiSpheresMasker(
    dmn_coords, radius=8,
    detrend=True, standardize=True,
    low_pass=0.1, high_pass=0.01,
    memory='nilearn_cache', memory_level=1, verbose=2)

func_filename = adhd_dataset.func[0]
confound_filename = adhd_dataset.confounds[0]
print (confound_filename)
time_series = masker.fit_transform(func_filename,
                                   confounds=[confound_filename])
Error
```dev/nilearn/nilearn/signal.py in clean(signals, sessions, detrend, standardize, confounds, low_pass, high_pass, t_r)
    501 
    502     if low_pass is not None or high_pass is not None:
--> 503         signals = butterworth(signals, sampling_rate=1. / t_r,
    504                               low_pass=low_pass, high_pass=high_pass)
    505 

TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```
Also, how do I find the t_r value from the header? New to this so I tried
```python 
import nibabel as nib
filename = '/nilearn_data/filtered_func_data.nii.gz'
img = nib.load(filename)
hdr = img.header
print (hdr) 
```
But there is no time series parameter in the header. Is it anything to do with confounds?

**Comment by fliem** [comment]
The TR can be found in hdr['pixdim'][4]
(see http://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/pixdim.html <http://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/pixdim.html>)

**Comment by sahmed95** [comment]
Thanks. On it. 
> since the header info is often wrong, it would be best to set the default to None.

So default t_r in signal.clean should be None instead of 2.5 as it is now.

>  in the case of bandpass filtering without explicitly providing a t_r raise an error and print the header t_r with a word of caution that the header info might be wrong.

 Can we instead raise a warning and the t_r is attempted to be fetched from the header with the value of the header t_r displayed? Alternative: Set t_r value as 2.5 with a warning if user doesn't give the value or header doesn't contain the value of t_r. 
@AlexandreAbraham  @GaelVaroquaux As I mentioned, if no t_r is provided by the script crashes and if 2.5 is an acceptable default value then we can set it to that instead of a crash, with a warning ofcourse?

**Comment by fliem** [comment]
> As I mentioned, if no t_r is provided by user the script crashes and if 2.5 is an acceptable default value then we can set it to that instead of a crash, with a warning ofcourse?
TR is depending on how the data was acquired, and varies between experiments. A default value of None to me makes more sense than a default of 2.5 sec.

**Comment by sahmed95** [comment]
Ok, got it. Thanks

**Comment by banilo** [comment]
On general basis, the information in the nifti header is neglected in neuroimaging, unfortunately.

**Comment by GaelVaroquaux** [comment]
To recap on this issue (I am having a hard time understanding where the discussion is going):

- signals.clean should have a default of None (actually, t_r should always default to None) https://github.com/nilearn/nilearn/blob/master/nilearn/signal.py#L347

- When t_r is None and we are asking for filtering, we should raise an error (probably in filter_and_extract https://github.com/nilearn/nilearn/blob/master/nilearn/input_data/base_masker.py#L24) and inspect the nifti image header to suggest a value.

**Comment by bthirion** [comment]
But then, shouldn't you raise a warning rather than an error ?

**Comment by sahmed95** [comment]
How can I test this in test_signal.py. I have checked it by running an example without specifying t_r and I get 
```python
nilearn/nilearn/signal.py in clean(signals, sessions, detrend, standardize, confounds, low_pass, high_pass, t_r)
    501 
    502     if low_pass is not None or high_pass is not None:
--> 503         signals = butterworth(signals, sampling_rate=1. / t_r,
    504                               low_pass=low_pass, high_pass=high_pass)
    505 

TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'

```
@fliem @GaelVaroquaux 

Also for checking in filter_and_extract should it be something like this ?
```python
    if parameters['t_r'] is None:
        raise ValueError('Repetition time (t_r) value not given'
                        'Value of t_r from img header is %s'
                        imgs.get_header()['pixdim'][4])
```

**Comment by sahmed95** [comment]
@GaelVaroquaux @fliem The build is failing and there is an error when I am setting default t_r=None. I haven't written the test case but in my Notebook, if I don't supply the t_r, I get the same error.
```python
/home/travis/miniconda2/envs/testenv/lib/python2.6/site-packages/nilearn-0.2.3-py2.6.egg/nilearn/signal.py", line 503, in clean
    signals = butterworth(signals, sampling_rate=1. / t_r,
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```
Check 9e1338b for details. I have opened that PR for this issue.
