### ISSUE TITLE
implement view_type param in plot_roi, in the spirit of plot_prob_atlas ?

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#1025]
implement view_type parameter in plot_roi, in the spirit of plot_prob_atlas ?

**Comment by GaelVaroquaux** [comment]
> implement view_type parameter in plot_roi, in the spirit of plot_prob_atlas ?

Not opposed, but that's going to be a fair amount of work, given that the
logic on plot_roi is very different from the logic of plot_prob_atlas.
Are you volonteering to do the work?

**Comment by dohmatob** [comment]
On Fri, Feb 26, 2016 at 4:43 PM, Gael Varoquaux <notifications@github.com>
wrote:

> > implement view_type parameter in plot_roi, in the spirit of
> plot_prob_atlas ?
>
> Not opposed, but that's going to be a fair amount of work, given that the
> logic on plot_roi is very different from the logic of plot_prob_atlas.
>
 Ah, i though the logic was more or less thesame.

> Are you volonteering to do the work?
>
No.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/issues/1025#issuecomment-189328721>.
>



-- 
Elvis Dohmatob,
*sent from my  potato...*
http://dohmatob.blogspot.fr/, https://team.inria.fr/parietal/elvis/,
https://github.com/dohmatob

**Comment by AlexandreAbraham** [comment]
Note that feeding ROIs to plot_prob_atlas is quite easy.

**Comment by banilo** [comment]
> implement view_type parameter in plot_roi, in the spirit of plot_prob_atlas ?

+1 for the idea
