### ISSUE TITLE
Running tests on circleCI

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1029]
From the logs
https://circleci.com/gh/nilearn/nilearn/1333
it seems that we are running the unit tests on circleCI. I think that we should skip them: they are already ran on travis, and I would really like the circleCI total time to be smaller.

**Comment by sahmed95** [comment]
Can a override in the test inside the circle.yml file do the trick? 

```code
test:
  override:
    - echo "test"
```
Another option is to include

**Comment by GaelVaroquaux** [comment]
@sahmed95 : possibly. Do you want to do a pull request to try? CircleCI will run that PR and we should see.

**Comment by sahmed95** [comment]
I will do a PR and try now. But I was just wondering why you have both travis and circleCI ? Isn't one CI sufficient ?

**Comment by GaelVaroquaux** [comment]
> But I was just wondering why you have both travis and circleCI ? Isn't
> one CI sufficient ?

CircleCI has much more horse power, both in terms of storage and length
of the runs. We use it to generate/test docs. Travis is for unit testing.

**Comment by sahmed95** [comment]
Showing an estimate Estimated: 1:38:26. How much time did a circleCI test take before? Also, from the circleCI docs : "CircleCI supports the use of override, pre, and/or post in the test section. All test commands will run, even if one fails" If there are nosetest commands by default in the pre or post sections, then those should be ignored too I guess ?

**Comment by GaelVaroquaux** [comment]
> Showing an estimate Estimated: 1:38:26. How much time did a circleCI test take
> before?

This is irrelevant, I believe: the estimate is based only on the past
runs.

> Also, from the circleCI docs : "CircleCI supports the use of override,
> pre, and/or post in the test section. All test commands will run, even
> if one fails" If there are nosetest commands by default in the pre or
> post sections, then those should be ignored too I guess ?

I guess. I don't know. I didn't have time to look at this so far.

**Comment by sahmed95** [comment]
I will take a look then and compare. But I how would I know if it is taking lesser time than before? Even for the current override statement.
