### ISSUE TITLE
CircleCI: share nilearn_cache across example folders

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1030]
I suggest to create one nilearn_cache directory in examples, and then, in each subfolder of examples, do a simlink to that directory.

The logic is that, hopefully, there are some common operations across the examples (because we tend to use similar datasets, and because we should as much as possible use default options), hence this should lead to speeding up the runtime of the examples.

**Comment by lesteve** [comment]
Once you do that you could also add the nilearn_cache folder in the CircleCI cache. I think this is likely to speed-up running the examples significatively. The problem may be that the nilearn_cache grows with time and I am not sure what the size limit is for the CircleCI cache.

**Comment by GaelVaroquaux** [comment]
> The problem may be that the nilearn_cache grows with time

You're going to fix that, though :).

> and I am not sure what the size limit is for the CircleCI cache.

I think that with the datasets we are very close to that limit. It's
actually a problem.

**Comment by aabadie** [comment]
> > and I am not sure what the size limit is for the CircleCI cache.
> 
> I think that with the datasets we are very close to that limit. It's
> actually a problem.

IIRC, we aleady had to decrease the ADHD number of subjects from 40 to 30 because we were reaching the circle ci cache limit.

**Comment by banilo** [comment]
> I suggest to create one nilearn_cache directory in examples, and then, in each subfolder of examples, do a simlink to that directory.

Perhaps I am missing something. But why not set a default nilearn caching directory somewhere in the home directory for all applications of nilearn software by that user? This would also cover the examples.

Having to set/consider that argument may also be a show stopper for newcomers.

**Comment by GaelVaroquaux** [comment]
> Perhaps I am missing something. But why not set a default nilearn caching
> directory somewhere in the home directory for all applications of nilearn
> software by that user?

I really don't like creating files where users don't expect them.

> Having to set/consider that argument may also be a show stopper for newcomers.

The nilearn_cache folders get big in a non-controled way. We cannot
implicitely create them. I would like them to be always explicit.

**Comment by GaelVaroquaux** [comment]
Fixed. Closing.
