### ISSUE TITLE
Masker does not properly check the shape of the data

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#1041]
Code:
```python
from nilearn.input_data import NiftiMasker
import nibabel
import numpy as np

masker = NiftiMasker(mask_img=nibabel.Nifti1Image(np.ones((10, 5, 5), dtype=int).astype(int), np.eye(4)))
masker.fit()
masker.transform(nibabel.Nifti1Image(np.random.random((20, 5, 5, 12)), np.eye(4))).shape
```
This works and outputs `(12,250)` but masking data with a mask having a different shape should be prohibited.

**Comment by GaelVaroquaux** [comment]
> This works and outputs (12,250) but masking data with a mask having a
> different shape should be prohibited.

Why? What matters is that the data are in the same brain space.

**Comment by AlexandreAbraham** [comment]
Okay, my formulation was clumsy but I thought that having a mask that does not cover the data may be a bug but, in the case of extracting a ROI, it makes sense.
