### ISSUE TITLE
row/col flipped in example

### ISSUE THREAD

**Issue by rschmaelzle** [nilearn/nilearn#1044]
HI all,
is it possible that in https://github.com/nilearn/nilearn/blob/master/examples/01_plotting/plot_visualization.py, line 54, the row and cols got flipped.... 
Best, Ralf

**Comment by GaelVaroquaux** [comment]
> is it possible that in https://github.com/nilearn/nilearn/blob/master/examples/
> 01_plotting/plot_visualization.py, line 54, the row and cols got flipped....

Hey! I think that you are right!

Could another pair of eyes confirm, please?

**Comment by AlexandreAbraham** [comment]
I confirm.

**Comment by AlexandreAbraham** [comment]
Fixed in 01eee99235208fd0162c46e1e481bbed9fb8ff03
