### ISSUE TITLE
plot_prob_atlas: Different view_types tell very different stories

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#1047]
![contours](https://cloud.githubusercontent.com/assets/634068/13518308/9161d8bc-e1cc-11e5-946a-98a062539589.png)
![filled_contours](https://cloud.githubusercontent.com/assets/634068/13518311/94a8de3a-e1cc-11e5-9fb3-c30504044aff.png)
![continuous](https://cloud.githubusercontent.com/assets/634068/13518313/97cccb30-e1cc-11e5-8d57-d9a020924f84.png)

Ideally, the top 2 plots should be contours of the the bottom-most one, but it looks like the implementations we have use completely different heuristics (disclaimer: i haven't yet looked at the code).

**Comment by AlexandreAbraham** [comment]
This is on purpose, there is a thresolding by défaut.

**Comment by dohmatob** [comment]
Is this "purpose" made explicit anywhere ? This looks ugly.

**Comment by KamalakerDadi** [comment]
Its easy for me to *test* whats going wrong if you provide your atlas and code. Could you provide ?

**Comment by GaelVaroquaux** [comment]
> Is this "purpose" made explicit anywhere ? This looks ugly.

Finding default that work well on all inputs is hard. You can always
override defaults. But we tuned them on many maps, as you can see here:
http://nilearn.github.io/auto_examples/01_plotting/plot_prob_atlas.html#sphx-glr-auto-examples-01-plotting-plot-prob-atlas-py

The challenge is to have a good behavior that looks OK for most input,
and not that looks great for one input! Remember that you can give an
explicit value for "threshold", and hence control the visualization you
achieve finely.

**Comment by AlexandreAbraham** [comment]
The code is:
```python
    if threshold is None:
        # it will use default percentage,
        # strategy is to avoid maximum overlaps as possible
        if view_type == 'contours':
            correction_factor = 1
        elif view_type == 'filled_contours':
            correction_factor = .8
        else:
            correction_factor = .5
        threshold = "%f%%" % (100 * (1 - .2 * correction_factor / n_maps))
```

> You can always override defaults.

No, you cannot here. Thresholding cannot be deactivated unless you give something like `np.neginf`.

**Comment by KamalakerDadi** [comment]
>Remember that you can give an explicit value for "threshold", and hence control the visualization you achieve finely.

Yes, you have choice to provide list of ```threshold```s for each map if you want ```contours``` and ```filled_contours``` as your view_type.

**Comment by GaelVaroquaux** [comment]
> Yes, you have choice to provide list of thresholds for each map if you want contours and filled_contours as your view_type.

I find that the docstring describes this quite well. Can it be improved?

**Comment by AlexandreAbraham** [comment]
> I find that the docstring describes this quite well. Can it be improved?

Describe the heuristics in the docstring. Set threshold as `auto` by default and allow deactivation by using `None` (for the moment, `None` = `auto`).

Personnaly, well, I don't use this function but a very similar one that has no thresholding.

**Comment by KamalakerDadi** [comment]
> I find that the docstring describes this quite well. Can it be improved?

I think yes it should be improved. I will try to take care of this doc improvement.

**Comment by GaelVaroquaux** [comment]
> Describe the heuristics in the docstring.

As long as the description is not longer than the code. Sometime, reading
the source is a good option.

> Set threshold as auto by default and allow deactivation by using None
> (for the moment, None = auto).

Maybe (see below).

> Personnaly, well, I don't use this function but a very similar one that has no
> thresholding.

What does not thresholding means for filled_contours, or contours?

**Comment by AlexandreAbraham** [comment]
> What does not thresholding means for filled_contours, or contours?

Well, it means that I don't apply thresholding other than to remove numerical noise.

**Comment by KamalakerDadi** [comment]
> Personnaly, well, I don't use this function but a very similar one that has no thresholding.

This concept works for continuous display I believe. But, I really don't know how to control levels without giving threshold (more or less acts like choosing levels) for contours and filled.

**Comment by AlexandreAbraham** [comment]
Well, the regions are usually surrounded by a background value that is 0 or some numerical noise.

**Comment by GaelVaroquaux** [comment]
No. Only for sparse models, which is not what most people run in the wider community.

**Comment by AlexandreAbraham** [comment]
> No. Only for sparse models, which is not what most people run in the wider community.

I don't say that we should use that by default, I just answer the question about how to plot contours with no thresholding.
