### ISSUE TITLE
Fit method of estimators (decomposers, decoders, etc.) should accept filename wildcards

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#1048]
Since `check_niimg_4d` and co. now do globbing, it should be easy to have estimators accept filename wildcards.

For example, we should allow the following usage:

```
canica.fit("/home/mrbumble/nilearn_data/spm_auditory/sub001/fM00223/fM00223_*.img")
```

**Comment by GaelVaroquaux** [comment]
> Since check_niimg_4d and co. now do globbing, it should be easy to have
> estimators accept filename wildcards.

Don't they?

**Comment by AlexandreAbraham** [comment]
Probably not, they différent codepaths for efficiency.

**Comment by GaelVaroquaux** [comment]
@aabadie, do you want to have a look at that?

**Comment by dohmatob** [comment]
Nope.

```
ValueError: [MultiNiftiMasker.fit] For multiple processing, you should provide a list of data (e.g. 

Nifti1Image objects or 
filenames).'/home/elvis/nilearn_data/spm_auditory/sub001/fM00223/fM00223_0*.img' is an invalid 

input
```

**Comment by dohmatob** [comment]
Any progress ?

**Comment by AlexandreAbraham** [comment]
> Any progress ?

Seems like more people are reporting this issue. This item increased by 1 in my todo-list.
