### ISSUE TITLE
expandpath should be applied to the "memory" argument

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1051]
The CacheMixin should be modified so that when the argument is a basestring, it is expanded, with the same logic to turn this off as the globbing that we already have.

**Comment by aabadie** [comment]
@GaelVaroquaux, maybe I can work on that ?

**Comment by GaelVaroquaux** [comment]
Sounds great!  Thanks

**Comment by AlexandreAbraham** [comment]
To be complete, this should actually be applied to all paths in nilearn.

**Comment by aabadie** [comment]
Just had a look at the code and I have a question: when the argument is a basestring, globbing may return a list a matching paths. Does the CacheMixin be modified to manage a list of Memories in this case ?

**Comment by GaelVaroquaux** [comment]
> basestring, globbing may return a list a matching paths.

We don't want globbing. Only exandpath.
