### ISSUE TITLE
BaseDecomposition.score should accept a per_component parameter

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#1052]
`BaseDecomposition.score` should accept `per_component` param, and have a default value `False`. At the moment it's hard-coded.

**Comment by GaelVaroquaux** [comment]
> BaseDecomposition, MultiPCA, and related estimators should accept
> per_component param.

What does "per_component" mean?

**Comment by dohmatob** [comment]
Typo. I meant BD.score. Updated.

On Wed, Mar 9, 2016 at 4:12 PM, Gael Varoquaux <notifications@github.com>
wrote:

> > BaseDecomposition, MultiPCA, and related estimators should accept
> > per_component param.
>
> What does "per_component" mean?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/issues/1052#issuecomment-194338110>.
>



-- 
Elvis Dohmatob,
*sent from my  potato...*
http://dohmatob.blogspot.fr/, https://team.inria.fr/parietal/elvis/,
https://github.com/dohmatob

**Comment by GaelVaroquaux** [comment]
> Typo. I meant BD.score. Updated.

I still don't understand what you mean.

**Comment by dohmatob** [comment]
BaseDecomposition, MultiPCA, etc. have a score method (based on explained var I guess). We should provide the possibility of computing this component wise.

**Comment by dohmatob** [comment]
```
    def score(self, imgs, confounds=None):
        """Score function based on explained variance on imgs.

        Should only be used by DecompositionEstimator derived classes

        Parameters
        ----------
        imgs: iterable of Niimg-like objects
            See http://nilearn.github.io/manipulating_visualizing/manipulating_images.html#niimg.
            Data to be scored

        confounds: CSV file path or 2D matrix
            This parameter is passed to nilearn.signal.clean. Please see the
            related documentation for details

        Returns
        -------
        score: float,
            Holds the score for each subjects. Score is two dimensional
            if per_component is True. First dimension
            is squeezed if the number of subjects is one
        """
        data = mask_and_reduce(self.masker_, imgs, confounds,
                               reduction_ratio=1.)
        return self._raw_score(data, per_component=False)
```

Maybe it's better with some code...

**Comment by KamalakerDadi** [comment]
Closing with #2577
