### ISSUE TITLE
extra spaces in somes labels and networks of MSDL atlas

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1053]
The csv file has extra-spaces
```Python
from nilearn import datasets
msdl = datasets.fetch_atlas_msdl()
```
for instance `msdl.networks[-10]` is  `'    Language'` and  `msdl.labels[-5])` is `'  L Ins'`

**Comment by banilo** [comment]
Good catch. We should probably get that fixed.

**Comment by KamalakerDadi** [comment]
I am trying to figure out how to change csv file corrected for white spaces. How can I ?

**Comment by GaelVaroquaux** [comment]
> I am trying to figure out how to change csv file corrected for white
> spaces. How can I ?

What is the question: do you want to change the file that is hosted on
the website?

**Comment by KamalakerDadi** [comment]
In general, How can I solve this issue ?

>What is the question: do you want to change the file that is hosted on the website?

Yes, Can I ?

**Comment by GaelVaroquaux** [comment]
>     What is the question: do you want to change the file that is hosted
>     on the website?

> Yes, Can I ?

No, you can upload a new one, but not override the present one.

**Comment by KamalakerDadi** [comment]
>No, you can upload a new one

Ok. I have managed to upload in nitrc. PR ?
