### ISSUE TITLE
Collapsable Table of Content on the side (javascript, HTML, style)

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1071]
We already have a TOC (table of content) on the side of the page that stick to the page when scrolling. It currently displays two levels of depth of the page's TOC, however for long pages this is too long (see
http://nilearn.github.io/manipulating_visualizing/manipulating_images.html ). 

An option (eg used in scipy-lectures) is the expandable TOC, that expands one level to the current section:
http://www.scipy-lectures.org/intro/matplotlib/matplotlib.html
It's much more readable.

Other option: grab the full CSS and theme from scipy-lectures, which is overall much better (eg displays better on small devices, less cramped with more whitespace which relaxes the reading). It will however require adapting details like the color scheme. What do people think?

**Comment by banilo** [comment]
...likes CSS.

**Comment by GaelVaroquaux** [comment]
> ...likes CSS.

What do you mean?

**Comment by bthirion** [comment]
The expandable TOC is probably simpler to implement. I'd go for it, but this is not a strong opinion.

**Comment by GaelVaroquaux** [comment]
> The expandable TOC is probably simpler to implement. I'd go for it, but
> this is not a strong opinion.

But there are many more improvement in the scikit-learn theme. So the
danger is to backport them one after the other.

**Comment by bthirion** [comment]
Yes, a global refactoring might be a good solution. Just need to find a volunteer ;-)

**Comment by GaelVaroquaux** [comment]
I also want to make sure that people have the same feeling about the
scipy-lectures theme as me: ie they like it.

**Comment by AlexandreAbraham** [comment]
> The expandable TOC is probably simpler to implement.

It should be as simple as defining the non-active `li` parent node as hidden by default.

> I also want to make sure that people have the same feeling about the scipy-lectures theme as me: ie they like it.

I see no big difference between the 2. One annoyance with the scipy lecture note website is the size of the fonts: on my laptop they look huge, on my phone, they look OK, except the ones in frames that at are so small that I need to zoom in. nilearn website looks OK on both devices. The only problem is that big images are sometimes out of the frame on my phone, which is not a big deal IMHO.

**Comment by bthirion** [comment]
I also find the scipy lectures notes font a bit large on my laptop.

**Comment by aabadie** [comment]
The given link is broken in the description. I think it should be http://nilearn.github.io/manipulating_images/manipulating_images.html
