### ISSUE TITLE
Turn the "creating an ROI mask manually" doc section to a notebook-like example

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1072]
The following section of the narrative documentation
http://nilearn.github.io/manipulating_visualizing/manipulating_images.html#image-operations-creating-a-roi-mask-manually
should be fully integrated in the corresponding example:
manipulating_visualizing/plot_roi_extraction.html
as a notebook-like example.

Then we remove it from the narrative documentation, and simply add a paragraph describing the big steps in a few words (with links to the useful functions) and pointing to it.

**Comment by lesteve** [comment]
You may want to edit the title to make it more meaningful :)

**Comment by GaelVaroquaux** [comment]
Title changed.
