### ISSUE TITLE
nilearn in nipype

### ISSUE THREAD

**Issue by alexsavio** [nilearn/nilearn#1088]
Hi,
I have done a few nipype interface nodes that use nilearn and have plans to create more.
I would like to push these to nipype source in a month or two, when I have them tested and repeatedly used. 
I was wondering if you have any concern/comment or if you know of anyone working on this to join efforts.
One example is here: https://github.com/Neurita/pypes/blob/master/pypes/postproc/decompose.py
Thanks!

**Comment by GaelVaroquaux** [comment]
No opposition on this, but it should be clearly said the natural way of using nilearn is via its Python API. Nipype is useful for combining multiple tools, but it comes with inherent clunckiness due to that. Nilearn strives to make things simpler via its API.

**Comment by alexsavio** [comment]
I agree with you. I think the most valuable contribution would be adding the plotting sub-module to plot internal pipeline results, for me they are quite handy.

**Comment by GaelVaroquaux** [comment]
> I think the most valuable contribution would be adding the plotting
> sub-module to plot internal pipeline results,

Agreed. When I was using nipype heavily, I was mixing it a lot with
plotting (a bit like what's currently in pypreprocess)

**Comment by GaelVaroquaux** [comment]
Closing this issue, as closing the issue does not prevent discussion.
