### ISSUE TITLE
Make a nilearn logo with a tag line

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1091]
For promotional reasons (ie tweets), it would be great to have a version of our nilearn with a tagline below it saying "Easier machine learning for neuroimaging". This should be done by first creating a new version of our SVG (https://github.com/nilearn/nilearn/blob/master/doc/logos/scikit-learn-logo.svg) with the tagline, and then exporting it to PNG.

**Comment by AlexandreAbraham** [comment]
Somehting like this?
![nilearn_logo_tagline](https://cloud.githubusercontent.com/assets/1647301/14736125/4cbb865c-0875-11e6-865b-319241809107.png)

**Comment by GaelVaroquaux** [comment]
Totally! Dude you're fast.

**Comment by AlexandreAbraham** [comment]
Give me 2 minutes to polish it because it breaks some basic design rules like "never more than 2 fonts in a logo".

**Comment by GaelVaroquaux** [comment]
> "never more than 2 fonts in a logo".

+1

**Comment by AlexandreAbraham** [comment]
I don't have the cursive "learn" font so I went for the Helvetica used for the "ni" (well, not Helvetica exactly but its free counterpart "Liberation"). Also added some colors.

![nilearn_logo_tagline](https://cloud.githubusercontent.com/assets/1647301/14736659/85e90906-0878-11e6-8861-0d358b0da3dd.png)

**Comment by GaelVaroquaux** [comment]
Better for the fonts, but I would stick to black for the colors.

**Comment by AlexandreAbraham** [comment]
![nilearn_logo_tagline](https://cloud.githubusercontent.com/assets/1647301/14736819/2a637c6e-0879-11e6-9ffa-50718858fe52.png)

**Comment by GaelVaroquaux** [comment]
:+1: 

I am loosing connection (boarding my plane), so this counts as a :+1: for a PR. Thanks!

**Comment by AlexandreAbraham** [comment]
Pushed in 2fc69457257c65b7210b6c65563a783a18017c66
