### ISSUE TITLE
Use of an atlas to extract signals. Add feature to NiftiLabelsMasker to achieve something like a NiftiAtlasMasker?

### ISSUE THREAD

**Issue by MartinPerez** [nilearn/nilearn#1092]
I find myself constantly segmenting atlases into lists of masks. Recently I had to extract "again" from a 3d niimg multiple ROIs given by an atlas (3d niimg with multiple labels) and thought that NiftiLabelsMasker could do the job. But NiftiLabelsMasker gives its own summary statistic and I needed all the features to do my own statistic on them.

Do you think adding this feature to NiftiLabelsMasker would be useful to others, so it could also work like a NiftiAtlasMasker? it would be simple to implement and I can take care of it.

**Comment by banilo** [comment]
I am not sure what you mean. Do you mean, for instance, a resting-state network, into masks for its compact network nodes? If yes, this is also something that I am missing in the nilearn API right now. Even if it can easily be done with scipy, it might be a feature worthy of consideration.

**Comment by AlexandreAbraham** [comment]
What I understand is that, instead of taking the mean of each region, you would like to take the PCA or something else? If so, it has already been suggested, a good interface has already been proposed but there was no consensus to integrate it.

**Comment by MartinPerez** [comment]
Yes @AlexandreAbraham , I mean exactly that. Or at least to return one list of voxels per ROI, so you can do what you want with it afterwards.

**Comment by AlexandreAbraham** [comment]
Returning a list of voxels is against the Transformer interface and it would be non efficient. The evoked option was to add an "aggregator" parameter that would be "mean" by default but could be replaced by any function. A bit like the "scorer" in scikit-learn. You would then be able to replace it with median, pca, or whatever you want.

**Comment by MartinPerez** [comment]
well that would be great

**Comment by GaelVaroquaux** [comment]
+1 for that approach.

**Comment by alexsavio** [comment]
I mentioned this some months ago in #841, there is an interesting discussion about the work involved. Now the code is in the `img_to_signals_labels` function in `nilearn.regions.signal_extractor`. I didn't have time to do it yet.

**Comment by banilo** [comment]
> least to return one list of voxels per ROI, so you can do what you want with it afterwards.

This can be done by the ``NiftiMasker`` already.

**Comment by MartinPerez** [comment]
@banilo you mean I can pass an atlas to niftimasker as the mask and provide the label id when masking some other image?

**Comment by banilo** [comment]
> you mean I can pass an atlas to niftimasker as the mask and provide the label ids when masking some other image? I did not get that from the docs.

Year, if you go region-by-region with one pass over your data using NiftiMasker, it will exactly give the regin-wise set of voxel-values. And then you can apply a custom pooling function on these selected features.

**Comment by bthirion** [comment]
Stalled.
