### ISSUE TITLE
Coordinates of Default Mode Network 

### ISSUE THREAD

**Issue by cinvro** [nilearn/nilearn#1093]
In this [example](https://nilearn.github.io/auto_examples/03_connectivity/plot_adhd_spheres.html) on nil earn website, it says the coordinates of Default Mode Network are: [(0, -52, 18), (-46, -68, 32), (46, -68, 32), (0, 50, -5)]. 

I wonder where are these coordinates coming from? In what atlas/template? 

It seems that it's not the MNI coordinates according to [this paper](http://www.nature.com/ncomms/journal/v4/n1/fig_tab/ncomms2388_T1.html).

**Comment by rschmaelzle** [comment]
i am not the developer, but the coordinates are within the DMN (e.g. [http://neurosynth.org/locations/0_-52_18_6/]).  the example uses adhd200 data from the fcon_1000 project - these should be in MNI space. hope that helps.

**Comment by KamalakerDadi** [comment]
After looking back into nilearn history, "The coordinates of the spheres have been taken from a meta-analysis on neurosynth website".

**Comment by KamalakerDadi** [comment]
@cinvro Do you think this issue can be closed or you still waiting for more info about coordinates ?

**Comment by cinvro** [comment]
We can close it. Thx.

Best,
Xinyue Liu

On May 30, 2016 at 4:50:32 PM, KamalakerDadi (notifications@github.com) wrote:

@cinvro Do you think this issue can be closed or you still waiting for more info about coordinates ?
