### ISSUE TITLE
Issue with matplotlib dev version and plot_brain_schematics

### ISSUE THREAD

**Issue by robbisg** [nilearn/nilearn#1094]
Hi all,

I used the `plotting.plot_connectome` function with `black_bg=True`, but when figure is displayed I could not see the brain contour. I use matplotlib 1.5 github version.
After digging out in the nilearn code I found that in the `glass_brain.py` file the first line of code
`black_bg = ax.get_axis_bgcolor() == 'k'` is always `False` because `ax.get_axis_bgcolor()` gives the rgba tuple instead of the color string.
I changed the line to` black_bg = ax.get_axis_bgcolor() == colors.colorConverter.to_rgba('k')` to have the figure correctly saved and showed.
I think it's a matplotlib version problem, but maybe I'm wrong!

**Comment by banilo** [comment]
Could you provide the wrong figure with the bad contours here for us to get an idea?

**Comment by robbisg** [comment]
This is an example!

![samatha_svr_c_1_connectome_feature_choices_x](https://cloud.githubusercontent.com/assets/695037/14956409/d6a4bc1e-107f-11e6-8bdf-814221692aeb.png)

**Comment by bthirion** [comment]
Could you issue a PR ?
Best,

Bertrand

**Comment by robbisg** [comment]
I hope I did it well!! ;)

**Comment by rschmaelzle** [comment]
sounds related to an issue I just ran into, but I'm not sure:
in plotting.plot_connectome, the alpha argument that is supposed to set the transparency of the brain schematics has no effect on my machine (matplotlib 1.5.0) - i.e. whether I give 0.01 or 0.99 - all looks the same.
Best, Ralf

**Comment by robbisg** [comment]
@rschmaelzle Yes, it is related! This is due to style changing in matplotlib, to use alpha and others kwargs with matplotlib 1.5.0, run the command `(mpl.style.use('classic'))`, it should fix these problems.

**Comment by lesteve** [comment]
It should be fixed in master now that #1095 has been merged.

**Comment by lesteve** [comment]
Closing, feel free to reopen if it doesn't fix your problem @rschmaelzle.

**Comment by GaelVaroquaux** [comment]
> It should be fixed in master now that #1095 has been merged.

Real cool. Great work everybody
