### ISSUE TITLE
Allow scalars in `math_img`

### ISSUE THREAD

**Issue by alexsavio** [nilearn/nilearn#1097]
What about allowing scalar input arguments as well as `img_like` in `math_img`?
I created an adapter for it and as far as I see it wouldn't make any harm to be actually inside `math_img`. IMO this would help doing function composition with this function.

I guess I could add some checks or change how I check for a scalar, but a simple version would be this:

```python
import numpy as np
from six import string_types

def math_img(formula, **imgs):
    """ Use nilearn.image.math_img. """
    from nilearn.image import math_img
    for name, arg in imgs.items():
        if isinstance(arg, string_types):
            continue

        if np.isscalar(arg):
            formula = formula.replace(name, str(arg))
            imgs.pop(name)

    return math_img(formula=formula, **imgs)
```

**Comment by GaelVaroquaux** [comment]
I am a bit worried that too much polymorphism leads to functions hard to
grasp and with horrible error message. In addition, I can see people
asking for more, once we allow scalars.

**Comment by alexsavio** [comment]
Ok, no problem. I was just asking. :)
