### ISSUE TITLE
Specify font size for plotting.plot_stat_map

### ISSUE THREAD

**Issue by TheChymera** [nilearn/nilearn#1107]
I am using [`plotting.plot_stat_map`](https://nilearn.github.io/modules/generated/nilearn.plotting.plot_stat_map.html#nilearn.plotting.plot_stat_map) to create some figures which I include in LaTeX presentations. I am doing this with pythontex, which automatically generates figures at the correct resolution and allows me to specify font sizes to match my document via [`matplotlibrc`](http://matplotlib.org/users/customizing.html).

Sadly this does not seem to affect the text size in the the aforementioned plotting function from nilearn. I assume this is because of some idiosyncrasy of the plotting which rasterizes the text behind the scenes. Do you know if this is the case? And more importantly, do you know how I can change the font size? Presentations have low resolution, so the text on my figures is disproportionally huge.

**Comment by lesteve** [comment]
I know nothing about pythontex, I am not sure I understand your question fully and I presume the problem you are describing is not specific to nilearn. Here is a work-around that should let you set the font size:

The display object you get back from the `plot_stat_map` call has a `title` method which you can pass the size into, so something like this should work:

```python

display = plot_stat_map(...)
display.title('Your title', size=30)
```

**Comment by TheChymera** [comment]
@lesteve I ask this question here because it is specific to nilearn - I have not yet encountered any other package for the plots of which matplotlibrc fails to take effect. 

```
display = plot_stat_map(...)
display.title('Your title', size=30)
```

this seems to add a *second* title on top of the one I pass to the plotting function. It's a bit of a hack, but ok...
However I am also (or rather especially) looking to change the font size of the color bar tick labels and the L/R labels. Any idea how I could do that?

**Comment by TheChymera** [comment]
Ok, `matplotlibrc` did not take effect n the colorbar labels, because I had forgotten to take another set of `matplotlibrc` settings out of the wrapper I wrote for `plot_stat_map`. so that works now.

Setting the title with:

```
display = plot_stat_map(...,title=False)
display.title('Your title', size=30)
``

works, and setting the annotation font size with

display = plot_stat_map(...annotate=False)
display.annotate(size=30)

Works as well. Now, before I call this completely solved. Is there any way to set these sizes in the function call, or tweak them via one of the many `matplotlibrc` parameters? It's weird to have to explicitly not set stuff first, just to then be able to set it correctly with a separate call....

**Comment by lesteve** [comment]
Basically nilearn has some default size for these things that completely ignore matplotlibrc. I am not sure whether it should care about matplotlibrc to be honest.

If I am following correctly, the general request seems to be more something like "how do I generate a nilearn plot that looks good for slides (looks like you care about title, L/R annotations and colorbar ticks mostly)"? Maybe @AlexandreAbraham @eickenberg @mrahim or @GaelVaroquaux have some suggestions about that.

**Comment by GaelVaroquaux** [comment]
> If I am following correctly, the general request seems to be more
> something like "how do I generate a nilearn plot that looks good for
> slides (looks like you care about title, L/R annotations and colorbar
> ticks mostly)"? Maybe @AlexandreAbraham @eickenberg @mrahim or
> @GaelVaroquaux have some suggestions about that.

Use the lower-level commands, as you are already doing. The high-level
functions cannot catter for all the usecases.

**Comment by TheChymera** [comment]
@GaelVaroquaux Actually in this case they could, since you could forward `**kwargs` to the base matplotlib commands you use for these elements (as you do for some of the others). This was probably just an oversight, but sadly I am still unfamiliar with the code and can't make time to fix it now.

For the time being, I wrote [a short wrapper](https://github.com/TheChymera/chyMRI/blob/master/plotting.py#L51-L75) to allow `nilearn.plotting.plot_stat_map` plots to scale ~properly.

@lesteve I can't see any reason why anything using matplotlib should disregard `matplotlibrc`. And it's not just about slides, but about making the figures look good at *any other* dpi except that of a "normal" monitor. HIDPI, poster, presentation, booklet, flyer, all these formats need different scaling, best handled via matplotlibrc.

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux Actually in this case they could, since you could forward
> **kwargs to the base matplotlib commands you use for these elements (as you do
> for some of the others).

There are forwarded to the imshow command.

> This was probably just an oversight,

It's not: routing the arguments to different underlying commands would be
incomprehensible, not to mention hard to implement. 

> @lesteve I can't see any reason why anything using matplotlib should
> disregard matplotlibrc. And it's not just about slides, but about
> making the figures look good at any other dpi except that of a "normal"
> monitor. HIDPI, poster, presentation, booklet, flyer, all these formats
> need different scaling, best handled via matplotlibrc.

Use svg/pdf output, and not changing figure size.

**Comment by seralouk** [comment]
Any way to change the `figsize` in `display = plotting.plot_stat_map(z_map, bg_img=ni_struct_img, threshold=3)` ??

**Comment by jeromedockes** [comment]
pass a previously created matplotlib Axes as the axes argument. For questions on how to use nilearn, prefer the neurostars forum with the tag "nilearn"
