### ISSUE TITLE
Coordinates of regions for a parcellation?

### ISSUE THREAD

**Issue by cinvro** [nilearn/nilearn#1111]
Does anyone have a chance to know the MNI coordinates for AAL atlas? 
Since the fetch_dataset_atlas_aal API returns no region_coords (MDSL has) for AAL atlas, so one cannot apply plotting.plot_connectome to visualize brain connectome in AAL atlas. 
Is there any alternative way to do so? 

I briefly searched the web, and I got [this](http://neuro.compute.dtu.dk/services/brededatabase/index_roi_tzouriomazoyer.html)
Is this the coordinates (the Mean coordinate in the bottom) for AAL atlas in MNI space?

**Comment by GaelVaroquaux** [comment]
IMHO, this question means that we need an example (with a good title, and links to it) that shows the use of find_cut_coords for this purpose.

Maybe, also, we should try to finish https://github.com/nilearn/nilearn/pull/664

PS: @cinvro : you shouldn' be using the AAL, it's crap

**Comment by cinvro** [comment]
@GaelVaroquaux  Thanks Gael. 
I am doing research project on fMRI data, can you tell me a little more details about what AAL is crap?

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux Thanks Gael. I am doing research project on fMRI data,
> can you tell me a little more details about what AAL is crap?

It was done manually on one subject. Hence it is a very rough mapping of
brain territories. If you look at it, you'll see that it has many
straight lines, which does not reflect at all anatomy.

**Comment by cinvro** [comment]
I see. But I am working on fMRI data extracted by masking AAL atlas, it is difficult to switch to other atlas. 
However, do you know any good alternatives?

**Comment by KamalakerDadi** [comment]
This should be fixed in PR #1602. Closing this one
