### ISSUE TITLE
Restructure the section 5 of the docs

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1115]
Section 5 of the docs is split as follows:

<pre>
5. Image manipulation
5.1. Data preparation: data loading and signal extraction
5.2. Manipulating brain volume: input/output, masking, ROIs, smoothing...
</pre>

The 2 subsections have overlaps, and title that don't summarize what's in them. When teaching, I spend my time jumping from one to the other, which is an indication that it's not structured at all the right way.

Here is how I suggest to restructure:
<pre>
5. Image manipulation
5.1. Input and output: neuroimaging data representation (would integrate current 5.1.1, 5.2.1, 5.2.2)
5.2. Manipulating brain volumes: resampling, filtering, smoothing, masking, ROIs...
5.3. From neuroimaging volumes to data matrices: the masker objects
</pre>

What do people think: @banilo (this may affect how we teach), @AlexandreAbraham, @mrahim, @KamalakerDadi ?

**Comment by KamalakerDadi** [comment]
I agree, sounds good to me.

**Comment by KamalakerDadi** [comment]
May be we can take each one part to work ?
