### ISSUE TITLE
Create / expose new functions to process niimgs

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#1116]
We have noticed that people are sometimes doing workarounds because specific functions are not exposed to the user. This includes flattening niimgs to process all voxels or using third party packages (such as nibabel) to load files.

I list here the functions that we plan to create / expose. Do not hesitate to modify them:
* [x] `clean_img`
* [ ] `check_niimg` (exposed as `load_niimg`)

**Comment by banilo** [comment]
Why not? This new function could be a simple wrapper for the existing function operating on masked data.

**Comment by AlexandreAbraham** [comment]
I have created a PR for clean_img. Do you have any other function in mind?
