### ISSUE TITLE
documentation conflict between niftimasker and signal.clean and lack of exception for error case.

### ISSUE THREAD

**Issue by MartinPerez** [nilearn/nilearn#1118]
In the nifti masker low pass and high pass can take a False value according to the documentation. But in signal.clean only float is allowed and in case False is passed it is considered as different from None and line 505 of signal.py is executed when it shouldnt. I was getting an error for passing False on both high and low pass and then putting tr to None which results in a division by None.

Does this make sense? Should the docs be updated and a Value error be raised whenever tr is none with any given value for high or low pass? I can make a PR if I am not wrong about this.

**Comment by AlexandreAbraham** [comment]
I have not checked but I believe you. PR welcome.

**Comment by KamalakerDadi** [comment]
There exists this documentation problem in many places for example: MultiPCA and soon. Shall we take opportunity to change them accordingly ?

**Comment by MartinPerez** [comment]
I am happy to do it. Could you point me to all relevant places?

**Comment by KamalakerDadi** [comment]
>Could you point me to all relevant places?

For example, I would do ```git grep``` masker family and then see if there is anything to be changed. Let me know if your not clear.

**Comment by MartinPerez** [comment]
@KamalakerDadi following your instructions, there were only two more places. multipca.py and base.py. I made the corresponding changes.

**Comment by KamalakerDadi** [comment]
>@KamalakerDadi following your instructions, there were only two more places. multipca.py and base.py. I made the corresponding changes.

Thank you. I will have a look.

**Comment by GaelVaroquaux** [comment]
Closing as fixed in #1143
