### ISSUE TITLE
which confounds to use?

### ISSUE THREAD

**Issue by rphlypo** [nilearn/nilearn#112]
sparse precision
------------------------
It seems important to at least use movement confounds and their temporal derivatives, as well as the instantaneous variance (squared signal) of both. These account for approximately the same subspace that is spanned by the first high variance confounds (usually 5, but may get to 20 or more), but are less demanding from a computational point of view.

After subtraction of the [augmented matrix of] movement confounds and the first 5 high variance confounds, the connectivity matrix---represented by the precision matrix of the clean time series, i.e., the time series with the confounds regressed out---seems sufficiently sparse in almost all cases.

HCP only?
----------------
The question is whether this can be generalized beyond the HCP dataset (of course, movement confounds must be available).

**Comment by AlexandreAbraham** [comment]
I think we can close this one as this is an open problem. @GaelVaroquaux ?

**Comment by GaelVaroquaux** [comment]
> I think we can close this one as this is an open problem. @GaelVaroquaux ?

Agreed.
