### ISSUE TITLE
Proposal: symbolic links to a common nilearn_cache dir

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1124]
For building the docs, I propose to have "make html" create symbolic links to examples/nilearn_cache from all the example subfolders nilearn_cache directory (on unix systems only, of course). The goal being to federate the cache across all examples, in order to minimize computation.

This would be useful for CircleCI, but I suspect for all developers also.

What do people think?

**Comment by bthirion** [comment]
It will be a significant gain for a moderate cost, so +1

**Comment by GaelVaroquaux** [comment]
I implemented it in #1123. Let's see what CircleCI says.
