### ISSUE TITLE
Get rid of fetch_haxby_simple

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1127]
It's confusing to have 2 haxby fetchers. In addition, it puts strains on generating the documentation (more downloads, less shared path to cache) and it clogs the download folders of people.

I vote to remove fetch_haxby_simple. The examples should all be changed accordingly.

**Comment by AlexandreAbraham** [comment]
+1

**Comment by GaelVaroquaux** [comment]
I've labelled it as easy, with the hope that a new contributor can pick
it up.

**Comment by AlexandreAbraham** [comment]
Maybe a not so easy part: shouldn't we delete or issue a warning if a user updates the software and has already downloaded haxby_simple? I'm trying to avoid unnecessary disk occupation.

**Comment by GaelVaroquaux** [comment]
> Maybe a not so easy part: shouldn't we delete or issue a warning if a
> user updates the software and has already downloaded haxby_simple? I'm
> trying to avoid unnecessary disk occupation.

Not bother about it.

IMHO users should/will clean or delete their nilearn_data directory.
