### ISSUE TITLE
cut_coords and threshold masking

### ISSUE THREAD

**Issue by alexsavio** [nilearn/nilearn#1135]
Hi,
I am struggling a bit with an error in `nilearn.plotting.displays`.

First I use `nilearn.plotting.find_cut_slices` to find a specific number of cuts for a image in the `z` direction. Then I plot some of these cuts (because I am building a grid of plots) with `plot_stat_map`. I use a custom `bg_img` which is in the same space as the input image. The approach has been working well so far.

With the last update, I have 2 problems:
- the `bg_img` does not appear anymore (I get blobs over black) and
- in one case so far, the `data_2d_list` variable in [displays.py line 651](https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/displays.py#L651) ends up full of None, so `ims` is empty.

Any insight will be appreciated. Thanks!

**Comment by AlexandreAbraham** [comment]
Hi Alex,
Do you a minimal usecase reproducing the problem by any chance?

**Comment by alexsavio** [comment]
Hi Alex,
Thanks!

I prepared a minimal case for the `data_2d_list` problem. I can't reproduce the first issue though, will keep checking.
Please check it here:
https://www.dropbox.com/sh/cf7k8v0atts2f66/AABzqmJG_haYuxfOkS5KSimIa?dl=1

**Comment by alexsavio** [comment]
Hi, 
I fixed the `bg_img` problem, I had to fix the figure size in the plot function. I am not sure yet why it was working before and it stopped working.

**Comment by alexsavio** [comment]
A fix suggestion: #1144.

**Comment by GaelVaroquaux** [comment]
Closing as fixed by #1144
