### ISSUE TITLE
interpolation flags not working correctly

### ISSUE THREAD

**Issue by poldrack** [nilearn/nilearn#1136]
I am trying to generate an image using plot_stat_map with nearest neighbor interpolation, but I can't seem to get it to work. I have made some changes to ensure that the proper interpolation flags get passed all the way down to display.map_show (see my fork for details), and have confirmed that kwargs['interpolation']=='nearest' within map_show.  the values in the plotted stat map are binary, but the resulting plotted image still looks interpolated - see attached image.  any ideas?
![interpolation](https://cloud.githubusercontent.com/assets/871056/16156660/22cbe4c4-346a-11e6-872d-e0d9808698f4.png)

**Comment by GaelVaroquaux** [comment]
I don't think that this image is interpolated. I can clearly see the squares of the voxels. What makes you think that it is?

**Comment by poldrack** [comment]
zoom in and you will see that there are voxels that vary in color between yellow and black

> On Jun 17, 2016, at 9:09 AM, Gael Varoquaux <notifications@github.com> wrote:
> 
> I don't think that this image is interpolated. I can clearly see the squares of the voxels. What makes you think that it is?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/nilearn/nilearn/issues/1136#issuecomment-226811729>, or mute the thread <https://github.com/notifications/unsubscribe/AA1KkDrFo8QrX4VtvvTtNnH_MPfti5qxks5qMsbAgaJpZM4I4gDP>.
> 

—
Russell A. Poldrack
Albert Ray Lang Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by eickenberg** [comment]
Can there have been a resampling procedure (with interpolation order > 0)
somewhere on the way to bring the functional image to the shape of the
anatomical background?

**Comment by GaelVaroquaux** [comment]
> zoom in and you will see that there are voxels that vary in color between
> yellow and black

I think that that's aliasing, not interpolation. If you want you can
increase the DPI to diminish this effect, in the call to savefig.

**Comment by GaelVaroquaux** [comment]
> Can there have been a resampling procedure (with interpolation order > 0)
> somewhere on the way to bring the functional image to the shape of the
> anatomical background?

It's matlplotlib that does the alignment of layers.

**Comment by AlexandreAbraham** [comment]
Can you tell us the affine of your data ?

**Comment by AlexandreAbraham** [comment]
Can you try to set the "resampling_interpolation" if "_map_show" to "nearest"?

**Comment by poldrack** [comment]
it is using nearest already - I added a print statement within _map_show():

        print('map_show using %s interpolation'%kwargs['interpolation'])
        img = reorder_img(img, resample=kwargs['interpolation'])

and in the notebook it shows:

map_show using nearest interpolation

here is the affine for the stats image:

array([[  -2.,    0.,    0.,   90.],
       [   0.,    2.,    0., -126.],
       [   0.,    0.,    2.,  -72.],
       [   0.,    0.,    0.,    1.]])
> On Jun 17, 2016, at 9:27 AM, Alexandre Abraham <notifications@github.com> wrote:
> 
> Can you try to set the "resampling_interpolation" if "_map_show" to "nearest"?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/nilearn/nilearn/issues/1136#issuecomment-226815903>, or mute the thread <https://github.com/notifications/unsubscribe/AA1KkEBFhYZiqyv_I6CPtwxietZChry1ks5qMsrZgaJpZM4I4gDP>.
> 

—
Russell A. Poldrack
Albert Ray Lang Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by poldrack** [comment]
FWIW, increasing DPI to 2400 does not seem to reduce the phenomenon

> On Jun 17, 2016, at 9:14 AM, Gael Varoquaux <notifications@github.com> wrote:
> 
> > zoom in and you will see that there are voxels that vary in color between
> > yellow and black
> 
> I think that that's aliasing, not interpolation. If you want you can
> increase the DPI to diminish this effect, in the call to savefig.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/nilearn/nilearn/issues/1136#issuecomment-226812743>, or mute the thread <https://github.com/notifications/unsubscribe/AA1KkM7n6pIjCCF-9_MnwbkY67MNCToBks5qMsfIgaJpZM4I4gDP>.
> 

—
Russell A. Poldrack
Albert Ray Lang Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by GaelVaroquaux** [comment]
I still haven't understood what the problem is: I can clearly see the
voxels on the image. It doesn't seem interpolated to me.

**Comment by eickenberg** [comment]
Maybe the values of the image to be shown were discrete and now appear
smooth (this is different from the plot interpolation)

**Comment by poldrack** [comment]
correct - what I mean is that the image intensity values have been interpolated - the original image is binary whereas the colors shown in the displayed image appear to be continuous over [0,1]

> On Jun 17, 2016, at 10:02 AM, eickenberg <notifications@github.com> wrote:
> 
> Maybe the values of the image to be shown were discrete and now appear
> smooth (this is different from the plot interpolation)
> 
> On Fri, Jun 17, 2016 at 7:00 PM, Gael Varoquaux <notifications@github.com>
> wrote:
> 
> > I still haven't understood what the problem is: I can clearly see the
> > voxels on the image. It doesn't seem interpolated to me.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/nilearn/nilearn/issues/1136#issuecomment-226824103>,
> > or mute the thread
> > <https://github.com/notifications/unsubscribe/ABPwC3Jb539IGVIcW9dgOvtpP_oGjHbSks5qMtKfgaJpZM4I4gDP>
> > .
> >
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/nilearn/nilearn/issues/1136#issuecomment-226824626>, or mute the thread <https://github.com/notifications/unsubscribe/AA1KkM40bMl2t7zle90Fr_WTZ2auiKMyks5qMtMkgaJpZM4I4gDP>.
> 

—
Russell A. Poldrack
Albert Ray Lang Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by poldrack** [comment]
I think that I may have found the error - more shortly, or will send full example to generate the issue from scratch

> On Jun 17, 2016, at 10:17 AM, Russ Poldrack <poldrack@gmail.com> wrote:
> 
> correct - what I mean is that the image intensity values have been interpolated - the original image is binary whereas the colors shown in the displayed image appear to be continuous over [0,1]
> 
>> On Jun 17, 2016, at 10:02 AM, eickenberg <notifications@github.com <mailto:notifications@github.com>> wrote:
>> 
>> Maybe the values of the image to be shown were discrete and now appear
>> smooth (this is different from the plot interpolation)
>> 
>> On Fri, Jun 17, 2016 at 7:00 PM, Gael Varoquaux <notifications@github.com <mailto:notifications@github.com>>
>> wrote:
>> 
>> > I still haven't understood what the problem is: I can clearly see the
>> > voxels on the image. It doesn't seem interpolated to me.
>> >
>> > —
>> > You are receiving this because you commented.
>> > Reply to this email directly, view it on GitHub
>> > <https://github.com/nilearn/nilearn/issues/1136#issuecomment-226824103 <https://github.com/nilearn/nilearn/issues/1136#issuecomment-226824103>>,
>> > or mute the thread
>> > <https://github.com/notifications/unsubscribe/ABPwC3Jb539IGVIcW9dgOvtpP_oGjHbSks5qMtKfgaJpZM4I4gDP <https://github.com/notifications/unsubscribe/ABPwC3Jb539IGVIcW9dgOvtpP_oGjHbSks5qMtKfgaJpZM4I4gDP>>
>> > .
>> >
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub <https://github.com/nilearn/nilearn/issues/1136#issuecomment-226824626>, or mute the thread <https://github.com/notifications/unsubscribe/AA1KkM40bMl2t7zle90Fr_WTZ2auiKMyks5qMtMkgaJpZM4I4gDP>.
>> 
> 
> —
> Russell A. Poldrack
> Albert Ray Lang Professor of Psychology
> Bldg. 420, Jordan Hall
> Stanford University
> Stanford, CA 94305
> 
> poldrack@stanford.edu <mailto:poldrack@stanford.edu>
> http://www.poldracklab.org/
> 
> 
> 

—
Russell A. Poldrack
Albert Ray Lang Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by poldrack** [comment]
hey guys - turns out this was an error on my part, was displaying the wrong image.  many apologies for the noise.

**Comment by GaelVaroquaux** [comment]
Well, we want to be convinced that our display routines are good: to make
sure that when we're looking at an image, what we see is not an artifact
of the display.

**Comment by poldrack** [comment]
thanks - once I got the correct data going into the routine, it looks as it should. just a dumb mistake on my part!

> On Jun 17, 2016, at 10:35 AM, Gael Varoquaux <notifications@github.com> wrote:
> 
> Well, we want to be convinced that our display routines are good: to make
> sure that when we're looking at an image, what we see is not an artifact
> of the display.
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub <https://github.com/nilearn/nilearn/issues/1136#issuecomment-226832648>, or mute the thread <https://github.com/notifications/unsubscribe/AA1KkBYx2ph_2VjabVC-evTNR_vPxEltks5qMtrxgaJpZM4I4gDP>.
> 

—
Russell A. Poldrack
Albert Ray Lang Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/
