### ISSUE TITLE
dim argument in plotting functions should have meaningful error message

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#1138]
When we change beyond the limit. For example, dim=-2 will have no change. The limit we have is between -1, 1.

**Comment by KamalakerDadi** [comment]
Should we raise an error or warning here ?

**Comment by AlexandreAbraham** [comment]
My guess: raise an error when the value has no sense, given that it may reveal that the user does not know what is the real purpose of the parameter.

**Comment by KamalakerDadi** [comment]
Also, I am in favour of making ```dim=False``` by default. By default ```dim=True``` implies automatic dimming applies which makes contrast of the anatomical image weak. Some plotting functions are True and some are False by default. Any opinions on this ?

**Comment by bthirion** [comment]
Note that dim is actually a number, so it would be 0. rather than False.

**Comment by GaelVaroquaux** [comment]
> Also, I am in favour of making dim=False by default. By default dim=True
> implies automatic dimming applies which makes contrast of the anatomical image
> weak. Some plotting functions are True and some are False by default. Any
> opinions on this ?

I would do a dim='auto' and apply diming by default only for the MNI
template. For the MNI template it is very useful.

**Comment by KamalakerDadi** [comment]
Ok. To summarize: dim='auto', float range of [-1, 1]

**Comment by GaelVaroquaux** [comment]
> Ok. To summarize: dim='auto', float range of [-1, 1]

I think that the upper range can go higher up than 1, to dim a lot.

**Comment by bthirion** [comment]
Actually, I have already used -1.5  to increase contrast a lot. but [-1, 
1] is a reasonable default choice.

**Comment by GaelVaroquaux** [comment]
> Actually, I have already used -1.5 to increase contrast a lot. but [-1,
> 1] is a reasonable default choice.

Well, then we should keep -1.5 an option. Actually, maybe I said
something wrong, and 1 is a good upper bound, while the negative lower
bound should be lower. Kamalakar, can you try, please?

**Comment by KamalakerDadi** [comment]
![lower_contrast](https://cloud.githubusercontent.com/assets/11410385/16565187/064bf582-420c-11e6-9668-14f64e24fc2a.png)
![dim_1](https://cloud.githubusercontent.com/assets/11410385/16565196/0f9b563c-420c-11e6-8619-16fb1ba543d2.png)
![dim_2](https://cloud.githubusercontent.com/assets/11410385/16565197/0f9b533a-420c-11e6-946b-136dd35d64c9.png)

 Top one is dim=-1.5. Both are showing some change of effet actually.

**Comment by KamalakerDadi** [comment]
May be I have to change my mind. I don't think there is an issue here ?

**Comment by GaelVaroquaux** [comment]
Didn't we open this issue because we got a crash during a tutorial with someone passing in a bad value for the dim parameter?

If so, it seems that we are not reproducing this crash.

**Comment by KamalakerDadi** [comment]
>Didn't we open this issue because we got a crash during a tutorial with someone passing in a bad value for the dim parameter?

No, not because of crash. We opened because we noticed no effect even given beyond upper bound. May be we haven't noticed the slight difference in the display.

**Comment by GaelVaroquaux** [comment]
> No, not because of crash. We opened because we noticed no effect even given
> beyond upper bound. May be we haven't noticed the slight difference in the
> display.

OK, then I suggest that we improve documentation and introduce the 'auto'
value, and not worry about error messages.

**Comment by KamalakerDadi** [comment]
>OK, then I suggest that we improve documentation and introduce the 'auto' value, and not worry about error messages.

Ok. I will keep all plotting to dim='auto' since all use MNI template except for plot_epi and plot_glass_brain ?

**Comment by GaelVaroquaux** [comment]
> Ok. I will keep all plotting to dim='auto' since all use MNI template
> except for plot_epi and plot_glass_brain ?

Yes, the default should be dim='auto'.

**Comment by KamalakerDadi** [comment]
Closing this one. This issue is addressed in #1168
