### ISSUE TITLE
In the anova SVM example on Haxby, we should use SelectPercentile

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1139]
In the anova-SVM example on Haxby, we are using SelectKBest. However, when doing full-brain analysis, it is better to use SelectPercentile, keeping 10% of voxels (because it is independent of the resolution of the data).

I think that it would be more useful for the end user to use SelectPercentile. What do people think?

**Comment by banilo** [comment]
Good idea, perhaps we could even add this reflection as a comment to the
example script.

Gael Varoquaux <notifications@github.com> schrieb am Mo., 20. Juni 2016 um
16:36 Uhr:

**Comment by bthirion** [comment]
+1 for SelectPercentile.
