### ISSUE TITLE
Add Juelich atlas

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#1145]
I just noticed that fsl comes installed with a hell lot of interesting atlases: HarvardOxford, Juelich, JHU, MNI, etc.

Should we have the possibility to fetching this (at least locally when present) ? For example, I find the Juelich atlas really interesting.

![inversecovariance](https://cloud.githubusercontent.com/assets/634068/16281427/b09127d4-38c4-11e6-9545-0dade0a10e0c.png)

**Comment by GaelVaroquaux** [comment]
+1.

Do you want to do a PR?

**Comment by dohmatob** [comment]
ok, no pb.

**Comment by NicolasGensollen** [comment]
@achamma723 I think you should take a look at #1146 if you're interested in working on this.

**Comment by achamma723** [comment]
@KamalakerDadi Hello, can you please tell me how did you manage to add a new dataset (Desterieux) to the nitrc site

**Comment by KamalakerDadi** [comment]
Please create account on nitrc. Tell your account name to admin team. Then, admin should be able to give rights to upload data.

Alternative: Use Nilearn's open science framework account.
