### ISSUE TITLE
Name collision for ABIDE dataset

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#1147]
Rich anatomical data has been released for ABIDE. It makes no sense to fetch them using the functional one because of some specific options (global_signal_regression for example). But, if I create a new fetcher in the anat submodule, it would have the same name as the functional one and we may have trouble.

Should we let people rename the functions or change their names?

**Comment by GaelVaroquaux** [comment]
How about fetch_anat_abide?

I might be interested in having a more systematic naming such as
fetch_rest_adhd instead of fetch_adhd...

**Comment by bthirion** [comment]
Stalled, closing.
