### ISSUE TITLE
Changing the glass brain template

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#1150]
More and more people are asking for the ability to modify the svg template of the glass brain. For example, Pasteur's people want to plot ferret brains. I suggest that we may be able to set a global variable, or a shadow parameter to allow advanced user to change the template. I can show them how to hack it locally, the question is if we decide to propagate this change in the official repo.

**Comment by TheChymera** [comment]
Here's some basic data for quick testing:

* [Mouse Brain Template](http://chymera.eu/NIhelp/general_plotting/ds_QBI_chr.nii.gz)
* [tstats in template space](http://chymera.eu/NIhelp/general_plotting/tstat1.nii.gz)
* [coronal](http://chymera.eu/img/coronal.svg) and [sagittal](http://chymera.eu/img/sagittal.svg) glass brain SVGs

**Comment by MartinPerez** [comment]
I would be interested on helping out.

**Comment by GaelVaroquaux** [comment]
Are these people going to turn into developers (some of them)? Or is this
a non profitable market? :)

**Comment by TheChymera** [comment]
Actually I'm starting to have doubts on this - I think setting up a mesh with high transparency for the template and a mesh with low transparency for the stats would be a lot nicer and more portable. I'm not sure if this yet-another-svg aproach would be going places.

I guess the only question is whether there is any software that can make and plot meshes which nipype can reliably depend on for this. I am using MRIcroGL, which however is a bit bulky, and has an imho very difficult API.

I checked out Mango, which is easier and smaller, but it seems it's not open source...

Here's what I can get out of Mango  for instance: [horizontal](http://chymera.chymera.eu/img/glassbrain/QBI_chr_horizontal.png), [sagittal](http://chymera.chymera.eu/img/glassbrain/QBI_chr_sagittal.png), [coronal](http://chymera.chymera.eu/img/glassbrain/QBI_chr_coronal.png)

**Comment by emdupre** [comment]
For the moment it seems that there's still no realistic path forward, here. Closing, but we can revisit if the situation changes !

**Comment by TheChymera** [comment]
For the record, we ended up resolving our need for transparent visualization by implementing a [nice 3D plotting function based on blender in SAMRI](https://github.com/IBT-FMI/SAMRI/blob/cc1c5ca38b868b724bd4eb564e9eba8249113666/samri/plotting/maps.py#L552). If anybody is interested in porting this to nilearn you can find more info [here (under Methods:Visualization)](http://chymera.eu/docs/tina_masterarbeit.pdf) and I would be happy to clarify anything you don't understand.

Example:

![fig3](https://user-images.githubusercontent.com/950524/68166515-de1f9380-ff62-11e9-9591-a3e44d93fb52.png)

**Comment by GaelVaroquaux** [comment]
Thank you Christina!

The philosophy of nilearn is to have very light dependencies. I am not
sure that blender qualifies :).

**Comment by kchawla-pi** [comment]
@GaelVaroquaux It would be worth documenting this ourselves (with due credits), or point to this, for people looking for such a workaround. "Something along the lines of Nilearn does not support this but here's a way to do it".

**Comment by TheChymera** [comment]
@GaelVaroquaux @kchawla-pi happy if you would link to our project and/or @setina42 's thesis for people who are interested.

Regarding the dependencies I fully understand and I think it's a very good idea to constrain the list as much as possible. Having said that, for plotting purposes specifically, our experience has been that blender+scikit-image (for marching cubes) is both more lightweight and better performing than other more “scientific” packages such as freesurfer.
