### ISSUE TITLE
Automatically loading colormaps when importing nilearn (or cm?)

### ISSUE THREAD

**Issue by KirstieJane** [nilearn/nilearn#1151]
The colormaps that are created in [cm.py](https://github.com/KirstieJane/nilearn/blob/40069cb14b43333a73137797eac895cfb054db29/nilearn/plotting/cm.py) are really nice!

Currently, if I want to use them in one of my wrapper scripts I have the following hack:

```
from nilearn.plotting import cm

cmap = 'cold_white_hot'

if hasattr(cm, cmap):
    cmap = getatt(cm, cmap)
```

Would it be possible to have these colormaps already loaded so they're available by name without this code?

**Comment by GaelVaroquaux** [comment]
> Would it be possible to have these colormaps already loaded so they're
> available by name without this code?

Is there a reason that the way it is done in:
http://nilearn.github.io/auto_examples/01_plotting/plot_overlay.html#sphx-glr-auto-examples-01-plotting-plot-overlay-py
is not satisfactory?

**Comment by AlexandreAbraham** [comment]
When proposing new colormaps, it is a good practice to register them in matplotlib so that it is automatically available using string identifiers.

**Comment by GaelVaroquaux** [comment]
> When proposing new colormaps, it is a good practice to register them in
> matplotlib so that it is automatically available using string identifiers.

OK, sounds like a good idea. PR welcomed!

**Comment by KirstieJane** [comment]
Thank you @AlexandreAbraham for explaining the problem more clearly! And to @GaelVaroquaux for all the support :grinning:
