### ISSUE TITLE
Dropping scikit-learn dependency < 0.14.1

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#1160]
It makes easier to set base for decoder object in nilearn which actually requires lot of backports for versions. #1148 

I don't have great justifications though. Let me know if I miss something important in nilearn which we need to take into account dropping 0.13.

FYI: https://packages.debian.org/jessie/python-sklearn

Discussions are welcome.

**Comment by GaelVaroquaux** [comment]
+1 for me!

**Comment by AlexandreAbraham** [comment]
0.14.1 is very old. This seems like a safe move to me.

+1.

**Comment by KamalakerDadi** [comment]
OK, I am assigning myself to address this issue.
