### ISSUE TITLE
is there a minimal data with GM, WM and CSF masks ?

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1165]
to add an example with standard careful preprocessing, including intersecting ROIs with grey matter and using anatomical compCor.

**Comment by GaelVaroquaux** [comment]
Not sure, but you can always use nilearn.datasets.fetch_icbm152_2009
to retrieve group-level tempates.

**Comment by KamalakerDadi** [comment]
You could also try this: ```datasets.fetch_icbm152_brain_gm_mask``` or ```datasets.load_mni152_brain_mask``` for a simple canonical mask.

Similar idea is proposed in Issue #1104 which takes gray matter mask for example and compute confounds and return the same from out of mask (white matter mask) depending upon the number of confounds user wants.

is that something you are planning for ?

**Comment by salma1601** [comment]
Well I wasn't thinking of a function, but just an example to demo a careful preprocessing pipeline.

**Comment by GaelVaroquaux** [comment]
> Well I wasn't thinking of a function, but just an example to demo a careful
> preprocessing pipeline.

Well, maybe we can use the group-level maps then, and mention in the
example that subject-level maps would be better.

**Comment by salma1601** [comment]
Yes, but I am trying to make it "optimal"...
Is there any reason we can not add one spatially preprocessed subject with its anatomical masks, host it on nilearn NITRC and use it to demo preprocs ?
It can be for instance a subject from the surgical epilepsy
http://fcon_1000.projects.nitrc.org/indi/retro/NorthShoreLIJ.html
Sorry, just suggesting, don't know how much this is relevant

**Comment by GaelVaroquaux** [comment]
The problem is that each data download used in examples makes tutorials
harder to give and building the doc take more time and disk space. That
last item has become a major problem, and we are actively fighting to
reduce the number of different datasets used in the examples.

**Comment by salma1601** [comment]
Ok, then I use the group masks

**Comment by thomasbazeille** [comment]
A solution seem to have been found, can be closed i guess
