### ISSUE TITLE
[BUG] hemispheric glass brain, left and right in wrong positions in plot

### ISSUE THREAD

**Issue by MartinPerez** [nilearn/nilearn#1170]
During developement this was checked to be correct, maybe during the PR corrections the order was messed up. Anyway the images are correct, is just that the left image is in the place of the right image and viceversa, so it does not correspond with the display_mode and is very misleading due to the labels. Here an example of display_mode='lyrz' in a language localizer.

![sub-02_task-languagelocalizer_language-string](https://cloud.githubusercontent.com/assets/8766915/16650566/2569128a-443f-11e6-97cd-3d7a732d766e.png)

I will submit a PR ASAP.

**Comment by MartinPerez** [comment]
And effectively is wrong in the public example in the webpage :S. Even though the initial examples in the PR are correct.
http://nilearn.github.io/auto_examples/01_plotting/plot_demo_glass_brain.html#sphx-glr-auto-examples-01-plotting-plot-demo-glass-brain-py

**Comment by MartinPerez** [comment]
There is another bug. Sometimes the image at the left is not inverted, giving the left and right looking in the same direction, this two maps come from exactly the same code with a different contrast image. Altnough the statistics are correct. This is only a lack of inversion of the plot image during plot construction.

![pseudo_-_letter_glass](https://cloud.githubusercontent.com/assets/8766915/16687859/3f4a1230-451b-11e6-8f6b-c81d1cb81247.png)

![pseudo_glass](https://cloud.githubusercontent.com/assets/8766915/16687871/54af310a-451b-11e6-996b-8c558b3c5ec7.png)

**Comment by AlexandreAbraham** [comment]
Thanks to the help of Martin, I am now getting very close to the bug. First, let me tell you that it is a problem of display and not of data. So, apart from the left/right inversion that has been corrected, the things that are displayed are right.

**Comment by rschmaelzle** [comment]
Hi, not entirely sure this is related, but when I try to create an animation with a glassbrain that has display_mode='l', and then grab the figure via mplfig_to_npimage(f), this flips the glassbrain and I am seeing a jittering brain flipping between left and right orientation.

**Comment by AlexandreAbraham** [comment]
@rschmaelzle, could you:

* check that you are using the latest version of nilearn (the last release, no need to have the latest dev version)
* open another issue with a minimal working example?

The present issue should have been resolved so I will close it.
