### ISSUE TITLE
The code to display left sagittal cut is a bit fishy

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#1186]
In order to display the left sagittal cut of the brain, we horizontally flip the xaxis. The problem is that this is done in several places in the code and it may be run several times.

As discussed with other people, this particular case should be handled by the Axes object and not the Slicer. Also, it should be done only once per axis before plotting. We should do a pass on this code to make it clearer.

**Comment by bthirion** [comment]
Stalled. Closing.
