### ISSUE TITLE
nilearn.plotting.find_xyz_cut_coords() does not support unsigned integer 16/32/64 niftis

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#1191]
If you pass a nifti with data that does not allow for signs, a `TypeError` is returned. This explains the crash, but is why should there be no perfect xyz cuts just because the content of the nifti image cannot be negative?

**Comment by AlexandreAbraham** [comment]
In the code, we do:

`mask = np.abs(my_map) > activation_threshold - 1.e-15` to account for numerical noise. If the threshold is 0, like in your file, we get something negative.

**Comment by bthirion** [comment]
No example to reproduce, closing.
