### ISSUE TITLE
extracting voxels timeseries within a sphere and using inverse_transform with NiftiSpheresMasker

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1192]
Is there an appropriate way to extract voxels time series within spheres ? I am using  `iter_signals_from_spheres`

``` Python
import nibabel
from nilearn import datasets, input_data
from nilearn.input_data.nifti_spheres_masker import _iter_signals_from_spheres
adhd = datasets.fetch_adhd(n_subjects=1)
func_filename = adhd.func[0]
seeds_masker = input_data.NiftiSpheresMasker([(-6, 50, -1)], radius=6.)
seeds_masker.fit()
sphere_timeseries = _iter_signals_from_spheres(
    seeds_masker.seeds_, nibabel.load(func_filename),
    seeds_masker.radius,
    seeds_masker.allow_overlap).next()
```

I also want to go from array to image using `inverse_transform` but I got an error

``` Python
image = seeds_masker.inverse_transform(sphere_timeseries.T)
```

> 'NiftiSpheresMasker' object has no attribute 'mask_img_'

**Comment by AlexandreAbraham** [comment]
Yes, your code to get the signals should work.

The error you get is a design bug, actually. BaseMasker has a "valid" `inverse_transform` method though it should raise a NotImplemented error. NiftiSpheresMasker has no `inverse_transform` method.

**Comment by salma1601** [comment]
Can't we have an `inverse_transform` method for `NiftiSpheresMasker` ?

**Comment by AlexandreAbraham** [comment]
> Can't we have an inverse_transform method for NiftiSpheresMasker ?

PR welcome!

For non-overlapping spheres, it should indeed be a quickfix. For non-overlapping... It's more complicated (as you can guess).

I don't have time to do that now, I spent my nilearn time on other things. If you need, I should be able to do a quick draft though.

**Comment by salma1601** [comment]
I wanted it for a connectivity example I plan to PR to demo the impact of changing the radius in spheric ROIs.
OK I will take a look to see if it's not too hard for me :)

**Comment by AlexandreAbraham** [comment]
> I wanted it for a connectivity example I plan to PR to demo the impact of changing the radius in spheric ROIs.

If you have enough seeds, It would be interesting to use them to cluster the whole brain volume (so end up with non-spherical regions) and compare that to spheres.

**Comment by salma1601** [comment]
OK I will try that too

**Comment by salma1601** [comment]
> For non-overlapping spheres, it should indeed be a quickfix. For non-overlapping... It's more complicated (as you can guess)

I looked into it this afternoon and it looks complex for me. May be I can try to work on #1229 to become familiar with the inverse_transform concept

**Comment by SRSteinkamp** [comment]
Hi,
it's kinda weird for me to bump this quite old topic. However, I've been looking for something like salma's solution at the beginning of the issue to extract voxel-wise TS from a sphere for a while and have to admit I didn't look at the solution close enough. 
I even hacked the NiftiSpheresMasker function to create spherical masks/niftis based on the parameters, which can then be used with the NiftiMasker or LabelsMasker, however, it's quite inefficient.

My two cents on this:
* I think in general (also for debugging) an inverse transform for the SpheresMasker might be quite interesting/important. I can try to deal with implementing the inverse transform, which can take long, as I am short on time currently (well the issues has been open for some years as well...). Also I think having it only for non-overlapping ROIs wouldn't be an issue at first? I.e. throwing an error, if ROIs overlap?
 
*  Would a small tutorial be helpful to show how to extract voxel-wise timeseries from spheres? I think this is a functionality former SPM users might also be looking for.

Best,
Simon

**Comment by bthirion** [comment]
+1 for an inverse transform. 
Imho it's fine to use a stupid heuristic for overlapping spheres, at least at the beginning. To me, the least stupid solution is to assign voxels to the nearest sphere center.
Throwing an error for overlapping ROIs is bad: it will break people's pipeline for bad reasons.
+1 for a tutorial on that
Thx @SRSteinkamp

**Comment by SRSteinkamp** [comment]
I had a look at the inversion function the last few days. The inverse transform for the NiftiSpheresMasker seems a bit more complicated or extensive than I expected. 

The biggest issue (in my opinion is), that there is no template to put the inverse on. If I understand it correctly, for all the other masker you have a "template" i.e. the labels or maps on which the inverse can be performed. 
In the SpheresMasker there is basically no real affine nor a target shape which could be used.
I drafted something (definitely not pretty) and was too shy for a pull request, as I don't know if it makes sense...
[https://github.com/nilearn/nilearn/compare/master...SRSteinkamp:inverse_spheres_masker](https://github.com/nilearn/nilearn/compare/master...SRSteinkamp:inverse_spheres_masker)


My approach was to create a series of functions, basically hacks of the functions underlying the SpheresMasker:
1. I adjusted `_apply_mask_and_get_affinity` and `_iter_signals_from_spheres` - to only extract the coordinates of the voi
2. Then I created a class similarly to the `_ExtractionFunctor`, which builds a map like atlas, with each sphere getting its own image. Unfortunately, I found the need here to hardcode the affine and shape for the template into which to put the spheres, I think I used the MNI standard space. 
3. Finally in the inversion function I'm basically putting the maps into `signal_extraction.signals_to_img_maps`. I haven't had a closer look at the `signals_to_img_maps` function, but might it take care of the `allow_overlap` problem?

I hope my explanations are somehow clear. There still seem to be some issues when there is a mask provided though...

**Comment by thomasbazeille** [comment]
@bthirion or @GaelVaroquaux if you could take a look at the draft Simon provided juste above and share some thoughts on the design it will be the best way forward towards a PR

**Comment by SRSteinkamp** [comment]
Great thanks, I am a bit busy this morning, but will later check, if the code above actually (still) works, it's been a while that I have been working on this.

**Comment by bthirion** [comment]
There is a `mask_img` provided at the creation of NiftiSpheresMasker My understanding is that `inverse_transform` should take the `mask_img` field of view and affine to define the output space.

**Comment by SRSteinkamp** [comment]
Yes, so in the current version I am using the mask info if there's a mask provided. But in the case there's no mask, the reference is missing.

**Comment by SRSteinkamp** [comment]
Update for today:
* Signal in overlapping spheres are now averaged (yay)
* The function now works when a `mask_img` is provided - had some issues with it before. 

Tomorrow I will write tests for the inverse transform (taking some inspiration from the other inverses)  + some additional things based on todays experience. 

** Documentation? ** 
I am not sure where this could fit in. I could actually imagine an example showcasing the extraction of beta-weights from a first-level GLM analysis (maybe pulling one or two maps from Neurosynth for simplicity), as is sometimes done in the SPM community, using the `_iter_signals_from_spheres` and `inverse_transform` functions as possible debugging (for example with regards to masking), and visualization options? (And should this be a different issue / PR)?
I think the `NiftiSpheresMasker` is used so far only in a connectome example, where I do not see the `inverse_transform` and other functions really fit in.

**Comment by bthirion** [comment]
Thx ! 
Don't hesitate to issue a PR ven if it 's not fully complete: early feedback is good.
Maybe you can provide documentation in 
http://nilearn.github.io/modules/generated/nilearn.input_data.NiftiSpheresMasker.html#nilearn.input_data.NiftiSpheresMasker
