### ISSUE TITLE
find_xyz_cut_coords takes numpy array as mask

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#1193]
Unlike all img functions that takes all input as niimg, this one force the mask to be a numpy array, which is a bit odd.

**Comment by GaelVaroquaux** [comment]
> Unlike all img functions that takes all input as niimg, this one force
> the mask to be a numpy array, which is a bit odd.

+1

**Comment by shoshber** [comment]
+1. Same for `find_cut_slices()`. I can call them with the input as a Nifti1Image, but not as a niimg, which is a lot less convenient!

**Comment by GaelVaroquaux** [comment]
+1 @shoshber 

Do you want to have a go at it?

**Comment by shoshber** [comment]
I don't have time at the moment (looming deadlines), unfortunately. I know it's annoying when someone keeps suggesting changes without contributing, sorry!

**Comment by GaelVaroquaux** [comment]
> I know it's annoying when someone keeps suggesting changes without contributing, sorry!

Don't worry, I've been in open source too long to be annoyed :). It's
just that things would get done, and that's cool. We'll probably get
along to doing this, but right now we are busy with other things.

**Comment by GaelVaroquaux** [comment]
Fixed in #1430
