### ISSUE TITLE
SpaceNet should receive mask_strategy as parameter

### ISSUE THREAD

**Issue by ahoyosid** [nilearn/nilearn#1204]
I've been working with SpaceNet without a precomputed mask, then it computes the mask with a mask_stategy = 'epi', and I need 'background' instead.
But there is no parameter in the API to change it.

This is a minor change in the code, I wouldn't mind to do it if you guys think is useful.

@dohmatob, @GaelVaroquaux  

Best

**Comment by AlexandreAbraham** [comment]
You should be able to instantiate a `NiftiMasker` object with the parameters you want and then give it to SpaceNet through the `mask` parameter.

**Comment by ahoyosid** [comment]
Ok, it is as simple as that
