### ISSUE TITLE
np.corrcoef or ConnectivityMeasure

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1212]
Two connectivity examples use `np.corrcoef`to compute correlation matrix
- `plot_signal_extraction`
- `plot_probabilistic_atlas_extraction`

Shall we rely on `ConnectivityMeasure((cov_estimator=EmpiricalCovariance(), kind='correlation')` instead ?

**Comment by AlexandreAbraham** [comment]
I think so.

**Comment by bthirion** [comment]
+1
