### ISSUE TITLE
ConnectivityMeasure fit_transform for one subject requires a list input parmeter

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1215]
an returns a list of matrices. I am in favour of allowing a 2D array single subject timeseries as an input of `ConnectivityMeasure` `fit_transform` method and returning one matrix in this case.

**Comment by GaelVaroquaux** [comment]
> an returns a list of matrices. I am in favour of allowing a 2D array single
> subject timeseries as an input of ConnectivityMeasure fit_transform method and
> returning one matrix in this case.

Such flexibility means that error capture and managment becomes very
hard. In scikit-learn, we have actually gone the other way, and
explicitely made such flexibility impossible.

**Comment by salma1601** [comment]
OK !
