### ISSUE TITLE
rename plot_adhd_spheres example

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1220]
Most of examples rely on ADHD but do not cite it in file name.
What about renaming it `plot_spheres_extraction` or `plot_spheres_connectome` ?

**Comment by GaelVaroquaux** [comment]
> Most of examples rely on ADHD but do not cite it in file name.
> What about renaming it plot_spheres_extraction or plot_spheres_connectome ?

Yes!

I am actually in favor trying to limit the use of dataset name in the
example name, in order to have names that describe better what is the
didactic purpose of the example.

**Comment by AlexandreAbraham** [comment]
Maybe `plot_seed_based_connectome` ?

**Comment by salma1601** [comment]
Actually I don't like using the **seed** vocabulary when playing with ROI-to-ROI connectivity. I always associate it to seed-to-voxel connectivity, but may be I am biased.

**Comment by bthirion** [comment]
Solved, closing.
