### ISSUE TITLE
Rename ConnectivityMeasure

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1231]
I was teaching today, and it stroke me that ConnectivityMeasure computes connectomes, and the name doesn't express this well. The "Measure" name doesn't capture the fact that it gives matrices, it feels more like a bivariate measure.

Not sure of a name? ConnectomeBuilder? ConnectomeEstimator?

Suggestions? Comments? Discussion?

**Comment by AlexandreAbraham** [comment]
+1 for ConnectomeEstimator

**Comment by GaelVaroquaux** [comment]
Also came to my mind: "Connectomer" "ConnectomeGrapher"

**Comment by bthirion** [comment]
I prefer ConnectomeEstimator.

**Comment by AlexandreAbraham** [comment]
Connectomist ? :D

Summon @eickenberg

**Comment by salma1601** [comment]
+1 for `ConnectomeEstimator`

**Comment by salma1601** [comment]
may be also something stressing the fact that it is designed for a group of subject, that's why it fits a list.
`GroupConnectomeEstimator` ? but too long

**Comment by bthirion** [comment]
ConnectomesEstimator is fine.

**Comment by bthirion** [comment]
Stalled, closing.
