### ISSUE TITLE
ConnectivityMeasure(kind='tangent') is misleading

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1233]
I was presenting the mean connectivity matrix for `kind='tangent'` and one guy wanted to see how much it differs from individual connectivities. So I refitted my `ConnectivityMeasure` with `kind='covariance'` to show him.
I think this is very counter-intuitive. I have a proposition to tackle this but I don't know if it's the good one:
- change the output of the `fit_transform` for `kind='tangent'` to covariances. This would have the benefit to homogenize the output for all kinds to individual connectivity matrices
- add an attribute `deviations_` that will give the  actual output of `fit_transform` for kind='tangent'

I am hesitating whether it would be of benefit to define this attribute for the remaining kinds (just subtracting the mean from the individual connectivities)

**Comment by GaelVaroquaux** [comment]
>   • add an attribute deviations_ that will give the actual output of
>     fit_transform for kind='tangent'

That's not a good option, because it means that the object can no longer
be used in a pipeline, which is what I think we really want.

**Comment by salma1601** [comment]
Ok so may be add a `covariances_` attribute ?

**Comment by GaelVaroquaux** [comment]
> Ok so may be add a covariances_ attribute ?

I don't like very much the idea of putting too much state in the object.
It is hidden to the user and not very discoverable.

I'd much rather prefer having the inverse_transform reconstruct
covariances from the corresponding displacement vectors. In addition, it
matches the idea that inverse_transform would also undo an optional
vectorization.

**Comment by salma1601** [comment]
Ok. I don't know if I will be able to do a PR on that. The inverse_transform looks difficult for me.

**Comment by salma1601** [comment]
So again back to this: what about outputting the deviations from means for all kinds of connectivities (as it is done for 'tangent', meaning just subtracting the `mean_` from the individual matrices for all kinds but 'tangent'. Then the connectivity matrices can be computed with the inverse_transform
The benefit for it is outputting objects of the same nature for all kinds. I am having a hard time with the namings in my example, as I loop over all kinds

**Comment by GaelVaroquaux** [comment]
> So again back to this: what about outputting the deviations from means for all
> kinds of connectivities (as it is done for 'tangent', meaning just subtracting
> the mean_ from the individual matrices for all kinds but 'tangent'. Then the
> connectivity matrices can be computed with the inverse_transform

I'd rather not. Only tangent embedding needs this, as the rest rely on a
Euclidean space.

> The benefit for it is outputting objects of the same nature for all
> kinds. I am having a hard time with the namings in my example, as I
> loop over all kinds

Actually, I would rather that you did not loop of the kinds: it makes the
code difficult to read for a beginner. I would rather have 3 sub
sections, and 3 different comments on them, with, ideally, 3 dedicated
visualizations.

**Comment by salma1601** [comment]
>Actually, I would rather that you did not loop of the kinds: it makes the code difficult to read for a beginner. I would rather have 3 sub sections, and 3 different comments on them, with, ideally, 3 dedicated visualizations.

Ok
But even when I don't loop I don't like that we output things of different natures by the same object. I am not talking for math, it's rather for the reality. People have to be aware that the output of 'tangent' are not connections.
May be I am giving myself a headache, but I feel like this ConnectivityMeasure is not well done

**Comment by salma1601** [comment]
Yes but its mean_ will not be a deviation !
I am back to the idea of adding an attribute
- at the fit, compute `connectivities_` which are the individual connectivity matrices, for `tangent` they are covariances -> to be plotted and watched, with a nice positive diagonal
- transform: this is transformation to vector space $R^p$, and for `tangent` this is the displacement who lives in the vector space -> to be used in statistical tests, and classification
- inverse transform: just back from vector to matrix, without any diabolic rescaling -> useful for p-values plotting

This is what see

**Comment by GaelVaroquaux** [comment]
>   • at the fit, compute connectivities_ which are the individual connectivity
>     matrices, for tangent they are covariances -> to be plotted and watched,
>     with a nice positive diagonal

I don't like that: it is hidden from the user, only the rest of our
pipeline which is explicite.

**Comment by salma1601** [comment]
I think I am not getting well your argument. When you say pipeline, are you thinking to something specific in chaining operations or something like that ?
I don't understand why it bothers you for ConnectivityMeasure while this is the way GroupSparseCov works, isn't it ?
Could you please be more explicit in your explanation ?

**Comment by salma1601** [comment]
Ah I think I understand, you mean in the examples we are going to use directly fit_transform not fit ?

**Comment by AlexandreAbraham** [comment]
I am not particularly fond of universal objects which behavior heavily differ when one parameter changes. Users can be mislead and it usually makes documentation harder to write.
I see, from this issue and others, that we start having a big divergence between tangent stuff vs. classical covariance estimation. In that case, wouldn't it be more clever to mark the difference by splitting the objects? Meaning having one object for classical correlation, eg CovarianceEstimator, and one for the tangent stuff, eg DeviationEstimator?

**Comment by salma1601** [comment]
You mean having something like a BaseCovarianceEstimator, which will give the covariances, which are the base for all the connectivity kinds, and than derivate correlation, partial correlation and tangent from this base estimator with new classes inheriting from the BaseCovarianceEstimator ?

**Comment by AlexandreAbraham** [comment]
> and than derivate correlation, partial correlation and tangent from this base estimator with new classes inheriting from the BaseCovarianceEstimator 

At least, having different objects for tangent and the rest looks like a good idea to me. One class per type of covariance is fine for me, because I tend to overdesign things, but I'm not sure if it's a good idea.

**Comment by salma1601** [comment]
>At least, having different objects for tangent and the rest looks like a good idea to me
I think separating tangent is a good idea, and I am in favour of really changing the design of this ConnectivityMeasure. If I am stacked so much in the examples and the namings than I think there is a problem that can not be solved just by customizing the examples.

Again I am a humble user and don't know design, but I like your idea, so +1 for `BaseConnectomesEstimator` and `TangentConnectomesEstimator`

**Comment by GaelVaroquaux** [comment]
> At least, having different objects for tangent and the rest looks like a good
> idea to me. One class per type of covariance is fine for me, because I tend to
> overdesign things, but I'm not sure if it's a good idea.

I'd rather not. These really are two aspects of the same thing. Let's not
make the design complex for purity reasons.

**Comment by salma1601** [comment]
OK, so I understand there is no good solution to handle the tangent stuff. I am going to add to the example something like

``` python
tangent_measure = ConnectivityMeasure(kind='tangent')
individual_deviations = tangent_measure.fit_trasnform(subjects, vectorize=True)
individual_connectivity_matrices = tangent_measure.inverse_transform(individual_deviations)
``` 
to show how we can extract the individual covariances. Seems to me things are the other way round, but I want to move.

**Comment by salma1601** [comment]
I was thinking of a compromise: putting `vectorize` to True by default. This is useful for second-level analyses, which is compatible with the strategy of teaching `ConnectivityMeasure` for multi-subjects. If they want to recover individual matrices, they do the `inverse_transform`. This way, the complexity of the tangent model is completely hidden, and outputs are homogeneous across kinds.
While we are on it, I was also thinking of adding `discard_diagonal` to `ConnectivityMeasure`, for practical reasons :
- Fisher Z-transform gives nan on the diagonal 1.,
- t-tests  display an ugly Runtime warning when one coefficient is the same across all subjects
