### ISSUE TITLE
seed terminology used for spheric ROIs connectome

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1234]
The example relying on spheric ROIs is named `plot_seed_based_connectome`
For me seed terminology is used for any ROI (or even one voxel) when studying its connectivity with all the other voxels. It does not tell it is spheric and is not generally used for ROI-to-ROI connectivity. Am I wrong ?

**Comment by GaelVaroquaux** [comment]
I agree with you, and I agree that in this case the terminology should be fixed.

**Comment by salma1601** [comment]
closing this, as fixed in PR #1224
