### ISSUE TITLE
mean_ attribute for ConnectivityMeasure with all kinds

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1237]
Does it make sense to define the mean_ for all kinds and not only 'tangent' ?
This allows to get the mean connectivity matrix when the outputs are vectorized as requested in #1236, without refitting of the estimator.

**Comment by GaelVaroquaux** [comment]
> Does it make sense to define the mean_ for all kinds and not only
> 'tangent' ? This allows to get the mean connectivity matrix when the
> outputs are vectorized as requested in #1236, without refitting of the
> estimator.

Yes, I would think so. I stumbled on this when teaching on Monday.

**Comment by KamalakerDadi** [comment]
Closing this one as the request is been addressed in PR #1236.

To know how to use ```mean_``` attribute for various kinds. Please see in a very good example examples/03_connectivity/plot_group_level_connectivity.py showing how to do this.
