### ISSUE TITLE
Enhancement suggestion: MultiNiftiMapsMasker / MultiNiftiLabelsMasker

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1240]
The example http://nilearn.github.io/auto_examples/03_connectivity/plot_multi_subject_connectome.html coud be greatly simplified if the NiftiMapsMasker could take a list of subjects / confounds.

However, it makes very brittle and awkward input verification to accept both 4D and 4+1D data.

Hence, I suggest to create 2 new classes: MultiNiftiMapsMasker and MultiNiftiLabelsMasker that take 4+1D data. These could be chained into a ConnectivityMeasure and a supervised learning to get a full predictive pipeline.

What do people think?

**Comment by Hororohoruru** [comment]
I would like to work on this, if you still think it's a good idea.

**Comment by bthirion** [comment]
Yes AFAIK.
