### ISSUE TITLE
NaN problem in NiftiMapsMasker

### ISSUE THREAD

**Issue by darya-chyzhyk** [nilearn/nilearn#1249]
Have a problem with NiftiMapsMasker and fit_transform, that have some limitation on using the images which contain NaN (e.i. anatomical tissue segmented images from SPM):

ValueError: array must not contain infs or NaNs

2 options:
- Add "ensure_finite" to ilearn.image.clean_img
- Deal automatically with NaNs in NiftiLabelsMasker

**Comment by bthirion** [comment]
In that case, it is clear that the semantic of 0 is that the map loadings vanish, so I am OK with the first option, which is also probably easier to implement.

**Comment by GaelVaroquaux** [comment]
> In that case, it is clear that the semantic of 0 is that the map loadings
> vanish, so I am OK with the first option, which is also probably easier to
> implement.

Good to know. I think that we should do both: first deal with nans in the
maps_img, second add an ensure_finite=False kwarg to clean_img.
