### ISSUE TITLE
Import coord_transform in nilearn.image

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1250]
I was wondering: should we import and expose and document "coord_transform" in nilearn.image.**init**? It would seem useful.

**Comment by salma1601** [comment]
It would be useful e.g. to form spheres binary masks, because for the moment I couldn't find a straightforward way to do that with `NiftiSpheresMasker`.
I think it is useful to be able to visualize the spheres, to check things were correctly done (e.g. resampling, see #1246)

**Comment by KamalakerDadi** [comment]
Closing with #1538
