### ISSUE TITLE
The hemispheric glass_brain is broken for filled contours

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1252]
<pre>
from nilearn import datasets
localizer_dataset = datasets.fetch_localizer_button_task()
localizer_tmap_filename = localizer_dataset.tmaps[0]

from nilearn import plotting

glass_brain = plotting.plot_glass_brain(None, display_mode='lyrz')
glass_brain.add_contours(localizer_tmap_filename, filled=True,
                         levels=[3, ], colors=['g', ], alpha=1)
</pre>

This will produce 
![tmp](https://cloud.githubusercontent.com/assets/208217/17817110/07cb2d06-663d-11e6-8806-cba813c45f3d.png)

Notice how the orientation of the hemispheric plot is broken.

If I add an image, instead of None, in the glass brain, it works right.

**Comment by AlexandreAbraham** [comment]
I guess that the axis inversion  is made in a code path that is skipped if img is None.

**Comment by GaelVaroquaux** [comment]
> I guess that the axis inversion is made in a code path that is skipped if img is None.

Probably :$
