### ISSUE TITLE
NiftiLabelsMasker's mask_img may forget to mask the data

### ISSUE THREAD

**Issue by sparkler0323** [nilearn/nilearn#1257]
In nifti_labels_masker.py , the class **_ExtractionFunctor** may forget to transfer the mask_img so the NiftiLabelsMasker fail to mask the data.

Sorry for taking your time

**Comment by GaelVaroquaux** [comment]
> In nifti_labels_masker.py , the class _ExtractionFunctor may forget to
> transfer the mask_img so the NiftiLabelsMasker fail to mask the data.

Can you give us a small example to reproduce your problem? I don't
exactly understand it.

**Comment by sprak0323** [comment]
Of course,I have a fmri data which the points outside the brain are nan,and I would like to make time series from AAL by NiftiLabelsMasker.So I make a mask_img for my data,but the time series made by NiftiLabelsMasker are always obtains nan in some AAL regions. So I find the bug in nifti_labels_masker.py ,it forget to use the mask_img inside in the class _ExtractionFunctor.

**Comment by jeromedockes** [comment]
> Of course,I have a fmri data which the points outside the brain are nan

they should be `0` not `nan`

**Comment by bthirion** [comment]
Stalled or solved ? Closing.
