### ISSUE TITLE
not succeeding to build my docs after ubuntu reinstall

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1259]
I can no more build the docs with `make html`. I just backuped all the nilearn folder after the ubuntu reinstall

>  Make sym-links to share the cache across various example
 directories
cd ../examples/ && mkdir nilearn_cache
mkdir: impossible de créer le répertoire «nilearn_cache»: Le fichier existe
Makefile:42 : la recette pour la cible « sym_links » a échouée
make: [sym_links] Erreur 1 (ignorée)
cd ../examples/01_plotting/ && ln -s ../nilearn_cache
ln: impossible de créer le lien symbolique './nilearn_cache': Le fichier existe
Makefile:42 : la recette pour la cible « sym_links » a échouée
make: [sym_links] Erreur 1 (ignorée)
cd ../examples/02_decoding/ && ln -s ../nilearn_cache
ln: impossible de créer le lien symbolique './nilearn_cache': Le fichier existe
Makefile:42 : la recette pour la cible « sym_links » a échouée
make: [sym_links] Erreur 1 (ignorée)
cd ../examples/03_connectivity/ && ln -s ../nilearn_cache
ln: impossible de créer le lien symbolique './nilearn_cache': Le fichier existe
Makefile:42 : la recette pour la cible « sym_links » a échouée
make: [sym_links] Erreur 1 (ignorée)
cd ../examples/04_manipulating_images/ && ln -s ../nilearn_cache
ln: impossible de créer le lien symbolique './nilearn_cache': Le fichier existe
Makefile:42 : la recette pour la cible « sym_links » a échouée
make: [sym_links] Erreur 1 (ignorée)
cd ../examples/05_advanced/ && ln -s ../nilearn_cache
ln: impossible de créer le lien symbolique './nilearn_cache': Le fichier existe
Makefile:42 : la recette pour la cible « sym_links » a échouée
make: [sym_links] Erreur 1 (ignorée)
 These two lines make the build a bit more lengthy, and the
 the embedding of images more robust
rm -rf _build/html/_images
sphinx-build -b html -d _build/doctrees   . _build/html
make: sphinx-build : commande introuvable
Makefile:57 : la recette pour la cible « html » a échouée
make: *** [html] Erreur 127

**Comment by aabadie** [comment]
You tried on a freshly reinstalled Ubuntu but it seems that you forgot to install `sphinx-build` (see last error message).
Le 3 sept. 2016 4:52 AM, salma1601 <notifications@github.com> a écrit :I can no more build the docs with make html. I just backuped all the nilearn folder after the ubuntu reinstall


Make sym-links to share the cache across various example
 directories
cd ../examples/ && mkdir nilearn_cache
mkdir: impossible de créer le répertoire «nilearn_cache»: Le fichier existe
Makefile:42 : la recette pour la cible « sym_links » a échouée
make: [sym_links] Erreur 1 (ignorée)
cd ../examples/01_plotting/ && ln -s ../nilearn_cache
ln: impossible de créer le lien symbolique './nilearn_cache': Le fichier existe
Makefile:42 : la recette pour la cible « sym_links » a échouée
make: [sym_links] Erreur 1 (ignorée)
cd ../examples/02_decoding/ && ln -s ../nilearn_cache
ln: impossible de créer le lien symbolique './nilearn_cache': Le fichier existe
Makefile:42 : la recette pour la cible « sym_links » a échouée
make: [sym_links] Erreur 1 (ignorée)
cd ../examples/03_connectivity/ && ln -s ../nilearn_cache
ln: impossible de créer le lien symbolique './nilearn_cache': Le fichier existe
Makefile:42 : la recette pour la cible « sym_links » a échouée
make: [sym_links] Erreur 1 (ignorée)
cd ../examples/04_manipulating_images/ && ln -s ../nilearn_cache
ln: impossible de créer le lien symbolique './nilearn_cache': Le fichier existe
Makefile:42 : la recette pour la cible « sym_links » a échouée
make: [sym_links] Erreur 1 (ignorée)
cd ../examples/05_advanced/ && ln -s ../nilearn_cache
ln: impossible de créer le lien symbolique './nilearn_cache': Le fichier existe
Makefile:42 : la recette pour la cible « sym_links » a échouée
make: [sym_links] Erreur 1 (ignorée)
 These two lines make the build a bit more lengthy, and the
 the embedding of images more robust
rm -rf _build/html/_images
sphinx-build -b html -d _build/doctrees   . _build/html
make: sphinx-build : commande introuvable
Makefile:57 : la recette pour la cible « html » a échouée
make: *** [html] Erreur 127

**Comment by GaelVaroquaux** [comment]
You should install python-sphinx, or python3-sphinx.

**Comment by salma1601** [comment]
Thanks for the replies ! Now it works after installing python-sphinx, and also removing sphinx installed with conda and reinstalling it with pip ...
