### ISSUE TITLE
_iter_signals_from_spheres doc says radius and allow_overlap optional but TypeError without them

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1260]
`radius` is said optional
https://github.com/nilearn/nilearn/blob/master/nilearn/input_data/nifti_spheres_masker.py#L103
but
```Python
import nibabel
from nilearn import datasets
adhd = datasets.fetch_adhd(n_subjects=1)
func_img = nibabel.load(adhd.func[0])
from nilearn.input_data import nifti_spheres_masker
signals_iterator = nifti_spheres_masker._iter_signals_from_spheres([(-42, 3, 42)], func_img)
```
throws
>TypeError: _iter_signals_from_spheres() takes at least 4 arguments (2 given)

Similarly for `allow_overlap`
https://github.com/nilearn/nilearn/blob/master/nilearn/input_data/nifti_spheres_masker.py#L106

```Python
signals_iterator = nifti_spheres_masker._iter_signals_from_spheres([(-42, 3, 42)], func_img,
    radius=8.)
```

>TypeError: _iter_signals_from_spheres() takes at least 4 arguments (3 given)

**Comment by AlexandreAbraham** [comment]
In fact, they are not optional.
