### ISSUE TITLE
Add notice to and preview docs

### ISSUE THREAD

**Issue by TheChymera** [nilearn/nilearn#1261]
Nilearn and all its deps have been available for quite some time now [from the Gentoo Science overlay](https://github.com/gentoo-science/sci/tree/master/sci-biology/nilearn).

I would like to submit a PR adding a style-consistent notice of package availability [where neuro/debian/ubuntu are also mentioned](https://github.com/nilearn/nilearn/blob/master/doc/install_doc_component.html).
However, I don't know how to preview that web page. 
`google-chrome-stable doc/install_doc_component.html` perhaps predictably ignores all styling.

**Comment by bthirion** [comment]
Stalled.
