### ISSUE TITLE
plot_stat_map does not display the bg anat when it contains NaNs

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#1268]
Presumably because thre sampling used in plotting does not handle Nans correctly.
This is suprising because I thought that this was not occurring in previous versions of Nilearn.
Maybe related to issue #1249 ?

**Comment by KamalakerDadi** [comment]
>Maybe related to issue #1249 ?

It would be great if you can tell your problem is fixed now.

**Comment by dohmatob** [comment]
Maybe this should be closed ?

**Comment by bthirion** [comment]
Cannot check now, but will do next Monday hopefully.

**Comment by bthirion** [comment]
Hi @KamalakerDadi the problem is apparently not solved: whenever I try to upload the anatomical image in e.g. /storage/store/data/ibc/derivatives/sub-07/ses-00/anat/wsub-07_ses-00_T1w.nii.gz
I cannot use it as a bg_img in plot_stat_map: nothing appears, presumably doe to the NaN issue.

**Comment by GaelVaroquaux** [comment]
> I cannot use it as a bg_img in plot_stat_map: nothing appears, presumably doe
> to the NaN issue.

Did you check that it's because of NaNs?

**Comment by bthirion** [comment]
Indeed, when I replace Nans in the anat by 0, the image displays correctly.
