### ISSUE TITLE
from nilearn import  fails

### ISSUE THREAD

**Issue by medcharleslaidi** [nilearn/nilearn#1269]
I started having problems when importing from nilearn

import nilearn works fine, but I always have the same error ; 

For example with 
`from nilearn import plotting`

> ---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)
<ipython-input-2-35cd2f5e057b> in <module>()
----> 1 from nilearn import plotting

ImportError: cannot import name plotting

>

**Comment by GaelVaroquaux** [comment]
You most likely didn't install nilearn correctly. How did you install
nilearn?

**Comment by medcharleslaidi** [comment]
I just followed the instructions as described in the nilearn webiste (for mac users) : pip install -U --user nilearn
then it worked several times and now I always have the same problem. 
I tried to update nilearn with the latest version, but I always have the samed error...

**Comment by GaelVaroquaux** [comment]
How about you try uninstalling (pip uninstall nilearn) and reinstalling
it?

**Comment by medcharleslaidi** [comment]
I also tried that but it didn't worked :(
When not using ipython I have the same error message... 

> >>>

 import nilearn
>>> from nilearn import plotting
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name plotting

>

**Comment by GaelVaroquaux** [comment]
I just had an idea: do you have a file or a directory named nilearn.py or
nilearn in your current directory? If so, it is overriding the global
nilearn.

**Comment by medcharleslaidi** [comment]
Yes ! That was the problem. I deleted that file and it's working again. 
Cheers !
