### ISSUE TITLE
[Discussion] expose _cov_to_corr and _prec_to_partial from connectome.connectivity_matrices

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1274]
may be useful functions

**Comment by KamalakerDadi** [comment]
>may be useful functions

May be can you elaborate where these functions can be more useful to expose them ?
As I see it, one can use ConnectivityMeasure object easily to compute these measures.

**Comment by AlexandreAbraham** [comment]
The question is: Is there a usecase where we want to run these commands, ie where we grab connectivity matrices from somewhere else. I have mixed feelings about this. On one hand, these functions are simples, so there is no debate on the signature or usage, and I belive that making them public is harmless. On the other hand, I don't have any usecase in mind for that.

So, +0 for me.

**Comment by salma1601** [comment]
That follows discussion #1213, with @GaelVaroquaux  saying to use `ConnectivityMeasure` only for groups of subjects

>I thought about this in the context of the rationalization of the examples. The way that I see it is that we should introduce and advertise ConnectivityMeasure for group-level / multi subject analysis, but not when we are discussing single-subject analysis. It brings complexity but little benefits.

So that will allow to plot for instance the partial correlation coefficients, instead of negating the precision matrix. Negating the precision matrix assumes that people know the underlying relationship between precision/partial correlation.

**Comment by GaelVaroquaux** [comment]
> That follows discussion #1213, with @GaelVaroquaux saying to use ConnectivityMeasure only for groups of subjects

In this line of though, I am +1

**Comment by salma1601** [comment]
Do I apply a systematic `prec_to_partial` and `cov_to_corr` to the examples ?

**Comment by salma1601** [comment]
closing this one, since `cov_to_corr` and `prec_to_partial` are now exposed
