### ISSUE TITLE
"the mask is invalid as it is empty" -  mask issues

### ISSUE THREAD

**Issue by medcharleslaidi** [nilearn/nilearn#1275]
Sorry for taking your time... 

I am trying to extract resting state network with Canica and/or Dict_learning from the Abide dataset. 
I chose the UM sample and downloaded the data after dparsf pre-processing (abide pre-processed).

When launching CanICA, I get a "mask is invalid as it is empty" error. 
As I didn't managed to extract the mask from the fmri images, I downloaded a mask for each subject from the abide repository and produced a mask for the dataset using Niftimasker. 
I created a list named "mask" with all the masks of the subjects and tried : 

`masker = NiftiMasker(mask_strategy='background', mask_args=dict(opening=8))`
`masker.fit(mask)`

and get  :
 
![mask1](https://cloud.githubusercontent.com/assets/11093149/18511577/c191aa16-7a84-11e6-9eeb-824a5c0eee1b.png)

As the result was not perfect, I tried (even if the epi strategy should not be applied in this case because I am using a mask and not an fmri image)

`masker = NiftiMasker(mask_strategy='epi',mask_args=dict(upper_cutoff=.79,lower_cutoff=.77,opening=False))`
`masker.fit(mask)`
`plot_roi(masker.mask_img_, title='Mask-Nilearn')`

and get : 

![mask2](https://cloud.githubusercontent.com/assets/11093149/18511627/0d912a40-7a85-11e6-8081-2ffb556a969c.png)

which is a little better. 

However the mask is not covering all the brain so I am wondering if I am using a correct strategy. 

Thanks a lot, 

Charles

**Comment by GaelVaroquaux** [comment]
If you're using CanICA you shouldn't have to rely on a NiftiMasker,
CanICA does it for you. What are the lines that you are using to call
CanICA?

**Comment by medcharleslaidi** [comment]
I used : 

`canica = CanICA(mask=masker.mask_img_, 
                n_components=21, 
                smoothing_fwhm=6., 
                memory="nilearn_cache", memory_level=2, 
                threshold=3., verbose=10, random_state=0)
canica.fit(func)`

When not specifying any mask argument, I had the "the mask is invalid as it is empty" error....

**Comment by GaelVaroquaux** [comment]
Is there a reason why you really want to give to CanICA a mask? Usually letting CanICA figure out it's mask work quite well.

If you really want to compute the mask yourself, you could do a soft intersection of the masks of the different subjects, using http://nilearn.github.io/modules/generated/nilearn.masking.intersect_masks.html#nilearn.masking.intersect_masks

**Comment by bthirion** [comment]
Another part of the discussion is that the mask does not vocer perfectly the MNI template. This is because individual brains do not have extactly the shape of the MNI brain, due to the  variability between subjects.
In a group analysis, you probably want a standard mask that does not correspond to one subject in particular, but to the average of your sample. CaniCa does it for you (see Gael's response)?
 Best,

**Comment by medcharleslaidi** [comment]
Actually I didn't wanted to give CanICA a mask, but when just doing : 

`canica = CanICA(n_components=21,   
                smoothing_fwhm=6., 
                memory="nilearn_cache", memory_level=2, 
                threshold=3., verbose=10, random_state=0)
canica.fit(func) `

I had the : 
> 
ValueError: The mask is invalid as it is empty: it masks all data.
> error

So I assumed that CanICA wasn't able to compute the mask and that I should create the mask myself...

**Comment by GaelVaroquaux** [comment]
So the automatic masking fails. It would be interesting for us to
reproduce. What is the exact set of data that you are putting in. We
might have it available on our computers, as we have also looked at
ABIDE. Cc @abraham

**Comment by medcharleslaidi** [comment]
Using the soft intersection of the masks of my different subjects just gave me a fairly similar result : 

![mask3](https://cloud.githubusercontent.com/assets/11093149/18515149/9f1d7112-7a94-11e6-80d7-c49683b9a335.png)

I used data from the "UM" sample from abide i  preprocessed with dparsf
I could easily send you this sample (I'm working at the 2nd floor of Neurospin !).  
Would also be very interested if you guys are planning to schedule a nilearn tutorial at neurospin or elsewhere. 

Thanks for your help !

**Comment by GaelVaroquaux** [comment]
> I could easily send you this sample (I'm working at the 2nd floor of Neurospin !).

OK. Let's see this together tomorrow, I am not in Neurospin today. Let's
sit down at your computer and debug this. Grab me at some point.

**Comment by GaelVaroquaux** [comment]
I saw with @medcharleslaidi today. The problem was that he was feeding in images that were already zero-meaned and variance-normalized. As a result, the mask extraction was failing.

To prevent this issue, we should do two things. First work on reporting: if @medcharleslaidi had been able to show us a report, we would have immediately diagnosed the problem. Second, we can add a warning in the mask extraction routines if they fail. It might prompt the user to look at their data. I have added #1276 as an enhancement issue on this subject.

**Comment by Borda** [comment]
@GaelVaroquaux  may you please help me with an application of your proposed solution on my case? I have a 2D  image - atlas, and sample images created by randomly activating particular patterns, so there is no mask needed but I still receive the error...

```
import numpy as np
import nibabel as nib

template = np.zeros((64, 64), dtype=int)
template[10:30, 15:45] = 1
template[40:60, 20:35] = 2
template[15:40, 35:55] = 3

weights = np.random.randint(0, 2, (500, 3))
weights = np.hstack(([[0]] * 500, weights))
w_sum = np.sum(weights, axis=1)
weights[w_sum == 0, 1] = 1

images = [lut[template] for lut in weights]
nii_imgs = [nib.Nifti1Image(np.expand_dims(img, axis=0), affine=np.eye(4)) for img in images]

from nilearn.decomposition import CanICA
canica = CanICA(n_components=3, memory_level=2,
                threshold=3., n_init=5, verbose=1)
canica.fit(nii_imgs)
```
Gives me:
`ValueError: The mask is invalid as it is empty: it masks all data.`

**Comment by bthirion** [comment]
when defining canica, use the folloing argument `mask_strategy='background'`
So that the mask estimator knows that the brain mask is obtained by removing the values in the background, ie 0.

**Comment by Borda** [comment]
@bthirion I did but the error is the same, please try to run the example....

**Comment by bthirion** [comment]
2 things are problematic in your examples: i) images are actually 2D ii) they're full of zeros.
A slight modification of your example avoids the issue
```
import numpy as np
import nibabel as nib

template = np.zeros((64, 64, 5), dtype=int)
template[10:30, 15:45, 1:4] = 1
template[40:60, 20:35, 1:4] = 2
template[15:40, 35:55, 1:4] = 3
bg = template * 0
bg[5:45, 10:55] = 1

weights = np.random.randint(0, 2, (500, 3))
weights = np.hstack(([[0]] * 500, weights))
w_sum = np.sum(weights, axis=1)
weights[w_sum == 0, 1] = 1

images = [bg + lut[template] for lut in weights]
nii_imgs = [nib.Nifti1Image(img, affine=np.eye(4)) for img in images]

from nilearn.decomposition import CanICA
canica = CanICA(n_components=3, memory_level=2,
                threshold=3., n_init=5, verbose=1)
canica.fit(nii_imgs)
```

**Comment by Borda** [comment]
@bthirion so you say that it does not work correctly for 2D images?
One of my real applications is creating an atlas on binary images which are full of zeros...

**Comment by GaelVaroquaux** [comment]
> @bthirion so you say that it does not work correctly for 2D images?

Indeed.

> One of my real applications is creating an atlas on binary images which are
> full of zeros...

That is an unusual brain image. Many small things will fail on this.
