### ISSUE TITLE
NiftiMasker.transform() not biggish-data ready

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#1281]
Running `transform()` on a dozens of Nifti images does still not fly well with the masker family it appears. Concrete example: It does not work well for me to apply a 50-region NiftiLabelsMakser on 500 HCP VBM volumes. Could one solution be to internally batch the transformation by chunking image sets and putting the together without the user/coder having to interact with the process or having to introduce a new argument like `batch_size` ?

**Comment by AlexandreAbraham** [comment]
We noticed with @KamalakerDadi some unusual memory consumption when masking. We are currently investigating it. If anybody can run profiling on masking code, that would be helpful.

**Comment by GaelVaroquaux** [comment]
I am closing this issue: it's not helpful. It's a general comment, and not something that someone (eg an external person to the project) can tackle.
