### ISSUE TITLE
There is no vec_to_sym function

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#1282]
We would need this for visualisation.

**Comment by KamalakerDadi** [comment]
I saw there is. May be I am missing something ?

**Comment by AlexandreAbraham** [comment]
SOrry, vec_to_sym ;)

**Comment by GaelVaroquaux** [comment]
> We would need this for visualisation.

Are you sure that you don't mean the converse: vec_to_sym? It seems to me
that this is what we would need for visualization.

**Comment by KamalakerDadi** [comment]
Ok. Yes PR #1236 in progress

**Comment by salma1601** [comment]
This PR #1236 has many things that may be useful in it, including `vec_to_sym`. I am not going to finish it before I am sure of how we do the statistical testing for the `tangent` coefficients. I am working on this right now, but I can in the meantime remove the statistical testing part, and address all the comments.
Just tell me if this is useful for you so I do it @AlexandreAbraham  @GaelVaroquaux .

**Comment by KamalakerDadi** [comment]
There is now vec_to_sym function in master with this PR #1236. Closing.
