### ISSUE TITLE
connectome.sym_to_vec: add option to include/exclude the diagonal

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#1289]
This could be useful in many instances, where the diagonal is ones-only.

**Comment by salma1601** [comment]
there is, a `discard_diagonal` option has been added in version 0.2.
@KamalakerDadi do you think I should add it in `ConnectivityMeasaure`, in addition to the `vectorize` ?

**Comment by KamalakerDadi** [comment]
>@KamalakerDadi do you think I should add it in ConnectivityMeasaure, in addition to the vectorize ?

Yes, I think so. Basically, we should also give class parameter option to discard or not the diagonal if vectorize is True. ping @GaelVaroquaux @AlexandreAbraham ?

**Comment by bthirion** [comment]
Fixed. Closing.
