### ISSUE TITLE
RSN templates

### ISSUE THREAD

**Issue by alexsavio** [nilearn/nilearn#1290]
Hi,
I am working on resting-state network templates using the ICA output from MIALAB's GIFT and the Allen RSN templates.
I have implemented a class that:
- reads the GIFT RSN template input format (a nifti and a txt file with labels and indices),
- gives a few helpers to work with these files, and
- measures goodness-of-fit (as in Zhou et al., Brain, 2010) and correlation against a given set of subject IC spatial maps.

My questions:
1) is there any plan to do subject reconstruction of the spatial maps from group CanICA or DictLearning? If yes, any interest in doing it? I could start this, but would definitely need help with the maths, or any reference to the method that you prefer.
2) Is there any interest in this RSN templates development to be included in nilearn?

If yes, any comment on how to proceed, I would love to contribute.

This is a WIP of what I mention:
https://github.com/Neurita/pypes/blob/rsn/pypes/postproc/rsn.py
I would move outside the more complex functions in the class, and also optimise them.

**Comment by GaelVaroquaux** [comment]
2 things that come to my mind:

- We should implement a fetcher to these templates
- This is related to https://github.com/nilearn/nilearn/pull/1284
  Ideally, we should have one function useable for both purposes.

**Comment by alexsavio** [comment]
Sounds good to me, to begin with. The unthresholded Allen RSN templates are here:
http://mialab.mrn.org/data/index.html
The labels file should be included in the code, since it is not available online. I built one using a Figure in their paper as a reference. I will start with the fetcher later this week (I have a deadline on Wednesday and I am procrastineering).

I was thinking on a simple helper class to manage these RSN templates and labels and separate measure functions for each functionality, such the Jaccard coefficient mentioned in #1284, etc..., if these goes into nilearn.

**Comment by GaelVaroquaux** [comment]
> I was thinking on a simple helper class to manage these RSN templates and
> labels and separate measure functions for each functionality,

I'd rather start with functions (think about the great talk on the
"functional core" at Euroscipy).

**Comment by alexsavio** [comment]
Okay, a bunch of functions will also do the job :)

**Comment by KamalakerDadi** [comment]
Can this be closed in favour of #1295

**Comment by GaelVaroquaux** [comment]
Yes indeed: closing as fixed by #1295 / #1335
