### ISSUE TITLE
Unexpected behavior from 'subject' argument on haxby fetcher

### ISSUE THREAD

**Issue by Joaoloula** [nilearn/nilearn#1313]
The docstring says the `subjects` argument in `fetch_haxby` is a list containing the subjects to be fetched, but it actually also accepts an int as argument, in which case it behaves as the deprecated `n_subjects`. This is problematic because in this case an unaware user can pass an int n as the argument and run  `haxby_dataset.func[0]`, which will return data for subject 1 instead of subject n. It seems to me that we should either:
- Make this use case explicit in the docstring or;
- Throw an error when `subjects` is an int.

**Comment by bthirion** [comment]
Please update the docstring.
(my preference was two have two different arguments: `subjects` and `n_subjects` but I was not convincing enough...)

**Comment by AlexandreAbraham** [comment]
> my preference was two have two different arguments: `subjects` and `n_subjects` 

+1

**Comment by AlexandreAbraham** [comment]
@bthirion I merged the PR of Joao because it makes doc better. Do you want me to open an issue about the two different args?

**Comment by bthirion** [comment]
No. Let's see if users complain.
