### ISSUE TITLE
Inconsitency of having and not having argument `threshold` in add_overlay and add_contours

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#1317]
This has rather surprising behaviour when using `add_contours` with `filled=True`. Example of one suprising behaviour can be seen from a plot in PR #1315. 

It appears that we need an argument called `threshold=1e-6` in `add_contours` for the same terminology in consistent with `add_overlay` to suppress out minimum background value given in `threshold`.

**Comment by KamalakerDadi** [comment]
Any thoughts on this ?

If there is an agreement that we need threshold argument in add_contours, I can fix that in PR #1315.
Please let me know your thoughts.

**Comment by GaelVaroquaux** [comment]
I am +1 on changing threshold in add_contours from None to 1e-6, as in
add_overlay.

**Comment by KamalakerDadi** [comment]
>I am +1 on changing threshold in add_contours from None to 1e-6, as in add_overlay.

Thank you, I will address this in PR #1315

**Comment by KamalakerDadi** [comment]
Closing this one. It has been addressed in PR #1315
