### ISSUE TITLE
update COBRE fetcher

### ISSUE THREAD

**Issue by pbellec** [nilearn/nilearn#1319]
A number of issues were raised with the COBRE preprocessed dataset since its integration:
- First and foremost, the dataset was too big (8 GB)
- Too many steps of the preprocessing had been fixed ("scrubbing", regression of certain confounds, etc) while this could be done easily with nilearn
- also there were some discrepancies between the ids used to name the files and the ids used in the public phenotypic data

I have prepared a new figshare release that addresses these issues:
- fMRI data is now resampled at 6 mm isotropic and encoded with 16 bit integers. Size has dropped to 620 MB.
- Data is now released with minimal preprocessing (motion correction, BOLD-T1, T1-template registration, no smoothing, no regression of confounds, no scrubbing). A spreadsheet (gzipped tabular-separated values) is released for each fMRI dataset, with a fairly comprehensive list of confounds. Those can be grabbed to run regression/scrubbing in nilearn, although some of these operations can also be done independently using nilearn tools. 
- Data come with a consolidated phenotypic_data.tsv.gz file. It includes demographics and diagnostic data, as well as measures of motion with/without scrubbing, that can be used to filter the subjects or match patients/controls based on motion levels. 

The confounds and phenotypic data are described in two separate json files. The files as well as a markdown description of the dataset (README.md) are available here https://figshare.com/articles/COBRE_preprocessed_with_NIAK_0_17_-_lightweight_release/4106844

Note that the registration of all volumes have been checked visually. An interactive report (including registration and motion) is available here
https://simexp.github.io/qc_cobre/registration.html

@KamalakerDadi could you update the cobre fetcher and companion tutorial?

**Comment by KamalakerDadi** [comment]
Thanks for the updates and for new light weight data. I will definitely make time to look into this as well work on updating fetcher and companion tutorial. I will get back to you in case I have any doubts/questions.

**Comment by bthirion** [comment]
That sounds great indeed.

**Comment by GaelVaroquaux** [comment]
> That sounds great indeed.

+1! Pretty awesome.

I'd like to change all our example to use COBRE rather than ABIDE at some
point, as the prediction of phenotype actually somewhat works on COBRE.

**Comment by pbellec** [comment]
I should have double checked the release. Althgouh all files are listed, with the correct size, the download links are broken. I probably messed up with their upload API. I've contacted figshare support, will let you know when it works.

**Comment by pbellec** [comment]
So this took me much more time than I would have liked, but I finally figured out their API. The collection is now stored here: https://figshare.com/articles/COBRE_preprocessed_with_NIAK_0_17_-_lightweight_release/4197885 I checked and the "download all" works, and files are identical to what I uploaded. So I think it's now ready to go, sorry about the hicup. FYI over my university network I had download  speeds of 500k-1M/sec, so it took a good 15 mns to download the whole collection of ~150 subjects.

**Comment by GaelVaroquaux** [comment]
The json file giving the list of download_url is no longer up to date. I think that found the proper request to figshare to get the json with the list of files: https://api.figshare.com/v2/articles/4197885

**Comment by KamalakerDadi** [comment]
This should also work https://figshare.com/api/articles/4197885/1/files

**Comment by GaelVaroquaux** [comment]
That's probably for the version 1 of the API.

**Comment by darya-chyzhyk** [comment]
The last link works better, thanks @KamalakerDadi

**Comment by pbellec** [comment]
@darya-chyzhyk sorry I missed that. Would it be useful if I updated list_files.json ? Best,

Pierre

**Comment by darya-chyzhyk** [comment]
Thank you @pbellec ! 

It would be helpful.
Could you please also update keys_phenotypic_data.json and keys_confounds.json.
