### ISSUE TITLE
plot_connectome node coordinates issue

### ISSUE THREAD

**Issue by khamael** [nilearn/nilearn#1320]
I've done a per-connection correlation between a set of connectomes and some psycometric scores - doesn't really matter here, just that I have a 'matrix' I want to plot using plot_connectome, so I easily see where are the interesting connections. However I'm having issues with the node_coords, as they end up outside of the glass brain.

I'm trying also to get each region node by computing the center_of_mass (as I found in some previous issues here), but there's still issues. So what is the coordinate frame here? What do you mean by world space?

Thanks

**Comment by bthirion** [comment]
Dear @khamael,

Your data are probably not in MINI space, which is required for 'plot_connectome' to work.
Sincerely,

**Comment by khamael** [comment]
Suggestions how to convert to MNI?

**Comment by bthirion** [comment]
This is the process called `(spatial) normalization`, which is carrid out with software like SPM12 (Dartel), FSL (Fnirt) or ANTS.
Look at nipype to find a simple interface to these functions. they usually require an anatomical image to register the images to the template.

**Comment by khamael** [comment]
yeah, so I'm registering the cortical labels file into the standard/MNI152_T1_2mm
I get the x,y,z of that new file, and when I plot it, it's kinda in the glass brain, but not quite:
<img width="666" alt="screen shot 2016-11-01 at 7 20 28 pm" src="https://cloud.githubusercontent.com/assets/5000837/19901701/4df029f2-a068-11e6-9072-d2ba6f31a453.png">

**Comment by GaelVaroquaux** [comment]
I think that either you are not correctly registered, or the way you compute the x, y, z coordinates of the nodes is wrong.

**Comment by khamael** [comment]
Ok, I've figured out. I was using x,y,z from LabelStats but something was wrong there. It's nice now! thanks
