### ISSUE TITLE
Wrong reference for dictionary learning in current nilearn?

### ISSUE THREAD

**Issue by dawnsong** [nilearn/nilearn#1323]
Dear Dr. Gaël and Arthur, 

The reference given in the help and code of diction learning is:
Gaël Varoquaux, Gramfort, A., Pedregosa, F., Michel, V., Thirion, B., 2011. Multi-subject dictionary learning to segment an atlas of brain spontaneous activity, in: Information Processing in Medical Imaging. Springer, pp. 562–573.

But after reading the code, it looks like the reference should be:
Mensch, A., Varoquaux, G., Thirion, B., 2016. Compressed online dictionary learning for fast resting-state fMRI decomposition, in: 2016 IEEE 13th International Symposium on Biomedical Imaging (ISBI). Presented at the 2016 IEEE 13th International Symposium on Biomedical Imaging (ISBI), pp. 1282–1285. doi:10.1109/ ISBI.2016.7493501

Am I correct? If I am correct, will you also include MSDL method into nilearn in future?

Best,
Xiaowei

Reference:

- [nilearn dictionary learning help](http://nilearn.github.io/auto_examples/03_connectivity/plot_compare_resting_state_decomposition.html)

- [nilearn dictionary learning code](https://github.com/nilearn/nilearn/blob/master/nilearn/decomposition/dict_learning.py)

**Comment by bthirion** [comment]
You probably mean that the Varoquaux method in 2011 wans not an online version. I'm not sure that the implementation here uses the tricks of the ISBI paper though. 
@arthurmensch can you confirm ?

**Comment by dawnsong** [comment]
Thanks for your response, Prof. Thirion, @bthirion .
I guess batch/online might be also one difference, as you pointed out, but I don't know where to download and try MSDL.
In the current "dict_learning.py", the penalty is only L-1 norm (from sklearn's Dictionary Learning), not like Varoquax's MSDL, which used smooth-Lasso. 
And the current "dict_learning.py" feed DL  with PCA reduced in subject-level and temporal-concatenated to group level. While MSDL's cost fucntion directly modeled subject's data, does not use PCA to reduce subject's data. I guess it is very similar and should be Arthur's 2016 ISBI paper.

Best,
Xiaowei

**Comment by GaelVaroquaux** [comment]
Xiaowei is right, and the code that we use is actually pretty much the
paper by Arthur in ISBI.

The MSDL is much more complicated to code, and is still in the pipeline
:(. It's also much slower.

**Comment by dawnsong** [comment]
Dear Dr. Varoquaux, @GaelVaroquaux , thanks a lot for confirmation :)
The current Arthur's online DL version is lightning fast for my test data!

**Comment by KamalakerDadi** [comment]
Closing fixed with PR #1393
