### ISSUE TITLE
fetch_oasis_vbm with dartel_version=False crashes

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1324]
```Python
oasis = datasets.fetch_oasis_vbm(dartel_version=False)
```
returns
>IOError: Fetching aborted: [Uncompress] unknown archive file format: /home/salma/nilearn_data/oasis1/31882ed26d0636264fe56f5ceae2f898/archive.tgz

**Comment by ncullen93** [comment]
I get same error fetching other datasets in both Mac and Windows... wtf

**Comment by GaelVaroquaux** [comment]
> wtf

What do you mean?

**Comment by ncullen93** [comment]
No offense.. it's just weird. No datasets seem to be working.. Working on it right now

**Comment by ncullen93** [comment]
I'm inclined to think it's the path to the files that has changed.. something w/  https://www.nitrc.org/frs/download.php/../archive.tgz

**Comment by GaelVaroquaux** [comment]
> I'm inclined to think it's the path to the files that has changed.. something w / https://www.nitrc.org/frs/download.php/../archive.tgz

The datasets/struct.py contains the URL. If you can change it and tell us
what works, we'll fix it.

**Comment by AlexandreAbraham** [comment]
Superseded by #1327

**Comment by GaelVaroquaux** [comment]
This should not be fixed.

**Comment by AlexandreAbraham** [comment]
Now that the download links are active again, you have to clear your `nilearn_data`directory (or at least the corrupted datasets) to force downloading of files.

**Comment by GaelVaroquaux** [comment]
> Now that the download links are active again, you have to clear your
> nilearn_datadirectory (or at least the corrupted datasets) to force downloading
> of files.

Good point.

It would probably be a good thing to trigger a new download when the data
is corrupted.
