### ISSUE TITLE
context manager for plotting module

### ISSUE THREAD

**Issue by shoshber** [nilearn/nilearn#1326]

**Comment by GaelVaroquaux** [comment]
What do you mean?

**Comment by shoshber** [comment]
Ah, sorry, I meant to come back and flesh this out. Since the return value of `plotting.plot_*` functions should be closed (`retval.close()`), a context manager that can do that automatically would be 👍, since it reduces the chance of programmer error . Similar to python's built-in context manager for opening files (`with open('file.txt'):`). An example implementation: https://github.com/nipy/nipype/blob/master/nipype/utils/tmpdirs.py. Should be quick enough work, but I don't have time to do it myself at the moment!

**Comment by bthirion** [comment]
Closing for now.
