### ISSUE TITLE
All NITRC files are gone

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#1327]
It seems that we cannot host files anymore on NITRC. This is critical as most of the datasets are hosted there. Plus, NITRC does not return a 404 error, meaning that nilearn thinks it downloads the correct files but explodes afterward.

Plan of action:
- First, update nilearn to add basic checks after download: either specify the size explicetely, or a hash, or simply check that binary files do not start with <html>
- Then, upload the files on another hosting service and update all the links
- Finally, implement something to force nilearn downloading the data again if a new version is available (here, the new version will be the one hosted elsewhere). This is something already asked for neurovault fetcher so it is not orthogonal to nilearn's roadmap.

**Comment by GaelVaroquaux** [comment]
I think that I've fixed the problem. It was a configuration switch to flip in the NITRC set up (disable the external downloads).

Everything should be working now. Could people check (I did a small check myself).

**Comment by AlexandreAbraham** [comment]
Fiou, I'm relieved :P.

Small check passed for me. For people having problem: you can clear the nilearn_data directory (sorry for the inconvenience).

**Comment by salma1601** [comment]
`fetch_oasis_vbm` works OK for me now. Thanks
