### ISSUE TITLE
High Variance Confounds - add memory parameter

### ISSUE THREAD

**Issue by ccvanschie** [nilearn/nilearn#1331]
I think it would be practical for users when nilearn.image.high_variance_confounds has an option to assign a memory like in the niftilabelsmasker. 
Of course it is possible to use joblib but this may not be so easy or accessible for everyone and just like e.g. extracting timeseries, calculating high variance confounds can take some time.

**Comment by GaelVaroquaux** [comment]
The high variance confound code that we have is more ment for advanced
users.

I wonder however if it would not be good to add it, in some way, as an
option to the maskers. In such situation, it would be easy to insert
memory on it.

**Comment by KamalakerDadi** [comment]
> I wonder however if it would not be good to add it, in some way, as an option to the maskers. In such situation, it would be easy to insert memory on it.

+1. Before reaching masker level, I think it is good start with adding in function level.

**Comment by GaelVaroquaux** [comment]
> +1. Before reaching masker level, I think it is good start with adding in
> function level.

Well, the thing is that at the function level it is trivial to add if you
know joblib (just use joblib on the function). As this function is for
advanced user, we should rather point them to use joblib (for instance
with a sub-section in the advanced part of the documentation).

**Comment by KamalakerDadi** [comment]
@ccvanschie Do you wanna do Pull Request (PR) ?

**Comment by ccvanschie** [comment]
Yes, but it is not clear to me how/where you would like to see this. The code is indeed quite simple (see below) and can be added as an example to the documentation. 

p.s. Perhaps this issue is related to issue #104.

```python
from nilearn.image import high_variance_confounds
from sklearn.externals.joblib import Memory
#To improve processing time of high_variance_confounds function use cache
mem = Memory(cachedir = 'nilearn_cache')
hvc = mem.cache(high_variance_confounds)
```

**Comment by bthirion** [comment]
See #1241. Closing for now.
