### ISSUE TITLE
`find_cut_slices()` returns slices from only one hemisphere?

### ISSUE THREAD

**Issue by shoshber** [nilearn/nilearn#1332]
`find_cut_slices()` gives a puzzling result where cuts in the `x` direction (see below) show only one hemisphere of the brain. I'm not sure what the origin of this is, perhaps I'm misusing nilearn's api. Does anyone know what the problem might be?

see the top row here:
http://htmlpreview.github.io/?https://github.com/shoshber/pastebin/blob/master/reports/betnilearncuts.html

the above html was calculated using this code:
https://github.com/shoshber/niworkflows/blob/deprecbbox/niworkflows/viz/utils.py#L72

**Comment by bthirion** [comment]
Stalled, closing.
