### ISSUE TITLE
Restyle frontpage

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1334]
At some point we should restyle the frontpage (only the frontpage). Here is an example of modern design that we should strive for
http://www.dataforgood.fr/

**Comment by banilo** [comment]
I am all for it!

**Comment by GaelVaroquaux** [comment]
> I am all for it!

You mean you're going to do it? Awesome!

**Comment by GaelVaroquaux** [comment]
@katjaq mention that she might give a hand tomorrow, so I am adding a bit of information here:

# Potential sources of inspiration

* http://jupyter.org/
* http://studyforrest.org/

In both of these, I like the spatial layout of the information with a set of horizontal blocks well separated

# Information to put on there

* First a very short text telling us what is nilearn (as on the jupyter page or the studyforest page)

* Some "Using nilearn links", maybe in a horizontal banner

* Cool things about nilearn, maybe each with an image:
  - Easy plotting
  - Powerful decoding
  - Functional connectivity
  - Versatile Python scripting

* The "Nilearn is part of the nipy ecosystem" should die: we already have a link to nipy.

# Modifying the sidebar

We need to integrate the sidebar in the page:

* The news becomes a box, probably on the top right of the page

* The installation instruction link should probably be in the body of the page, maybe in a "Using nilearn" box, alongside with the links to Getting started, examples and user documentation

* The developer information should also be in the body of the page, in a "Development" box

* The citation would go next to the developer information

* The "next topic" section should die.

**Comment by GaelVaroquaux** [comment]
I've refactored the HTML and the CSS to enable the redesign of the front page: it's on my "restyle doc" branch: https://github.com/GaelVaroquaux/nilearn/tree/restyle_doc

**Comment by tsalo** [comment]
Can we close this given @alexisthual's work on the website?

**Comment by bthirion** [comment]
Indeed, closing. Thx !
