### ISSUE TITLE
A binary file in the repo ?

### ISSUE THREAD

**Issue by mrahim** [nilearn/nilearn#1337]
I'm wondering why do we have this binary file  `nilearn/datasetsc` ?
https://github.com/nilearn/nilearn/blob/948a00ea0dff48e8c04eb9d6335648a98809ef4b/nilearn/datasetsc

**Comment by AlexandreAbraham** [comment]
Looks like an error.

**Comment by GaelVaroquaux** [comment]
> Looks like an error.

Let's kill it.

**Comment by GaelVaroquaux** [comment]
Thanks. Fixed.

PS: congratulations for getting the issue number 1337!
