### ISSUE TITLE
resample_img functions incompatible with scipy 0.18

### ISSUE THREAD

**Issue by jnecus** [nilearn/nilearn#1343]
Hello,

I found that resample_to_img() and resample_img() functions do not appear to work with the latest version of Scipy 0.18.

I reverted my version of Scipy back to 0.15 which appeared to fix the problem.

Thanks,
Joe

**Comment by bthirion** [comment]
Could you provide a snippet of code to reproduce the issue ?
Thx,

**Comment by jnecus** [comment]
I first tried using both functions to resample my nifti image:

`nilearn.image.resample_to_img(source,target)`

which gave the following warning, and the output file was empty:

> UserWarning: The behaviour of affine_transform with a one-dimensional array supplied for the matrix parameter has changed in scipy 0.18.0.

I then downgraded Scipy to version 0.15 and it worked fine.

**Comment by GaelVaroquaux** [comment]
>     UserWarning: The behaviour of affine_transform with a one-dimensional array
>     supplied for the matrix parameter has changed in scipy 0.18.0.

> I then downgraded Scipy to version 0.15 and it worked fine.

This is just a warning.

The latest nilearn are compatible with scipy 0.18.
