### ISSUE TITLE
Absurd MemoryError

### ISSUE THREAD

**Issue by lrq3000** [nilearn/nilearn#1364]
I have an issue while loading one sample dataset: I always get a MemoryError, even when I only try to draw a few slices for only one subject.

I reproduced this error on 3 different computers: 2 laptops with Windows 7 x64 and 4GB of RAM, and 1 research workstation with 16 GB.

I just installed nilearn on all these computers using `pip install nilearn`.

Here is the code used:

```
import nilearn
print(nilearn.__version__)

from nilearn import datasets

# By default 2nd subject will be fetched
haxby_dataset = datasets.fetch_haxby('datasets')

# print basic information on the dataset
print('Mask nifti image (3D) is located at: %s' % haxby_dataset.mask)
print('Functional nifti image (4D) is located at: %s' %
      haxby_dataset.func[0])

func_filename = 'datasets\\haxby2001\\subj1\\bold.nii.gz'

from nilearn.image import index_img
func_filename = index_img(haxby_dataset.func[0], slice(0,1))
func_filename
```

And here is the output:
```
0.2.6
Mask nifti image (3D) is located at: datasets\haxby2001\mask.nii.gz
Functional nifti image (4D) is located at: datasets\haxby2001\subj2\bold.nii.gz
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-1-92d8185ad49b> in <module>()
     15 
     16 from nilearn.image import index_img
---> 17 func_filename = index_img(haxby_dataset.func[0], slice(0,1))
     18 func_filename

C:\Anaconda2\lib\site-packages\nilearn\image\image.pyc in index_img(imgs, index)
    554     """
    555     imgs = check_niimg_4d(imgs)
--> 556     return _index_img(imgs, index)
    557 
    558 

C:\Anaconda2\lib\site-packages\nilearn\_utils\niimg_conversions.pyc in _index_img(img, index)
     72     """Helper function for check_niimg_4d."""
     73     return new_img_like(
---> 74         img, img.get_data()[:, :, :, index], get_affine(img),
     75         copy_header=True)
     76 

C:\Anaconda2\lib\site-packages\nibabel\spatialimages.pyc in get_data(self, caching)
    580         if self._data_cache is not None:
    581             return self._data_cache
--> 582         data = np.asanyarray(self._dataobj)
    583         if caching == 'fill':
    584             self._data_cache = data

C:\Anaconda2\lib\site-packages\numpy\core\numeric.pyc in asanyarray(a, dtype, order)
    523 
    524     """
--> 525     return array(a, dtype, copy=False, order=order, subok=True)
    526 
    527 def ascontiguousarray(a, dtype=None):

C:\Anaconda2\lib\site-packages\nibabel\arrayproxy.pyc in __array__(self)
    142     def __array__(self):
    143         # Read array and scale
--> 144         raw_data = self.get_unscaled()
    145         return apply_read_scaling(raw_data, self._slope, self._inter)
    146 

C:\Anaconda2\lib\site-packages\nibabel\arrayproxy.pyc in get_unscaled(self)
    137                                        offset=self._offset,
    138                                        order=self.order,
--> 139                                        mmap=self._mmap)
    140         return raw_data
    141 

C:\Anaconda2\lib\site-packages\nibabel\volumeutils.pyc in array_from_file(shape, in_dtype, infile, offset, order, mmap)
    515     if hasattr(infile, 'readinto'):
    516         data_bytes = bytearray(n_bytes)
--> 517         n_read = infile.readinto(data_bytes)
    518         needs_copy = False
    519     else:

C:\Anaconda2\lib\gzip.pyc in read(self, size)
    266             try:
    267                 while size > self.extrasize:
--> 268                     self._read(readsize)
    269                     readsize = min(self.max_read_chunk, readsize * 2)
    270             except EOFError:

C:\Anaconda2\lib\gzip.pyc in _read(self, size)
    317             raise EOFError, 'Reached EOF'
    318 
--> 319         uncompress = self.decompress.decompress(buf)
    320         self._add_read_data( uncompress )
    321 

MemoryError:
```

Any idea what is causing this and how to fix it? Thanks a lot for any suggestion!

**Comment by GaelVaroquaux** [comment]
> I have an issue while loading one sample dataset: I always get a
> MemoryError, even when I only try to draw a few slices for only one
> subject.

> I reproduced this error on 3 different computers: 2 laptops with
> Windows 7 x64 and 4GB of RAM, and 1 research workstation with 16 GB.

Are you running a 32bit installation of Python? If you are running a
32bit install, it cannot use all your memory.

**Comment by lrq3000** [comment]
Yep, I guess you got it. I indeed use 32bit install because it's easier to develop 32-bit Cython extensions than with 64-bit. I'm going to try to reinstall Anaconda 64-bit.

**Comment by lrq3000** [comment]
But still, is it normal it's buggy when I tried to access only 2 slices of one subject?

**Comment by GaelVaroquaux** [comment]
> But still, is it normal it's buggy when I tried to access only 2 slices
> of one subject?

Yes, you still need to address the whole array.

**Comment by lrq3000** [comment]
Ok great, I can confirm it works. Indeed, Py 32bits can only allocate 2GB (on Windows) per process. So Py 64bits is mandatory.

Maybe you should add a note in the documentation intro and/or in the readme? I think this is a pretty important point (right now I'm at a nilearn workshop where several people have the exact same error, and I guess the same cause).

**Comment by GaelVaroquaux** [comment]
> Maybe you should add a note in the documentation intro and/or in the
> readme? I think this is a pretty important point (right now I'm at a
> nilearn workshop where several people have the exact same error, and I
> guess the same cause).

It's in bold in the installation documentation:
http://nilearn.github.io/introduction.html#installation

I am not sure that we can do better.

**Comment by lrq3000** [comment]
Ah new info: it works on my 16 GB machine, but not on my 4GB laptops, even with Python 64-bits. Is it normal with this dataset? (I'm very new to nilearn, sorry...)

About the doc, yes indeed I missed it, but maybe you can just add a note about why 64 bits is necessary and not 32 bits?

**Comment by GaelVaroquaux** [comment]
> Ah new info: it works on my 16 GB machine, but not on my 4GB laptops,
> even with Python 64-bits. Is it normal with this dataset? (I'm very new
> to nilearn, sorry...)

Are you sure that you are indeed using the 64bit Python, and not an old
one that is lying around? I am a bit surprised that it breaks.

> About the doc, yes indeed I missed it, but maybe you can just add a
> note about why 64 bits is necessary and not 32 bits?

You mean that on top of having it in the title of the first step and in
bold in the text we should add a note? You would read the note but not
the title of the first step? My experience with instructions has been
that the more we put, the less people read, so I am not convinced that it
would change anything.

**Comment by lrq3000** [comment]
Can't test right now, I'll dig more and report in a few hours.

About the doc, I meant not necessarily on install section but it can be in troubleshooting or something like that, because I tried googling and found no answer, which is why I had to post, it's not a trivial bug. Additionally, on the install page, this:

> We recommend that you install a complete scientific Python distribution like 64 bit Anaconda 

Could be replaced by this:

> We recommend that you install a complete scientific Python distribution like 64 bit Anaconda (but not 32 bit).

As it makes it clear that using 64 bit is not just an advice but mandatory. But that's just my humble opinion.

**Comment by GaelVaroquaux** [comment]
> About the doc, I meant not necessarily on install section but it can be
> in troubleshooting or something like that, because I tried googling and
> found no answer, which is why I had to post, it's not a trivial bug.

32bit cannot address the data by definition. It's not something about
nilearn. It's just that no 32 bit program can address that data. So yes
it's trivial for a certain definition of trivial. I agree that for a non
technical person it maybe be not obvious.

But I don't understand how a non technical person ends up with a 32 bit
install of Python in 2017. CPUs for PCs and macs switched to 64bit in
2003. Windows XP 64bit was released in 2005. The default download for all
the Python distributions that I looked at is 64bit. Installing 32bit
requires a conscious choice. I would expect someone making that choice to
understand the consequences. There are many other unusual choices that
are possible such as using UCS2, which will lead to problems.

Unfortunately, we cannot add a troubleshooting entry for every problem
like this. The more we put in the documentation, the less people read it.

> Additionally, on the install page, this:

I've taken in account your feedback and made "64 bit" red. I frowned on
having it blinking.

**Comment by lrq3000** [comment]
An update on this issue, I checked the third computer where the 64bit install did not fix the issue, and in fact the RAM is 2GB, so no hope to be able to process such a big dataset. So problem solved, thanks a lot :)

About the choice of using 32 bits, please don't be so agressive, I already explained why I did that choice, but not [in details](http://stackoverflow.com/a/6983481/1121352). Indeed, Cython needs a C compiler, and on Windows there are [two choice](https://github.com/cython/cython/wiki/CythonExtensionsOnWindows)s: either use the simple and lightweight Microsoft Visual C++ Compiler for Python or install Visual Studio + appropriate Windows SDK C/C++ compiler. The first is of course way easier to setup than the second, in addition to being free.

So I'll just setup two python environments, no big deal, it's just that I never had any trouble with doing machine learning with my 32 bit version before on my main machine, so I didn't think about this being the issue. Thanks a lot for troubleshooting this so quickly.

**Comment by GaelVaroquaux** [comment]
I've been keeping open this tab in my browsing because I wanted to give a proper reply and never found time.

I agree with you that my tone / phrasing was inappropriate. My apologies.

As an explanation (but not an excuse: my behavior should not be excused or justified in any way): open source software developers get a huge amount of questions and suggestions. I am active on many projects, with many users. It's quite tiring.

**Comment by lrq3000** [comment]
Thank you for replying once again, I understand very well the strain of developing (and maintaining!) open source projects. Thank you for developing this great project, I will try to contribute when I'll have mastered it more :) Have a nice day!

**Comment by GaelVaroquaux** [comment]
> I will try to contribute when I'll have mastered it more :)

We'll be happy to have you onboard. I am not that grumpy usually :)

**Comment by lrq3000** [comment]
Haha, good to know!  ;)
