### ISSUE TITLE
Nested CV

### ISSUE THREAD

**Issue by antogeo** [nilearn/nilearn#1368]
Hello, 
Is there any nested CV planned to be implemented?
Best!

**Comment by ahoyosid** [comment]
What do you mean?. If you are talking about a meta-estimator which performs hyperparameter selection and model validation, you can check out this PR #698

**Comment by eickenberg** [comment]
and independently, nested cross-validation can be done with scikit-learn. nilearn is not going to provide anything that already exists in scikit-learn.
But maybe your question was more specific?

**Comment by antogeo** [comment]
Thank you for your quick responses! 
What I had in my mind was hyperparameter selection and is included in the #698 
Merci!
