### ISSUE TITLE
The confounds attribute should be documented better

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#137]
It is not pointed out that it is a list of csv files, and that the list should be ordered to match the order of the list of niimgs.

As well as the smoothing_fwhm and the t_r and low_pass, high_pass.

**Comment by juhuntenburg** [comment]
Does this refer to the reference doc or user guide?

The reference doc says:
"confounds: list of confounds, optional :
    List of confounds (2D arrays or filenames pointing to CSV files). Must be of same length than imgs_list."

So is it already solved or should the ordering be pointed out specifically?

**Comment by GaelVaroquaux** [comment]
I think that you are right, and that this issue has been fixed since then. 

I am closing it. Thanks a lot for checking things.

**Comment by banilo** [comment]
I agree. People have repeatedly asked me how the confound removal does work
exactly statistics-wise.

2015-07-13 11:54 GMT+02:00 Gael Varoquaux <notifications@github.com>:

> I think that you are right, and that this issue has been fixed since then.
>
> I am closing it. Thanks a lot for checking things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/issues/137#issuecomment-120877002>.
>



-- 
Viele Grüße,
Danilo
