### ISSUE TITLE
Doubt:  Dicom image com CT

### ISSUE THREAD

**Issue by rspadim** [nilearn/nilearn#1373]
Hi guys, could be possible use nilearn with DICOM CT (Computed tomography) files?

**Comment by GaelVaroquaux** [comment]
> Hi guys, could be possible use nilearn with DICOM CT (Computed tomography) files?

Not really. Nilearn doesn't accept DICOM images.

**Comment by AlexandreAbraham** [comment]
You can try dcm2nii to convert your files toward Nifti but I have never tried it.

**Comment by KamalakerDadi** [comment]
@rspadim Just curious, what you want to process using Nilearn with CT images ?
