### ISSUE TITLE
using canICA to denoise?

### ISSUE THREAD

**Issue by russellu** [nilearn/nilearn#1380]
Hello, i have managed to run canICA on my FMRI datasets, yielding physiologically plausible components in voxel space. 

i would like to use canICA to filter out noise by removing all components which are not related to my signal of interest (it was a visual task). 

so i want to return to my 3d+time FMRI dataset, but only use components which i will decide based on their spatial weight maps if they are contributing relevant signal. 

does anyone know how to do this? either canICA or DictLearning would be great. thanks!
Russell

**Comment by bthirion** [comment]
AFAIK there is no mechanism to select components (similar to FIX) nor to reconstruct time series from a subset of components. That would be a nice addition !

**Comment by GaelVaroquaux** [comment]
> AFAIK there is no mechanism to select components (similar to FIX) nor to reconstruct time series from a subset of components.

I think that the question was more related to the second aspect of your
sentence than the first one: the OP is OK selecting noisy components by
hand.

We should do an example implementing that.

**Comment by KamalakerDadi** [comment]
May be I am wrong. NiftiMapsMasker can be useful here ?

NiftiMapsMasker will extract timeseries signals from fmri datasets based on the components. Will it not be useful ?

**Comment by russellu** [comment]
Hey Kamalaker, yes that would be a good start, but then i actually want the timeseries from the hand-picked components to be projected back to 3d+t space, so i can examine the spatio-temporal signature of the sub-set of components.  

i will take a look at NiftiMapsMasker ,thanks!

**Comment by KamalakerDadi** [comment]
You can visualize your components. Then, you can use :func:`nilearn.image.index_img` to handpick component of your interest (http://nilearn.github.io/modules/generated/nilearn.image.index_img.html). Then, use NiftiMapsMasker to extract timeserie of this particular handpicked.

Note that: NiftiMapsMasker needs maps_img whose dimensions are (x, y, z, n_components/n_regions) -> 4D.

**Comment by russellu** [comment]
yes, i was able to accomplish that just now using NiftiMapsMasker. thanks!
however, i still need a way to filter out undesireable components from my original 3d+t FMRI, do you know how i can do this?

**Comment by KamalakerDadi** [comment]
No direct way. May be a try: You can use undesirable components turned to time series signal values to a confounds while fitting canica to fmri images.

**Comment by russellu** [comment]
ok. do you think it would be possible with DictLearning?

**Comment by KamalakerDadi** [comment]
Can you give it a try ?

**Comment by akatav** [comment]
> yes, i was able to accomplish that just now using NiftiMapsMasker. thanks!
> however, i still need a way to filter out undesireable components from my original 3d+t FMRI, do you know how i can do this?

@russellu Can you please upload this code snippet ?It'll be helpful for me too.

**Comment by jeromedockes** [comment]
In the future, for questions about usage, please post on Neurostars: https://neurostars.org/ and add the tag "nilearn" to your post

**Comment by tsalo** [comment]
Given that this issue reflects a usage question and the last post from the original author is three years old, can we close this?

**Comment by bthirion** [comment]
Closing, indeed. Thx.
