### ISSUE TITLE
Find cut slices and smoothing

### ISSUE THREAD

**Issue by alexsavio** [nilearn/nilearn#1383]
Hi,

I've found out that you perform a smoothing to find cut slices coordinates. For that, just before calling `_smooth_array` you convert the data type to float in:
https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/find_cuts.py#L228

My issue is in that some atlases have a "np.uint8" dtype, in this case `data.dtype.kind` is 'u', not 'i' as expected.

The following change solved my problem. Do you think it is a reasonable change for Nilearn?
```
if data.dtype.kind in ('i', 'u'):
    data = data.astype(np.float)
```

**Comment by GaelVaroquaux** [comment]
> The following change solved my problem. Do you think it is a reasonable change for Nilearn?

> if data.dtype.kind in ('i', 'u'):
>     data = data.astype(np.float)

Yes, preceeded by a comment that explains why it's necessary. Thanks!

**Comment by alexsavio** [comment]
PR in #1385. Merged. Thanks!
