### ISSUE TITLE
Running examples is too long 

### ISSUE THREAD

**Issue by mrahim** [nilearn/nilearn#1396]
Some examples can be shortened such as :
- ` nilearn/examples/02_decoding/plot_haxby_space_net.py `
- ` nilearn/examples/02_decoding/plot_mixed_gambles_space_net.py `

**Comment by salma1601** [comment]
I did a summary table for connectivity examples in
https://github.com/nilearn/nilearn/issues/1223

may be this can be useful for merging and shortening some examples
