### ISSUE TITLE
wish list: locate the peaks (maxima) in a volume

### ISSUE THREAD

**Issue by chrplr** [nilearn/nilearn#1397]
It would be nice to have a function which returns a list of the xyz coordinates of the first 'n' local maxima ? (or just the the n maximal voxels, without being necessarily local maxima)

**Comment by eickenberg** [comment]
n maximal voxels is

img.get_data().argsort()[::-1][:n]

a bit faster with argpartition.

This is quite different from finding local maxima, which for stability
should be smoothing followed by an intersection of masks indicating whether
a voxel value is larger than eqch of it's neighbors' values

**Comment by chrplr** [comment]
Thanks!
Now, I am just a bit unsure how I should then convert back into coordinates (to create a SphereMasker). I guess I must apply the affine transform.

**Comment by AlexandreAbraham** [comment]
One can use scikit-image to retrieve local maxima. I have this code but not sure it is still working:
`def find_poi(data, affine, smooth=10.):
    from skimage.feature.peak import peak_local_max
    # Smooth the data to remove meaningless local maxima
    markers_ind = _smooth_array(data, affine, fwhm=smooth)
    markers_ind = peak_local_max(markers_ind, exclude_border=False,
            min_distance=6)
    return markers_ind`

**Comment by tsalo** [comment]
Can `get_clusters_table` be used for this?
