### ISSUE TITLE
Variable unassigned

### ISSUE THREAD

**Issue by alexsavio** [nilearn/nilearn#1412]
`best_candidate` might not get assigned in
https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/find_cuts.py#L303

I think that a better error message would be helpful.

**Comment by KamalakerDadi** [comment]
Could you tell us your use case and reproducible script for variable unassigned ?
To see what's causing this.
Thanks

**Comment by alexsavio** [comment]
No, I can't. With just a look at the code I am pointing at you will see what condition makes this happen. There is no 'else' assigning any value to `best_candidate`. IMO the function is incomplete.

**Comment by KamalakerDadi** [comment]
I completely understood about this issue. But, how could we tackle this issue. In other words, what would be the ```best_candidate``` in ```else``` ?

**Comment by alexsavio** [comment]
Is `[0, 0, 0]` the central cut_coord? Else I would raise an exception.

**Comment by GaelVaroquaux** [comment]
> Is [0, 0, 0] the central cut_coord?

Yes.

> Else I would raise an exception.

Exceptions are counterproductive: this function is used in things like
plotting for reporting. It's very counterproductive when the whole
pipeline crashes because of finding a cut. Hence, return [0, 0, 0] seems
like the right option. Possibly raising a warning (after all, if people
are nitpicky, warnings can be captured).

**Comment by alexsavio** [comment]
I agree @GaelVaroquaux. Would you like me to do a PR?

**Comment by GaelVaroquaux** [comment]
> I agree @GaelVaroquaux. Would you like me to do a PR?

It would be great!

**Comment by tsalo** [comment]
I'm not sure if [`DEFAULT_CUT_COORDS`](https://github.com/nilearn/nilearn/blob/b36df65af7cb9926f5e4abc9ba3787353c90c349/nilearn/plotting/find_cuts.py#L28) was in use when this issue was opened, but since empty maps default to cutting at [0, 0, 0] (at least now), can this be closed?

**Comment by bthirion** [comment]
Anyay the issue has been inactive for three years. Closing.
