### ISSUE TITLE
ICA and variance normalization

### ISSUE THREAD

**Issue by chrisfilo** [nilearn/nilearn#1414]
Currently, CanICA has the option `standardize` set to True by default. This means intensity and variance normalization. According to [this work](http://mialab.mrn.org/software/gift/publications/2010_OHBM_Elena_ICAPrenormalization_submitted.pdf), variance normalization is detrimental for the stability of ICA components. Shouldn't we change this argument to take the following options:

- `False`
- `'intensity only'` (new default)
- `True` (intensity and variance standardization - old default)

**Comment by GaelVaroquaux** [comment]
> Currently, CanICA has the option `standardize` set to True by default. This means intensity and variance normalization. According to [this work](http://mialab.mrn.org/software/gift/publications/2010_OHBM_Elena_ICAPrenormalization_submitted.pdf), variance normalization is detrimental for the stability of ICA components.

I don't buy this result. AFAIK packages other than GIFT do variance normalization.

I think that the optimality of this choice depends on what you are doing.
