### ISSUE TITLE
wrong scaling  by regions.img_to_signals_maps if probabilistic atlas is given in percent ?

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1416]
Looks like `regions.img_to_signals_maps` divides signals by `100 * 100` if probabilistic atlas is given by percent, like the case of Harvard Oxford ?
```Python
from nilearn import image, regions, datasets

atlas = datasets.fetch_atlas_harvard_oxford('cort-prob-2mm')
img = image.math_img('img > 0.01', img=image.index_img(atlas.maps, 2))
signals, _ = regions.img_to_signals_maps([img], atlas.maps)
print(signals.max())
```
gives 0.0273107163216

Same code with `MSDL` atlas, which gives probability from `0.` to `1.` seems to have correct scale

**Comment by bthirion** [comment]
Sorry, I don't undertsand it. Closing for now.
