### ISSUE TITLE
Drop Scikit Learn < 0.15

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#1436]
Whats new doc says: "Dropped support for scikit-learn 0.14 Minimum supported version is now 0.15".

What I see from version.py is minimum required is 0.14.1.
https://github.com/nilearn/nilearn/blob/master/nilearn/version.py

and from travis
https://github.com/nilearn/nilearn/blob/master/.travis.yml

Question: According to doc string, minimum version should be changed to 0.15 or doc string needs to be changed ?

**Comment by GaelVaroquaux** [comment]
Good point, this should be changed.

I suggest to release 0.3 first (we're in the beta window, and we've been
in the beta window too long) and fix this after.
