### ISSUE TITLE
Problem in example masker objects

### ISSUE THREAD

**Issue by acamargofb** [nilearn/nilearn#1439]
Hi there:

I was following the example of this link:
http://nilearn.github.io/manipulating_images/masker_objects.html

and the script is now working on this part:

plot_roi(masker.mask_img_, mean_img, title='EPI automatic mask')

because the mean_img was not defined.

Do you know how to defined?

Thanks a lot,

Aldo Camargo

**Comment by KamalakerDadi** [comment]
>Do you know how to defined?

Please follow this example:
http://nilearn.github.io/auto_examples/04_manipulating_images/plot_mask_computation.html

You should be able to find relevant examples linked to each section. Small code snippets will give only overall idea of how to use. It might be either a Masker or some other class/object.

**Comment by KamalakerDadi** [comment]
Closing this one for now.

I am willing to suggest to look at full functioning of examples after you understood the big picture idea in all sections of userguide. All userguide sections will have relevant examples linked to them.

If there are any bugs then I suggest to open an issue with error traceback and minimal reproducible script.
Thanks for your interest.
