### ISSUE TITLE
Add WFU Pick atlas to nilearn.datasets

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#1440]
It might be a worthy consideration to add the WFU Pick atlas to the datasets module:

http://fmri.wfubmc.edu/software/pickatlas

**Comment by GaelVaroquaux** [comment]
Sure. Agreed. Are you planning to do the PR (or find someone to do it).

**Comment by banilo** [comment]
I am swamped right now :-(

Disclaimer: The person in charge might have to install WFU Pick atlas as a toolbox in SPM/Matlab :c:

**Comment by banilo** [comment]
I am swamped right now :-(

Disclaimer: The person in charge might have to install WFU Pick atlas as a toolbox in SPM/Matlab 🌵
