### ISSUE TITLE
NITRC is down

### ISSUE THREAD

**Issue by eitanlees** [nilearn/nilearn#1442]
I am trying to run some of the examples from your website but when I run the

`haxby_dataset = datasets.fetch_haxby()`

It says it's grabbing data from https://www.nitrc.org/frs/download.php/7868/mask.nii.gz but the website appears to be down. 

The full error I get is:
`URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)| Error while fetching file mask.nii.gz; dataset fetching aborted.>`

Any thoughts on what is going on, or when the website will be back up?

**Comment by KamalakerDadi** [comment]
NITRC is up now. Do you want to try again and close this issue if it is working ?
Thanks

**Comment by eitanlees** [comment]
In the time since posting my issue I managed to get the haxby data set from another source but when I run the other examples that use NITRC I am still running into an error, but it seems to be a different problem. Now when I run:

`from nilearn import datasets
adhd_dataset = datasets.fetch_adhd(n_subjects=1)`

I get the error:

`IOError: Fetching aborted: [Uncompress] unknown archive file format: /Users/eitanlees/nilearn_data/adhd/cda7351a79e3def091c719f4a5257206/adhd40_metadata.tgz`

**Comment by KamalakerDadi** [comment]
>I get the error:

>IOError: Fetching aborted: [Uncompress] unknown archive file format: /Users/eitanlees/nilearn_data/adhd/cda7351a79e3def091c719f4a5257206/adhd40_metadata.tgz

Ok. Let me see it.

**Comment by KamalakerDadi** [comment]
Seems like there is still a problem with NITRC database. I might also be wrong. May be we wait and see if it working or it's a bug in Nilearn.

**Comment by ainafp** [comment]
Same error fetching Harvard-Oxford
OSError: Fetching aborted: [Uncompress] unknown archive file format: nilearn_data/fsl/c0712ea7d16cd8f58aad506c26db0cf0/HarvardOxford.tgz

And I get other errors for some other atlases: craddock_2012, surf_destrieux

**Comment by KamalakerDadi** [comment]
I contacted NITRC team. The reply is below:

"NITRC suffered hardware failure last week and we are working to restore the site.
  Until then NITRC has limited functionality, including missing files for download.  We hope to have this fixed by the end of the week.

Sorry for the inconvenience.

"

Currently their database is down.

**Comment by KamalakerDadi** [comment]
Now, NITRC seems to be fine now. I am able to download data from all the fetchers you have mentioned here. Can you please try to see them if problem still exists ? @ainafp @eitanlees

**Comment by eitanlees** [comment]
Everything seems to be working now. Thanks for your help.
