### ISSUE TITLE
Retreiving the Dictionary and the cost function when using DictLearning

### ISSUE THREAD

**Issue by Apoorva3108** [nilearn/nilearn#1443]
I’m trying to use Dictionary Learning to estimate the group components of fMRI data and I’m pretty much in my initial stages. I have 2 concerns with the DictLearning command in nilearn.
As mentioned Dictionary Learning in nilearn is a map learning algorithm. In order to understand the efficiency of this technique I tried to estimate the Frobenius norm of ||X-DS||. I’m currently trying to retrieve the dictionary D. From the code, it is not clear as to how we can directly retrieve the final estimated dictionary used to find the group components.
Also, I want to get the value of the cost function mentioned in the paper.
Mensch, A., Varoquaux, G., Thirion, B., 2016. Compressed online dictionary learning for fast resting-state fMRI decomposition, in: 2016 IEEE 13th International Symposium on Biomedical Imaging (ISBI). Presented at the 2016 IEEE 13th International Symposium on Biomedical Imaging (ISBI), pp. 1282–1285. doi:10.1109/ ISBI.2016.7493501
I know that this value keeps changing one each iteration. But I want to see as to how it changes on each iteration and what iteration does this change stop.

Can you please help me with the above mentioned problems?

**Comment by GaelVaroquaux** [comment]
For such technical details, you want to open up the black box of the
algorithm and modify things. Indeed, the questions that you are asking
are about internals, not about the usage per se of the method.

The way to go about it is to read the corresponding code, and probably
subclass the object.

I'll help you with your specific: you'll need to pass a callback to
scikit-learn's dict_learning_online that's used in nilearn. This callback
will enable you to compute what you want.
