### ISSUE TITLE
region_extractor.connected_regions gets zero volume from affine

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1446]
in 
https://github.com/nilearn/nilearn/blob/master/nilearn/regions/region_extractor.py#L188

volume is computed from affine diagonal. This is making my extraction fails because my affine is
```Python
np.array([[0.3, 0   , 0  , -14.55],
          [0  , 0   , 0.3, -14.55],
          [0  , -0.3, 0  ,  14.55],
          [0  , 0   , 0  ,  1]])
```

What do you think about getting the volume information from `header.get_zooms()`

**Comment by KamalakerDadi** [comment]
What is your ```min_region_size``` specified ? What is the size you get in return ?

I would be in favour of changing min_region_size line to 
```min_region_size = min_region_size / np.abs(np.linalg.det(affine[:3, :3]))``` if it solves your problem.

As what we have did for ```connected_label_regions```

**Comment by bthirion** [comment]
+1 for the change

**Comment by albayenes** [comment]
Hi,
I am curious about what is the purpose of an affine transformation with zero on the diagonal. Is an affine transformation with zero on the diagonal meaningful?

**Comment by bthirion** [comment]
Yes: think of a permutation matrix (e.g. x->y, y->z, z->x). what matters is that det(affine[:3, :3]) != 0

**Comment by salma1601** [comment]
Hi @KamalakerDadi 
Was this issue solved ? Do you want me to do a PR ?
