### ISSUE TITLE
Change variable name in plot_simulated_data

### ISSUE THREAD

**Issue by ahoyosid** [nilearn/nilearn#1451]
In  /02_decoding/plot_simulated_data, the regressors are refereed as classifiers. This can be confusing. 
Is this name intended?. If not, I'd suggest to change it to regressors or estimators.

**Comment by KamalakerDadi** [comment]
+1 for estimators. Can you do a PR please ?

**Comment by ahoyosid** [comment]
Ok, I'll do it

**Comment by KamalakerDadi** [comment]
Closing in favour of PR #1457
