### ISSUE TITLE
Plotting failure: ROIs visible in nifti viewer but not by plot_roi()

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#1452]
Plotting these 4 binary (0, 1 values) images using nilearn.plotting.plot_roi does not lead to success (see image). However, loading the niftis into a standard image viewer gives the expected result.

![image](https://cloud.githubusercontent.com/assets/3907396/25943424/13c07e3a-3640-11e7-8e8e-cf984dc36408.png)

Images attached.
[ROIs.zip](https://github.com/nilearn/nilearn/files/992578/ROIs.zip)

**Comment by banilo** [comment]
New piece of evidence: Looks like little endian is back in new cloths.
Left image works, right one doesn't.

![image](https://cloud.githubusercontent.com/assets/3907396/25943771/549598e0-3641-11e7-8152-9fa0cd915e45.png)

**Comment by KamalakerDadi** [comment]
Seems OK to me. (development version)
![rois](https://cloud.githubusercontent.com/assets/11410385/25946338/eabf431c-364a-11e7-9a05-c6c4fbed9f0a.png)

```python
from nilearn import plotting

display = plotting.plot_roi('ROIs/dmpfc-1_r.nii', cmap='black_green_r')
display.add_overlay('ROIs/dmpfc-2_r.nii', cmap='RdBu')
display.add_overlay('ROIs/dmpfc-3_r.nii', cmap='RdBu_r')
display.add_overlay('ROIs/dmpfc-4_r.nii', cmap='Paired_r')
```
What is it missing here ?

**Comment by KamalakerDadi** [comment]
>What is it missing here ?

Can you reveal what is it missing here. Otherwise we can close this one ?
