### ISSUE TITLE
Harvard cortical atlas coords

### ISSUE THREAD

**Issue by nilearn-user** [nilearn/nilearn#1455]
I need the Harvard cortical atlas coords to plot my connectome but nothing woorks. is there a way to compute those coords?

**Comment by mrahim** [comment]
Use `nilearn.plotting.find_xyz_cut_coords`

**Comment by AlexandreAbraham** [comment]
But be careful to take the symmetrized version of HO in that case because this function can misbehave for maps with two symmetrical blobs.

**Comment by nilearn-user** [comment]
I tried using _nilearn.plotting.find_xyz_cut_coords_ but it returns 3 coords only, and to plot a connectome the coords should be a map of (n, 3) where n is the number of ROIs.

AlexandreAbraham I don't know what is the symmetrized version of HO and where to find it

**Comment by bthirion** [comment]
On 17/05/2017 09:26, nilearn-user wrote:
>
> I tried using /nilearn.plotting.find_xyz_cut_coords/ but it returns 3 
> coords only, and to plot a connectome the coords should be a map of 
> (n, 3) where n is the number of ROIs.
>
You probably wish to loop over ROIs.
>
> AlexandreAbraham I don't know what is the symmetrized version of HO 
> and where to find it
>
symmetric_split=True in
datasets.fetch_atlas_harvard_oxford()

**Comment by mrahim** [comment]
You can try this :

```python
import numpy as np
import nibabel
from nilearn.datasets import fetch_atlas_harvard_oxford
from nilearn.plotting import find_xyz_cut_coords, plot_connectome

atlas = fetch_atlas_harvard_oxford(atlas_name='cort-maxprob-thr25-2mm',
                                   symmetric_split=True)
atlas_img = atlas['maps']

# all ROIs except the background
values = np.unique(atlas_img.get_data())[1:]

# iterate over Harvard-Oxford ROIs
coords = []
for v in values:
    data = np.zeros_like(atlas_img.get_data())
    data[atlas_img.get_data() == v] = 1
    xyz = find_xyz_cut_coords(nibabel.Nifti1Image(data, atlas_img.affine))
    coords.append(xyz)

# no connections, just visualize coords
plot_connectome(np.eye(len(coords)), coords)

```

**Comment by nilearn-user** [comment]
Thank you all for your help.

I tried the code of @mrahim and it worked perfectely.

but when I tried plotting the connectome of my correlation matrix I got this error:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by AlexandreAbraham** [comment]
Can you please post the full stacktrace or your code so that we can see where the error comes from?

Thanks.

**Comment by nilearn-user** [comment]
Here:

# afficher le connectome
plotting.plot_connectome(correlation_matrix, coords,
                         edge_threshold="80%", colorbar=True)
plotting.show()


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5.py in resizeEvent(self, event)
    336         self.figure.set_size_inches(winch, hinch)
    337         FigureCanvasBase.resize_event(self)
--> 338         self.draw()
    339         self.update()
    340         QtWidgets.QWidget.resizeEvent(self, event)

C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5agg.py in draw(self)
    146         # causes problems with code that uses the result of the
    147         # draw() to update plot elements.
--> 148         FigureCanvasAgg.draw(self)
    149         self._priv_update()
    150 

C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py in draw(self)
    467 
    468         try:
--> 469             self.figure.draw(self.renderer)
    470         finally:
    471             RendererAgg.lock.release()

C:\Anaconda3\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     57     def draw_wrapper(artist, renderer, *args, **kwargs):
     58         before(artist, renderer)
---> 59         draw(artist, renderer, *args, **kwargs)
     60         after(artist, renderer)
     61 

C:\Anaconda3\lib\site-packages\matplotlib\figure.py in draw(self, renderer)
   1083         dsu.sort(key=itemgetter(0))
   1084         for zorder, a, func, args in dsu:
-> 1085             func(*args)
   1086 
   1087         renderer.close_group('figure')

C:\Anaconda3\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     57     def draw_wrapper(artist, renderer, *args, **kwargs):
     58         before(artist, renderer)
---> 59         draw(artist, renderer, *args, **kwargs)
     60         after(artist, renderer)
     61 

C:\Anaconda3\lib\site-packages\matplotlib\axes\_base.py in draw(self, renderer, inframe)
   2051             _do_composite = True
   2052 
-> 2053         dsu.sort(key=itemgetter(0))
   2054 
   2055         # rasterize artists with negative zorder

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()





---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5.py in resizeEvent(self, event)
    336         self.figure.set_size_inches(winch, hinch)
    337         FigureCanvasBase.resize_event(self)
--> 338         self.draw()
    339         self.update()
    340         QtWidgets.QWidget.resizeEvent(self, event)

C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5agg.py in draw(self)
    146         # causes problems with code that uses the result of the
    147         # draw() to update plot elements.
--> 148         FigureCanvasAgg.draw(self)
    149         self._priv_update()
    150 

C:\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py in draw(self)
    467 
    468         try:
--> 469             self.figure.draw(self.renderer)
    470         finally:
    471             RendererAgg.lock.release()

C:\Anaconda3\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     57     def draw_wrapper(artist, renderer, *args, **kwargs):
     58         before(artist, renderer)
---> 59         draw(artist, renderer, *args, **kwargs)
     60         after(artist, renderer)
     61 

C:\Anaconda3\lib\site-packages\matplotlib\figure.py in draw(self, renderer)
   1083         dsu.sort(key=itemgetter(0))
   1084         for zorder, a, func, args in dsu:
-> 1085             func(*args)
   1086 
   1087         renderer.close_group('figure')

C:\Anaconda3\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     57     def draw_wrapper(artist, renderer, *args, **kwargs):
     58         before(artist, renderer)
---> 59         draw(artist, renderer, *args, **kwargs)
     60         after(artist, renderer)
     61 

C:\Anaconda3\lib\site-packages\matplotlib\axes\_base.py in draw(self, renderer, inframe)
   2051             _do_composite = True
   2052 
-> 2053         dsu.sort(key=itemgetter(0))
   2054 
   2055         # rasterize artists with negative zorder

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by nilearn-user** [comment]
I found my error.
In the code after computing the correlation matrix I called:
G=nx.from_numpy_matrix(correlation_matrix)
to create a graph from the matrix
and then I called:
correlation_matrix=nx.to_numpy_matrix(G)
to recreate the matrix from the graph
I suppose that something has gone wrong in between.
