### ISSUE TITLE
axes parameter for plot_surf?

### ISSUE THREAD

**Issue by jona-sassenhagen** [nilearn/nilearn#1461]
For plotting a few brains (or views of brains), it would be cool if `plot_surf_stat_map` exposed an axes parameter (so that you can do e.g. `for ax, data_ in zip(axes, data): plot_surf_stat_map(..., ax=ax)` and get multiple brains in one figure.

If this sounds like a good idea, and not yet implemented in a different function, I'd be willing to make a PR.

**Comment by GaelVaroquaux** [comment]
Yes, I think that this is a good suggestion. We should also probably add a "figure" argument (as discussed in the comments of #1420).

We should strive to make the plot_surf function as homogeneous as possible with the other plotting functions, and thus add both an "axes" and a "figure" argument, with the same semantics.

Thanks!

**Comment by jona-sassenhagen** [comment]
Ok, I'll try to get on it next week.

**Comment by KamalakerDadi** [comment]
Closing with PR #1462
