### ISSUE TITLE
Make statistic map plots share colorbar

### ISSUE THREAD

**Issue by TheChymera** [nilearn/nilearn#1464]
I am performing brain stimulation in a region which has ample inhibitory projections. As such, I commonly need to show statistical maps centered both on the site of stimulation and on the projection areas (commonly the larger cluster). An example can be seen in this seed-based connectivity plot:
![dr_fc](https://user-images.githubusercontent.com/950524/27064023-4c3ff10e-4ff5-11e7-8634-a59039f01ae3.png)

Since it is one and the same map, and it makes no sense to change the color mapping between the two views, I would like to make the plots share the colorbar. Is there any way of doing so?

I have tried to dig through [the code](https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/img_plotting.py) but it seems none of the kwargs make their way to matplotlib.

**Comment by bthirion** [comment]
This is typically advances usage and I don't see how to find a solution to cover all the possible cases. You probably want to use colorbar=None and create a separate figure for the colorbar, by re-using the code in Nilearn plotting (that's what I do in this kind of case).

**Comment by TheChymera** [comment]
@bthirion do you have any examples? I find the internal figure handling of nilearn prohibitively opaque :-/

**Comment by bthirion** [comment]
Here is an example that creates a colorbar in a given axis (inspired from nilearn, but purely matplotlib).
HTH

```
def _draw_colorbar(colorbar_ax, vmax=8, offset=4.):
    from matplotlib.colorbar import ColorbarBase
    from matplotlib import colors
    our_cmap = plotting.cm.cold_hot
    nb_ticks = 5
    ticks = np.linspace(-vmax, vmax, nb_ticks)
    bounds = np.linspace(-vmax, vmax, our_cmap.N)
    norm = colors.Normalize(vmin=-vmax, vmax=vmax)
    # some colormap hacking
    cmaplist = [our_cmap(i) for i in range(our_cmap.N)]
    istart = int(norm(-offset, clip=True) * (our_cmap.N - 1))
    istop = int(norm(offset, clip=True) * (our_cmap.N - 1))
    for i in range(istart, istop):
        cmaplist[i] = (0.5, 0.5, 0.5, 1.)  # just an average gray color
    our_cmap = our_cmap.from_list('Custom cmap', cmaplist, our_cmap.N)

    ColorbarBase(
        colorbar_ax, ticks=ticks, norm=norm,
        orientation='vertical', cmap=our_cmap, boundaries=bounds,
        spacing='proportional', format='%.2g')
    colorbar_ax.yaxis.tick_left()
    tick_color = 'w'
    for tick in colorbar_ax.yaxis.get_ticklabels():
        tick.set_color(tick_color)
    colorbar_ax.yaxis.set_tick_params(width=0)
```

**Comment by TheChymera** [comment]
@bthirion  thanks for the advice!

I have solved this by writing a [colorbar drawing function](https://github.com/IBT-FMI/SAMRI/blob/b693ef9206a75c54741f1e14866b593cc68e2ddc/samri/plotting/maps.py#L24), and drawing it only [after a sequence of plots of the same image ends](https://github.com/IBT-FMI/SAMRI/blob/b693ef9206a75c54741f1e14866b593cc68e2ddc/samri/plotting/maps.py#L291).

**Comment by lrq3000** [comment]
@TheChymera Thanks a lot for sharing your script!

In addition I have found another way to share and modify the colorbar position only for the last plot (or whatever plot you want): just disable colorbar for all subplots except the last one, and then to modify the position to your liking (and avoid overlap):

```python
        # Plot the colorbar at the last plot of the row
        fig._show_colorbar(plt.get_cmap('BlueRedAlpha'), MidpointNormalize(midpoint=0., vmin=cmin, vmax=cmax))
        box = fig._colorbar_ax.get_position()
        fig._colorbar_ax.set_position([box.x0+(box.x0*0.1/total_cols), box.y0, box.width, box.height])  # move a bit the bar to the right, need to divide by number of columns (to move relative to last figure only, not to overall row, else will get too far away)
        fig._colorbar_ax.tick_params(labelsize=colorbar_labelsize)
```
The only thing I did not find how to do was to modify the orientation from horizontal to vertical, but in this case I think it's just easier to plot a new colorbar from scratch:

```python
    a = np.array([[0,1]])
    fig_cbar = plt.figure(figsize=(4, 0.25))
    img = plt.imshow(a, cmap=plt.get_cmap('BlueRedAlpha'), norm=MidpointNormalize(midpoint=0., vmin=allmin, vmax=allmax))
    plt.gca().set_visible(False)
    cax = plt.axes([0.1, 0.2, 0.8, 0.6])
    plt.colorbar(orientation="horizontal", cax=cax)
    fig_cbar.savefig('figs/whole_figure_colorbar.png', bbox_inches='tight', pad_inches=0)
```
