### ISSUE TITLE
Bug in example plot_haxby_anova_svm.py

### ISSUE THREAD

**Issue by sfvnDTU** [nilearn/nilearn#1472]
In line 92 of examples/02_decoding/plot_haxby_anova_svm.py the variable "cv" is defined, however it is not used. 

I think it should be added to the function call in line 94 to be:

`cv_scores = cross_val_score(anova_svc, X, conditions, cv = cv)`

**Comment by bthirion** [comment]
Sure ! Thx for pointing it. Can you make  a PR ?

**Comment by sfvnDTU** [comment]
PR made now

**Comment by KamalakerDadi** [comment]
I am opening this issue because PR is not yet merged.

**Comment by banilo** [comment]
Great catch! Good we figured this out during the PRNI nilearn workshop :-D
