### ISSUE TITLE
NiftiMasker

### ISSUE THREAD

**Issue by paul-bd** [nilearn/nilearn#1478]
Good evening, 

I don't know if it is the right place but I haven't found any information regarding a problem I have with niftimasker. 
I basically just want to extract signal from two ROIs (the striatas and the occipital cortex) to generate Binding Potential parametric brain maps. 

I have therefore two mask in the MNI template and an image 3D DOPA PET (to quantify brain uptake of dopamine) also in the MNI template in which I want to extract the signal ( the masks and images have nevertheless different shapes and affines). 
 - Those ROI seems to be well co-registred to the image when using nilearn.plotting_roi
 - but when using niftimasker, and masker.fit_transform to extract data to compute basic stats it seems to not extract the good portion of the image (as striatal would have a higher uptake than occipital cortex).  

<img width="478" alt="capture d ecran 2017-06-29 a 22 02 35" src="https://user-images.githubusercontent.com/24830940/27707733-b231db34-5d16-11e7-8798-9e9df7566212.png">

I guess the problem come from the fact that they have different affine as it fails when I try to use the function apply mask, but I fail to resample them (using resample_to_img) to the same affine.

How can I do it? 

Thanks for your answer and your time.

Best, Paul

[data.zip](https://github.com/nilearn/nilearn/files/1113506/data.zip)

I also added the nii of the occipital template and striatal template and my patient.

**Comment by GaelVaroquaux** [comment]
The NiftiMasker should deal with resampling transparently. We recently fixed a couple of nasty bugs with resampling. Hence I suggest that you check that you are using the latest version of nilearn to see if the problem goes away.

**Comment by paul-bd** [comment]
Hello,
indeed seems to be perfectly working (at least when I perform a resampling). 
Thank you very much for your time,

Paul bd
