### ISSUE TITLE
resample_img() is acting weird

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#1479]
There may be some issue with resampling the nilearn-provided atlases. The following code yields an all-zero atlas map:

``` python
import numpy as np
import nibabel as nib
from nilearn import datasets as ds
from nilearn.image import resample_img

tmp_nii = ds.fetch_icbm152_brain_gm_mask()
cort_atlas = ds.fetch_atlas_harvard_oxford('cort-prob-1mm')
cort_atlas_maps = resample_img(
    nib.load(cort_atlas['maps']),
    target_affine=tmp_nii.get_affine(),
    target_shape=tmp_nii.shape,
    interpolation='nearest'
    )
print np.unique(cort_atlas_maps.get_data().ravel())
```

**Comment by GaelVaroquaux** [comment]
Is this on latest master ? We fixed problems recently. 

⁣Sent from my phone, please excuse typos and briefness​

**Comment by bthirion** [comment]
When I do that , I get range(100). Are you using the latest nilearn ? 

B 

----- Mail original -----

**Comment by banilo** [comment]
![image](https://user-images.githubusercontent.com/3907396/27773735-a3bc415e-5f80-11e7-9131-abe792930528.png)

...looks like my nilearn was in the stone age. I get the right response with version 0.3.1 as you predicted.
