### ISSUE TITLE
Add Diedrichsen Cerebellum atlas

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#1480]
I suggest to consider adding the Cerebellum atlas from Diedrichsen lab. This is because the UKBiobank uses it extensively, prompting more and more investigators to need the atlas.

http://www.diedrichsenlab.org/imaging/propatlas.htm

**Comment by GaelVaroquaux** [comment]
Sure. PR welcomed.

**Comment by GaelVaroquaux** [comment]
I don't have the impression that the atlas is openly downloadable. So I fear that we might have to close this issue.

**Comment by banilo** [comment]
It has been used in UKbiobank Imaging to generate the cerebellum IDPs... It
can't be that hidden from the world.

2017-11-06 22:18 GMT+01:00 Gael Varoquaux <notifications@github.com>:

**Comment by GaelVaroquaux** [comment]
> It has been used in UKbiobank Imaging to generate the cerebellum IDPs... It can't be that hidden from the world.

Well the license it not an open one.

Yes, scientists tend not to care, but it can backfire:

http://www.nature.com/news/legal-confusion-threatens-to-slow-data-science-1.20359

(there was another recent issues where researchers were told after doing
the research that they were bound by the licensing of the materials that
they used, but I can't find it).

Nilearn strives to be actually open source, and not to build in grey
legal zones. For now we will stay away from such ill licensed data.

**Comment by bthirion** [comment]
Not doing it for due to the licence.
