### ISSUE TITLE
Nuisance regression in nilearn

### ISSUE THREAD

**Issue by chrisfilo** [nilearn/nilearn#1482]
I could not find it in the docs, but maybe I am missing something. Is there an easy way to perform nuisance regression using nilearn (4D volume to 4D volume)?

If yes this person would like to know: https://neurostars.org/t/confounds-from-fmriprep-which-one-would-you-use-for-glm/326/9

**Comment by GaelVaroquaux** [comment]
I think that you are looking for:
http://nilearn.github.io/modules/generated/nilearn.image.clean_img.html#nilearn.image.clean_img

**Comment by KamalakerDadi** [comment]
@chrisfilo Shall we close this one ?
