### ISSUE TITLE
Documentation: Link to MSDL Atlas broken

### ISSUE THREAD

**Issue by megh1241** [nilearn/nilearn#1483]
The link to the MSDL Atlas in the following page is broken.

http://nilearn.github.io/auto_examples/03_connectivity/plot_probabilistic_atlas_extraction.html#sphx-glr-auto-examples-03-connectivity-plot-probabilistic-atlas-extraction-py

I think the correct link is in the following page:
https://team.inria.fr/parietal/18-2/spatial_patterns/spatial-patterns-in-resting-state/

**Comment by KamalakerDadi** [comment]
Thanks for spotting. Can you issue a PR ?

**Comment by GaelVaroquaux** [comment]
Fixed in #1484
