### ISSUE TITLE
glass brain: front versus back view

### ISSUE THREAD

**Issue by kingjr** [nilearn/nilearn#1485]
In https://github.com/mne-tools/mne-python/pull/4408, we noticed that the plotting of the glass brain can be counter intuitive:
![image](https://user-images.githubusercontent.com/4881164/28624736-1470c64e-71e8-11e7-9554-13d39d18588a.png)

Specifically, the above drawing shows the temporal lobes and the cortex hides the cerebellum. The drawing thus suggests a front view. However, the left right lateralization suggests a back view (the left hemisphere is on the left if we look at the brain from the back).

It would be great to change the drawing depending on the mirror. Specifically, I was thinking of something like this for the backview:

![image](https://user-images.githubusercontent.com/4881164/28624389-0253ba76-71e7-11e7-9cb9-08fe585965ad.png)

**Comment by GaelVaroquaux** [comment]
I like your second image. It's elegant and explicit.

PR welcomed.

**Comment by kingjr** [comment]
Thanks. Regarding the PR, I can make the drawing if you indicate me
1) where to look for the data used to draw the first 3 plots, and 
2) which sulci to draw.

**Comment by GaelVaroquaux** [comment]
>  1. where to look for the data used to draw the first 3 plots, and

Have a look at the content of the nilearn/plotting/glass_brain_files
folder.

>  2. which sulci to draw.

It seems to me that the drawing that you prefered was nice. But then, I
am not a neuroanatomist (I am not even sure that I am a neuroscientist).
