### ISSUE TITLE
Overlay connectome plots?

### ISSUE THREAD

**Issue by dpisner453** [nilearn/nilearn#1492]
Also, is there an easy way to overlay connectome plots on a glass brain in nilearn? If not, what would be the easiest way to achieve this without having to manually color scheme the nodes (e.g. by community as some have done using the seaborn color libraries)?

**Comment by KamalakerDadi** [comment]
>Also, is there an easy way to overlay connectome plots on a glass brain in nilearn?

For me, I didn't get your question. plot_connectome does plots connectivity matrices on a glass brain.

Do you have any example to show what you meant by using seaborn color libraries ?

**Comment by dpisner453** [comment]
Sure, what I want to avoid is having to do this:

```
##where membership_plotting here is a 2-column array of coordinates and categories of membership to different communities
n = len(membership_plotting.unique())
clust_pal = sns.color_palette("Set2", n)
clust_lut = dict(zip(map(str, np.unique(membership_plotting.astype('category'))), clust_pal))
clust_colors = colors.to_rgba_array(membership_plotting.map(clust_lut))
plotting.plot_connectome(conn_matrix, coords, node_color = clust_colors, edge_threshold=edge_threshold, node_size=20, colorbar=True)
```

In other words, I wish to be able to simply do something like the following instead:
```
connectome = plotting.plot_connectome(conn_matrixA, coordsA, edge_threshold=99%, node_color='red')
connectome.add_overlay_connectome(conn_matrixB, coordsB, edge_threshold=99%, node_color='blue')
##Where the latter function 'add_overlay_connectome' does not exist in nilearn
```

How can I easily go about overlaying to different connectome plot on the same glass brain? Maybe there is a straightforward way to do this already that I'm just not aware of in nilearn?

Hopefully my question makes a bit more sense now :-/

**Comment by KamalakerDadi** [comment]
>In other words, I wish to be able to simply do something like the following instead:

I am afraid there is no straightforward to do what you are asking.
One thing you could try.

```python
connectome = plotting.plot_connectome(conn_matrixA, coordsA,
                                      edge_threshold=99%, node_color='red')
connectome.add_graph()
```
To know how to use ```add_graph```, you can have a look at plot_connectome plotting function code.
Hope this helps.

**Comment by dpisner453** [comment]
Aha! add_graph was what I was looking for :-) Check out what that allowed me to do:

<img width="1280" alt="sn_dmn_slf" src="https://user-images.githubusercontent.com/16432683/29472536-dfc9cd66-8419-11e7-9a32-e22a42953d2b.png">

Thanks for the help!

**Comment by KamalakerDadi** [comment]
>Aha! add_graph was what I was looking for :-)

Good that it worked for you. Closing this one then.
