### ISSUE TITLE
Few plotting functions not removes background with threshold=None

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#1504]
Reproducible script:
```python
from nilearn import datasets, plotting

n_subjects = 1
localizer_path = datasets.fetch_localizer_contrasts(
    ['calculation (auditory cue)'], n_subjects=n_subjects, get_tmaps=True)
tmap_filename = localizer_path.tmaps[0]

plotting.plot_stat_map(tmap_filename, threshold=None)
```
According to doc threshold=None implies not thresholding an image which is good. But, we are not eliminating any numerical noise here.

Shall I go for a PR to fix this ?
I would add small threshold = 1e-6 in helper function ```_plot_img_with_bg``` in nilearn.plotting.img_plotting.py

**Comment by bthirion** [comment]
What kind of numerical noise are you thinking of ? On this data, the estimation noise is large (it has basically variance=1), so we know that thee maps do not give very precise information.
Sorry if I misunderstood your point.

**Comment by KamalakerDadi** [comment]
>What kind of numerical noise are you thinking of ?

Noise which represents background. See for instance the doc [at line 660](https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/img_plotting.py#L660)
plotting will look like this.
![figure_1](https://user-images.githubusercontent.com/11410385/30001088-8649dd64-9083-11e7-806f-0557716d0876.png)


This issue is concerned to any map. I have my own maps which looks like this.

**Comment by bthirion** [comment]
Yes, but adding a very small threshold will not improve the display.You significantly change the aspect of the map only when you take a threshold significantly above 0. 
So, I don't see the reason to change the behavior of the function.
