### ISSUE TITLE
estimator_precision_ larger than 1

### ISSUE THREAD

**Issue by grjd** [nilearn/nilearn#1508]
How can be possible that the precision matrix returns values larger than 1?
I found that with my own data but also running the nilearn example
http://nilearn.github.io/auto_examples/03_connectivity/plot_inverse_covariance_connectome.html#sphx-glr-auto-examples-03-connectivity-plot-inverse-covariance-connectome-py

I get 
In [111]: estimator.precision_.max()
Out[111]: 2.0537018448578808

In [112]: estimator.precision_.min()
Out[112]: -1.0522529001195888

I get this just using the above example with the estimator as in the example http://nilearn.github.io/_downloads/plot_inverse_covariance_connectome.py
estimator = GraphLassoCV()
estimator.fit(time_series)

**Comment by GaelVaroquaux** [comment]
> How can be possible that the precision matrix returns values larger than 1?

Precisions are not normalized, unlike partial correlations. So yes, it's
not surprising.

**Comment by grjd** [comment]
d'accord.
thanks Gäel

**Comment by grjd** [comment]
I should have put this in my previous post. Just to make sure how the precision matrix is built.
I do a GraphLassoCV estimator for just 4 nodes and plot the covariance and the precision matrix, also Ledoit (which is pretty much like the precision) 
The precision matrix  (also Ledoit) dont recover the main diagonal, i should have maximum values for the diagonal, normalized or not. 

    lw_cov_, _ = ledoit_wolf(time_series)
    lw_prec_ = linalg.inv(lw_cov_)
    lw_prec_.precision_  gives me
 array([[ 1.31104237, -0.32148359, -0.1051193 , -0.4004092 ],
       [-0.32148359,  2.01339135, -1.22316702, -0.09501513],
       [-0.1051193 , -1.22316702,  1.93573103, -0.21259643],
       [-0.4004092 , -0.09501513, -0.21259643,  1.2511603 ]])  

This is the ledoit estimator.prec_
![screen shot 2017-09-12 at 3 39 36 pm](https://user-images.githubusercontent.com/7142903/30328767-9ea0b578-97d0-11e7-9ca1-edb327128a5f.png)

**Comment by GaelVaroquaux** [comment]
> The precision matrix (also Ledoit) dont recover the main diagonal,

What do you meean?

> i should have maximum values for the diagonal, normalized or not.

And what do you mean here?

**Comment by bthirion** [comment]
I think that these matrices should be diagonal-dominant -- which ensures that they are SDP -- which they are.
@grjd Maybe you're bothered by sign flipping of coefficients ?

**Comment by grjd** [comment]
yes SDP they are . I find confusing that the diagonal elements have very different values, if the variables are gaussian the precision represents the partial correlations, then, the diagonal elements should have all maximum precision.

**Comment by bthirion** [comment]
* The off-diagonal coefficient of the precision *once normalized by the diagonal  of the precision* represent partial correlation (up to a sign flip).
* The diagonal of the precision represents partial variance. They have no reason to be equal. 
HTH

**Comment by grjd** [comment]
So you normalize each off diagonal element in row i by the the diagonal element i?
P_{i, j} -> P_{i, j} / P_{i, i}

**Comment by bthirion** [comment]
Please check the code  but I think it is P_{i, j} -> P_{i, j} / sqrt(P_{i, i} * P_{j,j})
