### ISSUE TITLE
precision matrix diagonal not max values

### ISSUE THREAD

**Issue by grjd** [nilearn/nilearn#1509]
Just to make sure how the precision matrix is built.
I do a GraphLassoCV estimator for just 4 nodes and plot the covariance and the precision matrix, also Ledoit (which is pretty much like the precision)
The precision matrix (also Ledoit) dont recover the main diagonal, i should have maximum values for the diagonal, normalized or not.

lw_cov_, _ = ledoit_wolf(time_series)
lw_prec_ = linalg.inv(lw_cov_)
lw_prec_.precision_  gives me
array([[ 1.31104237, -0.32148359, -0.1051193 , -0.4004092 ],
[-0.32148359, 2.01339135, -1.22316702, -0.09501513],
[-0.1051193 , -1.22316702, 1.93573103, -0.21259643],
[-0.4004092 , -0.09501513, -0.21259643, 1.2511603 ]])

This is the ledoit estimator.prec_
![screen shot 2017-09-12 at 3 39 36 pm](https://user-images.githubusercontent.com/7142903/30330525-9d08ffe0-97d5-11e7-8190-a0d1fb745a89.png)

**Comment by GaelVaroquaux** [comment]
> Just to make sure how the precision matrix is built.

It's the standard mathematical definition, with the corresponding
estimator.

> I do a GraphLassoCV estimator for just 4 nodes and plot the covariance and the
> precision matrix, also Ledoit (which is pretty much like the precision)
> The precision matrix (also Ledoit) dont recover the main diagonal, i should
> have maximum values for the diagonal, normalized or not.

I don't understand the question.

**Comment by grjd** [comment]
The partial correlation of one variable with itself should be one.

**Comment by GaelVaroquaux** [comment]
> The partial correlation of one variable with itself should be one.

Yes, but this is a precision matrix, and not a partial correlation
matrix.

**Comment by grjd** [comment]
Yes, but the precision matrix is proportional to the partial correlation matrix and the diagonal elements should  keep the same proportion, right?

**Comment by GaelVaroquaux** [comment]
> Yes, but the precision matrix is proportional to the partial
> correlation matrix and the diagonal elements should keep the same
> proportion, right?

No.

**Comment by grjd** [comment]
I guess is this , for the Conditional Covariance Formula
Cov(X, Y) = E[Cov(X, Y|Z)] + Cov(E[X|Z], E[Y|Z]), when X=Y 
...
Cov(X, X) = E(X|Z)
