### ISSUE TITLE
[feature request] ConfoundEstimator as an Estimator class

### ISSUE THREAD

**Issue by rphlypo** [nilearn/nilearn#151]
Will work on it if the idea is accepted.

**Proposition**: To get a plethora of confounds into an estimator 'class' that only takes 'data_file', 'confound_name', and 'confound_file' as inputs. Specific confounds could then inherit from this basis estimator class, which leaves room for the experimenter on how to manage the confounds (for now only the 'clean' and 'high_variance_confounds' methods seem available, next to the filtering operation). Probably, the 'clean' method will need a little redesign to take a 'dict' object as an argument for the 'confounds' (which should merely be a dispatching if retrocompatibility is needed on the string, or numpy arrays). The 'dict' object could be organized as {"confound_name": confound_file}.

**How**: The basic estimator will be a mere fileloader, whereas more advanced methods for confound extraction can be made available using extra arguments (also to be made available as an extra argument to the 'clean' method, or just through the **kwargs filter). For instance, an envelope, and instantaneous amplitude estimator for the respiration (available in the HCP) as in _Birn et al., NeuroImage 31, pp.1536--1548, 2006_ or the data and/or masks for CompCor ('high_variance_confounds' method).

**Advantages**: many more confounds could be managed, and the user could easily add his own confound types without interfering with the existing code.

**Comment by bthirion** [comment]
Stalled.
