### ISSUE TITLE
Ward clustering for n niis

### ISSUE THREAD

**Issue by grjd** [nilearn/nilearn#1510]
I want to use scikit.cluster.Ward for group analysis. For one nii object it is straightforward to use the code bellow to fit one 4D object ("fmri_masked") .
ward = FeatureAgglomeration(n_clusters, linkage='ward')
ward.fit(fmri_masked)
Is it possible to do Ward clustering for a list of objects, that is, rather than 1 fmri scan a list of them ?
thanks

**Comment by KamalakerDadi** [comment]
For the moment you can use this PR #1370 
Thanks

**Comment by KamalakerDadi** [comment]
A working example which shows how to use Clustering object is in this [example](https://2619-1235740-gh.circle-artifacts.com/0/home/ubuntu/nilearn/doc/_build/html/auto_examples/03_connectivity/plot_rest_clustering.html#sphx-glr-auto-examples-03-connectivity-plot-rest-clustering-py)

**Comment by KamalakerDadi** [comment]
Closing this one as we can discuss about this issue in #1521
