### ISSUE TITLE
Add affiliation to author list

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1511]
And update it.

**Comment by tsalo** [comment]
What about linking to folks' `meta` repositories (or other self-maintained location for affiliation info) instead?

**Comment by bthirion** [comment]
Sorry, I'm not familiar with that. Can you describe more precisely what `meta` repository you are thiking of ?

**Comment by tsalo** [comment]
I'm referring to a dedicated personal repository for affiliation and ID information. Here's mine: https://github.com/tsalo/meta

That way, we wouldn't have to manually update affiliations.

**Comment by bthirion** [comment]
OK, I don't think it is easy to systematize this. 

My feeling is that maintaining this information is  a task for the core team :-)

**Comment by bthirion** [comment]
I'm not going to do it. Sorry. If any one wants to jump in, you're welcome.

**Comment by Remi-Gau** [comment]
Will open a draft PR so we can see judge whether we want to go down the CITATION.CFF route
