### ISSUE TITLE
plot_connectome for directed graphs

### ISSUE THREAD

**Issue by mike1729** [nilearn/nilearn#1513]
Hi all!

I have a directed connectome resulting from Granger causality in a form a matrix and I'd like to visualize it in the from of a graph. I used plot_connectome function, but instead of using lines I ploted arrows.
It looks like this:
![obraz](https://user-images.githubusercontent.com/4404982/30607125-401a9344-9d74-11e7-85cc-948530798c4d.png)
I can send a PR if you like it.
I think that tools which are able to produce directed connectomes are sparse, so it would be great if nilearn support such plotting. In this way or another:)

**Comment by GaelVaroquaux** [comment]
I think that it's a feature that would be good to have in nilearn: I suspect it requires actually few additional lines of code.

What's the interface that you have in mind? Maybe adding a "directed=False" argument to "plot_connectome" and the add_graph method of the glass brain object?

Thanks for stepping up!

**Comment by mike1729** [comment]
That is exactly what I thought. So, I'll create PR, and then we can discuss details.

**Comment by sofievdbos** [comment]
Is there any update wrt to this issue? Thank you in advance!

**Comment by bthirion** [comment]
Still accepting such a PR ;-)

**Comment by NicolasGensollen** [comment]
Addressed in #2703
