### ISSUE TITLE
Add bagging and boosting meta-estimators

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#1514]
Among the many possible committee estimators, two of the most prominent strategies may be a) bagging and b) boosting. While both have straightforward implementations, there is variation in the literature. It may therefore be both high-yield to implement both meta-estimators in nilearn and thus also increase comparability and standardization in using advanced learning algorithm in neuroimaging.

**Comment by bthirion** [comment]
We are finalizing a paper showcasing the advantage of bagging -- that has particularly welcome variance reduction properties.
Anyhow, PRs are welcome indeed !

**Comment by bthirion** [comment]
Done in Decoder. thx for the suggestion.
