### ISSUE TITLE
Test scipy 1.0 release candidate

### ISSUE THREAD

**Issue by lesteve** [nilearn/nilearn#1515]
If someone has not done it already it would be a good idea to do it.
```
pip install --pre scipy==1.0.0rc1
```

**Comment by lesteve** [comment]
OK I quickly ran the tests and they pass with scipy==1.0.0rc1.

**Comment by lesteve** [comment]
I am going to generate the doc to be safe.

**Comment by GaelVaroquaux** [comment]
Thank you Loïc ! 

⁣Sent from my phone, please excuse typos and briefness​

**Comment by lesteve** [comment]
Everything seems fine on the documentation AFAICS, closing.
