### ISSUE TITLE
resamling strategy in nifti masker

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1519]
Hi

I got many times trapped in signals extracted from unregistered atlas and functional volumes. Is there a reason why the default resampling strategy in the `NiftiLabelsMasker` is not `None` ?

Thanks

**Comment by KamalakerDadi** [comment]
Your issue is not clear for me. Can you show by any small script you have ?
Infact, the resampling strategy in ```NiftiLabelsMasker``` is not None.

**Comment by salma1601** [comment]
It's for basic use. For mice data there is not yet a standard space (analog to MNI) to which people put their data. Many times I didn't pay attention to the space to which functional volumes were registered
and use an atlas/functional data from different spaces. But the masker resamples by default so I discovered very late in the analysis my registration problem.
``` Python
from nilearn.input_data import NiftiLabelsMasker
gm_masker = NiftiLabelsMasker(labels_img=atlas_filename,
                              mask_img=non_noise_mask_img,
                              detrend=True,
                              smoothing_fwhm=.6,
                              memory='nilearn_cache')
```
Having the masker's default behavior to not resample seems less dangerous to me, no ?

**Comment by KamalakerDadi** [comment]
>Having the masker's default behavior to not resample seems less dangerous to me, no ?

Why not put ```resampling_strategy=None``` manually by yourself ?

I am asking because it we change to not resample by default. Then, we may also see same situation as yours i.e. trapped in signals extracted from unregistered atlas and functional volumes. Am I wrong ?

**Comment by salma1601** [comment]
>Why not put resampling_strategy=None manually by yourself

Yes but I wanted to understand the reason why the default strategy is to resample

>we may also see same situation as yours i.e. trapped in signals extracted from unregistered atlas and functional volumes

Yes you are right, this is possible but unlikely, usually unregistered images have different affines/shapes

**Comment by salma1601** [comment]
>This is what the nifti standard was designed to avoid.

You mean the fact that the functional volumes and the atlas are not in the same space ?

**Comment by GaelVaroquaux** [comment]
>     This is what the nifti standard was designed to avoid.

> You mean the fact that the functional volumes and the atlas are not in the same space ?

The sform (aka 'affine') is there to code the relationship between the
voxels.

**Comment by salma1601** [comment]
Yes so the logic is that if the affines are different, resampling solves the problem ? It does not solve it if the functional volumes and the atlas are not in the same space, I mean for instance functional volumes are not normalized to MNI while atlas is in MNI, no?

**Comment by GaelVaroquaux** [comment]
> Yes so the logic is that if the affines are different, resampling solves the problem ?

Yes.

> It does not solve it if the functional volumes and the atlas are not
> in the same space, I mean for instance functional volumes are not normalized to
> MNI while atlas is in MNI, no?

Correct. However that is not a problem that can be solved by a library,
as there missing information.

**Comment by salma1601** [comment]
Well I would think that if there is such a problem, I get an error. I understand that in plotting we resample images because the user may want to see the brains "however" they are. But I don't understand that the resampling is done almost "silently" in a preprocessing dedicated to extract time series. The most expected default behaviour for me would be not to resample, unless the user specifies he wants to do so, in which case I assume he knows what he is doing. What do you think ?

**Comment by KamalakerDadi** [comment]
>But I don't understand that the resampling is done almost "silently" in a preprocessing dedicated to extract time series. The most expected default behaviour for me would be not to resample, unless the user specifies he wants to do so, in which case I assume he knows what he is doing.

Resampling is done only when provided images have no same FOV. I think in a way it is right because most use cases your assumption will not happen.

**Comment by salma1601** [comment]
> most use cases your assumption will not happen

Yes in the very standard and basic use case, say atlas in MNI and all volumes normalized to MNI, my assumptions will not happen and it is convenient to have the resampling done if needed. But many other use cases exist. For mice there isn't a unique popular standard space. Also for human imagine you want to extract time series in the subjects-spaces with atlas that have been transformed in these spaces, then any little mix in the files etc will just not be noticed.

Also, many people do (or not) their resampling at the end of their spatial normalization pipeline and would not expect a timeseries extraction step to impact the resampling so they can miss such an error.

**Comment by bthirion** [comment]
Concretely, what is your suggestion ?

**Comment by salma1601** [comment]
just to put the default value of `resampling_target` to None in the Nifti Masker

**Comment by bthirion** [comment]
I don't know how to find a cgood compromise on that. In most cases, for human data, you have FOV and sampling differences but agree on the referential --MNI space-- hece resampling is the right default.
I am afraid of breaking this type of scenarii to accomodate the case that the two images may not have been properly registered. Should a warning be issued for the user ?

**Comment by salma1601** [comment]
> In most cases, for human data, you have FOV and sampling differences but agree on the referential --MNI space-- hece resampling is the right default

Well, even in this case setting the default to None doesn't look bad for me. The user will bump into this the very first time, and then set explicitly `resampling_target='data'`. Why want the code to run with a user unaware of this necessary step ?

**Comment by salma1601** [comment]
closing this one, since the default behavior seems the most practical one for human studies and that nilearn is more used for that

**Comment by SaqibMamoon** [comment]
My question is, as Glasser atlas’s default resolution is 1x1x1, how could I resample the atlas resolution to 3x3x3 before transformation on ABIDE-I data. Will setting the **resampling_target = 'data'** in **NiftiLabelsMasker** will do it or I have to it some other way?

**Comment by bthirion** [comment]
Yes, that should work. Let us know if you encounter any issue.
