### ISSUE TITLE
displays coordinates for mouse data

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1520]
Resolution for mouse MRI data is not the same magnitude as human data (~ .1 mm) and when plotting
them annotated coordinates are often 0. Is there a way to print more precision ?
Thanks !
![mouse_anat](https://user-images.githubusercontent.com/7080143/31034455-8392395e-a564-11e7-8f3c-c027d600d1a0.png)

**Comment by KamalakerDadi** [comment]
Have you tried ```from nilearn.plotting import find_cut_slices``` and tweaking parameter ```spacing``` in it ?

**Comment by salma1601** [comment]
>Have you tried from nilearn.plotting import find_cut_slices and tweaking parameter spacing in it ?

No because I want to see these slices y=.2, y=.5, y=.8 etc. The whole image ranges from -12 to 7 so it is natural to visualize many slices with smaller differences than with humans.
![mouse](https://user-images.githubusercontent.com/7080143/31966670-af9e7eb2-b90b-11e7-88b9-e023fe625606.png)

**Comment by bthirion** [comment]
This has been done recently. closing.
