### ISSUE TITLE
Offer clip option in resample_img

### ISSUE THREAD

**Issue by cancan101** [nilearn/nilearn#1528]
Currently using `resample_img` with `interpolation='continuous'` (default) can lead to values outside of the input range (e.g. getting negative values). `skimage` has a [`clip` option](http://scikit-image.org/docs/dev/api/skimage.transform.html?highlight=resize#skimage.transform.resize) which states:
>Whether to clip the output to the range of values of the input image. This is enabled by default, since higher order interpolation may produce values outside the given input range.

**Comment by GaelVaroquaux** [comment]
Sounds like a good idea. It is indeed a behavior that surprises people.
Do you mind doing a PR?

The question is: do we want it on or not by default?

**Comment by GaelVaroquaux** [comment]
So, the big question that remains on this PR is: do we want to change the behavior or not?

@bthirion, what do you think?

**Comment by bthirion** [comment]
I don't see disadvantage in adding clipping t the resampling. Yet another argument added to the function signature, but calling it 'clipping' should be transparent enough.

**Comment by GaelVaroquaux** [comment]
OK, then let's just change to True and not worry about it.

I'm merging and changing to True.
