### ISSUE TITLE
plotting.plot_connectome with voxels coordinates not in mm

### ISSUE THREAD

**Issue by grjd** [nilearn/nilearn#1529]
Hi ,
is it possible to use plotting.plot_connectome with the coordinates in voxels rather than in mm?
I got the coordinates of the Atlas from fsl/data/atlases/HarvardOxford-Cortical.xml which are not in mm but in voxels.
When I plot the Harvard-Oxford atlas, since plot_connectome expects the coordinates in mm and I get this
![hovoxels](https://user-images.githubusercontent.com/7142903/31728928-e9a6860a-b42d-11e7-91e7-d3b92b131b2a.png)

**Comment by GaelVaroquaux** [comment]
> iIs it possible to use plotting.plot_connectome with the coordinates in voxels
> rather than in mm?

You can use the affine to transform them in brain space.

Use nilearn.image.resampling.coord_transform for this.

**Comment by grjd** [comment]
thanks, the img is already resample in the MNI space but I have the Harvard-Oxford cortical Atlas coordinates in the MNI space but in voxels rather than in mm. So I dont need to change at all the image but transform an array containing the regions from voxel space to cartesian space (in mm).

**Comment by GaelVaroquaux** [comment]
> thanks, the img is already resample in the MNI space but I have the
> Harvard-Oxford cortical Atlas coordinates in the MNI space but in voxels rather
> than in mm. So I dont need to change at all the image but transform an array
> containing the regions from voxel space to cartesian space (in mm).

Yes. This is the definition of what the affine does. I had understood you
goal correctly and gave you the information that you need to solve it.

**Comment by GaelVaroquaux** [comment]
Closing this issue as it hasn't had activity.
