### ISSUE TITLE
[discussion] LedoitWolf vs EmpiricalCovariance in practice

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1539]
I am trying to illustrate the benefit of `LedoitWolf` vs `EmpiricalCovariance` in connectivity estimation, but when simulating multivariate Gaussian signals with a given true covariance I have the impression `LedoitWolf` underestimates the saliant patterns although the overall error is lower.

Example here with true covariance from fMRI data, left-right connections are on sub-diagonals
and deviate from true values more with LedoitWolf
<img src="https://user-images.githubusercontent.com/7080143/32416429-34ff435c-c249-11e7-80d5-09885e8dd675.png" width="200"><img src="https://user-images.githubusercontent.com/7080143/32416430-351bf880-c249-11e7-8793-62a98c7298c6.png" width="200"><img src="https://user-images.githubusercontent.com/7080143/32416431-353e4610-c249-11e7-88f8-0ee13a3c9ba4.png" width="200">

**Comment by bthirion** [comment]
Is the true matrix poorly conditioned ? If so, you expect the LW estimate to be quite poor. Interme of SSE LW is worse than empirical ? that would be suprising.

**Comment by salma1601** [comment]
the true matrix has condition number 134. In term of SSE LW is better, I just don't like the fact that the left-right connections are better estimated with empirical

**Comment by bthirion** [comment]
Sure, but the l2 penalty is mercyless for meaningful details.
What happens with less catastrophic conditioning of the true matrix (e.g. < 10) ?

**Comment by salma1601** [comment]
SSE is much better for LW, but patterns estimation is even worse ! Now also the little blacks are better estimated with empirical, and left-right is worse
<img src="https://user-images.githubusercontent.com/7080143/32419582-6b085708-c27c-11e7-89d1-50b6a11f66a3.png" width="200"><img src="https://user-images.githubusercontent.com/7080143/32419583-6b28fa3a-c27c-11e7-9ffc-cd934dfe56a8.png" width="200"><img src="https://user-images.githubusercontent.com/7080143/32419584-6b4343d6-c27c-11e7-9c3a-f521859946b2.png" width="200">

**Comment by bthirion** [comment]
No obvious solution to this issue.
