### ISSUE TITLE
Unexpected mask behaviour

### ISSUE THREAD

**Issue by vukovicnikola** [nilearn/nilearn#1548]
I am fitting a SpaceNet Classifier, passing in a white matter mask (voxels of interest = 1), attached: [mni_152_wm_mask.nii.zip](https://github.com/nilearn/nilearn/files/1463701/mni_152_wm_mask.nii.zip)
```
mnimask = './mni152_template/mni_152_wm_mask.nii'
decoder = SpaceNetClassifier(cv=cv, memory="nilearn_cache", penalty='tv-l1', memory_level=2, n_jobs=1, mask=mnimask)
```

Interestingly, when I later plot the coefficients against said mask, it seems like they lie precisely outside the mask (i.e. "0" voxels). 
![wm](https://user-images.githubusercontent.com/6719774/32688991-6cab26ea-c6db-11e7-8f83-ebb8988343a2.jpg)

Is this normal behaviour? Does nilearn use some non-standard masking convention? Unfortunately, I couldn't find information about this in the User Manual.

**Comment by KamalakerDadi** [comment]
If I understood your analysis properly, what you need to give is a gray matter mask.

If user has given a mask then it implies that analysis is done according to the provided mask. Please refer to this manual which describes about masking and related. http://nilearn.github.io/manipulating_images/masker_objects.html

**Comment by vukovicnikola** [comment]
Indeed. The problem is, rather, that how nilearn handles this mask does not seem to conform to standard neuroimaging practice. In most toolboxes, certainly in SPM or Afni, providing a binary mask means dot-multiplication will occur, and only non-zero matrix values will be kept for further analysis.
I don't mind inverting this logic when using nilearn and passing a grey matter mask to analyse white matter, however, I would like to make sure that this is what the developers intended. In which case, the manual needs to state this point prominently, as it subverts SPM-users' expectations.

**Comment by bthirion** [comment]
Nilearn actually considers the non-zero values as the ROI. So the behavior that you report is very surprising.  Is the masked sampled at the same resolution as the data that you are testing ?  I would suspect some issue occurring due to data resampling.
Note also that by default,  only 20% of the brain volume are considered by the spacenet estimator.

**Comment by vukovicnikola** [comment]
Thanks for your reply @bthirion! The data has been normalised to MNI space, and the mask is also MNI152. Though, the resolution is less in data (79 x 95 x 79 voxels, 2 mm isotropic) than in MNI template (193 x 229 x 193, 1mm isotropic) from which masks are created. Would this be a problem?
As for the screening_percentile parameter, would it still not choose 20% of voxels -within- the ROI, not outside? Any suggestions for troubleshooting this are welcome. Thank you!

**Comment by bthirion** [comment]
Of course, the vooxels should be chosen within the ROI.
You might want to set the screening_percentile to 100 to double check 
the behavior without the screening step.

Also, have you tried with a simpler (non-sparse) classifier, e.g. SVM ? 
If there is an issue in mask definition/corespondence, you should see it.

HTH

**Comment by GaelVaroquaux** [comment]
Maybe we have a simple terminology problem: what we call a "grey-matter
mask" is a mask in which the grey-matter voxels are at 1: a mask that
selects grey matter, and not one that masks out grey matter.

**Comment by vukovicnikola** [comment]
I have not tried SVMs, @bthirion... I can try running it again using screening_percentile=100. In principle, would downsampling the mask to match the data resolution help?

Hi @GaelVaroquaux! We both use the term in the way you describe. My GM mask has all GM voxels set as 1 (i.e. I want to keep this data).

**Comment by bthirion** [comment]
Normally, mask resampling is done whenever necessary by the estimator (the data are resampled at mask resolution). For debugging, pre-resampling the mask to the data resolution might help, but it not a pre-requisite for normal use of the methods.
