### ISSUE TITLE
MNI canonical mask in NiftiMasker

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1549]
We should add a mask_strategy="template" to NiftiMasker that computes the mask by resampling the MNI gray matter tissue to the images, and thresholds it.

The logic behind this (as opposed to the mask_strategy="epi") would be to remove the dependence of the mask on the data at hand (eg in a cross-validation loop) and thus make the computation more cache friendly.

We would have to create a function "compute_grey_matter_mask" in masking.py which take the "target_img" and an optional "threshold" argument as an input and returns the mask.

**Comment by SylvainLan** [comment]
I'm willing to look into this issue, just a question, what should be a typical value for the MNI to represent gray matter ? 

And to be sure I understood well, what's needed here is to resample the mni152 template onto an arbitrary image right ?

**Comment by GaelVaroquaux** [comment]
> I'm willing to look into this issue, just a question, what should be a typical
> value for the MNI to represent gray matter ?

1=True=gray matter, 0=False=not gray matter.

> And to be sure I understood well, what's needed here is to resample the mni152
> template onto an arbitrary image right ?

Yes, that's the key point.

**Comment by KamalakerDadi** [comment]
Closing with #1682

**Comment by meghalD** [comment]
> We should add a mask_strategy="template" to NiftiMasker that computes the mask by resampling the MNI gray matter tissue to the images, and thresholds it.
> 
> The logic behind this (as opposed to the mask_strategy="epi") would be to remove the dependence of the mask on the data at hand (eg in a cross-validation loop) and thus make the computation more cache friendly.
> 
> We would have to create a function "compute_grey_matter_mask" in masking.py which take the "target_img" and an optional "threshold" argument as an input and returns the mask.

I am getting an error when i passed mask_strategy='template' as a parameter to define DictLearning.
raise ValueError("Unknown value of mask_strategy '%s'. "
ValueError: Unknown value of mask_strategy '%s'. Acceptable values are 'background' and 'epi'. 

How do I resolve this. When I used 'background' it worked fine. But I want to use MNI template

**Comment by kchawla-pi** [comment]
Which Nilearn version are you using? v0.5.0 was just released. Are you getting the error with that?

**Comment by meghalD** [comment]
> Which Nilearn version are you using? v0.5.0 was just released. Are you getting the error with that?

I updated nilearn and now it is working fine. Thank you for the insight.

**Comment by meghalD** [comment]
I followed this link to find correlation matrix of the regions extracted by Dictionary Learning and ICA.
https://joaoloula.github.io/functional-atlas.html

But I see that it is not as per the number of regions selected. And also it does not state the regions.
I feel the matrix should come up as clean as here https://nilearn.github.io/connectivity/region_extraction.html

also with labelled regions in rows and columns. Can some guide me how to do that?

**Comment by meghalD** [comment]
> Which Nilearn version are you using? v0.5.0 was just released. Are you getting the error with that?

I want to fetch (timeseries, voxels) data for ABIDE. 
I ran the code as follows -
abide = datasets.fetch_abide_pcp(data_dir='/media/meghal/nilearn_data',derivatives=['func_preproc','rois_cc200'])
func_filename=abide.func_preproc
from nilearn.masking import compute_epi_mask
mask_img = compute_epi_mask(func_filename)

from nilearn.masking import apply_mask
masked_data = apply_mask(func_filename, mask_img)

But this gives a Memory error. Later I want to smooth out this signal and use further. Is there any other way to do the same ?

**Comment by kchawla-pi** [comment]
Post the traceback for the error here.
 (Surround it with a pair of triple backticks(\`) like this :
\`\`\`
 code/traceback
 \`\`\`
to ensure code is formatted properly.

**Comment by meghalD** [comment]
> Post the traceback for the error here.
> (Surround it with a pair of triple backticks(`) like this :
> ```
> code/traceback
> ```
> to ensure code is formatted properly.

``` 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/iab/.local/lib/python3.5/site-packages/nilearn/masking.py", line 706, in apply_mask
    ensure_finite=ensure_finite)
  File "/home/iab/.local/lib/python3.5/site-packages/nilearn/masking.py", line 726, in _apply_mask_fmri
    imgs_img = _utils.check_niimg(imgs)
  File "/home/iab/.local/lib/python3.5/site-packages/nilearn/_utils/niimg_conversions.py", line 268, in check_niimg
    return concat_niimgs(niimg, ensure_ndim=ensure_ndim, dtype=dtype)
  File "/home/iab/.local/lib/python3.5/site-packages/nilearn/_utils/niimg_conversions.py", line 460, in concat_niimgs
    order="F", dtype=dtype)
MemoryError
```

**Comment by meghalD** [comment]
> MemoryErrors usually happen when there is insufficient available memory. Are you using 32bit python or 64bit?

64bit. Earlier too I got the same error in ICA with number of components=40. As soon as I reduced it to 20 there was no error. 
Also, It is possible to feed the output of ICA in fMRI to supervised learning. If yes,  how do I include time series in it alongwith.

**Comment by kchawla-pi** [comment]
You are probably running out of usable memory, which is a combination of RAM+empty disk space which can be used as memory in a pinch. If you are using a virtual memory partition, how much is it and how full is it? If you are not, how much empty space is there on the root partition?
Which OS are you using?

**Comment by meghalD** [comment]
> You are probably running out of usable memory, which is a combination of RAM+empty disk space which can be used as memory in a pinch. If you are using a virtual memory partition, how much is it and how full is it? If you are not, how much empty space is there on the root partition?
> Which OS are you using?

I am using a server having a virtual partition. with 462GB space available and at root 14GB available. Is there a way to give some directory path to use instead of root to do all the computation?

**Comment by kchawla-pi** [comment]
I cannot answer that offhand. You should also talk to the server admin.
@KamalakerDadi Any ideas? Will joblib help here?

**Comment by meghalD** [comment]
> I cannot answer that offhand. You should also talk to the server admin.
> @KamalakerDadi Any ideas? Will joblib help here?

Ok actually I applied this code to fetch timeseries data for ABIDE. It would be great if you can help with the difference between rois_cc200 1D data and the timeseries we obtain by applying masking on functional files. I want to use it later for classification problem.

**Comment by KamalakerDadi** [comment]
>Ok actually I applied this code to fetch timeseries data for ABIDE. It would be great if you can help with the difference between rois_cc200 1D data and the timeseries we obtain by applying masking on functional files. I want to use it later for classification problem.

```rois_cc200``` key contains 2D timeseries data (number of timepoints, number of rois) extracted on Craddock parcellation atlas of dimension 200. Please read thoroughly this link http://preprocessed-connectomes-project.org/abide/Pipelines.html

You can use them directly for classification problem without have to apply masking. Like, ```rois_cc200``` you have plenty of timeseries data pre-extracted on various atlases, ```rois_aal```, ```rois_cc200```, ```rois_cc400```, ```rois_dosenbach160```, ```rois_ez```, ```rois_ho```, ```rois_tt```.

You can also use them as well for classification. Please read the link I have posted above to understand what they mean.

**Comment by meghalD** [comment]
> You are probably running out of usable memory, which is a combination of RAM+empty disk space which can be used as memory in a pinch. If you are using a virtual memory partition, how much is it and how full is it? If you are not, how much empty space is there on the root partition?
> Which OS are you using?

Is it technically correct to give entire data of healthy and diseased together for ICA if I want to study the difference between the two groups? 
Should I not pass diseased patient separately and perform ICA on them, repeat the same for healthy patients?

**Comment by bthirion** [comment]
I'm not sure what you want to do at the end, but if the idea is to compare connectomes across the two groups, I'd rather  use a fixed dictionary of regions, which is obtained e.g. by running ICA on the pooled data from the two groups of subjects.
See e.g. https://hal.inria.fr/hal-01824205v2
HTH

**Comment by meghalD** [comment]
> I'm not sure what you want to do at the end, but if the idea is to compare connectomes across the two groups, I'd rather use a fixed dictionary of regions, which is obtained e.g. by running ICA on the pooled data from the two groups of subjects.
> See e.g. https://hal.inria.fr/hal-01824205v2
> HTH

My end goal is to be able to compare the brain activations in healthy and ASD patients.
I wanted to replicate a study in order to learn this topic better.  Can you help me know how are the figures below made using nilearn. Did they use connectivity matrices and ICA or something else. If ICA how can we plot seperately for DMN.
![alex](https://user-images.githubusercontent.com/22214794/50540512-12932800-0bb9-11e9-9641-dc4750ad7945.JPG)

**Comment by bthirion** [comment]
In the image you show, region definition seems to be data-driven (from ICA or some kind of meta-analysis), but it may be shared across individuals.
Again; the crucial question is the statistical comparison of connectomes from signals extracted from these regions in the two groups. 
See e.g. https://nilearn.github.io/auto_examples/03_connectivity/plot_group_level_connectivity.html#sphx-glr-auto-examples-03-connectivity-plot-group-level-connectivity-py
