### ISSUE TITLE
Automatic resampling option for the neurovault fetcher

### ISSUE THREAD

**Issue by nicofarr** [nilearn/nilearn#1553]
It would be good to add an option to the neurovault fetcher so that images are resampled right after downloading, and stored only in resampled format. 

This would be useful to save space when downloading large collections. 

Ran into this issue when considering building an example (see #1506) using a large Neurovault collection (for example collection 503)

@jeromedockes

**Comment by GaelVaroquaux** [comment]
+1 on my side: if we store these via the caching mechanism of the downloaders, it will save a lot of space and compute time for the users.

**Comment by NicolasGensollen** [comment]
Addressed in #2696
