### ISSUE TITLE
Add VisibleDeprecationWarning from numpy in warn calls

### ISSUE THREAD

**Issue by cbedetti** [nilearn/nilearn#1560]
Several `warnings.warn` calls do not specify the category.

By default, python will not show `DeprecationWarning` so it would  be better to use : 

`warnings.warn(warn_str, np.VisibleDeprecationWarning, stacklevel=2)`

**Comment by jache-P7** [comment]
Hello,
It could be a good train for me (as it would be my first contribution).
Can you confirm that you would like to add `np.VisibleDeprecationWarning` in every `warnings.warn` ?
If it is okay for you I can work on it.
Thanks

**Comment by KamalakerDadi** [comment]
>Can you confirm that you would like to add np.VisibleDeprecationWarning in every warnings.warn ?

I think that np.VisibleDeprecationWarning should be added in warnings.warn wherever there are deprecated features.

**Comment by GaelVaroquaux** [comment]
Fixed in #1625
