### ISSUE TITLE
Formatting in example notebooks

### ISSUE THREAD

**Issue by emdupre** [nilearn/nilearn#1567]
Nilearn is exposing the rst formatting in notebook creation (e.g., in http://nilearn.github.io/_downloads/plot_decoding_tutorial.ipynb). This is less readable and would be nice to patch.

**Comment by GaelVaroquaux** [comment]
> (e.g., in http://
> nilearn.github.io/_downloads/plot_decoding_tutorial.ipynb). This is
> less readable and would be nice to patch.

Absolutely. This is due to imperfections of the sphinx-gallery converter.
The right thing to do would be to open issues on sphinx-gallery for each
of the rst syntax not captured.

**Comment by emdupre** [comment]
It looks like this issue is already open in Sphinx gallery: 

https://github.com/sphinx-gallery/sphinx-gallery/issues/219

Closing it here !
