### ISSUE TITLE
Too recent pandas required for decoding examples

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#1570]
decoding examples e.g. plot_haxby_space_net.py require very recent pandas (at least > 0.19.2) to work,   maybe because of the initial manipulation .isin

**Comment by emdupre** [comment]
.isin was added in 0.13.0, so it shouldn't be unavailable in more recent versions of pandas. Testing in a new (0.20.3) and an older (0.15.0) pandas environment, I get the correct shapes for both`y_train` and `y_test` in the `plot_haxby_space_net.py` example, suggesting .isin is working ok. 

In the 0.15.0 pandas environment, though, I don't get the correct shapes for `X_train` and `X_test` from .index_img unless I modify the code to explicitly pass values:

> X_train = index_img(func_filenames, condition_mask_train)
> X_train.shape
(40, 64, 64, 1452)
> X_train = index_img(func_filenames, condition_mask_train.values)
> X_train.shape
(40, 64, 64, 126)

My guess is it has to do with how newer vs older versions of pandas are returning data series. It's an easy patch in the examples, but do you think it's something that should instead be checked for in .index_img?

**Comment by GaelVaroquaux** [comment]
Ok, we should fix this in index_img. I'd like not to import pandas there,
though. How do we ducktype a pandas array? "hasattr(arr, 'values') and 
hasattr(arr, 'iloc')"?

**Comment by bthirion** [comment]
OK, I probably messed up with the versions of one of the libraries. Shame on me. I'll try to reproduce the issue to explain it better.
Thx for checking !

**Comment by emdupre** [comment]
It looks like this same issue is occurring in #1582, so I've opened PR #1583 to try and patch.

If you ended up finding any other bugs in trying to reproduce the issue @bthirion, please let me know and I can try to add those fixes in this PR!

**Comment by KamalakerDadi** [comment]
Can this be closed ?

**Comment by bthirion** [comment]
Sure, I close it.
