### ISSUE TITLE
plotting.plot_roi does not display colors correctly

### ISSUE THREAD

**Issue by TheChymera** [nilearn/nilearn#1574]
I am trying to plot a few voxels in a NIfTI with white on top of a template, I am calling `nilearn.plotting.plot_roi()` in the following fashion:

```
from nilearn.plotting import plot_roi
import matplotlib

skullcolor = matplotlib.colors.ListedColormap(['#FFFFFF','#FFFFFF'], name='skullcolor')
plot_roi(img,
        bg_img='/home/chymera/ni_data/templates/DSURQEc_40micron_average.nii',
        display_mode='yx',
        draw_cross=False,
        cmap=skullcolor,
        )
```

The result looks like this:

![figure_1](https://user-images.githubusercontent.com/950524/33184849-2ab92874-d07f-11e7-9fed-0dfee57439b6.png)

The voxels intended to be white are gray. This can't be prevented by adding more white entries to the listedcolormap or by tweaking the `dim` parameter (indeed, this seems to just affect the background image). The value of the voxels in `img` is 1.

Any idea how I can get nilearn to display the colormap colors correctly?

**Comment by KamalakerDadi** [comment]
Can you provide images ?

**Comment by GaelVaroquaux** [comment]
I think that it's because of the alpha: there is transparency. You can 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by TheChymera** [comment]
Thank you Gael. It was indeed the alpha!
