### ISSUE TITLE
DictLearning.fit does not work with globs

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1575]
DictLearning().fit('*.nii.gz') does not work.

We also need to check that this is not the case for CanICA

**Comment by KamalakerDadi** [comment]
I can see fixing this issue by adding a parameter wildcards=True or False (by default) and make use of helper function _resolve_globbing which is in nilearn/_utils/niimg_conversions.py.

_resolve_globbing should be called upon two usecases, one is when imgs are of list pattern ["*.nii.gz"] and str pattern "*.nii.gz". In former case, we should loop over the list and append all paths together and give to estimator. If agreed I can go for a FIX.

**Comment by GaelVaroquaux** [comment]
The plan seems good, but why do you want to add the parameter: we already
do this everywhere (or try to) and there is the global switch
nilearn.EXPAND_PATH_WILDCARDS to control that (though I just realized
that I can't find where it's documented, I would expect it to be on the
page:
http://nilearn.github.io/manipulating_images/input_output.html#file-name-matching-globbing-and-user-path-expansion

**Comment by KamalakerDadi** [comment]
nilearn.EXPAND_PATH_WILDCARDS is always True and also controlled by other parameter wildcards. We do this only in check_niimg but new_img_like has nibabel.load. Moreover, as I said there is difference between resolving globs when given as list. check_niimg will give you single nifti image loaded. Please tell me if I am missing something ?

https://github.com/nilearn/nilearn/blob/6269fdee4a048b5f6cbf8c5bb36f99e505c93e34/nilearn/__init__.py#L49

**Comment by GaelVaroquaux** [comment]
You're not missing anything. I think that we should just do a global
behavior. The way to change it is:

import nilearn
nilearn.EXPAND_PATH_WILDCARDS = False

**Comment by KamalakerDadi** [comment]
I think both are looking at this issue in a different views. We can discuss IRL.

**Comment by GaelVaroquaux** [comment]
I really don't want to add function-specific control of wildcards. It
should be a global.

**Comment by KamalakerDadi** [comment]
closing with #1606

**Comment by GaelVaroquaux** [comment]
Thanks!
