### ISSUE TITLE
GroupSparseCovarianceCV

### ISSUE THREAD

**Issue by grjd** [nilearn/nilearn#1577]
Calculating the precision matrix for a group  of subjects via these two methods I get different results. First I just call GroupSparseCovarianceCV for the group  and in the second approach I do an average of the correlation matrix I got for each subject.
I wonder if it is any better to use LedoitWolf rather than Empirical covariance?
#approach 1  
>     gsc = GroupSparseCovarianceCV(verbose=2)
>     gsc.fit(time_series)
>     precision_matrix = -gsc.precisions_[...,0]

#approach 2 
> > ConnectivityMeasure(EmpiricalCovariance(assume_centered=True), kind='precision') 
> for i in range(0, len(time_series)):
>      correlation_matrix = connectivity_measure.fit_transform([time_series[i]])[0]
>      correlation_matrix_subjects.append(correlation_matrix)
>

**Comment by GaelVaroquaux** [comment]
Unsurprising that you're getting two different results: different
estimators give different estimation. Choosing which one is the most
likely to be close to a population covariance is hard.

Here is my advice, based on many years of research on this:

- Prefer LedoitWolf to EmpiricalCovariance in general

- If you're interested in a graph with not too many edges, it is better
  to use GroupSparseCovarianceCV than to threshold the precision matrix
  obtained in LedoitWolf. You might have to use GroupSparseCovariance and
  set an alpha slightly higher than the one given by the cross-validated
  object.

**Comment by KamalakerDadi** [comment]
If I take your issue correctly there is already an issue #1460 on this. That may help to get more insights
