### ISSUE TITLE
Nilearn installation through conda-forge does not work

### ISSUE THREAD

**Issue by mick-d** [nilearn/nilearn#1581]
Installing `nilearn` through `conda-forge` causes the package not to be found when imported (although it is installed). In this case, maybe better to remove it from the `conda-forge` repository to avoid users debugging their installation?

**Comment by lesteve** [comment]
Thanks for opening an issue, this is what I tried:
```
conda create -n nilearn -c conda-forge nilearn python
 python -c 'import nilearn; print(nilearn.__version__)'
```

and this seems to work just fine. Can you post the commands you used to create your conda environment plus a fully standalone script reproducing your problem?

The nilearn version available through conda-forge is 0.3.1, you are more than welcome to open a PR at https://github.com/conda-forge/nilearn-feedstock if you want to have the latest version available (0.4.0 at the time of writing) through conda-forge.

**Comment by KamalakerDadi** [comment]
Thanks for the hint @lesteve . I can see if I can open a PR.

**Comment by lesteve** [comment]
This is generally quite easy to do. Look at https://github.com/conda-forge/nilearn-feedstock/pull/3/files for an example basically you update the version and the hash of the .tar.gz.

**Comment by KamalakerDadi** [comment]
Thanks @lesteve I opened a PR. https://github.com/conda-forge/nilearn-feedstock/pull/17

**Comment by lesteve** [comment]
Thanks @KamalakerDadi, nilearn 0.4.0 is now available from conda-forge. I am going to close this one.

@mick-d feel free to reopen if that does not fix your problem. In this case it would be really great if you can post a fully stand-alone snippet reproducing your problem. Have a look at 
https://stackoverflow.com/help/mcve which is a great ressource.
