### ISSUE TITLE
Online documentation search is broken

### ISSUE THREAD

**Issue by chrisfilo** [nilearn/nilearn#1586]
![image](https://user-images.githubusercontent.com/238759/34588285-04200842-f161-11e7-84d7-4542aa099bad.png)

**Comment by KamalakerDadi** [comment]
Thank you for reporting. I will FIX it soon.

If you are looking for Ward related user guide. Here it [is](http://nilearn.github.io/connectivity/parcellating.html). So far, there is no object in Nilearn which does parcellations directly on Nifti images.

But, there is a WIP PR https://github.com/nilearn/nilearn/pull/1370. It should be merged at some point (almost ready).
