### ISSUE TITLE
Off By One Bug in reorder_img

### ISSUE THREAD

**Issue by cancan101** [nilearn/nilearn#1589]
This seems like an off by one bug in `reorder_img`:
Given image and affine:
```python
affine = np.array(
    [[-1        , -0.        ,  0.        ,  0.        ],
    [-0.        , -1         ,  0.        ,  0.        ],
    [-0.        , -0.        ,  1         ,  0.        ],
    [ 0.        ,  0.        ,  0.        ,  1.        ]],
)
img = nib.Nifti1Image(np.zeros((90, 100, 123)), affine=affine)
```
Calling `reorder_img`:
```
print(reorder_img(img).affine)
[[  1.   0.   0. -89.]
 [  0.   1.   0. -98.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]]
```
Which for the second translate seems to be off by 1.
And of course getting the transform from one space to the other (should be a mirroring):
```
print(np.linalg.inv(reorder_img(img).affine) @ affine)
[[ -1.   0.   0.  89.]
 [  0.  -1.   0.  98.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]]
```
such that:
```
print([0,0,0,1] @ (np.linalg.inv(reorder_img(img).affine) @ affine).T)
[ 89.  98.   0.   1.]
```
rather than: `[ 89.  99.   0.   1.]`

**Comment by bthirion** [comment]
Indeed. Can you have a look at the code to try and localize the bug ?

**Comment by cancan101** [comment]
The issue is that this line: https://github.com/nilearn/nilearn/blob/dc6b15ea17c39327549233ba6e54fc684b041729/nilearn/image/resampling.py#L684 is not the same as this line (`+ 1` in one not other): https://github.com/nilearn/nilearn/blob/dc6b15ea17c39327549233ba6e54fc684b041729/nilearn/image/resampling.py#L690
