### ISSUE TITLE
Weird warning message when using threshold_img() with float

### ISSUE THREAD

**Issue by lrq3000** [nilearn/nilearn#1599]
Hi (again)!

I just noticed a weird warning message when using `threshold_img()` with a float:

```python
c:\anaconda2\lib\site-packages\nilearn\_utils\param_validation.py:69: UserWarning: The given float value must not exceed 0.0. But, you have given threshold=0.0001 
  threshold))
```

[According to the documentation](http://nilearn.github.io/modules/generated/nilearn.image.threshold_img.html), when using a float this specifies the absolute voxel intensity at which we want to threshold (which is exactly what I want), but the warning tells me I should only use negative values. Am I misunderstanding something here?

**Comment by bthirion** [comment]
Have you checked the value range in your image ?

**Comment by KamalakerDadi** [comment]
This warning comes from the images you have provided. So, not obvious that we understood the issue by looking at the warning message.

Could you give us minimal reproducible script to investigate this issue ?
Thanks
