### ISSUE TITLE
[MAINT] ImportError: No module named nose.tools

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#1600]
### Current behavior
With PR #1592 , we made temporary patch to fix issues related to doc test failures when NumPy is 1.14.0.
#### What is the patch for:
The patch added in ```nilearn/__init__.py``` has workaround which checks if tests are running. If tests are running then we switch back to printing doc tests to older NumPy version 1.13.

This workaround creates problem because it requires nose to be installed as mandatory dependency.
This tries to block not importing nilearn. Even, if nilearn is installed.

Traceback error:
```python
Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> print(numpy.__version__)
1.14.0
>>> import nose
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named nose
>>> import nilearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nilearn/__init__.py", line 47, in <module>
    from ._utils.testing import is_nose_running
  File "nilearn/_utils/testing.py", line 17, in <module>
    from sklearn.utils.testing import assert_warns
  File "/home/kamalakar/miniconda2/envs/myenv/lib/python2.7/site-packages/sklearn/utils/testing.py", line 49, in <module>
    from nose.tools import raises
ImportError: No module named nose.tools
```
### Expected behavior
Nose should not act like a dependency to install. Because it only requires when running tests but not to use package.

**Comment by GaelVaroquaux** [comment]
Good catch! We should us try/except to avoid the problem.

**Comment by KamalakerDadi** [comment]
>We should us try/except to avoid the problem.

Ok. I will do a PR to fix. Thanks

**Comment by KamalakerDadi** [comment]
While I don't see the **Current behavior** with Python 3.6 ?
