### ISSUE TITLE
Search on docs fails

### ISSUE THREAD

**Issue by surchs** [nilearn/nilearn#1601]
Hey,

search queries with the builtin google search on the [docs site](http://nilearn.github.io/index.html) fail with the following prompt:

![image](https://user-images.githubusercontent.com/1302022/35771712-3017d3fc-08ff-11e8-9eab-c7f4470f1cb6.png)

The [linked site mentions direct access to the API as a problem](https://support.google.com/customsearch/answer/4542055).

**Comment by emdupre** [comment]
This looks like a duplicate of #1586. I'm also seeing the same error in the current online version (but not in the build artifact @KamalakerDadi linked in their PR: https://2840-1235740-gh.circle-artifacts.com/0/home/ubuntu/nilearn/doc/_build/html/index.html).

Any ideas why this fix isn't showing up in the current build?

**Comment by surchs** [comment]
Indeed, it's a duplicate - closing.

**Comment by KamalakerDadi** [comment]
This is fixed in master. Should be fine for next release.
