### ISSUE TITLE
problems reading minc format data using NiftiLabelsMasker

### ISSUE THREAD

**Issue by zhangyu2ustc** [nilearn/nilearn#1613]
Hi,
  I was trying to use nilearn.input_data.NiftiLabelsMasker to exact time-series for each parcel in the atlas. But my fmri data and atlas are both in MINC format. I was able to read and plot them in nibabel. But when I try to use NiftiLabelsMasker it gives weird shapes of data:

import nibabel as nib
from nilearn import plotting
mist_atlas_file = "MIST_ROI_3mm_HCP.mnc"
mist_atlas = nib.load(mist_atlas_file)
plotting.plot_roi(mist_atlas)
  ##output: atlas figure is good
print(mist_atlas.get_data().shape)
  ##output: (284, 52, 64, 53)

mist_atlas = NiftiLabelsMasker(labels_img=mist_atlas_file, detrend=True, standardize=True, low_pass=0.1, high_pass=0.01, t_r=TR)
mist_roi_tc = mist_atlas.fit_transform(fmri_files[0])
print(mist_roi_tc.shape)
  ##output: (53, 446), but it suppose to be (284,210)

Do you have an idea what is wrong with my code and what is the best way to load minc format image data?
Thanks!

Best,
   Yu.

**Comment by bthirion** [comment]
Sorry I'm not familiar with MINC.
What does `print(mist_atlas.shape)` return ?
Can you make one of these images available to us, so that we can figure out what's going on ?

**Comment by KamalakerDadi** [comment]
Could you please provide the atlas in .mnc ?

Thanks

**Comment by bthirion** [comment]
Stalled.
