### ISSUE TITLE
Resampled image being padded with zeros

### ISSUE THREAD

**Issue by ellisdg** [nilearn/nilearn#1620]
When I resample images using ```resample_img```, I'm noticing a weird padding behaviour. For example, I can create a 4x4x4 image as follows:
```
import numpy as np
import nibabel as nib
from nilearn.image import resample_img

image = nib.Nifti1Image(np.arange(4**3).reshape((4, 4, 4)), affine=np.diag(np.ones(4)))
```
I then want to downsample that image to half it's original size:
```
new_image = resample_img(image, target_affine=np.diag(np.ones(3)*2))
```
I can then print out the data array from the new image as follows:
```
print(np.round(new_image.get_data()))
```
And this gives me a 3x3x3 array. This array includes the 2x2x2 array that I was expecting, plus some extra zeros:
```
[[[  0.   2.   0.]
  [  8.  10.   0.]
  [  0.   0.   0.]]

 [[ 32.  34.   0.]
  [ 40.  42.   0.]
  [  0.   0.   0.]]

 [[  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]]
```
Is it expected behaviour for the output image to be padded with zeros?

**Comment by bthirion** [comment]
Yes. What else would you expect ?
Best,
B

**Comment by ellisdg** [comment]
Since I'm not specifying a specific shape in the resampling, I would expect a 2x2x2 image. A 2x2x2 image with 2mm x 2mm x 2mm spacing would have the same extent as a 4x4x4 image with 1mm x 1mm x 1mm spacing, right? The extent of the resampled image is now 6mm x 6mm x 6mm, no? What is the utility of increasing the extent of the image by padding with zeros?

**Comment by KamalakerDadi** [comment]
Hi @ellisdg there exists some **Notes** and the example documented in particular how resampling does when target_affine is 3x3. May be cropping the image would help ?

**Comment by KamalakerDadi** [comment]
@eickenberg Do you have some inputs here ?
Thanks.

**Comment by bthirion** [comment]
Actually, this is a wanted  behavior (look at the docstrings). To avoid that, you need to provided a target_shape and a 4*4 affine.

**Comment by bthirion** [comment]
Stalled. Closing.
