### ISSUE TITLE
Resample timeseries

### ISSUE THREAD

**Issue by andrewheusser** [nilearn/nilearn#1621]
I am running an analysis that involves resampling a 4D nifti in the time dimension.  I don't think nilearn has a builtin way to do this.  If this is something the nilearn community would find useful I'll submit a PR, but otherwise i'll just implement it in my own pipeline.

**Comment by KamalakerDadi** [comment]
What would be the use case ?

**Comment by andrewheusser** [comment]
I'm using dynamic time warping to temporally align fmri time series and a
model of subsequent recall and I want to resample back to the original
length.

**Comment by bthirion** [comment]
you probably want to use interpolation function from scipy. The use case seems a bit too specific for inclusion in Nilearn.

**Comment by andrewheusser** [comment]
thanks! i agree it's a pretty specific use case and probably not worth including

**Comment by GaelVaroquaux** [comment]
> thanks! i agree it's a pretty specific use case and probably not worth including

Also, it can probably be done quite easily using a combination of nilearn
and scipy.signal.
