### ISSUE TITLE
Error on "from dipy.core.gradients import gradient_table"

### ISSUE THREAD

**Issue by paultimothymooney** [nilearn/nilearn#1624]
When I run the following code 

`from dipy.core.gradients import gradient_table`

I get the following error message

`ImportError: dlopen: cannot load any more object with static TLS`

**Comment by GaelVaroquaux** [comment]
I believe that this is the wrong repository : this issue tracker is about nilearn, not nipy.

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by KamalakerDadi** [comment]
Hi @paultimothymooney I think you should ask in https://github.com/nipy/dipy
