### ISSUE TITLE
crop_img takes axis to preserve

### ISSUE THREAD

**Issue by cancan101** [nilearn/nilearn#1626]
For example I have images that are `256x256xN` and I want to crop all black slices in the axial (third) dimension but I want to preserve the size of the first two dimensions.

I suggest adding some optional kwarg to `crop_img` specifying which axis to keep or perhaps which axis can be cropped.

**Comment by bthirion** [comment]
Makes sense to me.
I would use `axis=False` to specify axis to preserve.

**Comment by cancan101** [comment]
I'm not sure I  follow your api proposal.

**Comment by KamalakerDadi** [comment]
Can you point to some references where this methodology is routinely used ?

**Comment by cancan101** [comment]
Maybe the numpy squeeze method https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.squeeze.html which be default squeezes all but can take a subset of axis.

**Comment by bthirion** [comment]
My thought was simply to add a kw argument to `crop_img` -- and make sure that the default behaviour remains unchanged.
I agree that `axis` is ineed ambiguous because we need to read the doc to know whether the axis is preserved or changed.
Are you suggesting an alternative function ?

**Comment by bthirion** [comment]
Stalled.
