### ISSUE TITLE
get_voxel_spacing utility function

### ISSUE THREAD

**Issue by cancan101** [nilearn/nilearn#1627]
From here:
https://github.com/nilearn/nilearn/blob/f6c5d3e273d24964e7b84fc32b05cb9f324cf864/nilearn/image/resampling.py#L659-L663
factor out:
```python
def get_voxel_spacing(affine):
    Q, R = np.linalg.qr(affine[:3, :3])
    return np.abs(np.diag(R))[np.abs(Q).argmax(axis=1)]
```

This function is useful for example when resizing to isotropic you can use the smallest dimension in the new affine.

**Comment by KamalakerDadi** [comment]
Isnt't this simple to grab the diagonal of the affine ? Why do we need function ?

You mean we can use this function multiple places in the code base ?

**Comment by cancan101** [comment]
It isn't quite the (raw) diagonal of the affine. It is doing a QR decomposition.

**Comment by KamalakerDadi** [comment]
yeah but the result will be the same. isn't it ?

**Comment by cancan101** [comment]
Take this as an example:
```
array([[4, 1, 3],
       [1, 0, 0],
       [0, 0, 2]])
```
```
> get_voxel_spacing(arr)
array([4.12310563, 0.24253563, 2.        ])
```

**Comment by bthirion** [comment]
Well, can you issue a PR ?

**Comment by bthirion** [comment]
Stalled.
