### ISSUE TITLE
Off By One in Auto Shape for resample_img

### ISSUE THREAD

**Issue by cancan101** [nilearn/nilearn#1630]
```python
resample_img(
    nib.Nifti1Image(np.ones((8, 8, 6)), np.eye(4)),
    np.diag((0.5, 0.5, 0.5))
).get_data().shape
```
is producing an image that is `(15, 15, 11)`. I would expect `(16, 16, 12)`.

**Comment by KamalakerDadi** [comment]
Please give us a script to reproduce this behavior ?
Thanks

**Comment by cancan101** [comment]
The above code should be self contained minus the import.

**Comment by bthirion** [comment]
AFAIK the logic is the following: when you oversample a set of n aligned points by a factor of 2, you want to create the (n-1) intermediate points, yielding 2n  - 1 points on the oversampled grid. if you oversample by a f actor of k, you obtain (n-1)k + 1 points.
This may be a bit surprising, but I don't see how to improve the logic. Also remember that you can provide a `target_shape` argument.

**Comment by cancan101** [comment]
@bthirion How would you express a "standard" 2x upsample operation?

**Comment by NicolasGensollen** [comment]
Hi @cancan101 
As far as I can tell, there does not seem to be any bug here although the output shape might be surprising at first as @bthirion explained above.
Should we close this?

**Comment by bthirion** [comment]
Closing indeed.
