### ISSUE TITLE
How to get the ordering of plot_matrix(reorder=True)

### ISSUE THREAD

**Issue by dangom** [nilearn/nilearn#1633]
Is there a way to access the sorting of elements after calling `plotting.plot_matrix` with `reorder=True`?

I ask because I would like to compare two correlation matrices, but reordering them individually leads to different sorting orders.

Otherwise wouldn't it be better to expose the reordering functionality outside of `plot_matrix`?  This way `plot_matrix` wouldn't have to change, but users could also do the sorting on their own, if they wanted to.

Perhaps `order = nilearn.connectome.reorder(data)`?

**Comment by mjboos** [comment]
Here's a somewhat hacky way to do it for a matrix `mat`:
```
labels = [str(i) for i in range(mat.shape[0])
ax = plot_matrix(mat, labels=labels, reorder=True)
reordered_labels = [int(lbl.get_text()) for lbl in ax.axes.get_xticklabels()]
```
You could then use `reordered_labels` to sort the second matrix and set `reorder=False`.

Alternatively, if you want to do the ordering outside, just compute the ordering of your matrix yourself and reorder both matrices before you give them to plot_matrix.
The reordering is quite simple:
```
from scipy.cluster.hierarchy import (linkage, optimal_leaf_ordering, leaves_list)
linkage_matrix = linkage(mat, method='average')
ordered_linkage = optimal_leaf_ordering(linkage_matrix, mat)
index = leaves_list(ordered_linkage)
```

Then just use `index` to reorder your matrices.

**Comment by KamalakerDadi** [comment]
@dangom is there anything that you are missing. can this be closed ?
