### ISSUE TITLE
plot_connectome outside boundaries

### ISSUE THREAD

**Issue by grjd** [nilearn/nilearn#1634]
When plotting a covariance matrix with the Harvard-Oxford atlas the nodes are outside the boundaries. How can this be corrected? Does this happens with other atlases, for example the atlas_msdl ? 

plotting.plot_connectome(corr_matrix, coord_map,edge_threshold=0, title=' ', display_mode="ortho") 

#coord_map
[(-18, 76, 0), (28, 28, -6), (33, 73, 63), (26, 32, 40), (38, 42, 10), (38, 30, 24), (-10, 10, 66), (-44, 26, -6), (-68, 6, -6), (-72, -8, 0), (-70, 6, -18), (50, -10, -10), (-66, -42, 6), (34, 10, -38), (-62, -28, -18), (-62, -42, -12), (-26, -28, 68), (22, -34, 56), (-68, -16, 36), (-66, -34, 32), (36, -38, 40), (-42, -56, 4), (-58, -56, 6), (-16, -66, 10), (-12, 56, -16), (-12, 14, 56), (-14, 36, -16), (-12, 48, 34), (-12, 10, 44), (-10, -28, 38), (-12, 50, 40), (-12, -66, 28), (28, -38, -12), (-36, 12, -34), (-38, -22, -14), (-4, -68, -4), (-46, 10, -40), (-50, -18, 38), (-46, -38, -12), (12, -66, -10), (-54, 36, 4), (40, 10, 10), (44, -12, 24), (38, 8, 2), (-56, -8, 8), (-70, -6, 10), (-10, -70, 14), (4, -82, -2)]
#corr_matrix.shape . is (48, 48)

![hoatlas](https://user-images.githubusercontent.com/7142903/39134672-6c69c49a-4717-11e8-8edb-042b1000e6ff.png)

**Comment by GaelVaroquaux** [comment]
Where did you get the coord_map? It's probably wrong.

**Comment by grjd** [comment]
```
atlas_name = 'nilearn_data/fsl/data/atlases/HarvardOxford/HarvardOxford-cort-maxprob-thr25-2mm.nii.gz''
dataset = datasets.fetch_atlas_harvard_oxford(atlas_name)
atlas_filename = dataset.maps(masker = NiftiLabelsMasker(labels_img=atlas_filename ....)
```

**Comment by GaelVaroquaux** [comment]
I am not sure that this tells me how the variable "coord_map" was defined.

**Comment by grjd** [comment]
yes you are right, sorry, I built this dictionary below with the coordinates I found in FSL.
 Is there any way to get the MNI coordinates  of the Harvard-Oxford directly from nilearn ?

dim_coords_mm = OrderedDict([(labels[0],(-18, 76,0)), (labels[1],(28,28 ,-6 )),(labels[2],(33, 73, ```
63)),
	(labels[3],(26,32 ,40 )),(labels[4],(38, 42,10 )),(labels[5],(38, 30, 24)),(labels[6],(-10,10 ,66 )),
	(labels[7],(-44,26 ,-6 )),(labels[8],(-68, 6, -6)),(labels[9],(-72, -8,0 )),(labels[10],(-70, 6, -18)),
	(labels[11],(50, -10,-10)),(labels[12],(-66,-42 ,6 )),(labels[13],(34, 10, -38)),(labels[14],(-62,-28 ,-18 )),
	(labels[15],(-62, -42,-12 )),(labels[16],(-26,-28 ,68 )),(labels[17],(22, -34, 56)),(labels[18],(-68, -16,36 )),
	(labels[19],(-66,-34 ,32 )),(labels[20],(36, -38, 40)),
	(labels[21],(-42, -56, 4)),
	(labels[22],(-58, -56, 6)),(labels[23],(-16, -66, 10)),(labels[24],(-12,56 ,-16 )),(labels[25],(-12, 14, 56)),
	(labels[26],(-14,36 ,-16 )),
	(labels[27],(-12, 48, 34)),
	(labels[28],(-12,10,44)),(labels[29],(-10,-28, 38)),(labels[30],(-12,50 ,40)),(labels[31],(-12,-66 ,28 )),
	(labels[32],(28,-38 ,-12)),
	(labels[33],(-36, 12,-34)),
	(labels[34],(-38,-22, -14)),(labels[35],(-4,-68,-4)),(labels[36],(-46,10 ,-40 )),(labels[37],(-50, -18, 38)),
	(labels[38],(-46, -38, -12)),
	(labels[39],(12,-66 ,-10 )),
	(labels[40],(-54, 36, 4)),(labels[41],(40,10 ,10 )),(labels[42],(44, -12, 24)),(labels[43],(38,8,2)),
	(labels[44],(-56, -8, 8)), (labels[45],(-70, -6, 10)),(labels[46],(-10, -70, 14)),(labels[47],(4,-82,-2))]) 
```

**Comment by KamalakerDadi** [comment]
>Is there any way to get the MNI coordinates of the Harvard-Oxford directly from nilearn ?

For instance, you can use the code from this PR #1602

**Comment by KamalakerDadi** [comment]
@grjd did you tried with MNI coordinates ? are they still plotting outside the brain ?
if yes, please give us a fully reproducible script.
