### ISSUE TITLE
Update on click orthoslicer

### ISSUE THREAD

**Issue by mko010** [nilearn/nilearn#1637]
Hi guys, 
I want to know if orthoslicer update the rest of views (axial, coronal and sagital of brain) when you click on one of them, and How I can get one of that views separately?

Thank you.

**Comment by KamalakerDadi** [comment]
You may need to capitalize the arguments ```cut_coords``` for getting the slice position and ```display_mode``` for getting the one of the view in x, y, z. If I understood your question properly.

This example could give the demo http://nilearn.github.io/auto_examples/01_plotting/plot_demo_more_plotting.html#sphx-glr-auto-examples-01-plotting-plot-demo-more-plotting-py

**Comment by mko010** [comment]
Thank you so much
