### ISSUE TITLE
Documentation should point out that inputs are beta

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#164]
The current documentation and examples (in particular the Haxby example) are misleading, because they start from raw data. We need to stress that the typical situation is to start from beta maps, and that those beta maps need to be estimated by another software.

Also, we need to have other datasets that are made of beta maps to make the examples more realistic.

**Comment by AlexandreAbraham** [comment]
Adding a NeuroVault (and/or Neurosynth) fetcher is very easy and could give access to a large number of contrasts easily.

**Comment by banilo** [comment]
Good idea!

2015-01-28 11:19 GMT+01:00 Alexandre Abraham <notifications@github.com>:

> Adding a NeuroVault (and/or Neurosynth) fetcher is very easy and could
> give access to a large number of contrasts easily.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/issues/164#issuecomment-71810913>.
>



-- 
Viele Grüße,
Danilo

**Comment by AlexandreAbraham** [comment]
> Good idea! 

Looks like we have a volunteer :smiling_imp:

**Comment by GaelVaroquaux** [comment]
> Adding a NeuroVault (and/or Neurosynth) fetcher is very easy and could
> give access to a large number of contrasts easily.

Yes absolutely. However, these won't really give interesting decoding
problems. In this sens the poldrack dataset is more interesting. However,
it's also a very difficult problem.

I think that at the parietal retreat we should maybe make betas for one
of the openfmri datasets and upload them.

**Comment by bcipolli** [comment]
I'm very interested in the dataset fetching functionality of this project, so happy to help out on any of these.  Creating a fetcher, then trying to create an example, could be a great use of my time in getting more familiar with the package and neuroimaging analysis in general.

**Comment by GaelVaroquaux** [comment]
> I'm very interested in the dataset fetching functionality of this project, so
> happy to help out on any of these.

There are a few steps here:

1. Having a dataset (ie a set of beta maps). This involves probably
   running a preprocessing and Co

2. Uploading it to our online data storage and creating a downloader

3. Making an example.

I was suggesting that we might do the step 1 during the yearly retreat of
the Parietal team, which is going to happen early April.

**Comment by GaelVaroquaux** [comment]
Now that the Jimura-Poldrack data is in nilearn, we can tackle this issue. For instance by doing a toy example classifying gains versus losses.

Any one up for that?

**Comment by bthirion** [comment]
Solved by http://nilearn.github.io/auto_examples/02_decoding/plot_haxby_glm_decoding.html#sphx-glr-auto-examples-02-decoding-plot-haxby-glm-decoding-py I think
