### ISSUE TITLE
Brainomics url not responding

### ISSUE THREAD

**Issue by SylvainLan** [nilearn/nilearn#1641]
I am trying to run the example [http://nilearn.github.io/auto_examples/04_manipulating_images/plot_resample_to_template.html#sphx-glr-auto-examples-04-manipulating-images-plot-resample-to-template-py](url)

I am running into an error when trying to get the localizer dataset, with 
`localizer_dataset = fetch_localizer_button_task(get_anats=True)`

The url [https://brainomics.cea.fr/localizer](url) is indeed not responding. I have contacted Vincent Frouin, but wanted to warn you about it.

**Comment by bthirion** [comment]
Yep, we should probably find another placeholder for these files.
If somebody can volunteer for that, that would be great.

**Comment by GaelVaroquaux** [comment]
Could this be related to #1590 ? Ping @AGrigis

**Comment by KamalakerDadi** [comment]
Yes it is related. The idea is to fix this issue by #1590 and also hold a static version of this datasets in osf.io We should try and catch from static version whenever the server is down.

**Comment by SylvainLan** [comment]
OK sorry for the double post then, closing it

**Comment by GaelVaroquaux** [comment]
Wait: is the PR fixing this problem? If so we need to merge the PR.

**Comment by SylvainLan** [comment]
I reran the example today, and everything seems to work fine. The brainomics project's website is  responding well

This issue should be closed and issues related to this dataset should be addressed on #1590

**Comment by DimitriPapadopoulos** [comment]
Indeed the Brainomics server might have been down in the past. The server used to lack monitoring but the IT team has added Nagios agents to avoid such issues in the future. However the server will still be down once a year due to mandatory electrical maintenance in the server room.
