### ISSUE TITLE
test_uncompress does not test the right thing

### ISSUE THREAD

**Issue by pierreglaser** [nilearn/nilearn#1642]
Hello, 
so I was going through the `datasets/test_utils.py` and it seems that `test_uncompress` does not actually assert the right thing.

here is the test for the zipfile:
```
def test_uncompress():
    # Create dummy file
    fd, temp = mkstemp()
    os.close(fd)

    # Create a zipfile
    dtemp = mkdtemp()
    ztemp = os.path.join(dtemp, 'test.zip')
    ftemp = 'test'
    with contextlib.closing(zipfile.ZipFile(ztemp, 'w')) as testzip:
        testzip.writestr(ftemp, 'test')
    datasets.utils._uncompress_file(ztemp, verbose=0)
    assert(os.path.exists(os.path.join(dtemp, temp)))
    shutil.rmtree(dtemp) 
```

temp is a absolute filepath, created at the beginning of the function, and not touched afterwards. 
So `assert(os.path.exists(os.path.join(dtemp, temp)))` is basically doing 
`assert(os.path.exists(temp))` which is always true.

It seems that we should rather be testing if `ftemp`, which is the file that is supposed to be uncompressed, was indeed uncompressed correctly, using 
` assert(os.path.exists(os.path.join(dtemp, ftemp)))`

Any thoughts?

**Comment by bthirion** [comment]
Agreed. Can you issue a PR ?

**Comment by pierreglaser** [comment]
Yes - working on it, will be issued tomorrow.
