### ISSUE TITLE
Fetching image collection from Neurovault by DOI doesn't work

### ISSUE THREAD

**Issue by souravsingh** [nilearn/nilearn#1647]
Hello,

I am trying to download image collections from Neurovault based on DOI, as shown here- http://nilearn.github.io/modules/generated/nilearn.datasets.fetch_neurovault.html

But while trying to run the code, I encounter an issue-

```python
nv_data = datasets.fetch_neurovault(max_images=None, collection_terms=dict(basic_collection_terms(), DOI=NotNull()))

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-16-a21c37dc8c77> in <module>()
      2       "if you haven't downloaded any Neurovault data before "
      3       "this will take several minutes.")
----> 4 nv_data = datasets.fetch_neurovault(max_images=None, collection_terms=dict(basic_collection_terms(), DOI=NotNull()))

NameError: name 'basic_collection_terms' is not defined
```

Is this a mistake on my part or a bug?

**Comment by KamalakerDadi** [comment]
This should work
```python
from nilearn.datasets import fetch_neurovault
from nilearn.datasets.neurovault import NotNull

nv_data = fetch_neurovault(max_images=1, collection_terms=dict({'DOI': NotNull()}))
```
Similar to ```NotNull``` there are many helpers in the Neurovault API which can be used. See the Notes section of ```fetch_neurovault```.

```basic_collection_terms``` is a default selection criteria which can defined and used along with other selections, in your case with DOI like this
```python
from nilearn.datasets import fetch_neurovault
from nilearn.datasets.neurovault import basic_collection_terms, NotNull
print(basic_collection_terms())
nv_data = fetch_neurovault(max_images=1, collection_terms=dict(basic_collection_terms(), DOI=NotNull()))
```

**Comment by KamalakerDadi** [comment]
There exists also a minimal guide you may want to look at it. http://nilearn.github.io/building_blocks/neurovault.html

**Comment by souravsingh** [comment]
Thanks a lot for solving the query @KamalakerDadi
