### ISSUE TITLE
symmetric colormap in plot_surf

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#1648]
see http://nilearn.github.io/auto_examples/01_plotting/plot_3d_map_to_surface_projection.html#sphx-glr-auto-examples-01-plotting-plot-3d-map-to-surface-projection-py

for `plot_glass_brain` and `plot_stat_map`, the colormap is centered on 0;
activations are red and deactivations are blue. it is not the case for
`plot_surf_stat_map`, and `symmetric_cbar` seems to be ignored. `plot_surf` does
call `_get_colorbar_and_data_ranges` but does nothing with the values it returns
(except `vmax`).

it would be nice to be able to get the same behaviour in the surface plotting
functions as in the projection and slice plotting.

also, it might be nice to have a colorbar.

also, default colormap should probably be the same as in `plot_stat_map` i.e.
`cm.cold_hot`

**Comment by GaelVaroquaux** [comment]
Fixed in #1650
