### ISSUE TITLE
camera-ready surface plots

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#1649]
due to the use of matplotlib Axes3D, surface plots are saved with wide margins
that need to be cropped. Moreover, there is no colorbar. could it be possible to
have a function that prepares a camera-ready figure as e.g. `plot_stat_map`
does, possibly combining several views?

**Comment by mjboos** [comment]
Heya,
while I really like the surface plotting functionality I regularly stumble over the lack of colorbars and Axes3D idiosyncrasies. I recently fixed that locally and will make it into a PR.

**Comment by GaelVaroquaux** [comment]
> while I really like the surface plotting functionality I regularly stumble over
> the lack of colorbars and Axes3D idiosyncrasies. I recently fixed that locally
> and will make it into a PR.

Yey! Thank you. That's the way it's supposed to work.

Have you seen what just got merge? Interactive plots for the notebook:
https://github.com/nilearn/nilearn/pull/1665

**Comment by jeromedockes** [comment]
> I recently fixed that locally and will make it into a PR

that's great! thanks a lot Moritz!

**Comment by KamalakerDadi** [comment]
Closing with #1716
