### ISSUE TITLE
new_img_like fails for AFNIImage

### ISSUE THREAD

**Issue by CRiddler** [nilearn/nilearn#1662]
With the recent addition of nibabel to support Afni HEAD/BRIK files, I wanted to test out some code using AFNI's file format.

Copy pastable example:

    import os.path

    from nibabel.testing import data_path
    import nilearn

    def test_nifti():
        nifti_file = os.path.join(data_path, 'example4d.nii.gz')
        nifti_img = nilearn.image.load_img(nifti_file)

        nilearn.image.new_img_like(nifti_img, nifti_img.get_data(), copy_header=False)
        nilearn.image.new_img_like(nifti_img, nifti_img.get_data(), copy_header=True)

    def test_brik():
        brik_file = os.path.join(data_path, 'example4d+orig.BRIK.gz')
        brik_img = nilearn.image.load_img(brik_file)

        #Fails on if copy_header is either True or False for different errors
        nilearn.image.new_img_like(brik_img, brik_img.get_data(), copy_header=False)
        nilearn.image.new_img_like(brik_img, brik_img.get_data(), copy_header=True)

    test_nifti()
    test_brik()

**traceback when `copy_header=False`:**

	<ipython-input-9-42963bb91221> in test_brik()
		 15     brik_img = nilearn.image.load_img(brik_file)
		 16 
	---> 17     nilearn.image.new_img_like(brik_img, brik_img.get_data(), copy_header=False)
		 18     nilearn.image.new_img_like(brik_img, brik_img.get_data(), copy_header=True)
		 19 

	~/anaconda/lib/python3.6/site-packages/nilearn/image/image.py in new_img_like(ref_niimg, data, affine, copy_header)
		650         # we shouldn't return it
		651         klass = nibabel.Nifti1Image
	--> 652     return klass(data, affine, header=header)
		653 
		654 

	~/anaconda/lib/python3.6/site-packages/nibabel/spatialimages.py in __init__(self, dataobj, affine, header, extra, file_map)
		449         '''
		450         super(SpatialImage, self).__init__(dataobj, header=header, extra=extra,
	--> 451                                            file_map=file_map)
		452         if affine is not None:
		453             # Check that affine is array-like 4,4.  Maybe this is too strict at

	~/anaconda/lib/python3.6/site-packages/nibabel/dataobj_images.py in __init__(self, dataobj, header, extra, file_map)
		 40         '''
		 41         super(DataobjImage, self).__init__(header=header, extra=extra,
	---> 42                                            file_map=file_map)
		 43         self._dataobj = dataobj
		 44         self._fdata_cache = None

	~/anaconda/lib/python3.6/site-packages/nibabel/filebasedimages.py in __init__(self, header, extra, file_map)
		190            mapping giving file information for this image format
		191         '''
	--> 192         self._header = self.header_class.from_header(header)
		193         if extra is None:
		194             extra = {}

	~/anaconda/lib/python3.6/site-packages/nibabel/brikhead.py in from_header(klass, header)
		313         print(klass, header)
		314         if header is None:
	--> 315             raise AFNIHeaderError('Cannot create AFNIHeader from nothing.')
		316         if type(header) == klass:
		317             return header.copy()

	AFNIHeaderError: Cannot create AFNIHeader from nothing.

**traceback when `copy_header=True`:**

	---------------------------------------------------------------------------
	TypeError                                 Traceback (most recent call last)
	<ipython-input-11-4967bfa2a1ac> in <module>()
		 20 
		 21 test_nifti()
	---> 22 test_brik()

	<ipython-input-11-4967bfa2a1ac> in test_brik()
		 17     #Fails on if copy_header is either True or False for different errors
		 18     #nilearn.image.new_img_like(brik_img, brik_img.get_data(), copy_header=False)
	---> 19     nilearn.image.new_img_like(brik_img, brik_img.get_data(), copy_header=True)
		 20 
		 21 test_nifti()

	~/anaconda/lib/python3.6/site-packages/nilearn/image/image.py in new_img_like(ref_niimg, data, affine, copy_header)
		637     if copy_header:
		638         header = copy.deepcopy(ref_niimg.header)
	--> 639         header['scl_slope'] = 0.
		640         header['scl_inter'] = 0.
		641         # 'glmax' is removed for Nifti2Image. Modify only if 'glmax' is

	TypeError: 'AFNIHeader' object does not support item assignment

It seems that `copy_header=False` intentionally throws an error so I'm not sure about a fix for that. But when `copy_header=True` it seems like `new_img_like` is assuming we're working with a nifti image considering the header properties its trying to set. So maybe there could be an `isinstance()` check to see if the ref_niimg.header is a nifti header before attempting to assign the header variables?

**Comment by bthirion** [comment]
When `copy_header==False` what you obtain is a nibabel error. The way forward would be to add proper read/write capabilities in Nilearn for this type of image. Or  I am missing something ?

So far, we've intentially restricted our tools to Nifti images since this is the standard used by the community. I'm afraid of the zoology of possible image types and variants thereof.  What is this BRIK image ?

**Comment by CRiddler** [comment]
> When copy_header==False what you obtain is a nibabel error

Yes, but its an error that's caused at the nilearn level, so it could either be nibabel `AFNIHeader` needs to implement `__getitem__`, but unless I'm mistaken, AFNI HEAD files don't have these attributes ("scl_slope", "scl_inter") to begin with.

> So far, we've intentially restricted our tools to Nifti images since this is the standard used by the community.

Ah, I was unaware of that- thanks for letting me know though! This is probably the root of my issue, I'll see into transferring my files into Nifti format since it is more widely known/accepted than what I'm trying to use.

> What is this BRIK image?

A BRIK file is a file format used by AFNI (Analysis of Functional Neuro Imaging), a software tool created an maintained by a group at the National Institutes of Health. [AFNI website](https://afni.nimh.nih.gov)

**Comment by KamalakerDadi** [comment]
So far, Nilearn is used heavily to process Nifti images. Could you please convert AFNI2Nifti and try ?

Sidenote: We have before similar problems with spm2Analyze, spm99Analyze and now Brik image formats. If the API doesn't get too complex then I think we should also handle non-nifti images. Needs to be deeply thought.

**Comment by CRiddler** [comment]
> Could you please convert AFNI2Nifti

Yep, I converted from Afni format to Nifti format and was able to get my code to work.

I'll go ahead and close this issue, since I wasn't aware `nilearn` was mainly focused on nifti format. Thanks for the insight!

**Comment by emdupre** [comment]
Would it be worth documenting this somewhere, to at least pin for discussion as @KamalakerDadi mentioned ? I ask since I imagine this question is likely to come up again, particularly since BRIK file-handling is a brand new functionality in Nibabel.

**Comment by GaelVaroquaux** [comment]
Well, it's either this, or someone contributes tests and fixes to handle
this type of images. I am not opposed to it, as long as there is some
maintenance.

**Comment by bthirion** [comment]
Stalled.
