### ISSUE TITLE
missing import in user guide example 

### ISSUE THREAD

**Issue by PeerHerholz** [nilearn/nilearn#1664]
A rather simple and easy one:

the [searchlight section](https://nilearn.github.io/decoding/searchlight.html) of the user guide's [2. Decoding and MVPA: predicting from brain images](https://nilearn.github.io/decoding/index.html) part is missing an import function which is necessary to run the example successfully. 

More precisely,  within [2.4.4. Running Searchlight](https://nilearn.github.io/decoding/searchlight.html#running-searchlight) `nilearn.decoding.Searchlight` is used to define a searchlight without importing `nilearn.decoding` before, as e.g. in the comparable nilearn usage example [8.3.6. Searchlight analysis of face vs house recognition](https://nilearn.github.io/auto_examples/02_decoding/plot_haxby_searchlight.html#searchlight-computation).

Should I change the [corresponding part in the searchlight.rst file](https://github.com/nilearn/nilearn/blob/master/doc/decoding/searchlight.rst#running-searchlight) and open a pull request?

Discovered via a [post on neurostars.org](https://neurostars.org/t/searchlight-questions-in-nilearn/1870).

**Comment by KamalakerDadi** [comment]
@PeerHerholz Thank you for posting the issue here. Can you open a PR to get this import.

But, the idea behind the user guide is to give the gentle introduction about concepts used in the search light analysis with nilearn. From there a user can follow a gallery to full example.

**Comment by KamalakerDadi** [comment]
Closing with #1718
