### ISSUE TITLE
add fetch_surf_fsaverage

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#1666]
we have `nilearn.datasets.fetch_surf_fsaverage5` to fetch fsaverage5. It seems many users prefer to use meshes with a finer resolution; should we add `fetch_surf_fsaverage` to fetch fsaverage? we may have to transform the freesurfer files to gifti using freesurfer's mris_convert and mri_convert and upload them somewhere we can fetch them from

@KamalakerDadi  @juhuntenburg @GaelVaroquaux

**Comment by GaelVaroquaux** [comment]
I am fine with the plan.

**Comment by juhuntenburg** [comment]
+1

**Comment by bthirion** [comment]
+1 on that

**Comment by jeromedockes** [comment]
waiting on nitrc's confirmation to upload the files

**Comment by KamalakerDadi** [comment]
closing with #1668
