### ISSUE TITLE
Add Schaefer/Yeo atlas

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#1667]
There is rapidly increasing adoption of the SchaeferYeo atlas now in the imaging neuroscience community. It would be great to add it soon in nilearn.datasets has been precomputed with 100, 200, 300, ... 1000 parcellations including their assignment to the original 7 and 17 Yeo networks.

https://github.com/ThomasYeoLab/CBIG

**Comment by GaelVaroquaux** [comment]
Sounds great. PR welcome. 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by fliem** [comment]
Is anybody working on that? I'd be happy to create a PR.

**Comment by kchawla-pi** [comment]
@fliem Thanks! GO for it! Let us know if you need help.
