### ISSUE TITLE
Upgrading CircleCI to v2.0 before Aug 31.

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1676]
See PR #1733 

Circle CI 1.0 is being EOL'd on Aug 31. Many people may not be around in Aug, indicating we should do the upgrade in July. Thoughts?

**Comment by GaelVaroquaux** [comment]
Yes we should. Do you want to send a pull request? 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by kchawla-pi** [comment]
I am studying CircleCI config file from another project to get clues about transitioning to CircleCI 2.0 (SKLearn's. Thanks Kamalaker) and will apply the lessons here.

**Comment by KamalakerDadi** [comment]
https://circleci.com/docs/2.0/workflows/

**Comment by kchawla-pi** [comment]
No matter what I do I am unable to export the path to conda in the circleci docker image.
Looked at all the sources for help.
Its all fine if use the absolute path of conda for each command, but that fails within the shell scripts.
I will need help on this one.

**Comment by GaelVaroquaux** [comment]
Yes, indeed, I see that there is a challenge. I'll see if I can get some
help here, at the brainhack Montreal.

**Comment by kchawla-pi** [comment]
I have one more idea that I will try out.

**Comment by kchawla-pi** [comment]
My first idea, using an ubuntu docker image and installing stuff in it didn't work, as the docker image does not have wget command to get miniconda.

My second idea is that we build a custom docker image with all the environments etc already setup. This will give us a pristine environment for every test run, without having to redownload & reinstall everything, saving heaps of time.

Additionally, there seems to be a lot of redundancy in the build setup. We are installing packages from within the circleci's YAML file and then also from within the shell scripts??
If we can move the setup stages out of the shell scripts, whether via a custom docker image or config.yml, that will be neat.

**Comment by kchawla-pi** [comment]
I emailed CircleCI and they have responded with a few options. Gonna try them now.

**Comment by kchawla-pi** [comment]
Think it worked!

**Comment by kchawla-pi** [comment]
Seems that particular pit-stop has been solved. Stuff seems to be running, all the way to circle_ci_test_doc.sh, which starts out fine and then glitches soon after, with `ModuleError: No Module named scipy`.
This is big step forward. Will look into this tomorrow.

**Comment by kchawla-pi** [comment]
@GaelVaroquaux There is a lot of scope for simplification & improving efficiency of this. Once you are back, let's go over this.

**Comment by bthirion** [comment]
Great, thx for this important infrastructure work.

**Comment by kchawla-pi** [comment]
The latest push has 2 problems:

1. At many places I get the error: 
`ValueError: Found input variables with inconsistent numbers of samples: [1452, 864]`

2. The test seems to stall. This happens in different examples every time I run it.

**Comment by kchawla-pi** [comment]
Okay its happening on `examples/02_decoding/plot_haxby_space_net.py`
