### ISSUE TITLE
plot_glass_brain problem

### ISSUE THREAD

**Issue by zjjydycg** [nilearn/nilearn#1678]
Hi nilearn team, thanks for you great work !

I just started to learn to use your functions and I tried to use you plotting function and got the following error :

In [6]: plotting.plot_glass_brain("/Volumes/15626490320/dpabi_sec_stats/before/R2.nii")
Out[6]: <nilearn.plotting.displays.OrthoProjector at 0x1c1c7ebda0>

Could you please help me to solve this problem? Thanks.

**Comment by KamalakerDadi** [comment]
It is not an error. try doing ```plotting.show()```. To display a figure you need to do that.

Have a look at this:
https://nilearn.github.io/auto_examples/01_plotting/plot_atlas.html#sphx-glr-auto-examples-01-plotting-plot-atlas-py

**Comment by KamalakerDadi** [comment]
CLosing this one. Please reopen if you have any error with a reproducible script.
