### ISSUE TITLE
01_plotting/plot_overlay.html doc seems broken

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1683]
Hi

I am getting a page not found for the plot_overlay example on the nilearn web site doc
http://nilearn.github.io/auto_examples/_01_plotting/plot_overlay.html

**Comment by KamalakerDadi** [comment]
oops. how did you get this ?

It should be like this: http://nilearn.github.io/auto_examples/01_plotting/plot_overlay.html

**Comment by salma1601** [comment]
I just clicked on the image for the display.add_overlay example on the page

http://nilearn.github.io/plotting/index.html

 (section 4.3)

**Comment by salma1601** [comment]
I can fix it if you want, it's just a typo in the index of plotting

**Comment by KamalakerDadi** [comment]
>I can fix it if you want, it's just a typo in the index of plotting

Sure. Please do a PR on this issue. Thanks
