### ISSUE TITLE
_extrapolate_out_mask does not use the Z dimension

### ISSUE THREAD

**Issue by zanospi** [nilearn/nilearn#1689]
PR: #1690

Hi,

The hidden **_extrapolate_out_mask function** in `masking.py` only uses the X (twice) and Y (once) dimension to calculate the new voxels. It should use the mean of the close voxels over all 3 dimensions.

Pull request incoming: it will make things clearer.

BR,

Romuald

**Comment by KamalakerDadi** [comment]
Closing with #1690
