### ISSUE TITLE
Add Python2 deprecation warning for the next release.

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1696]
We should target Python3.6.3 onwards as the minimum supported version.
It has under the hood performance improvements and I want my fstrings!

Python professionals seem to be finally satisfied with this version as THE version that's good enough to switch to.

**Comment by GaelVaroquaux** [comment]
> We should target Python3.6.3 onwards as the minimum supported version.

Not convinced.

**Comment by kchawla-pi** [comment]
@GaelVaroquaux Did we add the deprecation warning to the alpha?

**Comment by GaelVaroquaux** [comment]
No, we can do it for the beta.

G
