### ISSUE TITLE
plot_surf_roi

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#1697]
The interface of plot_surf_roi is buggy, confusing and inconsistent with
plot_roi.

it takes a roi_map, which can be:

- a list -> interpreted as a list of list of node indices, each for an roi.
- an array of the same shape as the mesh -> interpreted as a mask
- an array of a different shape -> interpreted as a list of indices for the roi nodes.
- a string -> should be interpreted as the path to a surface map (according to docstring), but results in an exception.

I suggest we only accept valid surface maps (i.e. arrays of shape (# of nodes,),
or paths to surface map files that contain a map of the same shape), and treat them
as atlases with two regions (0=background, 1=roi). If a user has an ROI in the
form of a list of node indices, they can easily produce a mask themselves with
mask = np.zeros(len(mesh), dtype=int); mask[roi_idx] = 1. plot_roi only accepts full volume maps
so this would be consistent.

at the very least, we must remove the different behaviour for lists and arrays, and
treat paths to surface images correctly.

@KamalakerDadi  @GaelVaroquaux

**Comment by KamalakerDadi** [comment]
@jeromedockes do you think this can be closed in favour of #1991

**Comment by jeromedockes** [comment]
> @jeromedockes do you think this can be closed in favour of #1991

I think so
