### ISSUE TITLE
Specifying encoding to read unicode strings

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1698]
I am getting this Visible Deprecation Warning:

/nilearn/nilearn/datasets/func.py:503: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  dtype=None)

I haven't looked at the code yet but seems it would be simple enough to fix.
What's the encoding being used? I can fix it.

**Comment by NicolasGensollen** [comment]
@kchawla-pi this looks outdated and there is no way to reproduce. 
Should we close?
