### ISSUE TITLE
Upgrade the imposed scikit-learn  ( + numpy and scipy) version

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1702]
The imposed scikit-learn version (specified in nilearn/version.py) must be upgraded to v0.17, which also means upgrading the numpy and scipy.
SKL has deprecated the cross_validation module from v0.17 onwards. NiLearn's examples are being changed to accommodate this. The new examples will not work with SKL v0.16 and lower.
The documentation & comments in the example must also be changed to reflect this.

**Comment by GaelVaroquaux** [comment]
Fixed in #1691
