### ISSUE TITLE
Ship fsaverage5 with nilearn

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1705]
We now need fsaverage5 for basic interactive plotting functionality. It is retrieved via datasets.fetch_surf_fsaverage.

However, as any Internet access, this is brittle and can fail. For example:
https://ci.appveyor.com/project/nilearn-ci/nilearn/build/1.0.2612/job/0bn4wduir9icwafu

I suggest that we embed in nilearn the files needed for plotting, after compression with "gzip --best". It gives the following sizes:

```
$ ll -h
total 784K
-rw-r--r-- 1 varoquau varoquau 196K Jul 26 14:49 pial_inflated.left.gii.gz
-rw-r--r-- 1 varoquau varoquau 196K Jul 26 14:49 pial_inflated.right.gii.gz
-rw-r--r-- 1 varoquau varoquau 196K Jul 26 14:49 pial.left.gii.gz
-rw-r--r-- 1 varoquau varoquau 196K Jul 26 14:49 pial.right.gii.gz
```
This will make the download bigger by 784K, but the addition of the javascript libraries already added 1.3M (coming mostly from plotly-gl3d-latest.min.js).

The code of datasets.fetch_surf_fsaverage will need to be modified to load these files when it is fsaverage5 pial.

**Comment by GaelVaroquaux** [comment]
This has become a major issue: it is breaking all our CI. We unfortunately need to address it urgently.

@KamalakerDadi : do you have some spare cycles?

**Comment by KamalakerDadi** [comment]
What are files needed to be shipped ? Everything surface plotting uses ?

**Comment by GaelVaroquaux** [comment]
Listed above. And they need to be gzipped with best compression.

**Comment by KamalakerDadi** [comment]
Ok. I am on it.

**Comment by GaelVaroquaux** [comment]
Thank you so much Kamalakar!

**Comment by KamalakerDadi** [comment]
Shall we do the same for brainomics localizer data. Shipping only part of data where examples are dependant on ?

Right now it is down again http://brainomics.cea.fr/localizer

**Comment by GaelVaroquaux** [comment]
No: fsaverge affects the tests, more than the examples. 

Brainnomics will be addressed by @bthirion in a separate PR.

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by KamalakerDadi** [comment]
Does this needs to be uncompressed in home directory in nilearn_data folder ?

**Comment by GaelVaroquaux** [comment]
> Does this needs to be uncompressed in home directory in nilearn_data folder ?

No, shipped like the template, avg152T1_brain.nii.gz in datasets/data.

They can be gzipped separately, and then they don't need to be unzipped:
nibabel knows how to read from gzipped files.

**Comment by KamalakerDadi** [comment]
> They can be gzipped separately, and then they don't need to be unzipped: nibabel knows how to read from gzipped files.

Meaning if I give directly the gzipped files to plotting functions it should work, right ?

**Comment by KamalakerDadi** [comment]
gzipped gifti files doesn't work with nibabel.load or gifti.read ?

**Comment by GaelVaroquaux** [comment]
> Meaning if I give directly the gzipped files to plotting functions it should work, right ?

Yes
