### ISSUE TITLE
replacement of brainomics-based examples

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#1708]
One example is hard to update with a brainomics -> Neurovault replacement:
examples/05_advanced/plot_localizer_mass_univariate_methods.py
as it uses not only brain images but also behavioral variables that will not be available from NeuroVault
I see 2 options:
* cp the Brainomics stuff to osf and keep the example mostly as is
*  replace the example by a simple one-sample t-test
What do people think ?

**Comment by GaelVaroquaux** [comment]
>   • cp the Brainomics stuff to osf and keep the example mostly as is
>   • replace the example by a simple one-sample t-test

Maybe the advanced part of this example is redundant with nistats? In
which case we can replace it by something simpler.

**Comment by bthirion** [comment]
Makes sense. I'll try to take care of that.

**Comment by KamalakerDadi** [comment]
Can be closed I guess ?

**Comment by GaelVaroquaux** [comment]
> Can be closed I guess ?

Yes!
