### ISSUE TITLE
New CI test env with packages built from their latest master

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1728]
In light of issue #1724 , should we add an 'Allowed to Fail' test to the CIs, where all the primary packages are built from the current master source? For example, in this issue, SKLearn master had a bug. I used `make` to build it from source, installed that in my local environment and then debugged the issue.

I  may create a local testing script to repeat this formyself.

Would it be worth while to clone masters of SKL, Numpy, SciPy, build from source & install them and then run tests in that environment?
It would catch such glitches earlier and help the package maintainers certainly, it may also add to our CI times.

What do you all think?

**Comment by bthirion** [comment]
Sounds like a great suggestion.

**Comment by kchawla-pi** [comment]
Continued from https://github.com/nilearn/nilearn/pull/2523#issuecomment-645672671

>> This was outlined in #1728 . If you wish, you can reopen that discussion.
>
> yes I think we can. With respect to #2224 which closed #1728 I am
wondering if we should:
>
> - test with master branches or nightly builds besides or instead of alpha, beta, rc releases
> - make this a scheduled job rather than one triggered by PRs
>
> WDYT?

I think we should leave test with master on a schedule, not PR triggerred. Weekly should be sufficient, so long as the results are not forgotten about, which is possible when we see it only once a week. We could set up an email notification if this job fails. The details are up to you all.

I would leave the current Travis precheck as it is. The master builds are for long term foresight of problems, but can be overwhelming if we take them super-seriously all the time.

The Travis Pre Builds will sound an alarm for impending releases, when the break is close & likely. Far as I know, all our core libs release RCs via pip so this should be fine.

If the extra time taken by Travis is an issue, the builds can be moved to Azure Pipelines. It has many spare containers.

**Comment by bthirion** [comment]
I'm note sure I fully get the core question: is it to reduce pressure on Travis ?  To reduce false alarms ? Cut redundancies btw Travis and Azure ?
I am used to Travis, so I need good motivation to change ;-)

**Comment by jeromedockes** [comment]
> I'm note sure I fully get the core question: is it to reduce pressure on Travis ?  To reduce false alarms ? Cut redundancies btw Travis and Azure ?

The core question is whether we should have a CI job that installs the
master branch of the dependencies, rather than installing from PyPi, so
that we catch breaking changes in e.g. scikit-learn early.

> I am used to Travis, so I need good motivation to change ;-)

(note we are already using both travis and azure; this job could be
added on either one)
