### ISSUE TITLE
fetch_neurovault_ids specifying the collection seems to return only one image

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1731]
"data = datasets.fetch_neurovault_ids(collection_ids=[658])"
returns only one image, while I think that there are several images in the collection.

**Comment by jeromedockes** [comment]
can you try again with mode='overwrite'?

**Comment by jeromedockes** [comment]
and I don't think that's the problem but neurovault warns that this collection is missing "crucial metadata"

**Comment by KamalakerDadi** [comment]
I tried with mode='overwrite' and downloaded 65 images.
