### ISSUE TITLE
accessing and saving cutAxes images

### ISSUE THREAD

**Issue by jmparelman** [nilearn/nilearn#1734]
I am wondering if it is possible to save to disc each of the CutAxes image slices that are rendered during an ortho_slice plot call? 

I see that each of the slices are accessible like this:
`myPlot = plotting.plot_stat_map(avgIm, threshold=-.2,display_mode='x')`
`myPlot.axes`

and when i dig a little deeper into the matplotlib.axes object to access the plot data, it seems like i'd have to essentially reconstruct the AxesImages if I wanted to save them how they are displayed in the nilearn plot. I don't want to make a new nilearn.plot for each slice coordinate, and accessing these images once they've already been rendered in the `plotting.displays.XSlicer` would be much faster and easier. It'd be great to see some sort of function like `myPlot.axes[49].savefig()`.

Any help is really appreciated! Thanks

**Comment by KamalakerDadi** [comment]
>I am wondering if it is possible to save to disc each of the CutAxes image slices that are rendered during an ortho_slice plot call?

With this step, you can grab the cut coordinates.
```python
myPlot = plotting.plot_stat_map(avgIm, threshold=-.2,display_mode='x')
```

With this step, use the coordinates grabbed from step 1 to loop over and save.
```python
for coord in coords:
    myPlot = plotting.plot_stat_map(stat_img, cut_coords=[coord], display_mode='x')
    plt.savefig(str(coord) + '.png')
```
If it helps please close the issue.

**Comment by jmparelman** [comment]
This isn't quite what I'm asking for help with. I know that I could draw a new single-slice plot for each of the coords I'd like, but that would take a long time if I was say, making a plot for every other slice in an entire volume and saving each of those. I've found that plotting all of the coordinates I want into a single `display.Xslicer`is significantly faster than doing that, and saving the orth_plot and cropping it for each image with PIL doesn't seem to work very well. 

 If I could access each of the subplots from the `display.Xslicer` and get each image as it appears in the `Xslicer`, I could finish up a project I'm working on to make a lightweight inline viewing tool for ipython notebooks, My widget is essentially the same as the `Niwidget` but would render the images before plotting to make it run smoother as apposed to on the fly. 

Thanks again for the help

**Comment by bthirion** [comment]
Would the following work ?
```
plop = myPlot.axes.popitem()[1]
extent = plop.ax.get_window_extent().transformed(plop.ax.axes.figure.dpi_scale_trans.inverted())
plop.ax.figure.savefig('/tmp/plop.png', bbox_inches=extent)
```

**Comment by jmparelman** [comment]
Thanks @bthirion that worked perfectly.
