### ISSUE TITLE
how to skip tests requiring network access?

### ISSUE THREAD

**Issue by yarikoptic** [nilearn/nilearn#1735]
to satisfy debian policy and robustify build system (so pkg remains rebuildable regardless either the universe is still out there ;-)) we need to disable all internet access while building (neuro)debian package.
We do run unittests at pkg build. ATM a bunch of tests fail to fetch the datasets they need.  Is there some way provisioned to skip those tests may be?

**Comment by bthirion** [comment]
I tried to look at the tests and at first sight it seems to me that the main downloads performed are from NeuroVault. Am I wrong ?

**Comment by kchawla-pi** [comment]
DIdn't we embed some of the data necessary for tests in the latest alpha? Are these different?

**Comment by jeromedockes** [comment]
> I tried to look at the tests and at first sight it seems to me that the main downloads performed are from NeuroVault. Am I wrong ?

you're right. we could mock neurovault but then the tests aren't really useful. we can remove them but it will reduce coverage significantly

**Comment by NicolasGensollen** [comment]
I believe this has been addressed in #2514
