### ISSUE TITLE
plot_decoding_tutorial.py:  condition_mask is not being applied to fmri_masked (?)

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1736]
While running `/examples/plot_decoding_tutorial.py`, I am getting this error (and so is CircleCI 2.0)
@bthirion found that while condition_mask should be applied to both conditions and fmri_masked, in the latter case, it looks like no masking is applied. He thinks Pandas is to blame.

```
Traceback (most recent call last):
  File "examples/plot_decoding_tutorial.py", line 144, in <module>
    svc.fit(fmri_masked, conditions)
  File "/home/kshitij/anaconda3/envs/nilearn-py35/lib/python3.5/site-packages/sklearn/svm/base.py", line 151, in fit
    X, y = check_X_y(X, y, dtype=np.float64, order='C', accept_sparse='csr')
  File "/home/kshitij/anaconda3/envs/nilearn-py35/lib/python3.5/site-packages/sklearn/utils/validation.py", line 531, in check_X_y
    check_consistent_length(X, y)
  File "/home/kshitij/anaconda3/envs/nilearn-py35/lib/python3.5/site-packages/sklearn/utils/validation.py", line 181, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [1452, 216]
```
I have encountered this kind of error before, but not when running in `jupyter lab`. Now it is occurring in that as well.

Package versions:
 - pandas=0.23.1
 - python=3.5.0
 - scikit-learn=0.18
 - scipy=0.17.0
 - numpy=1.11.0
 - matplotlib=1.5.1

I have noticed that both `conditions` and `condition_mask` are of type `pandas.core.series.Series`, `fmri_masked` is of type `numpy.ndarray`. Dunno yet if that's relevant here.

**Comment by kchawla-pi** [comment]
I am not getting this error in my Python3.6 based environment that draws its specs from TravisCI.

**Comment by thomasbazeille** [comment]
I think this has not been observed anymore since python version bumping, and the example was reworked.

Can be closed ?

**Comment by tbng** [comment]
Sorry could you provide the modification to the `plot_decoding_tutorial.py` that produces the error? I rerun the default example without a problem.

**Comment by thomasbazeille** [comment]
@tbng this was solved during the sprint no? Can you point me to the related PR ?

**Comment by tbng** [comment]
On 16.09.2020 03:41, ThomasBaz wrote:
>@tbng this was solved during the sprint no? Can you point me to the related PR ?
>
Again I cannot reproduce this bug, but I think it is solved with PR gh-2451
during the last sprint.

**Comment by bthirion** [comment]
OK, time to close then.
