### ISSUE TITLE
bugs in plot_surf

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#1738]
- zeros are always thresholded, even when threshold=None. the culprit is this line:
```
                kept_indices = np.where(surf_map_faces)[0]
```
- when no background map is provided, an empty transparent mesh is shown, rather than a solid grey background

the problem is here
```
    # set alpha if in auto mode
    if alpha == 'auto':
        if bg_map is None:
            alpha = .5
        else:
            alpha = 1

```
and here
```
        # modify alpha values of background
        face_colors[:, 3] = alpha * face_colors[:, 3]
        # should it be possible to modify alpha of surf data as well?

```
(here the background is made half transparent even if nothing will be plotted on top of it)

also, maybe this 185-line function could be refactored a bit

**Comment by KamalakerDadi** [comment]
Related to PR #1997
