### ISSUE TITLE
Bug in plotting slice coordinates? (nilearn 0.4.0)

### ISSUE THREAD

**Issue by jnecus** [nilearn/nilearn#1740]
Hello team,

I am wondering whether this is a bug in the display for nilearn. When I view the same anatomical image using the same scanner coordinates they appear to be slightly displaced from one another.

For example, see the screenshot below. Both the top and bottom image show exactly the same T1 image located at coordinates (-8, 107, -52). The top half of the image is displayed using the following command in nilearn (version 0.4.0) : 

`plot_anat(t1_scan,cut_coords=[-8,107,-52])`

The bottom half is displayed using fsleyes, you can see the coordinates and corresponding voxel locations underneath. The difference in the images is most notable in the z plane.

![screenshot at 2018-08-21 18-53-22](https://user-images.githubusercontent.com/18306309/44419922-6db26f80-a574-11e8-9364-1ac15c6629d7.png)

**Comment by jeromedockes** [comment]
according to the documentation, the cut_coordinates used by plot_anat are MNI
coordinates, not scanner coordinates. does this explain the difference you see?

**Comment by jnecus** [comment]
Hello,

@jeromedockes Thank you for your fast response.

I take your point that the documentation specifies MNI space. However, my T1 image is in native space, and I has assumed that the documentation refers to use of the default MNI152 anat_image.

I am not so sure that this is the answer to my problem. If I try to plot the same coordinates above on the default MNI brain, this location doesn't exist. (I.e. slice [-8, 107, -52] is outside of the field of view in MNI space).

Also, if it were the case that I was mistaking MNI space for subject space then I wouldn't expect the images to map as closely together as they do in the image above.

**Comment by bthirion** [comment]
Can you reproduce the issue with some random (non-normalized) T1 image ? That would help !

**Comment by GaelVaroquaux** [comment]
I think that part of the confusion comes from the fact that the
documentation uses a slightly imprecise wording: rather than "MNI
coordinate" we should be saying "brain-space coordinates (typically
MNI)".

**Comment by jnecus** [comment]
Hi Both @bthirion @GaelVaroquaux

I have reproduced this using an MRI image which can be found at the following location: https://drive.google.com/open?id=1IdH2Sx6CFP8i2b5NUBfOOaRe2a99zOWM

I have also reproduced this using this shared T1 image on nilearn, fsleyes and mricron. Both fsleyes and mricron are in agreement, confirming that this is not a problem with fsleyes. Please see the image below.

The coordinates used are -3, -5, 30. So the corresponding nilearn function would be: 

`plot_anat(anat_img='t1', cut_coords=[-3,-5,30])`

I have highlighted where the coordinates are displayed on mricron and fsleyes in red, and have highlighted the discrepancy in anatomical location in blue (it is most easily seen in the ventricles).

![comparison](https://user-images.githubusercontent.com/18306309/44865599-b0fa9580-ac7a-11e8-9429-ec37efe14998.png)

**Comment by jnecus** [comment]
Do we feel that this is a bug? Or am I maybe just being a bit slow?

**Comment by jeromedockes** [comment]
looking at the first two rows in the images above, the coordinates seem to be the same, but the angle of the slice seems different -- the head displayed by nilearn appears to be tilted backwards and to the right with respect to fsleyes and micron

**Comment by bthirion** [comment]
We should check whether Nilearn handles correctly off-diagonal coeffs of the affine.

**Comment by bthirion** [comment]
Hi,
I've done a further experiment: I've resampled the t1 image to get a diagonal affine.
```
target_affine = np.array([[1, 0, 0, -96],[0, 1, 0, -90],[0, 0, 1, -130]
img_ = resample_img(img, target_affine=target_affine)         
img_.to_filename('/tmp/t1.nii.gz')
```
Then I've plotted the resulting image with Nilearn and FSLeyes.
with Nilearn, the same thing is displayed.
Now, FSLeyes displays the same thing as Nilearn.

To me, this means that FSLeyes does not take into account properly the information contained in the affine transformation in the image. This is seen when the affine is not a pure translation + rescaling, but also contains some rotation part.
Does that make sense to you ?

**Comment by jeromedockes** [comment]
>  Does that make sense to you ?

yes. @jnecus do you see the same behaviour with micron?

**Comment by jnecus** [comment]
@bthirion @jeromedockes  I see the same behaviour with mricron as described above. 

I.e. Both FSLeyes and mricron show the same display behaviour as nilearn after the following resampling process:

```
img=nib.load('original_t1.nii.gz')
target_affine = np.array([[1, 0, 0, -96],[0, 1, 0, -90],[0, 0, 1, -130],[0,0,0,1]])
img_ = resample_img(img, target_affine=target_affine)        
img_.to_filename('resampled_t1.nii.gz')

```

**Comment by jeromedockes** [comment]
thanks! so if I understand correctly nilearn's behaviour is the correct one, we can close this issue (and optionally open issues on fsleyes and micron)

**Comment by jnecus** [comment]
Admittedly I haven't had the chance to digest what the issue above is yet. However, my only concern is that fsleyes and mricron have been around for much longer and are likely much more widely used. While this doesn't mean that they are 'correct' it is at least concerning that these longstanding pieces of MRI viewing software which will have been used to generate numerous now published figures are behaving differently to nilearn. (I realise that fsleyes is relatively new, but certainly its precursor 'fslview' was around for a while). 

Any thoughts?

**Comment by bthirion** [comment]
I understand your concern. 
I believe that part of the problems is that fsleyes doe not perform data resampling, hence plots th image in the provided grid coordinates. This being said, i'm not an FSL expert.
Would you submit the current case to the fsleyes people so that we understand their reasoning on that ?
Thx for taking time on this !

**Comment by pauldmccarthy** [comment]
Hey all, it looks to me like there is no problem here - FSLeyes and nilearn just default to displaying the images differently. FSLeyes defaults to displaying in a scaled voxel coordinate system, and nilearn defaults to displaying in the coordinate system defined by the image affine.

**Comment by GaelVaroquaux** [comment]
> Hey all, it looks to me like there is no problem here - FSLeyes and nilearn
> just default to displaying the images differently. FSLeyes defaults to
> displaying in a scaled voxel coordinate system, and nilearn defaults to
> displaying in the coordinate system defined by the image affine.

Indeed, I think that this is a good summary.

**Comment by jnecus** [comment]
@GaelVaroquaux  @pauldmccarthy Thank you this seems to make sense and happy to go with this answer :) .

Just finally to fully clear this up for me, how would I instruct nilearn to display a slice matching that in FSLeyes. For example, how would I instruct nilearn to display the slice depicted by the coordinates -3, -5, 30 in FSLeyes?
