### ISSUE TITLE
Finding Optimal Number of Components using dict_learning as well as canICA

### ISSUE THREAD

**Issue by nilover** [nilearn/nilearn#1744]
Dear All,
Thanks a lot for helping in Voxel based Morphometry using dictionary learning as well as using canICA.
Regarding selecting the optimal number of components, we can select the log (the number of data points). So the number of data points would be the total number of data points right?

log(x=60 * y=72 * z=60 * n=600) = 18.8 ~19  so
n_components = 19 ??
[here 600 is the number of subjects]

Thanks a lot.

**Comment by bthirion** [comment]
There's no good number. You just need to pick one, reasonable in view of the literature and of the data. People typically use between 20 and 70...  (assuming a much larger number of images).

**Comment by nilover** [comment]
Many thanks @bthirion. Sure we can choose the expected number of components based on the literature review as well as from the number of available images. However is there any way to create "elbow plot" or any way to measure variance of each component in canICA and dict_ learning algorithm?

**Comment by nilover** [comment]
Thanks a lot @bthirion. Yes absolutely, as you advised the selection of number of components should be always based on literature survey and number of available images. 
Thank again for indicating about the score function. I just would like to check about the rough indication of expected number of components.

I have tried the score function for checked the explained variance of each component imgs but the output is 0.0. Now I am really not sure if I am using the correct syntax.

> "estimator.score(components_imgs, confounds=None)" 

Score function mentioned in the attributes and it should be used by DecompositionEstimator derived classes.

> score(imgs, confounds=None)
> Score function based on explained variance on imgs.
> 
> Should only be used by DecompositionEstimator derived classes

So the output of "estimator.score(components_imgs, confounds=None) " is 0.0

Thanks a lot again

**Comment by nilover** [comment]
Thanks a lot @bthirion for the idea of using score function to get a rough idea about number of components. However I could find how the score was calculated using estimated variance per component. Is it cumulative? Because in my case, the variation in the score value is constant (1.0) after 50 components ( k =100), so that means 50 could be rough indication of the expected number of components from the data? I was also looking for score function (source code) to check how it is calculating score of explained variance for each components, but could not find it yet.

Thanks a lot again.

**Comment by bthirion** [comment]
Indeed, the `score()` methods seems brken. Sorry for that. I'll open an issue.

**Comment by nilover** [comment]
Okay thanks a lot @bthirion. I will wait for it.

**Comment by KamalakerDadi** [comment]
Please note that this snippet has 100 components. What is broken ```score``` for all components or ```per_component``` score ?

You cannot see score per component because the argument ```per_component``` is not exposed to user at the moment. So, this needs to be open ?

I am asking because I want to fix this for next release. I am not clear on this aspect.

```python
from nilearn import datasets
adhd = datasets.fetch_adhd(n_subjects=20)

from nilearn.decomposition import DictLearning
dictlearn = DictLearning(n_components=100, memory='nilearn_cache')
dictlearn.fit(adhd.func)

masker = dictlearn.masker_
data = np.concatenate(masker.transform(adhd.func))
scores = dictlearn._raw_score(data, per_component=True)
plt.plot(scores, '-o')
plt.title('Explained variance for 100 components')
```
![ev](https://user-images.githubusercontent.com/11410385/46015052-8f51ca00-c0d1-11e8-9646-12fceea9e278.png)

**Comment by nilover** [comment]
Hi @KamalakerDadi 

Many thanks for your reply.

actually I have to calculate score for each component by doing this

`` 
![screen shot 2018-09-25 at 15 28 44](https://user-images.githubusercontent.com/42041244/46017658-4cdfbb80-c0d8-11e8-977e-6951760d8f1f.png)
![screen shot 2018-09-25 at 15 23 48](https://user-images.githubusercontent.com/42041244/46017675-5c5f0480-c0d8-11e8-9015-20b429425631.png)

for i, cur_img in enumerate(iter_img(components_img)):
     
     print(i)
      
     score2 = estimator.score(cur_img, 
                             confounds=None)
      
     exp_var_score2.append(score2)``

**Comment by nilover** [comment]
> Please note that this snippet has 100 components. What is broken `score` for all components or `per_component` score ?
> 
> You cannot see score per component because the argument `per_component` is not exposed to user at the moment. So, this needs to be open ?
> 
> I am asking because I want to fix this for next release. I am not clear on this aspect.
> 
> ```python
> from nilearn import datasets
> adhd = datasets.fetch_adhd(n_subjects=20)
> 
> from nilearn.decomposition import DictLearning
> dictlearn = DictLearning(n_components=100, memory='nilearn_cache')
> dictlearn.fit(adhd.func)
> 
> masker = dictlearn.masker_
> data = np.concatenate(masker.transform(adhd.func))
> scores = dictlearn._raw_score(data, per_component=True)
> plt.plot(scores, '-o')
> plt.title('Explained variance for 100 components')
> ```
> 
> ![ev](https://user-images.githubusercontent.com/11410385/46015052-8f51ca00-c0d1-11e8-9646-12fceea9e278.png)

Hi @KamalakerDadi, many thanks for "dictlearn._raw_score" score approach, however can I also use this function for the complete append components_img ? I have tried but it did not work. Please let me know about it, then I won't have to use estimator.score function. Again I am sorry for the naive question. Many thank to you as well @bthirion for the tremendous help and guide.

**Comment by nilover** [comment]
Dear All,

Finally I managed to use "dictlearn._raw_score" to compute the explained variance per components. Again thanks a lot to @KamalakerDadi. However I am using this dictionary learning approach with structural MRI images (not functional MRIs) (n=600 subjects) and trying to find different components. In that sceniario, I have tuned parameters in dictionary learning algorithm for structural MRI images.

Parmeters:
{'alpha': 10, ## default value for alpha
 'batch_size': 20,
 'detrend': True,
 'dict_init': None,
 'high_pass': None,
 'low_pass': None,
 'mask': None,
 'mask_args': None,
 'mask_strategy': 'epi',
 'memory': Memory(cachedir='nilearn_cache/joblib'),
 'memory_level': 2,
 'method': 'cd',
 'n_components': 40,
 'n_epochs': 1,
 'n_jobs': 1,
 'random_state': 0,
 'reduction_ratio': 'auto',
 'smoothing_fwhm': 0,
 'standardize': True,
 't_r': None,
 'target_affine': None,
 'target_shape': None,
 'verbose': 1}
Are these parameters okay? or I might also need to switch off the "detrend" and "standardize" parameters?

Thanks a lot again.

**Comment by KamalakerDadi** [comment]
>Are these parameters okay? or I might also need to switch off the "detrend" and "standardize" parameters?

@nilover Parameters looks good to me. But, I must admit that I haven't worked much on sMRI using Dictionary Learning. I would check visually the dictionary maps before going further. I would also suggest to look at the literature if any.

**Comment by bthirion** [comment]
Hi, I'm a bit afraid of `mask_strategy='epi'`, which was certainly not designed for structural MRI. i would take `mask_strategy='background'` or even use an MNI gray matter mask.

**Comment by nilover** [comment]
> Hi, I'm a bit afraid of `mask_strategy='epi'`, which was certainly not designed for structural MRI. i would take `mask_strategy='background'` or even use an MNI gray matter mask.
Thanks a lot for the reply. Okay great then I would use 'background'.

**Comment by nilover** [comment]
> > Are these parameters okay? or I might also need to switch off the "detrend" and "standardize" parameters?
> 
> @nilover Parameters looks good to me. But, I must admit that I haven't worked much on sMRI using Dictionary Learning. I would check visually the dictionary maps before going further. I would also suggest to look at the literature if any.

Thanks a lot @KamalakerDadi. I will also check literature. It looks okay after the test run. However I am facing a bit of difficulty to view the score code of estimator._raw_score. I tired with "inspect" but I could not view the complete score code for calculating explained variance.

**Comment by nilover** [comment]
Hi @KamalakerDadi  and @bthirion I have finally found the source code for explained variance per components.

`def explained_variance(X, components, per_component=True):
    """Score function based on explained variance

        Parameters
        ----------
        data: ndarray,
            Holds single subject data to be tested against components

        per_component: boolean,
            Specify whether the explained variance ratio is desired for each
            map or for the global set of components_

        Returns
        -------
        score: ndarray,
            Holds the score for each subjects. score is two dimensional if
            per_component = True
        """
    full_var = np.var(X)
    n_components = components.shape[0]
    S = np.sqrt(np.sum(components ** 2, axis=1))
    S[S == 0] = 1
    components = components / S[:, np.newaxis]
    projected_data = components.dot(X.T)
    if per_component:
        res_var = np.zeros(n_components)
        for i in range(n_components):
            res = X - np.outer(projected_data[i],
                               components[i])
            res_var[i] = np.var(res)
        **return np.maximum(0., 1. - res_var / full_var)**
    else:
        lr = LinearRegression(fit_intercept=True)
        lr.fit(components.T, X.T)
        res_var = X - lr.coef_.dot(components)
        res_var **= 2
        res_var = np.sum(res_var)
        return np.maximum(0., 1. - res_var / full_var)`



data= np.concatenate(masker.transform(func_filenames))
scores= estimator._raw_score(data,per_component=True)


So in my case, the explained variance for each component is very low (0.3%) and I have altogether 40 components. So can I sum the explained variance for each component? In my case, it is 
np.sum(scores)
**0.1179496310922681**
**11%**
Is it okay or expected total expected variance? 
I hope I am not doing anything wrong. I am really sorry for asking so naive questions.

**Comment by KamalakerDadi** [comment]
>I hope I am not doing anything wrong. I am really sorry for asking so naive questions.

I don't think there is something wrong here. Are these scores explained on structural MRI ? But then I am not if this is the expected total variance on sMRI.

Do you think you can open a PR to close this issue #1757. The things which I see missing is

-  to expose ```per_component``` parameter in ```score``` , in order to not to use ```_raw_score```.
- adding a small section in existing example comparing the explained variance ```score``` on components between ICA and Dictionary Learning. 

The existing example, I have in mind is http://nilearn.github.io/auto_examples/03_connectivity/plot_compare_resting_state_decomposition.html#sphx-glr-auto-examples-03-connectivity-plot-compare-resting-state-decomposition-py

**Comment by nilover** [comment]
> I don't think there is something wrong here. Are these scores explained on structural MRI? But then I am not if this is the expected total variance on sMRI.
Okay. Yes I am working with structural MRI images (n_subjects=563)

> Do you think you can open a PR to close this issue #1757. The things which I see missing is
to expose per_component parameter in "score", in order to not to use _raw_score.
Done.
Hoever, I tried again with the existing example (as you recommended) but "score" function is not working with "per_component=True"
`tmp_score = estimator.score(components_imgs,per_component=True)
Traceback (most recent call last):

  File "<ipython-input-251-134cec1353ce>", line 1, in <module>
    **tmp_score = estimator.score(components_imgs,per_component=True)**

TypeError: score() got an unexpected keyword argument 'per_component'`

I hope my syntax is correct?? Did I use the "per_component" paramerter in a correct way? components_imgs is a list object
`components_imgs
Out[278]: [<nibabel.nifti1.Nifti1Image at 0x1c1178d850>]`

`type(components_imgs)
Out[279]: list`

I have also checked the documentation for calling the score function. Again apologies in advance if you found any wrong in my steps.


"
score(imgs, confounds=None)
Score function based on explained variance on imgs.

Should only be used by DecompositionEstimator derived class"


`
Parameters: | imgs: iterable of Niimg-like objectsSee http://nilearn.github.io/manipulating_images/input_output.html Data to be scoredconfounds: CSV file path or 2D matrixThis parameter is passed to nilearn.signal.clean. Please see the related documentation for details
-- | --
score: float,Holds the score for each subjects. Score is two dimensional if per_component is True. First dimension is squeezed if the number of subjects is one

Parameters: | imgs: iterable of Niimg-like objectsSee http://nilearn.github.io/manipulating_images/input_output.html Data to be scoredconfounds: CSV file path or 2D matrixThis parameter is passed to nilearn.signal.clean. Please see the related documentation for details
-- | --
score: float,Holds the score for each subjects. Score is two dimensional if per_component is True. First dimension is squeezed if the number of subjects is one

`
"per_component not working" issue also happened with me before and that's why after your suggestion I tried with "_raw_score" function. 

Sorry again for so much bothering about the explained variance topic.

Many thanks in advance.

**Comment by nilover** [comment]
> Do you think you can open a PR to close this issue #1757. The things which I see missing is
>
Sorry actually the PR is disabled for me, so I could not close it.

**Comment by nilover** [comment]
Hi @KamalakerDadi 
I am adding a small section in existing example (which you have mentioned in the previous reply) investigating the explained variance score on components (n=40) using only Dictionary Learning.
`score =[]
exp_var_score=[]
per_component = True

from nilearn.plotting import plot_prob_atlas

plot_prob_atlas(components_img, title='All ICA components using dict learning ')

from nilearn.image import iter_img
from nilearn.plotting import plot_stat_map, show

for i, cur_img in enumerate(iter_img(components_img)):
    
     plot_stat_map(cur_img, display_mode="z", title="IC %d" % i,
                  cut_coords=1, colorbar=True)
     if per_component:
         score = estimator.score(cur_img)
         print(score)
         exp_var_score.append(score)
         cur_img.to_filename('test_%02i.nii' % i)

show()
    

plt.plot(exp_var_score,'-o')
plt.title('Explained variance for: N=%n_components components')
plt.xlabel('Number of Components')
plt.ylabel('Explained Variance value per components')
plt.grid(True)
plt.show()       `

I am also including the explained variance plot which has 0.0 for all components

![screen shot 2018-11-26 at 15 51 10](https://user-images.githubusercontent.com/42041244/49030279-3670e180-f1a7-11e8-9205-f9c985165429.png)

**Comment by KamalakerDadi** [comment]
Seems like score is broken but not _raw_score. We need to fix it. @nilover thanks for the assessment.

**Comment by nilover** [comment]
Thanks @KamalakerDadi. So the _raw_score and score values would be comparable then? I still did not get why using _raw_score function the variance value were so low?

**Comment by bthirion** [comment]
@nilover do you want to get into the code to investigate the reason why `explained_variance` is broken ?
Best,
B

**Comment by KamalakerDadi** [comment]
@bthirion  
The code uses ```LinearRegression``` when variance is asked to explain based on all components.
```python
lr = LinearRegression(fit_intercept=True)
lr.fit(components.T, X.T)
res_var = X - lr.coef_.dot(components)
res_var **= 2
res_var = np.sum(res_var)
return np.maximum(0., 1. - res_var / full_var)
```

From what I checked with adhd 20 subjects with 10 components. The value for ```res_var=191449763.4724569```, ```full_var=0.9987454``` and  ```1 - res_var / full_var``` is negative. That is why it is returned as 0.

Do you have any suggestions for improvements of this code ?

**Comment by bthirion** [comment]
In that case, it seems that `res_var` should be scaled (actually, there is a confusion on the semantics of variance: technically, the computed `res_var` is a 'residual sum of squares', not a variance).
 
The simplest fix is to replace `full_var` by `np.sum(X ** 2)`: it should work correctly.
Does it make sense ?

**Comment by nilover** [comment]
@bthirion @KamalakerDadi 
Thanks a lot for fixing the score, I will try it soon. However, I have also created a Matlab function which will compute explained variance per component.
However, now I have noticed some more points and would like to understand it.
1. I have compared the dictionary learning algorithm with CanICA, however, I have noticed that CanICA is producing the same number of components which is provided by the user but dictionary learning is producing very less number of components compared to CanICA. Is it because of thresholding and creating more noise-free component than CanICA?

2. Now I have to create a stability matrix based on a different range of numbers of components, which could provide the information that n_componsts = 60 is the most stable compared to all other numbers of component solution. I know (we have already discussed it before, however, maybe I will have to implement by myself), I was wondering about the parameters "n_init" as well as "random_state", what would be the utility of the parameters in the current algorithm so if n_init =100 then we are running the algorithm for 100 times with random sampling? maybe I could use these two parameters in terms of implementing the stability matrix, which could be comparable with ICASSO stability matrix

>  [ (Estimate stability index (Iq)- Icasso returns stability (quality) index (Iq) for each estimate-cluster. This gives a rank for the corresponding ICA estimate. In the ideal case of m one-dimensional independent components, the estimates are concentrated in m compact and close-to-orthogonal clusters. In this case, the index to all estimate-clusters is (very close) to one. The value drops when the clusters grow wider and mix up]

**Comment by bthirion** [comment]
> * 
> 
> * Now I have to create a stability matrix based on a different range of numbers of components, which could provide the information that n_componsts = 60 is the most stable compared to all other numbers of component solution. I know (we have already discussed it before, however, maybe I will have to implement by myself), I was wondering about the parameters "n_init" as well as "random_state", what would be the utility of the parameters in the current algorithm so if n_init =100 then we are running the algorithm for 100 times with random sampling? maybe I could use these two parameters in terms of implementing the stability matrix, which could be comparable with ICASSO stability matrix

This makes sense. using random initialization is a way to sample the state of solutions. using n_init >1 typically yields better solutions, hence it avoids poor local maxima of the criterion. 
As a  word of skepticism, don't expect stability to yield a clear optimum. 
Picking the "right number of components" for ICA is known to be hard, in the absence of a clear validation criterion. I'd rather use a fixed number, e.g. 60 or decide about this number by using a final classification criterion, using nested cross-validation --- if you have a lot of data.

**Comment by KamalakerDadi** [comment]
This issue seems more like a discussion. @nilover can you close this ?

**Comment by KamalakerDadi** [comment]
Closing with #2577
