### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by dPys** [nilearn/nilearn#1748]
Thanks @GaelVaroquaux and whomever else for creating find_parcellation_cut_coords and find_probabilistic_atlas_cut_coords in nilearn.plotting. Much cleaner and less memory hungry than the functions that I had been relying on previously...

Cheers,
Derek;

**Comment by GaelVaroquaux** [comment]
I believe that it's mostly @amadeuskanaan  and @KamalakerDadi  that you need to thank. But it's really nice to hear such kind of feedback!

Thank you very much!

Gaël

(PS: closing to avoid clutter in the tracker, but the discussion will stay open here).
