### ISSUE TITLE
NiftiMasker with target_affine throws exception.

### ISSUE THREAD

**Issue by cl445** [nilearn/nilearn#1751]
I am using the NifitiMasker in a sklearn pipeline. Everythings works fine until i try to reshape the images:

`nifti_masker = NiftiMasker(target_affine=np.eye(3)*3)`

The error i got was:

`File "/anaconda3/envs/toolbox/lib/python3.6/site-packages/nilearn/masking.py", line 62, in _load_mask_img
    % values)
ValueError: Given mask is not made of 2 values: [-0.0000000e+00  1.4012985e-45  2.8025969e-45 ...  5.1444152e-15
  5.3116801e-15  1.0000000e+00]. Cannot interpret as true or false`

I unsing nilearn version 0.4.2 .

**Comment by bthirion** [comment]
You probably want ro use interpolation='nearest' when resampling to keep only int values.

**Comment by cl445** [comment]
Thanks for your reply but I don't think thats the problem. The masking expects a mask out of two values so that it can stencil the region that you want to use. But the mask it gets is out of multiple values.  If I would use interpolation='nearest' the multiple values would be integers instead of float but the problem still remains. 
The problem could have two causes in my eyes:

1. The function gets totaly wrong data or
2.  There is a preprocessing step like thresholding missing thad reduce the date to two values.

But at least this is an unexpected behavior.

**Comment by KamalakerDadi** [comment]
>The masking expects a mask out of two values so that it can stencil the region that you want to use. >But the mask it gets is out of multiple values.

If mask is extracted by itself with multiple values ? Then we need to look at what is causing this behavior. Can you give us a minimal script with data if you wish to like to know what's happening and propose possible fix/solution for this ?

Just want to make sure that if mask is given explicitly, then mask should have [0, 1].

Thanks

**Comment by cl445** [comment]
Sure! Here is a py.test that fails: 
```
import numpy as np
from nilearn import datasets
from nilearn.input_data import NiftiMasker
import pytest

def test_reshape():
    mri_images = datasets.fetch_neurovault_motor_task()['images']

    nifti_masker = NiftiMasker()
    nifti_masker.target_affine = np.eye(3) * 5

    nifti_masker.fit(mri_images)
    try:
       nifti_masker.transform(mri_images)
    except ValueError:
        pytest.fail("ValueError accours")
```

**Comment by bthirion** [comment]
Sorry I forgot to track the error. There is indeed a bug in the library: when the mask data are interpolated, the mask should be kept binary. Thx for posting.
Note that a workaround is to process the mask first, making sure it is binary, then mask the data. This is a bit inelegant I agree.

**Comment by KamalakerDadi** [comment]
I would do pre (after mask extraction) and post resample sanity checks on the number of unique values in mask image. If they are not same then I would impose ```math_img``` to threshold. 

That this sounds good ?

**Comment by bthirion** [comment]
Why not thresholding directly then ? The cost is so much smaller than that of resampling.

**Comment by KamalakerDadi** [comment]
>Why not thresholding directly then ? 

Without sanity checks ?

**Comment by bthirion** [comment]
Maybe I'm missing something, but if the mask image has to be binary  ---is it really the case ?--- I don't seen any issue with binarizing systematically.

**Comment by KamalakerDadi** [comment]
I made a PR. May be we can iterate on that #1805
