### ISSUE TITLE
Switch from nosetests to pytest

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1752]
Should be simple, pytest can run most aspects of nosetests. I did a pilot in https://github.com/neurospin/pypreprocess and it worked fine (undid it due to other reasons). We replace the command nosetests with pytest and that's pretty much it.

**Comment by bthirion** [comment]
Nosetests is no longer supported if I'm not mistaken.

**Comment by kchawla-pi** [comment]
The trigger for the change is nosetests is no longer being maintained. 
nose2 is not looking to introduce new features anytime soon. pytests are the current flavor. They are popular, so it will be easier to find resources to help with them. I expect they will get feature improvements and bug fixes faster as well.
pytests can run nose and unittests without any change.

I have written a few simple tests using unittest and more complex ones using pytest Haven't used nose before.
Between unittest and pytest, pytest allows writing a lot more sophisticated tests with a lot less boilerplate.

**Comment by jeromedockes** [comment]
here is the discussion where scikit-learn decided to make the same change:

https://github.com/scikit-learn/scikit-learn/issues/7319

**Comment by kchawla-pi** [comment]
Fixed in #2076
