### ISSUE TITLE
add Seealsos: refs to NiftiMasker

### ISSUE THREAD

**Issue by agramfort** [nilearn/nilearn#1753]
I would vote to put see also refs to NiftiMasker

in regions functions eg in:

https://nilearn.github.io/modules/generated/nilearn.regions.img_to_signals_labels.html#nilearn.regions.img_to_signals_labels

**Comment by GaelVaroquaux** [comment]
+1: the NiftiLabelsMasker needs to be mentioned in the see also of this
function.

In general, the maskers should be mentioned more as "see also"s in this
module, as people find this module naturally instead of the maskers.

Thanks @agramfort for the issue!
