### ISSUE TITLE
Add see alsos: from plotting.plot_surf* to surface.vol_to_surf

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1755]
We should add surface.vol_to_surf in the seealso of the plotting.plot_surf functions.

**Comment by soojcho** [comment]
First time contributing here, would like to help if I could be given access to make edits to the [page](https://nilearn.github.io/modules/generated/nilearn.plotting.plot_surf.html). Couldn't find instructions to gain an edit access in the Contribution documentations.

**Comment by bthirion** [comment]
Hi, 
Thx for volunteering. 
You need to make edit through the Github repository 
Please see: https://nilearn.github.io/contributing.html 
And then issue pull requests with the fix that you propose. 
Best, 

Bertrand

**Comment by kchawla-pi** [comment]
Thanks for your help @soojcho 
This document will explain how to submit a contribution in detail. 
https://gist.github.com/Chaser324/ce0505fbed06b947d962
If you have difficulty with anything, it would make me very happy to be of assistance, so let me know.

**Comment by psadil** [comment]
Hoping to close this as part of dev days 2021! It'd be my first contribution.

I think I know what to do. But it's going to take a bit while I try out the steps.

**Comment by bthirion** [comment]
Thx ! Let us know if you need help.
