### ISSUE TITLE
Improve error message of vol_to_surf when input is wrong

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1756]
The following code inputs the wrong gitfi to vol_to_surf (the one with the data, and not the mesh):
<pre>
from nilearn import datasets
data = datasets.fetch_neurovault_motor_task()
image = data.images[0]

surf_mesh = datasets.fetch_surf_fsaverage()
from nilearn import surface
surf_data = surface.vol_to_surf(image, surf_mesh.sulc_left)
</pre>

It raises the following error, which is unhelpful, as it does not really tell me what's wrong in simple terms, or how to fix it:
<pre>
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/home/varoquau/dev/nilearn/nilearn/surface/surface.py in _gifti_img_to_mesh(gifti_img)
    619             coords = gifti_img.get_arrays_from_intent(
--> 620                 nibabel.nifti1.intent_codes['NIFTI_INTENT_POINTSET'])[0].data
    621         except IndexError:

IndexError: list index out of range

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/home/varoquau/test.py in <module>()
      5 surf_mesh = datasets.fetch_surf_fsaverage()
      6 from nilearn import surface
----> 7 surf_data = surface.vol_to_surf(image, surf_mesh.sulc_left)
      8 

/home/varoquau/dev/nilearn/nilearn/surface/surface.py in vol_to_surf(img, surf_mesh, radius, interpolation, kind, n_samples, mask_img)
    505     img = _utils.check_niimg(img, atleast_4d=True)
    506     frames = np.rollaxis(img.get_data(), -1)
--> 507     mesh = load_surf_mesh(surf_mesh)
    508     sampling = sampling_schemes[interpolation]
    509     texture = sampling(

/home/varoquau/dev/nilearn/nilearn/surface/surface.py in load_surf_mesh(surf_mesh)
    679         elif surf_mesh.endswith('.gii.gz'):
    680             gifti_img = _load_surf_files_gifti_gzip(surf_mesh)
--> 681             coords, faces = _gifti_img_to_mesh(gifti_img)
    682         else:
    683             raise ValueError(('The input type is not recognized. %r was given '

/home/varoquau/dev/nilearn/nilearn/surface/surface.py in _gifti_img_to_mesh(gifti_img)
    620                 nibabel.nifti1.intent_codes['NIFTI_INTENT_POINTSET'])[0].data
    621         except IndexError:
--> 622             raise ValueError('Gifti file needs to contain a data array '
    623                              'with intent NIFTI_INTENT_POINTSET')
    624         try:

ValueError: Gifti file needs to contain a data array with intent NIFTI_INTENT_POINTSET
</pre>

**Comment by himanshupathak21061998** [comment]
I tried this code 
`from nilearn import datasets
data = datasets.fetch_neurovault_motor_task()
image = data.images[0]

surf_mesh = datasets.fetch_surf_fsaverage()
from nilearn import surface
surf_data = surface.vol_to_surf(image, surf_mesh.sulc_left)
`
But this code is giving this error not as defined above why
 File "<ipython-input-4-fbcf22d42746>", line 2, in <module>
    data = datasets.fetch_neurovault_motor_task()

AttributeError: module 'nilearn.datasets' has no attribute 'fetch_neurovault_motor_task'

**Comment by KamalakerDadi** [comment]
@himanshupathak21061998 Can you try installing upgrading Nilearn using "pip install nilearn==0.5.0a0"

 Full details about new additions can be tracked here: https://nilearn.github.io/whats_new.html

**Comment by himanshupathak21061998** [comment]
`surf_data = surface.vol_to_surf(image, surf_mesh.sulc_left)`
The error is because of surf_mesh.sulc_left argument because it contains the data of sulcal depth which is not needed here . It requires the surface mesh data only  to calculate the vertex of mesh . Am I right or wrong ?

**Comment by KamalakerDadi** [comment]
Closing with #1834
