### ISSUE TITLE
skull stripping of 4d fmri data

### ISSUE THREAD

**Issue by AzmatUllahKhan** [nilearn/nilearn#1759]
Can we do brain extraction of 4d fmri data in nilearn?
if not, kindly suggest me a good tool for this.

**Comment by bthirion** [comment]
The function for mask estimation ('compute_mask') does it on 4D images 
--actually taking the mean along the temporal dimension.
Note that this is brain mask extraction and not skull stripping stricto 
sensu.
Best,

**Comment by AzmatUllahKhan** [comment]
Hi @bthirion 
it is giving the error below

Brain = masking.compute_mask("/media/azmat/Data/processed/fmriprep/sub-1/ses-1/func/sub-1_ses-1_task-rest_acq-TR2500_bold_space-MNI152NLin2009cAsym_preproc.nii.gz")

AttributeError: module 'nilearn.masking' has no attribute 'compute_mask'

**Comment by KamalakerDadi** [comment]
Please have a look at this brief guide about [masking](https://nilearn.github.io/manipulating_images/manipulating_images.html).
In particular, section **5.2.4. Computing and applying spatial masks**. It tells you masking options available in Nilearn.

From what I have seen, you have BOLD-fMRI images you should be using ```compute_epi_mask```

**Comment by KamalakerDadi** [comment]
@AzmatUllahKhan did you made it work to close this issue ?

**Comment by AzmatUllahKhan** [comment]
Yes it worked, thankyou.
