### ISSUE TITLE
[ENH] Contrasts testing

### ISSUE THREAD

**Issue by VirgileFritsch** [nilearn/nilearn#176]
The API of mass univariate models should make it possible to specify contrasts to be tested. The actual code can be hacked (modification of the input design) to obtain the same results but this is not convenient/efficient.
However, including a contrast in the current code would result at least in `n_perm` supplementary calls to the `np.dot` function, which is actually the bottleneck of the code. I am afraid this would considerably slow the code down. Regarding that the main use-case remains fitting and testing several tested variates independently, I wonder if allowing the user to provide contrasts is a good idea after all.

Contrasts testing would also require to put back the F-test (while the t-test should remain available since it can perform one-sided tests). This would increase the code size and make it more difficult to maintain.

I think this is a tricky contribution that needs to be discussed carefully before any implementation attempt.

**Comment by AlexandreAbraham** [comment]
What do we do about this one?

**Comment by bthirion** [comment]
My understanding is that this part of the codebase is a bit peripheral.  With the forthcoming development of a (say) nistats package, we probably want to avoid developing the contrasts algebra within nilearn. I would thus close it.

**Comment by thomasbazeille** [comment]
I think this old nilearn issue can be closed thanks to nistats merge
