### ISSUE TITLE
 Convert non-tsv files to tsv during dataset fetch

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1760]
From https://github.com/nistats/nistats/issues/234 . Also, https://github.com/nistats/nistats/issues/223#issuecomment-423317417

As with NiStats, we need to write a function called by the dataset fetchers whenever a dataset is accessed where the events are written not as csv r tsv but with a different delimiter character, such as spaces.

**Comment by KamalakerDadi** [comment]
Just curious have you tried this on csv or tsv. Does this works ?

```from nilearn._utils.numpy_conversions import csv_to_array```

**Comment by kchawla-pi** [comment]
No. Thanks, will check it out.

**Comment by bthirion** [comment]
No fetcher currently returns csv.
