### ISSUE TITLE
SciPy absent as one of the installation requirements

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1762]
In the Nilearn installation documentation, Scipy is not mentioned as one of the dependencies that must be installed. If we currently follow the installation instructions as they are and then try to import Nilearn, we get 
```
>> ImportError: No module named 'scipy'. Module "scipy" could not be found. See http://nilearn.github.io/introduction.html#installation for installation information.
```

**Comment by kchawla-pi** [comment]
We should also add it in the `requires` field of the package setup config files.

**Comment by kchawla-pi** [comment]
Checking out the version.py file:

```
REQUIRED_MODULE_METADATA = (
    ('numpy', {
        'min_version': '1.11',
        'required_at_installation': True,
        'install_info': _NILEARN_INSTALL_MSG}),
    ('scipy', {
        'min_version': '0.17',
        'required_at_installation': True,
        'install_info': _NILEARN_INSTALL_MSG}),
    ('sklearn', {
        'min_version': '0.18',
        'required_at_installation': True,
        'install_info': _NILEARN_INSTALL_MSG}),
    ('nibabel', {
        'min_version': '2.0.2',
        'required_at_installation': False}))
```
`scipy` is listed as `required: True` but not in the documentation and  is not installed automatically by `pip`. 
`sklearn` is listed as `required: True` and in the documentation and  is (presumably) not installed automatically by `pip`. 
`nibabel` is listed as `required: False` but it is in the documentation and  is (presumably) not installed automatically by `pip`. 

I would like more clarity about hwat's going on here. Would someone explain?
Additionally, there doesn't seem to be any dependency management at all? Why is that?
Why not have a requirements.txt file for pip?

**Comment by KamalakerDadi** [comment]
Yeah sure SciPy is not listed. It is  a good idea to list this documentation.

My user experience is that, by looking at the documentation I would first try to install scikit-learn. Scikit-learn has the dependency of SciPy and NumPy. I don't see how I can by-pass this.

**Comment by kchawla-pi** [comment]
I installed scikit-learn first, yet got the script import error.
We can bypass this by creating a requirements.txt file which will list all
appropriate dependencies. When pip sees that this file is present,it'll
first install the packages and the listed version in the listed order, and
then finally install nilearn.

On Sep 25, 2018 14:30, "KamalakerDadi" <notifications@github.com> wrote:

Yeah sure SciPy is not listed. It is a good idea to list this documentation.

My user experience is that, by looking at the documentation I would first
try to install scikit-learn. Scikit-learn has the dependency of SciPy and
NumPy. I don't see how I can by-pass this.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/nilearn/nilearn/issues/1762#issuecomment-424323489>,
or mute
the thread

**Comment by thomasbazeille** [comment]
Can be closed
