### ISSUE TITLE
build confounding csv 

### ISSUE THREAD

**Issue by grjd** [nilearn/nilearn#1764]
I am performing resting state analysis and I am looking at how to build a decofounder csv file. 
Is there an easy way about how to o obtain the mean signal per tissues?
I have used FSL to segment the T1 image and perform motion correction. 
Is there a function I can call to make a csv that I can pass to for example the clean function? Is the segmented T1 good to confound an fmri image?
 

> nilearn.signal.clean(signals, sessions=None, detrend=True, standardize=True, confounds=**csv**??, ...)

**Comment by KamalakerDadi** [comment]
You can take some help from this gist: https://gist.github.com/KamalakerDadi/af531d09eb47eb98cd82272cda6704c0

You can use segmented T1 images as a "mask" to extract signals on fmri images.

Hope this helps.

**Comment by grjd** [comment]
Thanks I used your code, but I got the error bellow, I dont see why.
The mask_img is a <class 'nibabel.nifti1.Nifti1Image'> with only 0's and 1's (data = mask_img.get_data(caching='unchanged', data.max()=! and data.min()=0)

> high_variance = high_variance_confounds(img, mask_img=mask_img, n_confounds=n_confounds)
> ** ValueError: Given mask is not made of 2 values: [0.0000000e+00 2.0861626e-06 2.2242389e-06 ... 9.9999988e-01 9.9999994e-01
>  1.0000000e+00]. Cannot interpret as true or false

**Comment by bthirion** [comment]
```
from nilearn.mimage import math_img
mask_img = math_img('img >.5', img=mask_img)
```

**Comment by grjd** [comment]
thanks.
Now I get this error bellow. I wonder if it is about the dimensions of img and img_mask:
img.shape (79, 95, 79, 120)  
img.affine.shape (4,4)
mask_img.shape (91, 109, 91)  

> 
> high_variance = high_variance_confounds(img, mask_img=mask_img, n_confounds=n_confounds)
> *** ValueError: Mask affine:
> [[  -2.    0.    0.   90.]
>  [   0.    2.    0. -126.]
>  [   0.    0.    2.  -72.]
>  [   0.    0.    0.    1.]]
>  is different from img affine:
> [[  -2.    0.    0.   78.]
>  [   0.    2.    0. -112.]
>  [   0.    0.    2.  -70.]
>  [   0.    0.    0.    1.]]

**Comment by bthirion** [comment]
The you can use nilear.image.resample_to_img
```
from nilearn.mimage import math_img, resample_to_img
mask_img_resampled = math_img('img >.5', img=resample_to_img(mask_img, img))
high_variance = high_variance_confounds(img, mask_img=mask_img_resampled, n_confounds=n_confounds)
```

**Comment by grjd** [comment]
that made it thanks.
