### ISSUE TITLE
Better installation using pip requirements file

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1770]
Currently all the necessary dependencies for Nilearn need to be manually installed, by following the documentation. We can streamline the experience for new users by employing a requirements file.

SO instead of having to manually install scipy, then scikit-learn then atplotlib etc, and then installing nilearn, a user only has to do pip install nilearn and be done.

**Comment by NicolasGensollen** [comment]
Closing this since it has been already addressed.
