### ISSUE TITLE
Using argument alpha has no effect using in plot_prob_atlas with continous view_type

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#1772]
alpha is not called at display.add_overlay in ```plot_prob_atlas``` function. Inputs from @alpinho 

Code to reproduce:

```python
from nilearn import plotting, datasets

smith = datasets.fetch_atlas_smith_2009()
plotting.plot_prob_atlas(smith.rsn20, view_type='continuous', alpha=0.9)
plotting.plot_prob_atlas(smith.rsn20, view_type='continuous', alpha=0.2)
```
It is always the same results no matter the change in ```alpha```.
![alpha_0 2](https://user-images.githubusercontent.com/11410385/46409369-8edeb200-c715-11e8-823c-0da67dea1b26.png)
![alpha_0 9](https://user-images.githubusercontent.com/11410385/46409370-8edeb200-c715-11e8-94f2-ab206882fbc5.png)

Expected to be change the contrast of the colors depending upon alpha:
![alpha_0 3](https://user-images.githubusercontent.com/11410385/46409428-d1a08a00-c715-11e8-8eb0-a6dd0af15eb5.png)

Any objections of not varying ```alpha``` for continuous colors overlay ?

**Comment by bthirion** [comment]
No we should indeed vary  `alpha` according to user requests. Thx for sharing.

**Comment by KamalakerDadi** [comment]
Trying to find a good alpha value by default for both continuous overlays and filled contours.

**alpha: 0.5**
![alpha_0 5_con](https://user-images.githubusercontent.com/11410385/46909982-22955700-cf3c-11e8-80bb-1d866da0ecbe.png)
![alpha_0 5_contours](https://user-images.githubusercontent.com/11410385/46909983-22955700-cf3c-11e8-9a89-44211aeffb6e.png)



**alpha:0.7**
![alpha_0 7_con](https://user-images.githubusercontent.com/11410385/46909987-45c00680-cf3c-11e8-8d60-acaeec688428.png)
![alpha_0 7_contours](https://user-images.githubusercontent.com/11410385/46909988-45c00680-cf3c-11e8-869c-d70116ab5670.png)

**Comment by KamalakerDadi** [comment]
Which value should I prefer as default ?

0.5 or 0.7

**Comment by bthirion** [comment]
Without the outlines, I think that .5 lacks contrast, so I'd for .7 by default.
With the outlines, both are OK.

**Comment by KamalakerDadi** [comment]
For me .7 too and this is default in plot_roi and plot_glass_brain as well. I will open a PR.
