### ISSUE TITLE
fetch_neurovault_ids doesn't retrieve from data directory

### ISSUE THREAD

**Issue by souravsingh** [nilearn/nilearn#1774]
When using `fetch_neurovault_ids`, the function should read the collection from the data directory, if the collection has been downloaded before. In my case, it is collection 1952, which consists of about 6000+ images.

During every run of the function, the data is downloaded from Neurovault without retrieving from the data directory instead. This causes the data to be downloaded during every run, which wastes time for the user.

**Comment by souravsingh** [comment]
A small snippet from the execution of `fetch_neurovault_ids`-

```
Fetching Neurovault images; if you haven't downloaded any Neurovault data before this will take several minutes.
Reading local neurovault data.
No image found on local disk.
Reading server neurovault data.
getting new batch: http://neurovault.org/api/collections/1952
Scroll images from collection 1952: getting new batch: http://neurovault.org/api/collections/1952/images/?limit=100&offset=0
Scroll images from collection 1952: batch size: 100
Downloading file: https://neurovault.org/media/images/1952/task007_face_vs_baseline.nii.gz
Download succeeded, downloaded to: nilearn_data/neurovault/collection_1952/image_32015.nii.gz
Already fetched 1 image
Downloading file: https://neurovault.org/media/images/1952/task007_face_vs_baseline_1.nii.gz
Download succeeded, downloaded to: nilearn_data/neurovault/collection_1952/image_32016.nii.gz
Already fetched 2 images
```

**Comment by souravsingh** [comment]
And here is where my data for collection 1952 is stored- `/home/ssouravsingh12/nilearn_data/neurovault/collection_1952`

**Comment by KamalakerDadi** [comment]
>When using fetch_neurovault_ids, the function should read the collection from the data directory, if the collection has been downloaded before.

Have you tried using ```mode='offline'```

**Comment by souravsingh** [comment]
I tried using it. It shows a message saying no images are available on the disk when the collection is stored in my data directory.

Also, This problem doesn't happen with `fetch_neurovault` when using `mode='offline'`. The function is able to retrieve all images stored in the data directory.

**Comment by jeromedockes** [comment]
thanks for reporting this! can you show the exact call to fetch_neurovault_ids that you made?
for some reasons it seems to look for images in the current working directory rather than your home dir

**Comment by souravsingh** [comment]
@jeromedockes Here is y function call to fetch_neurovault_ids-`data = fetch_neurovault_ids(collection_ids=['1952'])`

This call uses `nilearn_data` directory to store the collection, but doesn't retrieve from the directory again, instead downloading the collection online.

**Comment by KamalakerDadi** [comment]
I first downloaded data as you said there are 6001 images. Then, I used mode='offline' to fetch data. I am able fetch all 6001 images properly. What is missing here ?

By the way, you should specify as int not string ['1952']

**Comment by jeromedockes** [comment]
> By the way, you should specify as int not string ['1952']

good catch @KamalakerDadi  this is the problem: it compares '1952' with ids in the metadata, which are ints, and finds that they are different. i'll open a pr to convert ids passed as strings to ints.

in the meantime, @souravsingh , you can fix your problem by replacing '1952' with 1952

**Comment by souravsingh** [comment]
@KamalakerDadi Thanks for helping! I was able to fix the problem

**Comment by KamalakerDadi** [comment]
For now, I am closing this one. But, there is a similar issue here #1731 if you want to discuss on this.
