### ISSUE TITLE
Plotting functions do not respect matplotlibrc context

### ISSUE THREAD

**Issue by TheChymera** [nilearn/nilearn#1777]
Matplotlibrc provides a [highly parametereized specification for customizing plot appearance](https://matplotlib.org/users/customizing.html). Perhaps one of the most trivial and useful parameters in matplotlibrc is `figure.figsize`, which is a tuple determining the size of the plot.

Sadly, at least `nilearn.plotting.plot_anat` and `nilearn.plotting.plot_img` (though I suspect this affects most related plots) override these settings. This is most probably done by explicitly specifying a `figsize` parameter [for the matplotlib Figure object](https://matplotlib.org/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure) --- which as the page indicates would default to the matplotlibrc context if left empty.

**Comment by GaelVaroquaux** [comment]
The reason behind this is that the optimal figure size depends on the
arguments to the plotting functions (specifically the display_type
argument).

For most users, this is a good behavior. Advanced user can override it by
creating a figure and passing it to the plotting functions as an
argument.

**Comment by TheChymera** [comment]
I could not find the string `display_type` anywhere in the nilearn source.

I'm not sure what you mean by optimal figure size. for interactive plots the optimal figure size depends on the user's monitor, and is handled by the user's default matplotlibrc. For exporting to PNG/PDF the optimal size depends on what exactly the user wants. None of these things are knowable to nilearn.

Looking at other high-level plotting packages, e.g. seaborn, they have made the experience that overriding matplotlibrc by default adds more confusion, makes behaviour inhomogeneous among packages, and goes against the Python “flat is better than nested” design principle.

**Comment by GaelVaroquaux** [comment]
> I could not find the string display_type anywhere in the nilearn source.

Sorry, "display_mode".
