### ISSUE TITLE
plotting.plot_connectome not plotting 

### ISSUE THREAD

**Issue by sento4000** [nilearn/nilearn#1783]
Hi, 

I just started using nilearn to plot graphs, i was trying to plot my connectome using the function plotting.plot_connectome, here is the code:
PRJDIR="/bcbl/home/public/PARK_VFERRER"
import scipy.io as sio
from nilearn import plotting
import nilearn
import pyexcel 
# import matlab workspace
mat_space=sio.loadmat(PRJDIR+"/ConnICA/RC_PCA_33_ICA_33MB3.mat")
RC=mat_space["RC"] # get connectomes 
connectome=RC[0][1][1] # select connectome
Parcels=nilearn.image.load_img(PRJDIR+"/PREPROC/sub-008ParkImaCm/anat/aparc.a2009s+aseg.ANAT.MNI.nii.gz", wildcards=True, dtype=None) # get parcellation atlas
node_coords=plotting.find_parcellation_cut_coords(Parcels, background_label=0, return_label_names=True) #find coordinates for each parcel

# get the parcellations that are actually used for the connectivity matrix
sheet = pyexcel.get_sheet(file_name=PRJDIR+"/Scripts/ConnICA_scripts/GM_SCORT_aparc.xls")
# filter the needed coordinates 
coords_final=[]
node_final=[]
order=[]
for value in sheet.column[0]: # for each parcel in the atlas
	if value in node_coords[1]: # see if it is used in the connectivity matrix
		coords_final.append(node_coords[0][node_coords[1].index(value)]) # save the new used parcel and value
		node_final.append(value)
		order.append(sheet.column[3][sheet.column[0].index(value)])

plotting.plot_connectome(connectome, coords_final, node_color='auto', 
	edge_threshold="10%", output_file=None, display_mode='ortho', figure=None,axes=None, title=None, 
	annotate=True, black_bg=False, alpha=0.7, edge_kwargs=None, node_kwargs=None, colorbar=False)

My code gets executed, but in the end it doesn't plot anything, it gives this messages in the terminal:
/opt/anaconda2/lib/python2.7/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
<nilearn.plotting.displays.OrthoProjector object at 0x2adf9a17dfd0>
Do i have to do something else in order to plot the connectome?
thanks in advance.
Cheers,
Vicente

**Comment by KamalakerDadi** [comment]
Try to add this line at the end of the script
```python
plotting.show()
```

**Comment by sento4000** [comment]
Hi,
thanks for the answer, now the plot is appearing but there is nothing plot in the glassbrain:
![image](https://user-images.githubusercontent.com/38909338/46799280-b1e01600-cd54-11e8-856a-14676b817ec2.png)
Is it a problem with the coordinates? does the atlas needs to be in a specific MNI space?.

Cheers,
Vicente

**Comment by KamalakerDadi** [comment]
>does the atlas needs to be in a specific MNI space?.

Yes it should be in MNI space coordinates.

**Comment by sento4000** [comment]
is there any other reason that can lead to the program no plotting the graph?

**Comment by KamalakerDadi** [comment]
See this guy this may help http://nilearn.github.io/modules/generated/nilearn.image.coord_transform.html. But, I am not completely sure this may solve this problem and there is no other reason.

**Comment by sento4000** [comment]
Hi, thanks for the function. So if i understand i have to get the affine between my Parcel image and datasets.load_mni152_template() and the apply the coord_transform function?

**Comment by sento4000** [comment]
I suppose that computing the affine has to be done externally?

**Comment by KamalakerDadi** [comment]
I am not sure how to construct affine. Have you tried with mni standard template affine. Did it worked ?

**Comment by sento4000** [comment]
The problem is that affine has to be the affine transform between Parcels which is my atlas and the MNI space that nilearn.plotting.plot_connectome uses. Can you give me an image that is in that space so i can compute the affine externally? Once i have done that i can use that affine to get the coordinates.

**Comment by KamalakerDadi** [comment]
http://nilearn.github.io/modules/generated/nilearn.image.coord_transform.html

You can have a look at the doc string. Examples.

**Comment by sento4000** [comment]
One more thing. I would like to know if it is possible to put an actual template rather than a glass brain in the background?

**Comment by GaelVaroquaux** [comment]
> One more thing. I would like to know if it is possible to put an actual
> template rather than a glass brain in the background?

You cannot: it's a glass brain. Template displays are cuts, and not
projections.
