### ISSUE TITLE
Super verbose CI logs

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1784]
The CI logs are brimming with noise, making it a chore to debug a real problem.

Moreover TravisCI has a log length beyond which it terminates the testing and we have started bumping against it.

We should systematically check all the warnings being generated and update the codebase so they are no longer generated.

This should be made a priority, these spurious failures are costing time and enthusiasm.

**Comment by GaelVaroquaux** [comment]
Absolutely. We need to:

* See where warnings call for a fix on our side
* add in the codebase a few well targeted warning suppression code (https://docs.python.org/2/library/warnings.html#temporarily-suppressing-warnings)
