### ISSUE TITLE
Ship compressed versions of the Allen atlases

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1792]
The Allen atlases that we ship are not compressed. As a result, they use a total of 75M on a download (eg circleCI). We should reship them using OSF, after a "gzip -9", this drops the disk usage to 31Mb.

**Comment by GaelVaroquaux** [comment]
@kchawla-pi : do you think that you can tackle this in the near future? It should make our circleCI builds a bit faster and a bit more robust, hence streamlining the release.

**Comment by GaelVaroquaux** [comment]
Thanks!

**Comment by kchawla-pi** [comment]
What do you think, how far along are we towards the release?

**Comment by GaelVaroquaux** [comment]
> What do you think, how far along are we towards the release?

Almost there.

**Comment by kchawla-pi** [comment]
Oh wait, the files inside are .nii files, they are not compressed at all. Nevermind

**Comment by GaelVaroquaux** [comment]
The goal is to ship .nii.gz so that less disk space is used.

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by kchawla-pi** [comment]
@GaelVaroquaux @bthirion 
I have created a project on OSF to store the data in a manner accessible to the fetchers, on the basis of other osf datasets we are using in the fetcher.
Before I proceed, take a look at it and make sure everything is in the clear, legally & scientific etiquette-wise.

**Comment by kchawla-pi** [comment]
Can't seem to find anything about legal rights regarding the data, the paper itself seems open access. Certainly nothing about rehosting the data.

**Comment by kchawla-pi** [comment]
Should I write them an email and clarify?

**Comment by GaelVaroquaux** [comment]
> Should I write them an email and clarify?

I would just go ahead.

**Comment by kchawla-pi** [comment]
I have uploaded the data as a project and made it public, now figuring out the url.

**Comment by kchawla-pi** [comment]
Figured it out. Will require more work than I thought, no worries.

**Comment by kchawla-pi** [comment]
@GaelVaroquaux Review & Discussion nescessary for #1840
