### ISSUE TITLE
Unclosed sockets warning in example

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1807]
When running `examples/02_decoding/plot_haxby_different_estimators.py` I get this warning:

```
/home/kshitij/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.4323.49/helpers/pycharm_matplotlib_backend/backend_interagg.py:107: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 59472), raddr=('127.0.0.1', 43417)>
```

What is it? We should fix this, it looks ugly when running the example.

**Comment by Remi-Gau** [comment]
I don't see this warning when I run this now. We may consider closing this issue.

**Comment by Remi-Gau** [comment]
I am still not seeing this warning: closing for now.
