### ISSUE TITLE
Remove "quick search" from website

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1816]
The "quick search" has reappeared in the sidebar of the website (probably as a result of https://github.com/nilearn/nilearn/pull/1082). It should be removed.

ping @aabadie

**Comment by GaelVaroquaux** [comment]
The reason that I was seeing this was simply that the PR by @aabadie was old, and didn't integrate this change. My bad.

**Comment by kchawla-pi** [comment]
It's back and it's pissed.

**Comment by bthirion** [comment]
Hm... indeed

**Comment by emdupre** [comment]
I can replicate those search results in Chrome but not Firefox. It looks like Chrome is inserting adds at the top of the search. I don't have access to Safari, but I'm curious how widespread this problem is !

**Comment by jeromedockes** [comment]
> I can replicate those search results in Chrome but not Firefox. It looks like Chrome is inserting adds at the top of the search. I don't have access to Safari, but I'm curious how widespread this problem is !

I see adds in Firefox and in Safari (running in a virtualbox) . maybe we can just remove both quick search bars?
