### ISSUE TITLE
2x2 volumetric plot Arrangement

### ISSUE THREAD

**Issue by TheChymera** [nilearn/nilearn#1822]
Sorry for crossposting, but I was unable to get an answer [elsewhere](https://neurostars.org/t/2x2-field-plot-arrangement-from-nilearn/2602).

Is there any way to get the more “traditional” 2x2 plot arrangement (e.g. as seen in SPM, FSL, MRIcroGL, etc.) where the crosshairs of the frontal slice extend right and down into the horizontal slice view?

I appreciate the 3x1 matrix default of nilearn, as it is better packed, but I would also like to be able to use the traditional 2x2 arangement.

This approach has the major drawback that it leaves one cell of the 2x2 plot arrangement empty, but given modern technology that actually turns out to be very useful for a 3D visualizarion. Not least of all the consistent crosshair alignment is also very helpful to better grasp the placement in the brain.

**Comment by GaelVaroquaux** [comment]
No there is not, unfortunately. 

A PR would be most appreciated. The way to do it would be to do a new display subclass. 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by TheChymera** [comment]
@GaelVaroquaux I haven't yet figured out where exactly the slices axes are arranged, but you mean make a variation of this class? https://github.com/nilearn/nilearn/blob/0e03cf6644662bd0ee0c420eff59926a22e29289/nilearn/plotting/displays.py#L1037

**Comment by GaelVaroquaux** [comment]
Indeed, that's exactly (sorry, I was on my phone, and in trains)

The positioning of the axes is done by the "locator" method: https://github.com/nilearn/nilearn/blob/0e03cf6644662bd0ee0c420eff59926a22e29289/nilearn/plotting/displays.py#L1109

It's something a bit tricky: it's a callback called by matplotlib. We use it to get optimal ratios depending on the data.

**Comment by KamalakerDadi** [comment]
Closing with #1869
