### ISSUE TITLE
Missing files in /examples/01_plotting/plot_dim_plotting.py

### ISSUE THREAD

**Issue by mahagonx** [nilearn/nilearn#1826]
Hi

The function `datasets.fetch_localizer_button_task()` does download the required anatomical file for the demo (`localizer_dataset.anat`), and the tmap path cannot be accessed with the function in the code (`localizer_dataset.tmap`).
Simple workaround, which does, however, not use the subject specific anatomical image:

```
from nilearn import datasets

localizer_dataset = datasets.fetch_localizer_button_task()
# Contrast map of motor task
localizer_tmap_filename = localizer_dataset.tmaps[0]
# Standard anatomical image (MNI)
localizer_anat_filename = datasets.MNI152_FILE_PATH
```

Kind regards
Matthias

**Comment by KamalakerDadi** [comment]
What is the version of your Nilearn ?

Small correction in your workaround. It should be:
```python
localizer_tmap_filename = localizer_dataset.tmap
```

**Comment by KamalakerDadi** [comment]
Did you manage to make this example work ? @mahagonx

**Comment by mahagonx** [comment]
Hi

Sorry for the late reply. I use Anaconda (Win7) and installed nilearn 0.4.2 with `pip install nilearn`. The localizer button task dataset does not have a key `tmap` or `anat`, which is why the script interrupted with an error. 

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
C:\ProgramData\Anaconda3\envs\neuro\lib\site-packages\sklearn\utils\__init__.py in __getattr__(self, key)
     70         try:
---> 71             return self[key]
     72         except KeyError:

KeyError: 'tmap'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-1-5731b3c065c7> in <module>
     18 localizer_dataset = datasets.fetch_localizer_button_task()
     19 # Contrast map of motor task
---> 20 localizer_tmap_filename = localizer_dataset.tmap
     21 # Subject specific anatomical image
     22 localizer_anat_filename = localizer_dataset.anat

C:\ProgramData\Anaconda3\envs\neuro\lib\site-packages\sklearn\utils\__init__.py in __getattr__(self, key)
     71             return self[key]
     72         except KeyError:
---> 73             raise AttributeError(key)
     74 
     75     def __setstate__(self, state):

AttributeError: tmap
```

Instead, the dataset contains:
```
for key in localizer_dataset:
    print(key)
```

```
cmaps
tmaps
masks
anats
ext_vars
description
```

With tmaps as a list:
`print(localizer_dataset.tmaps)`

`['C:\\Users\\XYZ/nilearn_data\\brainomics_localizer\\brainomics_data\\S02\\t_map_left_auditory_&_visual_click_vs_right_auditory&visual_click.nii.gz']`

**Comment by kchawla-pi** [comment]
@mahagonx  This *might be* fixed in Nilearn 0.5.0beta. Could you let us know if you are getting the error with that?

**Comment by mahagonx** [comment]
Allright, the demo works in the beta. The localizer dataset contains:
```
description
tmap
anat
```
Thanks.

For others with the same issue, use `pip install nilearn==0.5.0b0`

**Comment by kchawla-pi** [comment]
Thanks for updating us @mahagonx !
Closing this.
Feel free to report any problems.
