### ISSUE TITLE
how to filter out noise using CanICA

### ISSUE THREAD

**Issue by russellu** [nilearn/nilearn#1827]
hello, i'm not sure if this is any actual issue or more of a question, but i was curious about how to properly remove noise from FMRI images using CanICA?

right now, i'm doing the following (python pseudocode)

```
canica = CanICA(params)
canica.fit(nifti)

components = canica.transform([nifti])
# here, i visually inspect the components weight map and/or power spectrum to get the 
# "good" components. i then build a vector of bad component indices:

bad_components = all components that i didn't classify as good

components[:,bad_components] = 0 # set all bad components to zero

denoised_nifti = inverse_transform(components) 
```
so basically, i run CanICA, extract the components, set the bad components to zero (thereby cleaning the component vector), and then do the inverse transform on the cleaned component vector to get my denoised nifti image. 

***Edit - it seems to be working correctly now - i just needed to subtract out the mean of each voxel over the entire time series, to get the desired effect. 

by the way, can anyone explain to me how inverse_transform works? it seems to give quite different (and superior) results to FSL's melodic/fsl_regfilt method for removing noise with ICA. 

thanks,

Russell

**Comment by russellu** [comment]
btw, if anyone is interested, here is the code i use to subtract noise using CanICA

import matplotlib.pyplot as plt 
from nilearn.decomposition import CanICA, DictLearning
import nibabel as nib 
import numpy as np 
from scipy.cluster.vq import vq, kmeans, whiten
import scipy as scipy 

path = '/media/sf_E_DRIVE/task/subject_0/';
nifti = nib.load(path + 'orboth.nii.gz')
niftidata = nifti.get_data()

mask = np.double(niftidata[:,:,:,0] > np.mean(niftidata))# make the mask a bit fatter, to get more voxels
nmask = nib.Nifti1Image(mask,nifti.affine); 

dlearn = CanICA(n_components=75,smoothing_fwhm=3,threshold=None,standardize=True,
                mask=nmask)
dlearn.fit(nifti);

comps = dlearn.transform([nifti])
compsimg = dlearn.components_img_.get_data()
f = np.abs(np.fft.fft(comps[0],axis=0))

# plot the components, for hand selection
for i in np.arange(0,75):
    plt.figure()
    plt.subplot(1,3,1)
    plt.imshow(scipy.ndimage.rotate(np.max(compsimg[:,:,:,i],axis=0),90))
    plt.subplot(1,3,2)
    plt.imshow(scipy.ndimage.rotate(np.max(compsimg[:,:,:,i],axis=1),90))
    plt.subplot(1,3,3)
    plt.imshow(scipy.ndimage.rotate(np.max(compsimg[:,:,:,i],axis=2),270))
    plt.title(i)
    plt.show()
    
 # set the good component indices (found by hand selection)
goodinds = [73,71,67,63,62,47,44,38,34,29,23,16,15,4]; 

indrange = np.zeros([75])
indrange[goodinds] = 1
allbades = np.where(indrange==0)

freshcomps = dlearn.transform([nifti])
freshcomps[0][:,allbades] = 0 # set the bad components to zero

inv = dlearn.inverse_transform(freshcomps)

invdata = inv[0].get_data()
invdata = invdata - np.mean(invdata,axis=3,keepdims=True) # subtract mean of denoised FMRI
new_nifti = nib.Nifti1Image(invdata,nifti.affine)

nib.save(new_nifti,path+'inv_orientation.nii.gz')

**Comment by bthirion** [comment]
Hi,
I tried doing that and I find the result quite weird. I would really advise not to do that. This will require me some time to figure out what happens really when we do this type of manipulation.
Regarding signal denoising, I prefer to rely on the high_variance_confounds approach and/or regressing out signals from targeted regions (ventricles etc.). At least, it makes you pipeline explicit and does not require manual choice of bad ICs.
HTH,
B

**Comment by GaelVaroquaux** [comment]
Thanks for the feedback. I'll close the issue, then.

**Comment by GaelVaroquaux** [comment]
The inverse transform of CanICA applies the ICA model. ICA is a well-defined model, and going from time series to observations once the components images have been estimated is just a matter of multiplying the two.

With regards to automated IC classification tools, I think that we should welcome such contribution. It's a bit of work to implement reliably, though.

**Comment by kchawla-pi** [comment]
We should spell out the steps for more complex PRs such as the one you suggest @GaelVaroquaux , here in the issue so a contributor is encouraged to take it up.
