### ISSUE TITLE
`nilearn.signal.clean` order might not be as described

### ISSUE THREAD

**Issue by miykael** [nilearn/nilearn#1828]
The [description](https://github.com/nilearn/nilearn/blob/master/nilearn/signal.py#L362) of `nilearn.signal.clean` states that the signal is cleaned in the following order:
    - detrend
    - standardize
    - remove confounds
    - low- and high-pass filter

But if I understand the code correctly then this order is wrongly documented. `standardize` should be described as the last step, as shows the code [here](https://github.com/nilearn/nilearn/blob/master/nilearn/signal.py#L537).

I'm happy to write a quick PR about this, but first wanted to make sure that this needs correction (in the documentation?).

**Comment by GaelVaroquaux** [comment]
I think that the issue is deeper than that as pointed out by the [neurostar](https://neurostars.org/t/nilearn-signal-clean/2690) question that (I believe) triggered your comment: indeed, the documentation is wrong, but also the way things are done is not correct: as recommended by the [Linquist paper](https://www.biorxiv.org/content/biorxiv/early/2018/09/04/407676.full.pdf), we should make sure that at each step, the filter applied to the data is orthogonal to the previous filters (where confounds are understood as filters).

I think that the right solution is to do the following (as recommended by the Linquist paper):

1. Band-pass filter the data (if filtering is specified)
2. Band-pass filter the confounds
3. Remove the confounds.

@bthirion : do you agree with my analysis?

**Comment by miykael** [comment]
Considering the Linquist paper and this issue https://github.com/nilearn/nilearn/issues/1011, would it make sense to replace band-pass filters with cosine filters (DCT bases)? By putting confounds, cosine filters and linear trend into one matrix, we could filter all at once, as suggested by the Linquist paper, correct?

**Comment by GaelVaroquaux** [comment]
> Considering the Linquist paper and this issue #1011, would it make sense to
> replace band-pass filters with cosine filters (DCT bases)?

It would be something interesting to add cosine filter, but I would like
to keep to option of having a Butterworth filter, which has good
signal-processing properties.

> By putting confounds, cosine filters and linear trend into one matrix,
> we could filter all at once, as suggested by the Linquist paper,
> correct?

Linquist suggests several options. His most important message is that one
step should not undo what the previous did.

**Comment by bthirion** [comment]
DCT basis is definitely a good option for high-pass filtering.

**Comment by imawla** [comment]
One option would be for `nilearn.signal.clean` to mimic behavior of AFNI's `3dTproject` (https://afni.nimh.nih.gov/pub/dist/doc/program_help/3dTproject.html) as I believe it conducts temporal filtering+confound regression simultaneously, which is one recommendation provided by Lindquist et al.

**Comment by GaelVaroquaux** [comment]
> I don't see any objection to performing simultaneous regression.

I've just read so much in the signal processing literature that it is
strongly recommended not to implement a band-pass filter by hand, and
rather rely on well-known filter, that I am wary.

**Comment by miykael** [comment]
Going according to the title of this issue, I think we can close this issue, once https://github.com/nilearn/nilearn/pull/1837/ is merged. The cosine basis/DCT discussion should qprobably continue under https://github.com/nilearn/nilearn/issues/1011.

**Comment by KamalakerDadi** [comment]
Thanks @miykael for keeping things simplified.

**Comment by kchawla-pi** [comment]
@miykael Based on your comment, this issue appears resolved. You can close this if you are satisfied and don't see any lingering issues, or we can close this in a day or two.

**Comment by miykael** [comment]
Happy to close it :+1:

**Comment by kchawla-pi** [comment]
Many thanks @miykael ! You were very thoughtful about all aspects.
