### ISSUE TITLE
What's the easiest way to fetch all subjects from adhd datasets?

### ISSUE THREAD

**Issue by QinglinDong** [nilearn/nilearn#1841]
If that's out of scope, could you please publish your fMRI preprocessing pipeline? I'd really really appreciate that too.

**Comment by KamalakerDadi** [comment]
Detailed here:  https://github.com/nilearn/nilearn/issues/1065

**Comment by QinglinDong** [comment]
> Detailed here: #1065

Thank you! I am looking into it. 
It would still be great if the entire dataset is available from nilearn, though.

**Comment by GaelVaroquaux** [comment]
The downloader is there for examples and demo. The original data can be downloaded from the original data provider.

Sorry, closing, as we are overloaded with work and cannot tackle this one.

**Comment by kchawla-pi** [comment]
Hi @QinglinDong , as Gael explains, the dataset fetchers NiLearn provides are for convenience for new users learning the ropes with fMRI & NiLearn; and is useful when giving demos to others. Beyond that, a user is expected to download the data from their proper/official sources.
For Nilearn to provide the entire dataset, one would have to write a lot of extra code to make it a reliable method, for resuming interrupted downloads, for confirming the integrity of the downloaded file and so on. 
These capabilities already exist in modern web browser, so it is not smart to reinvent such a complex wheel.

**Comment by QinglinDong** [comment]
@kchawla-pi Sure, I totally understand now. Thank you and Gael for replying!
