### ISSUE TITLE
How to compute a confounds from a resting state fmri nii file

### ISSUE THREAD

**Issue by poppintiger** [nilearn/nilearn#1849]
I want to extract signals on a parcellation defined by labels.
`time_series = masker.fit_transform(fmri_filenames, confounds=?)`
but when i run above code, it need the parameter confounds. How can I get a confounds from a original resting state fmri nii file? Can you help to specify the steps?

**Comment by poppintiger** [comment]
Can I pass a HarvardOxford-cort atlas to this parameter?

**Comment by poppintiger** [comment]
And when I get the confounds matrix, how can I output a valid csv form file？

**Comment by poppintiger** [comment]
Hi ，bthirion
Thanks for your reply!
 I am confused that if I pass only one mask to the  regressors.py code, it only create the confounds base on this one mask. How can I compute the "global	motion-pitch	motion-roll	motion-yaw	motion-x	motion-y	motion-z	gm	compcor1compcor2compcor3compcor4compcor5" at one time, passing multiple mask to create this kinds of confounds. Or should I pass different masks saparately and concatenate them to one confounds? 

And another question is where can I find the specific mask to generated “compcor1compcor2compcor3compcor4compcor5” compcor regressor confound？

**Comment by poppintiger** [comment]
And when I run regressors.py code, it pop out the error:
NameError: name '_check_same_fov' is not defined.

**Comment by KamalakerDadi** [comment]
@poppintiger I will give you an example showing how to use ```high_variance_confounds``` on a 4D resting state fmri nii (See below). You should replace the ```func_img``` with your 4D nii file.

CompCor
```high_variance_confounds``` is implemented based on a paper 'CompCor' (Behzadi NeuroImage 2007).

Simple example which shows how to use ```high_variance_confounds``` on a single 4D fMRI Nifti image. You don't have to think about mask_img with this function.

```python
from nilearn import datasets
from nilearn.image import high_variance_confounds

adhd = datasets.fetch_adhd(n_subjects=1)
func_img = adhd['func'][0]

# 5 CompCor
compcor = high_variance_confounds(func_img, n_confounds=5)
print(compcor.shape)
```

```high_variance_confounds``` is also used in a pipeline showing how to extract confounds. Have a look at this example: examples/03_connectivity/plot_multi_subject_connectome.py


Motion:

"global motion-pitch motion-roll motion-yaw motion-x motion-y motion-z" are motion parameters which should be extracted while pre-processing raw fMRI data. Nipype or fmriprep are the packages you should look at to extract motion parameters. No implementation is available in Nilearn to extract motion parameters.

**Comment by poppintiger** [comment]
Hi @KamalakerDadi 

Thank you so much！It is very helpful. you saved me a lot of time！

**Comment by Ibrahim-Ali-Salim** [comment]
Hi @KamalakerDadi 

I have 3D nii images. I'm wondering how can I use  **high_variance_confounds** ?...

Thank you so much in advance

**Comment by bthirion** [comment]
If you have a series of 3D images, it is equivalent to having a single 4D image. if you have a single 3D images, there is nothing you can do with high_variance_confounds.
Best,

**Comment by Ibrahim-Ali-Salim** [comment]
Thank you @bthirion for quick reply. Actually, I'd like to extract brain rois and build connectivity matrix from ADNI dataset. 
I found the following code :

from nilearn.connectome import ConnectivityMeasure

correlations = []
# Initializing ConnectivityMeasure object with kind='correlation'
connectome_measure = ConnectivityMeasure(kind='correlation')
for filename, confound in zip(func_filenames, confounds):
    # call transform from RegionExtractor object to extract timeseries signals
    timeseries_each_subject = extractor.transform(filename, confounds=confound)
    # call fit_transform from ConnectivityMeasure object
    correlation = connectome_measure.fit_transform([timeseries_each_subject])
    # saving each subject correlation to correlations
    correlations.append(correlation)

Unfortunately I couldn't applied on my dataset cause I don't have **confounds**  

Could you please help me?

**Comment by bthirion** [comment]
Would we continue this discussion in a suitable place (Neurostars) not on this issue ?

The first thing to do is to proceed with estimation without confounds.
Otherwise, you can estimate confounds  from your data, as done in
https://nilearn.github.io/auto_examples/04_glm_first_level/plot_first_level_details.html#sphx-glr-auto-examples-04-glm-first-level-plot-first-level-details-py

**Comment by Ibrahim-Ali-Salim** [comment]
> Would we continue this discussion in a suitable place (Neurostars) not on this issue ?
> 
> The first thing to do is to proceed with estimation without confounds.
> Otherwise, you can estimate confounds from your data, as done in
> https://nilearn.github.io/auto_examples/04_glm_first_level/plot_first_level_details.html#sphx-glr-auto-examples-04-glm-first-level-plot-first-level-details-py

For sure I'd like to discuss  about this issue. How can I get Neurostars

**Comment by Ibrahim-Ali-Salim** [comment]
Hi @bthirion. I registered in Neurostars. How can we do discussion there?

Thanks.

**Comment by NicolasGensollen** [comment]
Hi @Ibrahim-Ali-Salim 

As @bthirion said, we generally use Github issues for bugs and feature requests and rely on the Neurostars forum for usage questions.
If you want to continue this discussion over there, you can either go to [Neurostars](https://neurostars.org/latest) and open a new topic describing your issue (make sure to add the tag "Nilearn").
Alternatively, you can open a new issue [here](https://github.com/nilearn/nilearn/issues/new/choose) and select "Usage question", which will open a new topic on Neurostars with the "nilearn" tag added automatically.

Hope this helps, let me know if you have problems doing this.

**Comment by Ibrahim-Ali-Salim** [comment]
Hi @NicolasGensollen 

I already did it and I'm waiting the replies.

Thank you so much for your help
