### ISSUE TITLE
About the ward parcellation.

### ISSUE THREAD

**Issue by rickwith** [nilearn/nilearn#1850]
Hi,
   I did the ward clustering on resting fmri data by nilearn, but there is one issue that i am not clear here, i.e, as the input data is 4d functional fmri data, and the program use multi-PCA( randomized SVD) to reduce the dimensionality, how it can turn 4d data to data matrix? Is it turning it by every volume and average all? 
  Another issue here is i wanna get the specific cluster number by choosing different distance, and plot the dendrogram, can nilearn provide this?
  Thanks for your attention!

**Comment by GaelVaroquaux** [comment]
With regards to turning the data into a matrix, the PCA is applied to the list of volumes, and each volume is turned into a vector. 

Nilearn does not expose the dendogram, sorry. 

⁣Sent from my phone. Please forgive typos and briefness.​
