### ISSUE TITLE
BoundingBoxError:  image.resample_img

### ISSUE THREAD

**Issue by poppintiger** [nilearn/nilearn#1852]
I got the error ,when I tried to run:
`resample_img(mask, target_shape= dataset.shape[:3] ,target_affine = dataset.affine )`

my dataset is a  4D fmir nii file,  the mask is acquried from the code ：
`icbm = datasets.fetch_icbm152_2009()
mask = image.load_img(icbm['csf'])`

I don't know what the error mean, and how can I deal with it.
Is that because my dataset is not in MNI space? If this is the case, how should I convert it into MNI space?

**Comment by GaelVaroquaux** [comment]
Can you give us the full traceback.

**Comment by poppintiger** [comment]
OK, this is the full traceback:


---------------------------------------------------------------------------
BoundingBoxError                          Traceback (most recent call last)
<ipython-input-93-33d88f53ab35> in <module>()
     41 from nilearn.image import math_img
     42 
---> 43 mask = math_img('img >.5', img=resample_img(mask, target_shape= dataset2.shape[:3],target_affine = dataset2.affine ))
     44 
     45 #(1, 176, 5)

~\Anaconda3\envs\tensorflow\lib\site-packages\nilearn\image\resampling.py in resample_img(img, target_affine, target_shape, interpolation, copy, order, clip)
    485     # of the target affine
    486     if xmax < 0 or ymax < 0 or zmax < 0:
--> 487         raise BoundingBoxError("The field of view given "
    488                                "by the target affine does "
    489                                "not contain any of the data")

BoundingBoxError: The field of view given by the target affine does not contain any of the data

**Comment by poppintiger** [comment]
`---------------------------------------------------------------------------
BoundingBoxError                          Traceback (most recent call last)
<ipython-input-93-33d88f53ab35> in <module>()
     41 from nilearn.image import math_img
     42 
---> 43 mask = math_img('img >.5', img=resample_img(mask, target_shape= dataset2.shape[:3],target_affine = dataset2.affine ))
     44 
     45 #(1, 176, 5)

~\Anaconda3\envs\tensorflow\lib\site-packages\nilearn\image\resampling.py in resample_img(img, target_affine, target_shape, interpolation, copy, order, clip)
    485     # of the target affine
    486     if xmax < 0 or ymax < 0 or zmax < 0:
--> 487         raise BoundingBoxError("The field of view given "
    488                                "by the target affine does "
    489                                "not contain any of the data")

BoundingBoxError: The field of view given by the target affine does not contain any of the data
`

**Comment by KamalakerDadi** [comment]
I would do:

```python
from nilearn.image import resample_img
import numpy as np
from nilearn.image import new_img_like

img=resample_img(mask, target_shape= dataset2.shape[:3],target_affine = dataset2.affine )

# Threshold the resampled image

mask = (img.get_data() > .5).astype(np.int)

# Get mask back to Nifti image

mask_img = new_img_like(img, mask)
```

**Comment by poppintiger** [comment]
Hi @KamalakerDadi ,

I have tried your method, but this line still have the same error:
`img=resample_img(mask, target_shape= dataset2.shape[:3],target_affine = dataset2.affine )
`
So, I suspect whether is there something wrong with my mask, or dataset2? I got the mask from:
`icbm = datasets.fetch_icbm152_2009()
mask = image.load_img(icbm['csf'])`

And my dataset2 is from the ABIDE's 1000 autism fmir nii data. Or is that because my dataset2 is not in MNI space? If this is the case, how should I convert it into MNI space?

**Comment by bthirion** [comment]
Yes, your dataset is likely not in MNI space. you need to move it using what is called "spatial normalization" in the field. You need to do that with a standard tool from the community, such as SPM or FSL --- we don't support that in Nilearn directly.

Note: you should check that the mask superimposes nicely with your data...

**Comment by poppintiger** [comment]
@bthirion  
OK , I got it , Think you so much !
