### ISSUE TITLE
Stable version documentation on website

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1857]
Hey @GaelVaroquaux , once we are ready to release 0.5.0, lets split it off to a `current-release` branch and then you can change the repo settings to point to this branch instead of master to build the documentation from.
This way, alpha and beta builds will not change the documentation of the stable branch.

**Comment by tsalo** [comment]
Was this addressed by #2968 and #3011?

**Comment by NicolasGensollen** [comment]
Indeed ! Thanks for noticing !
