### ISSUE TITLE
loading data already in memory

### ISSUE THREAD

**Issue by meghalD** [nilearn/nilearn#1859]
Hello everyone !
Thanks for all the help earlier. I am facing another issue. It would be great if someone can help me.

I have downloaded entire ABIDE preprocessed data including func_preproc, func_mask and rois_cc200. I wanted to perform dictionary learning and used this link as a reference http://nilearn.github.io/auto_examples/03_connectivity/plot_extract_regions_dictlearning_maps.html
with abide dataset I feel confounds is equivalent to rois_cc200. If not how do I calculate it or fetch it automatically.

2)Another doubt is that the data is quite huge for me to download it again and again. I have saved it in memory and want to fetch these functional files and rois_cc200 files in the format nilearn requires it to be. How do I do that. ?

**Comment by kchawla-pi** [comment]
The dataset fetchers download the dataset to disk and keep them there. One can specify the path for this as the first arg in a fetcher function call or leave it empty, in which case the default download directory is `~/nilearn_data`, where `~` is the current user's home directory.
WHen reusing the fetcher, the function checks for existing datsets on disk at the specified location or the default and does not redownload it if it finds the dataset files in that location.
Is this not the behavior you see?

**Comment by meghalD** [comment]
> The dataset fetchers download the dataset to disk and keep them there. One can specify the path for this as the first arg in a fetcher function call or leave it empty, in which case the default download directory is `~/nilearn_data`, where `~` is the current user's home directory.
> WHen reusing the fetcher, the function checks for existing datsets on disk at the specified location or the default and does not redownload it if it finds the dataset files in that location.
> Is this not the behavior you see?

Yes the behaviour is same. But I don't have enough space in home directory to store all the data. It is possible that I make the folder /nilearn_data somewhere else and specify the directory to use while fetching func_preproc files ?

**Comment by kchawla-pi** [comment]
Yes, as long as the path specified is the same.

**Comment by meghalD** [comment]
> Yes, as long as the path specified is the same.

I am unable to understand. Suppose my /home/user folder does not have enough space and, I have a directory A/B/nilearn_data. How do I specify the files are to be fetched from that location in my script. IT will always look for /home/user

**Comment by KamalakerDadi** [comment]
By default if you don't specify ```data_dir``` explicitly, it downloads in home directory /home/user. But, if you have specified ```data_dir```, then downloader downloads at the specified directory with a folder as nilearn_data.

**Comment by KamalakerDadi** [comment]
If you want to fetch the downloaded data from specified directory, you should specify as ```data_dir=A/B/``` so it fetches from there. You don't have to mention nilearn_data.

**Comment by kchawla-pi** [comment]
Example:
The first time you are accessing a dataset on your system, and you want it on your Desktop:
```
from nilearn.datasets import fetch_atlas_craddock_2012


download_path = '/home/meghaid/Desktop'
craddock_data = fetch_atlas_craddock_2012(download_path)
```
The files will be downloaded to `/home/meghaid/Desktop/nilearn_data/atlas_craddock_2012`.
Then next time you want to access this dataset without downloading it again,
```
from nilearn.datasets import fetch_atlas_craddock_2012


already_existing_data_download_path = '/home/meghaid/Desktop'
craddock_data = fetch_atlas_craddock_2012(already_existing_data_download_path)
```

OR, if you have already downloaded that particular dataset at another location, such as '~/nilearn_data`, move the `nilearn_data` directory to the new location, and then access it in this way.


```
from nilearn.datasets import fetch_atlas_craddock_2012

# if old_location == '/home/meghaid`
new_location = '/home/meghaid/Desktop`
craddock_data = fetch_atlas_craddock_2012(new_location)
```

**Comment by meghalD** [comment]
I generated plots using CanICA decomposition. Can someone explain how to interpret those results. What does the orange/yellow color and blue color signify. What does the regions selected signify ?

**Comment by bthirion** [comment]
CanICA, as all the fMRI decomposition methods, estimates a set of maps that combine linearly to generate the observed data. 
ICA maps have a positive part displayed in orange/yellow, and a negative part, displayed in blue.
The maps typically concentrated on few regions, that are often interpreted as a "network" of regions with correlated activity. The ICA algorithm is said to outline or select such regions.
For more information, you probably want to read 
https://nilearn.github.io/connectivity/resting_state_networks.html

**Comment by meghalD** [comment]
> CanICA, as all the fMRI decomposition methods, estimates a set of maps that combine linearly to generate the observed data.
> ICA maps have a positive part displayed in orange/yellow, and a negative part, displayed in blue.
> The maps typically concentrated on few regions, that are often interpreted as a "network" of regions with correlated activity. The ICA algorithm is said to outline or select such regions.
> For more information, you probably want to read
> https://nilearn.github.io/connectivity/resting_state_networks.html

Thank you for the information. I tried to see maps using both ICA and Dictionary learning with n_components=20. I am unable to judge with the output if ICA performs better or Dictionary learning.
![dict_learn](https://user-images.githubusercontent.com/22214794/48661445-cde37f80-ea97-11e8-98e5-bed440cd4746.JPG)
![ica](https://user-images.githubusercontent.com/22214794/48661446-cde37f80-ea97-11e8-8d22-8c1e73274f67.JPG)

Can someone give some insight on this output ?

**Comment by KamalakerDadi** [comment]
> I am unable to judge with the output if ICA performs better or Dictionary learning.

It is hard to say by looking at the maps. You need to do some classification task to see which is better.

>Can someone give some insight on this output ?

As @bthirion wrote above, those are set of maps extracted with these two different methods. Each component is showed in unique color. It is just a visualization to see quickly if the maps/components extracted are covered over the brain to learn the connectivity interactions.

>I feel confounds is equivalent to rois_cc200. If not how do I calculate it or fetch it automatically.

No, they are not confounds. 
- You should either contact http://preprocessed-connectomes-project.org/abide/ team to ask for motion and other confounds.
- it is possible to use this function ```from nilearn.image import high_variance_confounds``` to compute confounds like CompCor (Behzadi NeuroImage 2007) on functional images (4D) 
Please have a look at the example there: http://nilearn.github.io/modules/generated/nilearn.image.high_variance_confounds.html#nilearn.image.high_variance_confounds

**Comment by meghalD** [comment]
> > I am unable to judge with the output if ICA performs better or Dictionary learning.
> 
> It is hard to say by looking at the maps. You need to do some classification task to see which is better.
> 
> > Can someone give some insight on this output ?
> 
> As @bthirion wrote above, those are set of maps extracted with these two different methods. Each component is showed in unique color. It is just a visualization to see quickly if the maps/components extracted are covered over the brain to learn the connectivity interactions.
> 
> > I feel confounds is equivalent to rois_cc200. If not how do I calculate it or fetch it automatically.
> 
> No, they are not confounds.
> 
> * You should either contact http://preprocessed-connectomes-project.org/abide/ team to ask for motion and other confounds.
> * it is possible to use this function `from nilearn.image import high_variance_confounds` to compute confounds like CompCor (Behzadi NeuroImage 2007) on functional images (4D)
>   Please have a look at the example there: http://nilearn.github.io/modules/generated/nilearn.image.high_variance_confounds.html#nilearn.image.high_variance_confounds

Can you share some code to identify which performs better ?

**Comment by KamalakerDadi** [comment]
>Can you share some code to identify which performs better ?

Sorry, I don't have code to show which performs better. You can compare yourself by following the same tutorial as you are doing before. https://joaoloula.github.io/functional-atlas.html. It has full pipeline in it. Run one pipeline with CanICA and another one with DictLearning and compare the prediction results.

**Comment by meghalD** [comment]
> > Can you share some code to identify which performs better ?
> 
> Sorry, I don't have code to show which performs better. You can compare yourself by following the same tutorial as you are doing before. https://joaoloula.github.io/functional-atlas.html. It has full pipeline in it. Run one pipeline with CanICA and another one with DictLearning and compare the prediction results.

I have already tried doing this. But the issue is the classifiers doesn't require any output of ICA or DictLearning. It gives general result. So how do I compare between the two.

**Comment by KamalakerDadi** [comment]
Sorry, I don't know how to compare the outputs of ICA and DictLearning.

What I was saying is that you can compare which atlas method is better by learning the features (connectivity) extracted on these maps. May be this is not what you need.

**Comment by meghalD** [comment]
> Sorry, I don't know how to compare the outputs of ICA and DictLearning.
> 
> What I was saying is that you can compare which atlas method is better by learning the features (connectivity) extracted on these maps. May be this is not what you need.

Yes, I wanted to differentiate among ICA and Dictionary learning. By the way How do I change atlas methods using the code in the link you gave ?

**Comment by KamalakerDadi** [comment]
```python
from nilearn import decomposition
canica = decomposition.CanICA(n_components=20)
canica.fit(func)
```

```python
dictlearn = decomposition.DictLearning(n_components=20)
dictlearn.fit(func)
```

Have a look at this guide as well. 
https://nilearn.github.io/connectivity/resting_state_networks.html

**Comment by meghalD** [comment]
I followed this link to find correlation matrix of the regions extracted by Dictionary Learning and ICA.
https://joaoloula.github.io/functional-atlas.html

But I see that it is not as per the number of regions selected. And also it does not state the regions.
I feel the matrix should come up as clean as here https://nilearn.github.io/connectivity/region_extraction.html

also with labelled regions in rows and columns. Can some guide me how to do that?

**Comment by bthirion** [comment]
If you want labeled regions, you need to rely on an existing anatomical atlas, and thus not estimate regions from individual data. 
If you want the matrix to display cleanly, you need to reorder it : see e.g. the 'reorder' argument in https://nilearn.github.io/modules/generated/nilearn.plotting.plot_matrix.html

**Comment by meghalD** [comment]
> ```python
> from nilearn import decomposition
> canica = decomposition.CanICA(n_components=20)
> canica.fit(func)
> ```
> 
> ```python
> dictlearn = decomposition.DictLearning(n_components=20)
> dictlearn.fit(func)
> ```
> 
> Have a look at this guide as well.
> https://nilearn.github.io/connectivity/resting_state_networks.html

To find the difference between healthy and diseased patient do I need to pass the data to ICA separately and view the output? Or I should pass the entire data and then plot specific patients and see the difference between diseased and healthy. 
Which approach is correct if I merely want to compare the two types based on their activations and functional connectivities.

**Comment by bthirion** [comment]
ICA is used to create spatial components (dictionaries), the signals of which are the nodes of your connectome. So, you rather want to have common spatial regions for the control+patient population, and study a posteriori the difference between groups by doing statistics on the estimated covariance models.

**Comment by thomasbazeille** [comment]
Can be closed I guess, intricated discussion with no action needed on our side.
