### ISSUE TITLE
Brain mask is bigger than the volume of a standard human brain

### ISSUE THREAD

**Issue by vukovicnikola** [nilearn/nilearn#1863]
Hi @bthirion, @GaelVaroquaux, @KamalakerDadi - this is about an issue I've never encountered before when trying to fit a SpaceNetClassifier model.

I have tried passing a mask to SpaceNetClassifier using either:
a. Generating one using NiftiMasker
```
masker = NiftiMasker(mask_strategy='background')
masker.fit(X)
```
b. Providing a standard MNI mask.nii

I get the following warning when trying to run:
```
decoder = SpaceNetClassifier(
    cv=cv,
    memory="nilearn_cache",
    penalty=fitpenalty,
    memory_level=2,
    n_jobs=1,
    verbose=1,
    screening_percentile=screenp,
    mask=masker
    )
decoder.fit(X, y)
```

> .local/lib/python3.6/site-packages/nilearn/decoding/space_net.py:835: UserWarning: Brain mask is bigger than the volume of a standard human brain. This object is probably not tuned to be used on such data.

I'm intrigued by the error because all the input data (X) is already in MNI space...

I would be grateful for any hints as to why this happens.
N

**Comment by KamalakerDadi** [comment]
Hi @vukovicnikola it is just a warning not an error  ?

**Comment by vukovicnikola** [comment]
Correct - it is a warning. But when it shows up the fitting process ends prematurely...

**Comment by KamalakerDadi** [comment]
It is difficult to tell what is happening. Could you provide us a script and images ?

**Comment by KamalakerDadi** [comment]
If you let it compute the mask by itself, does this happening ?

**Comment by eickenberg** [comment]
It looks like it's triggering this

https://github.com/nilearn/nilearn/blob/master/nilearn/_utils/param_validation.py#L121

Btw what nilearn version are you using? (The latest master has this
functionality not on l835 of space_net.py)

Try:
from nilearn._utils.param_validation import _get_mask_volume

and check the volume of you mask with that function, against

MNI152_BRAIN_VOLUME = 1827243  # mm^2

According to the warning there should be a significant difference.
This can be either because the affine in the mask volume has a the wrong
unit volume, or the mask somehow doesn't mask away any voxels, passing a
full cuboid of voxels.

> input data (X) is already in MNI space...
What does this mean? Is X already masked to be only MNI voxels?

**Comment by vukovicnikola** [comment]
Hi
The nilearn version is 0.4.2. Thanks for the volume calculation function! Indeed, one of the masks seems significantly larger than your estimate. About the "wrong affine unit volume" - how could I check this?
Thanks,
N

**Comment by vukovicnikola** [comment]
Update - I've also let SpaceNet/NiftiMasker computer the mask automatically, and its volume ends up being:  3243351.99 (vs standard MNI mask:  1903751.99). When I run the np.linalg.det(img.affine) on the two files I get -7.99 vs 7.99 respectively...

**Comment by bthirion** [comment]
This hint at a problem with the affine: a human brain with such a volume does not exist...
Can you take the mask and plot it with plot_roi and some transparency to see the MNI brain underneath ?  This should give some hints

**Comment by vukovicnikola** [comment]
OK, so the NiftiMasker generated one is in white, whereas a standard MNI one I had is in red: https://jmp.sh/W9Iv1Wo
Seems NiftiMasker adds some padding...

**Comment by KamalakerDadi** [comment]
> Seems NiftiMasker adds some padding...

If you could provide a Nifti file that would be great. I could try some feasible options on this and tell you.
