### ISSUE TITLE
Adding a new machine learning tutorial to Nilearn

### ISSUE THREAD

**Issue by illdopejake** [nilearn/nilearn#1864]
To the good people of Nilearn,

A small group including myself and @GaelVaroquaux  collaborated on a Nilearn tutorial as part of a satellite workshop series alongside the Resting State and Brain Connectivity 2018 conference in Montreal. The third part of this tutorial featured a machine-learning example, where we used functional connectivity data from an open dataset of 155 young children, adolescents and young adults to predict age. It went quite well, and Gaël and I had discussed the possibility of adding it to Nilearn.

@pbellec is putting on another machine learning workshop as a satellite event to the Montreal Artificial Intelligence and Neuroscience conference (Dec. 12th), which will feature a Nilearn tutorial. We were thinking of using the same tutorial as described above. The group members responsible for this tutorial thought it might be good to try to add the tutorial to Nilearn ahead of the conference, if possible, and would love to put in some work to make that happen!

The tutorial, as it was given, can be found here: https://github.com/illdopejake/RS2018_Nilearn_tutorial. The specific part we would like to add can be found within, or here: https://github.com/illdopejake/RS2018_Nilearn_tutorial/blob/master/Nilearn_tutorial_2018_3_Machine_learning.ipynb

The dataset is here: https://openneuro.org/datasets/ds000228/versions/1.0.0

The first challenge would probably be reduction of the size of the dataset. The full size of this dataset is around 14GB. We've done some work to reduce the size while retaining the original result by varying the sample size, voxel-size, and to a lesser degree, numerical precision. 

This work (which is in progress) can be found here: https://github.com/illdopejake/RS2018_Nilearn_tutorial/blob/reducing_dataset/development/Reducing_dataset.ipynb. Apologies, it's not super clean at the moment.

At this point, we have been able to reduce the data substantially (under 2GB) while still retaining some semblance of the original effects. We were wondering if there were Nilearn preferences or standards to pay attention to here? Would it be acceptable to represent the data with ints instead of floats? How large of a voxel size is really permissible? 

Anyway, we would love to collaborate with the Nilearn team to make this happen. We wanted to move our discussion to a public place to facilitate that! 

Cheers,
@illdopejake, @pbellec , @emdupre , @gkiar, et al.

**Comment by KamalakerDadi** [comment]
Interesting!

>At this point, we have been able to reduce the data substantially (under 2GB) while still retaining some semblance of the original effects. We were wondering if there were Nilearn preferences or standards to pay attention to here? Would it be acceptable to represent the data with ints instead of floats? How large of a voxel size is really permissible?

Could you please summarize the R2 score we got so far and data resolution we used to get this score ? 

If I understand correctly, the idea is to integrate this work into Nilearn ? Given this, is that only the data fetcher missing ?

**Comment by bthirion** [comment]
Sounds great !
Regarding resolution, I believe that we can go up to 4mm isotropic. Using ints is fine I think.

If you want to save more space, you should use the projection of the data onto a given atlas, but this would create a much more ad hoc data representation, hence it should be avoided I think.

**Comment by GaelVaroquaux** [comment]
To give more context: if this works out, I hope to rework all our
resting-state examples to use this dataset. It would enables a consistent
teaching of resting-state processing, from network extraction to
biomarkers.

**Comment by pbellec** [comment]
We are working on making a lightweight release of the data now, and discussing where to host it. We are thinking because it's nice, kind of permanent with a good API. If the nilearn team has suggestions/concerns on this front, please let us know.

**Comment by kchawla-pi** [comment]
We have used osf for a few example datasets recently. Seems good so far.

**Comment by illdopejake** [comment]
So, I'm going to come back a bit later with more details, but it looks like if we: 

a) resample the images to 4mm, 
b) express values as int16s (already precision of the raw data actually), 
c) crop them using crop_img, 
d) double the TR by deleting every other volume
e) gzip individual images 

I *think* the whole dataset (155 subjects) should be less than 1.5 GB. We can still get decent results from the age prediction, but its mostly just segregating young subjects (3-12) from older subjects (18-39). Anyway, more on all this later. Do you think the parameters above could be acceptable?

**Comment by GaelVaroquaux** [comment]
> a) resample the images to 4mm,
> b) express values as int16s (already precision of the raw data actually),
> c) crop them using crop_img,
> d) double the TR by deleting every other volume
> e) gzip individual images

> I think the whole dataset (155 subjects) should be less than 1.5 GB.

That's definitely small enough!

> We can still get decent results from the age prediction, but its mostly
> just segregating young subjects (3-12) from older subjects (18-39).

OK. Maybe we could just download 40 young and 40 adults by default, and
try to do a classification. It should be easier.

> Do you think the parameters above could be acceptable?

I worry about d), because I would like this data to be useable for demoing
other things, such as ICA. My goal is to replace what we have by this
data.

**Comment by illdopejake** [comment]
Hi all,

@emdupre was able to downsample the data to 4mm, zip it, and throw it on OSF. At @GaelVaroquaux 's suggestion, we didn't end up doubling the TR. The whole dataset 155 subject still fits into less than 2GB. The OSF link to the dataset is here:

https://osf.io/5hju4/

Regarding the tutorial, at Gael's suggestion, we change it to a classification problem -- adults vs. children. This seems like a good idea -- I ran the analysis with the whole sample using a regular SVC and the classification accuracy was very good:
Training data 10-fold CV: Precision = 0.96, Recall = 0.96, f1 = 0.96.
Left-out test data: Precision = 0.93, Recall = 0.94, f1 = 0.93

There are only 33 adults anyway, so we can probably move forward with all adults and a subsample of ~40-50 children. This would surely be <1.5GB... probably closer to 1GB. As soon as possible, I'll get a clean draft of the machine learning tutorial with this subsample of the data. Hopefully this weekend.

**Comment by GaelVaroquaux** [comment]
Wow, this seems like a fantastic work!

This will be incredibly useful!! Thanks so much!

**Comment by illdopejake** [comment]
Hi all!

Sorry for the silence. We kind of got swept up with the conference and preparing the tutorial. I think it went spectacularly well. People seemed blown away by how much they can accomplish with Nilearn!

Anyway, the executed tutorial we used can be found here:

https://github.com/brainhack101/introML/blob/master/MAIN_tutorial_machine_learning_with_nilearn_EXECUTED.ipynb

We selected 50 random children and all 33 adults. This dataset (which was gzipped but not archived) is about 1GB in total. The dataset is sitting here:

https://osf.io/5hju4/

We're happy to discuss next steps and how we can help facilitate!

**Comment by GaelVaroquaux** [comment]
> We selected 50 random children and all 33 adults. This dataset (which was gzipped but not archived) is about 1GB in total.

Awesome!! We need to look at that!!

> We're happy to discuss next steps and how we can help facilitate!

It is mostly about trying out example that currently run with the ADHD
data to see if they look good with this data. Our goal is to replace the
ADHD data with this one.

**Comment by thomasbazeille** [comment]
Can be closed thanks to the merge of #1953
