### ISSUE TITLE
nilearn plotting.plot_roi error

### ISSUE THREAD

**Issue by AnantShinde** [nilearn/nilearn#1867]
I am trying to follow http://nilearn.github.io/co...

I was able to run all the python instructions without error. However, plotting do not show any images. Do I have to install some other library?

In [21]: plotting.plot_roi(atlas_filename)
Out[21]: <nilearn.plotting.displays.orthoslicer at="" 0x7fb5723310f0="">

In [22]: atlas_filename
Out[22]: '/home/ITS/abshinde/nilearn_data/fsl/data/atlases/HarvardOxford/HarvardOxford-cort-maxprob-thr25-2mm.nii.gz'

**Comment by kchawla-pi** [comment]
IF you are using Jupyter notebook, have you inserted and executed this command in the first cell?
`%matplotlib inline`
If not run it and run the plotting command again.
If you are not using Jupyter Notebook or that didn't work, use the show function found under
`matplotlib.pyplot.show()`

**Comment by GaelVaroquaux** [comment]
> matplotlib.pyplot.show()

Also available as nilearn.plotting.show()

**Comment by AnantShinde** [comment]
@kchawla-pi 
I am not using jupyter notebook.
system: anaconda: python 3.6 on Linux Redhat. 
installed ipython , scipy, scikit-learn, matplotlib and nibabel as it is required for installation.

matplot.pyplot.show() worked for displaying the brain.

nilearn.plotting.displays.orthoslicer is this a error?

**Comment by KamalakerDadi** [comment]
>nilearn.plotting.displays.orthoslicer is this a error?

No it is an Python object inherited when you call plotting functions which is in your case plot_roi.

@AnantShinde  Closing this one as I don't see any issue here ?
