### ISSUE TITLE
Building exe problems

### ISSUE THREAD

**Issue by shylocks** [nilearn/nilearn#1868]
When i use pyinstaller to build a script with these code:
```
display = plotting.plot_stat_map(self.stat_img, display_mode=d, cut_coords=[j])
display.add_contours(self.stat_img, levels=[self.threshold], colors=self.color)
display.savefig(self.roaming_path + d + '_' + str(j) + '.png')
```
add_contours function requires  `nilearn\datasets\data\avg152T1_brain.nii.gz`
I tried `pyinstaller -F --add-data="..\nilearn\datasets\data\avg152T1_brain.nii.gz" test.py`
It doesn't work and tell me not found \nilearn\datasets\data\avg152T1_brain.nii.gz in temporary running folders.
But when i use `pyinstaller test.py` and move `nilearn\datasets\data\avg152T1_brain.nii.gz` to the running folder it works properly.
How can i use pyinstaller or other pips to build a nilearn based script which contains add_contours function into one file without requirements?

**Comment by kchawla-pi** [comment]
Not entirely certain about your use case. Why is this useful?

However won't `add-data="..\nilearn\` add the data not to the current directory but one higher up? Would `add-data=".\nilearn\` work?

**Comment by kchawla-pi** [comment]
@shylocks Success? Yay? Nay?

**Comment by shylocks** [comment]
> @shylocks Success? Yay? Nay?

works. Thanks a lot.
