### ISSUE TITLE
Add an option for displaying plots in radiological rather than neurological view

### ISSUE THREAD

**Issue by jclauneuro** [nilearn/nilearn#1875]
Relatively new to nilearn and was hoping to adopt this tool for displaying plots in a more reproducible way. The default plotting view is in neurological convention (left-is-left), but is there a possibility of providing an option for radiological view (left-is-right)?

From what I can gather from the (excellent!) documentation and neurostars, this functionality does not currently exist: https://neurostars.org/t/how-to-control-displayed-orientation-in-nilearn-plots/1408

**Comment by GaelVaroquaux** [comment]
Given that nilearn is used by many different populations, with different expectations, I think that adding such an option would indeed be a good thing.

We would welcome a pull request from anybody, adding a 'radiological=False' option to the various plotting function. We will review and give advice to help the merge.

**Comment by willtack** [comment]
I want to bring up this issue again. I'm using the `plot_glass_brain` function to display a statistical map which will be read by a radiologist as part of a clinical pipeline, and it would ideal to be able to display in radiological (RPI) orientation. 

I've forked the Repo and, to get started, added [some code](https://github.com/willtack/nilearn/blob/15057fbe52653b8fb175dc72b095286097b32eba/nilearn/plotting/displays.py#L132) to displays.py to assign the L and R labels depending on a specified orientation (hopefully). 

I'm not sure where to go from here though; some direction would be greatly appreciated. Thanks for all you do!

**Comment by jclauneuro** [comment]
Great! On my list, but just haven't had time to personally look into this. Agree that this would be helpful for presenting data to users more on the clinical side

**Comment by GaelVaroquaux** [comment]
Given how nilearn has spread and is popular, I am +1 on integrating this today.

As a pointer, it probably should be done by using ax.invert_axis in places such as https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/displays.py#L107

Also, for this feature to be accepted, it will need to be exposed in all the nilearn.plotting.plot_* functions, be documented (at least in the docstrings of these functions), and be illustrated in an example (for instance adding a line to an existing example that demoes plotting functions).

**Comment by kwagstyl** [comment]
We're also keen to have a radiological view option in nilearn.
I've added a radiological=False option to all the plot_* functions and tested it on all the plots in plot_demo_plotting.py, and added an example at the bottom.
The only issue I'm having is with plot_glass_brain which seems to ignore the radiological flag. 
I can't figure out why this is as it calls the same _plot_img_with_bg() as the other plotting functions. Is it somehow using a different axis set up?
https://github.com/kwagstyl/nilearn/tree/radiological

**Comment by bthirion** [comment]
Thx for sharing !
Can you open a Pull Request (PR) with the existing code ?
We will then sort out the case of plot_glass_brain, that is indeed likely different.
Best,
