### ISSUE TITLE
'nilearn.plotting' has no attribute 'find_parcellation_cut_coords'

### ISSUE THREAD

**Issue by poppintiger** [nilearn/nilearn#1876]
I want to run this example:
[https://nilearn.github.io/auto_examples/03_connectivity/plot_atlas_comparison.html#sphx-glr-auto-examples-03-connectivity-plot-atlas-comparison-py](url)
But, it shows the "'nilearn.plotting' has no attribute 'find_parcellation_cut_coords'" ERROR.
How can I find the alternative method?

**Comment by KamalakerDadi** [comment]
It might be that you are not using recent version. What is your nilearn version ?

**Comment by poppintiger** [comment]
> It might be that you are not using recent version. What is your nilearn version ?

@KamalakerDadi Thanks for reminding, I upgraded it and it works.
