### ISSUE TITLE
issue about ward parcellation

### ISSUE THREAD

**Issue by rickwith** [nilearn/nilearn#1885]
Hi,
I have tried the ward clustering with nilearn, but i found that i only get the results by giving a total cluster number,  rather than giving a threshold distance like "criterion" in fcluster of scipy. 
The reason i wanna do this is that i try to do the clustering based on AAL altas, on each region separately, so i cannot give a total number for all different region, and i need the "criterion" option like scipy. I try to do the same thing in scipy, but it is hard for me to do this alone,  so i hope nilearn could provide this option if it is possible.

**Comment by KamalakerDadi** [comment]
>I have tried the ward clustering with nilearn, but i found that i only get the results by giving a total cluster number, rather than giving a threshold distance like "criterion" in fcluster of scipy.

We wrapped around scikit-learn based clustering methods. Which one are you pointing at based on this link: https://scikit-learn.org/stable/modules/generated/sklearn.cluster.AgglomerativeClustering.html#sklearn.cluster.AgglomerativeClustering

>The reason i wanna do this is that i try to do the clustering based on AAL altas, on each region separately, so i cannot give a total number for all different region, and i need the "criterion" option like scipy. I try to do the same thing in scipy, but it is hard for me to do this alone, so i hope nilearn could provide this option if it is possible.

Would something like this work for you ?

```python
import nibabel
from nilearn import datasets
from nilearn import plotting
from nilearn.regions import Parcellations
from nilearn.image import new_img_like

adhd = datasets.fetch_adhd(n_subjects=5)

aal = datasets.fetch_atlas_aal()
data = nibabel.load(aal.maps).get_data()

single_label = data == 2002
single_roi_img = new_img_like(aal.maps, single_label)

parcellations = Parcellations(method='ward', n_parcels=10,
                              mask=single_roi_img)
parcellations.fit(adhd.func)
plotting.plot_roi(parcellations.labels_img_)
plotting.show()
```
![parcellations_on_single_roi](https://user-images.githubusercontent.com/11410385/50404855-16840c00-07ad-11e9-9c4b-78f8e0ebabbc.png)

**Comment by KamalakerDadi** [comment]
If it is the same like #1750 then we should close this duplicate one. AFAIK @dPys is working on a example related to issue #1750

**Comment by rickwith** [comment]
> If it is the same like #1750 then we should close this duplicate one. AFAIK @dPys is working on a example related to issue #1750

okay, thanks a lot, i am looking forward for the example.

**Comment by KamalakerDadi** [comment]
Please continue discussion on issue #1750. Closing this one.
