### ISSUE TITLE
Inconsistencies between view_connectome and plot_connectome

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1886]
There are a few inconsistencies between plot_connectome and view_connectome that means that one is not interchangeable with the other. In particular, I note:

* node_coords is called coords in view_connectome
* the colormaps differs.

There might be more. This is just what I saw at a cursory glance.

**Comment by GaelVaroquaux** [comment]
> Which one should we support going forward?

plot_connectome: it has been around for longer.

> We will also add a deprecation warning for the other.

Yes.

> Which other method/functions would be candidates for checking this?

I don't know. I just discover these things as I go: as a user, they smell
weird.

**Comment by meghalD** [comment]
What do the axis range suggest in view_connectome. Is it correlation ? If yes, it should be within (+1,-1) , but as I plot it goes beyond the range.
am I misinterpreting the plot ? Does view_connectome show functional connectivity like plot_connectome ?

**Comment by bthirion** [comment]
As far as I can see, `view_connectome` does not make assumptions on the displayed statsitics nor on its range. If you use inverse covariance or tangent representations, or even simply some z-transform of correlations the values will not be confined in [-1, 1].

**Comment by meghalD** [comment]
> As far as I can see, `view_connectome` does not make assumptions on the displayed statsitics nor on its range. If you use inverse covariance or tangent representations, or even simply some z-transform of correlations the values will not be confined in [-1, 1].

Yes, I got the range [-1,+1] on applying partial correlation. So the colors here represent the level of correlation. right?
Also, why is this not the range for sparse inverse covariance? Is there any way out to transform range for inverse covariance.

**Comment by bthirion** [comment]
> Yes, I got the range [-1,+1] on applying partial correlation. So the colors here represent the level of correlation. right?

Indeed.

**Comment by bthirion** [comment]
> Also, why is this not the range for sparse inverse covariance? Is there any way out to transform range for inverse covariance.

You should not use inverse covariance, which is hard to interpret, especially in high dimension.
Note that partial correlations are inverse covariance estimated reweighted by the diagonal of the inverse covariance matrix (aka partial variance). Partial correlations are thus between -1 and  +1. See e.g. http://nilearn.github.io/connectivity/connectome_extraction.html

**Comment by jeromedockes** [comment]
> * node_coords is called coords in view_connectome
> 
> * the colormaps differs.

these two seem very easy to fix; is someone willing to open a pr?
I'm not sure I understood the rest of the discussion about the range, I think it should be a separate issue

**Comment by kchawla-pi** [comment]
It does not seem they pertain to the title of the topic.  @meghalD would you clarify?
I will start on the first part after the 22nd.

**Comment by jeromedockes** [comment]
here is a list of other inconsistencies that need to be fixed, I'm sorry that
there are so many:

view_connectome vs plot_connectome
----------------------------------
coords instead of node_coords
no possibility to set node_color
marker_size instead of node_size
cmap instead of edge_cmap
no edge_vmin or edge_vmax
threshold instead of edge_threshold

view_markes vs add_markers
--------------------------
coords instead of marker_coords
colors instead of marker_color
black by default instead of red

**Comment by kchawla-pi** [comment]
@jeromedockes Not at all, this is super helpful for my work! Thanks for finding & sharing them !

**Comment by kchawla-pi** [comment]
@GaelVaroquaux Do I choose to uphold the parameter names in plot_connectome since, as you mentioned,  it has been around longer, or in the above cases you have a preference?

**Comment by jeromedockes** [comment]
I think the idea is to keep plot_connectome as it is and make view_connectome as
similar to it as possible.
I think there can be a first PR for inconsistensies that are just parameter
naming, introducing the correct names and emitting a DeprecationWarning if the
old names are used.
Functionalities that need to be added, like node_color or edge_vmin, can be delt
with in separate PRs (if at all).

**Comment by meghalD** [comment]
Is there a function in nilearn to view brain activations in resting state fMRI for a group of patients ?

**Comment by kchawla-pi** [comment]
Hi @meghalD 
Thanks for using Nilearn and the question.
Would you post this question on Neurostars, adding the tag Nilearn to it? That is the proper forum for questions regarding Nilearn usage and data analysis help.
Gitub issues is for filing bugs & feature requests.

Also, adding a question in an existing issue,  unrelated to the issue, makes it difficult for the developers to keep track of software related issues and conversations.

**Comment by meghalD** [comment]
> Hi @meghalD
> Thanks for using Nilearn and the question.
> Would you post this question on Neurostars, adding the tag Nilearn to it? That is the proper forum for questions regarding Nilearn usage and data analysis help.
> Gitub issues is for filing bugs & feature requests.
> 
> Also, adding a question in an existing issue, unrelated to the issue, makes it difficult for the developers to keep track of software related issues and conversations.

Got it. I tried using neurostars but got no responses. :(  No problem, I will do the required.

**Comment by kchawla-pi** [comment]
I am sorry no one responded. Please post a link of the Neurostars post here.

**Comment by meghalD** [comment]
> I am sorry no one responded. Please post a link of the Neurostars post here.

https://neurostars.org/t/coactivations-in-resting-state-fmri/3359

**Comment by kchawla-pi** [comment]
Thanks. You should add the tag Nilearn to this and all your future Nilearn posts. We get emails from Neurostars when someone tags their post Nilearn. It will also make it easier for other users to find your post and help, or benefit from it.

**Comment by meghalD** [comment]
> Thanks. You should add the tag Nilearn to this and all your future Nilearn posts. We get emails from Neurostars when someone tags their post Nilearn. It will also make it easier for other users to find your post and help, or benefit from it.

Done. Thanks for the help.

**Comment by thomasbazeille** [comment]
Solved by 1913 ,can be closed
