### ISSUE TITLE
Automatic dtype selection for NiftiMasker failing for scaled data

### ISSUE THREAD

**Issue by effigies** [nilearn/nilearn#1891]
Following #1711, NIfTI images that have `int16` data blocks have their values coerced to `int`, even if the `scl_slope` and `scl_inter` fields are provided. This is because the `.get_data_dtype()` method is used, which refers to the on-disk data type, not the values.

Consider:

```Python
import numpy as np
import nibabel as nb

orig = nb.Nifti1Image(np.random.randn(5, 5, 5), np.eye(4))
orig.set_data_dtype('int16') 
orig.to_filename('fdata_as_int16.nii')

loaded = nb.load('fdata_as_int16.nii')
print("get_data_dtype():", loaded.get_data_dtype())
print("get_data().dtype:", loaded.get_data().dtype)
```

Output:
```
get_data_dtype(): int16
get_data().dtype: float64
```

This is causing problems in `nipype.interfaces.nilearn.SignalExtraction` (see nipy/nipype#2839, nipy/nipype#2841), which now returns results rounded to the nearest integer, e.g.:

```
test_signal_extr_4d_global_no_shared - interfaces.tests.test_nilearn.TestSignalExtraction

AssertionError:  Arrays are not almost equal to 1 decimals  ACTUAL: 0.0  DESIRED: 0.375

test_signal_extr_global_no_shared - interfaces.tests.test_nilearn.TestSignalExtraction
interfaces/tests/test_nilearn.py

AssertionError:  Arrays are not almost equal to 1 decimals  ACTUAL: 0.0  DESIRED: -0.6666666666666666

test_signal_extract_no_shared - interfaces.tests.test_nilearn.TestSignalExtraction
interfaces/tests/test_nilearn.py

AssertionError:  Arrays are not almost equal to 1 decimals  ACTUAL: -2.0  DESIRED: -2.33333
```

It looks like you're probably using `get_data_dtype` with the idea that it will give you `np.array(img.dataobj).dtype` without first loading the data array. The following will do the job:

```Python
import numpy as np
import nibabel as nb

def img_data_dtype(img):
    dataobj = img.dataobj
    if not nb.is_proxy(dataobj):
        return dataobj.dtype
    if (dataobj.slope, dataobj.inter) != (0.0, 1.0):
        return dataobj.dtype
    return np.float64
```

You could also get the same thing with less worry about copying the exact logic by just grabbing the first data element out of the image and checking its dtype:

```Python
def img_data_dtype(img):
    first_idx = tuple(np.zeros_like(img.shape))
    return img.dataobj[first_idx].dtype
```

**Comment by bthirion** [comment]
You fix with sounds right (I prefer the first function). Can you issue a PR ?
