### ISSUE TITLE
Nibabel installation failure on travis

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#1900]
Nibabel does not install on one of the travis jobs:
https://travis-ci.org/nilearn/nilearn/jobs/479892937

Does someone knows what changed? Forcing an install is trivial, but I would like to understand why it worked before and why it is not working now.

**Comment by KamalakerDadi** [comment]
For some reason, Python 2.7 could not install nibabel 2.3.2 because of ```ImportError``` issues. There is not a problem installing nibabel 2.3.2 on Python >=3.5.

Discussed here:
https://github.com/nilearn/nilearn/pull/1892

**Comment by KamalakerDadi** [comment]
I did on my PR #1890 by asking to install 2.3.1 on this environment. 
https://github.com/nilearn/nilearn/pull/1890/files

**Comment by GaelVaroquaux** [comment]
Thanks. I added an issue on the nibabel tracker.
