### ISSUE TITLE
Low silhouette score after ward clustering 

### ISSUE THREAD

**Issue by rickwith** [nilearn/nilearn#1902]
Hi, 
  I used ward method to cluster rs fmri data with nilearn, but i found that the silhouette_score in sklearn is very low according to the parcellation result, here are the script:
```   
  epi = '/home/jack/Desktop/s1r1.nii.gz'
  epi_img = nib.load(epi)
  ward_nilearn = Parcellations(method='ward', n_parcels=n_parcels,
                     standardize=False, smoothing_fwhm=False,
                     memory='nilearn_cache', memory_level=1,mask=mask_img,
                     verbose=1)
  ward_nilearn.fit(epi_img)
  labels_nilearn = ward_nilearn.labels_img_
  labels_nilearn_ = nifti_masker.transform(labels_nilearn).T
  score_nilearn = metrics.silhouette_score(epi_masked.T,labels_nilearn_,metric='euclidean')
```
The `score_nilearn` here is -0.044671338, do you have any suggestion about this? Could nilearn provide any way to measure the validity of clustering?

**Comment by kchawla-pi** [comment]
Hi @rickwith 
Thanks for your query and thank you for using Nilearn! Would you post this question on Neurostars instead? Someone can answer it there.
That is the appropriate forum for use-related questions. Github issues is for the purpose of bug-reporting & feature requests.
You may post the link of this question on Neurostars back here this time.
Thanks.

**Comment by rickwith** [comment]
Okay, thank you very much!

**Comment by kchawla-pi** [comment]
The question has been reposted at 
https://neurostars.org/t/nilearn-low-silhouette-score-after-ward-clustering/3261
If anyone opens this issue, please answer this there.

**Comment by rickwith** [comment]
> The question has been reposted at
> https://neurostars.org/t/nilearn-low-silhouette-score-after-ward-clustering/3261
> If anyone opens this issue, please answer this there.

Really thank you for this!

**Comment by KamalakerDadi** [comment]
How about increasing subjects ? Also, if I understood correctly, you are comparing between labels extracted on masked data and without masking ? Does this explain the difference ?

How is ```silhouette_score``` used in fMRI context ?

**Comment by rickwith** [comment]
> How about increasing subjects ?
You mean concatenate the rs time series matrix of all subjects and using multi-pca? 

The mask i used here is a grey matter mask to avoid data on csf and white matter. And the choice of silhouette_score is according to this paper: "Human brain mapping: A systematic comparison of parcellation methods for the human cerebral cortex" from 《NeuroImage》.
