### ISSUE TITLE
Questions regarding using Nilearn should be posted on Neurostars, not here.

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1904]

**Comment by kchawla-pi** [comment]
A banner for users.
Github issues is for Feature requests and bugs.

**Comment by emdupre** [comment]
Would it make more sense to put this information in an issue template ?

**Comment by GaelVaroquaux** [comment]
> Would it make more sense to put this information in an issue template ?

That's a good suggestion!

**Comment by kchawla-pi** [comment]
Woot! That is a great idea! Thanks!

**Comment by kchawla-pi** [comment]
Anyone not in favour of this idea, type in the Avogadro's Number till the 27th decimal place here.

**Comment by kchawla-pi** [comment]
Its on #1905 if someone wants to feedback the text. I'll merge tomorrow morning.
