### ISSUE TITLE
Plot multi layer niftiImage in one brain fig

### ISSUE THREAD

**Issue by QiuyueXue** [nilearn/nilearn#1909]
Hi all, is there anyway to plot multiple niftiimages in one brain fig? I basically have several niftiImages which corresponds to fmri data of different active regions(other not active regions are 0), and want to plot these data in one brain fig, with different regions showing in different color, is there anyway to do that?(for example is adding overlay layer on plot_glass_brain figs possible?)

Thanks for your help!

**Comment by kchawla-pi** [comment]
Hi Qiuyue,
Thanks for the question and using Nilearn!
Questions about usage and analysis are best posted on neurostars.org . This
is a place for pointing out bugs and for feature requests.

Would you repost this question on neurostars.org and add the tag Nilearn to
it?

**Comment by QiuyueXue** [comment]
Hi thanks for the reply, I'll repost my question on neurostars.org, sorry about that.
