### ISSUE TITLE
Change iframe call for rendering in Jupyter Book

### ISSUE THREAD

**Issue by emdupre** [nilearn/nilearn#1915]
I would like to render interactive brainsprites generated from `view_img` in [Jupyter Book](https://github.com/jupyter/jupyter-book). Jupyter Book is built using Jekyll, and converts executed notebooks to markdown using nbconvert. The nbconvert is then converted to stylized HTML using kramdown.

My difficulty comes that kramdown [cannot currently handle unquoted attributes](https://github.com/jupyter/jupyter-book/issues/72) (even though these are valid HTML!). When we generate the iframe in which the brainsprite viewer is embedded here in nilearn, [we don't quote the `width` and `height` attributes](https://github.com/nilearn/nilearn/blob/ed86f29305a264693156826f0e429b2d6281eeaf/nilearn/plotting/js_plotting_utils.py#L126).

I'd like to open a simple fix to quote these two attributes, and smooth nilearn use with Jupyter Book. Would that be alright?

**Comment by GaelVaroquaux** [comment]
> I'd like to open a simple fix to quote these two attributes, and smooth nilearn
> use with Jupyter Book. Would that be alright?

That sounds no problem to me, though maybe I didn't understand the
proposed change.

I suggest that you open the PR and we look at it.

Cheers!

**Comment by emdupre** [comment]
Great, thanks for the quick response ! It's a very (very) small patch, but I wanted to confirm you were ok to fix this on your side instead of the kramdown side :smile_cat: 

PR: #1916
