### ISSUE TITLE
Generalising img_to_signal_labels to reduce with funcs other than the mean?

### ISSUE THREAD

**Issue by dangom** [nilearn/nilearn#1926]
What would you like changed/added and why?

I've been working with statistical images using NiftiLabelsMasker. For a personal need, I had to generalise the `img_to_signal_labels` to reduce ROIs to a scalar value using the max and the std, instead of the mean.
In essence, [this part of the function here had to change to](https://github.com/nilearn/nilearn/blob/master/nilearn/regions/signal_extraction.py#L107):

```python
for n, img in enumerate(np.rollaxis(data, -1)):
    signals[n] = np.asarray(measurement_func(img,
                                             labels=labels_data,
                                             index=labels))
```
where `measurement_func` is checked previously as:

```python
# Check func
acceptable_funcs = ('mean', 'minimum', 'maximum', 'standard_deviation',
                    'variance', 'median')
if func in acceptable_funcs:
    measurement_func = getattr(ndimage.measurements, func)
else:
    raise ValueError("func not in %s" % (acceptable_funcs,))
```

I was wondering if this would merit a PR at all, and that's why I opened the issue. And if there is interest, should the user also be allowed to pass his/her own functions, as long as they obey the same signature as `ndimage.measurements.mean(img, labels=labels_data, index=labels)`?

What would be the benefit? Does the change make something easier to use?

I can think of all sorts of applications. One of them would be using the max and the standard_deviation to look at spikes within ROIs, comparing ROIs in general, or for studying the effects of regressing out confounds, i.e. general Q.A.

**Comment by bthirion** [comment]
I think that this deserves a PR.  Thx for proposing.

**Comment by GaelVaroquaux** [comment]
+1
