### ISSUE TITLE
Nilearn eeg virtual com port to nii files?

### ISSUE THREAD

**Issue by josheeg** [nilearn/nilearn#1939]
Nilearn eeg virtual com port to nii files?
There are a lot of open eeg type projects open bci open hardware exg ... How can the data from these go to ni kit learn?

**Comment by kchawla-pi** [comment]
Please post this at neurostars.org with the tag `nilearn`.

**Comment by josheeg** [comment]
Did now thanks

**Comment by kchawla-pi** [comment]
I don't see your post, please make sure you have tagged it with `nilearn` . Then post the link to your question here.

**Comment by thomasbazeille** [comment]
Can be closed
