### ISSUE TITLE
Spaghetti code in MultiPCA

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#194]
The way the code in MultiPCA uses the given masker to compute a mask, but not to load the time series (ie not the 'transform' method of the masker) is both confusing for the user (parameters such as smoothing are not taken in account) and leads to spaghetti code. This needs to be rethought.

**Comment by AlexandreAbraham** [comment]
It is now possible to refactor this code using `_iter_check_niimg` and a simple NiftiMasker.

**Comment by bthirion** [comment]
As fasr as I understand this has been addressed.
