### ISSUE TITLE
Improve docstring entry for NiftiMasker parameters

### ISSUE THREAD

**Issue by alpinho** [nilearn/nilearn#1940]
In nilearn.input_data.NiftiMasker class, many parameters point to documentation details of other functions. A link to the documentation of these functions should be provided.

Example:
low_pass: None or float, optional 
This parameter is passed to signal.clean. Please see the related documentation for details.

In this case, a link to the function "signal.clean' shall be given.

**Comment by kchawla-pi** [comment]
I think the docstring should have some more detail right here, beyond "This parameter is passed to signal.clean."

**Comment by tsalo** [comment]
I believe that this should be closed by #1942, but the keyword close wasn't triggered.
