### ISSUE TITLE
Incorrect description of low and high pass in signal.clean() docstring

### ISSUE THREAD

**Issue by alpinho** [nilearn/nilearn#1941]
This is the current description of the docstring:

```
low_pass, high_pass: float
        Respectively low and high cutoff frequencies, in Hertz.
```

It should be the other way around, i.e.:

`Respectively high and low cutoff frequencies, in Hertz.`

**Comment by tsalo** [comment]
This should be closed by #1943, but the way the issue was referenced in the PR didn't trigger the keyword close.
