### ISSUE TITLE
Changing Brainomics dataset to keep only what is used in Nilearn examples.

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1948]
What would you like changed/added and why?
We should host a small subset of Brainomics dataset on osf.io, keeping only the contrasts data that we use in Nilearn examples, and change the fetcher accordingly to directy and only download this subset, bypassing all the SQL queries etc.

What would be the benefit? Does the change make something easier to use?
Make the Brainomics dataset robust and it won't go down as much. The tests won't fail .

**Comment by DimitriPapadopoulos** [comment]
I am in the process of moving the whole _Brainomics/Localizer_ dataset to _osf.io_. See #1925 and #1935.

We will probably change the download function in _Nilearn_ as well. Hopefully this will be finalized in the next few weeks and you won't have to spend time on this issue.

**Comment by bthirion** [comment]
Solved, closing.

**Comment by DimitriPapadopoulos** [comment]
We plan on shutting down the `brainomics.cea.fr` server. Hopefully there aren't too many old Nilearn releases out there that would still use it.
