### ISSUE TITLE
Dropping Python 2.7 & 3.4 Support

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1950]
We have shown the DeprecationWarning regarding dropping support for Python 2.7 & 3.4 since October 2018 (0.5.0b).
The standard policy is to show the deprecation for two releases. We have been showing the warning now for 5 months, for release 0.5.0b and 0.5.0 Stable.
We are going to one more release of 0.5.1 in end of March before the sprint. That makes 2 releases.

Nilearn master should drop Python 2, 3.4 support after the 0.5.1 release. I can fix the multitude of warnings in the CI.

After that the next stable release is likely not gonna be before October, or more likely Nov-Dec.
That would have given users 2 releases and an year to decide what they want to do.

If users do not upgrade their Python installation, they will remain on 0.5.1, pip/conda won't let them upgrade. When they decide to upgrade, they can have the 0.6.0 releases.

@bthirion and I await your input @GaelVaroquaux

**Comment by GaelVaroquaux** [comment]
> Nilearn master should drop Python 2, 3.4 support after the 0.5.1 release. I can fix the multitude of warnings in the CI.

We cannot drop for a minor release. We need to drop before release 0.6.

**Comment by kchawla-pi** [comment]
That's what I am saying we drop after releasing 0.5.1 so that 0.6.0 will not support the older pythons.

**Comment by GaelVaroquaux** [comment]
> That's what I am saying we drop after releasing 0.5.1 so that 0.6.0 will not support the older pythons.

Yes. But do you think that it's very useful to do it right after 0.5.1?
What are the arguments in favor?

**Comment by kchawla-pi** [comment]
We spoke about removing all the warnings from the CI as a cleanup. I also think it will be ease debugging during the sprint not to have all the warnings.

I tried removing two frequent warnings, but that can't be done on Python 2.7, 3.4, because the dependency versions generating them need the older python and are not supported by newer pythons.

**Comment by kchawla-pi** [comment]
This came up in PRs #1946 , #1947

**Comment by GaelVaroquaux** [comment]
OK, point taken.

+1 for dropping after the 0.5.1 release.

**Comment by kchawla-pi** [comment]
I do have one concern. 
While I will create a new branch to maintain a copy of 0.5.1, this is a new scenario for me:
If a bug pops up in 0.5.1, after we have dropped support, how will we fix that?

**Comment by kchawla-pi** [comment]
Do we fix it in the next release, as per usual, and tell users to upgrade their python? (which I think is reasonable) or something else?

**Comment by GaelVaroquaux** [comment]
> I do have one concern.
> While I will create a new branch to maintain a copy of 0.5.1, this is a new
> scenario for me:
> If a bug pops up in 0.5.1, after we have dropped support, how will we fix that?

Yes indeed, and this is why I was not in a hurry to drop Python 2.7
support.

**Comment by kchawla-pi** [comment]
Whenever we do decide to drop it, this will be a factor.
Should we put the fix warnings quest on hold for now?

**Comment by NicolasGensollen** [comment]
Hasn't this been addressed in #2214 ?
see also #2213

**Comment by bthirion** [comment]
Indeed. I close it.
