### ISSUE TITLE
titles in interactive surface plots?

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#1958]
we can
- put the title in the plotly plot: pros: the title is in the plot, it appears when you download the png image, cons: it requires upgrading our plotly version if we want fine control over its position to avoid wasting a lot of space in the plot, causing a large diff

![newplot (1)](https://user-images.githubusercontent.com/9196501/55484033-0b504000-5628-11e9-927b-20c236702918.png)

- put it in the html page on top of the plot

**Comment by kchawla-pi** [comment]
I vote for Title in image.

We can first merge a separate PR to upgrade plotly and then a second PR for these changes

**Comment by bthirion** [comment]
But even in your example the colorbar is huge wrt the image. Can this be changed ?

**Comment by jeromedockes** [comment]
> Can this be changed ?

yes you're right. I've just added that to #1951 

https://github.com/nilearn/nilearn/pull/1951#issuecomment-480342353

**Comment by jeromedockes** [comment]
closed by #2084
