### ISSUE TITLE
Improving CircleCI for Sprint- Hide unrelated warnings, use multiple cores etc

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1965]
For the upcoming spring, a number of improvements in CircleCI will help in easier debugging.

Changes proposed:
 - Add JUnit.XML for chaseable traceback links.
 - Use the new features of upgraded Sphinx-Gallery  by virtue of PR #1964 to enable use of multiple CPU cores.
- Temporarily, for the duration of this sprint, prevent Warnings unrelated to Sphinx from being displayed to make it easier to track documentation build errors. This setting will be reverted after the sprint.

**Comment by thomasbazeille** [comment]
Close ?
