### ISSUE TITLE
Improving/replacing examples with less compute heavy ones

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1966]
Currently many examples in Nilearn are very compute & time heavy. Replacing them with better ones should be a priority.
Eventually I will add proper time metrics about duration each example took to complete, meanwhile here is one I felt took a while. 

`plot_mixed_gambles_space_net.py` in `examples/02_decoding`

Will update this.
Update: Seems all examples in /02_decoding are heavy.

**Comment by thomasbazeille** [comment]
Can be closed
