### ISSUE TITLE
Quick build on CIrcleCI is not updating changes in documentation,

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#1984]
Example , PR #1979

**Comment by NicolasGensollen** [comment]
@kchawla-pi I'm not sure I understand what you meant but I think this is not the case anymore.
Could you confirm so that we can close this. 
Thanks!

**Comment by ymzayek** [comment]
I don't think this is still an issue. Has anyone run into it recently? Otherwise I will close this.
