### ISSUE TITLE
Consolidating functional connectivity examples: merge 8.4.1 and 8.4.7

### ISSUE THREAD

**Issue by illdopejake** [nilearn/nilearn#1986]
Some of the current nilearn examples include some redundancy that creates unnecessary burden for test run-times. 

An example of this would be [8.4.1](https://nilearn.github.io/auto_examples/03_connectivity/plot_canica_resting_state.html#sphx-glr-auto-examples-03-connectivity-plot-canica-resting-state-py) (Group analysis of resting-state fMRI with ICA: CanICA) and [8.4.7](https://nilearn.github.io/auto_examples/03_connectivity/plot_compare_resting_state_decomposition.html#sphx-glr-auto-examples-03-connectivity-plot-compare-resting-state-decomposition-py) (Dictionary Learning and ICA for doing group analysis of resting-state fMRI), which contain a good deal of redundancy.

The goal here would be to create a single example that combines the non-redundant elements from both 8.4.1 and 8.4.7., and perhaps modifying the didactic structure such that it might better reflect the goals and thought-process of an end user.

**Comment by illdopejake** [comment]
As recommended by @KamalakerDadi , would also be useful to merge [8.4.8](https://nilearn.github.io/auto_examples/03_connectivity/plot_sphere_based_connectome.html#sphx-glr-auto-examples-03-connectivity-plot-sphere-based-connectome-py) (Extract signals on spheres from an atlas and plot a connectome) and [8.4.11](https://nilearn.github.io/auto_examples/03_connectivity/plot_multi_subject_connectome.html#sphx-glr-auto-examples-03-connectivity-plot-multi-subject-connectome-py) (Group Sparse inverse covariance for multi-subject connectome) into one notebook with both spheres and a full atlas.

So for reference:
* 8.4.1 + 8.4.7
* 8.4.8 + 8.4.11

 @kchawla-pi

**Comment by emdupre** [comment]
This looks like it was closed with #2013.

**Comment by KamalakerDadi** [comment]
I think #2013 is missing status on whats_new. I was looking for plot_canica_analysis example to work on my PR #1890 and realized lately that it is merged into plot_compare_decomposition. There is no mention of this in whats_new.

**Comment by emdupre** [comment]
Should we open a new PR specifically for that or do you want to handle it in #1890, @KamalakerDadi ?

**Comment by KamalakerDadi** [comment]
>Should we open a new PR specifically for that or do you want to handle it in #1890, @KamalakerDadi ?

I think you followed it better than me.

**Comment by emdupre** [comment]
Opened #2183 , if you'd like to review @KamalakerDadi ! :smile_cat:

**Comment by KamalakerDadi** [comment]
>Opened #2183 , if you'd like to review @KamalakerDadi !

Thanks!
