### ISSUE TITLE
globbing does not work with nilearn.surface.load_surf_data

### ISSUE THREAD

**Issue by SylvainTakerkart** [nilearn/nilearn#1989]
Hi folks,

I just noticed that globbing does not work with load_surf_data, i.e load_surf_data('*.gii') results in the following error:

FileNotFoundError: No such file or no access: '*.gii'

**Comment by juhuntenburg** [comment]
On it

**Comment by emdupre** [comment]
I believe this was closed with #2026.

**Comment by emdupre** [comment]
Closing this, but please re-open if it's not in-fact handled, now !
