### ISSUE TITLE
problem with setup.py: some dependencies are not installed by pip

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#1993]
pip install . in a fresh environment does not install dependencies

**Comment by KamalakerDadi** [comment]
Isn't it dependencies should be installed first ?

**Comment by kchawla-pi** [comment]
It should install the packages listed in install requires

**Comment by jeromedockes** [comment]
> It should install the packages listed in install requires

yes, there may be some issue with loading of _VERSION_GLOBALS

**Comment by kchawla-pi** [comment]
I installed it in a clean environment.
```
(nilearn-py37-test) kshitij@kshitij-dell-7490-linux:~/workspace/nilearn-org/nilearn-repo/kchawla-pi/nilearn$ pip install .
Processing /home/kshitij/workspace/nilearn-org/nilearn-repo/kchawla-pi/nilearn
Collecting nibabel>=2.0.2 (from nilearn==0.5.1)
  Using cached https://files.pythonhosted.org/packages/93/ed/35768f663a361030233a2357de0a482ea46e246af4fc9817dcd5273ee3a7/nibabel-2.4.0-py3-none-any.whl
Collecting numpy>=1.8 (from nibabel>=2.0.2->nilearn==0.5.1)
  Using cached https://files.pythonhosted.org/packages/91/e7/6c780e612d245cca62bc3ba8e263038f7c144a96a54f877f3714a0e8427e/numpy-1.16.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting six>=1.3 (from nibabel>=2.0.2->nilearn==0.5.1)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Building wheels for collected packages: nilearn
  Building wheel for nilearn (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-y2fsg2y0/wheels/2e/b3/a5/3303bb78bc33c3b75b694852ed8939deda2c5eb8763cdc81ee
Successfully built nilearn
Installing collected packages: numpy, six, nibabel, nilearn
Successfully installed nibabel-2.4.0 nilearn-0.5.1 numpy-1.16.2 six-1.12.0
```
scikit-learn, scipy are not getting installed!

**Comment by kchawla-pi** [comment]
Nistats installs all packages listed in `REQUIRED_MODULE_METADAT` and Nilearn does not.
Is that what you mean @jeromedockes ?

If so this is not a new thing, the same thing happened if I install `nilearn==0.4`.

**Comment by jeromedockes** [comment]
> scikit-learn, scipy are not getting installed!

yes this is what I mean. scikit-learn and scipy should be required, I think the only optional dependency is matplotlib

**Comment by kchawla-pi** [comment]
I agree. This broke a while ago. I'll see if I can fix it in the Sprint.

**Comment by KamalakerDadi** [comment]
I don't understand the word broken. This is never implemented to be broken FYI. or May be I am wrong.

**Comment by kchawla-pi** [comment]
The way its supposed to work with Python packages is that the stuff listed in required modules is how pip knows the necessary dependencies.
If its not working here, then I would say setup is broken.

**Comment by jeromedockes** [comment]
> I don't understand the word broken. This is never implemented to be broken FYI. or May be I am wrong.

sorry about poor wording. rephrased the title

**Comment by KamalakerDadi** [comment]
Thanks @jeromedockes

**Comment by jeromedockes** [comment]
@kchawla-pi
