### ISSUE TITLE
Remove Python 2 strings

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2008]
Sphinx latest versions do not support them, they also generate warnings.

**Comment by GaelVaroquaux** [comment]
> Sphinx latest versions do not support them, they also generate warnings.

Well, I think that this issue should be "remove Python 2" :)

**Comment by kchawla-pi** [comment]
Haha. Thats a longer goal. I will first remove python 2 stuff that crashes new versions of packages. :-)

**Comment by bthirion** [comment]
Solved AFAIK.
