### ISSUE TITLE
Decoding object

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#201]
We need a high-level decoding object, that exposes standard strategies, such as SVC, Ridge (with optional feature screening, and integrated parameter selection).

@schwarty : I believe that you have prototyping code that goes in this direction, maybe we can look at that in detail at the sprint.

**Comment by KamalakerDadi** [comment]
Should be addressed by #2000

**Comment by thomasbazeille** [comment]
Can be closed thanks to #2000

**Comment by jeromedockes** [comment]
thanks a lot @thomasbazeille for tracking down all the stale issues!
