### ISSUE TITLE
Deprecate fetch_nyu_rest

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#2020]
This dataset is not preprocessed, and it leads to people doing mistakes. We don't use it in our examples. We should deprecate it.

Related to #330

**Comment by GaelVaroquaux** [comment]
Anyone watching the repo interesting in working on this one? It's an easy one.

**Comment by emdupre** [comment]
Maybe @danjgale would be interested ?

**Comment by danjgale** [comment]
Thanks for the tag @emdupre. Pretty swamped right now, but I *am* interested. Just not sure what kind of timeline I can give for it

**Comment by GaelVaroquaux** [comment]
> Thanks for the tag @emdupre. Pretty swamped right now, but I am interested.

No huge hurry!

Thanks a lot!
