### ISSUE TITLE
intersect_mask: use greater or equal than sign instead of calculating threshold

### ISSUE THREAD

**Issue by JohannesWiesner** [nilearn/nilearn#2050]
In `intersect_masks` function `threshold = min(threshold, 1 - 1.e-7)` is used to calculate a new threshold. I don't know if I oversee something here (e.g. performance related reasons) but could one not just leave this away and change the comparison operator in `grp_mask = grp_mask > (threshold * len(list(mask_imgs)))` to `grp_mask = grp_mask >= (threshold * len(list(mask_imgs)))`? The output would be the same but it would make the code a little bit more readable (and as I find more logic than setting a threshold which is just slightly smaller than the provided threshold and then using the > operator.

**Comment by JohannesWiesner** [comment]
I realized that the function is supposed to be also used with non-binary-masks as input so one cannot use my suggested changes. However I still find the code not straight forward to read (especially the line `threshold = min(threshold, 1 - 1.e-7`). Another way of doing it (using if-else-statements) would be:

```
if threshold == 1:
    grp_mask = grp_mask == len(list(mask_imgs))
elif threshold == 0:
    grp_mask = grp_mask > 0
else:
    grp_mask = grp_mask > (threshold * len(list(mask_imgs)))
```

**Comment by bthirion** [comment]
I think I'm fine with such a change. You can submit a PR...

**Comment by GaelVaroquaux** [comment]
> (and as I find more logic than setting a threshold which is just slightly smaller than the provided threshold and then using the > operator.

Well, to me, a typical use of this function would be to give is 0 as a
threshold. So, in this respect, it makes more sense to use strictly
greater than ( > ). Using greater or equal would be awkward.
