### ISSUE TITLE
nilearn resample_img output pixel dimension mismatch

### ISSUE THREAD

**Issue by TinaWuUW** [nilearn/nilearn#2053]
When I attempted to upsample my nii mask to match my original scan, an issue would occur where I can see the image spacing parameter changing in 3d Slicer (as well as the pixel dimension in the upsampled mask header file). But once I port my mask into Amira, the voxel size would become 1x1x1 regardless of the pixel dimension/image spacing parameter. 

I've also tried using resample_to_image(mask, original_scan), but the result is the same (expected).

Just wondering if anyone has thoughts on this. Thanks!

Update: all pixels would disappear in the mask that I want to upsample even with proper transforms to match the origins between the mask and the original scan.

**Comment by jeromedockes** [comment]
thanks!
could you provide a small code snippet and the images to reproduce your problem?

**Comment by Remi-Gau** [comment]
@TinaWuUW
I am closing this issue since we have not heard back, but if you encounter this problem again feel free to reopen the issue.
