### ISSUE TITLE
Plot title overlays the image

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2054]
Currently adding a title to a plot results in the title being drawn over the image, especially prominent if the title is long:

![image](https://user-images.githubusercontent.com/8203204/57656689-6dae4000-75d9-11e9-90be-3e2d21486f67.png)

Ideally, there should be a space between the title and the image below that.

**Comment by mjboos** [comment]
That's indeed a bit annoying.
In `BaseSlicer` a title is added as just a text box, which makes it impossible to use matplotlib functionality like `tight_layout` to automatically adjust the subplots.
I can see two options to fix that: either add it as a title to the plot, then use `tight_layout` or check in the `title`function for the size of the created text and use `subplots_adjust` to shift the rest of the axes.
There are potentially some deep reasons that I couldn't glance from the code in `BaseSlicer` that prohibit using a title directly, but I can the first option a try in the next couple of days, and if it breaks revert to the second one.

**Comment by OliverWarrington** [comment]
I'd like to have a go at this please! Can I ask if there was any reason that prohibits using a title directly (mentioned above)?

**Comment by jeromedockes** [comment]
note the axes in which brains are shown don't provide `get_subplotspec` so `tight_layout` will show a warning and probably not work

**Comment by OliverWarrington** [comment]
In the title function of the BaseSlicer class, which object is the right one to be trying to call subplots_adjust for? Or alternatively, can we just increase the figure size if there is a title, like you do for the colourbar?
