### ISSUE TITLE
Incorrect word in manipulating_images documentation

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2058]
In http://nilearn.github.io/manipulating_images/manipulating_images.html

There is a line: `Smoothing: Before a statistical test, it is often use to smooth a bit the image using nilearn.image.smooth_img, typically fwhm=6 for fMRI.z`

I believe it should be `...it is often useful to smooth...`.

**Comment by reiningc** [comment]
I can clean this up!
