### ISSUE TITLE
Add a See Also section to plotting.plot_img 

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2062]
**Original Title:** plotting.plot_img should be a private function

`plotting.plot_img` is not supposed to be directly called by users and should be a private function.

What version of Nilearn are you using?
Master, 0.5.2

What were you trying to do?
Used `plotting.plot_img` like I do `plotting.view_img`

What did you expect will happen?
That instead of an interactive view, I'll get a same looking static image.

What actually happened?
The image had no background.

**Comment by bthirion** [comment]
I think that it depends on what you want to do. 
If you are looking at raw MRI data you certainly don't want a background.

**Comment by jeromedockes** [comment]
In this case wouldn't you use either `plot_anat` or `plot_epi` depending on the type of data?

**Comment by kchawla-pi** [comment]
We need a ruling on this one.

**Comment by jeromedockes** [comment]
`plot_img` is used directly in a couple of examples:

02_decoding/plot_haxby_searchlight.py
plot_nilearn_101.py

that would make it a public function. but we could add a line to the docstring stating that it is a rather low-level one and for most usecases other functions might be easier to use, with a `see also` section pointing to plot_stat_map, plot_anat, and so on

**Comment by bthirion** [comment]
Maybe the see also thing is sufficient. i'm worried of trying to issue complicated messages in docstrings.
