### ISSUE TITLE
How to add new surface views?

### ISSUE THREAD

**Issue by felenitaribeiro** [nilearn/nilearn#2066]
Hey guys, 
I've been using nilearn to make some plots of retinotopic maps, and my ROIs includes the occipital pole and part of the temporal and parietal cortex.  The views provided ({'lateral', 'medial', 'dorsal', 'ventral', 'anterior', 'posterior'}) only include part of the ROIs on the spherical surface, so I have make several plots to see all ROIs. 
So, it would be really helpful to be able to change the coordinates of the views in order to plot all my ROIs in only one figure, enabling easy comparisons of those maps across subjects. Is there a simple way to change those views?

**Comment by bthirion** [comment]
Yes, you can probably tweak the code in 
https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/surf_plotting.py
changing the `elev` and `azim` parameters to obtain what you wish to have.
HTH

**Comment by felenitaribeiro** [comment]
Hey, thank you!!!
Also, where could I change the view settings when opening images on the browser? (the ones available are the bottom, top, back, front, left and right)

**Comment by emdupre** [comment]
You might want to add another view here:
https://github.com/nilearn/nilearn/blob/9ab767ec41cad0e41e05854ac3141adfdcb634a3/nilearn/plotting/data/js/surface-plot-utils.js#L78-L97

**Comment by felenitaribeiro** [comment]
Thank you guys!!! I've done changes on both files and everything worked =)
