### ISSUE TITLE
vol_to_surf nearest-neighbour creates new values

### ISSUE THREAD

**Issue by florisvanvugt** [nilearn/nilearn#2068]
Dear nilearn developers,
first of all thank you for developing this wonderful set of tools, which I use so much I can't imagine my life without it anymore!
I am experiencing unexpected output from the `vol_to_surf` function when using nearest neighbour interpolation. Perhaps this is reflecting my lack of understanding.
The issue is that if you feed a nifti image with some discrete set of values and transform it into the surface, the values at the surface vertices are not necessarily in the discrete set of values.
Here is an illustration:

```python
%pylab inline
import nilearn
nilearn.__version__
```
    Populating the interactive namespace from numpy and matplotlib

    '0.5.2'

```python
from nilearn import datasets
motor_images = datasets.fetch_neurovault_motor_task()
stat_img = motor_images.images[0]
```

```python
# Create a discrete version of the stat map 
# (I know, I know, in real life you wouldn't want to do this but this is simply to quickly get a nifti with discrete values)
import nibabel as nib
orig = nib.load(stat_img)
data = orig.get_data()
discr = np.round(data)

# Find the unique values: confirms that this is a nifti with integers only
list(set(discr.flatten()))
```

    [0.0,
     1.0,
     2.0,
     3.0,
     4.0,
     5.0,
     6.0,
     7.0,
     8.0,
     -2.0,
     -8.0,
     -7.0,
     -6.0,
     -5.0,
     -4.0,
     -3.0,
     -1.0]

```python
# Turn back into nifti image and then map to the surface
discr_img = nib.Nifti1Image(discr, orig.affine)
fsaverage = datasets.fetch_surf_fsaverage()
from nilearn import surface
texture = surface.vol_to_surf(discr_img, fsaverage.pial_right,interpolation='nearest')
list(set(texture)) # I expect a discrete set of integers like the list above, but instead I find non-integer values
```

    [0.7,
     0.0,
     2.9000000000000004,
     -0.19999999999999996,
     -0.5,
     2.4000000000000004,
     6.4,
     4.0,
     5.9,
     7.799999999999999,
     1.5,
     8.0,
     -1.9999999999999998,
     2.0,
     1.0,
     0.5,
     3.5,
     2.5,
     3.0,
     4.5,
     1.5000000000000002,
     1.0000000000000002,
     5.0,
     5.5,
     6.5,
     6.0,
     6.600000000000001,
     7.0,
     7.5,
     7.600000000000001,
     2.0000000000000004,
     2.5000000000000004,
     3.0000000000000004,
     3.5000000000000004,
     -2.6000000000000005,
     0.20000000000000007,
     -0.29999999999999993,
     2.7755575615628914e-17,
     0.19999999999999998,
     2.8999999999999995,
     -1.6000000000000003,
     3.8999999999999995,
     -3.6,
     4.8999999999999995,
     -2.1,
     -2.6,
     4.3999999999999995,
     5.8999999999999995,
     -1.6,
     -1.1,
     5.500000000000001,
     5.3999999999999995,
     6.3999999999999995,
     5.000000000000001,
     -0.6000000000000001,
     0.8999999999999999,
     6.000000000000001,
     7.000000000000001,
     7.3999999999999995,
     1.4,
     1.9,
     7.8999999999999995,
     7.500000000000001,
     -1.5999999999999999,
     2.4,
     2.9,
     -1.0999999999999999,
     3.9,
     0.9000000000000001,
     3.4,
     1.4000000000000001,
     -2.0999999999999996,
     1.9000000000000001,
     -2.5999999999999996,
     -0.3,
     0.2,
     5.551115123125783e-17,
     0.09999999999999992,
     -0.4000000000000001,
     -0.10000000000000003,
     1.9000000000000004,
     0.39999999999999997,
     3.9000000000000004,
     3.4000000000000004,
     4.4,
     4.9,
     -2.2000000000000006,
     -2.7000000000000006,
     5.4,
     6.9,
     7.4,
     7.9,
     8.000000000000002,
     -2.2,
     -2.7,
     -1.2000000000000002,
     -1.7000000000000002,
     -2.9,
     -0.1,
     0.20000000000000004,
     1.2999999999999998,
     1.7999999999999998,
     2.8,
     -1.2,
     -1.7,
     2.3,
     3.8,
     0.30000000000000004,
     0.8,
     -0.7,
     3.3,
     4.8,
     1.8,
     1.3,
     -2.6999999999999997,
     4.3,
     5.8,
     -1.6999999999999997,
     5.3,
     -2.1999999999999997,
     6.8,
     6.3,
     7.8,
     7.3,
     1.8000000000000003,
     1.3000000000000003,
     5.700000000000001,
     2.8000000000000003,
     2.3000000000000003,
     3.8000000000000003,
     3.3000000000000003,
     0.9999999999999999,
     -0.5000000000000001,
     -0.4,
     0.7999999999999999,
     0.4,
     0.09999999999999998,
     0.6,
     -0.9,
     -0.7999999999999999,
     0.7000000000000001,
     -0.09999999999999998,
     -0.6,
     -0.9999999999999999,
     2.8000000000000007,
     3.8000000000000007,
     4.300000000000001,
     4.699999999999999,
     4.800000000000001,
     -2.8000000000000003,
     -2.3000000000000003,
     5.800000000000001,
     -1.8000000000000003,
     5.300000000000001,
     5.699999999999999,
     5.199999999999999,
     6.800000000000001,
     6.300000000000001,
     6.199999999999999,
     -1.3000000000000003,
     6.699999999999999,
     7.800000000000001,
     7.699999999999999,
     7.300000000000001,
     7.199999999999999,
     1.6999999999999997,
     -1.8,
     -1.3,
     2.6999999999999997,
     2.1999999999999997,
     3.6999999999999997,
     -0.8,
     -0.30000000000000004,
     3.1999999999999997,
     0.19999999999999996,
     -3.3,
     1.2,
     1.7,
     -2.8,
     -1.7999999999999998,
     -1.2999999999999998,
     0.1,
     -0.20000000000000004,
     0.2000000000000001,
     1.7000000000000002,
     1.2000000000000002,
     2.2,
     2.7,
     3.2,
     3.7,
     4.2,
     4.7,
     5.2,
     5.7,
     6.7,
     6.2,
     7.2,
     7.7,
     0.9,
     2.7000000000000006,
     3.2000000000000006,
     3.7000000000000006,
     -2.4000000000000004,
     -1.4000000000000004,
     -1.9000000000000004,
     0.3,
     -0.2,
     0.10000000000000003,
     0.49999999999999994,
     0.4000000000000001,
     -0.39999999999999997,
     4.700000000000001,
     4.200000000000001,
     -1.4000000000000001,
     2.5999999999999996,
     2.0999999999999996,
     3.5999999999999996,
     -0.9000000000000001,
     3.0999999999999996,
     4.1,
     1.5999999999999999,
     1.0999999999999999,
     4.6,
     -2.4,
     5.200000000000001,
     -1.9,
     -1.4,
     5.1,
     5.6,
     6.6,
     6.1,
     -0.8999999999999999,
     0.6000000000000001,
     6.200000000000001,
     7.200000000000001,
     7.6,
     1.6,
     1.1,
     7.700000000000001,
     7.1,
     2.1,
     2.6,
     3.6,
     3.1,
     1.6000000000000003,
     6.700000000000001,
     -0.19999999999999998,
     -2.7755575615628914e-17,
     -0.7000000000000001,
     0.29999999999999993,
     2.1000000000000005,
     2.6000000000000005,
     3.6000000000000005,
     4.6000000000000005,
     -2.0000000000000004,
     -2.5000000000000004,
     5.6000000000000005,
     5.1000000000000005,
     6.500000000000001,
     6.6000000000000005,
     6.1000000000000005,
     7.6000000000000005,
     7.999999999999999,
     -1.0000000000000002,
     -1.5000000000000002,
     2.9999999999999996,
     2.4999999999999996,
     3.4999999999999996,
     -3.0,
     3.9999999999999996,
     -2.0,
     -1.0,
     -2.5,
     1.9999999999999998,
     1.4999999999999998,
     -1.5,
     -3.4000000000000004,
     -2.3,
     -1.9000000000000001]

This is Python 3.6.

**Comment by jeromedockes** [comment]
hello and thanks a lot!

could you try setting `radius=0.` and `n_samples=1`?
for each node of the mesh, `vol_to_surf` measures the image values at several points around the node (for each point this is done either with "nearest" or "linear" interpolation), then averages the measures: see

  https://nilearn.github.io/auto_examples/01_plotting/plot_surface_projection_strategies.html#sphx-glr-auto-examples-01-plotting-plot-surface-projection-strategies-py

for an illustration. `n_samples` controls the number of measures and `radius`
the size of the region in which samples are drawn. by setting `n_samples` to 1
and `radius` to 0 you should get exactly the value of the voxel in which the
node lies.

**Comment by florisvanvugt** [comment]
That solved it! I had misunderstood the sampling scheme of `vol_to_surf`.
Thanks for your help `jeromedockes`

**Comment by jeromedockes** [comment]
glad to hear this and thanks for using nilearn!
