### ISSUE TITLE
"UserWarning: It seems you have created more than 10 nilearn views." But no way to delete nilearn views

### ISSUE THREAD

**Issue by DM-Berger** [nilearn/nilearn#2074]
When more than 10 _html_view_ objects via `html_view = nilearn.plotting.view_img()` in a loop, you will see the warning:

> UserWarning: It seems you have created more than 10 nilearn views. As each view uses dozens of megabytes of RAM, you might want to delete some of them.

This is a helpful warning, but it doesn't give the user any way to deal with the problem, as there doesn't seem to be any documented way to free the memory associated with these objects. There is also no clean way (besides e.g. https://stackoverflow.com/questions/5644836/in-python-how-does-one-catch-warnings-as-if-they-were-exceptions/30368735) to disable the warning for users that are sure they have sufficient memory, and/or don't wish to have the console spammed.

It is also not clear to me from the [source code](https://github.com/nilearn/nilearn/blob/2df00ffb1826550b9c8e6497c7c67756e2188039/nilearn/plotting/js_plotting_utils.py#L102) how to work around this: I don't seem to be able to call `html_view._all_open_html_repr.clear()` , `html_view._all_open_html_repr.remove()`, `HTMLDocument._all_open_html_repr.clear()` or etc to manually shrink the size of the `WeakRef` object which has the length causing the error message, although this may be due to my lack of familiarity with these objects. 

Any workaround would be appreciated.

**Comment by jeromedockes** [comment]
there are two things that can use some memory: the nilearn views themselves (the python objects), although I don't think these are very big, and the browser windows in which views are displayed, eg if you called `open_in_browser`, which can be quite big for surface plots. for the browser windows, you need to close them manually; nilearn provides no way to do it. for the python objects, as usual, if you don't keep a reference to them they will be garbage collected and you can also explicitly `del` them.

as you said, it is quite easy to silence a particular warning in python with `catch_warnings` or with filters:
https://docs.python.org/3.7/library/warnings.html#the-warnings-filter

but it is true that it would be better to be able to control the number of views that triggers the warning or disable it altogether; I'll open a PR and link it here

thanks!

**Comment by DM-Berger** [comment]
Thank you for the rapid response!

This actually clarifies it a lot. I was concerned that the nilearn python objects might themselves be the memory concern, because I was already just writing the html files and opening them in the browser later, manually. Perhaps the warning could clarify the source of the memory concerns, or, if it is only a concern for the _html_views_ while being viewed in the browser, only warn when there has actually been calls to `open_in_browser`

I've filtered the warnings for now, and your clarification makes me feel confident this is a safe workaround. Thanks for the help!

**Comment by jeromedockes** [comment]
>  Perhaps the warning could clarify the source of the memory concerns, or, if it is only a concern for the _html_views_ while being viewed in the browser, only warn when there has actually been calls to `open_in_browser`

indeed, or to `_repr_html_` which opens them in the jupyter notebooks. we should check memory usage and refine the warning

**Comment by GaelVaroquaux** [comment]
> indeed, or to _repr_html_ which opens them in the jupyter notebooks. we should
> check memory usage and refine the warning

Checking the memory usage might not be that easy.

But improving the warning is overall a good idea!

**Comment by jeromedockes** [comment]
> Checking the memory usage might not be that easy.

I meant offline, to decide what we want to warn about e.g. if the python views themselves are a problem or not.

I was not suggesting trying to figure out how much memory the views are occupying on the user's machine

**Comment by KirstieJane** [comment]
Hi folks - sorry to not understand this thread properly (I'm pretty confident the answer is in here I just haven't followed along :weary:) and please let me know if you'd rather I open a new issue to make it easier to track.

I can see the warning, and I really like the updated warning in #2075...but I don't know how to address the warning if I'm running the visualizations a jupyter notebook. TBH I've just killed the kernel and run the cells again and the warning has gone away (for now!) Is that the best plan? Is there something else I've missed?

**Comment by jeromedockes** [comment]
hello! does it fix the problem if you call `nilearn.plotting.set_max_img_views_before_warning(None)` at the beginning of your notebook?

**Comment by KirstieJane** [comment]
Hi @jeromedockes - sorry for the slow reply, and for not being clear in my question.

I can definitely get rid of the warning, what I meant is that I'm not sure how to deal with the fact that my jupyter notebook is opening a lot of views and therefore using lots of memory! (For context this is a tutorial showing a bunch of different functionality.) Is there a way to close the view?

**Comment by jeromedockes** [comment]
does it help to clear the jupyter cell's output?
especially in the case of the surface views, what takes memory is the browser's rendering, more than the python object themselves.
