### ISSUE TITLE
 TravisCI failing due to Conda not supporting older versions

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2077]
@GaelVaroquaux Similar to https://github.com/nistats/nistats/issues/363 , this problem is surfacing in Nilearn as well.The default conda channel no longer supports `scipy==0.17` and `scikit-learn==0.18`. To keep things simple for users, should we bump up the minimum supported versions. Or only address this in the CIs by switching channels or switch to `pip` instead of `conda`?

**Comment by GaelVaroquaux** [comment]
OK, let's do it!
