### ISSUE TITLE
How to add contours/overlays on surface plot

### ISSUE THREAD

**Issue by kshitijd20** [nilearn/nilearn#2085]
Is there a function like display.add_overlay() to add overlay or contours on surface plots?

**Comment by bthirion** [comment]
Not as far as I know.

**Comment by kshitijd20** [comment]
Thanks for the reply. Can you please provide me some idea of how I can implement it on my own? I was looking at the surface plotting code and add_contour function. So my naive idea is to transform the ROI img to surface and write a _map_show() function to add either contour or overlay on top of surface stat map?

**Comment by jeromedockes** [comment]
are you using `plot_surf_stat_map` or `view_surf`?

it may be worth trying out a tool that is more focused on surface plots than nilearn, such as pysurfer:

https://pysurfer.github.io/

**Comment by kshitijd20** [comment]
I am using `plot_surf_stat_map`. Thanks for the link, I will check that out.

**Comment by jeromedockes** [comment]
I think overlays on surface plots will not be implemented any time soon in nilearn so closing this
