### ISSUE TITLE
DocError: plot_stat_map( bg_img=None)

### ISSUE THREAD

**Issue by mandelkow** [nilearn/nilearn#2087]
https://nilearn.github.io/modules/generated/nilearn.plotting.plot_stat_map.html

To turn off background image, just pass “bg_img=False”.
...should probably read bg_img=None

Cheers, H.

**Comment by jeromedockes** [comment]
thanks! you're right. do you want to open a Pull Request?

**Comment by GaelVaroquaux** [comment]
> https://nilearn.github.io/modules/generated/nilearn.plotting.plot_stat_map.html

> To turn off background image, just pass “bg_img=False”.
> ...should probably read bg_img=None

Did you check? I am not convinced.

**Comment by jeromedockes** [comment]
yes i checked, `False` results in a `TypeError` and `None` gives the expected result
