### ISSUE TITLE
Simplifying CI test setup & execution

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2093]
Hey @GaelVaroquaux @jeromedockes 
I noticed that our `continuous_intergation\install.sh`, and `makefile` have tons of condition checks & options that I have not seen being used in the past one year.

For example, in the `makefile`, the `test-coverage` are not invoked in any of the CIs.

In the `install.sh`, we never test on Neurodebian containers. Maybe the Neurodebian folks use this but considering all the breaking changes we have made in the background regarding conda etc and they never filed an issue, I don't think it is infact used.

I propose we do a careful combination of update, simplify, & remove the parts that are currently vestigial. The sections that are or can be useful should be updated, the ones that have been superseded should be removed. 

The configs have been adopted from scikit-learn, however, nilearn does not do as complex a CI as they do. It would make sense to either adopt their practices if we need them or remove the unused ones.

**Comment by Remi-Gau** [comment]
Unless I am mistaken this issue has become obsolete and can now be closed

**Comment by bthirion** [comment]
Indeed, thx.
