### ISSUE TITLE
nilearn.image.smooth_img fails if fwhm is an ndarray

### ISSUE THREAD

**Issue by pausz** [nilearn/nilearn#2099]
nilearn.image.smooth_image fails if fwhm is a numpy.ndarray

##### What version of Nilearn are you using?
+ 0.5.0
+ master branch e3082d8

##### What were you trying to do?
Smoothing an image with different widths along each of the spatial axes. 

##### What did you expect will happen?
to work as per the reference documentation.

##### What actually happened?
Fails with a `ValueError` because the [first check in `_smooth_array()`](https://github.com/nilearn/nilearn/blob/master/nilearn/image/image.py#L189) essentially compares a scalar to an ndarray. 

A different behaviour arises if `fwhm` is specified as a numpy ndarray with one element: There is a `FutureWarning` coming from a comparison between 
an ndarray and a string in [line 208 of image.py](https://github.com/nilearn/nilearn/blob/master/nilearn/image/image.py#L208).

##### Steps to rperoduce the bug

The steps necessary to reproduce the `FutureWarning` and `ValueError` are detailed below.

```
~/Work/Code/Python/fmriprep_sandbox/nilearn (master)
└─ 
$ ☻ ▶ ipython
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

```

```python
In [1]: import nilearn as nl

In [2]: nl.__version__
Out[2]: '0.5.0'

In [3]: import nilearn.image as nl_img

In [4]: imgs = nl_img.load_img('sub-001_task-run1_space-MNI152NLin6Asym_desc-preproc_bold_confounds-removed.nii.gz')

In [5]: smoothed_img = nl_img.smooth_img(imgs, fwhm=5)   

In [6]: import numpy as np

In [7]: smoothed_img = nl_img.smooth_img(imgs, fwhm=np.array([1.]))   
/home/paula/.local/lib/python3.7/site-packages/nilearn/image/image.py:208: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if fwhm == 'fast':

In [8]: smoothed_img = nl_img.smooth_img(imgs, fwhm=np.array([1., 2.5, 4.2]))   
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-fb6ccd266709> in <module>()
----> 1 smoothed_img = nl_img.smooth_img(imgs, fwhm=np.array([1., 2.5, 4.2]))

~/.local/lib/python3.7/site-packages/nilearn/image/image.py in smooth_img(imgs, fwhm)
    268         affine = img.affine
    269         filtered = _smooth_array(img.get_data(), affine, fwhm=fwhm,
--> 270                                  ensure_finite=True, copy=True)
    271         ret.append(new_img_like(img, filtered, affine, copy_header=True))
    272 

~/.local/lib/python3.7/site-packages/nilearn/image/image.py in _smooth_array(arr, affine, fwhm, ensure_finite, copy)
    187     # Here, we have to investigate use cases of fwhm. Particularly, if fwhm=0.
    188     # See issue #1537
--> 189     if fwhm == 0.:
    190         warnings.warn("The parameter 'fwhm' for smoothing is specified "
    191                       "as {0}. Converting to None (no smoothing option)"

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

``` 

## Fix

My branch [`fix-smooth-image`](https://github.com/pausz/nilearn/tree/fix-smooth-image) resolves the issues described above and also extends the behaviour of `smooth_image` by allowing `fwhm` to be a a numpy's ndarray with zeros or Nones -- in which case smoothing is not performed along that dimension. 

Note that in test_image.py, the ndarray mentioned in the documentation was not actually tested. 
The closest matching test for an ndarray is when [`fwhm` has been specified as a Python tuple](https://github.com/nilearn/nilearn/blob/master/nilearn/image/tests/test_image.py#L151).

The changes in this PR also handle the case for when `fwhm` is specified as a tuple or a list. 

Other considerations:

I did not run test_image.py. However, I did test following the same steps describe in the code block provided above, for the following values and types of `fwhm`: 

+ fwhm = 1
+ fwhm = 1.0
+ fwhm = 0
+ fwhm = np.array([1.0, None, 8.0])
+ fwhm = np.array([1.0])
+ fwhm = np.array([1.0, 0.0, 8.0])
+ fwhm = [1.0, None, 8.0]
+ fwhm = (1.0, None, 8.0)
+ fwhm = (1.0, 0.0, 8.0)
+ fwhm = (1.0)
+ fwhm = (0.0)
+ fwhm = (None)
+ fwhm = None

Let me know if these changes are suitable and I'll send the corresponding pull request :)

**Comment by kchawla-pi** [comment]
Hi @pausz , thank you so much for helping us! I haven't reviewed the changes but it would be easier to do so in a pull request. Would you please open one?

**Comment by pausz** [comment]
@kchawla-pi Sent PR #2107!

**Comment by kchawla-pi** [comment]
Thanks Paula! ANd Thanks for the super detailed issue you filed. It always helps so much!

**Comment by thomasbazeille** [comment]
PR merged, can be closed
