### ISSUE TITLE
Remove Python2 compatibility shims

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2105]
Remove the code that is present to maintain interop & compatibility with Python2.

**Comment by jeromedockes** [comment]
We should not worry about python 2 features but I'm not sure we should actively try to break any python 2 client code that survived until now?

**Comment by kchawla-pi** [comment]
Python3 does a lot of stuff neater and cleaner than Python2. On their own they are small things but additively they improve a code base a lot. Removing the shims will make existing code better.
The new versions of Nilearn already fail in a python2 environment, so there is no interop to maintain anymore.

I may not jump on this right away, but at some point we should proactively do this.

**Comment by GaelVaroquaux** [comment]
> Python3 does a lot of stuff neater and cleaner than Python2. On their own they
> are small things but additively they improve a code base a lot. Removing the
> shims will make existing code better.

+1 for, at some point, removing the shims and using more elegant
solutions.

However, let us not rush: these will make backport fixes for bugfix
releases harder.

**Comment by kchawla-pi** [comment]
Oh totally. Not until we have 0.6.0 out as a stable release for  several months.

**Comment by Remi-Gau** [comment]
Doing more [cleaning](https://github.com/nilearn/nilearn/issues/2528) I am coming across the external/tempita.

Unless I am mistaken there is some code for python 2 compatibility in there.

https://github.com/nilearn/nilearn/blob/main/nilearn/externals/tempita/compat3.py

Is it ok to remove it that compatibility code? 

Or should the external directly be omitted from the black / flake 8 formatting as it may contain bundled external dependency?

Pinging @emdupre as git blame is telling she is the last one to have worked on this.

**Comment by kchawla-pi** [comment]
Since Tempita is not our library, we are vendoring it, i opine it should
not be changed by us for non-critical reasons. If we change it, it should
typically only be to vendor a newer version.

I suggest excluding it from the linter & formats, but not automated
security audits.

**Comment by Remi-Gau** [comment]
That makes sense to me.

**Comment by emdupre** [comment]
+1 to @kchawla-pi 's points !

If you think we need to update the vendored version for reporting template functionality, that makes sense to me. Otherwise I'd likely keep as is !

**Comment by Remi-Gau** [comment]
AFAICT no need to update. :-)

**Comment by Remi-Gau** [comment]
Does it make sense to keep this issue open?

**Comment by ymzayek** [comment]
I think it's safe to close
