### ISSUE TITLE
abc imported from collections

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2108]
abcs like `Iterable`, `Mapping`, `Sequence` are currently imported from `collections`, but this is deprecated and they should be imported from `collections.abc`

this was changed in python 3.3 so I guess we could go ahead and simply change the imports without importing from `_utils.compat`, although I would still recommend the usual `compat` scheme

**Comment by kchawla-pi** [comment]
I would like to do it.
Curious why `_utils.compat`? Aren't we trying to remove old python compatibility code?
If this has been part of stdlib since 3.3, I think we should directly import it.

**Comment by kchawla-pi** [comment]
If you wanted to work on this @jeromedockes that's fine as well, tell me here & I'll unassign myself.

**Comment by jeromedockes** [comment]
> If you wanted to work on this @jeromedockes that's fine as well, tell me here & I'll unassign myself.

please go ahead! I haven't started anything

**Comment by jeromedockes** [comment]
> Curious why `_utils.compat`? Aren't we trying to remove old python compatibility code?
> If this has been part of stdlib since 3.3, I think we should directly import it.

that is a valid point of view. I was just thinking that although we don't officially support python2, whenever it is easy we can still avoid breaking python2 code that still runs using nilearn, as I expect there is a bunch.

**Comment by kchawla-pi** [comment]
I believe we have already merged changes into master that break in python < 3.5.
Regardless, we were discussing about removing the shims. Either way we should commit, else  we cannot benefit from Python3's more concise syntax, better error classes, etc.

**Comment by jeromedockes** [comment]
> I believe we have already merged changes into master that break in python < 3.5.

yes that is the case

**Comment by KamalakerDadi** [comment]
Solved by #1898
