### ISSUE TITLE
Implement caching in nilearn.mass_univariate.permuted_ols

### ISSUE THREAD

**Issue by JohannesWiesner** [nilearn/nilearn#2111]
Are there any plans to implement caching in `nilearn.mass_univariate.permuted_ols`? I run this function with a high number of permutations and it would be great if caching would be available for this function to get quicker results (just like for `NiftiMasker` e.g.).

**Comment by jeromedockes** [comment]
I'm not sure but since it is a function you can easily cache it with joblib
```python
from joblib import Memory
mem = Memory("my_cache_dir")
mem.cache(permuted_ols)(*args)
```
