### ISSUE TITLE
view_img percentile threshold behavior is a bit confusing

### ISSUE THREAD

**Issue by ejolly** [nilearn/nilearn#2112]
A pretty common workflow in nilearn is to use the `NiftiMasker` with a brain mask, perform some operations on the 2d numpy array, put the resulting stats back in brain space using `masker.inverse_transform` and visualize them with a plotting function.

In this workflow, I was surprised about the behavior of the `threshold` argument to `view_img` specifically when threshold _is a percentile string_. 

Specifically, if a user specifies threshold as a percentile string, the percentile is computed with respect to _every value in the image_. More often than not, much of the entire 3d image space contains non-brain voxels (0s) and using these values to compute the percentile threshold has the effect of computing a _much lower cutoff_ than the same percentile over in-brain voxels. If a user instead specifies an integer/float threshold (e.g. a t-statistic) they wouldn't ever encounter this behavior. 

Is there a use case for computing a percentile threshold over the entire image? 
Otherwise one possibility is the addition of an optional mask argument specifically for what voxels to use to compute the percentile thresholds. 

It seems confusing because when one is typically specifying a threshold, they're thinking about _voxel values_ not _values across the entire image_. 

Sorry if this is noted more clearly somewhere and I missed it! The docstring is accurate but it still seems confusing if one doesn't remember that image != brain image with respect to the percentile calculation

Here's a jupyter notebook demonstrating this using the MNI template in nilearn as mock data: 
https://nbviewer.jupyter.org/urls/dl.dropbox.com/s/8bqpj7l1f9e5pio/view_img_percentile_thresholding.ipynb

Perhaps related to https://github.com/nilearn/nilearn/issues/2061

Nilearn version 0.5.2

**Comment by jeromedockes** [comment]
thanks! 
you are right that computing the percentile inside a brain mask would make more sense. 

however the plotting functions don't need a mask image for anything else, and I'm not sure it is worth adding a parameter just for this; the percentile string is meant to effortlessly guess a more or less reasonable value for visualization without any particular statistical meaning.
I guess we could also use the background image as a mask

of course it would be better to call fast_abs_percentile on the output of a niftimasker. I don't know if this will change in nilearn but in the meanwhile if the user code has the mask image I guess you could compute the percentile on the masked data and pass it as a float

**Comment by jeromedockes** [comment]
I don't think nilearn will adress this so closing for now
