### ISSUE TITLE
plotting.plot_matrix savefig

### ISSUE THREAD

**Issue by Xin-cqu** [nilearn/nilearn#2114]
When I was trying to save figure from plotting.plot_matrix function, it appeared that no savefig function was called and the error information is below:
![1](https://user-images.githubusercontent.com/5805124/62222305-b6f67a80-b3e5-11e9-8d70-b2ae4940ab1c.png)

How could I save the figure from this function?

**Comment by Xin-cqu** [comment]
just in case that the figure won't show up, the detailed code and corresponding message is:
`from nilearn import plotting

title = "resting state"
display = plotting.plot_matrix(rs, colorbar=True)
display.savefig('rs.tif',dpi=300)                               
plotting.show()
                  `
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-56-d62fae50d333> in <module>
      3 title = "resting state"
      4 display = plotting.plot_matrix(rs, colorbar=True)
----> 5 display.savefig('rs.tif',dpi=300)
      6 plotting.show()
      7 

AttributeError: 'AxesImage' object has no attribute 'savefig'`

**Comment by kchawla-pi** [comment]
Try `display.figure.savefig()`

**Comment by kchawla-pi** [comment]
Questions like these are best posted on neurostars.org with the tag `nilearn` added to them. The Issue tracker is strictly for reporting bugs and making feature requests.

**Comment by Xin-cqu** [comment]
@kchawla-pi Thanks for your help and sorry for display questions in wrong place. This issue is closed.

**Comment by kchawla-pi** [comment]
You're most welcome @Xin-cqu , we would love to help, this separation is helpful for easier organization for the developers.
Did `display.figure.savefig()` work?

**Comment by Xin-cqu** [comment]
@kchawla-pi Yes, your advise worked and help me with a emergence issue. Again, thx! :)

**Comment by hfxcarl** [comment]
The solution provided by @kchawla-pi to use display.figure.savefig() worked for me. But only after I arrived here and had already spent considerable time trying to figure out this issue. Complicating this are several similar functions from nilearn where disp.savefig() works directly without adding the .figure. in the middle, for example:
```from nilearn import plotting
disp=plotting.plot_connectome(corr_matrix,dmn_coords,title='DMN connectivity')
disp.savefig('dmn_connectome_plot.png')
plotting.show()
```
It would be nice if all plotting functions returned objects with the same savefig() function.

**Comment by NicolasGensollen** [comment]
Hi @hfxcarl 
Most plotting functions in nilearn (like `plot_connectome`) returns a figure (or "figure-like") object with a `savefig` method. However, for a reason I don't know, the matrix plotting functions like `plot_matrix` return an `Axes` instance (except `plot_event` which returns a figure...). 

I agree with you that consistency across nilearn plotting functions would be easier for users. @bthirion @jeromedockes do you know if there is a reason for these differences?

Note that you can pass a figure object to `plot_matrix`, which might be more convenient:

```python
import numpy as np
import matplotlib.pyplot as plt
from nilearn.plotting import plot_matrix

fig = plt.figure(figsize=(10,10))
data = np.random.random((100,100))
display = plot_matrix(data, figure=fig) # display is an axes
fig.savefig('matrix.png') # use fig to save output
```

**Comment by bthirion** [comment]
No, it's historical. It would be great to offer a more uniform API.

**Comment by NicolasGensollen** [comment]
OK, I'll open a new dedicated issue then!
