### ISSUE TITLE
Handling Conda's unreliability

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2115]
Conda, much as I like it as an end user, has been a source of difficulties recently. #2077 #2079 
They suddenly dropped support for older versions of packages, which prompted me to suggest upgrading our minimum supported versions of Scikit-learn, Scipy to 0.19. However, with each minor version bump they seemingly were dropping support for more and more packages (scipy 0.19 is no longer available in the main channel).

I asked them about it here, please read this: https://github.com/ContinuumIO/anaconda-issues/issues/11146#event-2509814992
This response, plus reading the linked blog post, indicates to me that conda might be fine as a package manager for end-users, but we cannot rely on it for running our CIs.

For a short term solution, we can either pin its version to 4.6 (currently we are doing that for Nistats).
Or we add the older channel back, as described in the issue link and the blog post.

For a longer term, I am thinking about switching to pip.
We can let CircleCI keep using conda - it always uses the latest version and is a good way to test our conda pipeline. For Travis etc, I propose we move to pip.

I would like to move quickly on this matter. @GaelVaroquaux

**Comment by kchawla-pi** [comment]
For the moment, as a temporary stop gap, I am manually adding the channel back as indicated by conda documentation

**Comment by GaelVaroquaux** [comment]
> For a short term solution, we can either pin its version to 4.6 (currently we
> are doing that for Nistats).
> Or we add the older channel back, as described in the issue link and the blog
> post.

No strong opinion on this.

> For a longer term, I am thinking about switching to pip.

I think that this is what we are going to have to do. Maybe you could ask
the scikit-learn team at Inria how they are dealing with it.

**Comment by kchawla-pi** [comment]
They use pip and apt for installation on most of the builds.

**Comment by GaelVaroquaux** [comment]
> They use pip and apt for installation on most of the builds.

OK. That's my favorite solution: more reliable in my experience.

**Comment by jeromedockes** [comment]
related to #2093

**Comment by jeromedockes** [comment]
> OK. That's my favorite solution: more reliable in my experience.

In this case we might want to have a look at `tox`.

it automates the creation of virtualenvs, pip installations etc. and works well
with pytest (for example pytest will look for a `tox.ini` file as well as
`pytest.ini` and `setup.cfg`, also pytest uses it for their CI). I have used it
on appveyor (for a much smaller project than nilearn) and it seems like a good
option.

https://tox.readthedocs.io/en/latest/
https://tox.readthedocs.io/en/latest/example/pytest.html
http://doc.pytest.org/en/latest/goodpractices.html#tox

summary from the pytest doc:

"Once you are done with your work and want to make sure that your actual package passes all tests you may want to look into tox, the virtualenv test automation tool and its pytest support. tox helps you to setup virtualenv environments with pre-defined dependencies and then executing a pre-configured test command with options. It will run tests against the installed package and not against your source code checkout, helping to detect packaging glitches."

**Comment by kchawla-pi** [comment]
> In this case we might want to have a look at tox.

I had the discussion pertaining to this with Jerome, once,  offline. Reproducing it here.

I posited, and Jerome concurred at that time, that we do not need Tox.

Since the tests are done on docker containers/ virtual machines discarded after each use, we don't need to create virtual environments, we can install the packages in the base env and run from that, so long as we specify the correct python version for each container/machine.

TravisCI already runs tests from the installed package, not the source code, so that functionality is covered as well.

**Comment by kchawla-pi** [comment]
I am going to start work on this. I will not do similar modification for Nistats, since it will be EOL'd soon.

After this I'll start work on incorporating Nistats into Nilearn.

**Comment by GaelVaroquaux** [comment]
Sounds good. Thanks for your thoughts!

**Comment by kchawla-pi** [comment]
@GaelVaroquaux What are your thoughts regarding #2093 It will be easier to write a new travis config than modify the existing one.
