### ISSUE TITLE
NKI urls for left and right hemispheres point to the same file

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2117]
it seems that e.g.
https://www.nitrc.org/frs/download.php/8261/A00033747_rh_preprocessed_fsaverage5_fwhm6.gii
and
https://www.nitrc.org/frs/download.php/8261/A00033747_lh_preprocessed_fsaverage5_fwhm6.gii

point to the same file (true for other subjects as well), which corresponds to the left hemisphere.

see 
https://neurostars.org/t/preprocessed-nki-fsaverage5-surface-data/4784

@juhuntenburg do you know if the files uploaded on nitrc have changed recently?

**Comment by juhuntenburg** [comment]
Hi, just to understand the issue, what do you mean by they point to the same file (the two urls are different)?

**Comment by jeromedockes** [comment]
the two urls are different but when I download them the result  is exactly the same (try to `wget` both URLs then `cmp` the resulting files)

**Comment by juhuntenburg** [comment]
The reason is that they have the same identifier (8261) which is not the correct one. The real files have the following urls and are different:
https://www.nitrc.org/frs/download.php/8262/A00033747_lh_preprocessed_fsaverage5_fwhm6.gii
https://www.nitrc.org/frs/download.php/8263/A00033747_rh_preprocessed_fsaverage5_fwhm6.gii

Where did you get the urls from?

**Comment by jeromedockes** [comment]
they are the ones used by the nilearn fetcher:

https://github.com/nilearn/nilearn/blob/bfbc2632f90e7e8e3ee3b7036d4fd08d8ec91fec/nilearn/datasets/func.py#L1853

https://github.com/nilearn/nilearn/blob/bfbc2632f90e7e8e3ee3b7036d4fd08d8ec91fec/nilearn/datasets/func.py#L1859

**Comment by juhuntenburg** [comment]
Jap, that is wrong, should I fix it?

**Comment by jeromedockes** [comment]
If you can that would be great! thanks!
