### ISSUE TITLE
user guide screenshots out of date

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2119]
the surface and connectome views have improved so we may want to update the screenshots in this section of the user guide:

https://nilearn.github.io/plotting/index.html#interactive-plots

**Comment by kchawla-pi** [comment]
ARe these not auto-generated from fresh code? Why not?

**Comment by GaelVaroquaux** [comment]
They are not, because it's hard.

That's the reason why we have sphinx-gallery. Though the interplay between sphinx-gallery and the narrative docs needs work and rethinking.

**Comment by orduek** [comment]
I don't mind updating those. Should I upload it here?

**Comment by jeromedockes** [comment]
> I don't mind updating those. Should I upload it here?

that would be very helpful, thank you!
you would have to replace the images in /doc/images/ with the new ones
(I don't remember exactly which images need updating but I would first
have a look at those whose name contains "plotly")
And then you could open a Pull Request
thanks!
