### ISSUE TITLE
start squashing commits when merging PRs

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2123]
squashing commits when merging PRs, as does scikit-learn for example, would make
it much easier to grab a particular patch for a bugfix release such as #2122. I
think it's important to be able to make these small releases easily.

@kchawla-pi @GaelVaroquaux what do you think?

**Comment by GaelVaroquaux** [comment]
Yes. Let's use the github feature "squash and merge", but not ask contributors to squash themselves. 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by jeromedockes** [comment]
great, I changed the repo settings so that we use "squash and merge"
