### ISSUE TITLE
Make doctests "allowed to fail"

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2124]
I propose making the doctests "allowed to fail". 

This will maintain the benefit of alerting us if documentation and behaviour are out of sync. 

This will also give us the benefit that the entire test suite doesn't fail due to a doctest, which are harder to nudge into correctness when we are supporting multiple versions of libraries, where some of them start returning an output (slightly) different from previous versions. I encountered such an issue in PR #2122 and PR #2076

**Comment by jeromedockes** [comment]
I don't think doctests should be allowed to fail.
if one particular test should be skipped that can be done with a doctest directive

**Comment by jeromedockes** [comment]
I haven't looked at #2122 in detail yet but for example in #2076 failures were genuine and it was good that you fixed them

**Comment by kchawla-pi** [comment]
Going with Jerome's recommendation here.

**Comment by GaelVaroquaux** [comment]
Thanks! Sorry, I didn't see this earlier.

In my experience, a test that is allowed to fail will be ignored and
eventually end up failing. Hence, it reduces a lot the usefulness of a
test.
