### ISSUE TITLE
Plans to add surface-based searchlight MVPA functionality?

### ISSUE THREAD

**Issue by johnmarktaylor91** [nilearn/nilearn#2128]
PyMVPA has functionality to run MVPA searchlights on the surface rather than the volume, but as far as I can see, this doesn't exist yet for nilearn... are there any plans to incorporate this at some point? Other than this one thing nilearn has met 100% of my needs :]

**Comment by bthirion** [comment]
Hi, I know that @SylvainTakerkart has been working on this.
Sylvain, any update on this ?
Best

**Comment by SylvainTakerkart** [comment]
Hi there, yes indeed, I have a PR open exactly for this #1959 . The code is working, I just need to finalize the associated data fetchers necessary to run the example and finalize a few things... Wanted to do this over the summer, but it seems the summer is gone now... (bouuuuhhh!!!)  I plan on finalizing this in october, sorry for the delay...

**Comment by mengjin123** [comment]
Hi, I’m trying to do searchlight decoding based on surface. According to the tutorial ([Nilearn: Statistical Analysis for NeuroImaging in Python — Machine learning for NeuroImaging](https://nilearn.github.io/auto_examples/02_decoding/plot_haxby_searchlight_surface.html?highlight=searchlight%20search_light#sphx-glr-download-auto-examples-02-decoding-plot-haxby-searchlight-surface-py)), I can only searchlight decode between two conditions. In my experiment, I have several conditions and I want to split the fmri data into one train dataset and several test datasets. Then I can train a classifier using the train datasets, and test the classfier for test datasets. 
How can I achieve such searchlight analysis on surface?
Any suggestions?
Thanks~

**Comment by SylvainTakerkart** [comment]
Hi!

A surface-decoding capability has been added in nilearn as you mention it... (not based on the PR I had opened before this, but it does the same thing, so this parenthesis is a technical detail that probably does not concern you as a user)

I don't think there is any restriction to binary decoding: if you have more than two values in your labels, it will automatically perform multi-class searchlight decoding... @bthirion, can you confirm?

Cheers,

Sylvain

ps: once this discussion with @mengjin123 is solved, we should probably close this issue which is obsolete ;)

pps: @mengjin123 re-reading your message, your issue might more be related to data splitting than to the number of conditions... maybe you should tell us more about your design, what you want to decode and how you would like to split your data... but maybe it would be more appropriate to post all this on https://neurostars.org/ with the "nilearn" tag

**Comment by SylvainTakerkart** [comment]
ahhh, I see @mengjin123 that in fact, you already posted your question on neurostars... ;)

it's clearly a better place than here, let's close this issue!
