### ISSUE TITLE
Appveyor still using Nosetests instead of pytest

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2129]
>  The tmpdir fixture must be a parameter in test_scraper() definition

Yes, sorry for being unclear ! That was what I had in https://github.com/nilearn/nilearn/pull/2019/commits/fbe2fda326abf250b47cf5fee6dbfb8644c9ae03, but [my AppVeyor build errored](https://ci.appveyor.com/project/kchawla-pi/nilearn-uaqwf/builds/27156763) with

```
======================================================================
ERROR: Test report scraping.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35-x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: test_scraper() missing 1 required positional argument: 'tmpdir'
```

I was suspicious from the traceback that nose was somehow being called. Any thoughts appreciated, but since this is resolved in the current PR I can also move this discussion to a new issue !

_Originally posted by @emdupre in https://github.com/nilearn/nilearn/pull/2019#issuecomment-527677031_

**Comment by kchawla-pi** [comment]
You are right @emdupre  Appveyor is using Nose. I will fix this once I am back.

**Comment by emdupre** [comment]
> I will fix this once I am back.

Hopefully you're not working on vacation ! No rush on this from me. 

🌅💆‍♂️🍧
