### ISSUE TITLE
Reorganize nilearn.image.resampling

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#213]
The module is currently a mess, because it has some bounds-computing code, that is somewhat weakly-related to resampling. This should probably be spawned to another file.

**Comment by lesteve** [comment]
Bumping this one up to 0.2.1.

**Comment by banilo** [comment]
There appear to be now volunteers for this one. Would not @eickenberg be the perfect candidate, since he wrote big parts of the original implementation, if I remember correctly.

**Comment by AlexandreAbraham** [comment]
Moving to 0.2.4 since a refactoring is a major change.

**Comment by bthirion** [comment]
I suggest to close that one, as it is stalled and we live with it.

**Comment by Remi-Gau** [comment]
Good with me.
