### ISSUE TITLE
SSL Certificate Verification Failing in CIs

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2133]
Recently, the CIs are failing due to SSL Certificate Verification Failure. How do we address this? Disable checking globally in our CIs? This may leave it vulnerable to man in the middle attacks to steal our CI key and make modifications of the repo, including deleting it, but I am not qualified to assess this problem. I will read some more. 
@GaelVaroquaux @jeromedockes

**Comment by AGrigis** [comment]
Is your problem linked with certifi, ie update CA file?

**Comment by kchawla-pi** [comment]
Seems to be fixed by the servers.
