### ISSUE TITLE
ENH : Adding hierarchical k-means method to Parcellations class (nilearn.regions.parcellation)

### ISSUE THREAD

**Issue by thomasbazeille** [nilearn/nilearn#2134]
Hello, 

While developping [fmralign](https://github.com/thomasbazeille/fmralign), @bthirion included a parcellation based on Hierarchical K-means. From his experience it provides better clustering and works faster than traditional K-means for neuroimaging data.

I can contribute a PR adding this method (hierarchical_kmeans) and corresponding tests to the Parcellation class if it is useful. Just, this method is not available directly in scikit-learn so I'd have to include as well the implementation of the algorithm in a dedicated module.

Would that be helpful ? Should it replace plain kmeans as default if added ?

**Comment by jeromedockes** [comment]
I think that would be useful, if the implementation of hierarchical
K-means is simple.

Note that in the meanwhile you have the Ward method in nilearn for
hierarchical clustering.

ping @KamalakerDadi who knows this part of nilearn well.

**Comment by GaelVaroquaux** [comment]
In my experience too hiearchical kmeans is great of neuroimaging data,
and it would probably be very useful for people.

However: has this been published somewhere? I think that for nilearn we
need to adopt a principled strategy for what we include. Typically,
basing ourselves on publications would be good.

**Comment by KamalakerDadi** [comment]
>While developping fmralign, @bthirion included a parcellation based on Hierarchical K-means. From >his experience it provides better clustering and works faster than traditional K-means for >neuroimaging data.

Just curious, ReNA ? Was it better ? 

>ping @KamalakerDadi who knows this part of nilearn well.

There was ReNA implemented in the same context. So why not, if it is useful.

**Comment by GaelVaroquaux** [comment]
> Just curious, ReNA ? Was it better ?

I would think that ReNA (and Ward) are good for many parcels (10000),
while hierachical kmeans is good in the opposite regime (few hundreds of
parcells).

**Comment by bthirion** [comment]
An interesting property of hierarchical k-means is that you can use it to obtain relatively balanced parcels (e.g. more balanced than Ward).

**Comment by thomasbazeille** [comment]
@GaelVaroquaux after quickly searching through the litterature I didn't find any paper showcasing the use of Hierarchical K-means in neuroimaging. @bthirion do you know such a paper ?

**Comment by bthirion** [comment]
No. The only paper where we were using it was actually not published and never resubmitted ...

I'm not sure I would like to have a dedicated publication on this. We should simply use it in one of our works and then cite that paper.

**Comment by thomasbazeille** [comment]
Ok I will open the PR. Thanks everyone,

**Comment by NicolasGensollen** [comment]
Solved by #2282
