### ISSUE TITLE
correct labels in fetch_atlas_schaefer_2018

### ISSUE THREAD

**Issue by danjgale** [nilearn/nilearn#2137]
Some errors were recently discovered in the labels provided with the Schaefer atlases (see [here for full detail](https://groups.google.com/forum/#!topic/cbig_users/6ra-LLlogUw)) due to a bug. This has been fixed and correct labels are provided in release version 0.14.3. 

Currently as of nilearn 0.5.2, `fetch_atlas_schaefer_2018`'s default `base_url` uses release [version 0.8.1](https://github.com/fliem/nilearn/blob/37964dac24fb566ebc916add307dacaa413244f0/nilearn/datasets/atlas.py#L1266) that contains the incorrect labels. A quick fix changing this to 0.14.3 would give users the correct labels by default (which would be the expected behaviour).

In addition to updating the URL, should `fetch_atlas_schaefer_2018` provide a warning to users if they wish to use a previous version with the old uncorrected labels?

**Comment by jeromedockes** [comment]
> In addition to updating the URL, should `fetch_atlas_schaefer_2018` provide a warning to users if they wish to use a previous version with the old uncorrected labels?

Maybe a note in the docstring and a whatsnew entry is enough?

**Comment by GaelVaroquaux** [comment]
Sounds good. Can you send a pull request, please?

Thank you very much!
