### ISSUE TITLE
math_img() misbehaves for binarizing probabilistic nifti image

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#2145]
The attached nifti file with continuous values is mixing things up in the initially 0-1 nifti image.

r_tr_bin = math_img('my_img > 0', my_img=r_tr_prob)

![image](https://user-images.githubusercontent.com/3907396/65964118-815d2480-e45c-11e9-9411-3ab54ba18f09.png)

[r_tr_bin.nii.gz](https://github.com/nilearn/nilearn/files/3676289/r_tr_bin.nii.gz)

**Comment by GaelVaroquaux** [comment]
> The attached nifti file with continuous values is mixing things up in the
> initially 0-1 nifti image.

> r_tr_bin = math_img('my_img > 0', my_img=r_tr_prob)

What if you do > 1e-4 ?

**Comment by jeromedockes** [comment]
can you share the original image?` r_tr_prob`

**Comment by banilo** [comment]
It is attached above: r_tr_bin.nii.gz

**Comment by banilo** [comment]
> What if you do > 1e-4 ?

Agree, Gael, that it may very well be a tresholding issue. If that is the case, perhaps some form of warning could be issued, if a nifti passed to math_img is many very-near-zero values to avoid confusion to future nilearn users.

**Comment by jeromedockes** [comment]
> It is attached above: r_tr_bin.nii.gz

that is the binarized one

**Comment by GaelVaroquaux** [comment]
> Agree, Gael, that it may very well be a tresholding issue. If that is the case,
> perhaps some form of warning could be issued, if a nifti passed to math_img is
> many very-near-zero values to avoid confusion to future nilearn users.

That's sound pretty hard to implement and pretty unreliable in general.

**Comment by jeromedockes** [comment]
Indeed the image contains many small values; replacing 0 with e.g. 1e-16
works for this image.

I think nilearn gives the correct result here

**Comment by jeromedockes** [comment]
closing as the displayed behavior is the expected one
