### ISSUE TITLE
Change Nifti(Spheres/Map/Labels)Masker to allow for empty ROIs when using a mask

### ISSUE THREAD

**Issue by trh3** [nilearn/nilearn#2146]
As it stands, when NiftiSphereMasker or the related functions encounter an ROI without any voxels in the supplied brain mask, it throws an ValueError and no ROI timeseries are returned.

This leads to issues where if you have poor coverage in some regions, you cannot supply a mask to correctly extract other regions that have better (but perhaps not 100% coverage).

I would suggest that instead of throwing an error when encountering empty ROIs, provide a column of nan's for the empty ROIs and proceed with the rest of the ROIs. This could be an additional flag to change from error to warning behavior.

**Comment by jeromedockes** [comment]
Thanks! do you think you could supply an image and a short script to
reproduce the error?

why not remove the empty roi from the sphere masker's list of seeds?

**Comment by thomasbazeille** [comment]
Not sure what we should do with this @jeromedockes , maybe time to close if no refactor of NiftiSphereMasker is yet envisionned?

**Comment by jeromedockes** [comment]
I think an error is the most sensible behaviour in this case anyway
