### ISSUE TITLE
Can't plot regions with nilearn 0.5.1 (because new_img_like() errs with non-iterable Headers)

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2147]
Referencing (private Repo): https://github.com/NeuroLang/NeuroLang/issues/182
I'll investigate & attempt to replicate the problem.

> After update Nilearn to the last version available (nilearn=0.5.2) I can't plot neurolang regions. Is not the case of nilearn=0.5.0 that works well.
> 
> The code in '[plot_neurolang_datalog_example.py'](https://github.com/NeuroLang/NeuroLang/blob/64eac3f0dee3fde9101166685e430d1134b20c08/examples/plot_neurolang_datalog_example.py) is enough to reproduce the problem.
> 
> ```
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-12-bd2b51b68e5c> in <module>
>      19 )
>      20 for name, region in res.value:
> ---> 21     plotting.plot_roi(region.spatial_image(), title=name)
> 
> ~/miniconda3/envs/neurolang/lib/python3.7/site-packages/nilearn/plotting/img_plotting.py in plot_roi(roi_img, bg_img, cut_coords, output_file, display_mode, figure, axes, title, annotate, draw_cross, black_bg, threshold, alpha, cmap, dim, vmin, vmax, resampling_interpolation, **kwargs)
>     706         threshold=threshold, bg_vmin=bg_vmin, bg_vmax=bg_vmax,
>     707         resampling_interpolation=resampling_interpolation,
> --> 708         alpha=alpha, cmap=cmap, vmin=vmin, vmax=vmax, **kwargs)
>     709     return display
>     710 
> 
> ~/miniconda3/envs/neurolang/lib/python3.7/site-packages/nilearn/plotting/img_plotting.py in _plot_img_with_bg(img, bg_img, cut_coords, output_file, display_mode, colorbar, figure, axes, title, threshold, annotate, draw_cross, black_bg, vmin, vmax, bg_vmin, bg_vmax, interpolation, display_factory, cbar_vmin, cbar_vmax, brain_color, **kwargs)
>     153 
>     154     if img is not False and img is not None:
> --> 155         img = _utils.check_niimg_3d(img, dtype='auto')
>     156         data = _safe_get_data(img, ensure_finite=True)
>     157         affine = img.affine
> 
> ~/miniconda3/envs/neurolang/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py in check_niimg_3d(niimg, dtype)
>     320     Its application is idempotent.
>     321     """
> --> 322     return check_niimg(niimg, ensure_ndim=3, dtype=dtype)
>     323 
>     324 
> 
> ~/miniconda3/envs/neurolang/lib/python3.7/site-packages/nilearn/_utils/niimg_conversions.py in check_niimg(niimg, ensure_ndim, atleast_4d, dtype, return_iterator, wildcards)
>     269 
>     270     # Otherwise, it should be a filename or a SpatialImage, we load it
> --> 271     niimg = load_niimg(niimg, dtype=dtype)
>     272 
>     273     if ensure_ndim == 3 and len(niimg.shape) == 4 and niimg.shape[3] == 1:
> 
> ~/miniconda3/envs/neurolang/lib/python3.7/site-packages/nilearn/_utils/niimg.py in load_niimg(niimg, dtype)
>     120         if niimg.header is not None:
>     121             niimg = new_img_like(niimg, niimg.get_data().astype(dtype),
> --> 122                                 niimg.affine, copy_header=True)
>     123             niimg.header.set_data_dtype(dtype)
>     124         else:
> 
> ~/miniconda3/envs/neurolang/lib/python3.7/site-packages/nilearn/image/image.py in new_img_like(ref_niimg, data, affine, copy_header)
>     637     if copy_header:
>     638         header = copy.deepcopy(ref_niimg.header)
> --> 639         if 'scl_slope' in header:
>     640             header['scl_slope'] = 0.
>     641         if 'scl_inter' in header:
> 
> TypeError: argument of type 'SpatialHeader' is not iterable
> ```

**Comment by jeromedockes** [comment]
link seems broken?

**Comment by kchawla-pi** [comment]
Oh I forgot it's a private repo. I'll post the details here after lunch.

**Comment by jeromedockes** [comment]
> Oh I forgot it's a private repo. I'll post the details here after lunch.

thanks!

**Comment by kchawla-pi** [comment]
The example can't be accessed by non-members currently. I'll do some investigating and then update here, then we can see if we need more access or not.

**Comment by jeromedockes** [comment]
I think we just need the image that can't be loaded, not the full example

**Comment by jeromedockes** [comment]
this is probably the problematic commit:

e0ae31ca1f53e399a4b66803654eac588e5922be

**Comment by kchawla-pi** [comment]
@gzanitti @tgy

**Comment by kchawla-pi** [comment]
They are using the `datasets.fetch_atlas_destrieux_2009()` in their example.
The issue stems from PR #1872 . Reversing the changes made in that PR fixes this.
I am going to explore more and figure out what to do about this without losing the benefits of PR #1872

**Comment by kchawla-pi** [comment]
SpatialHeader is not iterable and hence does not support the containership test (the `in` operator) that `new_img_like()` performs.

This implies to me that usual Nifti Image Headers are iterable which is why this hasn't been a problem for us generally.
However, PR #1872 was merged without tests to test the behaviour , so I will write one.

**Comment by kchawla-pi** [comment]
The simplest thing to do would be handle the exception in `nilean._utils.niimg.load_niimg()`
