### ISSUE TITLE
Revert PR #2078 & change the min library versions back

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2148]
Conda's changes led me to believe they had dropped support for many older version of the packages Nilearn depends upon, so we bumped up the versions, except this happened with the bumped up version in their next point release.
Turns out it is a bug in their rollback system that they don't consider a serious problem. However it is for us and our CI systems.
To address this we decided to switch to pip. The work is almost complete, awaiting a final review in PR #2141 . 
It is time to revert back to the current minimum version supported by Scikit-Learn.

**Comment by kchawla-pi** [comment]
Eh. I don't know if it is worth it. It's mostly matplotib and one version bump of scikit-learn.

**Comment by GaelVaroquaux** [comment]
> Eh. I don't know if it is worth it.

I'm not sure either. We already have a lot to do.
