### ISSUE TITLE
What is the range of z in nilearn.plotting?

### ISSUE THREAD

**Issue by leonardo-oz** [nilearn/nilearn#2152]
Hi, All:

I am using 'nilearn.plotting' to display a nifti image. 
````
nilearn.plotting.plot_anat('xyz.nii.gz', display_mode='z') 
````
If the image has shape as (128, 256, 170), I notice that z in display actually ranges from negative to positive. 

So my question is what is the zero for z here?  Is 170/2 = 85,  any z slice below 85 treated as negative, vice versa for any slice above 85?

Thanks.

**Comment by jeromedockes** [comment]
leonardo-oz <notifications@github.com> writes:

> Hi, All:
>
> I am using 'nilearn.plotting' to display a nifti image. 
> ````
> nilearn.plotting.plot_anat('xyz.nii.gz', display_mode='z') 
> ````
> If the image has shape as (128, 256, 170), I notice that z in display actually ranges from negative to positive. 
>
> So my question is what is the zero for z here?  Is 170/2 = 85,  any z slice below 85 treated as negative, vice versa for any slice above 85?
>
> Thanks.  
>

the "x=...", "y=...", z=...", in the display correspond to world
coordinates (in mm), not voxel indices. the image affine
`nilearn.image.load_img("my_image.nii.gz").affine` maps voxel indices to
coordinates:

https://nilearn.github.io/auto_examples/04_manipulating_images/plot_affine_transformation.html#sphx-glr-auto-examples-04-manipulating-images-plot-affine-transformation-py

the origin of the coordinate system is the last column of the affine.

the issue tracker is for bug reports and feature requests, so in the
future I recommend you use the neurostars forum:

https://neurostars.org/

with the tag "nilearn", for questions and help about how to use nilearn.

**Comment by leonardo-oz** [comment]
@jeromedockes , thanks for your explanation.

**Comment by jeromedockes** [comment]
> @jeromedockes , thanks for your explanation.

You're welcome! if you feel your question has been answered, you can
close the issue.
