### ISSUE TITLE
Compute_full_tree option in agglomerative-type clustering parcellations?

### ISSUE THREAD

**Issue by dPys** [nilearn/nilearn#2153]
Any particular reason why the compute_full_tree option of agglomerative clustering is hard-coded to 'auto' in nilearn? I certainly understand why this would be the case in _sklearn_.

It seems to me that it would be useful to allow the user to override this with a similar boolean in the Parcellations API in the case that a precise number of clusters in a parcellation output is desired.

@dPys

**Comment by jeromedockes** [comment]
The number of clusters is controlled by `n_parcels`.
`compute_full_tree` is only to stop the computation of cluster merges
that are not used. therefore it does not affect the result but can help
reduce computation time. I am not sure but I would guess it is not
exposed in nilearn to simplify the interface.

**Comment by dPys** [comment]
Thanks, That makes sense. Closing this issue!
