### ISSUE TITLE
expose useful _plot_img_with_bg kwargs explicitly in plotting.plot_img

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2154]
`plotting.plot_img` helpfully forwards kwargs, and in particular `bg_img`, to
`plotting.img_plotting._plot_img_with_bg`.

However the docstring says kwargs are passed to `pyplot.imshow`.

I would suggest exposing important arguments such as vmin, vmax and bg_img
explicitly in the function signature.

note that this example:

http://nilearn.github.io/auto_examples/02_decoding/plot_haxby_searchlight.html#sphx-glr-auto-examples-02-decoding-plot-haxby-searchlight-py

uses the `bg_img` kwarg

**Comment by bthirion** [comment]
+1

**Comment by jeromedockes** [comment]
> +1

then I'll open a PR
