### ISSUE TITLE
Problem with building docs

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2170]
> What version of Nilearn are you using?

`master`

> What were you trying to do?

Building docs using `make html-strict`

> What did you expect will happen?

DOcs will be built

> What actually happened?

On CircleCI I get 
```python
Warning, treated as error:
/home/circleci/project/examples/05_advanced/plot_age_group_prediction_cross_val.py failed to execute correctly: Traceback (most recent call last):
  File "/home/circleci/miniconda3/envs/testenv/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 480, in _memory_usage
    out = func()
  File "/home/circleci/miniconda3/envs/testenv/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 465, in __call__
    exec(self.code, self.globals)
  File "/home/circleci/project/examples/05_advanced/plot_age_group_prediction_cross_val.py", line 22, in <module>
    development_dataset = datasets.fetch_development_fmri(n_subjects=60)
  File "/home/circleci/project/nilearn/datasets/func.py", line 2107, in fetch_development_fmri
    verbose=verbose)
urllib.error.HTTPError: HTTP Error 504: Gateway Time-out
```
Locally I get 
```python
Exception occurred:
  File "/home/kshitij/workspace/nilearn-org/nilearn-repo/master/nilearn/nilearn/reporting/sphinx_report.py", line 39, in __call__
    for report in block_vars['example_globals'].values():
KeyError: 'example_globals'
```

**Comment by kchawla-pi** [comment]
@jeromedockes Your circleci build: https://circleci.com/gh/nilearn/nilearn/4843 is passing, but the master is not even though your PR is based on the same master. 
I figured its a server issue but  its not going away, and yours is passing. Ideas?

**Comment by kchawla-pi** [comment]
I will iterate through previous merges until I find one that works. WIll update here.

**Comment by GaelVaroquaux** [comment]
Looks like a problem with the version of sphinx or sphinx-gallery.

**Comment by kchawla-pi** [comment]
How? They haven't changed in my local environment. And CircleCI does not raise this error.

**Comment by kchawla-pi** [comment]
I didn't think it was due to something we merged, since the branches & master were passing pre-merge, and locally when I reverted to older versions of master I am still getting this error.

**Comment by jeromedockes** [comment]
>
> Building docs using `make html-strict`
>

there is no rule for this target in the Makefile on master; what command
did you run?

**Comment by kchawla-pi** [comment]
Okay, `fetch_development_fmri()` does not seem to be working, just like in CircleCI, so that is likely an OSF issue. I don't know why it is not working locally.

**Comment by kchawla-pi** [comment]
> there is no rule for this target in the Makefile on master; what command

Maybe you are looking at the Makefile in the root instead of the `docs`?

**Comment by jeromedockes** [comment]
> Maybe you are looking at the Makefile in the root instead of the `docs`?

I was. still, when I build the doc locally I get the same KeyError as you

**Comment by kchawla-pi** [comment]
Weird. I'm gonna put in a default for missing key and see what happens.

**Comment by jeromedockes** [comment]
> Weird. I'm gonna put in a default for missing key and see what happens.

for me upgrading sphinx-gallery seems to fix it

**Comment by kchawla-pi** [comment]
Ok... Well I guess I (and you) didn't run make html locally since the reports PR was merged so we didn't realize this would be a thing. CircleCI always uses the latest version so it never had thi problem.

**Comment by kchawla-pi** [comment]
Now its just the OSF server thing. WHy is your PR passing on CircleCI?

**Comment by jeromedockes** [comment]
> Now its just the OSF server thing. WHy is your PR passing on CircleCI?

mere luck with OSF I guess. Which build is not passing?

**Comment by kchawla-pi** [comment]
I'm trying the download locally, by calling `fetch_development_fmri()` and the process is stuck at downloading from https://osf.io/download/5c8ff37da743a90018606df1 . I have no problems downloading this link from the browser but the API seems to be having some. This is similar to what Dimitri experienced when uploading the data.
I'll notify OSF and then hope they fix it.

**Comment by kchawla-pi** [comment]
> mere luck with OSF I guess. Which build is not passing?

master, glematrie's PR. 

@jeromedockes If you call `fetch_development_fmri()` after renaming the exsiting dataset in nilearn_data, what happens?

**Comment by jeromedockes** [comment]
> @jeromedockes If you call `fetch_development_fmri()` after renaming the exsiting dataset in nilearn_data, what happens?

it seems to be downloading stuff. I will let you know when it finishes

**Comment by kchawla-pi** [comment]
It was a server for one of the fetcher was down and creating this problem.

**Comment by Baby-Baby** [comment]
I think change  url in   _fetch_development_fmri_functional()   of   nilearn/datasets/func.py is ok.
try url = 'https://files.osf.io/v1/resources/5hju4/providers/osfstorage/{}?action=download&direct&version=2'

**Comment by Baby-Baby** [comment]
i think change url in ( _fetch_development_fmri_functional) of (nilearn/datasets/func.py) is ok.
try url = 'https://files.osf.io/v1/resources/5hju4/providers/osfstorage/{}?action=download&direct&version=2'

**Comment by Baby-Baby** [comment]
Modifying url in (_fetch_development_fmri_functional) of (nilearn/datasets/func.py)  seems feasible.
try url='https://files.osf.io/v1/resources/5hju4/providers/osfstorage/{}?action=download&direct&version=2'
