### ISSUE TITLE
test_load_uniform_ball_cloud will fail with sklearn 0.22

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2173]
after this PR:

   https://github.com/scikit-learn/scikit-learn/pull/9288

the results of scikit-learn KMeans are different so this test:

https://github.com/nilearn/nilearn/blob/b5726d63b8838f929ba683cd8da67f73df0bc8fa/nilearn/surface/tests/test_surface.py#L387

will fail

**Comment by kchawla-pi** [comment]
So 2 tests, for  < v0.22 & >= v0.22
