### ISSUE TITLE
expose `vol_to_surf` parameters in `view_img_on_surf`?

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2180]
I wonder if we should allow users to specify parameters for the volume to surface projection when using `view_img_on_surf`. This would help explore the effect of these parameters. moreover, for discrete images such as atlases the default parameters of `vol_to_surf` are not appropriate.

Being able to disable interpolation would allow better plots for discrete images.

   ```python 
   from nilearn import datasets, plotting
   cmap = "gist_ncar"

   destrieux = datasets.fetch_atlas_destrieux_2009()
   plotting.view_img_on_surf(destrieux.maps, surf_mesh="fsaverage", cmap=cmap,
                             symmetric_cmap=False).open_in_browser()
   plotting.view_img_on_surf(
       destrieux.maps, surf_mesh="fsaverage",
       vol_to_surf_params={"n_samples": 1, "radius": 0.,
                           "interpolation": "nearest"},
       cmap=cmap, symmetric_cmap=False).open_in_browser()
   ```

![newplot(1)](https://user-images.githubusercontent.com/9196501/66900401-0750a200-effd-11e9-858a-1cb90a2f2604.png)

![newplot](https://user-images.githubusercontent.com/9196501/66900415-0f104680-effd-11e9-8d0e-5e660da55107.png)

or simply help getting a notion of voxel and mesh resolutions

![newplot(1)](https://user-images.githubusercontent.com/9196501/66900447-1cc5cc00-effd-11e9-88ac-26a34ac9a0c9.png)

**Comment by GaelVaroquaux** [comment]
> being able to disable interpolation would allow better plots for discrete images

This one does seem relevant.

I am not sure that I would expose the rest: they can use the lower-level
functions.

**Comment by jeromedockes** [comment]
Gael Varoquaux <notifications@github.com> writes:

>> being able to disable interpolation would allow better plots for discrete images
>
> This one does seem relevant.
>
> I am not sure that I would expose the rest: they can use the lower-level
> functions.

it needs to be interpolation + radius of the cloud of sample points,
i.e. to exactly the value of the image at the mesh node we need to set
radius=0 and interpolation="nearest"

**Comment by Craskermasker** [comment]
keen to look at this one today

**Comment by bthirion** [comment]
I think a demo explaining parameters impact is important here.
