### ISSUE TITLE
restore localizers interface

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2181]
it seems @GaelVaroquaux 's comment on #2097 

https://github.com/nilearn/nilearn/pull/2097/files#r328283557

was not addressed and we overlooked this when merging the PR.
`fetch_localizer_button_task` and `fetch_localizer_calculation_task` should be restored to their previous interface before the release

@kchawla-pi

**Comment by kchawla-pi** [comment]
Okay. This is high priority. I'll start on this right away.

**Comment by kchawla-pi** [comment]
Thank for caching i! A big save!
Kshitij

------------------------------------------------------------
"Those who never wander might be lost."

Working to be kind, aware, equanimous, and skilled at python.
