### ISSUE TITLE
`load_example_image`

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2184]
When I want to show how to plot, resample, or mask an image, I just want one
single functional image and I don't care which, nor about its metadata.

At the moment I have to use one of:

```python
from nilearn import datasets
datasets.fetch_localizer_button_task()["tmap"]
datasets.fetch_localizer_calculation_task()["cmaps"][0]
datasets.fetch_neurovault_motor_task()["images"][0]
datasets.fetch_neurovault_auditory_computation_task()["images"][0]
```

all these functions have long and similar but slightly different names, and
return dictionaries with different keys, and it's difficult to remember which
key is singular or plural or goes with which function or is a list or an image.

Would it be possible to have a function `load_example_functional_img() ->
Nifti1Image` returning not a dictionary but the path to a nifti file (possibly
distributed with nilearn to avoid network failures)? We could use it e.g. for
all the plotting examples, except an example that shows using the subject's
anatomy as `bg_img`.

**Comment by bthirion** [comment]
I like the idea. 
The only issue I can see with this is that the image is not actually random: it corresponds to a given contrast, in a given subject... I'd like the name of the function to acknowledge that fact. 
I'm afraid that some fMRI beginners will be lost other wise. 
Maybe `load_sample_motor_activation_image` or so ?

**Comment by jeromedockes** [comment]
> Maybe `load_sample_motor_activation_image` or so ? 

yes that sounds good

**Comment by alexisthual** [comment]
> should the function be included in `nilearn.plotting` or somewhere else?

I guess this function would belong to `nilearn.datasets` rather than `nilearn.plotting` :slightly_smiling_face: 

> although I am not sure how to make it so that the image is distributed with `nilearn`.

In essence, I think you want to write a new function which wraps one or several existing functions like the ones mentioned by @jeromedockes in the first post of this issue. In the end, you don't have to care about how the image is distributed with `nilearn`, you mostly have to make already accessible images even more accessible :ok_hand:

**Comment by ymzayek** [comment]
> I guess this function would belong to `nilearn.datasets` rather than `nilearn.plotting` slightly_smiling_face

Yes agreed
 
> In essence, I think you want to write a new function which wraps one or several existing functions like the ones mentioned by @jeromedockes in the first post of this issue. In the end, you don't have to care about how the image is distributed with `nilearn`, you mostly have to make already accessible images even more accessible ok_hand

I think you need to watch out for whether or not those examples you could wrap are downloading data or accessing a file shipped with nilearn. As far as I could tell, those mentioned above are all downloading data. You can see a list and location of all the data distributed with nilearn in [setup.py here](https://github.com/nilearn/nilearn/blob/main/setup.py#L69-L88). You can first check if there are any usable files in the referenced paths and if not, you could then add a file in the code base under the appropriate path and then reference it in `setup.py`.
