### ISSUE TITLE
Marker size array is not well displayed in plot_glass_brain

### ISSUE THREAD

**Issue by robbisg** [nilearn/nilearn#2185]
What version of Nilearn are you using? 
```python
In [36]: nilearn.__version__ 
Out[36]: '0.6.0a'
```
What were you trying to do?
Plot a connectome using ```plot_connectome``` function, giving the a numpy array as node_size.

Here's the snippet to replicate:
```coords``` and ```colors``` are obtained by some functions I've implemented in my libraries.

```python
from nilearn.plotting import plot_connectome
matrix = np.random.rand(90,90)
matrix = (matrix * matrix.T)/2
t_matrix = matrix * np.int_(matrix > 0.45) #Plot only some connections
f = plot_connectome(t_matrix, 
                        coords[:90], 
                        colors[:90], 
                        t_matrix.sum(0)*100, 
                        'magma_r',
                        display_mode='lyr',
                        edge_vmin=0.45,
                        edge_vmax=0.5,
                        figure=pl.figure(figsize=(25,15)),
                        )
```

What did you expect will happen?
![fixed](https://user-images.githubusercontent.com/695037/67026948-0d33a980-f109-11e9-83f5-24c2bf1c66e1.png)

What actually happened?
The node size of left and right images are different from those obtained in coronal view.
![buggy](https://user-images.githubusercontent.com/695037/67026961-13298a80-f109-11e9-909b-f8565edcd422.png)

I've found the problem in ```displays.py```and fixed it by adding at line 417
Maybe we also need some control on array/list length.
```python
            if isinstance(marker_size, np.ndarray) or \
                isinstance(marker_size, list):
                marker_size = np.array(marker_size)[relevant_coords]
```
I can do the PR, if you are ok.

**Comment by kchawla-pi** [comment]
Yes please!

**Comment by jeromedockes** [comment]
I think you are right and a PR would be welcome. Thanks!
