### ISSUE TITLE
Better documenting `slice()` usage in image.index_img

### ISSUE THREAD

**Issue by emdupre** [nilearn/nilearn#2188]
**What version of Nilearn are you using?**
0.6.0a0

**What were you trying to do?**
Index an image using `nilearn.image.index_img` over a set integer range. Passing a slice with the colon operator (e.g., `index=0:10`) results in a `SyntaxError`. 

The correct usage is `index=slice(0,10)`, but I could not find this documented in `nilearn.image.index_img`.

It'd be great to improve the documentation on using `index_img` with slices of arrays !

**Comment by bthirion** [comment]
Indeed PR welcome ;-)

**Comment by kchawla-pi** [comment]
It occurs to me that we may consider making `index=0:10` a valid way as well, though it would introduce 2 ways of doing the same thing, this is standar Python syntax that I would've expected to work. Thoughts?

**Comment by bthirion** [comment]
If nobody requests it, let's not do it...

**Comment by GaelVaroquaux** [comment]
> It occurs to me that we may consider making index=0:10 a valid way as well, though it would introduce 2 ways of doing the same thing, this is standard Python syntax that I would've expected to work.

I do not believe that this is valid Python syntax. What makes you think
that it is? The ":" to denote slicing can only be used in the bracket
operator, and I believe without keyword argument.

**Comment by jeromedockes** [comment]
indeed `index=0:10` is invalid syntax

**Comment by emdupre** [comment]
Closed with #2189
