### ISSUE TITLE
Testing Nilearn setup, build, & installation

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2199]
**What would you like changed/added and why?**
Use AzurePipelines unused additional CI jobs to test Nilearn installation.

**What would be the benefit?**
It will detect and forestall errors during building and installing Niearn preventing the need for PR like #2198 & help detect issues like #1993  . The additional time required for this would be very low.

**Comment by bthirion** [comment]
I guess you're ready for it !
