### ISSUE TITLE
Improve performance of the MetaEstimator Decoder object 

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2200]
Also in the discussion with @jeromedockes we agree on a future PR to improve performance of the Decoder object when using `LogisticRegression` estimator, in particular change from `LogisticRegression` to `LogisticRegressionCV`.

_Originally posted by @tbng in https://github.com/nilearn/nilearn/pull/2000#issuecomment-549411503_

**Comment by tbng** [comment]
@kchawla-pi One thing I notice that I have the privilege to work on some beautiful PR numbers.

**Comment by kchawla-pi** [comment]
Hahaha I noticed that as well when i was writing this issue!! :~)

**Comment by tbng** [comment]
Also there is a discussion about possibility of adding Variance Thresholder to `Decoder` object. See: https://github.com/nilearn/nilearn/pull/2000/files#r275962577

**Comment by bthirion** [comment]
I see that as a low-priority thing; Could be added later.

**Comment by kchawla-pi** [comment]
@tbng We should do it now while you have the momentum (after merging the original), just in a separate PR so it is easy to track and review. So You can open another issue (and PR) for this.

**Comment by kchawla-pi** [comment]
@tbng #2000 Has been merged int master. Congrats!!! That was a lot of work you did there.
As a special prize for your wonderful work, you now get to work on THIS issue!! Yay!

**Comment by bthirion** [comment]
Congrats ! B
