### ISSUE TITLE
Colobar distorts aspect ratio of plot_surf_roi surface

### ISSUE THREAD

**Issue by danlurie** [nilearn/nilearn#2207]
Bug Report
-----------
**What version of Nilearn are you using?**
Nilearn 0.6.0a, Matplotlib 3.1.2, Jupyter Lab 1.2.2
**What were you trying to do?** 
`plotting.plot_surf_roi` with `colorbar=True`
**What did you expect will happen?**
See a surface plot identical to when `colorbar=False`, but with a colorbar to the side.
**What actually happened?**
The surface plot gets squished horizontally to make room for the colorbar.

See attached image for an example. 
![JupyterLab](https://user-images.githubusercontent.com/1873103/68560905-325dc400-03f8-11ea-8e50-e1674ca70f1e.jpg)

I may end up trying to fix this myself. If I do, I'll submit a PR.

Thanks!

**Comment by bthirion** [comment]
Indeed, I can replicate the bug. Thx for looking at that !

**Comment by jeromedockes** [comment]
I think we should see if it is possible to get rid of the code used for adding a colorbar in these surface plots and use the same code as the slicers and projectors. see also #2220

**Comment by kchawla-pi** [comment]
I'm thinking the same thing and plan to work on this soon.

**Comment by NicolasGensollen** [comment]
This was adressed in #2643
