### ISSUE TITLE
Adding Variance Thresholder to `Decoder` object

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2211]
There is a discussion about possibility of adding Variance Thresholder to `Decoder` object. See: https://github.com/nilearn/nilearn/pull/2000/files#r275962577

_Originally posted by @tbng in https://github.com/nilearn/nilearn/issues/2200#issuecomment-552869412_

**Comment by bthirion** [comment]
Doesn't sound really needed.
