### ISSUE TITLE
Python 3.5 deprecation FutureWarning in Nilearn 0.6.0

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2213]
Python 3.5 will be EOL'd in September 2020. I will add a FutureWarning before release of Nilearn 0.6.0 stable, and we can drop support for it for Nilearn 0.8.0 stable.
@GaelVaroquaux

**Comment by kchawla-pi** [comment]
At the same time, I'll remove the warnings for Python 2.7, 3.4 deprecation.

**Comment by GaelVaroquaux** [comment]
OK
