### ISSUE TITLE
NiftiSpheresMasker does'nt allow the extraction of seeds with different radius.

### ISSUE THREAD

**Issue by yasmina-mekki** [nilearn/nilearn#2216]
Hi!
To my knowledge, currently, NiftiSpheresMasker does'nt allow the extraction of seeds with different radius.
In order to do that, you have to loop over all your seeds specifying the radius that you want. This process implies that the image is loaded each time which increase the computational time.

**Comment by GaelVaroquaux** [comment]
I think that this is a fairly uncommon usecase, and not one that we can
focus on making faster.

**Comment by kchawla-pi** [comment]
Would we consider a user submitted PR? Or is there an ad hoc suggestion to
achieve this without making it a feature to be maintained?

**Comment by GaelVaroquaux** [comment]
> Would we consider a user submitted PR?

It's going to make the codebase more complicated for an uncommon usecase.
I'd rather not.

**Comment by jeromedockes** [comment]
if you load the image first with `nilearn.image.load_img` it won't be read from disk every time. also, you could use the spheres masker to build an atlas containing your spheres, then use the labelsmasker. if you want, you can post a small example on the neurostars forum (https://neurostars.org/) and we can try to see if we can help you speed it up

**Comment by NicolasGensollen** [comment]
Hi @yasmina-mekki 
Were you able to implement the solution proposed above by @jeromedockes ? (If there is a related post on neurostars, adding a link to it here could be useful). 
However, I don't think this feature will be implemented such as to not make the codebase too complicated. Unless there is still something to do here, I will close the issue in a couple of weeks.

**Comment by yasmina-mekki** [comment]
Hi @NicolasGensollen ,
I was indeed able to implement the solution proposed by @jeromedockes. I used the 'create_sphere' function from nltools.mask for that purpose.
Thank you.
