### ISSUE TITLE
unexpected shape when upsampling image

### ISSUE THREAD

**Issue by fliem** [nilearn/nilearn#2217]
I tried to upsample an image and got an unexpected image shape (nilearn v0.6.0a).

I wanted to upsample the z-dimension of an image with 2x2x2mm voxels, so that it has 2x2x1mm voxels. I expected for the z-shape to double, but received z_original_size*2-1.

```
from nilearn import image
from nipy.testing import anatfile

in_file = anatfile
in_img = image.load_img(in_file)
target_aff = in_img.affine.copy()
target_aff[2, 2] = 1

res_img = image.resample_img(in_img, target_affine=target_aff, interpolation="nearest")
print("in shape", in_img.shape)
print("out shape", res_img.shape)
```

Output:
```
in shape (33, 41, 25)
out shape (33, 41, 49)
```
When I expected (33,41,50).

If I look at the data, it seems that the 0th voxel is not dealt with correctly.
```
print("in data", in_img.get_data()[15, 15, :3])
print("out data", res_img.get_data()[15, 15, :6])
```
Output:
```
in data [10741 10559 10597]
out data [10741 10559 10559 10597 10597  9145]
```
When I expected the output to look like:
`[10741 10741 10559 10559 10597 10597]`

If I force the output shape to be (33,41,50), the same thing happens but a slice with zeros is added in the top slice (data[:,:,-1]).
Any ideas what is happening here? Thanks

**Comment by bthirion** [comment]
Regarding the shape problem, I think that the idea is  that you should provide the target shape together with the target affine (as you finally do).
Regarding the zero imputation on the first slice, I thing that goes to scipy.ndimage. The point  is not so simple: depending on the conventions used, one of the top or bottom slice may be viewed as an extrapolation from the existing data, which is handled with imputation by a reference value, in that case, 0. 
Overall, I'm not sure how to handle this issue...

**Comment by bthirion** [comment]
Closing, as there is no clear solution as far as I can see.
