### ISSUE TITLE
plot_surf_roi Colorbar values are in scientific format 

### ISSUE THREAD

**Issue by seralouk** [nilearn/nilearn#2220]
Hi all,

I am plotting a `roi_map` and I get colorbar values in scientific format. I would expect to have only integers values since my `roi_map` contains integers.
The parcellation file contains only integers and can be found here: https://gofile.io/?c=ePmDcg

Additionally, I see `format='%.2g'` in https://github.com/nilearn/nilearn/blob/0941897aca6f3073221fcd3483afe91b8305b27c/nilearn/plotting/surf_plotting.py#L293. Maybe this is the culprit?

Shouldn't be `format='%.1f'` ?

Here is a small example:

```
import numpy as np
from nilearn import plotting, datasets

parcellation = np.load("parcellation.npy")
surface = datasets.fetch_surf_fsaverage('fsaverage') # the high resolution file - plot will take time

plotting.plot_surf_roi(surface["pial_left"], roi_map = parcellation, \
		hemi = 'left', view = 'lateral', bg_map = surface["sulc_left"], \
		bg_on_data = True, darkness = 0.6, \
		cmap = 'jet', colorbar = True)

```
![Figure_1](https://user-images.githubusercontent.com/25902670/69094532-d2e36200-0a50-11ea-9a2a-cc2a14b3c39d.png)

P.S: even by manually adding `vmin=0` and `vmax=181` the problem remains.

**Comment by jeromedockes** [comment]
> Additionally, I see `format='%.2g'` in
> 
> https://github.com/nilearn/nilearn/blob/0941897aca6f3073221fcd3483afe91b8305b27c/nilearn/plotting/surf_plotting.py#L293

probably, but this function (`plot_surf`) is also used to plot stat maps, so it would need to expose this parameter or choose the format based on the type of the data. 

I think the easier solution for you is to change the tick formatter of the matplotlib axis containing the colorbar

**Comment by seralouk** [comment]
Makes sense. Any idea how to do this? I have tried creating a figure and passing it to `figure=myfigure` argument but still no luck. Thanks for the reply

**Comment by jeromedockes** [comment]
can you try
```python
from matplotlib import pyplot as plt
from matplotlib import ticker

plt.gcf().axes[0].yaxis.set_major_formatter(ticker.FormatStrFormatter("%i"))
```

it may be `axes[1]` instead of `axes[0]`

**Comment by seralouk** [comment]
Even when I pass the `fig` and `ax`, it seems that the resulted figure does not obey my settings.

```
import numpy as np
from nilearn import plotting, datasets
from matplotlib import pyplot as plt
from matplotlib import ticker

parcellation = np.load("parcellation.npy")
surface = datasets.fetch_surf_fsaverage('fsaverage') # the high resolution file - plot will take time

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
plt.gcf().axes[0].yaxis.set_major_formatter(ticker.FormatStrFormatter("%i"))

plotting.plot_surf_roi(surface["pial_left"], roi_map = parcellation, \
		hemi = 'left', view = 'lateral', bg_map = surface["sulc_left"], \
		bg_on_data = True, darkness = 0.6, \
		cmap = 'jet', colorbar = True, axes= ax, figure=fig)

```

**Comment by jeromedockes** [comment]
the formatter should be changed for the colorbar axis, which is created by the plotting function. the axes you create will contain the brain plot, not the colorbar. can you try this?

```python
import numpy as np
from nilearn import plotting, datasets
from matplotlib import pyplot as plt
from matplotlib import ticker

parcellation = np.load("parcellation.npy")
surface = datasets.fetch_surf_fsaverage('fsaverage') # the high resolution file - plot will take time

plotting.plot_surf_roi(surface["pial_left"], roi_map = parcellation, \
    hemi = 'left', view = 'lateral', bg_map = surface["sulc_left"], \
    bg_on_data = True, darkness = 0.6, \
    cmap = 'jet', colorbar = True)

for ax in plt.gcf().axes:
    ax.yaxis.set_major_formatter(ticker.FormatStrFormatter("%i"))

plt.show()
```

**Comment by jeromedockes** [comment]
there does seem to be a problem, when formatted as ints I get 0 and 1, and the scientific notation gets truncated as in the plot you show.

for some reason `plot_surf` does not use the same code as other plotting functions to add the colorbar

**Comment by seralouk** [comment]
> there does seem to be a problem, when formatted as ints I get 0 and 1, and the scientific notation gets truncated as in the plot you show.
> 
> for some reason `plot_surf` does not use the same code as other plotting functions to add the colorbar

Exactly. I have tried more than 10 things to make it work but no luck. It's a bug indeed.

**Comment by jeromedockes** [comment]
yes, thanks for reporting!

**Comment by kchawla-pi** [comment]
I'll look at it.

**Comment by seralouk** [comment]
> Has there been any solution found for this issue? I am having the same issue using plot_anat.

Nothing new — still an issue

**Comment by bthirion** [comment]
I'm afraid that nobody can take time on that atm. would you try and identify the bug more precisely ?
Best,

**Comment by elliohow** [comment]
My issue is exactly the same as that described above, and trying to use [this](https://github.com/nilearn/nilearn/issues/2220#issuecomment-555506339) solution produced the same output as described [here](https://github.com/nilearn/nilearn/issues/2220#issuecomment-555514604).

**Comment by NicolasGensollen** [comment]
A little update on this:

- The link to download the parcellation file in the first message is not working anymore
- Even if it doesn't make much sense, the following code gives a colorbar with scientific notation (which indeed gets cropped): 

```python
import matplotlib.pyplot as plt
from nilearn import plotting, datasets

destrieux_atlas = datasets.fetch_atlas_surf_destrieux()
parcellation = destrieux_atlas['map_left']
surface = datasets.fetch_surf_fsaverage()

plotting.plot_surf_roi(surface["pial_left"], roi_map = parcellation,
        hemi = 'left', view = 'lateral', bg_map = surface["sulc_left"],
        bg_on_data = True, darkness = 0.6,
        cmap = 'jet', colorbar = True, 
        vmin=1, vmax=210) # force values larger than 99
plt.show()
```

With `matplotlib>=3.2.0` there is no longer a normalization between 0 and 1 (see this [link](https://matplotlib.org/3.2.1/api/prev_api_changes/api_changes_3.2.0.html)). So the following code proposed by @jeromedockes now works with recent versions of `matplotlib` (colorbar should display integer values from 1 to 210...):

```python
import matplotlib.pyplot as plt
from matplotlib import ticker
from nilearn import plotting, datasets

destrieux_atlas = datasets.fetch_atlas_surf_destrieux()
parcellation = destrieux_atlas['map_left']
surface = datasets.fetch_surf_fsaverage()

plotting.plot_surf_roi(surface["pial_left"], roi_map = parcellation,
        hemi = 'left', view = 'lateral', bg_map = surface["sulc_left"],
        bg_on_data = True, darkness = 0.6,
        cmap = 'jet', colorbar = True, 
        vmin=1, vmax=210) # force values larger than 99
for ax in plt.gcf().axes:
    ax.yaxis.set_major_formatter(ticker.FormatStrFormatter("%i"))
plt.show()
```

At this point I see two possibilities:

- consider that the user is responsible for manually formatting if scientific notation isn't wanted (as shown above). In this case, I think there is nothing to do and we can close this.
- enable the user to control this by adding an argument `cbar_tick_format` to `plot_surf` which will be used here:

https://github.com/nilearn/nilearn/blob/6c040cb98fe7e70b026522be5d404e5894348a9d/nilearn/plotting/surf_plotting.py#L297-L301

I'm OK with both but wondering what others think...

**Comment by jeromedockes** [comment]
> At this point I see two possibilities:
>
> - consider that the user is responsible for manually formatting if scientific notation isn't wanted (as shown above). In this case, I think there is nothing to do and we can close this.
> - enable the user to control this by adding an argument `cbar_tick_format` to `plot_surf` 

I think I prefer the second one; it adds a parameter to plot_surf but
most users don't use it directly but through plot_surf_stat_map or
plot_surf_roi. These functions would not expose the parameter to the
user but use appropriate values for the kind of data they are meant for
(floats for stat_map and ints for roi)
