### ISSUE TITLE
Deprecation cycle for fetch_haxby_simple ?

### ISSUE THREAD

**Issue by emdupre** [nilearn/nilearn#2230]
**What version of Nilearn are you using?** 0.6.0b

The current code suggests that `fetch_haxby_simple` will [be removed in a future release](https://github.com/nilearn/nilearn/blob/39c798e0310999e02341452ada6387958c04f72d/nilearn/datasets/func.py#L23), but it's unclear when that deprecation cycle is expected to occur. 

It looks like this warning was added in 2016 in #1127. Since we seem to be shipping the haxby simple data in our [datasets](https://github.com/nilearn/nilearn/blob/master/nilearn/datasets/data/pymvpa-exampledata.tar.bz2), I'm unsure if this can be used in eg the `index_img` docstring (see #2189) or if it will be removed in the near future.

Any insight is appreciated !

**Comment by bthirion** [comment]
Should probably be for the next release then...
thx.

**Comment by kchawla-pi** [comment]
This is way overdue for removal, but removing it as a last minute rush job seems unwise.
I was gonna say to focus on #2189 and use it if you think you should & we can always modify this later.
The alternative as I see it would be to defer PR #2189 for Nilearn 07.x .
What do you think?

**Comment by emdupre** [comment]
> This is way overdue for removal, but removing it as a last minute rush job seems unwise

WDYT of at least updating the deprecation warning to give a timeline for the anticipated removal (maybe 0.7.0) ?

**Comment by kchawla-pi** [comment]
Yes we should definitely do that

**Comment by kchawla-pi** [comment]
Targeting 0.7.0 seems sound.

**Comment by emdupre** [comment]
:+1: I can open a PR with that timeline, then !

**Comment by kchawla-pi** [comment]
@emdupre Would you do this today? Else I can.

**Comment by emdupre** [comment]
Can do today, sorry ! It will take me until lunch EST if that's ok.

**Comment by kchawla-pi** [comment]
Yup! 
PS: It's a simple enough one, I can do it if you would rather use your brainhack time attending to more complex ones.
