### ISSUE TITLE
Add warning when calculated n_parcels does not match requested n_parcels

### ISSUE THREAD

**Issue by emdupre** [nilearn/nilearn#2238]
In the `Parcellations` class, users can provide [a desired n_parcels](https://github.com/nilearn/nilearn/blob/5b7648cc4d452389f2d9320fafdfd1aa27562c0e/nilearn/regions/parcellations.py#L133) that they would like to be learned. I've noticed that sometimes &mdash; particularly, it seems, with k-means &mdash; the number of learned parcels does not exactly match the number of desired parcels. 

This can cause problems with downstream uses, such as in [fmralign](https://github.com/parietal-INRIA/fmralign). I'd like to add a check and to the `Parcellations` class that confirms that the learned number of parcels matches `n_parcels` and raises a warning if it does not.

WDYT ?

**Comment by GaelVaroquaux** [comment]
Fine by me

**Comment by jeromedockes** [comment]
Sounds good. do you know why the number of parcels can be different and
whether it can be fixed?

**Comment by emdupre** [comment]
From my reading of the [sklearn code for kmeans++](https://github.com/scikit-learn/scikit-learn/blob/1495f69242646d239d89a5713982946b8ffcf9d9/sklearn/cluster/k_means_.py#L112), it seems that it's likely arising from numerical imprecision. I remember @GaelVaroquaux mentioned that he hadn't found an easy solution when we discussed this in person... I'll let him confirm here, though.

Either way, I think it would need to be fixed in sklearn. But we could at least raise the warning here !

**Comment by jeromedockes** [comment]
OK, thanks!
