### ISSUE TITLE
Improper parameter name & non-optimal args for atlas Pauli 2017

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2239]
The `version` parameter for :func:`nilearn.datasets.fetch_atlas_pauli_2017` is a weird name. Version makes me think of numbers and iterations, and chronological versions of atlases, not the type of atlas. We should change it to `type`.

Additionally, currently, the valid arguments for this are 'prob' and 'det' which are not at all good. We should deprecate them with "probabilistic" & "deterministic".

I will open a PR for this.

**Comment by kchawla-pi** [comment]
My plan for this is to do 2 PRS. 
 1. Create a helper like `rename_parameters` (formerly `replace_parameters`) which allows us to change default args & issue FutureWarnings.
 2. Change this pauli 2017 fetcher using the above decorator.

**Comment by kchawla-pi** [comment]
Writing the new decorator might consume more time than I want to give for 1 function. I will proceed with step 2 and then if more functions need this, implement the decorator in step 1.

**Comment by kchawla-pi** [comment]
@bthirion @GaelVaroquaux 
What are your thoughts? Should we change the parameter and the atlas types?

**Comment by bthirion** [comment]
Please proceed.
Also, i agree that going directly to step 2 might be sufficient if the same need does not appear elsewhere.
