### ISSUE TITLE
Tutorial example for decoding 

### ISSUE THREAD

**Issue by ltetrel** [nilearn/nilearn#2242]
*What would you like changed/added and why?*

The idea is to update the [fMRI decoding notebook](https://nilearn.github.io/auto_examples/plot_decoding_tutorial.html#sphx-glr-auto-examples-plot-decoding-tutorial-py) and merge it with [MAIN19 material](https://github.com/main-training/main-training-nilearn-ml/blob/master/03_intro_to_nilearn.ipynb) 

*What would be the benefit? Does the change make something easier to use?*

A new material wlll be genrated (for workshops and training for ex.)

I am planning to work on this as a part of the [brainhack in montreal](https://brainhackmtl.github.io/global2019/projects.html#project8)

**Comment by jeromedockes** [comment]
@ltetrel can we close this issue thanks to your PR #2260 ?

**Comment by GaelVaroquaux** [comment]
Indeed, I forgot to close it. Thanks!!
