### ISSUE TITLE
Improving user guides: Searchlight  

### ISSUE THREAD

**Issue by danjgale** [nilearn/nilearn#2245]
Talking about user guide improvements with @GaelVaroquaux at the Montreal brain hack.

Based on our discussion, code would be moved out of user guides such that user guides are a high-level description of the technique. They provide narrative documentation that introduce concepts, etc. The user guides would link to the appropriate usage examples when relevant. 

Under this structure, users could refer to the user guide to learn about the technique, and then look at examples for how to implement the technique. In addition, this approach improves documentation maintainability by fully separating code examples.

I plan to work on this at the brain hack with Gael's guidance, starting with the Searchlight user guide (only because I've been doing a lot of searchlight analyses recently). 

Let me know your thoughts!

**Comment by bthirion** [comment]
Just one general comment: the difficulty with searchlight is that it is a way to do brain mapping, but it does not define 1) what is the statsistics used (prediction score ? some correlation or generalization thereof ? etc.) 2) how you get significance (p-value) from it, especially given that you end up with a tough multiple comparison problem.
Another difficulty is computation cost: you probably need to focus on a small brain region for the sake of documentation.

But clearly the main thing is to find a strategy regarding the two points above.
HTH

**Comment by GaelVaroquaux** [comment]
Fair enough, but some people are using it, so we might as document it
well.

PS: Dan is sitting next to me at the brainhack MTL

**Comment by danjgale** [comment]
Thanks for the input @bthirion; perhaps in the user guide we could provide a section on alternatives to searchlights.

**Comment by bthirion** [comment]
I think that it's fine to choose and illustrate your favorite scenario for searchlight use. 

Then possibly a discussion on limitations.
