### ISSUE TITLE
Stop recommending Anaconda for Nilearn installation for Windows 

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2249]
During the Marseilles Nilearn Workshop, about one-third users were on Windows and many among them were new Matlab users, new to Python. They followed the general recommendation for the workshop and installed the full Anaconda package.
Many systems were facing problems in setup which were fixable and fixed, however Anaconda was a hindrance not a help.

Anaconda on Windows is SLOW. A simple `conda list` can take much longer than on Linux.

Anaconda by default installs a HUGE number of packages and everytime a new package is installed it checks ALL existing packages in the current environment to ensure proper dependency management. However, since people don't use virtual environments and are not encouraged to do so much, this means everytime I tried to uninstall or install a package to fix things it took many many minutes, waiting for it to resolve stuff.
I can use the conda supplied `pip` to install packages and limit this delay but uninstalling existing versions is still a pain and sometime mixing pip and conda  creates problems.

Instead, if we advocate in our docs to install the standard Python from Python .org then pip install nilearn, matplotlib, and jupyter, that was very very quick even on old systems.

Since we have fixed the bug where `pip install nilearn` did not install the dependencies, I have seen the latter approach in action and it is fast and beautiful.

**Comment by GaelVaroquaux** [comment]
What's your concrete proposal in terms of installation instructions?

**Comment by emdupre** [comment]
@kchawla-pi , how would you feel about recommending miniconda instead of the full Anaconda installation ?

**Comment by kchawla-pi** [comment]
Miniconda will be a significant improvement.
In fact, nowadays I use miniconda for managing virtual environments and
python versions and then using pip for package installations.

Considerations:

It is not easy to find without a Google search.

How is it better than pipping it?

**Comment by kchawla-pi** [comment]
> What's your concrete proposal in terms of installation instructions?

We cover all 3 aspects:

1. We start using standard Python & pip for our preferred installation instructions.

2. We also provide instructions for Miniconda.

3. A lot of (esp Windows users) might already have Anaconda installed, due to historic reasons or because it is pervasive for data science, especially on Windows.. We explain why that may cause slowdowns and if it causes slowdowns for them, walk them through using a conda environment and installing things in that.

**Comment by agramfort** [comment]
before making such a decision let me share my experience.

when I teach and folks just took python from python.org things can do bad
too.

- what if you want to install spyder? is it a smooth install?

- anaconda is just one folder. Removing it is just removing the folder.
It's much
less invasive on the system. You can also install without admin privileges.

what if you want to install more things than nilearn later like things that
require
compilers on windows?

personally I use anaconda environments with bare minimum and then use pip
as much
as possible. it gives me more flexibility.

**Comment by kchawla-pi** [comment]
Overall, I think the most acceptable solution is as Elizabeth suggests, using Miniconda. It allows what you indicated and is fast for workshops.

We should cover all 3 cases (PyPI, Miniconda, Anaconda) and give context specific recommendations and that will help people decide how best to use it.

We can't take responsibility for how people will use everything down the line. If a user wants to install binaries and stuff, like INtel's MKL, they will have to do the due diligence and read up about it. Including the 3 installation scenarios will help them decide in the beginning or help them change their environments later on if they need to.

To maintain focus, this issue for Windows only, and primarily for conducting workshops.
The most straightforward way for workshops is to use conda or miniconda to create a conda environment and then install into that.
If we document this step on the Nilearn website, users can quickly refer to it and not get stuck or confused.

I am not talking about using virtual envs as good practices but simply because it will simplify all this issue.

**Comment by kchawla-pi** [comment]
Also, Python does not need admin rights on Windows if one doesn't choose to install it for all users.

On windows, uninstalling Python from PyPI is no more difficult than uninstalling Anaconda.

**Comment by GaelVaroquaux** [comment]
I'm a bit worried about recommending the vanilla Python. It comes with so
little that we would be putting burden on our users.

**Comment by kchawla-pi** [comment]
What more do we need?

**Comment by kchawla-pi** [comment]
All our tests are run by pip and standard python AFAICT.
Whatever we need for the workshops can be specified in the requirements file.
If there are any extra binaries necessary what are they?

**Comment by GaelVaroquaux** [comment]
> What more do we need?

Users need more: jupyter, an editor, maybe other scientific packages.

**Comment by kchawla-pi** [comment]
Jupyter is available via pip. Editor? For the workshop we use jupyter notebooks. They can always install their own editors afterwards.
Do you have other ideas about streamlining installations for workshops?
(How about we support anaconda officially then, if it's so useful, instead of depending on conda-forge?)

**Comment by kchawla-pi** [comment]
I'm gravitating towards recommending miniconda and a list of optional packages such as Spyder etc if anyone needs to. use them.

**Comment by ymzayek** [comment]
Closing this since we don't recommend Anaconda anymore in our docs
