### ISSUE TITLE
[Quality] Duplication: nilearn/regions/signal_extraction.py

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2250]
The following lines in [nilearn/regions/signal_extraction.py](https://github.com/nilearn/nilearn/blob/master/nilearn/regions/signal_extraction.py) are duplicated and should be refactored:

Lines 100-116, 183-200

https://github.com/nilearn/nilearn/blob/7fd55bad75a087ac591edf4c00c85a5806a1c461/nilearn/regions/signal_extraction.py#L100-L116

https://github.com/nilearn/nilearn/blob/7fd55bad75a087ac591edf4c00c85a5806a1c461/nilearn/regions/signal_extraction.py#L183-L200

**Comment by jbteves** [comment]
By refactored, in this case do you mean you'd like a function which does these things called twice instead of near-verbatim code repeat?

**Comment by KranthiGV** [comment]
@kchawla-pi I'm interested in working on this. Can I do that?

**Comment by kchawla-pi** [comment]
@jeromedockes @emdupre

**Comment by kchawla-pi** [comment]
@jeromedockes @emdupre

**Comment by bthirion** [comment]
@jbteves duplicated code should be in a private function called whenever needed.
Both you @KranthiGV are welcome indeed !

**Comment by ChristianGerloff** [comment]
Hey @NicolasGensollen, if that's fine for you, I could take the issue

**Comment by bthirion** [comment]
Thx ! let us know if you need help.

**Comment by ChristianGerloff** [comment]
alright, thx
