### ISSUE TITLE
[Maint] Removing deprecations in html_connectome

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2252]
There are a few deprecations which need to be removed in [`nilearn.plotting.html_connectome`](https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/html_connectome.py)

https://github.com/nilearn/nilearn/blob/7fd55bad75a087ac591edf4c00c85a5806a1c461/nilearn/plotting/html_connectome.py#L102-L110
https://github.com/nilearn/nilearn/blob/7fd55bad75a087ac591edf4c00c85a5806a1c461/nilearn/plotting/html_connectome.py#L202-L207

These two were added 10 months ago and released with 0.5.1 .

If anyone thinks we need to give users more time and defer the removal, mention it immediately. I will file a PR today and will merge it soon, probably tomorrow.

**Comment by kchawla-pi** [comment]
@emdupre @GaelVaroquaux

**Comment by emdupre** [comment]
If this was decided as the deprecation date, then I think it makes sense to stick with it. 

Thanks for bringing this up !
