### ISSUE TITLE
Strange comment in ICA example

### ISSUE THREAD

**Issue by swaythe** [nilearn/nilearn#2259]
This is the comment:
# XXX: must get the code to run for more than 1 subject
And this is the link to the example:
https://nilearn.github.io/auto_examples/05_advanced/plot_ica_resting_state.html

The comment appears to relate to an internal todo rather than comment/instruction to users.

**Comment by emdupre** [comment]
Great catch -- thanks for pointing this out, @swaythe !

Just opened #2264 to patch it, in case you'd like to review :smile_cat:
