### ISSUE TITLE
Possible break in fetch_development_fmri

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2266]
@AkiNikolaidis Reported that when he runs the example https://nilearn.github.io/auto_examples/03_connectivity/plot_data_driven_parcellations.html#sphx-glr-au

Then the line 
```python
dataset = datasets.fetch_development_fmri(n_subjects=1)
```
raises
```python
module 'nilearn.datasets' has no attribute 'fetch_development_fmri'
```
Is this right Aki?

**Comment by AkiNikolaidis** [comment]
That's correct! I think it's my mistake however-  I had updated my python version but forgot to quit and reopen the python notebook.

**Comment by AkiNikolaidis** [comment]
It's working now since updating everything!

**Comment by kchawla-pi** [comment]
Okay! I'll close this then.
