### ISSUE TITLE
Improve test fixtures for temporary paths

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2268]
Required for removing nosetests.

A lot of tests in Nilearn tests do not clean up after themselves. They create files and directories which should be temporary but don't delete them afterwards.
This is at least in part because the temporary dirs & files are not programmed to clean up after themselves. This includes the nose fixtures which create temp paths for tests to use.
The nose fixture will be gone once we remove nose calls.

Considerations:
1. There should be one fixture that creates and tears down temporary directories and their contents.
2. It should remove references to file handles in memory before trying to delete the files, or tear down will fail on Windows.
3. It should be pytest supported.

**Comment by jeromedockes** [comment]
use `tmp_path` fixture from pytest

**Comment by jeromedockes** [comment]
http://doc.pytest.org/en/latest/tmpdir.html

**Comment by kchawla-pi** [comment]
I am using `tmp_path` for the temp dir functionality, but we also need to clean up references when using tests in windows, which is what I have added.

**Comment by kchawla-pi** [comment]
Ah wait this is an issue not the PR. Hav a look at PR #2269 . In that I am using a custom fixture which uses tmp_path with some added functionality.

**Comment by NicolasGensollen** [comment]
Shouldn't we close this? It looks like it was taken care of in #2269, right?

**Comment by jeromedockes** [comment]
yes, closing
