### ISSUE TITLE
Add a fetcher for the Melbourne Subcortex Atlas

### ISSUE THREAD

**Issue by dangom** [nilearn/nilearn#2273]
What would you like changed/added and why?

A fetcher for the [recently released](https://twitter.com/DrBreaky/status/1206560282488668165) melbourne hierarchical [subcortical atlas](https://github.com/yetianmed/subcortex).
I could take this issue eventually unless someone else would like to volunteer to do so.

What would be the benefit? Does the change make something easier to use?

To my knowledge, there aren't that many multiscale subcortical atlases out there (except perhaps the [MIST atlas](https://mniopenresearch.org/articles/1-3), for which we could add a fetcher too), so this would be a nice addition..

If it is a new feature, what is the benefit? 
Easy access to a multiscale subcortical parcellation in 3T/7T versions.

**Comment by kchawla-pi** [comment]
Others will comment on adding this.

If we were to incorporate this, will we also need a good example showcasing its use.
How large is the  download? Will it need to be pared down?

**Comment by dangom** [comment]
Whole repo weights 40MB. There are both CIFTIs and NIFTIs, but I suppose support for NIfTIs only is a good start, in which case we're looking at 18MB.

**Comment by jeromedockes** [comment]
Isn't there the Harvard-Oxford subcortical atlas in nilearn? I am not
opposed to adding an atlas but the main goal of the fetchers is to
provide data for the example gallery; users can also download data
outside of nilearn. Which example would be improved / which features
would be better showcased with this additional fetcher? I worry a bit
about adding many fetchers because as they depend on external resources
they tend to require more maintenance and break or slow down the CI more
frequently than the rest of the library.

**Comment by dangom** [comment]
I see. I thought the fetchers were a convenience so that users can try different analysis and have access to atlas in different spaces. The Harvard-Oxford offers a course subcortical atlas, but only 21 regions. It doesn't provide a parcellation of each individual structure (no thalamic parcellation, for example), which could be very useful for those dealing with high res data. The Harvard-Oxford was also generated anatomically from ~40 people - not really a population.

But sure, I see the reasoning behind avoiding extra fetchers.

**Comment by Remi-Gau** [comment]
Was discussed at the last core dev meeting and decided that this is out of scope for Nilearn:

We have updated the documentation to make our policy regarding adding new atlases more obvious (note this is not a change in policy just trying to make it easier to point to) and also pointing to other projects that may accept atlas contribution: 

https://nilearn.github.io/dev/development.html#adding-atlases-and-datasets
