### ISSUE TITLE
Nilearn.masking.compute_gray_matter_mask does not output gray matter mask

### ISSUE THREAD

**Issue by JohannesWiesner** [nilearn/nilearn#2280]
As discussed with @bthirion and @jeromedockes I open this issue about `nilearn.masking_compute_gray_matter_mask`. The issue was already discussed on [neurostars](https://neurostars.org/t/nilearn-masking-compute-gray-matter-mask-does-not-output-gray-matter-mask/5505). To wrap this up in short for everyone who hasn't read it on neurostars: Although `nilearn.masking_compute_gray_matter_mask` suggests, that a **gray matter mask** is used for masking the images, it is actually a **whole brain matter mask**. This certainly can make a difference for the analysis because both grey **and white** matter are included then. This is normally not wanted by the user as in most cases you would preprocess and analyze grey and white matter images separately. 

Bertrand came up with two possible solutions:

> 1. Either we consider that a brain mask is OK, and we view this as a documentation bug
> 2. Or we consider that a gray matter mask is really important and we should add options.

If we choose the first option, (i) the documentation has to be changed and (ii) also the function name should be changed to something like `compute_whole_brain_mask` or `compute_whole_brain_matter_mask` to make it clear to the user, what the function does. 

If the second option is chosen, the function has to output a proper grey matter mask. 

_But for now  - Merry Christmas to Everyone and a Happy New Year!_

**Comment by bthirion** [comment]
Thx. In any case, we would like to keep a mask for the whole brain.
Besides that, I agree with all you write.
And indeed, - Merry Christmas and a Happy New Year!

**Comment by GaelVaroquaux** [comment]
IMHO this is a documentation / naming bug. I am not opposed to renaming
(and fixing the documentation), with a proper deprecation cycle.

**Comment by alpinho** [comment]
I am planning to work on this issue. What solution shall I choose?

**Comment by bthirion** [comment]
So renaming and deprecation cycle.

**Comment by tsalo** [comment]
I believe that this can be closed now that #2459 has been merged.

**Comment by thomasbazeille** [comment]
Thanks a lot @tsalo for the good catch ! Closing
