### ISSUE TITLE
nilearn.signal.clean modifies input when "session" parameter used.

### ISSUE THREAD

**Issue by drorcohengithub** [nilearn/nilearn#2281]
Hi guys, 

[docs](https://nilearn.github.io/modules/generated/nilearn.signal.clean.html) for nilearn.signal.clean say: 

"signals: numpy.ndarray
Timeseries. Must have shape (instant number, features number). **This array is not modified**."

However, I find that if the session parameter is used the input array **is** modified. 

Code to reproduce:
```
# make random data
np.random.seed(1)
nsamp = 1000
data_source= np.random.rand(nsamp)
confound= np.random.rand(nsamp)
data_observed_orig = data_source + confound
data_observed_input = data_observed_orig.copy()
print(np.corrcoef(data_observed_orig,confound)[0,1]**2) # theoretically 0.5
sessions_desc = np.ones(nsamp)
sessions_desc[0:nsamp//2]=0

data_cleaned_concat = nil.signal.clean(data_observed_input[:,np.newaxis],
                                       confounds=confound[:,np.newaxis],sessions=sessions_desc)
#should be True
np.all(data_observed_input == data_observed_orig)
```
output:
0.5228211029311932
False

Only happens if the session parameter is provided. In fact, the input data seems to change to something like the output, but not exactly. 

nil version 0.6.0

**Comment by bthirion** [comment]
Sorry, we haven't been able to look at that.
Would you be kind enough to localize the issue and propose a PR ?
Thx a lot,

**Comment by drorcohengithub** [comment]
I think the issue is to do with the recursion when using the sessions parameter, since the output of the recursion is the original input, not a copy.

An easy fix would be to copy the input early on.

Currently, the input is copied if ensure_finite=True, but this is not the default behaviour. So another solution is just to make this default.

Alternatively, we could just change the description and remove the "This array is not modified". For me the issue is not the inplace modification, but the inconsistency with the docs.

**Comment by bthirion** [comment]
I'd rather go for keeping the input array untouched. This is not a strong opinion though.

**Comment by drorcohengithub** [comment]
ok then easiest thing is just to copy it early on. If you have no other requests/comments then I can get on to the PR

**Comment by bthirion** [comment]
+1 on my side.
You'll have to add a test that fails with current implementation, but works with the new one.
