### ISSUE TITLE
Add Binder links to examples

### ISSUE THREAD

**Issue by emdupre** [nilearn/nilearn#2284]
I just noticed that the sklearn documentation includes Binder links (for example, [here](https://scikit-learn.org/stable/auto_examples/linear_model/plot_lasso_and_elasticnet.html#sphx-glr-auto-examples-linear-model-plot-lasso-and-elasticnet-py)). It'd be great to have these in Nilearn as well, so users could run our examples on Binder !

I can open a PR if that's of interest :smile_cat: I'll plan to build off https://github.com/scikit-learn/scikit-learn/pull/11221 and a few updates that it looks like have been [merged since then](https://github.com/scikit-learn/scikit-learn/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+binder).

**Comment by kchawla-pi** [comment]
DO IT DO IT DO IT DO IT

**Comment by bthirion** [comment]
No opinion on that, since I'm not using Binder, but if people like it, I'm fine with it.

**Comment by GaelVaroquaux** [comment]
+1. Go for it. Sphinx-gallery has support for this (if you struggle understand the sphinx-gallery docs on this, please submit PR/suggestions on how to improve it).

Thanks!!!!

**Comment by emdupre** [comment]
In #2300 I've been exploring using Jupytext to directly launch the Python files housed in the current repository, but as @GaelVaroquaux noted: given that we serve our documentation from a separate, built `nilearn.github.io` repository, we should be the ideal audience for the current Binder integration in Sphinx Gallery.

To do this, though, we'll need to re-build the documentation with Binder enabled. Once that's done, an `examples` folder should be generated with the generated .ipynb files in the same structure as `auto_examples` (cf. the [most recent artifacts](https://circleci.com/gh/nilearn/nilearn/5264#artifacts/containers/0) from #2300). I can then update the `conf.py` file of _this_ repository to point to the generated notebooks.

So, my current question is: What's the best way to achieve a re-build of the documentation with Binder enabled ? I'm not entirely clear on the process by which they're built at present, so any insight would be appreciated !

**Comment by GaelVaroquaux** [comment]
> So, my current question is: What's the best way to achieve a re-build of the
> documentation with Binder enabled ?

To prototype, I would push them to something like a github pages branch
on your github.

> I'm not entirely clear on the process by which they're built at present,

Manually, via "make install" in the doc folder.

**Comment by emdupre** [comment]
> Manually, via "make install" in the doc folder.

Sorry, I was unclear. I meant the process by which you decide to update the docs -- ie only at a release.

**Comment by kchawla-pi** [comment]
Whenever we do a new stable release, we update the docs website.

**Comment by kchawla-pi** [comment]
So we didn't update the website when we released 0.6.0a and b, but we did when releasing 0.6.0, 0.6.1 and so on.
We use the `make install` command from the docs directory at that time. You need write access to push to the repo https://github.com/nilearn/nilearn.github.io . I'll check and give it to you today sometime.

That's the process.

If you are asking whether we should push the new docs now, well if we have not merged anything new in master except this PR, then we can consider it, since it will only add the Binder links.

**Comment by GaelVaroquaux** [comment]
> well if we have not merged anything new in master except this PR, then
> we can consider it, since it will only add the Binder links.

+1!

The drawback of updating the docs often is that it loads the git repo a
lot (which makes it hard for binder to clone it).

To avoid that, something that would be good would be to do might be to
have something that forgets the history and force pushes in "make
install". I know that other projects have that.

**Comment by GaelVaroquaux** [comment]
> To avoid that, something that would be good would be to do might be to have something that forgets the history and force pushes in "make install". I know that other projects have that.

I couldn't find an example with a quick search, though

**Comment by emdupre** [comment]
OK, I just wanted to re-cap the conversation that @GaelVaroquaux and I had earlier this afternoon so everyone is in sync about the plan for moving forward.

I'm going to re-direct #2300 to drop the Jupytext patch in favor of pointing to the Sphinx Gallery generated notebooks. These do not yet exist on `nilearn.github.io`, as that documentation was built  without Binder configuration enabled. 

I see two immediate next steps to get #2300 merged:

1. I will try to build the documentation, host it on the `gh-pages` branch of my personal Nilearn fork, and confirm that Binder works as expected there. 
2. I will work on updating the CSS rules for the "download note" on each example, since with the extra Binder-related text it can now overlap with the example itself (see https://github.com/nilearn/nilearn/pull/2300#issuecomment-580062128)

Once these are done, I'll update the Binder configuration in #2300 to point to `nilearn.github.io`, build the documentation using that PR, and push the resulting built files to that repository. We can then merge in #2300.

In parallel, @GaelVaroquaux will look into updating the [`_set_mpl_backend`](https://github.com/nilearn/nilearn/blob/e447a7041ea7dcd4117b8375282b1fe561ee73e1/nilearn/plotting/__init__.py#L12) function to account for the `%matplotlib inline` magic, since we discovered it wasn't playing nicely with Jupyter.

Does that sound right, @GaelVaroquaux ? Any other suggestions or concerns ?
