### ISSUE TITLE
Speeding up docs building

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2286]
Currently CircleCI takes at least 1.5hrs to fully build the docs.
With addition of Nistats documentation this will become >2hrs.

To speed this up within PRs, currently the docs are built once a day or when a new PR is opened, the built docs are cached and for the rest of the day subsequent pushes to the PR branch do not rebuild the full docs. This cuts down the build time to ~5minutes.
The resulting build from existing cache to relies on sphinx-gallery autodetecting the changed files and rebuilding the differences. However, for whatever reason, this is not very reliable. I have seen examples where the changes in text for example are not reflected in the build.

If anyone has any ideas about this please share them. If this is a case of misunderstanding or misconfiguration, I would like to know and fix it.

Meanwhile, based on what MNE-Python does and what Scikit-Learn does, I intend to implement the processes they use.
Once a cache has been restored,
 - When a non-example .py file changes, make HTML is built with the no-plot option.
 - When an example file changes, that specific example is rerun and rebuilt from scratch.

For restoring the built-docs cache, I am thinking I will create a mechanism to use the docs built in master branch, but that is secondary goal.

**Comment by ymzayek** [comment]
@NicolasGensollen I'm wondering if we can close this?
It seems related to #1984. 

But the second part, I'm not sure I understand very well. Something to look into still?
> Meanwhile, based on what MNE-Python does and what Scikit-Learn does, I intend to implement the processes they use.
> Once a cache has been restored,
>
>    * When a non-example .py file changes, make HTML is built with the no-plot option.
>    * When an example file changes, that specific example is rerun and rebuilt from scratch.
>
> For restoring the built-docs cache, I am thinking I will create a mechanism to use the docs built in master branch, but that is secondary goal.

**Comment by bthirion** [comment]
Agreed. I propose that we close it for now. Of course, the process remains expensive and we should think how to make it more efficient.
