### ISSUE TITLE
offscreen rendering

### ISSUE THREAD

**Issue by rb643** [nilearn/nilearn#2287]
Hi all,

I've just started using nil earn mainly to create some qc plots for my existing pipeline as it seems very efficient and fast at doing so. Unfortunately I don't seem to be able to find a way to render plots offscreen with the plotting tools (though very likely I'm just missing something) and since I'm working on a high performance cluster submitting this as batch jobs for a very large dataset it would be much more efficient if I did not have to open a temporary display explicitly every iteration where I generate a plot.

For example is there a way to do this:
display = plotting.plot_anat(argv[1]) 
display.add_overlay(argv[2], cmap=plotting.cm.black_red) 

display.savefig('QC_checkreg.png')
display.close()

But offscreen :)

Cheers,

Richard

**Comment by GaelVaroquaux** [comment]
You need to setup up matplotlib to use a backend that does not require an X server
https://stackoverflow.com/questions/4931376/generating-matplotlib-graphs-without-a-running-x-server

**Comment by thomasbazeille** [comment]
I think this can be closed ! For other usage questions like this one, don't hesitate to ask on Neurostars forum which is a better place.

**Comment by jeromedockes** [comment]
@rb643 was your problem solved?

**Comment by rb643** [comment]
Yeah all solved!
