### ISSUE TITLE
ENH: Surface contours on statistical maps

### ISSUE THREAD

**Issue by mjboos** [nilearn/nilearn#2295]
Hello all,
I love the nilearn surface plots for their ease of use, but often wish I could add the outline of a cortical region to the surface plot of a statistical map. I.e. like such
![Surface_Contours_1_1](https://user-images.githubusercontent.com/7125006/73030248-38fcb480-3e07-11ea-9dfc-05b81849ef16.png)

I've recently implemented a simple version of this [here](https://mjboos.github.io/Nilearn-surface-contours/). The problem is that the only way how to add such outlines is via editing the corresponding facecolors, therefore contours can never appear as a matplotlib artist and information from the original stat map will be lost.

My question is if you think it is worth adding this feature anyway, it certainly was helpful to me and could be to others. If so, I could open a PR.

**Comment by bthirion** [comment]
If there is no better way to do this (looks like it is the case), I think it's worth adding the functionality (together with an example).
Thx,

**Comment by GaelVaroquaux** [comment]
I'm with Bertrand: send it along! (with tests and an addition to an
existing example).

**Comment by mjboos** [comment]
Hi all, I will tackle this during the Nilearn dev days!

**Comment by jeromedockes** [comment]
note that in the javascript plots it can be done by really drawing lines rather than changing some values in the stat map -- I would maybe start there

**Comment by jeromedockes** [comment]
or actually even a line plot in matplotlib might work?

**Comment by mjboos** [comment]
Thanks for the suggestions @jeromedockes 
I was thinking about Line3DCollection as well, but don't see a way of making it work ATM.
Not to get into too much details, but Axes3D hard codes the assignment of the plotting order based on the minimum z-value in each collection (so Line3DCollection & trisurf's Poly3DCollection), resulting in the Poly3DCollection always being plotted last and hence hiding the countour lines.
I don't see a way of changing it without it being too hacky, but am glad if you have a suggestion.

I'll see if I can get it working in the Javascript version as well.

**Comment by jeromedockes** [comment]
Ok, thanks! I had a quick IRL discussion with Moritz and it seems this
is a long-standing issue in matplotlib. In this case let's go for the
proposed solution: color some triangles of the map itself.
