### ISSUE TITLE
datasets.fetch_atlas_smith_2009()  -- SSL Certificate on Remote Server not valid

### ISSUE THREAD

**Issue by AxelBangert** [nilearn/nilearn#2296]
if url is None:
        if mirror == 'origin':
            url = "http://www.fmrib.ox.ac.uk/datasets/brainmap+rsns/"
        elif mirror == 'nitrc':
            url = [
                    'https://www.nitrc.org/frs/download.php/7730/',
                    'https://www.nitrc.org/frs/download.php/7729/',
                    'https://www.nitrc.org/frs/download.php/7731/',
                    'https://www.nitrc.org/frs/download.php/7726/',
                    'https://www.nitrc.org/frs/download.php/7728/',
                    'https://www.nitrc.org/frs/download.php/7727/',
            ]
        else:
            raise ValueError('Unknown mirror "%s". Mirror must be "origin" '
                'or "nitrc"' % str(mirror))

**Comment by emdupre** [comment]
Hi @AxelBangert --

Thanks for reporting ! To help us address this, could you include a little more information such as the version of Nilearn you're using, a minimal working example to reproduce your error, as well as the exact error you're encountering. 

The [issue template](https://raw.githubusercontent.com/nilearn/nilearn/master/.github/ISSUE_TEMPLATE/bug_report.md) &mdash; which should have pre-populated the box when you went to open this issue &mdash; has a nice description of the information we need.

**Comment by AxelBangert** [comment]
Hi,
I am on 
Win7 x64 English
Python 3.7.2 rc1
NiLearn 0.6.1
 
It only happens with: nilearn.datasets.fetch_atlas_smith_2009()
All the other fetches are working without error

Best Axel

**Comment by emdupre** [comment]
Hi @AxelBangert  --

Sorry for the delay, here ! Were you eventually able to access the dataset ? It seems to download without issue, currently, so please feel free to close this issue if that matches your experience. If not, please let us know what the exact error message is and we can look more closely at this.

Thanks !

**Comment by AxelBangert** [comment]
Hi,
it seems to depend on numpy. Look at the screenshot.
![NILearn-Numpy-ErrorGitHub](https://user-images.githubusercontent.com/11486866/77901118-5c1c6800-727f-11ea-983d-6f31b4a2659a.png)

**Comment by emdupre** [comment]
Thanks for following up ! Your current solution works in that it's no longer verifying the certificate, but to address the underlying issue directly we'd need to add the missing certificate(s) to your local system.

Could you try running the `Certificates.command` in your local python installation ? See [this answer](https://stackoverflow.com/a/45018725), updating the path for your machine.

**Comment by AxelBangert** [comment]
:)
