### ISSUE TITLE
Reorganizing Nistats code within Nilearn

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2298]
In the process of incorporating Nistats into Nilearn, we need to decide where to place the code and the examples.

One approach is a hard line between nilearn and nilearn.stats, where we treat the latter as a separate product within Nilearn, in terms of organization and layout of files and examples. This was my original vision, but it seems very artificial.

Other is to redistribute Nistats code and examples within Nilearn. So far I am more inclined to this.
This would entail, moving `nistats.datasets` code into `nilearn.datasets.func.py` code. `nistats.reporting` code into `nilearn.reporting` code.

For examples, I was more concerned, but @bthirion suggested a scheme which seems good to me.
It may entail rewriting some of the documentation text to tie it together.

According to this scheme, we move:

`nistats/examples/01_tutorials/*.py` -> `nilearn/examples/`
`nistats/examples/05_complete_examples/*.py` -> `nilearn/examples/05_advanced`
`nistats/examples/02_first_level_models` -> `nilearn/examples/`
`nistats/examples/03_second_level_models` -> `nilearn/examples/`
`nistats/examples/04_low_level_functions` -> across the first and second level model examples.

I think this will be straightforward to do and seems logical to me.

Over to you @GaelVaroquaux .
Whatever we decide, if we can discuss it quickly & iterate on it, that would be good.

**Comment by GaelVaroquaux** [comment]
> moving nistats.datasets code into nilearn.datasets.func.py code. nistats.reporting code into nilearn.reporting code.

Yes, this sounds right!

> nistats/examples/01_tutorials/*.py -> nilearn/examples/

Probably. But there needs to be no more than a couple.

> nistats/examples/05_complete_examples/*.py -> nilearn/examples/05_advanced

I think that that folder is getting too big. We need to break it down,
maybe with subfolders.

> nistats/examples/02_first_level_models -> nilearn/examples/
> nistats/examples/03_second_level_models -> nilearn/examples/

I think that these need to go in a stats folder. We would have decoding,
functional connectivity and stats, which seems a reasonable breakdown to
me.

> nistats/examples/04_low_level_functions -> across the first and second level
> model examples.

Sounds good!

**Comment by bthirion** [comment]
> I think that these need to go in a stats folder. We would have decoding, functional connectivity and stats, which seems a reasonable breakdown to me.

But then would you put first-level and second-level altogether, or introduce subdirs ? (see my comments below ?)

>  nistats/examples/05_complete_examples/*.py -> nilearn/examples/05_advanced
> I think that that folder is getting too big. We need to break it down, maybe with subfolders.

But isn't this too much nesting then ?

My gut feeling is that we should avoid too much nesting in the examples.

**Comment by GaelVaroquaux** [comment]
I think that we need nesting. Or rather subsections, which may be achievable with  a trick using different header title  hierarchies in the readme.txt of each fodder. Right now, there are too many examples listed with no good order or good hierarchy, and it's overwhelming 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by emdupre** [comment]
Would it make sense to first merge without the reorganization s.t. we could retain the git history and then settle on a new organization once all the material is brought over ? It seems a shame to lose the history of everyone who has contributed to Nistats !

**Comment by kchawla-pi** [comment]
> It seems a shame to lose the history of everyone who has contributed to Nistats !

I believe that can be done, as per this answer on SO: https://stackoverflow.com/a/8396318/5397214

I can create a new branch in Nistats and reorganize that branch to mirror Nilearn, then do the above thing into a new PR. If we add something to Nistats after that, I can pull the changes into this reorg branch and then pull the reorg branch into Nilearn. 

Eventually we merge this PR. Also, I think this should work the way I described, but there might be hiccups.
Another option is to do the SO answer in a new Nilearn branch, followed by the reorg in that Nilearn branch and merge that. Figure out later how to pull any subsequent changes in Nistats.
