### ISSUE TITLE
Different results when using `resample_to_img` function

### ISSUE THREAD

**Issue by mdiazmel** [nilearn/nilearn#2305]
Hi,
I've been trying to use the `resample_to_img` function to crop a T1 image based on a template. Both image are previously aligned.  Every works fine using **nilearn v.0.5.0**:

```
crop_img = resample_to_img(input_img, crop_template)
plot_anat(crop_img)
```
produces:
![np050](https://user-images.githubusercontent.com/9074823/74022995-ee4e7100-499e-11ea-95f0-8dac5627090f.png)

but when executing the same code (and the same inputs) with **nilearn v0.6.1**, the output image is not cropped at the right values:
![np061](https://user-images.githubusercontent.com/9074823/74023135-31104900-499f-11ea-8e2b-192feb621ef3.png)

It seems that there was some refactoring work on the file `nilearn/image/resampling.py` at the commit ee1f25a908d8357b4fba84dab1d2b7018e9f5e04 . It's maybe related to the changes on the behavior of this function?

Thanks in advance,

**Comment by jeromedockes** [comment]
Thanks for reporting! I will try to have a look.
could you by any chance share the images and a script to reproduce?

**Comment by mdiazmel** [comment]
Yes, of course. Files can be (temporary) available [here](https://framadrop.org/r/bYM9ZRI7uN#pROaifeZOOj3njUjlaMJEt104RzCG6LJ8HcWrViLP/0=).
The following snippet will reproduce the code (try it with both versions):
```
from nilearn.image import resample_img, crop_img, resample_to_img
from nilearn.plotting import plot_anat
input_img = './inputs/input_img.nii.gz'
crop_template = './inputs/ref_cropped_template.nii.gz'
crop_img = resample_to_img(input_img, crop_template)
plot_anat(crop_img)
```
@jeromedockes : if I can do any thing else, don't hesitate to tell me, but I'm pretty new with `nilearn` and I don't known exactly where to start debugging this function.

**Comment by jeromedockes** [comment]
> @jeromedockes : if I can do any thing else, don't hesitate to tell me, but I'm pretty new with `nilearn` and I don't known exactly where to start debugging this function. 
Thanks a lot for your help, I will let you know if I have more questions!

**Comment by bthirion** [comment]
I can reproduce the bug, but I don't have the fix yet...

**Comment by jeromedockes** [comment]
sorry for taking so long to get back to this. the bug was introduced in #2025 . i will try to open a pr today

**Comment by jeromedockes** [comment]
note that in the meanwhile you can fix your problem by passing `force_resample=True` to `resample_to_img`

**Comment by NicolasGensollen** [comment]
Has this bug been addressed? 
I cannot reproduce since the files are not available anymore, but the changes introduced in #2025 are still there AFAICT.

**Comment by jeromedockes** [comment]
@NicolasGensollen  AFAIK it hasn't been addressed

**Comment by ajoshiusc** [comment]
I encountered this bug today. While the bug is being fixed, force_resample=True should be made default for the functions resample_img and resample_to_img.
The force_resample=False which is currently default, the code is not implemented correctly and I see lot of #TODO flags in the code for force_resample=False case.

**Comment by ajoshiusc** [comment]
Created [PR](https://github.com/nilearn/nilearn/pull/4412). thanks,
