### ISSUE TITLE
Remove the `n_subjects` param from `fetch_haxby` in the next release

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2309]
Looking at that other docstring, it looks like we should also remove the `n_subjects` param from `fetch_haxby` in the next release :laughing: 

Should I update that deprecation warning in this PR, too ?

_Originally posted by @emdupre in https://github.com/nilearn/nilearn/pull/2256#issuecomment-562719797_

**Comment by emdupre** [comment]
This was handled in #2279 !

**Comment by kchawla-pi** [comment]
Whoops
