### ISSUE TITLE
Add white-matter surfaces (lh.smoothwm and lh.white) to fetch_surf_fsaverage 

### ISSUE THREAD

**Issue by braincharter** [nilearn/nilearn#2313]
Hi!
It would be nice to add the white-matter surfaces from freesurfer (call lh.smoothwm and lh.white) to fetch_surf_fsaverage as well. 

I'm interested in investigating the vessels located on the gm/wm border on a group of subjects, as well as fMRI maps on that location. As for now I am using my own surface computed from one subject, but adding those to fetch_surf_fsaverage would really simplify the process (and make it more consistent across subjects).

**Comment by jeromedockes** [comment]
It could also be useful to select points between the pial and wm
surfaces for the volume -> surface projections

**Comment by bthirion** [comment]
I'm +0
on the negative side, data download is our first cause of ci breakage (but not particularly from nitrc), and I guess that only few users would require both surfaces.
Maybe @jeromedockes has one: being able to perform 'layer-dependent' projection (or mapping).
Any other opinion ?

**Comment by braincharter** [comment]
I think that exactly for layer-dependent projection a lot of users would gain interest in the surf features!
Or it could be another function completely (fetch_surf_fsaverage_wm).

By the way, how were those surfaces computed? By running recon-all on ICBM_MNI_2009?

**Comment by bthirion** [comment]
No, I guess that it's a freesurfer-made average of individual mesh, but I'm not an exepert in freesurfer.

**Comment by jeromedockes** [comment]
that was done in #2517
