### ISSUE TITLE
Merge two decoder examples

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#2319]
We have two examples that are quite redundant:
plot_decoding_tutorial.py and 02_decoding/plot_haxby_decoder.py
visible on:
* https://5331-1235740-gh.circle-artifacts.com/0/doc/_build/html/auto_examples/plot_decoding_tutorial.html#sphx-glr-auto-examples-plot-decoding-tutorial-py
* https://5331-1235740-gh.circle-artifacts.com/0/doc/_build/html/auto_examples/02_decoding/plot_haxby_decoder.html#sphx-glr-auto-examples-02-decoding-plot-haxby-decoder-py

I suggest that we get rid of the non tutorial one (02_decoding/plot_haxby_decoder.py), in order to decrease maintenance and build load. I do not think that it adds something important to the tutorial one.

@tbng , what do you think?

**Comment by bthirion** [comment]
Agreed.

**Comment by tbng** [comment]
Yeah I think it would be neat to do so, should be straightforward as well.
@GaelVaroquaux: about the comment switching to pandas in the `plot_decoding_tutorial.py` example, do you mean the idea is to exclusively use pandas and get rid of numpy import?

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux: about the comment switching to pandas in the
> plot_decoding_tutorial.py example, do you mean the idea is to exclusively use
> pandas and get rid of numpy import?

Yes; but not be religious about it: if some things are done better with
pandas, use it.

**Comment by GaelVaroquaux** [comment]
> Yes; but not be religious about it: if some things are done better with pandas, use it.

Typo: I meant "numpy" in the above

**Comment by tbng** [comment]
Addressing this in #2323

**Comment by emdupre** [comment]
Closed with #2323 :rocket:
