### ISSUE TITLE
Test failure in surface plotting with the latest matplotlib version?

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#2330]
With seem to have test failures with the CIs that appeared recently:
https://travis-ci.org/nilearn/nilearn/jobs/660088664#L6059

I suspect that they are related to a matplotlib release.

**Comment by thomasbazeille** [comment]
I think @jeromedockes  adressed this one recently and it can be closed ?

**Comment by jeromedockes** [comment]
yes in #2335 I think
