### ISSUE TITLE
Dataset Import Error

### ISSUE THREAD

**Issue by deepakkochhar11** [nilearn/nilearn#2333]
**nilearn.datasets.fetch_oasis_vbm** is continuously throwing 403 Forbidden error while trying to fetch the oasis dataset.

I think it is because of some changes in the original URL. I tried overriding the URL parameter but still, it's not working.

I am running this on google colab (but also tested it on the local machine and still got the same error) and I'm using - 
- nilearn==0.6.2
- nibabel==3.0.1

```
from nilearn import datasets
sample = datasets.fetch_oasis_vbm(n_subjects=10)
```

```
Downloading data from https://www.nitrc.org/frs/download.php/6364/archive_dartel.tgz ...
Error while fetching file archive_dartel.tgz; dataset fetching aborted.
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-20-967fff5465b8> in <module>()
----> 1 sample = datasets.fetch_oasis_vbm(n_subjects=10)

7 frames
/usr/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: Forbidden
```

**Comment by deepakkochhar11** [comment]
Can you please help with this, @KamalakerDadi ?

**Comment by jeromedockes** [comment]
hi @deepakkochhar11 thanks for reporting; indeed we are having a problem with all downloads from NITRC, this is being discussed in #2334

**Comment by KamalakerDadi** [comment]
>Can you please help with this, @KamalakerDadi ?

@deepakkochhar11 Can you try now?

**Comment by deepakkochhar11** [comment]
> > Can you please help with this, @KamalakerDadi ?
> 
> @deepakkochhar11 Can you try now?

I just ran this code and it is working for me now. No 403 Forbidden error this time.
```
from nilearn import datasets
n_subjects = 416
oasis_dataset = datasets.fetch_oasis_vbm(n_subjects=n_subjects)
```
Why did the error occur before?

Is it because of the change in download URLs or IP addresses being blocked owing to the repeated posting of requests to fetch data?

**Comment by KamalakerDadi** [comment]
May be a temporary network issue.

**Comment by KamalakerDadi** [comment]
@deepakkochhar11 please close this if you don't have any further queries.
