### ISSUE TITLE
Plot matrix throws a length mismatch error

### ISSUE THREAD

**Issue by araikes** [nilearn/nilearn#2346]
Greetings,
I'm attempting to learn and use Nilearn and was working through the signal extraction example (https://nilearn.github.io/auto_examples/03_connectivity/plot_signal_extraction.html#sphx-glr-auto-examples-03-connectivity-plot-signal-extraction-py). 

This example works if I use the Harvard Oxford atlas as in the example. However, if I attempt to use another parcellation (e.g., Schaefer 400), the plotting.plot_matrix call throws an error:

`ValueError: Length of labels unequal to length of matrix.`

Based on the code in matrix_plotting.py, the length of the labels item and the length of the correlation matrix match (both equal 400) so I'm not clear on why I'm getting this error. Plotting the correlation matrix without the labels/reordering works. I'm sure it's something simple in my understanding of Nilearn but any help would be appreciated.

Reprex:
```
from nilearn import datasets
dataset = datasets.fetch_atlas_schaefer_2018(n_rois = 400, 
                                             yeo_networks = 7)
atlas_filename = dataset.maps
labels = dataset.labels

print('Atlas ROIs are located in nifti image (4D) at: %s' %
      atlas_filename)  # 4D data

# One subject of brain development fmri data
data = datasets.fetch_development_fmri(n_subjects=1)
fmri_filenames = data.func[0]

from nilearn.input_data import NiftiLabelsMasker
masker = NiftiLabelsMasker(labels_img=atlas_filename, standardize=True,
                           memory='nilearn_cache', verbose=5)

# Here we go from nifti files to the signal time series in a numpy
# array. Note how we give confounds to be regressed out during signal
# extraction
time_series = masker.fit_transform(fmri_filenames, confounds=data.confounds)

from nilearn.connectome import ConnectivityMeasure
correlation_measure = ConnectivityMeasure(kind='correlation')
correlation_matrix = correlation_measure.fit_transform([time_series])[0]

# Plot the correlation matrix
import numpy as np
from nilearn import plotting
# Make a large figure
# Mask the main diagonal for visualization:
np.fill_diagonal(correlation_matrix, 0)
# The labels we have start with the background (0), hence we skip the
# first label
# matrices are ordered for block-like representation
plotting.plot_matrix(correlation_matrix, figure=(10, 8), labels=labels[1:],
                     vmax=0.8, vmin=-0.8, reorder=True)
```

Environment:
Fresh conda environment created yesterday with Python 3.7.6, nilearn=0.6.2, nistats=0.01b2 and relevant dependencies.

**Comment by bthirion** [comment]
if you give `labels=labels[1:]`, this makes 399 labels, not 400.

**Comment by araikes** [comment]
Yep... knew it was simple. Thanks @bthirion
