### ISSUE TITLE
Allow single image as input for nilearn.image clean_img

### ISSUE THREAD

**Issue by JohannesWiesner** [nilearn/nilearn#2350]
I use `nilearn.image.clean_img` to clean my single statistical image from NaNs and Infs. I discovered, that the function only allows for 4D images. This is, of course, a minor issue, as I just used `nilearn.image.clean_img(imgs=[my_statistical_image]`) to solve this problem. But I still thought I'd post it here. From a logical point of view, it would make sense to make this function also applicable to single images like statistical images.

**EDIT:**

I just discovered, that I also had to change the shape of the output image in my workaround, from (x,y,z,1) to (x,y,z), as, of course, the function right now is made for multiple 3D images. I used `index_image(cleaned_image,0)` for that

**Comment by bthirion** [comment]
Hi, I think that this type of comment should be in Neurostars.
But I don't undertsand what clearn_img is supposed to do on a single volume ? It does mostly (time-domain) signal processing.

**Comment by JohannesWiesner** [comment]
You're right. 

> But I don't undertsand what clearn_img is supposed to do on a single volume

I used it for a single **statistical image**, so in this case, it's only one  image. I thought it would be nice to have a function that could remove Nans and Infs from a single statistical image, but this problem is probably too specific and does not fit the purpose of this function, as a lot of its arguments don't make sense for a single image.

**Comment by GaelVaroquaux** [comment]
You could use things like:

nilearn.image.math_img('np.nantonum(img)', img=img) ?

**Comment by JohannesWiesner** [comment]
> You could use things like: nilearn.image.math_img('np.nantonum(img)', img=img) ?

Yes, I actually had the same idea and did exactly this. Makes it even simpler than using clean_img
