### ISSUE TITLE
[DOC] Missing example thumbnails

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2352]
In the documentation built from master branch, there are two examples with missing thumbnails. These were imported from Nistats, and they are missing there as well.

We need to fix this before rolling out the next Nilearn stable.

The two examples are:

9.5.2. Example of a events.tsv file generation: the neurospin/localizer events
`04_glm/first-level-models-write-events-file.py`

9.8.9. Decoding of a dataset after glm fit for signal extraction
`07_advanced/plot-haxby-block-classification.py`

**Comment by bthirion** [comment]
@ja-che can you take care of that ? (... quickly)
Best,
Bertrand

**Comment by thomasbazeille** [comment]
This has been solved for both examples mentionned. Closing
