### ISSUE TITLE
Update CONTRIBUTING to mention restarting CI on pull requests

### ISSUE THREAD

**Issue by emdupre** [nilearn/nilearn#2353]
As our dataset fetchers show some sporadic failures (see #2283), we occasionally have CI failures that are not reflective of the tested PR. @kchawla-pi recently updated our CI suite such that all contributors -- not only project maintainers -- should now be able to re-trigger CI builds. 

It would be nice to note in the CONTRIBUTING guidelines how contributors can do this, and to ask everyone to check the error logs to confirm if a given failure stems from the contributed code or an unrelated dataset fetcher.

**Comment by kchawla-pi** [comment]
I seem to have misinterpreted the documentation. I orchestrated #2357 , and there are no restart options on the checks tab for users without write permissions. :-|

**Comment by kchawla-pi** [comment]
Sorry for the false celebrations, @GaelVaroquaux @bthirion @emdupre
