### ISSUE TITLE
Remove deprecated `fetch_surf_fsaverage5`

### ISSUE THREAD

**Issue by emdupre** [nilearn/nilearn#2358]
`fetch_surf_fsaverage5` has been deprecated in favor of `fetch_surf_fsaverage` since version 0.4.3:

https://github.com/nilearn/nilearn/blob/c776feb094f45b64d5bc203c79e68b4634b74f12/nilearn/datasets/struct.py#L502-L505

We should update this deprecation warning to note the exact release cycle where it will be removed.

**Comment by emdupre** [comment]
For an example of how to approach this, #2256 might be useful !

**Comment by kchawla-pi** [comment]
yeah we should remove it before 0.7.0 stable.

**Comment by tsalo** [comment]
I think that this can be closed now that #2447 has been merged.

**Comment by GaelVaroquaux** [comment]
Thanks @tsalo !
