### ISSUE TITLE
Add cluster-level tests and TFCE

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#2366]
This requires a TFCE implementation and non-parametric tests from nilearn/nistats#26.

**Comment by kingjr** [comment]
@bthirion not sure if this is still relevant, but we have a pure python spatio (-temporal) test  implemented in MNE, including tfce which could be directly re-used here for e.g. second-level mass univariate stats and searchlights:

https://mne.tools/0.15/auto_tutorials/plot_stats_cluster_methods.html

**Comment by bthirion** [comment]
Without going too much into detail, I think it is relevant indeed.

**Comment by tsalo** [comment]
Would this be implemented in `permuted_ols` or `SecondLevelModel`?

**Comment by bthirion** [comment]
Maybe `permuted_ols` is the right place.

**Comment by tsalo** [comment]
In that case, I have two questions: first, can `permuted_ols` be extended to work on contrasts? Second, would we just want to calculate and retain maximum cluster mass and/or size, as well as TFCE values, within `_permuted_ols_on_chunk`? If so, that seems fairly straightforward, as long as we calculate TFCE correctly.

**Comment by bthirion** [comment]
I think that the `permuted_ols` does not natively work on contrasts (tbc).
We'll probably have to rewrite a function similar to `_permuted_ols_on_chunk` but taking into account spatial context.
And indeed we need a TFCE implementation (I must have that somewhere).

**Comment by bthirion** [comment]
Sorry to be late on this.
Regarding 3), I would do it optionally, as it probably makes the method less efficient computationally. I'l look at it in #3181

**Comment by tsalo** [comment]
Once #3181 and #3196 are merged, I think all that's left is to support contrasts in `permuted_ols`. Does that sound right?

**Comment by bthirion** [comment]
I've realized recently that contrasts testing was actually more tricky than expected. Since this requires more developments, I would not add it now.
