### ISSUE TITLE
Q: Does SecondLevelModel handle Group factors?

### ISSUE THREAD

**Issue by chrplr** [nilearn/nilearn#2372]
If I am not mistaken,  the SecondLevelModel can only currently generate one-way anova within-subject models (2 additive factors, subject being one of them). 

If I am correct, it would be good to extend it to allow more factors, notably Group (=between subjects) factor (See SPM flexible factorial design)

Or rename it OneWay-withinSubject.

**Comment by thomasbazeille** [comment]
I think this can be closed for now as situation didn't evolved much apparently

**Comment by G21R** [comment]
Hello everyone I apologize for my English.I would like to know if it is possible to calculate the contrast for two different groups of the same experiment? I have two different groups (Those who do well in math and those who do poorly) they are undergoing one experiment. But how do I get visual information about the contrast and differences of these two groups?

**Comment by bthirion** [comment]
Hi, could this discussion move to Neurostars ? Thx

**Comment by G21R** [comment]
> 

I'm sorry, what do I need to do? I opened a new discussion if that's what you mean?
https://github.com/nilearn/nilearn/issues/3325
