### ISSUE TITLE
Create a python based fitlins as an exercise

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2382]
1. Take in the info from `model.json` in root of datasets  in openneuro.
2. Use `nistats` to build a model, considering all the experiments and their parameters.
3. Learn what one can from the experience.

This is not an intended feature for nistats.
Use examples from fitlins as starting point.

@GaelVaroquaux

**Comment by bthirion** [comment]
Corresponds to ongoing work regarding BIDS integration. Closing that one.
