### ISSUE TITLE
Code refactoring necessary for future ease of maintenance and development

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2383]
There are many functions in Nistats that are super long, some as much as ~100 lines and do multiple things within the same function body. One example that caught my eye is nistats.first_level_model.FirstLevelModel.fit() .

There are many difficulties with such an approach. It makes it impossible to do Test-Driven Development, the recommended way of programming. It also means new functions have to work around existing functionality, which can not be segregated from existing functions due to this reason.

In the long-term, this code will become increasingly fragile and difficult to maintain. It also sends the message to new contributors and for contributions that this is an acceptable way to write new code.

As a rule of software engineering, each function should do one, and ONLY one thing. In python, this usually means 5-7 lines in a function. So instead of a 100 line function, we should (for example), have 20 functions around 5 lines each. All called by an encompassing function.

This also ensures we can write more atomic unit tests for each of those small functions.

I intend to start refactoring this code. This is a massive undertaking, so I will do this slowly and piecemeal, while adding more atomic unit tests.

**Comment by tsalo** [comment]
This is a duplicate of #1769, now that nistats has been merged into nilearn, so I will close it.
