### ISSUE TITLE
Should have a plot_event function in nistats.reporting

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#2385]
I'm realizing that we rely increasingly on BIDS-type events files, which is great, but having a facility to explore such files would have some value.

**Comment by tsalo** [comment]
Would something like this make sense?
![events](https://user-images.githubusercontent.com/8228902/82388025-83352180-9a06-11ea-91ab-9aef1c55e235.png)

**Comment by bthirion** [comment]
Yes, but I was thinking of it without hrf convolution: plain boxcars.

**Comment by robbisg** [comment]
@bthirion 

I made a function for plotting the event file and I tested it with event Dataframe from ```examples/04_glm_first_level_models/write_events_file.py``` and with data from ```fetch_language_localizer_demo_dataset``` using ```first_level_models_from_bids``` output.

Here a sample picture of the first one.
![plot_event](https://user-images.githubusercontent.com/695037/82458869-85a38400-9ab7-11ea-88cd-5d25597c3fb1.png)


I have few questions:
0. Is the figure ok? :)
1. Should I use a single DataFrame as input, a list of DataFrame or both? 
2. I used as function parameters ```def plot_event(model_event, cmap=None, output_file=None)```. Do you think it's ok, or you think I have to add/remove parameters.
3. I add the function in ```_plot_matrices.py``` but I think it's not proper to put it here, what is your suggestion?

Thank you!

**Comment by bthirion** [comment]
Thx. The example you took is a bit extreme, with 10 event types.
Text and labels should be much larger relative to the plot: it's not readable currently.

Maybe give a try with this example:
https://github.com/nilearn/nilearn/blob/master/examples/04_glm_first_level_models/plot_spm_multimodal_faces.py

**Comment by bthirion** [comment]
> Should I use a single DataFrame as input, a list of DataFrame or both?

You mean: one Dataframe per run ? Ans support multiple runs, hence mutliple dataframes ? Sounds right for me. I don't know if one of those is more compliant with BIDS-style.

**Comment by bthirion** [comment]
>     2\. I used as function parameters `def plot_event(model_event, cmap=None, output_file=None)`. Do you think it's ok, or you think I have to add/remove parameters.

LGTM

**Comment by bthirion** [comment]
>     3\. I add the function in `_plot_matrices.py` but I think it's not proper to put it here, what is your suggestion?

It is the right place, next to  the `plot_design_matrix` function.

**Comment by robbisg** [comment]
> > Should I use a single DataFrame as input, a list of DataFrame or both?
> 
> You mean: one Dataframe per run ? Ans support multiple runs, hence mutliple dataframes ? Sounds right for me. I don't know if one of those is more compliant with BIDS-style.

If I take the ```models_events``` output  from ```first_level_model_from_bids```, this is a list of list of Dataframes (n_subjects x n_runs, I suppose), should I use this as input or a single Dataframe since BIDS has a single tsv file for each run?

**Comment by bthirion** [comment]
Yes.

**Comment by robbisg** [comment]
I think the function is not in a good shape yet, but I need some feedback, so if you want to see it, here's the link on my repo https://github.com/robbisg/nilearn/blob/nistats_plot_event/nilearn/reporting/_plot_matrices.py#L65 . 
If you think it is better, I can do a PR.

**Comment by bthirion** [comment]
Please open a PR. It's easier to read code in the PR interface of Github ;-)
