### ISSUE TITLE
include p values at peak level for get_clusters_table function

### ISSUE THREAD

**Issue by Tasserie** [nilearn/nilearn#2392]
Hello everyone,

I was looking to recover the p values at peak level and tried the get_cluster_table function. 
However, if cluster ID, localization, Z score peak and cluster size are reported, I can't found the associated p values. 
Because Nistats generates this table based on the input threshold, I am pretty sure this p value at peak level is already computed to discriminate if H0 is accepted or rejected, so I was wondering if you could add a columm to write it?

Many thanks,

Jordy T

**Comment by RaphaelMeudec** [comment]
@bthirion @NicolasGensollen I think this issue can be closed as the `get_cluster_table` now returns the `Peak Stat` column.

Snippet to check this:

```
from nilearn import image, reporting
from nilearn.datasets import MNI152_FILE_PATH

brain_map = image.smooth_img(MNI152_FILE_PATH, fwhm=3)
brain_map_table = reporting.get_clusters_table(brain_map, stat_threshold=1e2)
print(brain_map_table)
```

**Comment by bthirion** [comment]
Actually what was asked by @Tasserie was the p-value, rather than the stat. I guess that other sowftare do that. and it's a simple one-to-one trsanform between stat and p-val.
I'm a bit worried of clutting the result table though. Do other people have an opinion ?

**Comment by tsalo** [comment]
I wonder what the use for p-values would be? As you said, it's a one-to-one transform between stat and p-value, and the statistic is really only useful (IMHO) for coordinate-based meta-analysis. We already know the cluster is significant because `get_clusters_table` accepts a threshold parameter.

I could be missing something though.

**Comment by bthirion** [comment]
Then we should close it anyhow.

**Comment by NicolasGensollen** [comment]
Unrelated to the issue per se, but when I execute your code @RaphaelMeudec I get the following error. Does this only happen on my side? 

```
ValueError                                Traceback (most recent call last)
<ipython-input-1-8f558e26d0eb> in <module>
      3 
      4 brain_map = image.smooth_img(MNI152_FILE_PATH, fwhm=3)
----> 5 brain_map_table = reporting.get_clusters_table(brain_map, stat_threshold=1e2)
      6 print(brain_map_table)

~/GitRepos/nilearn-fork/nilearn/reporting/_get_clusters_table.py in get_clusters_table(stat_img, stat_threshold, cluster_threshold, two_sided, min_distance)
    237 
    238             # Get peaks, subpeaks and associated statistics
--> 239             subpeak_ijk, subpeak_vals = _local_max(
    240                 masked_data,
    241                 stat_img.affine,

~/GitRepos/nilearn-fork/nilearn/reporting/_get_clusters_table.py in _local_max(data, affine, min_distance)
     43 
     44     """
---> 45     ijk, vals = _identify_subpeaks(data)
     46     xyz, ijk, vals = _sort_subpeaks(ijk, vals, affine)
     47     ijk, vals = _pare_subpeaks(xyz, ijk, vals, min_distance)

~/GitRepos/nilearn-fork/nilearn/reporting/_get_clusters_table.py in _identify_subpeaks(data)
     93         if peak_idx not in cluster_idx
     94     ]
---> 95     vals[subpeaks_outside_cluster] = np.nan
     96     if subpeaks_outside_cluster:
     97         warnings.warn(

ValueError: cannot convert float NaN to integer
```

**Comment by RaphaelMeudec** [comment]
I re-ran the code to be sure, and it's still working on my side (python 3.8, nilearn 0.7.1).
Though, I had a similar error when using `load_img` instead of `smooth_img`.

**Comment by NicolasGensollen** [comment]
@RaphaelMeudec OK, thanks! :+1: 
I think it's because I'm on `0.8.1.dev`, and I suspect that the recent MNI152 template update (see #2738) has something to do with this...

**Comment by Remi-Gau** [comment]
Maybe I am wrong but I think this can be closed, unless we have changed our mind and want to add p-values to the cluster table
