### ISSUE TITLE
z-values from compute_contrast are inaccurate for p-values close to 1

### ISSUE THREAD

**Issue by mwegrzyn** [nilearn/nilearn#2395]
Dear nistats team,
using the compute_contrast function, my colleague and I noticed that if one contrast and its exact inversion are plotted, there are some inconsistencies regarding negative z-scores.

> What version of Nistats are you using?

0.0.1b

> What were you trying to do?

use compute_contrast to make z-score maps

> What did you expect will happen?

If i have a contrast [+1 -1] and a contrast [-1 +1], the z-scores should be inverted, respectively

> What actually happened?

z-scores cannot go lower than -8.2, because the associated p-values (e.g. 0.99999999999999999) are represented as 1, while the corresponding p-values of the inverted contrast (e.g. 0.00000000000000001) are not.
See the following notebook which uses the example "2.1.2. Analysis of a single session, single subject fMRI dataset" from the nistats page to illustrate the issue:

[https://gist.github.com/mwegrzyn/9349842ee2abbff05df735a595bb239a](https://gist.github.com/mwegrzyn/9349842ee2abbff05df735a595bb239a)

Thank you.

Best regards,
Martin Wegrzyn

**Comment by alpinho** [comment]
@bthirion @mwegrzyn I'll start working on this problem. Do you have any further suggestions besides what is reported [here](https://gist.github.com/mwegrzyn/9349842ee2abbff05df735a595bb239a)?

**Comment by mwegrzyn** [comment]
Dear @alpinho,

thank you very much for your message and for working on the issue. Right now, I don't have any further ideas. But if you have anything that you need help with, I would be happy to try and contribute something (maybe tests or documentation; I'm not too experienced with working on software, but am looking for opportunities to gain more experience). Thank you!

Best regards,
Martin

**Comment by alpinho** [comment]
As an attempt to solve this issue, the PR #2567 contains a sketch for a possible solution to this problem. I firstly note that this PR already contains a dedicated test function that reproduces the problem herein described. Please, see lines 46-83 of `nilearn/glm/tests/test_utils.py` of this PR. The remaining two files, i.e. `nilearn/glm/contrasts.py` and `nilearn/_utils/glm.py`, contain a proposition for a solution. The idea is to estimate p-values using both the Survival function (SF) and the Cumulative distribution function (CDF). (Note that in the current implementation, Nilearn only uses SF both for t-statistic and F-statistic.) Therefore, in `nilearn/glm/contrasts.py`, the function `p_value` is replaced by two functions named respectively `sf_value` and `cdf_value`. The results returned by these two functions will then be used by the function `z_score` in `nilearn/_utils/glm.py`. In this function, z-scores are now computed using the p-values estimated from both SF (`sfvalue`) and CDF (`cdfvalue`). The final result returned by this function contains the z-scores estimated using SF for x>=0 and CDF for x<0. @ja-che and I believe this is a feasible workaround to solve this problem, which comes from the fact that python represents values close to 0 much more accurately than values close to 1. Nevertheless, substituting the `p_value` function by `sf_value` and `cdf_value` will affect many other functions in Nilearn and, perhaps, some redesigning might be necessary. We would thus like to ask what you think. @bthirion @GaelVaroquaux @KamalakerDadi @jeromedockes @thomasbazeille @emdupre @tbng

**Comment by bthirion** [comment]
Thx.  We agreed that this is the right thing to go, so I simply suggest to go ahead.
Maybe simply keep `p_value` and add a `one-p_value` function and use both of them to return z_scores. This would minimize side effects.
