### ISSUE TITLE
Censor time points during rescaling

### ISSUE THREAD

**Issue by effigies** [nilearn/nilearn#2403]
In [`FirstLevelModel.fit`](https://github.com/nistats/nistats/blob/f7e1056e26bd5b1070fc361a1d4335b14f0de32c/nistats/first_level_model.py#L324-L506), scaling is performed on the whole time series `Y`:

https://github.com/nistats/nistats/blob/f7e1056e26bd5b1070fc361a1d4335b14f0de32c/nistats/first_level_model.py#L475-L476

For dummy scans or other outliers (such as motion-related intensity spikes), it might be desirable to censor these. You can either handle these by modifying these volumes (e.g., removing dummy scans, or mean-imputing spikes) or by adding dummy regressors for them.

These two strategies will clearly have different effects on the calculated means/ranges of the time series when rescaling. Would it be useful to add a censoring parameter to `fit`, such that any rescaling would ignore those time points?

I can think of a couple options:

1) A list of volume indices. This has the advantage of being simple, while the disadvantage that you're depending on the user to pass consistent censored time points and dummy regressors.
2) Given that we'll have access to the design matrix, we could just use a list of columns that identify dummy regressors, and get the volume indices from these.

**Comment by Shotgunosine** [comment]
Any column in the design matrix that has just a single 1 in it is a censor column, it's easy to identify those columns and the corresponding TRs assuming a dense design matrix. This seems like the least error prone approach to me.

**Comment by bthirion** [comment]
If you're doing OLS regression, indeed. But it is encouraged to take into account noise serial correlation in fMRI. This is handled by a pre-whitening filter than induces some artefact if a volume is corrupted. This is why it would be better to have an explicit `sample_mask` parameter.

**Comment by henrymj** [comment]
@bthirion Do you have any more advice for handling censored timeseries while attempting to use a pre-whitening filter, especially in nilearn? I have access to a preprocessed dataset with timepoints that were motion-censored. I'm not sure how the pre-whitening filter would be affected by imputed values.

Is there any movement towards adding this `sample_mask` parameter?

**Comment by bthirion** [comment]
Regarding the strategy for handling censored time series, I would advise to run the GLM with `noise_model='ols'` and then `noise_model='ar1'` If the difference is tiny ---which is what I would expect, then it means that the pre-whitening has limited impact on the statistics and you can safely fall back to 'ols'. My 2c.

**Comment by bthirion** [comment]
Regarding the addition of `sample_mask` in GLM API, I thing that @htwangtw wants to do this.

**Comment by htwangtw** [comment]
`sample_mask` is now in the `NiftiMasker` and related modules. It would be useful for GLM API to have it as well. I can look into this.
