### ISSUE TITLE
Misc issues in Nistats reports

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#2405]
Here are some  issues I have encountered using nistats reports.
* Does not seem to take into account use-provided parameters for thresholding 
* the contrast maps only have the positive part displayed
* multi-dimensional contrasts do not display well.

**Comment by Remi-Gau** [comment]
Other minor issues:

The top table should not mention fir delay if fir was not used.

![image](https://github.com/nilearn/nilearn/assets/6961185/d6f680e0-c070-4d14-8216-7ce04cea15b2)

Design matrix title overlaps with picture

![image](https://github.com/nilearn/nilearn/assets/6961185/bb47475c-f70f-4686-8c4a-184a685d3991)

Change the color map used 

unicolor sequential when only positive or negative color (probably bwr_r will be better):

![image](https://github.com/nilearn/nilearn/assets/6961185/4844871c-dd3f-446c-9e7f-721ba5308a1c)

bicolor diverging when positive and negative values are present (black_red ?):

![image](https://github.com/nilearn/nilearn/assets/6961185/b9d9fdb7-b849-4f24-b971-0b45cd1e23a2)

Cluster table alpha does not have an appropriate number of significant figure:

![image](https://github.com/nilearn/nilearn/assets/6961185/d79b4b29-22dc-4e4c-940a-1e9e4ce99867)

**Comment by bthirion** [comment]
All of those are good points, thx.

**Comment by Remi-Gau** [comment]
Sorry for turning this into a "meta-issue / laundry-list". 
Will try to add a checklist in the top post of the issue to make it easier to track.
