### ISSUE TITLE
compute_contrast function contains false keyword documentation

### ISSUE THREAD

**Issue by JohannesWiesner** [nilearn/nilearn#2409]
`nistats.contrasts.compute_contrast` contains a keyword argument `regression_result`, but the documentation contains only a description of a keyword called 'results'. I guess that's a typo? 

https://nistats.github.io/modules/generated/nistats.contrasts.compute_contrast.html#nistats.contrasts.compute_contrast

**Comment by tsalo** [comment]
It looks like this should be closed by #2448 but no supported keyword was used.

**Comment by bthirion** [comment]
>  but no supported keyword was used.

Sorry, WDYM ?

**Comment by tsalo** [comment]
The PR has the following description:

> Simply fixes a typo in the docstring issue #2409

The way it was phrased prevented GitHub from auto-closing this issue when the PR was merged. Something like "Fixes #2409" would have linked that PR with this issue.

**Comment by bthirion** [comment]
All, right, thx !
