### ISSUE TITLE
[Question] Using RGBA value from FreeSurfer LUT to plot ROI

### ISSUE THREAD

**Issue by tashrifbillah** [nilearn/nilearn#2412]
Hello there,

I would like to use [plotting.plot_roi](https://nilearn.github.io/modules/generated/nilearn.plotting.plot_roi.html#nilearn.plotting.plot_roi) function to plot ROIs with colors defined in [FreeSurferColorLUT](https://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/AnatomicalROI/FreeSurferColorLUT).
I believe I need to play with `cmap` argument for the above purpose. The task would be to covert RGBA from the LUT to a value that `cmap` can accept.

I have been looking at [matplotlib.colors.ListedColormap](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.colors.ListedColormap.html#matplotlib.colors.ListedColormap.html) to understand how that is possible but haven't been able to figure out yet. Can anyone please help?

**Comment by bthirion** [comment]
Hi,
This type of request better fits in the Neurostars site.
I'm not sure I get your question, but the matplotlib colormaps can be seen here:
https://matplotlib.org/tutorials/colors/colormaps.html
Does this answer your concern ?

**Comment by tashrifbillah** [comment]
This is how I did this:

```python
# load and RGBA from FreeSurferColorLUT
# let's say the first row is loaded: "1 Left-Cerebral-Exterior     70  130 180 0"
from matplotlib.colors import ListedColormap
c= ListedColormap([70/255, 130/255, 180/255, 1-0])
# finally
from nilearn.plotting import plot_roi
plot_roi(aseg, brain, cmap=c)

# the above can be repeated to for ROIs defined in mri/aseg.mgz
```

My realization is, given a FreeSurferColorLUT, `nilearn` does not have a function for obtaining colormaps directly, which I expected it to have.

**Comment by kchawla-pi** [comment]
@tashrifbillah Maybe you can file an issue for it. And if so inclined, open a PR?

**Comment by jeromedockes** [comment]
the `ListedColormap` takes a list of RGBA tuples, so you need to double the square brackets on line 4 of your example
```python
from matplotlib.colors import ListedColormap
c= ListedColormap([[70/255, 130/255, 180/255, 1-0]])
# finally
from nilearn.plotting import plot_roi, show
from nilearn.datasets import load_mni152_brain_mask
plot_roi(load_mni152_brain_mask(), cmap=c)
show()
```

**Comment by jeromedockes** [comment]
> @tashrifbillah Maybe you can file an issue for it. And if so inclined, open a PR?

as @tashrifbillah correctly pointed out taking a list of colors and creating a colormap object usable for matplotlib (and nilearn) plots is exactly the role of `ListedColormap` so there probably no need to repeat that in nilearn

**Comment by jeromedockes** [comment]
btw the colormap argument doesn't seem to be documented in `plot_roi`'s docstring

**Comment by tashrifbillah** [comment]
> so you need to double the square brackets on line 4 of your example

Sure.

> plots is exactly the role of ListedColormap so there probably no need to repeat that in nilearn

You are right, I can define my own dictionary and access the appropriate key-value pair as I need them.

> btw the colormap argument doesn't seem to be documented in plot_roi's docstring

At the very least, this is something we can improve.

**Comment by ymzayek** [comment]
Closing this as colormap argument is now in `plot_roi` docstring
