### ISSUE TITLE
SpaceNetRegressor Scoring

### ISSUE THREAD

**Issue by vukovicnikola** [nilearn/nilearn#2416]
Hi,
Does the SpaceNetRegressor.score() method return the mean r2 score taking into account the KFold cross-validation folds?
N

**Comment by bthirion** [comment]
No, as far as I can see, it just returns the accuracy for the provided data; you probably need to do the cross-validation "manually".
Please note that this type of question should rather go to Neurostars.
Best,
Bertrand

**Comment by vukovicnikola** [comment]
Ah I see. I will try to do it manually then. And thanks for the heads up about Neurostars - I didn't even know about this forum!
