### ISSUE TITLE
Add distance-based interpolation

### ISSUE THREAD

**Issue by Spenhouet** [nilearn/nilearn#2420]
Doing affine transformations and interpolation on 3D data we thought that there has to be a library already doing that more optimized that we could but the only thing we could find was nilearn.
 
We tested the `nilearn.image.resample_img` method and were very happy with the performance, but we require a distance-based interpolation which nilearn doesn't have.

Would it be possible to add a distance-base (distance weighting) interpolation?
Our requirement would be a flexible (parameter) 3D window size and a distance weighted majority interpolation. We are using this for segmentations, therefore it should not introduce new colors.

I did see that nilearn uses `scipy.ndimage.affine_transform` and translates the interpolation parameter into a spline interpolation order. This does not really look compatible. What are your thoughts?

**Comment by bthirion** [comment]
If I understand correclyt, your proposed interpolation scheme is useful for discrete images, such as label images, that you would manipulate for atlases/segmentations. As you point out, we have decided to avoid integrating advanced code in nilearn for than, as the main focus is machine learning and statistics: we defer core operations to scipy.
I am wondering whather your proposal would not fit better in scikit image, that is the scipy-related library dealing with images ?

**Comment by Spenhouet** [comment]
> as the main focus is machine learning

Yes, segmentation is the second most used task after classification (just a guess). I would say that it is very important for ML and we are using it for that.

> we have decided to avoid integrating advanced code in nilearn

I understand the desire for that. I was more referring to the fact that you currently don't seem to provide a discrete interpolation method at all. Your "nearest neighbor" interpolation translates into a continuous cubic spline interpolation (ignoring how that is correct - I might have missed something in your code).

> I am wondering whather your proposal would not fit better in scikit image, that is the scipy-related library dealing with images ?

Could you point me to any method that they provide which is already closely related to a 3D affine transform + discrete interpolation?

**Comment by GaelVaroquaux** [comment]
> >    I am wondering whather your proposal would not fit better in scikit image, that is the scipy-related library dealing with images ?

> Could you point me to any method that they provide which is already closely related to a 3D affine transform + discrete interpolation?

Cc @emmanuelle

**Comment by Spenhouet** [comment]
I would like to check in again on this issue since we are still missing such a functionality.

@emmanuelle @GaelVaroquaux

**Comment by bthirion** [comment]
> Your "nearest neighbor" interpolation translates into a continuous cubic spline interpolation (ignoring how that is correct - I might have missed something in your code).

Sorry, I don't understand what you mean: these are two distinct interpolation schemes.

**Comment by emmanuelle** [comment]
Hi @Spenhouet sorry to have missed the first mentions. Since this feature seems to be more upstream than nilearn, could you please open an issue in https://github.com/scikit-image/scikit-image/issues/ to follow up on the discussion? It would help also if you had examples (wikipedia pages, research papers or existing code) of the feature you are requesting, since it's not entirely clear to me.

**Comment by Spenhouet** [comment]
> > Your "nearest neighbor" interpolation translates into a continuous cubic spline interpolation (ignoring how that is correct - I might have missed something in your code).
> 
> Sorry, I don't understand what you mean: these are two distinct interpolation schemes.

Yes, sorry, I think I got confused at some point. Not completely sure but I guess I got confused by the translation of the "nearest neighbor" into a spline interpolation order of 0.

**Comment by Spenhouet** [comment]
@emmanuelle I did create a feature request here: https://github.com/scikit-image/scikit-image/issues/4824

**Comment by NicolasGensollen** [comment]
Hi @Spenhouet 
As has been said above, this feature seems to better fit within the scope of scikit-image than nilearn's. 
Unless you think that this issue is still relevant and should stay open, I will close it in a few days.

**Comment by Spenhouet** [comment]
@NicolasGensollen Since I already opened a scikit-image feature request this issue can be closed. Thanks for the pointer.
