### ISSUE TITLE
SurfLabelsMasker

### ISSUE THREAD

**Issue by sahahn** [nilearn/nilearn#2423]
Hi,
I just wanted to gauge interest around potentially adding functionality like NiftiLabelsMasker, but for surface data (just any 1D or 2D - time-series). I know in particular the reverse_transform aspect could be useful, i.e., going from ROI values to a surface that could be easily passed to plot_surf_stat_map. I know I also personally find having pipeline compatible ROI extra extractors helpful. The natural extension to this idea too would be a base SurfMasker class... with surface versions (where possible) of the NiftiMasker functionality. 

My main concern would just be scope, i.e., the majority of nilearn is geared towards working with volumetric data, is, therefore, trying to add more support for surfaces too far outside of the intended project scope? If not, I would be interested in implementing some of it.

Thanks!

**Comment by jeromedockes** [comment]
I think we are indeed planning to add more support for surfaces, see
e.g. https://github.com/nilearn/nilearn/issues/2171

ping @hcherkaoui

**Comment by GaelVaroquaux** [comment]
I agree with Jérome: I think that we would be super excited about such a
contribution!

**Comment by sahahn** [comment]
Great, thanks for the reply. I'll look into putting something together

**Comment by hcherkaoui** [comment]
@jeromedockes I did not start any contribution on this. The road is free :)

**Comment by thomasbazeille** [comment]
Hi everyone we'd love to take advantage of the sprint to have an open discussion about Surface support in Nilearn. It's scheduled today at 6p CET (12p EDT). More informations will be in the [sprint discord](https://discord.gg/bMBhb7w) around this time.

Hope to see you there !

**Comment by dangom** [comment]
Will this be recorded somewhere? Would've loved to attend but unfortunately I have a meeting at that time.

**Comment by Remi-Gau** [comment]
Will close this as we have now an (experimental) surface masker
