### ISSUE TITLE
Timeline for dropping Nibabel 2.x support

### ISSUE THREAD

**Issue by emdupre** [nilearn/nilearn#2429]
With the Nibabel 3.x release series, [`Pathlike`](https://docs.python.org/3/library/os.html#os.PathLike) objects are now directly supported by Nibabel. We currently do not support `Pathlike` objects, however, (for an example, see [`load_niimg`](https://github.com/nilearn/nilearn/blob/927976dad301ff729d3e695aef0aad7a9be53084/nilearn/_utils/niimg.py#L95)) presumably to maintain compatibility with Nibabel 2.x. 

I know there was a lot of discussion about updating Nilearn to handle deprecations that came with the Nibabel 3.x release series (see #2155 and #2172), but I'm unclear on how long we plan to continue supporting older versions of Nibabel. Since we're preparing to cut our own 0.7.x release, I thought it might be a good time to start the discussion !

**Comment by bthirion** [comment]
Nibabel 3.x is till much too recent (nov 2019) for us to drop older versions I'm afraid.

**Comment by emdupre** [comment]
Yes, sorry, I didn't meant to suggest we should drop it for the 0.7.x release ! Just in thinking about release cycles more generally, I'm wondering if we have a timeline in mind here.

Maybe this is a broader question on when we drop support for older libraries !

**Comment by bthirion** [comment]
I propose to have a 2 years margin, e.g. drop support for nibabel 2.x >= nov 2021 
?
