### ISSUE TITLE
Incorrect colorbar with thresholded statmap

### ISSUE THREAD

**Issue by ariekahn** [nilearn/nilearn#2430]
I'm trying to plot a thresholded statistical map, with values ranging between 0.0 and 0.27.

I can't get the colorbar 

Running `plotting.plot_stat_map(svm_loc)` gives me the following:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/54182/80816934-714a2680-8b9e-11ea-8e43-b240ead33bd5.png">

Notice the small colorbar box on the bottom right. I've tried playing around with `threshold`, `symmetric_cbar`, `vmax` without any success.

I'm taking a look at `plot_stat_map`, and specifically this line of `_crop_colorbar`:
https://github.com/nilearn/nilearn/blob/927976dad301ff729d3e695aef0aad7a9be53084/nilearn/plotting/img_plotting.py#L223

From what I can tell, it's being given cbar_vmin and cbar_vmax values of 0 and None, which are adjusted to 0 and 0.27, and _then_ normalized to 0.5 and 1.

If I replace `cbar.ax.set_ylim(cbar.norm(cbar_vmin), cbar.norm(cbar_vmax))` with `    cbar.ax.set_ylim(cbar_vmin, cbar_vmax)`, and disable the outline, I get the following:

<img width="540" alt="image" src="https://user-images.githubusercontent.com/54182/80817874-39dc7980-8ba0-11ea-82fd-7979f88d429f.png">

My guess is due to the following API change in matplotlib 3.x: https://matplotlib.org/3.2.1/api/api_changes.html#matplotlib-colorbar-colorbar-uses-un-normalized-axes-for-all-mappables

nilearn: 0.7.0a
matplotlib: 3.2.1

**Comment by jeromedockes** [comment]
thanks for finding this! So I guess we need to do one or the other depending on the matplolib version. Since you already found the solution would you like to open a PR?

**Comment by ariekahn** [comment]
No problem! Looks like this affects 3.2.0 onwards.
