### ISSUE TITLE
Error plotting single slice using plot_prob_atlas

### ISSUE THREAD

**Issue by ejolly** [nilearn/nilearn#2437]
`nilearn==0.6.2`
macOS 10.15.4

Plotting a single view from `plot_prob_atlas` with a single cut produces a type error and fails to behave like `plot_stat_map` despite having the same docstring for `cut_coords`

`# TypeError 'list' cannot be interpreted as an integer`  
`plot_prob_atlas(brain, cut_coords=[0], display_mode='z')`

`# Plots brain at z-index = 0`  
`plot_stat_map(brain, cut_coords=[0], display_mode='z')`

**Comment by jeromedockes** [comment]
Thanks. can you provide "brain"? this works for me (with nilearn 0.6.2):

```
from matplotlib import pyplot as plt
from nilearn import plotting, datasets

atlas = datasets.fetch_atlas_harvard_oxford("cort-prob-2mm").maps
plotting.plot_prob_atlas(atlas, cut_coords=[0], display_mode="z")
plt.gcf().savefig("/tmp/fig.png")
```

**Comment by ejolly** [comment]
Sure I was just trying it with one of the [neurosynth parcellations](https://neurovault.org/collections/2099/). Are there some specific properties that a file has to have that I missed?

**Comment by bthirion** [comment]
`plot_prob_atlas` takes as input a 4D image. You should probably use    `plot_roi` instead.

**Comment by ejolly** [comment]
Whoops somehow missed this thanks! Going to close the issue.
