### ISSUE TITLE
Enhancement for plotting.view_connectome: nodes size & color

### ISSUE THREAD

**Issue by kfinc** [nilearn/nilearn#2444]
H!
`plotting.view_connectome` offers 3D plotting of connections (edges with varying weights represented as adjacency matrix) together with spheres (nodes) with a fixed color and specified size (the same for all markers). We propose to provide an enhancement to the `plotting.view_connectome` by 
including varying markers colors/sizes (specified as arrays of nodes' colors and sizes). As `plotting.plot_connectome` already provides such functionality, the enhancement would make the connectome plotting tools in Nilearn more consistent.

Such functionality is also available in `plotting.view_markers` but that plotting option does not enable to visualize edges of the network. 

Do you think it is reasonable and feasible to work on such enhancement (+tutorial demonstration) during the Nilearn Dev Days sprint?

Many researchers in network neuroscience that use [BrainNet Viewer](https://www.nitrc.org/project/list_screenshots.php?group_id=504&screenshot_id=710) for plotting might appreciate such enhancement!

**Comment by GaelVaroquaux** [comment]
Cc @jeromedockes : what do you think?

**Comment by jeromedockes** [comment]
> H!
> `plotting.view_connectome` offers 3D plotting of connections (edges with varying weights represented as adjacency matrix) together with spheres (nodes) with a fixed color and specified size (the same for all markers). We propose to provide an enhancement to the `plotting.view_connectome` by 
> including varying markers colors/sizes (specified as arrays of nodes' colors and sizes).
>
> Such functionality is available in `plotting.view_markers` but that plotting option does not enable not to visualize edges of the network. 
>
> Do you think it is reasonable and feasible to work on such enhancement (+tutorial demonstration) during the Nilearn Dev Days sprint?
>
> Many researchers in network neuroscience that use [BrainNet Viewer](https://www.nitrc.org/project/list_screenshots.php?group_id=504&screenshot_id=710) for plotting might appreciate such enhancement!   

I think that's a good idea!

**Comment by thomasbazeille** [comment]
I think you did a lot of work on this during the sprint right @kfinc ? Can you point me to the related PR? Was it merged ?

Thanks a lot

**Comment by bthirion** [comment]
@kfinc do you want to work on this ?
Best,

**Comment by thomasbazeille** [comment]
I'm under the impression this was adressed in the sprint and finally merged but can"t find the PR? Can I close @kfinc @bthirion ?

**Comment by bthirion** [comment]
Actuall it was not done. I think this kind of feature is a nice project for a future sprint.

**Comment by RaphaelMeudec** [comment]
I'm looking into this.
