### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#2453]
I think it would benefit the community if there was a pull request template for nilearn. 
The specific rationale is that I've noticed several issues that haven't been closed by associated pull requests in both nilearn and nistats because appropriate keywords were not used (see [here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for those keywords).

A simple one, like [the one used by tedana](https://github.com/ME-ICA/tedana/blob/d338acc57f9fde09c5f8dcc251937f00236d3f52/.github/pull_request_template.md), would probably be sufficient. It includes "Closes # ." and a list of proposed changes, so contributors would know how best to link the associated issue without having to search for acceptable keywords in GitHub's documentation.

**Comment by thomasbazeille** [comment]
+ 100
