### ISSUE TITLE
generate_reports deviates from Nilearn naming convention

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2466]
Nilearn's naming conventions were brought closer to standardization in 2018. One example of that was instead of using `create`, `generate`, `make` to in function names to describe what is essentially the same activity, we had decided to use `make` only.

Unfortunately, somehow this was not communicated during the review process when creating Niftimasker's `generate_report` method.

I propose that we rename it to `make_report` with our usual deprecation cycle.

Your thoughts @emdupre @jeromedockes  ?

**Comment by bthirion** [comment]
+1

**Comment by emdupre** [comment]
I'd push back against `make`, personally, since it doesn't resemble other
functions with that naming convention. This is closer to `view_img` in
returning an HTML report (that eg should be opened in a browser window).

**Comment by bthirion** [comment]
But report generation is quite distinct from plotting: it involves some computations. I'd rather have `make_report`.
Or did I misunderstand  you ?

**Comment by emdupre** [comment]
I tried to explain a bit more in #2488, sorry ! I was reacting to the fact that prior to the Nistats merge, very few Nilearn functions were prefixed with `make` and those that were did not generate HTML output. I see now that Nistats had adopted its own conventions that are now intermixed in the code base. Reporting is something that definitely needs to be standardized, now ! I'd (personally) imagine this discussion makes more sense as part of #2488, though.

**Comment by bthirion** [comment]
Should we consider this solved, then ?

**Comment by bthirion** [comment]
Fine with me
