### ISSUE TITLE
[DOC] Missing pandas dependency in installation guide

### ISSUE THREAD

**Issue by robbisg** [nilearn/nilearn#2468]
In the Installing nilearn section, ```pandas``` is missing as nilearn dependency in Linux, Mac and Windows tabs.
https://nilearn.github.io/introduction.html#installing-nilearn

**Comment by bthirion** [comment]
Can you issue a PR ?

**Comment by thomasbazeille** [comment]
Maybe should better be integrated to a suitable PR to avoid adding a
specific CI jlb for that

**Comment by robbisg** [comment]
I was fixing that (fighting with vscode html prettier, actually), but if I have to do something different than usual PR, I will stop!
