### ISSUE TITLE
Messed up colorbar scaling with plot_abs=True

### ISSUE THREAD

**Issue by maalaria** [nilearn/nilearn#2470]
Dear Nilearn-developers,

after updating to the current version 0.6.2, I encounter problems when plotting activity maps (e.g. ```plot_glass_brain```). The problem is that when I set ```colorbar=True``` and ```plot_abs=True```, the size of the colorbar is messed up and consequently the figure size in general, leading to huge/long colorbars with normal sized activity maps. if ```plot_abs=False``` the scaling is correct. This problem was not present in version 0.6.0. 
I am using jupyterlab, and this happens independent of plotting inline or using a gui. 

Kind regrads

**Comment by bthirion** [comment]
Thx for reporting. Can you provide a simple snippet of code to reproduce ?

**Comment by maalaria** [comment]
Correct colorbar-scaling:
```nilearn.plotting.plot_glass_brain(example_nii, colorbar=True, plot_abs=False)```

False scaling:
```nilearn.plotting.plot_glass_brain(example_nii, colorbar=True, plot_abs=True)```

[example_nii.zip](https://github.com/nilearn/nilearn/files/4662528/example_nii.zip)

**Comment by bthirion** [comment]
Hm, it's looking fine on my box. Which version of matplotlib are you using ?

**Comment by maalaria** [comment]
I am using matplotlib: 3.2.1

**Comment by bthirion** [comment]
![image](https://user-images.githubusercontent.com/234454/82569017-f01ff700-9b7f-11ea-9f80-d5c870b57001.png)
This is what I get (with Matplotlib 3.2.1)...

**Comment by maalaria** [comment]
Here are the results how I get them with commands from above (the only difference is plot_abs=True/False).

False scaling:
![false_scaling](https://user-images.githubusercontent.com/10158536/82569547-ae438080-9b80-11ea-9a89-5ae7084be2b2.png)

Correct scaling:
![correct_scaling](https://user-images.githubusercontent.com/10158536/82569559-b4d1f800-9b80-11ea-8695-7e38b8370a6d.png)

**Comment by jeromedockes** [comment]
could it be the same issue as #2430 ? if so have a look at the PR linked in that issue for how to fix it

**Comment by maalaria** [comment]
Looks like beeing related. I will have a look. Thanks!

**Comment by bthirion** [comment]
My impression is that this has been fixed. Closing. 
Don't hesitate to repoen if needed.
