### ISSUE TITLE
Add "dummy" option as an estimator in the Decoder / DecoderRegressor

### ISSUE THREAD

**Issue by thomasbazeille** [nilearn/nilearn#2471]
1 - Accept "dummy" with smart default in the Decoder / DecoderRegressor to have an API consistent way to test chance for the decoding problem at hand

2 - Add in section 2.1 of the userguide an Introduction and example plot_intro_decoding a mention of this and a comparaison of results to chance in the haxby case

**Comment by jeromedockes** [comment]
great idea!

**Comment by tbng** [comment]
> 1 - Accept "dummy" with smart default in the Decoder / DecoderRegressor to
> have an API consistent way to test chance for the decoding problem at hand

Can you elaborate more on this point?

**Comment by thomasbazeille** [comment]
> > 1 - Accept "dummy" with smart default in the Decoder / DecoderRegressor to
> > have an API consistent way to test chance for the decoding problem at hand
> 
> Can you elaborate more on this point?

Really just have a tradeoff have a reasonable baseline for chance in our current examples.

Specifics I can think of :
- add "dummy" to the list of acceptable keyword
- when it's passed instantiate DummyClassifier / DummyRegressor with suitable strategy and parameter (but I think sklearn default will be a great start)
- find how it would work to fit this dummy as is, for example through the current _parallel_fit() function I think it should work
- I think this can override potential conflict with screening_percentile, param_grid.
