### ISSUE TITLE
API suggestion: stats.first_level_model -> stats.first_level

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#2472]
I suggest that we do the following renames:
* nilearn.stats.first_level_model -> nilearn.stats.first_level
* nilearn.stats.second_level_model -> nilearn.stats.second_level

The goal would be have slightly smaller names, which can help readability. This is still easily possible as we haven't released yet.

**Comment by effigies** [comment]
While we're on the subject: Is it possible that we might want to rename `nilearn.stats` to something that more specifically indicates the general linear model? Or is the goal that this will grow into something broader?

**Comment by GaelVaroquaux** [comment]
> to rename nilearn.stats to something that more specifically indicates the general linear model?

We could call it nilearn.glm. The question is whether this is too jargony or not. I don't know really. I'd love people's thoughts.

To be fair "decoding" is jargon too.

**Comment by GaelVaroquaux** [comment]
Summarizing a discussion that we just had:

* Moving stats -> glm would reduce the scope, which is fine but should be a conscious decision
* "glm" is wording used quite widely in BIDS as well as other software
* mass_univariate should be moved to this module.

This issue is still open for comments, but the consensus is currently:
* stats -> glm
* Removing "_model" from "first_level" and "second_level".

Remaining questions on the usage of "first" and "second" as there can be multiple levels of second level :smile: 

The plan is to reach a decision soon, to be able to implement it before the release

**Comment by bthirion** [comment]
> Remaining questions on the usage of "first" and "second" as there can be multiple levels of second level smile

One possibility is to use:
- "first_level" -> "subject_level"
- "second_level" -> "group_level"
But I still prefer  "first_level" / "second_level"  (I believe that people who have worked with SPM will find this fine).

**Comment by effigies** [comment]
If the choice is first/second or subject/group, then I would prefer first/second because subject/group is heuristically reasonable but not always true. "First" will not be violated, and somebody who can construct a third-level model should understand it enough to know it's the same idea as second.

As I mentioned on the channel timeseries/summary is maybe a bit more descriptive, but at the cost of introducing new terms.

**Comment by bthirion** [comment]
OK, I'd rather stick to first/second.

**Comment by effigies** [comment]
As one final point of (non)interest, I typically import as [`level1`](https://github.com/poldracklab/fitlins/blob/ab47bf25e48534550a833a8c2ce6a0be16775745/fitlins/interfaces/nistats.py#L130) and [`level2`](https://github.com/poldracklab/fitlins/blob/ab47bf25e48534550a833a8c2ce6a0be16775745/fitlins/interfaces/nistats.py#L229), to make it just a bit shorter. So I guess that's another option.

Again, though, first_level and second_level are fine with me.

**Comment by robbisg** [comment]
> This issue is still open for comments, but the consensus is currently:
> 
> * stats -> glm

What about ```nilearn.univariate``` ? You surely discussed about that and I know that final decision is up to the Temporary Benevolent Dictator (just noticed that :D) !!

**Comment by bthirion** [comment]
People are less familiar with `univariate` than `glm` even though it's more accurate technically.

**Comment by GaelVaroquaux** [comment]
> What about nilearn.univariate ?

I think that it's as jargony and incorrect as GLM (a GLM is univariate in
voxel-space, but multivariate in design space)

> I know that final decision is up to the Temporary Benevolent Dictator (just noticed that :D) !!

The Temporary Benevolent Dictator likes consensus. These are however hard
to achieve as we all come from different background (which is added
value!)

**Comment by dangom** [comment]
Why not `first_level` and `higher_level`, like in FSL Feat?

**Comment by bthirion** [comment]
IMHO that makes it even more obscure, at least for non-FSL-users ;-)

**Comment by tbng** [comment]
I have made a PR with the proposed API changes (gh-2509). Will need some eyes to check/review as there are a lot of minor modification across example.
