### ISSUE TITLE
clean function modifies the input time series object if performing pass-filtering without detrending

### ISSUE THREAD

**Issue by jrasero** [nilearn/nilearn#2475]
Hi,

I am using version 0.6.0. I've found that function **clean** within the module signal modifies the input time series object if one performs a pass-fitering when _detrend_ option is False. 

For example, if you run the following code (test time series borrowed from [here](https://gist.github.com/miykael/4bb887029cba3926902feb2e4afe190f)) and then plot both the original and clean time series:

```
import numpy as np
import matplotlib.pylab as plt
from nilearn.signal import clean

original_sx = np.array([np.sin(np.linspace(0, 100, 100) * 1.5),
                        np.sin(np.linspace(0, 100, 100) * 3.),
                        np.sin(np.linspace(0, 100, 100) / 8.),
              ]).T

# Clean with detrending and high pass filtering
clean_sx = clean(original_sx, 
                   standardize=False, 
                   t_r=1.0, 
                   detrend=True, 
                   high_pass=0.2)

# Plot both time series
fig, axs = plt.subplots(ncols=2, figsize=(10, 5))  
axs[0].plot(original_sx)
axs[0].set_title("Original Time Series")
axs[1].plot(clean_sx)
axs[1].set_title("Clean Time Series")
plt.show()
```

You should see how "green" signal is totally filtered out (its frequency is ~ 0.02):

![example_detrend_filt](https://user-images.githubusercontent.com/25054369/82581329-6f043800-9b5e-11ea-8c81-0db4642d8c9c.png)

However, if you now try to run the same code but without detrending the time series:

```
import numpy as np
import matplotlib.pylab as plt
from nilearn.signal import clean

original_sx = np.array([np.sin(np.linspace(0, 100, 100) * 1.5),
                        np.sin(np.linspace(0, 100, 100) * 3.),
                        np.sin(np.linspace(0, 100, 100) / 8.),
              ]).T

# Clean with only high pass filtering (Note that now detrend is set to False)
clean_sx = clean(original_sx, 
                   standardize=False, 
                   t_r=1.0, 
                   detrend=False, 
                   high_pass=0.2)

# Plot both time series
fig, axs = plt.subplots(ncols=2, figsize=(10, 5))  
axs[0].plot(original_sx)
axs[0].set_title("Original Time Series")
axs[1].plot(clean_sx)
axs[1].set_title("Clean Time Series")
plt.show()
```

The original time series object is modified as well

![example_only_filt](https://user-images.githubusercontent.com/25054369/82581328-6f043800-9b5e-11ea-8584-df17b808808e.png)

When __detrend__ option is set to True, it first calls the function **_standardize**, which creates a copy of the original time series, and then carries on to do the filtering by calling the  function **butterworth**. However, when __detrend__ is False, which skips the first step, since **butterworth** is alway called with its  _copy_ argument set to False (the default value), the original time series are modified too. 

Is this the expected behaviour? I would expect the input time series to remain always the same, as inline modifications can lead to unwanted results if the original time series need to be reused again at some point.

Cheers

**Comment by bthirion** [comment]
This could be related to #2281 . I think that the idea was that the input should never be modified.

**Comment by bthirion** [comment]
Thx for reporting !
Would you issue a PR ?

**Comment by jrasero** [comment]
I've never issued a pull request, but I can try it. As it is suggested in #2281, the safest thing would just to create a copy of the input time series right at the beginning of the function.

**Comment by bthirion** [comment]
... only if necessary. 
We want to avoid copies as much as possible, because we may have to process large chunks of data.
