### ISSUE TITLE
ImportError: A sklearn version of at least 0.19 is required to use nilearn. 0.0.0 was found. Please upgrade sklearn

### ISSUE THREAD

**Issue by hvannieuwenh** [nilearn/nilearn#2481]
I recently installed nilearn version 0.6.2, and when I try "import nilearn" I receive the error written in the title. I cannot update sklearn as it is outdated, it has now been switched to scikit-learn, for which I have the latest version, 0.22.2.post1.

Downgrading my scikit-learn version to 0.22 fixed the problem and allowed me to import nilearn with no issues.

**Comment by thomasbazeille** [comment]
Thanks for reaching out !

This is linked to #2288 and on our to-do list for next release as well. It might become a high priority if it makes nilearn fail with latest scikit-learn version.
