### ISSUE TITLE
Gray- and white- matter masks estimation

### ISSUE THREAD

**Issue by alpinho** [nilearn/nilearn#2487]
As a follow-up of the PR #2459, new parameters on gray and white-matter masks estimation should be added to the new function `Nilearn.masking.compute_brain_mask`. This function computes an whole-brain mask based on the MNI template and this can be kept as the default parameter.

**Comment by bthirion** [comment]
Please indicate which additional parameters are needed ?
What is the use case ?

**Comment by alpinho** [comment]
Only one additional parameter that would accept three possible string values, e.g. 'whole-brain', 'gray-matter' and 'white-matter'. Default should be 'whole-brain', which is what is implemented for the moment. A mask corresponding to the selected part of the brain will be then calculated through the resampling of the respective MNI152-template mask onto the target image.

**Comment by bthirion** [comment]
AFAIK there is no mechanism to extract gray matter or white matter in Nilearn. 
Are you suggesting to implement that ?

**Comment by jeromedockes** [comment]
> AFAIK there is no mechanism to extract gray matter or white matter in Nilearn. 
> Are you suggesting to implement that ? 

If so I guess you could threshold the output of `fetch_icbm152_brain_gm_mask`

**Comment by alpinho** [comment]
AFAIK, `Nilearn.masking.compute_brain_mask` loads an MNI152 whole-brain template and resample it. A similar procedure can be integrated in the same function but for grey and white matter templates.

**Comment by bthirion** [comment]
@alpinho do you want to take care of that ?

**Comment by alpinho** [comment]
OK!

**Comment by alpinho** [comment]
I am closing this issue since it has been addressed by the PR #2738.
