### ISSUE TITLE
API: nilearn.stats.map_threshold -> nilearn.stats.threshold_stats_img

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#2490]
This function is quite close to nilearn.image.threshold_img. We need to keep them consistent:

* names should be consistent (threshold first and not last)
* names should indicate the difference (one is about stats)
* orders of argument should be as consistent as possible (threshold should come second in map_threshold)
* they should reference each other in their see-also section

**Comment by tbng** [comment]
I can take care of this issue. Will open one PR for solving this one and gh-2472.
