### ISSUE TITLE
Rework the GLM documentation (nilearn.stats)

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#2492]
The GLM documentation (docs/glm) is currently a course on the GLM. It does not introduce in any way how to run an analysis with nilearn. While it is important that the narrative documentation stays high level, it still needs to introduce the concepts and objects of nilearn that are useful for the topic, as well as point to the most important examples to study.

Proposed plan:

* [ ] Add a subsection that goes before "An introduction to fMRI statistical analysis using GLMs" call "Models for GLM analysis" that explain briefly the first and the second level, the corresponding objects, and point to the corresponding tutorial examples
* [ ] Transform one of the second-level examples into a tutorial that introduces second-level modeling. Probably plot_thresholding.py (though we will have to change the name). It should stay simple.

**Comment by bthirion** [comment]
great suggestion, waiting for a candidate ;-)

**Comment by thomasbazeille** [comment]
My take on this was in #2467 (that I'll close as superseeded by this):

Basic functions to mention at the very least in the narrative documentation:

- [ ] plotting event file (upcoming)
- [ ] nilearn.stats.first_level_model.make_first_level_design_matrix
- [ ] nilearn.reporting.plot_design_matrix
- [ ] nilearn.stats.second_level_model

Maybe also a comparaison with glover / spm processing parameters ?

In any case it should be expanded to reflect at least the most important available examples in 9.5 and 9.6.

**Comment by swaythe** [comment]
I started working on this with the following template in mind:

Section summary that appears when you click on "Analyzing fMRI using GLMs":
"Nilearn's stats module uses Generalized Linear Model to analyse functional MRI data. Nilearn
offers functions to set up first- and second-level models, perform t-tests, multiple-comparisons
correction and thresholding, and allows for the generation of html reports that detail the
analyses performed and present thresholded results."

Sub-sections:
- An introduction to fMRI statistical analysis using GLMs (this section remains the same but I've done some spell-check and sentence restructuring)

- First level models
    - HRF models (plot_hrf)
    - Design matrices: event-based and timeseries-based (plot_spm_multimodal_faces, plot_adhd_dmn)
    - Fitting a first level model (plot_spm_multimodal_faces)
    - Extracting predicted time series and residuals (plot_predictions_residuals)
    - Surface-based analysis (plot_localizer_surface_analysis)

- Second level models
    - Design matrix for one-sample, two-sample or generic model (plot_second_level_one_sample_test, plot_second_level_two_sample_test, plot_second_level_association_test)
    - True positives in voxel clusters (plot_proportion_activated_voxels)
    - Thresholding statistical maps (plot_thresholding)
    - Voxel based morphometry (plot_oasis)

I've got a somewhat fleshed-out first level model section; I'll file a PR for that so you can give me feedback.

**Comment by swaythe** [comment]
Hi all,

I'm having some trouble getting the :ref: tag working in the documentation. I've used the documentation of functional connectivity as the model, but it's not working. Could someone please take a look? Thanks!

**Comment by rob-luke** [comment]
I just thought I'd note down that I really appreciate you writing these docs. And to highlight that they are helpful beyond fMRI too. I have just written a [brief tutorial on analysing fNIRS data with GLMs](https://mne.tools/mne-nirs/auto_examples/plot_10_hrf.html) (basically a light wrapper around nilearn.stats), and being able to point/link to your docs on things such as design matrices and first level fitting will be really handy.

**Comment by emdupre** [comment]
Hi @swaythe , thank you for working on this ! I followed up on your issue directly in the PR -- let's keep the discussion there, since it's already open :smile_cat:

**Comment by PeerHerholz** [comment]
Hi gang, 

the corresponding PR seems to be ready for merging. 
After that's done, I would like to check a few things @bthirion and I discussed in the prehistoric past of `nistats` (hehe) [here](https://github.com/nilearn/nistats/pull/436).

**Comment by bthirion** [comment]
Thx. That's a substantial amount of work. I think we should go ahead with that after the next release to avoid delaying it too much.

**Comment by GaelVaroquaux** [comment]
> I think we should go ahead with that after the next release to avoid delaying it too much.

Going ahead is akin to merging features without test: the current
documentation is not tested and will break. When it breaks, users will be
confused.

We did these errors in the past, and we need to avoid them. They lead to
documentation that cannot be maintained.

**Comment by bthirion** [comment]
I think we're talking about two different things. The documentation has to be tested.
I mean that in the list provided by @PeerHerholz there are many desirable improvements, but they are addition and could be added in the future. Sorry if I misunderstood your point.

**Comment by PeerHerholz** [comment]
I second @bthirion impression. As mentioned, there were some things we discussed over at `nistats`. However, given the recent merge and updates, I thought it's best to first check how things (the examples) have changed, before we go over the then addressed points again. Thus, we would wait for this PR to be merged and then take it from there as the goal/scope was comparable yet different. Sorry for creating confusion.

**Comment by emdupre** [comment]
@PeerHerholz do you want to review the open PR and open a new issue here (or link in the relevant issue if it was ported over from NiStats ?)

**Comment by PeerHerholz** [comment]
Oh, I thought you and @GaelVaroquaux were currently doing the reviews? Happy to open a new issue once I checked how many of the points @bthirion and I discussed are still there as they didn't focus on the `GLM` docs in particular but `nistats` examples as a whole. Sorry, I didn't mean to open a subthread here, but just "revive"/keep track the discussed points.
