### ISSUE TITLE
Rename : fREMXXX => FREMXXX

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#2494]
Classes need to be written strictly in CamelCase. As a result, the first letter of a class must be a capital.

We must rename before we release. Consistency is important.

**Comment by thomasbazeille** [comment]
This was raised during reviewing process because :"the method is called
fREM but the convention would mean using Frem (exact opposite). So I'm not
sure which one is more confusing for users"

and we agreed with @emdupre @jeromedockes and @tbng for fREM



Le lun. 25 mai 2020 à 19:42, Gael Varoquaux <notifications@github.com> a
écrit :

**Comment by GaelVaroquaux** [comment]
This is clearly a violation of Python style guidelines. A class cannot
start with a non upper case letter (there are plenty of violations out
there). We shouldn't do that.

**Comment by tbng** [comment]
Actually since I was the one who initially raised this discussion when
reviewing the code so there is no strict preference for my case, either is good
for me.

fREM is the similar name to the reference of the method so it might be less
confusing.

**Comment by jeromedockes** [comment]
actually I just checked the reference and it seems it should be FReM ?

https://hal.archives-ouvertes.fr/hal-01615015/

BTW I'm not sure why the "ensemble" in "fast regularized ensemble of
models" is not worthy of an upper-case letter.

in any case, in the future everybody please flake8 your publications
before submitting to journals to avoid this kind of issue.

**Comment by GaelVaroquaux** [comment]
> in the future everybody please flake8 your publications before submitting to journals to avoid this kind of issue.

:+1:  :)

By the way, sorry for coming after the fact with those annoying details.

**Comment by thomasbazeille** [comment]
I will handling as soon Doc and Examples PRs are merged, don't want to run into stupid conflicts there

**Comment by thomasbazeille** [comment]
tackled by #2570
