### ISSUE TITLE
Extract DMN using nilearn

### ISSUE THREAD

**Issue by wyang695441068** [nilearn/nilearn#2495]
Hello everyone, I am a novice user of nilearn, and I want to extract a default network (my own one data) of fMRI data through DictLearning. what should I do?
![}TPW@VZV`GAPA_6{9GET(5E](https://user-images.githubusercontent.com/35195009/82867649-cf7be680-9f5d-11ea-9fca-f586536ba81b.png)

dict_learn = DictLearning(n_components=8, smoothing_fwhm=6.,
                              memory="nilearn_cache", memory_level=2,
                              random_state=0)
    func_filenames = r'I:\TenDrugDataNoBrain\zeroDrug01_brain.nii'
    
    # Fit to the data
    dict_learn.fit(func_filenames)
    components_img = dict_learn.components_img_
    plotting.plot_prob_atlas(components_img, view_type='filled_contours',
                             title='Dictionary Learning maps')
    plotting.show()

**Comment by bthirion** [comment]
Hi, 
Could we have this discussion in Neurostars instead of Nilearn  issues?
I have the impression that the brain image  you are using is nit in MNI space. has it be preprocessed ?
Best,

**Comment by wyang695441068** [comment]
Sorry, I will refer this question to Neurostars.thanks! @bthirion
