### ISSUE TITLE
suggestion: check_niimg should raise FileNotFoundError if pathname doesn't exist

### ISSUE THREAD

**Issue by ariekahn** [nilearn/nilearn#2499]
I was iterating through a large dataset where a few subjects are missing individual scans, and noticed that `load_nii` raises a ValueError if the file I provided didn't exist. This seems like it would be more properly addressed with a FileNotFoundError.

It looks like this is coming from `check_niimg`, which either raises:
https://github.com/nilearn/nilearn/blob/46c7d2102eccad9d9dad0a975741ee3bfdbed87a/nilearn/_utils/niimg_conversions.py#L243-L249

or 

https://github.com/nilearn/nilearn/blob/46c7d2102eccad9d9dad0a975741ee3bfdbed87a/nilearn/_utils/niimg_conversions.py#L251

It's not completely clear-cut since the argument passed isn't necessarily a path, but based on the error messages themselves, it seems like it would be much more intuitive to raise a FileNotFoundError here.

Happy to submit a PR if this sounds reasonable.

**Comment by jeromedockes** [comment]
> Happy to submit a PR if this sounds reasonable.

It does, but changing it would break user code that catches the
ValueError. How do you suggest to handle that?

**Comment by ariekahn** [comment]
This might unnecessarily complicate things, but could create a custom class here subclassing both ValueError and FileNotFoundError, to preserve compatibility.

**Comment by jeromedockes** [comment]
yes that would work, but as you say I am afraid it would add clutter, and users might wonder what is this new exception class

**Comment by ariekahn** [comment]
Agreed. I think the existing choice is a bit confusing, but probably no great way to fix at this point.

**Comment by jeromedockes** [comment]
Still, thanks for reporting it!
