### ISSUE TITLE
Standardizing pd.DataFrame vs np.array usage

### ISSUE THREAD

**Issue by emdupre** [nilearn/nilearn#2505]
Right now, different portions of the code base seem to expect `pd.DataFrame`s or `np.array`s. For example, I hit this issue when generating a set of confounds and then trying to call `NiftiMasker.fit_transform()` or `FirstLevelModel.fit()`.

NiftiMasker expects a `np.array` and rejects a `pd.DataFrame`:

https://github.com/nilearn/nilearn/blob/f03f7250a9cc60b00e28b41801b12e99202f20f0/nilearn/input_data/base_masker.py#L189-L191

FirstLevelModel expects a `pd.DataFrame` and rejects a `np.array`:

https://github.com/nilearn/nilearn/blob/f03f7250a9cc60b00e28b41801b12e99202f20f0/nilearn/stats/first_level_model/first_level_model.py#L359-L366

I can solve this by just providing file paths, or converting between the two array types for each function. But this seems like an easy stumbling block for users, and something that should be standardized !

**Comment by jeromedockes** [comment]
> I can solve this by just providing file paths, or converting between the two array types for each function. But this seems like an easy stumbling block for users, and something that should be standardized !

thanks for pointing this out! we can try to make a list of all these
inconsistencies. As this might result in changes to the public API of
nilearn.stats, it is probably blocking the release?

**Comment by emdupre** [comment]
> As this might result in changes to the public API of
nilearn.stats, it is probably blocking the release?

I'd agree with that, but I'll ping @bthirion @GaelVaroquaux @thomasbazeille and @kchawla-pi for more opinions :smile_cat: 

I can work on starting that list in the meantime !

**Comment by GaelVaroquaux** [comment]
> I'd agree with that, but I'll ping @bthirion @GaelVaroquaux @thomasbazeille and @kchawla-pi for more opinions 😸

I think that we should strive to support both each time. We can introduce helper functions to cast one into the other.

**Comment by bthirion** [comment]
+1 for supporting both ,and thx for pointing this !

**Comment by kchawla-pi** [comment]
Both, +1

**Comment by emdupre** [comment]
Thanks all for the input ! Unless I hear otherwise I'm going to assume you also agree that it blocks the release 🙂

I'll work on the list and then we can see how to think about supporting both data types.

**Comment by thomasbazeille** [comment]
Hey everyone, I'd like to raise again this issue. If we agree this is a blocker for the next release(I agree...) we should consider dedicating time to it quickly, unless we find some volounteer to take care of that

**Comment by bthirion** [comment]
I agree that we should address it before the release.
My proposition is to accept both pandas DataFrames and Numpy arrays in both places.

**Comment by thomasbazeille** [comment]
@emdupre Bertrand opened the PR #2573 that takes care of FirstLevel and clean_img (which is behind NiftiMasker), do you want us to split modules to verify whether the same pb exists elsewhere ?

**Comment by emdupre** [comment]
Thank you, @bthirion !!

I can start looking through modules on Friday -- if other folks are willing to split, that would be great ! But I do think a sweep looking for this will be really useful to standardizing the code base.

**Comment by bthirion** [comment]
Note that there is a big effort to do in terms of documentation.

**Comment by thomasbazeille** [comment]
if you catch any updates to do @bthirion please report them so that we can plan on adressing what's needed

**Comment by thomasbazeille** [comment]
It seems to me that this PR is ok as is and handles the last blocker for the release. IMHO it can be merged and the release can happen right now.

**Comment by bthirion** [comment]
Merged, thx.
Following our last discussion, we should tag as experimental nilearn.glm before releasing.
