### ISSUE TITLE
Support atlases in plot_carpet

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#2515]
Currently, [nilearn.plotting.plot_carpet](https://github.com/nilearn/nilearn/blob/cc0f43ce329bda5af2eb4cb01b7207ed4ef24b9c/nilearn/plotting/img_plotting.py#L1467) only accepts a binary mask, but it would be preferable to accept an atlas to separate tissue types in the plot (see #1585). This better matches the implementation in MRIQC and the description from the original paper.

**Comment by bthirion** [comment]
In Nilearn jargon we would call that an atlas: 0 is counted as background, and masking is performed for each other class.

**Comment by bthirion** [comment]
Sounds good, of course.

**Comment by bthirion** [comment]
@tsalo, are you willing to work on it ?

**Comment by tsalo** [comment]
@bthirion Absolutely. :+1:
