### ISSUE TITLE
COBRE Dataset Mismatch Between Phenotypic Data and Func files

### ISSUE THREAD

**Issue by Alex-A14** [nilearn/nilearn#2519]
Hello,

I'm using Nilearn 0.6.2 in Jupyter Notebook via WSL and Ubuntu (Windows)

I was working with the COBRE dataset ```nilearn.datasets.fetch_cobre()``` recently and noticed that when I load the data, the indices/order of the phenotypic data don't match with with the order of the functional data files.

For example, reading in the phenotypic data with Pandas (e.g. ```pandas.DataFrame(data.phenotypic)```), the first row is for subject 40061, but if I print the functional data file paths with ```data.func``` the first file path leads to subject 40046.

This behavior doesn't match other datasets, like ```nilearn.datasets.fetch_development_fmri()``` in which the order of functional files match the phenotypic data indices.

Hope it's not just a bug of my specific build, or I'm not missing something obvious. But wanted to bring it up just in case in helps! Let me know if I can provide any more info.

**Comment by bthirion** [comment]
Thx for reporting. Could you provide a snippet of code to reproduce the problem ? This would save us a lot of time.

**Comment by Alex-A14** [comment]
Of course, here is an example with just the first item from each of the .func and .phenotypic objects.
```
from nilearn import datasets
data1 = datasets.fetch_cobre()

print(data1.func[0])
print(data1.phenotypic[0])
```

For me this returns (I've bolded the subject ID):
/home/aalbury/nilearn_data/cobre/fmri_**0040046**.nii.gz
(**40061**, 18, b'Male', b'Right', b'Control', b'None', 133, 0.25512, 0.22657)

**Comment by GaelVaroquaux** [comment]
Fetch_cobre is no longer maintained. It has been deprecated (see https://github.com/nilearn/nilearn/blob/46c7d2102eccad9d9dad0a975741ee3bfdbed87a/nilearn/datasets/func.py#L1491 ) and will be removed soon.

I suggest that you either use a different dataset, or another way of downloading the cobre data.
