### ISSUE TITLE
Importing nilearn not working as intended

### ISSUE THREAD

**Issue by fizzX** [nilearn/nilearn#2522]
Hi, 

I am using nilearn v0.6.2 running on a python 3.7 jupyterlab server on a CentOS server. I am trying to import nilearn and load a nifti image into the variable <sample_img> using
```
import nilearn as ni
sample_img = ni.image.load_img('nifti_file.nii.gz')
```

However, I am getting an error
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-442f43ad285b> in <module>
----> 1 sample_img = ni.image.load_img('nifti_file.nii.gz')

AttributeError: module 'nilearn' has no attribute 'image'
```

Even more confusing, this code snippet successfully loads the image
```
import nilearn as ni
from nilearn import image
sample_img = ni.image.load_img('nifti_file.nii.gz')
```

Loading other nilearn modules such as plotting also doesn't work when used per the first code block.

**Comment by jeromedockes** [comment]
An example of the same thing in the standard library:

```
import urllib
# try without this line:
from urllib import parse
urllib.parse
```

I think we can close this one.
