### ISSUE TITLE
nistats: volume censoring with regression?

### ISSUE THREAD

**Issue by jdkent** [nilearn/nilearn#2526]
I'm trying to exclude the non-steady-state volumes by including a 1 in the design matrix for that volume and 0s everywhere else, but I am getting a strange result.
Specifically, the residuals appear to show a large error for the neighboring volume when I compare to scikit-learn's linear regression.
nistats version: `0.0.1b2` (let me know if I should post this issue somewhere else)

[here's a minimally reproducible example](https://github.com/jdkent/nistatsRegression/blob/master/example.ipynb)

[and here's a binder link to the same notebook](https://mybinder.org/v2/gh/jdkent/nistatsRegression/master) for anyone to play around for insights.

Thanks for the help!

**Comment by jdkent** [comment]
It looks to be an unfortunate interaction between the autoregressive model and outliers.

**Comment by bthirion** [comment]
This could be due to the autoregressive noise model in nilearn. Will take a look at that.

**Comment by bthirion** [comment]
Indeed, if you replace
`outlier_model = FirstLevelModel(t_r, minimize_memory=False)`
with
`outlier_model = FirstLevelModel(t_r, noise_model='ols', minimize_memory=False)`
This solves the problem.
Basically, the whitening approach used for AR(1) model fitting is not compatible with censoring

For thr time being, this calls for better documentation. Another, possiby better solution would be to perform  sensoring before model sensoring, using e.g. the  `sample_mask` argument of NiftiMasker.
