### ISSUE TITLE
sphinx fails building doc on master

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2527]
sphinx fails building doc on master:

https://app.circleci.com/pipelines/github/nilearn/nilearn/758/workflows/41b300e1-f83d-4cd7-ae2a-b0c4b233cc07/jobs/5898/parallel-runs/0/steps/0-107

**Comment by bthirion** [comment]
I don't really understand what happens 
The layout issue was not there when we merged the PR ?
`jinja2.exceptions.TemplateNotFound: sphinxdoc/layout.html`

**Comment by bthirion** [comment]
Solved AFAIK. Closing
