### ISSUE TITLE
plot_seed_to_voxel_correlation maps variance?

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2536]
[in this example](https://nilearn.github.io/auto_examples/03_connectivity/plot_seed_to_voxel_correlation.html#fisher-z-transformation-and-save-nifti) we apply the fisher transformation to a correlation map. We say "to acheive a normal distribution", but  doesn't the output of the Fisher transformation have a standard error of 1 / sqrt(N - 3) (and not 1) ? 
https://en.wikipedia.org/wiki/Fisher_transformation#Definition (of course with the usual issue that points in the time series are not iid)
ping @PeerHerholz

**Comment by bthirion** [comment]
`Normal` does not mean `standard normal`.

**Comment by jeromedockes** [comment]
yes that's true! :) still wasn't the objective to obtain standard/z scores for
plotting, as is often done? the filename the image is saved in seems to imply
that (`pcc_seed_correlation_z.nii.gz`)
anyway if it was a deliberate choice I close this issue.

**Comment by bthirion** [comment]
To me the main point of z-transform is to better fulfill the assumptions of statistical models, the reducing the proportion of false positives or false negatives.
