### ISSUE TITLE
Gray matter volume on Oasis dataset

### ISSUE THREAD

**Issue by sunjc73** [nilearn/nilearn#2540]
Previous studies have shown that gray matter volume decreases with age. However, I calculated the gray matter volume of Oasis dataset and found that it did not decline with age, but remained steady. So could you tell me the reason？ The total gray matter volume was calculated by meaning all the voxels for each individual. The code is shown below

```
import numpy as np
import matplotlib.pyplot as plt
from nilearn import datasets
from nilearn.input_data import NiftiMasker

oasis_dataset = datasets.fetch_oasis_vbm(n_subjects=n_subjects, data_dir='/home/sunjc/simulation/Nilearn/nilearn_data')
gray_matter_map_filenames = oasis_dataset.gray_matter_maps
age = oasis_dataset.ext_vars['age'].astype(float)

nifti_masker = NiftiMasker(
    standardize=False,
    smoothing_fwhm=2,
    memory='nilearn_cache')  

gm_maps_masked = nifti_masker.fit_transform(gray_matter_map_filenames)

perm1 = np.argsort(age)[::-1]
age = age[perm1]
grey_v = gm_maps_masked[perm1]

grey_v = grey_v[:,:].mean(axis=1)
plt.plot(age, grey_v)

```

![Figure_1](https://user-images.githubusercontent.com/17763745/87151606-ba2d0280-c2e6-11ea-9db6-abbeb8215d76.png)

Please refer to paper 'A Voxel-Based Morphometric Study of Ageing in 465 Normal Adult Human Brains', and the relevant figure is shown below

![2020-07-10 20-01-12屏幕截图](https://user-images.githubusercontent.com/17763745/87152437-43910480-c2e8-11ea-97f1-367242258e4c.png)

**Comment by bthirion** [comment]
Thx for reporting that. I think that your point is important but it definitely concerns the OASIS project itself rather than Nilearn. 
I guess that the T1 data have been processed with a Standard SPM-based pipeline. What would you suggest ?
Note: this discussion should take place on Neurostars rather than the issue tracker.
Is it OK to close the issue ?
Best

**Comment by sunjc73** [comment]
Thanksfor your prompt reply. I think this issue  can be closed.
