### ISSUE TITLE
`make_fresh_openneuro_dataset_urls_index` never tested nor used

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2542]
we can 
- remove it (but see @kchawla-pi 's [comment](https://github.com/nilearn/nilearn/pull/2514#issuecomment-659010916) )
- have one of the CI test suites run with `boto3` installed

**Comment by bthirion** [comment]
Thx. I think we should have one CI suite with boto3 indeed.

**Comment by GaelVaroquaux** [comment]
> Thx. I think we should have one CI suite with boto3 indeed.

Yes. We cannot have code that is not tested.

**Comment by jeromedockes** [comment]
as it is never used as part of nilearn functionality I think it should be removed. we can keep it in the repo as a separate script if we ever need to re-generate a list of AWS indices

**Comment by Remi-Gau** [comment]
Technically it is tested but never used anywhere in the code base or an example:

https://github.com/nilearn/nilearn/blob/c33cca7adab3d44ce5b2553f65738e6ecf93a3ac/nilearn/datasets/tests/test_utils.py#L451

**Comment by bthirion** [comment]
+1 fore removing that.

**Comment by jeromedockes** [comment]
I would just remove it. if we ever need something like it in the future, which we probably won't as we don't want to add many dataset fetchers, rewriting these 10 lines will be faster than realizing we have it somewhere and figuring out what this function is or what it does. besides it is made for 1 specific dataset. the test is meaningless -- it just writes a list in a json file then loads it and compares to the original list.
