### ISSUE TITLE
nistats: dependence between function calls – strange bug may affect reproducibility

### ISSUE THREAD

**Issue by kbonna** [nilearn/nilearn#2548]
Hi,

I've encountered very strange behavior of two functions – `map_threshold` from `nistats.thresholding` module and `get_clusters_table` from `nistats.reporting` module. It seems like the threshold value returned by `map_threshold` depends on the last output value(s) of `get_clusters_table` function or some internal function variables. Impact seems to be severe (the higher the `cluster_threshold` value passed to `get_cluster_table`, the higher the threshold returned by subsequent call of `map_threshold`). 

Here is a simple demonstration: https://github.com/kbonna/decidenet/blob/master/activation_analysis/nistats_map_threshold_bug.ipynb

I've tried to find a source of the problem studying code of both functions, but I everything seems to be ok at first glance. 

Am I missing something simple?

**Comment by jeromedockes** [comment]
thanks for reporting. there seems to be a bug in `get_clusters_table`, both in [nilearn](https://github.com/nilearn/nilearn/blob/4c1c7337b38506e6ef60873cfe3dd316ce869cf0/nilearn/reporting/_get_clusters_table.py#L146) and [nistats](https://github.com/nilearn/nistats/blob/bd4e27fdd5487b1ff920d4ae2473a7671153d2b3/nistats/reporting/_get_clusters_table.py#L145) : the input image is modified

**Comment by jeromedockes** [comment]
(in both the problematic line is `            stat_map[label_map == c_val] = 0` ), to reproduce the problem:
```
import numpy as np
from nilearn import datasets, image
from nilearn.reporting import get_clusters_table
# from nistats.reporting._get_clusters_table import get_clusters_table

img = image.load_img(datasets.fetch_neurovault_motor_task()["images"][0])
data = image.get_data(img).copy()
assert np.allclose(data, image.get_data(img)), "???"
get_clusters_table(img, 2., cluster_threshold=5)
assert np.allclose(data, image.get_data(img)), "image was modified"
```

would you like to open a PR to fix this issue?

**Comment by kbonna** [comment]
Yes, I will try to fix that and submit a PR
