### ISSUE TITLE
`MNI152TEMPLATE` (default background) is always plotted with x axis flipped

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2550]
Reported in [this neurostars discussion](https://neurostars.org/t/is-the-nilearn-mni-brain-flipped-l-r/16336) (thanks!)
the problem is that:
- the default background is not an actual nifti image but a `nilearn.image.img_plotting._MNI152Template` defined [here](https://github.com/nilearn/nilearn/blob/4c1c7337b38506e6ef60873cfe3dd316ce869cf0/nilearn/plotting/img_plotting.py#L339) that mimicks its interface
- `BaseSlicer._map_show` calls `reorder_img` on the input image [here](https://github.com/nilearn/nilearn/blob/4c1c7337b38506e6ef60873cfe3dd316ce869cf0/nilearn/plotting/displays.py#L753) and then expects to be working with an image that has a diagonal and positive affine
- `reorder_img` calls `new_img_like` to build an image with the positive affine and reordered data, `new_img_like` uses the original image's class to build the new image, [here](https://github.com/nilearn/nilearn/blob/4c1c7337b38506e6ef60873cfe3dd316ce869cf0/nilearn/image/image.py#L766), so in this case a `_MNI152Template`
- but this class's `__init__` [ignores its parameters](https://github.com/nilearn/nilearn/blob/4c1c7337b38506e6ef60873cfe3dd316ce869cf0/nilearn/plotting/img_plotting.py#L351), as it is a fake image that always loads the mni template. so the reordering has no effect and `_map_show` proceeds with a freshly loaded, but identical, mni template, and
- the element 0,0 of the mni template is `-2`, so x axis is flipped.

I guess a quick fix would be to have the `_MNI152Template` reorder the image in its `load` function

**Comment by alexlicohen** [comment]
wow. fast work! commenting to follow along.
