### ISSUE TITLE
permuted_ols output is transposed when n_perm=0

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#2554]
I am using the current master branch, and I noticed that `permuted_ols` returns `score_orig_data` with the shape `(n_regressors, n_descriptors)` under most circumstances (e.g., if `n_perms > 0`), but when `n_perms <= 0`, it returns the data with the shape `(n_descriptors, n_regressors)`.

Here is where the t-statistics are typically returned (note the `.T`):

https://github.com/nilearn/nilearn/blob/4c1c7337b38506e6ef60873cfe3dd316ce869cf0/nilearn/mass_univariate/permuted_least_squares.py#L469

Here is where the t-statistics are returned when `n_perms == 0`:

https://github.com/nilearn/nilearn/blob/4c1c7337b38506e6ef60873cfe3dd316ce869cf0/nilearn/mass_univariate/permuted_least_squares.py#L444 

I think the only thing that needs to change is that, in L444, `scores_original_data` should be `scores_original_data.T`.

EDIT: The bug doesn't seem to have to do with intercept testing. Just the number of permutations.

**Comment by bthirion** [comment]
Thx for reporting ! 
Looks like you're in a good position to open a PR ;-) let us know if you wish to do it.
Best,

**Comment by tsalo** [comment]
Can do!

I have one question that can be moved into a separate issue. In cases where "intercept testing" is used, is the expected behavior for any map with any voxels where all values are the same (e.g., all zeros) to generate NaNs from the max value step? Essentially, are maps with non-varying voxels considered "invalid" for the method?

**Comment by bthirion** [comment]
No, I would consider that the statistic is not defined in that voxel.
Ideally, such voxels should be masked out, but we can simply handle degenerate voxels (with null variance) during the initial data fit.

**Comment by tsalo** [comment]
Thanks. I'll open an issue then.
