### ISSUE TITLE
Voxels with all-zeros invalidate permuted_ols results across all voxels

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#2556]
I am using the current master branch of nilearn. When a voxel has zeros across all input maps and `permuted_ols` is used, all voxels in the results maps are invalid for permutation-based findings (i.e., the `-log(p)` and `h0` results, not the t-statistics).

This stems from https://github.com/nilearn/nilearn/issues/2554#issuecomment-672005510.

## Replicating the bug

```python
import numpy as np
from nilearn.mass_univariate import permuted_ols

n_voxels = 100  # instead of n_descriptors
n_maps = 50  # instead of n_samples
n_regressors = 1

tested_vars = np.ones((n_maps, n_regressors))
target_vars = np.random.random((n_maps, n_voxels))

# perfectly fine
p, t, h0 = permuted_ols(tested_vars, target_vars, model_intercept=False, n_perm=1000, random_state=1)

# now, one voxel will have all zeros
target_vars2 = target_vars.copy()
target_vars2[:, 0] = 0

p, t, h0 = permuted_ols(tested_vars, target_vars2, model_intercept=False, n_perm=1000, random_state=1)
```

In the second case, `h0` will be all NaNs, while `p` will be all -0.

## Fixing the bug

I am sure there are a number of ways this could be handled, from raising a warning when invalid voxels are included to working around the NaN issue. One solution I came across would be to replace [`numpy.amax()`](https://numpy.org/doc/stable/reference/generated/numpy.amax.html) (which propagates NaNs) with [`numpy.nanmax()`](https://numpy.org/doc/stable/reference/generated/numpy.nanmax.html#numpy.nanmax) here: 
https://github.com/nilearn/nilearn/blob/21fdc532dee895b5e46c3fc6a3d4f9803b247ac1/nilearn/mass_univariate/permuted_least_squares.py#L223

**Comment by bthirion** [comment]
I think that issuing a warning  + using nanmax is the right thing to do.
