### ISSUE TITLE
BUG: nilearn.plotting forces matplotlib backend change to Agg on macOS

### ISSUE THREAD

**Issue by larsoner** [nilearn/nilearn#2560]
on macOS:
```
>>> import matplotlib
>>> assert matplotlib.get_backend() == 'Qt5Agg'
>>> import nilearn.plotting
>>> assert matplotlib.get_backend() == 'Qt5Agg', matplotlib.get_backend()
AssertionError: agg
```
I have `backend : Qt5Agg\ninteractive : True` in `~/.matplotlib/matplotlibrc`. I assume it's due to this line:

https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/__init__.py#L37

It seems like unwanted behavior that the backend is changed.

**Comment by bthirion** [comment]
@kchawla-pi  can you give any hint on why this was added ? 

What other backend should be used instead (sorry I don't know that well) ?

**Comment by larsoner** [comment]
My 2c is that in general libraries should not set the matplotlib backend at all but respect whatever the given user's configuration is (even if it's just "use the matplotlib default")

**Comment by jeromedockes** [comment]
> My 2c is that in general libraries should not set the matplotlib backend at all but respect whatever the given user's configuration is (even if it's just "use the matplotlib default")

I agree.
(if CI was the motivation for doing this we can set the `MPLBACKEND` env
variable)

**Comment by GaelVaroquaux** [comment]
The motivation for doing this was that non technical users ssh into a remote  computer, run calculations, and then things crash after two hours of computation because there is no X server available. 

We tried to put some guards so that the switch happens only in a case where it's likely to be useful. Maybe those guards aren't fine enough. I believe that they are in plotting/__init__.py

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by kchawla-pi** [comment]
This should not be a problem on MacOS. The code is specifically checking
for that and not changing the backend on MacOS. Perhaps the check is too
stringent with a new version of MacOS?

**Comment by larsoner** [comment]
The conditional is:
```
        if (os.name == 'posix' and 'DISPLAY' not in os.environ
                and not (sys.platform == 'darwin'
                         and 'macosx' in current_backend)
        ):
            matplotlib.use('Agg')
```
So if someone is on macOS and their backend is not `macosx`, their backend will be set to `agg`. In my case, my backend is `Qt5Agg`, so it gets set to `agg`, which is not good.

**Comment by bthirion** [comment]
@larsoner Sorry for the inconvenience. Would you like to open a PR ?
Best,

**Comment by larsoner** [comment]
Personally I would chalk this up to a matplotlib / user config problem -- mpl or the user should choose a backend that works on their system.

But assuming you want to keep some fix in place, one option would be to `try/except` something like `plt.figure()` and force to Agg if it fails.

Beyond that, I'm still not entirely clear on why there is even a check for `darwin` as the platform. Shouldn't it rather be a check that the platform is Linux but there is no display, so just `sys.platform == 'linux' and 'DISPLAY' not in environ`? I've never seen a macOS headless system. On CIs they always fall back to software rendering at least...

**Comment by GaelVaroquaux** [comment]
> Beyond that, I'm still not entirely clear on why there is even a check for darwin as the platform. Shouldn't it rather be a check that the platform is Linux but there is no display, so just sys.platform == 'linux' and 'DISPLAY' not in environ?

There are other unices than macosx and linux. Maybe these are no much
used these days. I used to encounter them in high performance and
academic environments.

**Comment by larsoner** [comment]
So perhaps the check should just be `if sys.platform not in ('darwin', 'win32') and 'DISPLAY' not in os.environ`?

**Comment by bthirion** [comment]
Sounds right to me.
