### ISSUE TITLE
Add header optional argument to unmask function

### ISSUE THREAD

**Issue by eurunuela** [nilearn/nilearn#2562]
I've been going crazy with the unmask function in nilearn lately. I can successfully mask my data from 4D into 2D using the `apply_mask` function. Now, I'd like to move my results back to the 4D space with the `unmask` function, but whatever I generate does not have the same header or the same TR as the input data. This is a problem for visualizing the results with AFNI.

I believe adding an optional `header` argument to the `unmask` function could potentially make saving unmasked data much easier and straightforward.

**Comment by GaelVaroquaux** [comment]
You should be using the niftimasker object for this purpose. It will make sure that information is not lost. 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by GaelVaroquaux** [comment]
At a quick glance, it seems right. What didn't work?

**Comment by thomasbazeille** [comment]
Do wish to provide specific feedback on your problme with masker @eurunuela ? This is definitely the object you need.

Note that you can provide t_r directly in Masker definition but I think it's only used if you set a high-pass or low-pass filter as well.
In some cases NiftiMasker itself is not the best suited object and some other Masker objects are recommended. They are described here : https://nilearn.github.io/manipulating_images/masker_objects.html

**Comment by eurunuela** [comment]
Thank you both for your responses. I'm sorry I haven't found the time to work on this recently. 

You can close the issue if you will, I'll contact one of you if I happen to run into the same issue.

Thanks!
