### ISSUE TITLE
plot wrong

### ISSUE THREAD

**Issue by alienx-zero** [nilearn/nilearn#2563]
This is my code following the tutorials:
`# -*- coding: utf-8 -*-
"""
Created on Thu Sep  3 20:50:02 2020

@author: 99488
"""

from nilearn import datasets
# By default 2nd subject will be fetched
haxby_dataset = datasets.fetch_haxby()
# 'func' is a list of filenames: one for each subject
fmri_filename = haxby_dataset.func[0]

# print basic information on the dataset
print('First subject functional nifti images (4D) are at: %s' %
      fmri_filename)  # 4D data

from nilearn import plotting
import matplotlib.pyplot as plt

from nilearn.image import mean_img
plt.figure(0)
plotting.view_img(mean_img(fmri_filename), threshold=None)
plt.show()`

I implement it in spyder, in plots window, it show nothing 
![1599187414](https://user-images.githubusercontent.com/55502834/92193695-f12b1a80-ee36-11ea-81c3-a66456ac111a.png)
But, if I use jupyter, it works
![1599187501(1)](https://user-images.githubusercontent.com/55502834/92193771-1e77c880-ee37-11ea-938b-6f0740d11df6.png)
why it is different?

**Comment by jeromedockes** [comment]
`view_img` returns the content of an html page, to be displayed by a web browser. The jupyter notebook can display it inline but otherwise you have to call `.open_in_browser()` on the result (or `save_as_html` to save to disk and then open the file with a web browser)

**Comment by alienx-zero** [comment]
@jeromedockes get it~thx
