### ISSUE TITLE
[BUG] Decoding docs improvements 

### ISSUE THREAD

**Issue by thomasbazeille** [nilearn/nilearn#2564]
Following #2415, two points that were not tackled inside #2476 in the interest of short cycles

- [x]  Add a section in 2.1 on how to determine chance with a Decoder API (waiting for #2147) EDIT : Adressed #2622
- [ ]  Rethink 2.2 section on OVO vs OVA, not sure it is useful as Decoder doesn't provide this flexibility easily. But show how to plot a confusion matrix using Decoder on a simple example.

**Comment by bthirion** [comment]
- Regarding chance determination with Decoder: this is performed in `plot_haxby_full_analysis.py` (drvtion 9.3.11) we just need to refer to that, right ?
- I would propose to leave the OVO vs OVA thing aside for the moment.
- Confusion matrix is presented in 2.2. This is enough imho. Agreed  ?

**Comment by thomasbazeille** [comment]
First part adressed by #2622 

> I would propose to leave the OVO vs OVA thing aside for the moment
Ok
> `Confusion` matrix is presented in 2.2. This is enough imho. Agreed ?
I think it would be helpful to show in an example how to make a confusion matrix from decoder object since it does not seem straight forward IMHO

If you don't agree we can close

**Comment by bthirion** [comment]
+1 for confusion matrix for decoder object example !

**Comment by michellewang** [comment]
Hi, I'd be interested in adding an example for plotting a confusion matrix from a decoder object, if you still think this is a good idea.

Should this be a new example or get folded into an existing one where there is a train/test split? For example https://nilearn.github.io/stable/auto_examples/02_decoding/plot_haxby_frem.html.

**Comment by jeromedockes** [comment]
Thanks @michellewang ! yes I think that would still be a good idea. If possible it would be better to include that in an existing example
