### ISSUE TITLE
outdated link to removed example in glm doc

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2572]
It seems one part of the GLM docs was made outdated by #2476 that was merged
just before GLM docs were added. The linked example
(`07_advanced/plot_haxby_block_classification.py`) has moved to `02_decoding`,
and doesn't seem to show usage of `plot_event` any more

https://github.com/nilearn/nilearn/blob/master/doc/glm/first_level_model.rst#event-based

ping @swaythe and @thomasbazeille

**Comment by KamalakerDadi** [comment]
@tbng has foreseen this issue and fixed in this PR #2565 
https://github.com/nilearn/nilearn/pull/2565#issuecomment-698992527

**Comment by thomasbazeille** [comment]
the new example should be in 02_decoding with a new title and should display the use of plot_event

**Comment by jeromedockes** [comment]
great! closing then
