### ISSUE TITLE
Nilearn main documentation website stuck at version 0.6.2

### ISSUE THREAD

**Issue by tbng** [nilearn/nilearn#2578]
I'm not sure if this is on purpose but currently all the documentation on https://nilearn.github.io/index.html seems to stuck at version 0.6.2 (while the correct latest version is 0.7.0a), especially on the `What's news` section. This might create wrong impression when users land on the front page. Again I'm not familiar with how the documenation website is made from sphinx html build so I might be wrong.

**Comment by KamalakerDadi** [comment]
0.7 is not released yet which is development. The one you are watching is released/stable version.

**Comment by tbng** [comment]
> 0.7 is not released yet which is development. The one you are watching is released/stable version.

OK makes sense. I guess I would close the issue?
