### ISSUE TITLE
A question about  cross_val_score in MVPA

### ISSUE THREAD

**Issue by Dong095939** [nilearn/nilearn#2581]

**Comment by thomasbazeille** [comment]
Hello, can you provide some info on your questions ? Usually if this is more of a usage question, we'd rather you ask it on Neurostars.org forum. If this is for a bug report, cross_val_score is a scikit learn function and bugs should be reported on their issue tracker. Thanks !

**Comment by Dong095939** [comment]
Got it, Thans for your reply.
