### ISSUE TITLE
confounds are not effectively regressed with some NiftiMasker parameters

### ISSUE THREAD

**Issue by pbellec** [nilearn/nilearn#2584]
I am working with nilearn 0.6.2
I am specifying confounds to a masker,  like so:
``` python 
masker = NiftiMasker(standardize=True, mask_img=mask).fit()
tseries = masker.transform(img, confounds=conf)
``` 
I expect the confounds to be regressed from tseries, i.e. the covariance between `tseries` and `conf` to be approximately zero. 
I've tested whether that is the case systematically with different values for `standardize`, and with/without demeaning the `conf`.
See the test file appended at the end of this message (written for `pytest`). 

My conclusion is that confounds are not regressed effectively in two situations: (1) with `standardize=False` and no demeaning of the confounds; (2) with `standardize='psc'` and demeaning of the confounds. 

In my persective both are bugs, although if one understands what NiftiMasker does it's logical. 
The problem is that the same standardization is applied to the fMRI time series and the confounds. 
This means that if `standardize=False`, then confounds do not get demeaned, and the "regression" then fits the mean of the provided signals, instead of fitting the fluctuations of the confounds to the fMRI fluctuations. 

If `standardize='psc'` and the confounds are demeaned, then it's impossible to adjust the confounds to a percentage signal change, so nilearn sets the confounds to zero.... While really the weights of the confounds are irrelevant (they will get scaled through the confound regression anyway), so there is no reason to scale them to psc. The regression would be more meaningful if the confounds were demeaned instead.

The solution I think makes the most sense is to systematically demean the confounds prior to regression, instead of standardizing them using the same option as the fMRI time series. At least, there should be a separate parameter for the standardization of the confounds set to `zscore`, but I can't think of a use case where users would not want to demean. 

Happy to work on a PR, and/or incorporate these tests in the code base.
Let me know what you think.

``` python 
import numpy as np
from pandas import read_csv
from sklearn.preprocessing import StandardScaler
from nibabel import Nifti1Image
from nilearn.input_data import NiftiMasker

epsilon = 10e-10


def _simu_img():
    # Random confounds
    conf = 2 + np.random.randn(100, 6)

    # Random 4D volume
    vol = 100 + 10 * np.random.randn(5, 5, 2, 100)
    img = Nifti1Image(vol, np.eye(4))

    # create an nifti image with the data, and corresponding mask
    mask = Nifti1Image(np.ones([5, 5, 2]), np.eye(4))

    return img, mask, conf


def _cov_conf(tseries, conf):
    conf_n = StandardScaler().fit_transform(conf)
    tseries_n = StandardScaler().fit_transform(tseries)
    cov_mat = np.matmul(tseries_n.transpose(), conf_n)
    return cov_mat


def _confounds_regression(standardize=True, demean=True):
    img, mask, conf = _simu_img()
    masker = NiftiMasker(standardize=standardize, mask_img=mask).fit()
    if demean:
        conf = StandardScaler(with_std=False).fit_transform(conf)
    tseries = masker.transform(img, confounds=conf)
    cov_mat = _cov_conf(tseries, conf)
    return np.sum(np.abs(cov_mat))


def test_no_standardize_demean():
    assert _confounds_regression(standardize=False, demean=True) < epsilon


def test_zscore_demean():
    assert _confounds_regression(standardize="zscore", demean=True) < epsilon


def test_psc_demean():
    assert _confounds_regression(standardize="psc", demean=True) < epsilon


def test_no_standardize_no_demean():
    assert _confounds_regression(standardize=False, demean=False) < epsilon


def test_zscore_nodemean():
    assert _confounds_regression(standardize="zscore", demean=False) < epsilon


def test_psc_nodemean():
    assert _confounds_regression(standardize="psc", demean=False) < epsilon
```

**Comment by bthirion** [comment]
I think I agree with you: systematically demeaning the confounds makes more sense to me !
Thx for digging into this.

**Comment by NicolasGensollen** [comment]
I'm closing this as it should have been fixed in #2609

**Comment by danjgale** [comment]
I'm aware of this is closed, but I'm curious: With the introduction of `standardize_confounds` in #2609 (and changes pending in #2730), is there a case in which a user would _not_ want to use `standardize_confounds=True`? For instance, would a user set `standardize_confounds=False` only when `standardize=False`?

**Comment by bthirion** [comment]
Sincerely, I don't see any reason not to standardize confounds. 
The justification for having the parameter is transparency: make clear to the user what computation is done in the model.
