### ISSUE TITLE
Harvard-Oxford label spelling inconsistency

### ISSUE THREAD

**Issue by jbdenniso** [nilearn/nilearn#2588]

**Comment by jbdenniso** [comment]
This should be an easy fix but wanted to make sure it got noted.

**Comment by bthirion** [comment]
Could you elaborate a little bit ? Thx.

**Comment by NicolasGensollen** [comment]
Hi @jbdenniso !
Any update on this?

**Comment by tsalo** [comment]
I took a look and I noticed a couple of minor possible typos:

- "Left Lateral Ventrical" (should be ventricle)
- "Frontal Operculum Cortex", "Parietal Operculum Cortex", and "Central _Opercular_ Cortex"
    - All three should probably be opercular, not operculum.
- "Right Cerebral Cortex " and "Left Cerebral Cortex " (trailing whitespace)

**Comment by jbdenniso** [comment]
Sorry for missing these comments I must have notifications off. Tsalo correctly identified what I had seen misspelling ventricle and the trailing whitespace in right & left Cerebral Cortex. I had not noticed the difference between the opercular labels.

**Comment by Remi-Gau** [comment]
Adding a good first issue label, though this may need some pointers on where in the code base one should start digging into.
