### ISSUE TITLE
Axes3D no longer adds itself to figure

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2614]
Upcoming break in Matplotlib `3.4.0`, see: [https://github.com/matplotlib/matplotlib/pull/18564](https://github.com/matplotlib/matplotlib/pull/18564)

This is causing 3 tests to fail on Travis with matplotlib-dev: 

```
FAILED plotting/tests/test_surf_plotting.py::test_plot_surf_stat_map - assert...
FAILED plotting/tests/test_surf_plotting.py::test_plot_surf_contours - IndexE...
FAILED plotting/tests/test_surf_plotting.py::test_plot_surf_contours_error - ...
===== 3 failed, 829 passed, 1 skipped, 1800 warnings in 721.48s
```

`ax = Axes3d(fig)` will need to be explicitly added to the figure with `fig.add_axes(ax)`

**Comment by jeromedockes** [comment]
there is still [this pending comment in a matplotlib issue](https://github.com/matplotlib/matplotlib/issues/18939#issuecomment-726142191) that suggests making the axis add itself by default

**Comment by tacaswell** [comment]
You will now be warned about this change rather than broken.   Long term we are still deprecating the behavior,  but hopefully this is enough of a migration window.

**Comment by bthirion** [comment]
@tacaswell  Thx for the information !

**Comment by tacaswell** [comment]
xref https://github.com/matplotlib/matplotlib/pull/19496
