### ISSUE TITLE
Duplicate examples

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2615]
It looks like the following examples:

- [9.6.3. Second-level fMRI model: a paired-sample test](https://nilearn.github.io/auto_examples/05_glm_second_level/plot_second_level_paired_sample_test.html#sphx-glr-auto-examples-05-glm-second-level-plot-second-level-paired-sample-test-py)
- [9.6.4. Second-level fMRI model: a two-sample test](https://nilearn.github.io/auto_examples/05_glm_second_level/plot_second_level_two_sample_test.html#sphx-glr-auto-examples-05-glm-second-level-plot-second-level-two-sample-test-py)

are exactly the same.

**Comment by jeromedockes** [comment]
> It looks like the following examples:
>
> - [9.6.3. Second-level fMRI model: a paired-sample test](https://nilearn.github.io/auto_examples/05_glm_second_level/plot_second_level_paired_sample_test.html#sphx-glr-auto-examples-05-glm-second-level-plot-second-level-paired-sample-test-py)
> - [9.6.4. Second-level fMRI model: a two-sample test](https://nilearn.github.io/auto_examples/05_glm_second_level/plot_second_level_two_sample_test.html#sphx-glr-auto-examples-05-glm-second-level-plot-second-level-two-sample-test-py)
>
> are exactly the same. 

Indeed! we can remove one example for free :)

**Comment by bthirion** [comment]
:)
