### ISSUE TITLE
labeling connectome nodes with anatomical regions

### ISSUE THREAD

**Issue by Ziaeemehr** [nilearn/nilearn#2618]
I am looking for a way to label each node of a connectome matrix with its anatomical region.
something like this:
[12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 12 19 19 19 19 19
 19  6  6 14 14 14 ... ]
which for example show 19 first elements belong to region 12 and so on. We know the xyz coordinates of nodes. So we can use different parcellation atlas to map each node on its region.

Is it possible in `nilean`?

it would be even better to if we could get the downsambled connection matrix (e.g. connectome with 998 nodes ->  32 connection matrix)

**Comment by jeromedockes** [comment]
multiplying the coordinates of a note by the inverse of the image affine will give you the voxel index and you can read the atlas image at that location to find the label. you can then sum over the voxels in each region to get the number of connections between regions. Note you could also directly use the atlas to define the connectome, thus you would directly have a connectome with one node per atlas region. general comments: we prefer to use github issues for bug reports, and the [neurostars forum](https://neurostars.org/) for usage questions

**Comment by Ziaeemehr** [comment]
@jeromedockes Thank you I think about your answer. I already asked it [here](https://neurostars.org/t/down-sampling-connectome-network-to-destrieux-parcellation/17326) about a month ago but could not get the proper answer.

**Comment by NicolasGensollen** [comment]
Hi @Ziaeemehr 
Did @jeromedockes answered your question in his comment above, or is there still something unclear here?
If not I suggest we close this.

**Comment by Ziaeemehr** [comment]
The  jeromedockes comment helped me to find the proper documentation.
