### ISSUE TITLE
Use pandas in the data loaders

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2621]
Since Pandas was added to the dependencies, we can use it in the data loaders to read CSV files instead of Numpy.
See #2619

**Comment by jeromedockes** [comment]
> Since Pandas was added to the dependencies, we can use it in the data loaders to read CSV files instead of Numpy.
> See #2619 

I wouldn't modify existing loaders; but when writing new loaders (which
should almost never happen anyway) pandas can be used when that's more
convenient

**Comment by GaelVaroquaux** [comment]
> I wouldn't modify existing loaders;

I had in mind modifying loaders :)

**Comment by jeromedockes** [comment]
> I had in mind modifying loaders :)

oops just saw your comment in #2619 -- ok, let's change them then :)

**Comment by NicolasGensollen** [comment]
Great! Thanks @achamma723 !
