### ISSUE TITLE
Misplaced overlay

### ISSUE THREAD

**Issue by idevicente** [nilearn/nilearn#2623]
Hey there!

I am trying to overlay two different R^2 maps on top of a T1 anatomical image.
One of the R^2 overlays works just fine, but when I try with the other R^2 map it appears misplaced from the T1 (see picture attached). In other viewers such as AFNI both of the overlays look perfectly aligned, so in principle it is not a preprocessing issue.

Any idea how to solve this? Below you can find the code I used.
Cheers,
Iñigo

![Nilearn_issue](https://user-images.githubusercontent.com/65595595/100861422-14934f00-3492-11eb-91e3-d64187a8fe7d.png)

`import nilearn as nl`
`import nibabel as nb`
`from nilearn import plotting`

`T1_ns_s35 = nb.load("/home/user/T1_ns.nii.gz")`
`odr_s35 = nb.load("/home/user/odr_s35.nii.gz")`
`ols_s35 = nb.load("/home/user/ols_s35.nii.gz")`

`display = nl.plotting.plot_anat(T1_ns_s35, display_mode = 'x', cut_coords = [-38, -19, -1, 18, 40], dim = 0)`
`display.add_overlay(odr_s35, cmap=nl.plotting.cm.red_transparent_full_alpha_range, vmax = 0.2, colorbar = True, alpha =1, threshold = None)`

`display2 = nl.plotting.plot_anat(T1_ns_s35, display_mode = 'x', cut_coords = [-38, -19, -1, 18, 40], dim = 0)`
`display2.add_overlay(ols_s35, cmap=nl.plotting.cm.red_transparent_full_alpha_range, vmax = 0.2, colorbar = True, alpha =1, threshold = None)`

**Comment by thomasbazeille** [comment]
Hello ! It seems weird indeed, the height of anatomical backgrounds of display2 seem to be lower than the one of display1. Did you check that the images had same affine ? I guess to replicate and debug, it'd be easiest if you could share the the images involved somehow.

**Comment by idevicente** [comment]
Solved! The images had different grids.
I should have checked that before, my apologies...

Thanks for the help!

**Comment by thomasbazeille** [comment]
Cool!
