### ISSUE TITLE
Bug in example 9.3.12

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2624]
It looks like the last section (`9.3.12.4`) in this [example](https://nilearn.github.io/auto_examples/02_decoding/plot_haxby_different_estimators.html#sphx-glr-auto-examples-02-decoding-plot-haxby-different-estimators-py) is not doing what it is supposed to. 

More precisely, the following lines

```python
# Restrict the decoding to face vs house
condition_mask = np.logical_or(stimuli == b'face', stimuli == b'house')
stimuli = stimuli[condition_mask]
fmri_niimgs_condition = index_img(func_filename, condition_mask)
```

build objects that aren't used afterwards for the plotting of the stat maps. 

Moreover, with Pandas `1.1.3`, the condition mask I get is empty:

```python
condition_mask = np.logical_or(stimuli == b'face', stimuli == b'house')
sum(condition_mask.values)
0
```

```python
condition_mask = np.logical_or(stimuli == 'face', stimuli == 'house')
sum(condition_mask.values)
216
```

**Comment by bthirion** [comment]
These are good points, thx.
