### ISSUE TITLE
Create "Administrative" repo

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2626]
I believe we mentioned this during our last meeting, but this could be a good time to do it since our next meeting is coming up shortly. 
The idea would be to store the meetings' notes in a separate repo under the nilearn organization like scikit-learn does [here](https://github.com/scikit-learn/administrative).

**Comment by GaelVaroquaux** [comment]
+1! Thanks for being on top of this!

**Comment by bthirion** [comment]
Done, thx for the reminder !
