### ISSUE TITLE
Move tests from Travis to GitHub Actions and/or Azure Pipelines

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2627]
Following discussion started in #2625 

I think that a possible first step in this direction would be to move one travis job to GitHub actions (similar to what was done for MNE a few weeks ago), and move another one to Azure Pipelines.
In the mean time, this could be the opportunity to check whether we need all current jobs, and how we want to distribute them between the available services.

**Comment by bthirion** [comment]
We might discuss that in the upcoming coredev meeting.

Just to be sure: why not simply ask Travis for some resources ?

**Comment by GaelVaroquaux** [comment]
> Just to be sure: why not simply ask Travis for some resources ?

That plan failed for scikit-learn (we were not granted resources), so it
might fail for nilearn.

**Comment by NicolasGensollen** [comment]
Closing since this has been addressed by #2633
