### ISSUE TITLE
Improve Issue Templates

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2629]
As discussed in last meeting:

TODO:

- [x] Fix labels in current issue templates which are not added automatically
- [ ] Improve existing templates
- [x] Add new templates? (Documentation Improvement, Question, others...?)

**Comment by tsalo** [comment]
It would be great to have a link on the issue template choice page that goes directly to NeuroStars for usage questions. I think that should be possible with a config file (see [here](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)). +1 for a documentation improvement template as well.

**Comment by bthirion** [comment]
+1 for a link to Neurostars !

**Comment by tsalo** [comment]
Regarding improving the actual templates- what about making the summary comment at the top into specific sections?

For example, for the bug report, instead of

```
<!--

Include this information:
-------------------------
What version of Nilearn are you using?
What were you trying to do?
What did you expect will happen?
What actually happened?

List the steps you performed that revealed the bug to you.
Include any code samples. Enclose them in triple back-ticks (```)
Like this:

```
<code>
``` 
-->
```

we could have:

```
Nilearn version: 

### Expected behavior


### Actual behavior


### Code to reproduce

\```python

\```
```

**Comment by NicolasGensollen** [comment]
I like the idea! :+1: 
I think the template is more clear and this will perhaps encourage user to copy-paste their code to reproduce.
