### ISSUE TITLE
seeding in `_utils.data_gen`

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2631]
- `utils.data_gen.generate_fake_fmri` creates a `np.random.RandomState` (mutable
  default argument) in its definition. This might actually have been intentional
  so that it returns a different output each time it is called, but it is not
  the behavior of other functions in this module, which use 0 as a fixed seed by
  default, and it means that the data seen eg by unit tests depends on the order
  in which tests are executed, which may cause spurious failures. instead, this
  function should initialize a new random generator by default, and callers can
  call it with different seeds or pass an existing generator.

- most other functions in the same module, eg `generate_timeseries`, have a
  `rand_gen` parameter that has a different behavior than the `random_state`
  used in many nilearn and scikit-learn functions. Indeed, with `rand_gen` (ie
  in `data_gen`):
     - `None` -> `RandomState(0)`
     - anything else must be a random number generator
  whereas with scikit-learn's `check_random_state`:
     - `None` -> `RandomState(None)` ie get a seed from `/dev/urandom` or the clock
     - an int -> use that as a seed
     - a random number generator -> use that as-is
  this is not a big issue but as `_utils.data_gen` is a private module making
  the api more similar to `check_random_state` is doable.

**Comment by rawwar** [comment]
Hi, I want to contribute to this issue. I am working on it. I will update this comment or create another one to notify if I no longer am working on this one.
