### ISSUE TITLE
ENH+NEWFEATURE: backport of sklearn.utils.extmath.squared_norm

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#264]
We need a backport of sklearn.utils.extmath.squared_norm, and we need to use it in many places.

**Comment by AlexandreAbraham** [comment]
There are not so much details. I think that we raised the min version of scikit_learn so is this issue still holding?

**Comment by AlexandreAbraham** [comment]
No further details, closing. Please reopen if needed.
