### ISSUE TITLE
accept `pathlib.Path` where strings representing filesystem paths are expected

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2642]
for example in `image.load_img`, `_utils.niimg.load_niimg`, `surface.load_surf_mesh` and `surface.load_surf_data`

**Comment by bakyazi** [comment]
hello, i am new in open source. can i work on it?

**Comment by jeromedockes** [comment]
>  hello, i am new in open source. can i work on it?

that would be great, thanks for offering!

**Comment by emdupre** [comment]
This is something that is handled natively with nibabel 3.0 ! Could be a chance to check for those potential updates.

**Comment by udion** [comment]
Hello, 
I am working on implementing this feature.

**Comment by RaphaelMeudec** [comment]
I started looking into it:

- all functions cited by Jerome raise either a `TypeError`, either a `ValueError`
- this is the case because nilearn checks for `isinstance(name, str)`
- as @emdupre said, nibabel underlying functions seem to be working with Path (at least, I checked `nibabel.load` and `nibabel.freesurfer.io`)

I guess we should loosen the `isinstance` check to accept pathlib.Path arguments

**Comment by RaphaelMeudec** [comment]
@udion let me know if you need help on this!

**Comment by udion** [comment]
Thank you. I was also thinking to check for the `Pathlib` object.

**Comment by effigies** [comment]
If it's helpful, you can import or copy [`nibabel.filename_parser._stringify_path()`](https://github.com/nipy/nibabel/blob/5c4f39cef1f04a9afd241242c7f0148d7e5935c9/nibabel/filename_parser.py#L19-L46).

**Comment by udion** [comment]
@RaphaelMeudec @effigies 
I made the following changes, to begin within the `nilearn/_utils/niimg_conversions.py` that has the `check_niimg` function that is invoked when `nilearn.image.load_img` is called. The idea was to extract the string from the `pathlib object` and then process it in the same manner as a regular string (currently handled by the code).

```python
if isinstance(niimg, pathlib.Path):
        # get the string from pathlib object
        # and then process like a normal string
        niimg = niimg.absolute().as_posix()
        if wildcards and ni.EXPAND_PATH_WILDCARDS:
            # Ascending sorting + expand user path
            filenames = sorted(glob.glob(os.path.expanduser(niimg)))
            # processing filenames matching globbing expression
            if len(filenames) >= 1 and glob.has_magic(niimg):
                niimg = filenames  # iterable case
            # niimg is an existing filename
            elif [niimg] == filenames:
                niimg = filenames[0]
            # No files found by glob
            elif glob.has_magic(niimg):
                # No files matching the glob expression, warn the user
                message = ("No files matching the entered niimg expression: "
                            "'%s'.\n You may have left wildcards usage "
                           "activated: please set the global constant "
                           "'nilearn.EXPAND_PATH_WILDCARDS' to False to "
                           "deactivate this behavior.") % niimg
                raise ValueError(message)
            else:
                raise ValueError("File not found: '%s'" % niimg)
        elif not os.path.exists(niimg):
            raise ValueError("File not found: '%s'" % niimg)
```

1. I checked `nilearn.image.load_img` by passing `pathlib` object to a nifty file and it works.
2. Does it make sense?
3. In the `nilearn/image/tests/test_image` there is no test function for load image, why is that?

**Comment by ymzayek** [comment]
I see there are a couple of stalled PRs concerning this issue. I could pick it up and try to finish it unless there is somebody else that still wants to work on it.
