### ISSUE TITLE
Add moving-average principal component analysis algorithm

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#2662]
Moving-average PCA (MA-PCA) is implemented in the [Group ICA of fMRI Toolbox (GIFT)](https://trendscenter.org/software/gift/), for order selection (i.e., number of components) during PCA dimensionality reduction prior to ICA (see [Li, Adali, & Calhoun, 2007](https://onlinelibrary.wiley.com/doi/10.1002/hbm.20359)). We use a Python implementation of this method in [`tedana`](https://github.com/ME-ICA/tedana/blob/5369e1d571030882b90dd01c86839c4fb9a6c32f/tedana/decomposition/ma_pca.py), but have seen interest in the method from other libraries. We were interested in moving the implementation to its own repository or, preferably, into `nilearn`.

At today's `tedana` developers call, we came to the conclusion that we should see if MA-PCA would be a good fit for `nilearn`. Would it be reasonable to add to `nilearn.decomposition`?

**Comment by bthirion** [comment]
If you find it useful for you, then it's a useful feature.
From a math perspective, I can only warn that this should only be seen as a heuristic, not as a kind of "true dimensionality" . The reason is that the various sources of correlations present in the data that break the conditions for any theoretical results to apply... buut people like to believe in a "true" model.   
This being said, heuristics are useful, thus my message  (first sentance above) is positive :-)

**Comment by GaelVaroquaux** [comment]
My question would be: what would it be useful for? Another way to phrase
this is: can we make an example in nilearn, using the datasets that we
have, that is meaningful to an end user?

**Comment by tsalo** [comment]
In `tedana` we use it to prepare data for ICA and to determine how many components should be extracted with the ICA. In the case of examples, we could perhaps use it before CanICA? Or we could add a new example that compares CanICA to MA-PCA+FastICA?

**Comment by GaelVaroquaux** [comment]
I have the feeling that moving-average PCA (if I understand it well) can
simply be done by low-pass filtering and running a PCA. I would consider
this as cleaner from a signal-processing point of view.

**Comment by tsalo** [comment]
@eurunuela has a much better handle on the algorithm, since he translated GIFT's MATLAB implementation to Python. If the results _are_ identical (or at least reasonably similar), I agree that the more straightforward approach would be preferable.

**Comment by eurunuela** [comment]
The key point of the moving-average (or entropy-based) PCA is it uses the entropy of i.i.d. surrogates to estimate the optimal number of components for PCA. The PCA step of maPCA we are currently using in `tedana` is the sklearn PCA with the estimated number of components from the moving-average (or entropy-based) part.

**Comment by tsalo** [comment]
Unless I'm misunderstanding it, it sounds like MA-PCA is different from PCA on a low-pass filtered version of the data.

**Comment by tsalo** [comment]
There is now a fairly stable library for MAPCA ([`ME-ICA/mapca`](https://github.com/ME-ICA/mapca)), and incorporating it into nilearn would require relicensing (with permission from the GIFT creators), so I think I'm going to close this.
