### ISSUE TITLE
difumo atlas resolution

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2665]
difumo maps downloaded with `resolution_mm=2` seem to have 1.875 mm resolution
```
from nilearn import datasets, image

difumo = datasets.fetch_atlas_difumo(dimension=64, resolution_mm=2)
difumo_maps = image.load_img(difumo["maps"])
print(difumo_maps.affine)
```

also why are we downloading the `resample_dictionaries.py` script?

**Comment by bthirion** [comment]
Indeed...

**Comment by KamalakerDadi** [comment]
>difumo maps downloaded with resolution_mm=2 seem to have 1.875 mm resolution

so what do you suggest?

>also why are we downloading the resample_dictionaries.py script?

down the lane somebody should not ask a question of how it is resampled.

**Comment by jeromedockes** [comment]
> so what do you suggest?

in order of preference:

- upload the maps resampled to 2mm and download these
- resample the maps in the fetcher

**Comment by KamalakerDadi** [comment]
> so what do you suggest?
>in order of preference:

>- upload the maps resampled to 2mm and download these
>- resample the maps in the fetcher

why not modifying the doc string to 1.875

**Comment by jeromedockes** [comment]
>>- upload the maps resampled to 2mm and download these
>>- resample the maps in the fetcher
>
> why not modifying the doc string to 1.875

yes that's also an option. but it is not only the docstring, the value
of resolution_mm parameter value would also have to be changed, and we
probably don't want to rely on a float comparison to identify which maps
to return (passing `resolution_mm=1.875` doesn't seem like a good
option)

**Comment by bthirion** [comment]
I am in favor of resampling it to 2mm.

**Comment by KamalakerDadi** [comment]
Ok. So, the option is either 2mm or 3mm and nothing else. Right? How about resample_dictionaries.py, remove?

I think there is an Open Science Framework (OSF) account in the name of Nilearn. I don't know the credentials. Currently, the files on my personal OSF account.

**Comment by bthirion** [comment]
> I think there is an Open Science Framework (OSF) account in the name of Nilearn. I don't know the credentials. Currently, the files on my personal OSF account.
I don't have it either. maybe @kchawla-pi ? or @GaelVaroquaux ?

**Comment by bthirion** [comment]
> Ok. So, the option is either 2mm or 3mm and nothing else. Right? How about resample_dictionaries.py, remove?

Yes. But keep resample dictionaries, that is always useful.

**Comment by KamalakerDadi** [comment]
>I think there is an Open Science Framework (OSF) account in the name of Nilearn. I don't know the credentials. Currently, the files on my personal OSF account.
>I don't have it either. maybe @kchawla-pi ? or @GaelVaroquaux ?

Good point. Just searched in my inria email account and found them. I shared with you again.

**Comment by GaelVaroquaux** [comment]
>     I don't have it either. maybe @kchawla-pi ? or @GaelVaroquaux ?

The account was created on Oct 8th 2018, by Kshitij, and the credentials
were shared with Kamalakar, Bertrand and myself in an email named
"NiLearn account on https://osf.io"

If you have difficulties finding it, I'll forward it again.

**Comment by bthirion** [comment]
Got it, thx.
