### ISSUE TITLE
Decoder.score() behaviour in classification mode

### ISSUE THREAD

**Issue by RaphaelMeudec** [nilearn/nilearn#2667]
Hello!

I'm not sure if this issue is a documentation or feature request issue: the `.score` seems a bit confusing for me as a new-comer. 

I used the Decoder object in a classification tasks. After fitting the model, I used the  `.score` method, expecting it to compute the mean accuracy (as it is done in scikit-learn for classifiers). I got lucky its value came back negative, it made me look at the documentation and the fact that it computes R^2 coefficient.

I think it should be a bit more explicit to the user that `.score` in a classification fashion does not compute the mean accuracy:

- either by changing the behaviour (which seems tricky as it comes from inherited scikit-learn RegressorMixin)
- or by explicitly warn the user when running the method (which should be easier by using the `self.is_classification` flag) and make a visible warning in the documentation

**Comment by jeromedockes** [comment]
Thanks for pointing this out! IMO it's a bug so I would go for your first
suggestion -- change the behavior. Either by having the _BaseDecoder inherint
from LinearModel rather than LinearRegression if possible, or by overriding the
score method.

**Comment by jeromedockes** [comment]
WDYT @tbng  and @thomasbazeille ?

**Comment by NicolasGensollen** [comment]
I might be wrong but I would expect `.score` to use whatever scoring strategy was provided to the decoder object (`decoder.scoring`). So I'd be in favour of overriding the `score` method to rely on the user-defined strategy.

**Comment by jeromedockes** [comment]
> I might be wrong but I would expect `.score` to use whatever scoring strategy was provided to the decoder object

Good point! I agree that's the most sensible behaviour

**Comment by bthirion** [comment]
Agreed. Thx for raising the point.
