### ISSUE TITLE
provide searchlight scores as a Nifti1Image and as a masked image

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2673]
ATM the `scores_` of the Searchlight are in the least practical form for an image: the full 3d data as a numpy array. It would be useful to have a `scores_img_` (as the decoders have a `coef_img_` for example)

also possibly a `masked_scores_`, or some convenient way to access the masked data? (note the `coef_` of decoders are masked, not the full 3d data)

to be sure the data twice either `scores_img_` or `scores_` could be a property

finally, the `process_mask` could be stored as well during `fit` so that we know how to mask or unmask scores

(discussed IRL with @PeerHerholz  )

**Comment by bthirion** [comment]
See also #2666

**Comment by PrakharJain1509** [comment]
@jeromedockes I want to work on this issue.

**Comment by jeromedockes** [comment]
> @jeromedockes I want to work on this issue.

that's great, thanks!

**Comment by PrakharJain1509** [comment]
@jeromedockes Can you please assign this to me?

**Comment by Remi-Gau** [comment]
@PrakharJain1509 you can assign an issue to yourself by posting a single message with "take" in it.

**Comment by Remi-Gau** [comment]
take

**Comment by PrakharJain1509** [comment]
> [@PrakharJain1509](https://github.com/PrakharJain1509) you can assign an issue to yourself by posting a single message with "take" in it.

Thanks, Didn't know that

**Comment by Remi-Gau** [comment]
> Thanks, Didn't know that

it is rarely used and specific only to this repo: not a github feature

also it may be slow to happen as this depends on github continuous integration and that ours is currently to busy testing code to actually add a label on an issue...

**Comment by PrakharJain1509** [comment]
@Remi-Gau @jeromedockes I have created a PR for this issue please have a look into it and let me know if any changes are required.

**Comment by PrakharJain1509** [comment]
#4265

**Comment by PrakharJain1509** [comment]
#4652 Here is the PR.
