### ISSUE TITLE
plot_connectome shows nodes below edge_threshold

### ISSUE THREAD

**Issue by JoffJones** [nilearn/nilearn#2675]
Hi there,

I am trying to only show significant nodes above edge_threshold using the plot_connectome function in nilearn 0.7.0. It plots the correct edges but it always displays all of the nodes, rather than just the ones with edges above the threshold as I expected it to. Is there a way to only show the nodes that survive the threshold.

I've tried this with a whole connectome and a masked connectome where all of the edges of no interest are set to 0. In the code below the masked connectome is a 100x100 matrix where only the edges of interest have non-zero values. Coodinates are from find_parcellation_cut_coords and network_colours is a list of 100 Hex colours.

```
plot_connectome(masked_connectome, coordinates, edge_threshold=0.1, node_size =15, 
                node_color=network_colours, display_mode='lzr')
``` 
-->
Many thanks for your help :)
Joff

**Comment by bthirion** [comment]
Can you provide a full example ?

I hope I understand correctly, but I think that (at least, by default) the function should plot all the nodes, even if they are not connected with a significant edge. because the absence of a significant edge to that node is in itself an important piece of information.

**Comment by JoffJones** [comment]
Hi @bthirion,
Thanks for your help, that is correct. I may well have misunderstood the functionality, I was looking at the first example (link below) where nodes are only shown on the left for the Yeo17 atlas so I assumed that this was due to the thresholding. I think that I should be able to achieve the desired result by slicing the coordinates and connectome before plotting them.
https://nilearn.github.io/auto_examples/03_connectivity/plot_atlas_comparison.html#sphx-glr-auto-examples-03-connectivity-plot-atlas-comparison-py

**Comment by JoffJones** [comment]
Fixed with indexing
