### ISSUE TITLE
Atlas To Regions cannot extract the correct number of regions

### ISSUE THREAD

**Issue by DasDominus** [nilearn/nilearn#2685]
The atlas I'm using: https://github.com/alfnie/conn/tree/master/rois
which contains 132 rois
The values are from 1-132 which is the same as what the example requested.

However, when using:

- nilearn.regions.connected_regions
-  nilearn.regions.RegionExtractor

The resulting regions are only a fraction of 132 even if I set the min_region_size to 0

What I'm trying to do is simply get the voxel values of each roi (based on label), 
this should be relatively easy as all the rois are already labeled, only a simple reshape is needed (eg. based on data)

I was wondering why the resulting rois are not matching what was given

Nilearn version:
0.7.0
### Expected behavior

connected_regions should break down regions to 132
whe min_region_size is 0

### Actual behavior

The default region value gives 38 rois
0 region size gives 56 rois.

None of which are correct.

### Steps and code to reproduce bug
download the atlas.nii image
```python
    atlas_img = 'path/to/atlas.nii
    region_extracted_img, index_map = regions.connected_regions(
        atlas_img, min_region_size=0)
    print (region_extracted_img.shape)
```

**Comment by NicolasGensollen** [comment]
Hi @DasDominus 
I suspect this might be due to the `smoothing_fwhm` argument of `connected_regions` which defaults to 6 when `extract_type` is set to `local_regions` (default). Could you try reducing it to see what you obtain?
Also, how long does your script take to run on your machine? I quickly tried to run it as is with the atlas you linked, but it was taking way too long (I stopped after about 10 minutes...).

**Comment by DasDominus** [comment]
hmm thanks for checking @NicolasGensollen !
I suspect it's smoothing_fwhm too...

btw, if I use smoothing_fwhm=6, it takes about a second
but if I change it to smoothing_fwhm=2, it takes much longer... I have been running the script for ~20mins and it's still running...

anyhow, I ended up writing a function to extract regions and create the regions.nii myself XD

**Comment by bthirion** [comment]
Hi,
I don't understand why you need to run region_extraction on an atlas ? Do you need to isolate one of the regions of the atlas ? Do you need to separate connected components ?
Best,

**Comment by DasDominus** [comment]
hi @bthirion I'm trying to isolate one of the regions of the atlas, then extract the voxel values for that region

**Comment by DasDominus** [comment]
but yeah based on what @NicolasGensollen mentioned, this is not a bug.
The doc can be improved to mention suggested smoothing_fwhm value

**Comment by bthirion** [comment]
If your initial atlas definition is by labels (discrete values), you should not use RegionExtractor.
You may want to look at that:
https://neurostars.org/t/nilearn-masking-the-prefrontal-cortex/17990
Best
