### ISSUE TITLE
Add example of two-sample t-test

### ISSUE THREAD

**Issue by alpinho** [nilearn/nilearn#2692]
Examples [9.6.3](https://nilearn.github.io/auto_examples/05_glm_second_level/plot_second_level_paired_sample_test.html#sphx-glr-auto-examples-05-glm-second-level-plot-second-level-paired-sample-test-py) and [9.6.4](https://nilearn.github.io/auto_examples/05_glm_second_level/plot_second_level_two_sample_test.html#sphx-glr-auto-examples-05-glm-second-level-plot-second-level-two-sample-test-py) are the same with different titles, I believe.

It seems that both of them refer to the 'paired-sample t-test'. In this case, example 9.6.3 is correct but 9.6.4 has to be fixed.

**Comment by tsalo** [comment]
It looks like this was handled in #2617, but there hasn't been a release since Nov 25 (when it was merged), so the docs don't reflect the fix.

**Comment by alpinho** [comment]
Thanks for the feedback. I think anyway that there should be a two-sample t-test example, though. PR #2617 only deletes the duplicate.

**Comment by tsalo** [comment]
Good point! I think this changes the nature of the issue though. It's now more of a documentation request (a new example) than a bug report. Would you mind if I updated the tags and title to reflect that?

**Comment by alpinho** [comment]
Of course! Thanks!

**Comment by psadil** [comment]
I can work on adding an 'unpaired', two-sample t-test example. 

How are the topics ordered? As in, what determines that, e.g., [plot_second_level_design_matrix.py](https://github.com/nilearn/nilearn/blob/034a0bc2df7e7242fafaf788c3eae2b5a94fa17f/examples/05_glm_second_level/plot_second_level_design_matrix.py) is 9.6.1 and [plot_proportion_activated_voxels.py](https://github.com/nilearn/nilearn/blob/034a0bc2df7e7242fafaf788c3eae2b5a94fa17f/examples/05_glm_second_level/plot_second_level_one_sample_test.py) is 9.6.2? The order doesn't seem to be alphabetical by filename.

**Comment by psadil** [comment]
The paired and unpaired examples could end up being quite similar. What about adding the unpaired example to what is currently 9.6.3, [plot_second_level_paired_sample_test.py](https://github.com/nilearn/nilearn/blob/034a0bc2df7e7242fafaf788c3eae2b5a94fa17f/examples/05_glm_second_level/plot_second_level_paired_sample_test.py)? That has an added advantage of getting to show the stat maps w/ and w/o subject intercepts side by side.

**Comment by bthirion** [comment]
Yes, makes sense.
