### ISSUE TITLE
Ensure finite data (replace NaNs with zeros) in NiftiLabelsMasker

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#2711]
`NiftiMapsMasker` handles NaNs implicitly, while `NiftiLabelsMasker` does not. I think it just comes down to the following line:

https://github.com/nilearn/nilearn/blob/02e915accc1dd29ee8af0e92004eabb4f0393958/nilearn/regions/signal_extraction.py#L118

### Benefits to the change

I think the main benefit would be ensuring consistent behavior across Maskers, but it would also be helpful to retain signal from regions with some NaNs in the data.

### Pseudocode for the new behavior, if applicable

```python
import nibabel as nib
import numpy as np
from nilearn import datasets, input_data

img = datasets.load_mni152_brain_mask()
data = img.get_fdata()
# add NaN for test
data[52, 53, 71] = np.nan
# make 4d
data = data[..., None]
img_nan = nib.Nifti1Image(data, img.affine, img.header)

labels_atlas = datasets.fetch_atlas_aal()["maps"]

# Apply masker and check voxel of interest
labels_masker = input_data.NiftiLabelsMasker(labels_atlas)
labels_values = labels_masker.fit_transform(img_nan)
print(labels_values[0, :5])
```

> [0.94469654 0.90653653 0.95470964 0.96079882 0.99480789]

Instead of 

> [       nan 0.90653653 0.95470964 0.96079882 0.99480789]

**Comment by bthirion** [comment]
So, you impute Nans by zeros ? 

I'm OK with the proposal. Of course, their would need to be a warning.

**Comment by tsalo** [comment]
>So, you impute Nans by zeros ?

Yes, it looks like that's what `_safe_get_data` does, although until I looked at the docstring I would have assumed that NaNs would be ignored instead of replaced, like [`numpy.nanmean`](https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html).

> Of course, their would need to be a warning.

I agree that a warning would be good. What about putting it in `_safe_get_data` though, since this impacts multiple maskers?

**Comment by bthirion** [comment]
Yes, that sounds right.

**Comment by tsalo** [comment]
@bthirion it looks like there's a test that specifically expects NaNs to remain in `test_signal_extraction_with_maps_and_labels`. This check was added in 744a38a73959a23144bbd17eab7b080c16469db1, although I'm having trouble tracking down the rationale for it since it doesn't look like it was linked to an issue or PR. Should we consider this behavior expected still?

Here's the current check:
https://github.com/nilearn/nilearn/blob/02e915accc1dd29ee8af0e92004eabb4f0393958/nilearn/regions/tests/test_signal_extraction.py#L339-L345
