### ISSUE TITLE
nilearn.signal PSC standardise option

### ISSUE THREAD

**Issue by htwangtw** [nilearn/nilearn#2713]
While working on https://github.com/SIMEXP/load_confounds/pull/96, the new test data led to a test for denoising using PSC strategy failed https://github.com/SIMEXP/load_confounds/issues/105. Our test data contain confounds with negative mean. The current implementation of `standardise="psc"` in `nilearn.signal` sets confound variables with a mean of 0 or less.
https://github.com/nilearn/nilearn/blob/02e915accc1dd29ee8af0e92004eabb4f0393958/nilearn/signal.py#L77-L81
@pbellec and I believe the change after the warning only need to apply to variable with mean of 0.

### Benefits to the change
There's no reason why (that I know of) you cannot calculate percent signal change with a mean signal below zero.
PSC standardise option is essentially a mean centred metric with scaling since we can rewrite the current code from:
https://github.com/nilearn/nilearn/blob/02e915accc1dd29ee8af0e92004eabb4f0393958/nilearn/signal.py#L74-L75
to
```python
signals = ( (signals - mean_signal) / mean_signal ) * 100
```
The divisor should be changed to the absolute value of `mean_signal` to account for `mean_signal` < 0.
And the `invalid_ix` should check for value of zero or close to zero.

### Pseudocode for the new behavior, if applicable
Change this part
https://github.com/nilearn/nilearn/blob/02e915accc1dd29ee8af0e92004eabb4f0393958/nilearn/signal.py#L73-L75
to this
```python
invalid_ix = np.absolute(mean_signal) < np.finfo(np.float).eps
signals = (signals - mean_signal) / np.absolute(mean_signal)
signals *= 100
```
and update the user warning message in L78.

**Comment by NicolasGensollen** [comment]
Hi @htwangtw 
Thanks for pointing this out. I don't see any reason either why we couldn't compute psc with negative mean. 
I think the fix you propose is good. 
Do you want to open a PR?

**Comment by htwangtw** [comment]
Sure I am happy to!
