### ISSUE TITLE
plot_roi should support 4D images

### ISSUE THREAD

**Issue by GMerakis** [nilearn/nilearn#2721]
as mentioned.
I have a list of atlas images with distinct values, but to plot them, I have to manually combine all the images into a single 3D image and plot.

This should be a simple integrated step within the function

**Comment by bthirion** [comment]
Thx for raising the point. IIUC `plot_prob_atlas` should do the trick, no ?

**Comment by NicolasGensollen** [comment]
I agree this could be easily added if there is a use case for it. 
Although this is not super convenient, note that you could also use `plot_roi` and add overlays for each atlas image. Something like this maybe:

```python
import numpy as np
from nilearn import datasets
from nilearn.image import get_data
from nilearn.image import new_img_like
from nilearn.plotting import plot_roi, plot_prob_atlas

# Load some atlas
atlas = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm')

# Artificially split it in 2
atlas_data = get_data(atlas.maps)
atlas_data_chunks = [np.copy(atlas_data) for _ in range(2)]
atlas_data_chunks[0][atlas_data_chunks[0] >= 15] = 0
atlas_data_chunks[1][atlas_data_chunks[1] < 15] = 0
atlas_chunks = [new_img_like(atlas.maps, chunk) for chunk in atlas_data_chunks]

# Add overlays to plot_roi
display = plot_roi(atlas_chunks[0], 
                   cut_coords=[0, -42, 11])
display.add_overlay(atlas_chunks[1])
```
![overlays](https://user-images.githubusercontent.com/2639645/110155210-996d6c00-7de5-11eb-9354-1f1f19be4178.png)

**Comment by jeromedockes** [comment]
- if the atlas images overlap, as @bthirion said `plot_prob_atlas` should be used
- if they don't overlap and have distinct values as in the issue description they can be combined simply with `atlas_3d = image.math_img("img.sum(axis=0)", img=atlas_4d)`
- if they are binary masks it is still quite easy to combine them:
  ```
  atlas_3d = image.math_img(
    "np.sum(img.T * np.arange(1, img.shape[0] + 1), axis=-1).T", img=atlas_4d
  )
  ```

and then `plot_roi` can be used.
So as I don't think this is an extremely frequent use case, I don't think it is worth adding a different format for the input of `plot_roi`, which makes the function's logic, the validation, and the interface and documentation more complex

**Comment by bthirion** [comment]
Will thus close that one if nobody objects.
