### ISSUE TITLE
plotting.view_markers marker_labels

### ISSUE THREAD

**Issue by greydongilmore** [nilearn/nilearn#2733]
I have been using `plotting.view_markers` for some time and really like the ability to define marker_color. I am wondering if it's possible to add marker_label as well?

### Benefits to the change
I think many users would find this helpful, especially when plotting many points at one time. In our use case, we are displaying depth electrode contacts for epilepsy patients and having each contact point labelled would be a benefit to our clinicians.

```python
import matplotlib.pyplot as plt
from nilearn import plotting

labels = #string label for each electrode contact
groups = #of implanted electrodes
n_members = #of contacts for each electrode

cmap = plt.get_cmap('rainbow')
colors=np.repeat(cmap(np.linspace(0, 1, len(groups))), n_members, axis=0)

html_view = plotting.view_markers(coordinates, marker_size=5.0, marker_color=colors, marker_labels=labels)
```

**Comment by bthirion** [comment]
Thx ! Sounds like a good idea. Are you interested in working on it ?
Best,
Bertrand

**Comment by greydongilmore** [comment]
yes, can do. Any advice on where I should start?

**Comment by NicolasGensollen** [comment]
Hi @greydongilmore 

Indeed, this would be nice to have! :+1: 
I had a quick look, and it seems we will need to do the following things:

- Update function `view_markers` to support a `marker_labels` argument (basic checks, and then add it to the `connectome_info` dictionary):

https://github.com/nilearn/nilearn/blob/dc9c21a7bec637f0aaad650372bbf4e59b294dec/nilearn/plotting/html_connectome.py#L180-L181

- Update `nilearn/plotting/data/html/connectome_plot_template.html`: use the passed labels to add a `text` field to the Plotly figure (see examples in doc [here](https://plotly.com/javascript/line-and-scatter/)).

https://github.com/nilearn/nilearn/blob/dc9c21a7bec637f0aaad650372bbf4e59b294dec/nilearn/plotting/data/html/connectome_plot_template.html#L129-L140

Does this make sense?

**Comment by greydongilmore** [comment]
yes, makes sense to me! I will get working on it :+1:
