### ISSUE TITLE
get_iframe() doesn't apply view_img()'s configuration

### ISSUE THREAD

**Issue by ZviBaratz** [nilearn/nilearn#2736]
Hi all,

I ran into an issue trying to embed the returned `view_img()`'s `StatMapView`'s into an HTML page using the `get_iframe()` method. 
Calling `view_img()` with the `bg_img=False` and `cmap=cm.bone` keyword arguments seems to work fine when displayed in the browser, and even more curiously, when called within a Jupyter notebook, However, when the same scan is embedded within an external HTML page using the `get_iframe()` method's output:

![image](https://user-images.githubusercontent.com/22370149/111766236-f79e5280-88ad-11eb-93dc-eca3250060fc.png)

Whereas within a notebook (the desired result):
![image](https://user-images.githubusercontent.com/22370149/111766539-549a0880-88ae-11eb-9414-ebbfb1c2bae8.png)

As far as I understand the notebook simply calls the `get_iframe()` method (by triggering the `_repr_html()` method) so it's odd the results are different. Anyone has any ideas?

Thank you for your work as always,
Zvi

> _I am using nilearn 0.7.1 on a LInux (Kubuntu) machine._

**Comment by NicolasGensollen** [comment]
Thanks for opening this @ZviBaratz :+1: 
Do you have an example we can run to reproduce the bug?

**Comment by ZviBaratz** [comment]
Huh. I tried creating a minimal HTML page and injecting the iframe and everything worked as expected :man_shrugging:  I'm sorry, I probably should have done this beforehand. 
I am embedding the plot in a Django template, so it would seem the problem is somehow caused by Django's templating system. I didn't really consider this because other than the configuration passed to `view_img()`'s keyword arguments, the plot is rendered perfectly. I realize this is out of scope, so I am closing this issue. Thank you anyway, if anyone still has some guess as to what might be causing this it would be appreciated :pray:
