### ISSUE TITLE
Nilearn - Nibabel dev-days 2021

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2739]
## Coding Sprint :calendar: 

The next [Nilearn](http://nilearn.github.io/) - [Nibabel](https://nipy.org/nibabel/) coding sprint will take place 

**May 5th 1pm UTC / 9am EDT** to **May 7th 7pm UTC / 3pm EDT** 

using the online platform *Discord* :tada:

Schedule and all information on how to register and get set up are available on the [event website](https://nilearn.github.io/dev-days-2021/).

## New contributors :new:

One of the main objective of this sprint is to onboard new contributors to both tools. We will provide a crash-course on how to contribute (May 5th 2pm UTC / 10am EDT), and make sure [core devs](http://nilearn.github.io/authors.html) and experienced members are available to help and review PRs during the sprint period.

Please make sure to have a look at issues with the label "good first issue" [here](https://github.com/nilearn/nilearn/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+first+issue%22).

## Main Topics :100: 

Here is a list of the general topics that we wish to tackle during this sprint with links to relevant issues, discussions, and Pull Requests:

- Website design (see #813)
- Website landing page (TBA)
- BIDS integration (see #2425 #2683 #2715)
- Surface integration (see #2171 #2423 #2424 #2681)
- HTML reports (see #2689 #2707)
- Barriers to adoption and community building (TBA)

*Feel free to make suggestions on other topics that you think would make sense here.*

## Project board :pushpin: 

The dedicated project board is available [here](https://github.com/nilearn/nilearn/projects/6).

**Comment by NicolasGensollen** [comment]
Today is the first day of the sprint! :tada: 

**Discord**

Discussions and sessions will happen on discord [here](https://discord.gg/bMBhb7w).

**Schedule**

- 13h UTC: Kick-off and what’s new in Nilearn and Nibabel
- 14h UTC: Interactive crash-course in contributing to Nilearn/Nibabel
- 16h UTC: Community feedback on Nilearn website, documentation

**Get started**

- Have a look at the [event website](https://nilearn.github.io/dev-days-2021/) which centralizes all the sprint related information
- [Setup your environment](https://nilearn.github.io/dev-days-2021/getting-started.html#install-nilearn-and-nibabel) if you haven't done it already
- Browse the board of issues that we selected for the sprint ([here](https://github.com/nilearn/nilearn/projects/6) for Nilearn, [here](https://github.com/nipy/nibabel/projects/1) for Nibabel). 
- If you have a specific idea and would like to work on it, please start by opening an issue describing it. You can also start by chating about your idea on discord!
- If this is your first time contributing to an open source project, you can target issues with the label "good first issue" and make sure you attend the contributing crash course at 14h UTC. 
- Some of the good first issues look like "Use bibtex in nilearn/xxxx" and do not require to write any Python code (only add bibtex refs). They should be a good start for newcomers willing to open their first Pull Request.
- If you want to work on an issue, please post a small message saying that you are interested in working on it and we will assign it to you. This will prevent multiple persons to work on the same issue.

**Comment by NicolasGensollen** [comment]
Intro session is starting now on discord! :tada:

**Comment by NicolasGensollen** [comment]
For those of you who couldn't make it yesterday for the first day of the sprint, here is a small recap of what happened:

- We had a quick overview of some of the new things in both Nilearn and Nibabel (you can get the slides/notebooks [here](https://github.com/nilearn/dev-days-2021/tree/main/Notebooks)).
- @GaelVaroquaux gave an awesome crash course for contributing to open source projects :clap: 
- @alexisthual did a great live coding session showing how to submit a PR step by step :1st_place_medal: 
- We had already 9 new PRs in Nilearn and Nibabel, among which 4 already got merged (thanks to @Craskermasker @alexisthual @ChristianGerloff @tvanasse @psadil @jeromedockes  and @RaphaelMeudec for opening these and thanks to the reviewers! :100: )  

For the second day of the sprint we have planned the following sessions:

**Schedule**

- 13h UTC: Brainstorming on BIDS integration
- 14h UTC: Discussions on supporting more surface modelling in Nilearn and Nibabel
- 15h UTC: Integration of `load_confounds` into Nilearn (see #2777)

As for yesterday, all sessions will take place on Discord (link in previous message).

Finally, don't hesitate to create your own sessions in one of the Discord rooms and ping people from the team if you need!

**Comment by NicolasGensollen** [comment]
This is the third and final day of the sprint. :tada: 

A lot happened yesterday! :rocket: 

We had productive discussions on 

- the integration of BIDS into Nilearn (See #2425 #2683 and #2715)
- the representation of surfaces in Nilearn and Nibabel (See #2171 #2423 #2424 #2681)
- the integration of [load_confounds](https://github.com/SIMEXP/load_confounds) within Nilearn (see #2777)

Thanks to the speakers and to everybody for the great discussions! :100: 

The day was also very active in terms of PRs and issue opening/closing! :fire: 
If my math is right, we had 14 new PRs among which 5 already got merged as well as additional work on already opened PRs. 

Thanks to @alexenge @Craskermasker @achamma723 @alexisthual @RaphaelMeudec @JLefortBesnard @htwangtw  @OliverWarrington @udion @jeromedockes @psadil @ChristianGerloff @tvanasse @alpinho  for working on these and thanks to all the reviewers! :1st_place_medal: 

For this final day, we will have the following sessions:

- 13h UTC: Community feedback on project documentation and generated reports
- 14h UTC: Barriers to adoption and community building
- 17h UTC: Closing session

All sessions will take place on Discord as for the last two days.

Finally, please don't hesitate to reach out and ask any questions either on discord or on github directly! :raising_hand:

**Comment by jeromedockes** [comment]
@NicolasGensollen  should we close this issue now that the sprint is over?

**Comment by NicolasGensollen** [comment]
@jeromedockes Absolutely, thanks !
