### ISSUE TITLE
Split CircleCI cache into smaller files

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2744]
in circleci nilearn chaches the whole `nilearn_data` folder in one huge cache.
Quite frequently the cache is missed.
When I discussed it with circleci support they could not find exactly what was the problem but they suggested that the huge cache size might be an issue.
We could try splitting the cache into smaller chunks (eg one for each dataset).
As @emdupre pointed out it is what MNE seems to do: https://github.com/mne-tools/mne-python/blob/02bb98b35a34d49d22037e3d494ba1e4f83994de/.circleci/config.yml#L255

**Comment by NicolasGensollen** [comment]
Thanks for opening this @jeromedockes !
I'd be happy to work on this once #2734 is merged.

**Comment by jeromedockes** [comment]
great! are you waiting for another review on #2734 ? If it helps I can look at it today

**Comment by NicolasGensollen** [comment]
>are you waiting for another review on #2734 ?  If it helps I can look at it today

Absolutely! It'd be great to have another review on this PR!
