### ISSUE TITLE
Improve testing of `_utils.data_gen`

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2750]
It looks like some functions of this module are either not tested correctly, or not tested at all.
For example: `generate_labeled_regions_large`, `write_fake_bold_img`, `generate_signals_from_precisions`....
I think it would help to have all these functions unit-tested in the same file (`nilearn/tests/test_testing.py` for example or some other file?).

**Comment by jeromedockes** [comment]
> It looks like some functions of this module are either not tested correctly, or not tested at all.
> For example: `generate_labeled_regions_large`, `write_fake_bold_img`, `generate_signals_from_precisions`....
> I think it would help to have all these functions unit-tested in the same file (`nilearn/tests/test_testing.py` for example or some other file?).

good idea! but also note if any of these functions is not used anywhere
in the tests or library it should just be removed (`_utils` is a private
subpackage)

**Comment by Remi-Gau** [comment]
public functions not explicitly tested:

- generate_random_img
- basic_paradigm
- generate_group_sparse_gaussian_graphs
- write_fake_bold_img
- write_fake_fmri_data_and_design
- generate_fake_fmri_data_and_design
- generate_timeseries
- generate_mni_space_img
