### ISSUE TITLE
plot_markers scaling issue

### ISSUE THREAD

**Issue by AReineberg** [nilearn/nilearn#2754]
Hi. I am trying to visualize the Gordon 2016 parcellation with plot_markers. I can get view_markers to produce an accurate image:

![newplot](https://user-images.githubusercontent.com/5094574/113948510-457dea80-97ca-11eb-82f1-10e71d8ce5ce.png)

but plot_markers is not working even though I think I've produced the voxel coordinates correctly from the provided MNI coordinates. It looks like the parcels are organized property but scaling is off and the brain is translated to the side:

![downloadx](https://user-images.githubusercontent.com/5094574/113949499-a9a1ae00-97cc-11eb-9b11-07b5eb1f3b26.png)

I double checked the MNI-to-voxel translation in fsleyes for a couple parcels and it looks good there. At this point, I am not sure if this is on my end or not.

Code:

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from nilearn import plotting
import nibabel as nib

parcellation = pd.read_excel('Parcels.xls') # from https://sites.wustl.edu/petersenschlaggarlab/parcels-19cwpgu/
parcellation[['x', 'y', 'z']] = pd.DataFrame([ x.split() for x in parcellation['Centroid (MNI)'].tolist() ])

niimg = nib.load('Parcels_MNI_222.nii') # from above link

# Not working:
coords = [image.coord_transform(float(parcellation['x'][i]), float(parcellation['y'][i]), float(parcellation['z'][i]), np.linalg.inv(niimg.affine)) for i in range(333)]
fig = plt.figure(figsize=(10,6))
plotting.plot_markers(
    node_values=mean, # personal data I want overlayed, can be replaced with random values shaped (333,1) for testing
    node_coords=np.array(coords),
    node_cmap=plt.cm.bwr,
    figure=fig
)

# Working:
coords = np.vstack((parcellation['x'], parcellation['y'], parcellation['z'])).T
plotting.view_markers(marker_coords=np.array(coords))
```

**Comment by NicolasGensollen** [comment]
Hi @AReineberg 

Unless I am missing something, the coordinates from the dataframe are already in the right space, right?
Here is your script with a few tweaks to make it work on my end:

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from nilearn import plotting, image
import nibabel as nib

parcellation = pd.read_excel('/home/nicolas/Downloads/Parcels-19cwpgu/Parcels/Parcels.xlsx',
                             engine='openpyxl') # from https://sites.wustl.edu/petersenschlaggarlab/parcels-19cwpgu/
parcellation[['x', 'y', 'z']] = pd.DataFrame([ x.split() for x in parcellation['Centroid (MNI)'].tolist() ])
niimg = nib.load('/home/nicolas/Downloads/Parcels-19cwpgu/Parcels/Parcels_MNI_222.nii') # from above link
for x in ['x','y','z']:
    parcellation[x] = parcellation[x].apply(lambda x:float(x))
coords = np.vstack((parcellation['x'], parcellation['y'], parcellation['z'])).T

plotting.view_markers(marker_coords=np.array(coords))
```

![1](https://user-images.githubusercontent.com/2639645/113994549-c59d6200-9855-11eb-9710-fd0c62d20d35.png)


```python
vals = np.random.random((333,1)) # random node values

fig = plt.figure(figsize=(10,6))
plotting.plot_markers(
    node_values=vals,
    node_coords=np.array(coords),
    node_cmap=plt.cm.bwr,
    figure=fig
)
```

![2](https://user-images.githubusercontent.com/2639645/113994589-cd5d0680-9855-11eb-8df3-e57250648779.png)

**Comment by AReineberg** [comment]
I tried yesterday with MNI coordinates and got the following image:

![downloadx2](https://user-images.githubusercontent.com/5094574/114053734-743ca500-984c-11eb-8807-7d6d1700dc20.png)

But your code did work for me. It looks like the culprit is the np.array call in my code. I guess the coordinates were already in the right shape, so without the np.array call in my plot_marker code, it works:

![downloadx3](https://user-images.githubusercontent.com/5094574/114054651-47d55880-984d-11eb-957d-1fe32898f8dc.png)

So thanks for the help! I am still confused as to why the documentation asks for matrix coordinates, but I'll take this victory.

**Comment by bthirion** [comment]
Great ! 
Is it OK to close the issue ?
Best,
