### ISSUE TITLE
Some public functions from `nilearn.regions` are not exposed

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2757]
Some public functions from the `regions` module are not exposed. For example:

https://github.com/nilearn/nilearn/blob/00d3873fb6cf23d09f8eba6d0d20e905f26d22dd/nilearn/regions/rena_clustering.py#L148-L152

https://github.com/nilearn/nilearn/blob/00d3873fb6cf23d09f8eba6d0d20e905f26d22dd/nilearn/regions/rena_clustering.py#L349-L355

Or

https://github.com/nilearn/nilearn/blob/00d3873fb6cf23d09f8eba6d0d20e905f26d22dd/nilearn/regions/rena_clustering.py#L286-L291

We should either make them private or add them here:

https://github.com/nilearn/nilearn/blob/00d3873fb6cf23d09f8eba6d0d20e905f26d22dd/nilearn/regions/__init__.py#L15-L20

**Comment by bthirion** [comment]
I think that none of these functions is meant to be public. We should prepend a '_'
