### ISSUE TITLE
Multiple definitions of `basic_paradigm`

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2763]
The function `basic_paradigm` is defined in `nilearn._utils.data_gen.py`:

https://github.com/nilearn/nilearn/blob/00d3873fb6cf23d09f8eba6d0d20e905f26d22dd/nilearn/_utils/data_gen.py#L505-L510

But, it is re-defined in other files (with a duration) for testing:

- `nilearn/glm/tests/test_first_level.py`:
https://github.com/nilearn/nilearn/blob/a36c0442fc8eebe401b310dd9799c0f071080e90/nilearn/glm/tests/test_first_level.py#L353-L360

- `nilearn/glm/tests/test_paradigm.py`:
https://github.com/nilearn/nilearn/blob/a36c0442fc8eebe401b310dd9799c0f071080e90/nilearn/glm/tests/test_paradigm.py#L16-L23

- `nilearn/glm/tests/test_dmtx.py`:
https://github.com/nilearn/nilearn/blob/a36c0442fc8eebe401b310dd9799c0f071080e90/nilearn/glm/tests/test_dmtx.py#L48-L55

It would be better to remove those and import `basic_paradigm` from `_utils.data_gen.py`.

**Comment by bthirion** [comment]
Good first issue indeed ! thx for spotting it.

**Comment by jithenshriyan** [comment]
I would love to take on this issue as my first open-source contribution. 

Let me know if it is still available, and I'll get to work on it!
