### ISSUE TITLE
Very similar GLM examples

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2771]
It looks like the following examples are very similar (although they are not exactly the same either). 
It might be worth factoring them, WDYT?

- [Example of explicit fixed effects fMRI model fitting](http://nilearn.github.io/auto_examples/04_glm_first_level/plot_fixed_effects.html#sphx-glr-auto-examples-04-glm-first-level-plot-fixed-effects-py)
- [Simple example of two-session fMRI model fitting](http://nilearn.github.io/auto_examples/04_glm_first_level/plot_fiac_analysis.html#sphx-glr-auto-examples-04-glm-first-level-plot-fiac-analysis-py)

**Comment by bthirion** [comment]
+1 for merging them. I think that 2 features are important:
1. The ability to perform fixed-effects inference once you have several effects and variance (aka summary statistics) images
2. the fact that  when you directly pass several fmri runs to a glm model, it computes a fixed effect on the data (no need to pass explicitly the summary statistics).

**Comment by ymzayek** [comment]
Updated links:
- https://nilearn.github.io/stable/auto_examples/04_glm_first_level/plot_fixed_effects.html#sphx-glr-auto-examples-04-glm-first-level-plot-fixed-effects-py
- https://nilearn.github.io/stable/auto_examples/04_glm_first_level/plot_fiac_analysis.html#sphx-glr-auto-examples-04-glm-first-level-plot-fiac-analysis-py
