### ISSUE TITLE
`FirstLevelModel._get_voxelwise_model_attribute` only returns first design matrix's attribute

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#2772]
The FirstLevelModel attributes which use `_get_voxelwise_model_attribute()` only return the img for the first design matrix, rather than all of the design matrices' associated imgs.

Nilearn version: ~0.7.1 (`master` at c4839dd)

### Expected behavior

Accessing one of the voxelwise attributes which rely on `FirstLevelModel._get_voxelwise_model_attribute()`, such as `FirstLevelModel.residuals`, `FirstLevelModel.predicted`, or `FirstLevelModel.r_square`, should return a list of Nifti1Image objects with the same length as `FirstLevelModel.design_matrices_`.

### Actual behavior

The attributes are lists with only one item.

### The associated code

https://github.com/nilearn/nilearn/blob/c4839ddfe68ddf15775def1fc0ce9ea23544a527/nilearn/glm/first_level/first_level.py#L668-L686

### The solution

Unindenting line 686 should fix it, I think. There should also be at least one test to make sure that the length of the attribute list is the same as the length of `model.design_matrices`.

**Comment by bthirion** [comment]
Thx, good catch !

**Comment by RaphaelMeudec** [comment]
Currently working on this.
