### ISSUE TITLE
Add CI documentation to contributing guidelines

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2774]
If we keep the CI changes introduced in #2734 and #2752, it could be a good idea to add some explanations in the docs for contributors. 

For example, explaining that CircleCI will only build modified examples (except for master) unless you add the tag `[circle full]` to your commit message, or that it will use the data cache if available unless you add the tag `[force download]` to your commit message, or that you can skip the CI...

It could be part of #2755 or the object of a separate PR.

**Comment by thomasbazeille** [comment]
Sounds good ! #2755 introduces a new doc/maintenance.rst where this would be a great addition I guess. Probably have to wait for it to be merge though.

**Comment by NicolasGensollen** [comment]
take

**Comment by ymzayek** [comment]
I wouldn't put it in the contributing docs. At most we could mention it to explain it as part of the review process. And I would also say not to add it itself to the maintenance doc but add a section explaining the CI as part of maintenance process and just link to the README to clarify where to find more information about each workflow.

**Comment by Remi-Gau** [comment]
AFAICT the extra bits regarding doc building are alreaday in the doc:
https://nilearn.github.io/stable/development.html#building-documentation

so closing for now
