### ISSUE TITLE
Use plot_event in a example

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2775]
The function `plot_event` has currently no example linked to its [doc](https://nilearn.github.io/modules/generated/nilearn.plotting.plot_event.html#nilearn.plotting.plot_event). 
It wouldn't be too costly to use it in one example somewhere.

**Comment by bthirion** [comment]
+1

**Comment by Craskermasker** [comment]
keen to try this issue

**Comment by bthirion** [comment]
Maybe https://nilearn.github.io/auto_examples/04_glm_first_level/write_events_file.html#sphx-glr-auto-examples-04-glm-first-level-write-events-file-py ?
