### ISSUE TITLE
Add link to source code in API pages

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#2776]
I think it would be helpful to users who are interested in nilearn's source code to link back to GitHub from each class or function's documentation. `scikit-learn`'s [`github_link.py`](https://github.com/scikit-learn/scikit-learn/blob/4023a0f94bde429456f45b983c84c5f35475480f/doc/sphinxext/github_link.py) could be adapted and used.

### Affected pages
All reference pages (`http://nilearn.github.io/modules/generated/*`)

**Comment by Craskermasker** [comment]
Interested in this one

**Comment by Craskermasker** [comment]
I have a WIP PR for this - is it ok to re-use the `github_link.py` from scikit-learn from a software licensing point of view? Both are BSD-3-Clause as far as I can tell.

**Comment by GaelVaroquaux** [comment]
> is it ok to re-use the github_link.py from scikit-learn from a software
> licensing point of view? Both are BSD-3-Clause as far as I can tell.

Yes. Thanks for asking!
