### ISSUE TITLE
Axes Cutoff in Example 9.2.15.9 (plotting.plot_img_on_surf)

### ISSUE THREAD

**Issue by tvanasse** [nilearn/nilearn#2778]
[`Example 9.2.15.9`](https://nilearn.github.io/auto_examples/01_plotting/plot_3d_map_to_surface_projection.html#plot-multiple-views-of-the-3d-volume-on-a-surface) features a quick plot showing multiple views of a volumetric stat map on an average surface. 

![sphx_glr_plot_3d_map_to_surface_projection_006](https://user-images.githubusercontent.com/8116564/116880214-5c580700-abe7-11eb-8af0-3c229cb1ffff.png)

However, the brain is cutoff on both axes (picture shown) both in the online example and when I use it on nilearn 0.7.1 within a jupyter notebook using the following code

```python
fig, ax = plotting.plot_img_on_surf(new_image,
                          views=['lateral','medial'],
                          hemispheres=['left', 'right'],
                          inflate=True,
                          colorbar=True
                         )
```
Perhaps this is easily fixed post-hoc by adjusting matplotlib parameters, but it is not obvious to me.

**Comment by NicolasGensollen** [comment]
Thanks for opening this @tvanasse !
Indeed, I can reproduce with:

```python
from nilearn.datasets import fetch_neurovault_motor_task
from nilearn.plotting import plot_img_on_surf

motor_images = fetch_neurovault_motor_task()
stat_img = motor_images.images[0]
plot_img_on_surf(stat_img,
                 views=['lateral'],
                 hemispheres=['left'],
                 colorbar=True)
```
![test](https://user-images.githubusercontent.com/2639645/116889329-b929e080-ac2c-11eb-89a2-085636087f6f.png)
