### ISSUE TITLE
Use bibtex in nilearn/connectome

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2780]
Convert references in 

- `nilearn/connectome/connectivity_matrices.py`
- `nilearn/connectome/group_sparse_cov.py`

to use footcite / footbibliography.
See #2759

**Comment by alexenge** [comment]
Hey, I've just took care of one of the bibtex issues (#2786) and wouldn't mind doing a few more of the remaining ones (probably all of them, i.e. #2780, #2782, #2783 #2785, #2787, and #2788).

Is that okay or would you like to leave them open for future newbies?

Also, would you prefer having separate PRs for each of them or rather one large one? Thanks!

**Comment by NicolasGensollen** [comment]
Hi @alexenge 
These issues are more meant to help newcomers do a first pull request without having to write code. This way you can just focus on the process of forking, cloning, pushing, submitting and so on. 
So, I think it'd be great if you could leave some of these issues to other newcomers. That being said, if you want to do another one, feel free to do so! 
Also, it's always better to do small PRs than large ones. It makes them much easier to review.

**Comment by NicolasGensollen** [comment]
Btw, let me know if you want to be assigned to this one!

**Comment by alexenge** [comment]
Thanks, I've thought so and this makes total sense.

It would be really cool if you could assign me this one so I can get just a bit more practice and then I would try to move on to something else.
