### ISSUE TITLE
Use bibtex in nilearn/signal.py

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2788]
Convert references in `nilearn/signal.py` to use footcite / footbibliography.
See #2759

**Comment by JLefortBesnard** [comment]
Hello, 
I would like to be assigned on this issue to train more with PR and git commands.
Thank you :)

**Comment by JLefortBesnard** [comment]
Thank you @NicolasGensollen 
Actually, I don't see any reference to add in nilearn/signal.py, or maybe I should create a reference section in the clean() function for Lindquist et al. (2018)?

**Comment by bthirion** [comment]
In the dostrings there are refs to Behzadi et al.  2007 and Lindquist et al. 2018.
