### ISSUE TITLE
Use bibtex in nilearn/datasets

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2789]
Convert references in:

- `nilearn/datasets/atlas.py`
- `nilearn/datasets/func.py`
- `nilearn/datasets/neurovault.py`
- `nilearn/datasets/struct.py`

to use footcite / footbibliography.
See #2759

**Comment by tsalo** [comment]
I don't want to introduce sprawl, but it would also be very helpful to move the in-line references out of the first lines in the docstrings of the following functions:

- fetch_atlas_destrieux_2009
- fetch_coords_power_2011
- fetch_atlas_smith_2009
- fetch_atlas_pauli_2017
- fetch_adhd
- fetch_haxby
- fetch_miyawaki2008
- fetch_surf_nki_enhanced
- fetch_atlas_surf_destrieux

As can be seen in the screen shot below, the first line of the docstring is used as the summary in the Reference page, and references end up looking odd in those rendered summaries. Simply moving the reference to the expanded description or Notes section of the docstring resolves this nicely.

![image](https://user-images.githubusercontent.com/8228902/117199718-87de1b80-adb8-11eb-91a5-8ce5f4a156cb.png)

**Comment by NicolasGensollen** [comment]
Good point, thanks @tsalo !

**Comment by JLefortBesnard** [comment]
Hi, I would like to be assigned on this issue, thanks :)
