### ISSUE TITLE
More diverse avg_method for plot_surf to handle sparse matrices

### ISSUE THREAD

**Issue by alexisthual** [nilearn/nilearn#2790]
Currently, the `avg_method` parameter in `plotting.plot_surf` only takes `mean` or `median` as arguments.
Having the possibility `min`, `max` or other functions would be useful to me, in the sense that sometimes I have some sparse surface matrices, therefore using `mean` or `median` kind of kills my plots :smile: 

### Benefits to the change

It would allow for a better representation of sparse matrices on the surface.

### Pseudocode for the new behavior, if applicable

```python
import matplotlib.pyplot as plt
from nilearn import datasets, plotting
import numpy as np

fsaverage = datasets.fetch_surf_fsaverage()
n_voxels = 10242

surface = np.zeros(n_voxels)
n = 100
surface[:n] = np.ones(n)

plotting.plot_surf(
    fsaverage.pial_left,
    surface,
    avg_method="min"
)
plt.show()
```

**Comment by NicolasGensollen** [comment]
Here is the part of the code implementing these:

https://github.com/nilearn/nilearn/blob/b08d1fea1857f988b0b916e6176235b1912bcaf5/nilearn/plotting/surf_plotting.py#L268-L273

I think having the possibility of specifying `min` or `max` would be a good addition indeed :+1:
