### ISSUE TITLE
localizer_first_level event file has useless dummy columns

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#2795]
loading the file triggers the following warning:  UserWarning: Unexpected column `Unnamed: 0` in events data will be ignored.  warnings.warn(("Unexpected column `{}` in events "

Nilearn version: 0.7.2

### Expected behavior
No warning and DataFrame with only 3 columns: 'event_type', 'onset', 'duration'

### Actual behavior
2 useless columns in the DataFrame

### Steps and code to reproduce bug

```python
from nilearn.datasets import func
data = func.fetch_localizer_first_level()
fmri_img = data.epi_img
events_file = data['events']
from nilearn.glm.first_level import FirstLevelModel
first_level_model = FirstLevelModel(t_r=2.4, high_pass=.01)
first_level_model = first_level_model.fit(fmri_img, events=events_file)
```

I think that the best solution is to clean the tsv file and upload to osf.

**Comment by Craskermasker** [comment]
keen to take this issue

**Comment by tsalo** [comment]
Do you have write access to the relevant OSF repository (https://osf.io/2bqxn)? If not, you may need to clean the file and attach it here, and then someone with access can upload it themselves. I think it would be particularly helpful to share the zip file so that whoever uploads the updated version just has to drag and drop instead of downloading, unzipping, updating, zipping, etc.

**Comment by bthirion** [comment]
Thx !

**Comment by Craskermasker** [comment]
Is this ok?

https://drive.google.com/file/d/14junssfREFTyltwpQZvM3RBLCeiq5q3L/view?usp=sharing

**Comment by tsalo** [comment]
The updated TSV looks good to me. Thank you. @bthirion it looks like you're the only person with write access to that OSF repo. Would you mind checking and uploading if it looks good to you?

**Comment by bthirion** [comment]
Done, the link is https://osf.io/2bqxn/
Best,

**Comment by tsalo** [comment]
I think this issue can be closed then. Thanks @Craskermasker.

**Comment by bthirion** [comment]
But we still need to change the osf link ?

**Comment by tsalo** [comment]
Isn't it still https://osf.io/2bqxn/ ?

**Comment by bthirion** [comment]
I thought the url had changed. Sorry for the noise. Thx !
