### ISSUE TITLE
Add more available resolutions for fsaverage

### ISSUE THREAD

**Issue by alexisthual** [nilearn/nilearn#2807]
For now, only fsaverage 5 (10k points per hemisphere) and 7 (150k points) are available.
I think it would make sense to add fsaverage 6 (40k points), and while we are at it do all versions from 1 to 4 as well.
You can visit [this page](https://brainder.org/2016/05/31/downsampling-decimating-a-brain-surface/) from brainder.org for more info about available resolutions :slightly_smiling_face:

Also, I feel like this issue is related to #2313 although not equivalent.

### Benefits to the change

- **fsaverage6**: A lot of people study quadratic problems on the brain surface, and going from 10k points to 150k can be a big step. I think it would be helpful to allow for intermediate resolutions.
- **fsaverage1-4?**: I think it sometimes makes sense to work with a low resolution on the brain surface (for instance when doing a big grid search or just when you want things to go really really fast); I would personally use `fsaverage4` from time to time if it were available!

### Pseudocode for the new behavior, if applicable

```python
fsaverage = datasets.fetch_surf_fsaverage(mesh='fsaverage4')
```

### Where to start

I think I would start from https://github.com/nilearn/nilearn/blob/a36c0442fc8eebe401b310dd9799c0f071080e90/nilearn/datasets/struct.py#L452 and try do something with a similar spirit as what has been implemented for fsaverage 5 and 7.

**Comment by bthirion** [comment]
I like it. I mean, I need it !

**Comment by jeromedockes** [comment]
It could be nice to ship the lowest-resolution mesh with nilearn and use it in tests instead of fsaverage5
