### ISSUE TITLE
EOL Python3.5

### ISSUE THREAD

**Issue by kchawla-pi** [nilearn/nilearn#2813]
Python 3.5 has been EOLed in Sept 2020. 
Nilearn should deprecate its use and add a warning to that effect.
Also the README and other relevant places should be updated to reflect the correct Python versions, for example more than 3.7

### Benefits to the change
Security and bugfixes for 3.5 have stopped.
3.6 has features especially Fstrings which make the code neater.
Putting out the warning now means we can remove 3.5 support in 2 cycle,s before it becomes too obsolete.

**Comment by bthirion** [comment]
Thx @kchawla-pi ! & happy to hear from you  :-)

**Comment by NicolasGensollen** [comment]
Indeed, It's almost the end of the story for Python 3.5:

https://github.com/nilearn/nilearn/blob/ae30ef6a4b622eff8a14750535449d4b38feee64/nilearn/__init__.py#L51-L59

**Comment by kchawla-pi** [comment]
Uh right I had added that warning. Time flies!
@bthirion thanks! Missing Nilearn!

**Comment by NicolasGensollen** [comment]
@kchawla-pi I'm closing this as dropping Python 3.5 is scheduled and will happen soon.

**Comment by kchawla-pi** [comment]
@NicolasGensollen Looking forward to f-strings!!
