### ISSUE TITLE
Refactor `signals.clean`

### ISSUE THREAD

**Issue by htwangtw** [nilearn/nilearn#2820]
The current code in `signals.py`, especially `signal.clean` is difficult to follow. To facilitate the integration of `load_confounds` #2777, and easier integration of DCT #1011, we should refactor it to a level where the data flow is easier to follow.

I would suggest, for now, extract some methods out just to clean up `signal.clean`. We can discuss if this function should be written into a module.

**Comment by bthirion** [comment]
You mean: make the code more modular ?

**Comment by htwangtw** [comment]
yes make it modular
