### ISSUE TITLE
Add "linewidths" arg for nilearn.plotting.plot_surf_contours

### ISSUE THREAD

**Issue by alpinho** [nilearn/nilearn#2834]
Similarly to other functions in Nilearn, the function [`plot_surf_contours` ](https://nilearn.github.io/modules/generated/nilearn.plotting.plot_surf_contours.html) should have a linewidths argument that changes the boundary thickness of the contours.

**Comment by jeromedockes** [comment]
ok it was a good idea but closing for now; hopefully if we add plotly surface plots this kind of thing will be easier to do! (#2793)
