### ISSUE TITLE
Unnecessary cross-validation when fitting Dummy Estimator in Decoder object

### ISSUE THREAD

**Issue by tbng** [nilearn/nilearn#2835]
While working on the PR to fix the bug of Dummy Classifier I noticed that when doing `Decoder.fit()` for `estimator='dummy_classifier'` and `estimator='dummy_regressor'` there is a cross-validation step. 

I understand that this is to conform with the pipeline of other type of estimators but maybe not really neccessary because essentially what the `DummyClassifier` and `DummyRegressor` does is making prediction based on the distribution/value of the training labels and not touching the other part of training dataset. Disabling the cross-validation step will also save computational time as well.

**Comment by jeromedockes** [comment]
> While working on the PR to fix the bug of Dummy Classifier I noticed that when doing `Decoder.fit()` for `estimator='dummy_classifier'` and `estimator='dummy_regressor'` there is a cross-validation step. 
>
> I understand that this is to conform with the pipeline of other type of estimators but maybe not really neccessary because essentially what the `DummyClassifier` and `DummyRegressor` does is making prediction based on the distribution/value of the training labels and not touching the other part of training dataset. Disabling the cross-validation step will also save computational time as well.

That's true, but at the same time this computational cost will usually
be very low compared to fitting actual estimators so it may not slow
down significantly the overall run (as typically the dummy estimator
will not be the only estimator that is fitted).
therefore, although it wouldn't be hard to do I'm not 100% sure it's
worth adding the logic to handle the special case of the Dummy estimators.
Besides it is a bit simpler to understand the decoder if the exact same
pipeline is used for all estimators. 
Also don't you think users might be interested in the variability of the
dummy scores across cv folds?

**Comment by tbng** [comment]
> While working on the PR to fix the bug of Dummy Classifier I noticed that when doing `Decoder.fit()` for `estimator='dummy_classifier'` and `estimator='dummy_regressor'` there is a cross-validation step. I understand that this is to conform with the pipeline of other type of estimators but maybe not really neccessary because essentially what the `DummyClassifier` and `DummyRegressor` does is making prediction based on the distribution/value of the training labels and not touching the other part of training dataset. Disabling the cross-validation step will also save computational time as well.
> That's true, but at the same time this computational cost will usually be very low compared to fitting actual estimators so it may not slow down significantly the overall run (as typically the dummy estimator will not be the only estimator that is fitted). therefore, although it wouldn't be hard to do I'm not 100% sure it's worth adding the logic to handle the special case of the Dummy estimators. Besides it is a bit simpler to understand the decoder if the exact same pipeline is used for all estimators. Also don't you think users might be interested in the variability of the dummy scores across cv folds?

Hmm I agree with the argument that to gain a bit of performance we would have to change the API for an arguably not the most important estimator. I think if there is no other opinion I would close this issue.

**Comment by jeromedockes** [comment]
>  I think if there is no other opinion I would close this issue.

@tbng  I guess we can close this one?

**Comment by thomasbazeille** [comment]
+1 for closing !
