### ISSUE TITLE
`plot_surf` creates a figure that is too wide

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2847]
by default `plot_surf`, `plot_surf_stat_map`, etc create a figure of height, width = 4, 6 (or 4, 6.7 with a colorbar), which is very wide and that results in a lot of white space on the left of the figure, see [here](https://nilearn.github.io/auto_examples/01_plotting/plot_3d_map_to_surface_projection.html#plot-the-result) for example, or with a colored figure and axis to make it easier to see the space occupied by the axis:

![fig](https://user-images.githubusercontent.com/9196501/118872461-96e3c400-b8b6-11eb-8867-4a6902595520.png)

AFAICT all that needs to change would be [this default size](https://github.com/nilearn/nilearn/blob/14d23f2a3e8416330a9f4db3110509799d32dc02/nilearn/plotting/surf_plotting.py#L161), but I guess it may have been chosen like this because it is a better choice for some meshes or point of views? it seems to have been set in #2643 @NicolasGensollen  do you remember?

**Comment by bthirion** [comment]
There are two points
* choose a better default (eg the default aspect ratio of matplotlib ?)
* make this easier to change: documentation /examples / tutorials.

**Comment by NicolasGensollen** [comment]
@jeromedockes I remember this PR indeed but I don't remember how I chose these values... I think they just correspond to my defaults:

```python
import matplotlib.pyplot as plt
fig = plt.figure()
print(fig.get_size_inches())
```
```
[6. 4.]
```
But I don't think they were chosen for any other particular reason, so I agree we should change them if they don't render nicely in the examples.

>make this easier to change

@bthirion For now, we can change this by passing a figure to `plot_surf`:

```python
import matplotlib.pyplot as plt
fig = plt.figure(figsize=(3,4))
display = plotting.plot_surf_stat_map(fsaverage.infl_right, texture, hemi='right',
                            title='Surface right hemisphere', colorbar=True,
                            threshold=1., bg_map=fsaverage.sulc_right, figure=fig)
print(display.get_size_inches())
```
```
[3. 4.]
```

Do you mean we should add support for a tuple (figsize) or a scalar (aspect ratio) for the figure argument?

**Comment by jeromedockes** [comment]
> But I don't think they were chosen for any other particular reason, so I agree we should change them if they don't render nicely in the examples.

great, we can just change it to 4, 4 then. I can open a pr

>
>>make this easier to change
>
> @bthirion For now, we can change this by passing a figure to `plot_surf`:
>
> ```python
> import matplotlib.pyplot as plt
> fig = plt.figure(figsize=(3,4))
> display = plotting.plot_surf_stat_map(fsaverage.infl_right, texture, hemi='right',
>                             title='Surface right hemisphere', colorbar=True,
>                             threshold=1., bg_map=fsaverage.sulc_right, figure=fig)
> print(display.get_size_inches())
> ```
> ```
> [3. 4.]
> ```
>
> Do you mean we should add support for a tuple (figsize) or a scalar (aspect ratio) for the figure argument?

IIUC the idea is to better explain and illustrate how to control the
figure size as in your code snippet above in the documentation and
example gallery?

there was a similar comment in another pr:
https://github.com/nilearn/nilearn/pull/2798#issuecomment-840110275
I also remember discussing with @PeerHerholz  the possibility of having a
slightly more advanced plotting example that highlights the fact that
nilearn plots can be customized by using matplotlib directly.

**Comment by bthirion** [comment]
> Do you mean we should add support for a tuple (figsize) or a scalar (aspect ratio) for the figure argument?

No, it's simpler to pass a figure.
