### ISSUE TITLE
Discrepancy of argument names in view_markers and view_connectome

### ISSUE THREAD

**Issue by RaphaelMeudec** [nilearn/nilearn#2852]
Following #2810 (discussion [here](https://github.com/nilearn/nilearn/pull/2810#issuecomment-838597255)), we noticed that arguments for `html_connectome.view_connectome` and `html_connectome.view_markers` have different names even though they reflect the same object: 

- in `view_markers`, arguments relative to the markers are prefixed with `marker_` (e.g `marker_coords`)
- in `view_connectome`, arguments relative to the markers are prefixed with `node_` (e.g `node_coords`)

My opinion is that we should converge to either one of them. What do you think?

Signatures of the two functions:

```python
def view_markers(marker_coords, marker_color=None, marker_size=5., marker_labels=None, title=None, title_fontsize=25)
```

```python
def view_connectome(adjacency_matrix, node_coords, edge_threshold=None, edge_cmap=cm.bwr, symmetric_cmap=True, linewidth=6., node_size=3., colorbar=True, colorbar_height=.5, colorbar_fontsize=25, title=None, title_fontsize=25)
```

**Comment by NicolasGensollen** [comment]
I agree that we should have consistent naming and pick one convention. I would be in favor of using the `node_` convention but I'm fine with the alternative if the majority prefers `marker_`.

**Comment by jeromedockes** [comment]
yes if one is changed both should use "node", as does `plot_connectome`:
https://github.com/nilearn/nilearn/blob/b1d44fdac93f972abe1ce17405f5dc3347945049/nilearn/plotting/img_plotting.py#L1477

and `plot_markers`:

https://github.com/nilearn/nilearn/blob/b1d44fdac93f972abe1ce17405f5dc3347945049/nilearn/plotting/img_plotting.py#L1760

note "marker" is used by `add_markers`:

https://github.com/nilearn/nilearn/blob/b1d44fdac93f972abe1ce17405f5dc3347945049/nilearn/plotting/displays.py#L1024

**Comment by RaphaelMeudec** [comment]
take

**Comment by RaphaelMeudec** [comment]
@jeromedockes @NicolasGensollen I'm renaming the markers_ arguments into nodes_ and wonder if it does make sense that `view_markers` should only take `node_*` arguments. Shouldn't we rename the method to `view_nodes`?

Also in the `connectome_html_template`, all references go to `marker_*`. Should I switch to `nodes_*` in this file too?

**Comment by NicolasGensollen** [comment]
> Shouldn't we rename the method to view_nodes?

I think so yes. I think the easiest way would be to do something like this:

```python
def view_nodes(node_coords, node_color='auto', node_size=5.,
                 node_labels=None, title=None, title_fontsize=25):
    # Func body

@deprecated("explanations...")
def view_markers(marker_coords, marker_color='auto', marker_size=5.,
                 marker_labels=None, title=None, title_fontsize=25):
    return view_nodes(marker_coords, node_color=marker_color, node_marker_size=marker_size,
                 node_labels=marker_labels, title=title, title_fontsize=title_fontsize)
```

**Comment by NicolasGensollen** [comment]
>Also in the connectome_html_template, all references go to marker_*. Should I switch to nodes_* in this file too?

I think we should since this is more consistent. I don't think there is an explicit additional deprecation needed here since the template is only  accessed  in a private view_markers's helper function:

https://github.com/nilearn/nilearn/blob/e6591d8907ceae55eea6f04ce181acb6a12743b5/nilearn/plotting/html_connectome.py#L218-L222

**Comment by jeromedockes** [comment]
closing as was decided in #2895
