### ISSUE TITLE
`fetch_openneuro_dataset_index` should clearly indicate it's hardcoded to retrieve a particular dataset

### ISSUE THREAD

**Issue by tyarkoni** [nilearn/nilearn#2853]
The docstring for `nilearn.datasets.fetch_openneuro_dataset_index` implies the function can be used to retrieve the file index from any OpenNeuro dataset, but it's actually hardcoded to only work with one dataset (ds000030). This is confusing, as the local directory takes the name of the requested dataset, even though it's always the same file list that's retrieved. A generalized function would be best if feasible, but failing that, it probably makes sense to only take a `version` argument and clarify in the docstring that the scope of the utility is limited to ds000030.

**Comment by NicolasGensollen** [comment]
Thanks for opening this @tyarkoni. I agree that this can be confusing as the URL is indeed harcoded and doesn't depend on the value of the `dataset_version` argument:

https://github.com/nilearn/nilearn/blob/7142c5c9199e13c67111e7a44c58c9169259908b/nilearn/datasets/func.py#L2295-L2302
 
I think there are two things we can do quickly to improve this:

- Clarify the docstring to reflect the fact that the argument `dataset_version` cannot take any value (currently only one).
- Add a safety check that raises an error for invalid values of this argument (which would avoid creating data folders with any string you pass in).

**Comment by jeromedockes** [comment]
`fetch_openneuro_dataset` also seems to rely on `fetch_openneuro_dataset_index` and work only for that particular dataset.
I think they should be called something like `fetch_ucla_neuropsychiatric_phenomics[_index]` or some other summary of the dataset name, and not `fetch_openneuro`

also should `fetch_openneuro_dataset_index` and `patch_openneuro_dataset` be private?

**Comment by NicolasGensollen** [comment]
>also should fetch_openneuro_dataset_index and patch_openneuro_dataset be private?

I also think they should. Note that `fetch_openneuro_dataset_index` is used in an example but I don't really see why it is called and not directly `fetch_openneuro_dataset` (might just be to link this function to an example in the doc...).

**Comment by jeromedockes** [comment]
ah yes it is to filter the urls to download with `fetch_openneuro_dataset` using `select_from_index` so I guess this one has to be public.

**Comment by tsalo** [comment]
Ultimately, it seems like `fetch_openneuro_dataset_index` and `fetch_openneuro_dataset` should be merged in some way. However, as a more immediate solution, what if we (1) renamed the functions to something like `fetch_ds000030`, (2) made the current function names aliases, and (3) added a deprecation warning to the aliases?
