### ISSUE TITLE
Using SearchLight without cross-validation

### ISSUE THREAD

**Issue by psadil** [nilearn/nilearn#2855]
I'm helping on a project that involves a somewhat atypical searchlight analysis. There are two kinds of runs, call them `A` and `B`. We'd like to train on `A` and test on `B`. Unlike a typical cross-validation, we don't need to do the reverse -- no need to train on `B` and test on `A`. As I understand, there isn't currently a clean way to do this. 

### Benefits to the change

#1632 gets part way there, in of that we could use a `leave-one-group-out` cross-validation generator and then focus analyses on just the fold in which `A` was the train and `B` was the test. But that still involves unneeded computation, since we don't have intentions to look at the other fold. 

### Pseudocode for the new behavior, if applicable

I can think of two ways to do this. One way would be to implement a `predict` and `score` method for the `SearchLight` class. 

Continuing from one of the [example searchlight analyses](https://nilearn.github.io/auto_examples/02_decoding/plot_haxby_searchlight.html#searchlight-computation)

```python
# special value that SearchLight would recognize and not do any cross-validation
cv = 0

import nilearn.decoding
# The radius is the one of the Searchlight sphere that will scan the volume
searchlight = nilearn.decoding.SearchLight(
    mask_img,
    process_mask_img=process_mask_img,
    radius=5.6, n_jobs=n_jobs,
    verbose=1, cv=cv)
searchlight.fit(fmri_img, y)

# predict labels for runs in group B
searchlight.predict(fmri_test_group_B)

# score labels for those runs
searchlight.score(labels_test_group_B)
```

An alternative strategy would be to implement a special cross-validation generator that `SearchLight` recognizes as 

```python
# new cross-validator generator to implement
# name to be determined
cv = train_one_test_one() # alt names: train_predict_score() train_test() others?

import nilearn.decoding
# The radius is the one of the Searchlight sphere that will scan the volume
searchlight = nilearn.decoding.SearchLight(
    mask_img,
    process_mask_img=process_mask_img,
    radius=5.6, n_jobs=n_jobs,
    verbose=1, cv=NoFold)
searchlight.fit(fmri_img, y)

# resulting searchlight.score_ values contains desired scores 
```
What do you think? Like I said, I'd like this feature for a project, so I'd be happy to implement it, or implement another approach that gives the same functionality.

Thanks,

**Comment by robbisg** [comment]
I think that the main problem here is that you have to store a model for each voxel. I have the feeling that this may be a bit difficult and memory-consuming.
My suggestion is to use Leave One Group Out and unless the test on group A could be useless, maybe it could add some information about the the reverse-decoding task.

**Comment by bthirion** [comment]
isn't this what you need ?:
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.PredefinedSplit.html
Best,

**Comment by psadil** [comment]
> 
> 
> isn't this what you need ?:
> https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.PredefinedSplit.html
> Best,

Oh! Yes, I think that is exactly what we need; `PredefinedSplit` implements what I was thinking with the 'alternative strategy'. Thanks for pointing that out. I'll close this issue.
