### ISSUE TITLE
Attribute `components_` is deprecated since 0.4.1 but still here

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2862]
As can be seen in these files:

https://github.com/nilearn/nilearn/blob/dbbd221e3633c97464034c5366faa548728c9999/nilearn/decomposition/canica.py#L130-L134

https://github.com/nilearn/nilearn/blob/dbbd221e3633c97464034c5366faa548728c9999/nilearn/decomposition/dict_learning.py#L152-L155

https://github.com/nilearn/nilearn/blob/a36c0442fc8eebe401b310dd9799c0f071080e90/nilearn/decomposition/multi_pca.py#L121-L125

There is also a note here:

https://github.com/nilearn/nilearn/blob/a36c0442fc8eebe401b310dd9799c0f071080e90/examples/03_connectivity/plot_extract_regions_dictlearning_maps.py#L20-L26

We should remove them in 0.8.0.

**Comment by NicolasGensollen** [comment]
Actually, I'm not really sure what was intended here. I initially thought that `components_` was meant to disapear in favor of `components_img_`, but I realize it could just be a note to encourage users to rely on `components_img_` instead of manually unmasking `components_`. Does someone knows more on this?

**Comment by jeromedockes** [comment]
it seems this was done in pr #1536 , and [here](https://github.com/nilearn/nilearn/pull/1536#issuecomment-361674725) is the discussion about deprecating `components_`

**Comment by jeromedockes** [comment]
also, the `transform` and `inverse_transform` of the base decomposition:
https://github.com/nilearn/nilearn/blob/dbbd221e3633c97464034c5366faa548728c9999/nilearn/decomposition/base.py#L458

unmask the components every time; they should rely on `components_img_`; they also create a new mapsmasker every time; this should be done in `fit`

**Comment by jeromedockes** [comment]
note the Decoder & co., for example, have both `coef_` and `coef_img_`. SearchLight has `scores_` which is neither an image nor masked data (see #2673), ... maybe we should make a list of all such objects and make this consistent?

I don't see a big disadvantage of having them both, as the Decoder does. to avoid storing them twice the least frequently used one can be implemented as a property
