### ISSUE TITLE
modulation column for make_first_level_design_matrix 

### ISSUE THREAD

**Issue by maalaria** [nilearn/nilearn#2872]
When having a 'modulation' column in the events.tsv that is passed to ```nilearn.glm.first_level.make_first_level_design_matrix```, a UserWarning occurs saying 
```
UserWarning: ‘modulation’ column found in the given events data.
```
This should be changed into a simple message saying that the 'modulation'-column is being used rather than printing a warning which is confusing.

### Benefits to the change
Clearer information about what is happening 

### Pseudocode for the new behavior, if applicable

```python
if modulation:
    print('Modulation column is found in events-data and is used')

```

**Comment by NicolasGensollen** [comment]
Linking #2680 where this warning was added.
Thanks for opening this @maalaria. I don't mind replacing the warning by a print and modifying the message if people think it is confusing.

**Comment by bthirion** [comment]
It can be confusing indeed IMHO.
