### ISSUE TITLE
ticks missing from `view_img` colorbar for some images

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#2874]
```python
from nilearn import plotting, datasets

plotting.view_img(datasets.load_mni152_template(), bg_img=None).open_in_browser()
```

![Screenshot from 2021-06-14 10-17-45](https://user-images.githubusercontent.com/9196501/121907215-d8229480-ccf9-11eb-9ac2-0452bde89220.png)

**Comment by NicolasGensollen** [comment]
I don't think the ticks are missing:

```python
plotting.view_img(datasets.load_mni152_template(), black_bg=True, bg_img=None)
```
![ticks](https://user-images.githubusercontent.com/2639645/121918841-b693ce00-cd36-11eb-9210-804de3ff0a02.png)
 
I'll have a closer look to see how we can fix this.

**Comment by jeromedockes** [comment]
I see, so I guess the issue that when `black_bg` is False, most of the background is still actually black. so depending on the position of the colorbar the tick labels end up being black text on a black background

**Comment by NicolasGensollen** [comment]
@jeromedockes This is also my conclusion. I'm still looking for a way to fix this. I think moving up the colorbar makes the most sense.

**Comment by jeromedockes** [comment]
maybe @pbellec has some advice?

**Comment by pbellec** [comment]
Not sure if it's related, but I noticed that in some instances nilearn volumes come with a mask, which leads to a white background in `plot_stat_map` for example, but is ignored by `view_img`. If the mask was applied, then `black_bg=False` would be the right guess, and the black writing would be visible.
