### ISSUE TITLE
The method of FDR threshholding in GLM

### ISSUE THREAD

**Issue by gourdchen** [nilearn/nilearn#2879]
The nilearn/glm/thresholding.py line 101：
` pos = p_vals < alpha * np.linspace(
        .5 / n_samples, 1 - .5 / n_samples, n_samples)`

In my opinion, the code should be 
`pos = p_vals < alpha * np.linspace(1/n_samles, 1,n_samples)`
Why does ’0.5‘ exist there？ It confuses me.

**Comment by bthirion** [comment]
Indeed, this is an error. Can you issue a PR ?

**Comment by AjithRamachandran** [comment]
Is anyone working on this rn?

**Comment by bthirion** [comment]
No. Please go ahead if you wish.

**Comment by AjithRamachandran** [comment]
Thank you

**Comment by bthirion** [comment]
Close as fixed.
