### ISSUE TITLE
Can you give a reference for the p-value calculation for contrasts?

### ISSUE THREAD

**Issue by jcrdubois** [nilearn/nilearn#2881]
<img width="359" alt="Screen Shot 2021-06-18 at 10 31 17 AM" src="https://user-images.githubusercontent.com/5529616/122597637-81ca9400-d020-11eb-8390-010fc9f42185.png">

This is the relationship between t-values and p-values (plotted as `-log10(p)`) for the contrast `active - rest` in the auditory dataset distributed with nilearn. 
The blue line is what I'd expect for the p-value -- a high negative t-value should yield a low p-value too. But perhaps nilearn chooses to do a one-tailed test, which I suppose is fine (one would just need to build both "active - rest" and "rest - active" if one is interested in bidirectional effects. However, I don't understand why some of the negative t-values yield a p-value that is != 1. 
The code to compute the p-value is [here](https://github.com/nilearn/nilearn/blob/297b15095e75da1566018a63b23a86031b90dfa5/nilearn/glm/contrasts.py#L275
): can you point me to a reference for this formulation?  (I saw a reference for the Nichols 2005 paper, but that was related to conjunction analysis, and didn't seem directly relevant)

Nilearn version: nilearn==0.7.1

### Expected behavior
(see blue line above)

### Actual behavior
(see orange line above)

### Steps and code to reproduce bug

```python
from nilearn.datasets import fetch_spm_auditory
from nilearn import image
import pandas as pd
from nilearn.glm.first_level import FirstLevelModel
import matplotlib.pyplot as plt
# load fMRI data
subject_data = fetch_spm_auditory()
fmri_img = image.concat_imgs(subject_data.func)
# Clean and smooth data
fmri_img = image.clean_img(fmri_img, standardize=False)
fmri_img = image.smooth_img(fmri_img, 5.)
# load events
onsets = pd.read_table(subject_data['events'])
# run glm
fmri_glm = FirstLevelModel(t_r=7,
                           drift_model='cosine',
                           hrf_model='spm', 
                           drift_order=1,
                           noise_model='ols',
                           high_pass=1/128,
                           fir_delays=[0], 
                           standardize=False,
                           signal_scaling=False,
                           mask_img=False, #mask,
                           minimize_memory=False)
fmri_glm = fmri_glm.fit(fmri_img, onsets)
# run contrast
stat_maps = fmri_glm.compute_contrast('rest - active', output_type='all')
# plot `-log10(p)` vs `t`
plt.plot(stat_maps['stat'].get_fdata().flatten(), -np.log10(stat_maps['p_value'].get_fdata().flatten()), '.')
plt.show()
```

**Comment by bthirion** [comment]
Hi @jcrdubois 
Thank you for opening this discussion.
AFAIK in fMRI data analysis at least, we relay on-sided tests, for two reasons:
* Effect sign matters: it makes a difference whether you detect a Bold increase or decrease in raltion to an experimental manipulation
* more anecdotally, this makes you test more powerful (by a factor of 2).
If you want to infer on the unsigned contrast, the most proper way is to use:
`stat_maps = fmri_glm.compute_contrast('rest - active', output_type='all', stat_type='F'` 
in the above example.
I realize that we don't make it explicit that
t-test <-> one-sided p-value
F-test  <-> two-sided p-value
Does that answer your concern ?

**Comment by jcrdubois** [comment]
Hi @bthirion thanks for the answer. 

I understand the one-sided argument, and indeed that may be the most common practice and buys you some statistical power if you are interested in a single direction for the effect.

What I don't yet understand is the way the p-value is derived, using a survival function ([here](https://github.com/nilearn/nilearn/blob/297b15095e75da1566018a63b23a86031b90dfa5/nilearn/glm/contrasts.py#L275)). I would have thought that the p-value would be `1 - cdf(t)` -- in fact, the very formulation that nilearn has for `one_minus_pvalue` ([here](https://github.com/nilearn/nilearn/blob/297b15095e75da1566018a63b23a86031b90dfa5/nilearn/glm/contrasts.py#L306)). I'm sure there is a good reason for it, I was just wondering if you could share a reference for my own instruction! 

Thank you!

**Comment by bthirion** [comment]
`sf = 1- cdf`
the reason to rely on one or the other is simply numerical: floats greater than 1- e-16 are equalled to one, leading to infinite z-values, so we keep in that case 1 minus pvalue, that is close to 0.

**Comment by bthirion** [comment]
Sorry, this is a bit sketchy. I hope I'm clear.

**Comment by jcrdubois** [comment]
Ah, I just tried the one-tailed p-value as 1 - cdf(t) and indeed, it overlaps exactly with the one from nilearn. Excuse me for spreading confusion here! Thank you for the fast replies
