### ISSUE TITLE
Nilearn Office Hours are every Friday at 16:00 UTC

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2882]
Dear friends and colleagues,

We will be holding office hours  around Nilearn on a regular basis from now on. :tada:

Our goal is to have one hour every two weeks :clock1: where at least one core-developer of Nilearn will be connected to answer questions.

We also wish to use this time to have live discussions around Nilearn and possible directions for its development. This is a good place to talk about potential feature requests for example. :rocket:

The next and first office hour will be held on **Monday June 28th from 4pm to 5pm UTC** on [Discord](https://discord.gg/bMBhb7w) (same link as for the dev-days 2021). :date:

If you have questions :raising_hand: or if you want to talk :speech_balloon: about Nilearn, please join us!

See you there!

The Nilearn Team

**Comment by NicolasGensollen** [comment]
The next office hours will be on **Monday July 12th from 4pm to 5pm UTC** on [Discord](https://discord.gg/bMBhb7w).

Please join us for questions or discussions around Nilearn.

See you there!

**Comment by NicolasGensollen** [comment]
Due to summer constraints, the next office hours will be on **Monday August 30th from 4pm to 5pm UTC** on [Discord](https://discord.gg/bMBhb7w).

Please join us for questions or discussions around Nilearn.

See you there!

**Comment by NicolasGensollen** [comment]
The next office hours will be on **Monday September 13th from 4pm to 5pm UTC** on [Discord](https://discord.gg/bMBhb7w).

Please join us for questions or discussions around Nilearn.

See you there!

**Comment by NicolasGensollen** [comment]
The next office hours will be on **Monday September 27th from 4pm to 5pm UTC** on [Discord](https://discord.gg/bMBhb7w).

Please join us for questions or discussions around Nilearn.

See you there!

**Comment by NicolasGensollen** [comment]
Due to an unforeseen event, we have to cancel the office hours scheduled Monday September 27th. Please open an issue here, or a post on Neurostars if you have a burning question.

The next office hours will be on **Monday October 11th from 4pm to 5pm UTC** on [Discord](https://discord.gg/bMBhb7w).

Please join us for questions or discussions around Nilearn.

See you there!

**Comment by htwangtw** [comment]
Do we want to advertise the office hours in [NiPy Calendar](https://nipy.discourse.group/t/announcement-meeting-calendar/83)? I can add the event.

**Comment by NicolasGensollen** [comment]
>Do we want to advertise the office hours in NiPy Calendar? I can add the event.

I think this is a good idea. Thanks a lot @htwangtw !  :+1: 
Btw, I realized that neither @bthirion or I will be available this Friday, so unless other core-devs are available, it might be better to switch to Fridays from next week... (Friday November 19th 4pm-5pm UTC would be the next office hour then).

**Comment by jeromedockes** [comment]
should we update the description of this issue and put office hours on the website?

**Comment by NicolasGensollen** [comment]
>should we update the description of this issue and put office hours on the website?

I can add a note to the landing page explaining that office hours take usually place every Friday from 4pm to 5pm UTC and link to this issue for special announcements (cancellations, change of time...). Is that what you had in mind?
Note: the office hours are also advertised in the README.
Note: We can also close this issue and open a new one with more up-to-date information in the first message.

**Comment by jeromedockes** [comment]
> I can add a note to the landing page explaining that office hours take usually place every Friday from 4pm to 5pm UTC and link to this issue for special announcements (cancellations, change of time...). Is that what you had in mind?

I think that would be great!

> Note: the office hours are also advertised in the README.

Sorry I had missed that

> Note: We can also close this issue and open a new one with more up-to-date information in the first message.

Yes it would be best if the correct time was at the top of the issue. I
can do it if you're busy!

**Comment by jeromedockes** [comment]
closing so we can open a new issue containing only the friday 16:00 UTC time which will be used from now on
