### ISSUE TITLE
Cannot use threshold with `plot_epi` although it is documented

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#2885]
The function `nilearn.plotting.plot_epi` documents a `threshold` parameter:

https://github.com/nilearn/nilearn/blob/78f7d133b564f30883d5771a716bd9109cf7cac9/nilearn/plotting/img_plotting.py#L698-L703

but does not have a `threshold` argument:

https://github.com/nilearn/nilearn/blob/78f7d133b564f30883d5771a716bd9109cf7cac9/nilearn/plotting/img_plotting.py#L631-L634

So, when trying to set a threshold through `plot_epi`, it gets passed to `plot_img` through kwargs and is also passed explicitly as None:

https://github.com/nilearn/nilearn/blob/78f7d133b564f30883d5771a716bd9109cf7cac9/nilearn/plotting/img_plotting.py#L716-L722

Which results in the following error:

```python
from nilearn import plotting, datasets
plotting.plot_epi(datasets.MNI152_FILE_PATH, threshold=.2)
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-3944ca75bc88> in <module>
      1 from nilearn import plotting, datasets
----> 2 plotting.plot_epi(datasets.MNI152_FILE_PATH, threshold=.2)

~/GitRepos/nilearn-fork/nilearn/plotting/img_plotting.py in plot_epi(epi_img, cut_coords, output_file, display_mode, figure, axes, title, annotate, draw_cross, black_bg, cmap, vmin, vmax, **kwargs)
    714 
    715     """
--> 716     display = plot_img(epi_img, cut_coords=cut_coords,
    717                        output_file=output_file, display_mode=display_mode,
    718                        figure=figure, axes=axes, title=title,

TypeError: plot_img() got multiple values for keyword argument 'threshold'
```

We should either remove the docstring entry or add threshold to the parameters of `plot_epi`. WDYT?

**Comment by tsalo** [comment]
It doesn't seem like threshold fits with `plot_epi`'s purpose. I vote for removing the docstring entry.
