### ISSUE TITLE
fmri_glm.compute_contrast() mention beta/parameter estimates explicitly?

### ISSUE THREAD

**Issue by mekman** [nilearn/nilearn#2913]
As a new user I struggled to figure out how to get simple **beta estimates** from ``glm.first_level``. I went through the user guide, searched the glossary page and tried all the GLM examples.. I might have just missed it, or not looked for the correct term, but I am proposing to make it easier to find.

Finally, in this [PR](https://github.com/nilearn/nilearn/pull/2910) @bthirion pointed out that it was as easy as ``glm.compute_contrast(..., output_type='effect_size')``

The last thing I want to get into is a discussion on nomenclature ;-) and I see why nilearn choose to call it ``effect_size``, but I wonder if you were open to a PR that would either
* add an glossary entry for effect_size to make the relationship clear with beta/parameter estimates (PE)
* mention beta/parameter estimates in the docstring of the ``Contrast`` object in ``glm.contrasts``
* use beta/parameter estimates for one of the GLM examples. I think the [GLM decoding example](https://nilearn.github.io/auto_examples/02_decoding/plot_haxby_glm_decoding.html#sphx-glr-auto-examples-02-decoding-plot-haxby-glm-decoding-py) is very useful, as most people will be familiar with decoding based on PE's (as this has been used in the literature frequently)
* This [example](https://nilearn.github.io/auto_examples/04_glm_first_level/plot_spm_multimodal_faces.html#sphx-glr-auto-examples-04-glm-first-level-plot-spm-multimodal-faces-py) actually mentions beta maps "We can specify basic contrasts (to get beta maps)." I could add a paragraph that states how to actually get the beta maps by setting ``output_type='effect_size'``. The example itself never shows how to get beta maps, so this might be a good and easy addition.

WDYT?

**Comment by bthirion** [comment]
Thx for opening this discussion.
I'm happy with your suggestions. Do you want to start working on one or two PRs to do this ? You seem to be in a good position to improve the documentation and examples !

**Comment by NicolasGensollen** [comment]
Thanks for opening this and for the suggestions @mekman !
Let us know if you are working on a PR and have some questions.

**Comment by mekman** [comment]
Thank you for the positive reception of my suggestions. FYI; I started with a PR adding the terms parameter estimate and beta to the glossary and linking it to the term effect_size that is used in Nilearn. I will follow-up with another PR tackling the example once I am more familiar/comfortable with the code base.
