### ISSUE TITLE
syntax error in glm

### ISSUE THREAD

**Issue by drammock** [nilearn/nilearn#2915]
#2532 introduced a syntax error that is breaking the MNE-Python CIs.  Specifically:

https://github.com/nilearn/nilearn/blob/f9deafe828dc21d5d4dd54b772da820ee1f4cac5/nilearn/glm/first_level/first_level.py#L147

leads to this in our documentation CI build:

```
Traceback (most recent call last):
  File "/home/circleci/project/tutorials/inverse/20_dipole_fit.py", line 24, in <module>
    from nilearn.plotting import plot_anat
  File "/home/circleci/.local/lib/python3.8/site-packages/nilearn/plotting/__init__.py", line 51, in <module>
    from .matrix_plotting import (plot_matrix, plot_contrast_matrix,
  File "/home/circleci/.local/lib/python3.8/site-packages/nilearn/plotting/matrix_plotting.py", line 13, in <module>
    from nilearn.glm.contrasts import expression_to_contrast_vector
  File "/home/circleci/.local/lib/python3.8/site-packages/nilearn/glm/__init__.py", line 31, in <module>
    from nilearn.glm import first_level
  File "/home/circleci/.local/lib/python3.8/site-packages/nilearn/glm/first_level/__init__.py", line 6, in <module>
    from nilearn.glm.first_level.first_level import (
  File "/home/circleci/.local/lib/python3.8/site-packages/nilearn/glm/first_level/first_level.py", line 147
    if ((noise_model[:2] != 'ar') and (noise_model is not 'ols')):
                                       ^
SyntaxError: "is not" with a literal. Did you mean "!="?
```

Nilearn version: looks like our CI installs 0.8.0

cc @rob-luke

**Comment by rob-luke** [comment]
Thanks @drammock. Is there an additional CI test we could add to nilearn to ensure these types of syntax errors sneak in? @NicolasGensollen I can see there is a flake8 test, but am I correct in seeing that it only checks the diff between commits? Is this as there was a lot of legacy pep violations and you just want to incrementally fix?

**Comment by drammock** [comment]
> Is there an additional CI test we could add to nilearn to ensure these types of syntax errors sneak in?

I don't think this would be caught by static analysis like flake8, but it should get caught if you try to execute the code. I suspect this means that this part of the GLM code isn't covered by a test (though I haven't checked).

**Comment by jeromedockes** [comment]
> I suspect this means that this part of the GLM code isn't covered by a test (though I haven't checked).

I believe with the default warning filters this should be a `SyntaxWarning`, not a `SyntaxError`, so it is possible that it is covered by a test and causes a warning there

**Comment by drammock** [comment]
> > I suspect this means that this part of the GLM code isn't covered by a test (though I haven't checked).
> 
> I believe with the default warning filters this should be a `SyntaxWarning`, not a `SyntaxError`, so it is possible that it is covered by a test and causes a warning there

That could be.  Or if you're not testing on Python 3.8 or later, it wouldn't show up at all.
