### ISSUE TITLE
SearchLight analysis with parallelization 

### ISSUE THREAD

**Issue by maalaria** [nilearn/nilearn#2922]
When running a searchlight analysis with more than 1 job (eg. `n_jobs=-1`) the execution breaks giving the error:

```
A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable
```

Nilearn version: 0.8.0

### Solution

I found a solution which is to modify the  `joblib.Paralle()` call in `searchlight.py`:

```
scores = Parallel(n_jobs=n_jobs, verbose=verbose, backend='multiprocessing')(
            delayed(_group_iter_search_light)(
                A.rows[list_i],
                estimator, X, y, groups, scoring, cv,
                thread_id + 1, A.shape[0], verbose)
```
i.e. specifying the backend. 

It works but since I am not familiar with the bedrocks I wonder if this causes any side effects?

**Comment by NicolasGensollen** [comment]
Thanks for opening this @maalaria 
Do you have a minimal working example on which we could investigate?

**Comment by thomasbazeille** [comment]
hello @maalaria. It is weird that it work with 'multiprocessing' back-end and not with threading. I suspect this has something to do with your arguments / your call. Note that [the advised syntax for Parallel()](https://joblib.readthedocs.io/en/latest/generated/joblib.Parallel.html) includes a `for` to iterate in parallel on its iterable argument e.g. :
```
from math import sqrt
from joblib import Parallel, delayed
Parallel(n_jobs=1)(delayed(sqrt)(i**2) for i in range(10))
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]
```

> It works but since I am not familiar with the bedrocks I wonder if this causes any side effects?

No, not in terms of results accuracy. It mostly results in a different way to handle concurrent memory access from different jobs that can lead to more or less efficient parallelization (i.e. runtime)
