### ISSUE TITLE
LGTM error: Non-iterable used in for loop

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [nilearn/nilearn#2926]
I don't fully grasp the details of [this LGTM.com alert](https://lgtm.com/projects/g/nilearn/nilearn/snapshot/0cd925e33787e277990b524efeba0c8125d04816/files/nilearn/decoding/space_net.py?sort=name&dir=ASC&mode=heatmap#x4b41318e0293a848:1):
> `[ 3 Values ]` of class '`[ 3 Values ]`' may be used in for-loop.

What are these "3 Values" about?

Nevertheless, it is true that in `l1_ratios` [might be a float, hence not iterable](https://github.com/nilearn/nilearn/blob/bbbc4ba/nilearn/decoding/space_net.py#L685-L687):
```python
            if isinstance(l1_ratios, numbers.Number):
                l1_ratios = [l1_ratios]
            for l1_ratio in l1_ratios:s.Number):
```
Indeed, `l1_ratios` is initialised to be a float, so why check whether it is an instance of `numbers.Number`? Am I missing something here?

**Comment by jeromedockes** [comment]
`l1_ratios` can be either a float or a sequence  of floats (in that case the best value will be selected by a nested cross-validation loop). this checks which it is, and turns it into a (length 1) sequence of floats if it is a single float. `0.` and `1.` are valid values for `l1_ratio`, so there is a chance that a user might pass an int instead of a float, so it is safer to check if it is a `numbers.Number` rather than just `float`.

I don't know what [ 3 Values ] of class '[ 3 Values ]' means

**Comment by DimitriPapadopoulos** [comment]
Ah, you mean a `float` **is** a `numbers.Number`? Didn't even try to test that, sorry. I'll report this as a false positive, then.

**Comment by DimitriPapadopoulos** [comment]
But since what we want is to change a non-iterable into a list, we could as well test:
```python
            try:
                iter(l1_ratios)
            except TypeError:
                l1_ratios = [l1_ratios]
```
instead of:
```python
            if isinstance(l1_ratios, numbers.Number):
                l1_ratios = [l1_ratios]
```

**Comment by jeromedockes** [comment]
yes that would also work, and we could also check if it is an instance of `collections.Iterable`. I think the existing solution is also fine, though

**Comment by DimitriPapadopoulos** [comment]
The current solution is fine, of course. I just want to work around the LGTM.com warning.

**Comment by jeromedockes** [comment]
I see, then yes if it silences the warning we can change it

**Comment by DimitriPapadopoulos** [comment]
Cannot be 100% certain, but I think this will silence the warning.
