### ISSUE TITLE
[bug] index_img does not adjust header pixdim if necessary

### ISSUE THREAD

**Issue by dangom** [nilearn/nilearn#2939]
When slicing timepoints from a dataset with index_img, the function does not adjust the pixel dimensions or TR.
This could be critical because users may forget to adapt the TR and get wrong results if attempting to run a GLM. I could see this being the case for, e.g., separating tag and control images from an ASL time-series and dealing with perfusion series.

Although in many examples throughout nilearn the TR is written as a variable external to the dataset, where header information being wrong is "acceptable" (see [example here](https://nilearn.github.io/auto_examples/04_glm_first_level/plot_design_matrix.html#sphx-glr-auto-examples-04-glm-first-level-plot-design-matrix-py)), if users save files generated with nilearn to disk it'd be nice if header info was kept in sync with the underlying data.

what do you guys think?

Nilearn version: latest from git

### Expected behavior

Index img corrects pixdim of output files.

### Actual behavior

Index img keeps the pixdim from the input file.

### Steps and code to reproduce bug

```python
from nilearn import image, datasets
import numpy as np

data = datasets.fetch_adhd(n_subjects=1)["func"][0]
all_timepoints = image.load_img(data)
every_other_timepoint = image.index_img(all_timepoints, slice(None, None, 2))

tr =  all_timepoints.header["pixdim"][4]
double_tr = every_other_timepoint.header["pixdim"][4]

assert np.allclose(tr, double_tr / 2), f"index_img did not adjust TR. TR={tr}, double TR = {double_tr}"
```

**Comment by dangom** [comment]
Hi guys,

after some thought, I think it doesn't make too much sense to add a "target_tr" to index_img. A couple of reasons:

1. My original suggestion was to have index_img automatically guess user intent, but if the user has to manually adapt the TR, then they can do so after the fact.
2. I think this is part of a broader annoyance that could be one day fixed in the niftiImage class upstream in nibabel. The NiftiImage does not offer a simple way to query or modify the TR. Ideally Nifti1Image would expose that ( and also implement a __str__ that would print some basic info for sanity checking).

If that were the case than a user could do something in the likes of:

```
tag = image.index_img(asl_series, slice(None, None, 2))
tag.tr = asl_series.tr / 2
```

So I'll close this issue though I'm happy to implement a workaround if at least one more end user would consider this useful in nilearn. I'll also open one upstream to ask whether it makes sense for Nifti1Image to expose such parameters, or the reasoning why it doesn't do so yet.

**Comment by bthirion** [comment]
Fair enough. Thx for the discussion.
