### ISSUE TITLE
Bundle dependencies in `setup.py` or `info.py` file

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#2947]
I think it would be beneficial to combine the requirements-[*].txt files into a single file, with flags for the different dependency groups.

### Benefits to the change

Installation for developers would be simplified, since `nilearn` and its developer-specific dependencies could be installed in one step (e.g., `pip install -e .[all]` or `pip install -e .[test,doc]`). 

From a maintenance perspective, it may also be easier to manage one file instead of three.

We could put the requirements in the `setup.cfg` file ([as in `pybids`](https://github.com/bids-standard/pybids/blob/00ee1ecd2d986f150b95710072d019414769a35e/setup.cfg#L22-L68)), the `setup.py` file, or a new `info.py` file ([as in `tedana`](https://github.com/ME-ICA/tedana/blob/ab7afd80defafc86a4e4f27bd88dd2b32e499adb/tedana/info.py#L27-L62)).

### Pseudocode for the new behavior, if applicable

Current steps for developer installation:

```bash
git clone git@github.com:<your_username>/nilearn.git
conda create -n nilearn
conda activate nilearn
pip install . -e
pip install -r requirements-dev.txt
```

New steps:

```bash
git clone git@github.com:<your_username>/nilearn.git
conda create -n nilearn
conda activate nilearn
pip install .[dev] -e
```

**Comment by bthirion** [comment]
+1. I see no issue with that suggestion.

**Comment by tsalo** [comment]
Does anyone have a preference on where the requirements should go? I'm leaning toward using the `setup.cfg` based on @\effigies' packaging recommendations (https://gist.github.com/effigies/9bbb424535d6a1d838d6325191c0a736).

**Comment by bthirion** [comment]
No strong feeling on that. @NicolasGensollen WDYT ?

**Comment by GaelVaroquaux** [comment]
In general, it is better practice if dependencies are inspectable without
executing code.

I have some hope that the project.toml (PEP518) might be useful. However,
I have never tried using it, so I don't know what is the situation of the
technological pile, but I hope that it can be useful.

**Comment by tsalo** [comment]
At the moment, I think that pyproject.toml can only store the dependencies for the actual build, but my understanding may be out of date. If I'm correct, then setup.cfg sounds most in line with what you're saying, since it's a config file and not a script, unlike setup.py or info.py. Does that sound good?

**Comment by NicolasGensollen** [comment]
>No strong feeling on that. @NicolasGensollen WDYT ?

No strong feeling either. I had a look at various well known packages, and I have the feeling that there are as many strategies as packages to handle this... 
I'm OK with Taylor's suggestion of relying on `setup.cfg`, it seems like a clean way of doing it.
