### ISSUE TITLE
Add `cluster_threshold` option to `threshold_img`

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#2956]
I think there's a strong use-case for the ability to apply an arbitrary cluster-size threshold in `nilearn.image.threshold_img`.

This stems from https://neurostars.org/t/plot-stat-map-plot-only-clusters/20134, which I think would be solved by adding a `cluster_threshold` parameter to `threshold_img`.

A `two_sided` parameter would also probably be useful, but I can open a separate issue for that if necessary.

### Benefits to the change
The main benefit would be the ability to apply cluster-extent thresholding outside of a full statistical analysis (as in `threshold_stats_img`).

### Pseudocode for the new behavior, if applicable

```python
from nilearn import image

thresh_img = image.threshold_img(img, threshold=3.09, cluster_threshold=10)
```

**Comment by bthirion** [comment]
Looks like a cheap addition to me.  +1 If people want it.
