### ISSUE TITLE
Automatically commenting on opened PR

### ISSUE THREAD

**Issue by thomasbazeille** [nilearn/nilearn#2962]
Issue off-loaded from previous documentation PR : #2755.

### Topic

When a PR is opened, set-up an automatic comment to ask the contributor to make sure his PR and give informations that are important to structure the review process e.g. :

> Thank your for sending code in. Please make sure it is compliant with our contributing guidelines. Don't hesitate to ask questions early if needed.

> Until this PR is ready for review, you can include the [WIP] tag in its title, or leave it as a github draft. When you remove those, we will review it as quick as possible.

### Affected pages

Benefits :

- Would give a strong reminder to new and non-frequent contributors about our guidelines and where to find them
- Would likely help smoothen the review process

Cost : 

- Would require to set up a GH action, probably [auto-comment](https://github.com/marketplace/actions/auto-comment).

**Comment by tsalo** [comment]
Beyond the comment, should there be a checklist? Maybe something like the following?

- [ ] My PR has an interpretable title.
- [ ] My PR has at least one prefix indicating its purpose. For more information about recommended prefixes for nilearn, see...
- [ ] (For new features) There is at least one unit test for the proposed new feature.
- [ ] (For bug fixes) There is at least one test that would fail under the original bug conditions.
- [ ] My code is PEP8-compliant, to the best of my knowledge.

**Comment by thomasbazeille** [comment]
> Beyond the comment, should there be a checklist?

I like it too. I'm just worried about maintainability of such a checklist which will be a partial duplicate of the contributing guidelines. If we're confident its content will be pretty stable, I think it's ok to include a few broad points for high-priority checks. I think we should avoid getting into details though since they will have less impact and stability.

**Comment by thomasbazeille** [comment]
Let's rather discuss content and wording directly on the PR.
