### ISSUE TITLE
Consistency of signal related parameter defaults in `signal.clean` and `NiftiMasker`

### ISSUE THREAD

**Issue by htwangtw** [nilearn/nilearn#2985]
As title. Discovered this while working on #2946. There are some shared parameters related to signal processing in `NiftiMasker` and `signal.clean`. They have different default settings

Defaults in `NiftiMasker`:
```
...
standardize=False, standardize_confounds=True, detrend=False,
```
Defaults in `signal.clean`:
```
...
standardize='zscore',  standardize_confounds=True, detrend=True, 
```
Is there a reason why they are not the same?

**Comment by bthirion** [comment]
I think that `NiftiMasker` is general pupropose: it is often used to get the values of an image, and byd efault you don't want to standardize or detrend. By contrast, `signal.clean`  targets times series that you supposedly want to clean.
The discrepancy is thus OK to my eyes.

**Comment by htwangtw** [comment]
That makes sense. I will close this issue then!
