### ISSUE TITLE
Prevent user passing `standardize_confounds=False` with confound variables to `signal.clean` 

### ISSUE THREAD

**Issue by htwangtw** [nilearn/nilearn#2999]
While working on the test in #2946, I noticed there's no mechanism in place to prevent user from passing some illogical options, such as `standardize_confounds=False, detrend=False, standardize=False` and `standardize_confounds=False, detrend=False` when passing confound variables. When confound variables are present, they should always be demeaned or standardised.

### Benefits to the change

Reduce the chance of mistake for users who decided not to use the default parameters. 

### Pseudocode for the new behaviour, if applicable

I have thought of several ways:

1. Raise error when bad parameter combinations are passed to the function
2. Raise warning and fall back to default options
3. Warn the user without changing the provided parameters (proposed by @NicolasGensollen)

Here's a list of option combinations that should not be allowed in `signal.clean`.

|`standardize_confounds`|`detrend`|`standardize`|
|--|--|--|
|False|False|zscore|
|False|False|psc|
|False|False|False|

**Comment by NicolasGensollen** [comment]
Thanks for opening this @htwangtw !
I agree that combinations of these parameters that do not make sense should be made clear to the user. 
I would add a third possible solution which is to "just" warn the user without changing the provided parameters.

**Comment by bthirion** [comment]
I vote for 3.

**Comment by htwangtw** [comment]
3 it is.
