### ISSUE TITLE
node_size does not work as array-like for nilearn.plotting.plot_markers for "r" and "l" directions

### ISSUE THREAD

**Issue by LeSasse** [nilearn/nilearn#3012]
I think the nilearn.plotting.plot_markers function is not working as expected. Specifically when giving node size as an array-like it will not work for "r" and "l" directions because the marker_size length is not adjusted according to the relevant coordinates

Nilearn version:
nilearn==0.8.1

### Expected behavior
each node should be sized according to node_size

### Actual behavior
It will work as expected for directions "y" and "z".
however this will not work for "l" and "r" display direction.

I think this is because in display.add_markers() under

```python
elif direction == 'l':
        relevant_coords = (xcoords <= 0)
        xdata = xdata[relevant_coords]
        ydata = ydata[relevant_coords]
```
you do not select the correct index from marker_size based on the relevant coordinates.

Traceback (most recent call last):
  File "04_plot_pareto_scores.py", line 92, in <module>
    brain = plotting.plot_markers(
  File "/home/leonard/.venvs/Gradient-Identification/lib/python3.8/site-packages/nilearn/plotting/img_plotting.py", line 1429, in plot_markers
    display.add_markers(
  File "/home/leonard/.venvs/Gradient-Identification/lib/python3.8/site-packages/nilearn/plotting/displays.py", line 1081, in add_markers
    display_ax.ax.scatter(xdata, ydata, s=marker_size,
  File "/home/leonard/.venvs/Gradient-Identification/lib/python3.8/site-packages/matplotlib/__init__.py", line 1361, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/leonard/.venvs/Gradient-Identification/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 4507, in scatter
    raise ValueError(
ValueError: s must be a scalar, or float array-like with the same size as x and y

### Steps and code to reproduce bug
The below code should reproduce the faulty behaviour.

It will do as desired for display mode "yz", but throw the beforementioned error for display mode "lyrz".

```python
#!/usr/bin/env python3

import matplotlib.pyplot as plt
from nilearn import plotting
from nilearn import datasets
import numpy as np

# get some coords
power = datasets.fetch_coords_power_2011()
coords = np.vstack((power.rois['x'], power.rois['y'], power.rois['z'])).T

# node strength
node_strength = np.random.rand(264,)
node_sizes = np.random.rand(264,)*50

brain = plotting.plot_markers(
    node_strength,
    coords,
    node_vmin=0,
    node_vmax=1,
    node_size=node_sizes,
    node_cmap = "rainbow",
    display_mode="lyrz"
)
plt.show()


```

**Comment by bthirion** [comment]
Sorry, I have a hard time reproducing the bug on my box, but your your case is certainly valid... it looks like you have identified the fix. Can you open a PR ?
Best,

**Comment by LeSasse** [comment]
Yeah sure!
