### ISSUE TITLE
A proposal to reorganize Maskers and I/O functions

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#3014]
Per discussion in #2946 and last week's developers call, we are thinking about restructuring how certain classes and functions, especially Masker objects, are organized in nilearn. We want to ensure that the community has the ability to provide feedback before we make any changes.

The first issue is that the module name `input_data` is somewhat ambiguous. Therefore, we propose creating a new module, `maskers`, which would contain all Masker objects, including volumetric (i.e., the existing `NiftiMasker`s) and potential future surface maskers. This would remain distinct from the `masking` module, which contains functions for creating and operating on masks.

Secondly, #2946 will introduce a new function for loading fMRIPrep-generated confounds for use with Maskers or in GLMs. We defaulted to placing this in `input_data`, but, should we rename that module to `maskers`, the new function will no longer fit. We are considering a new `interfaces` module, which would contain submodules dedicated to external tools (e.g., fMRIPrep), specifications (e.g., BIDS, NIDM), etc. These submodules would then contain functions and classes used to ingest or write out files associated with each tool. For example, the new function would be located at `nilearn.interfaces.fmriprep.load_confounds`.

Finally, given that some users have expressed an interest in using image-loading functions currently in the private `_utils` module, we are also considering creating a new `io` module for input/output operations. Some functions that would end up in that function are `nilearn._utils.load_niimg`, `nilearn.image.load_img`, and `nilearn.image.get_data`.

Any proposed changes that we actually implement will go through a lengthy deprecation cycle, so please don't expect any breaking changes in the next couple of releases.

**Comment by pbellec** [comment]
I think the proposed organization makes a lot of sense overall. Couple thoughts.

It looks like proposed content for `io` is really for image io, with other `io` functions living in `interfaces`. If that's indeed the intended use case it may be better to use `image_io`.

I am concerned that users discovering the project structure will be left wondering what the difference is between `masker` and `masking`. I am not sure what the solution is, and maybe it is not an actual problem. An option may be to have maskers live in `image_io`.

**Comment by NicolasGensollen** [comment]
After discussions during the core-devs meeting of yesterday, we seem to converge towards the following organization:

- Creation of a new module ``interfaces``.
- Move all ``load_confounds`` utilities, recently added to ``input_data``, to ``interfaces.fmriprep`` (**must be done before next release**).
- Creation a new module ``maskers``.
- Move all maskers from ``input_data`` to ``maskers``.
- Keep imports in ``input_data``  for backward compatibility.
- Keep all masking utilities in the ``masking`` module (no change).

This will result in the following:

```python
from nilearn.input_data import NiftiMasker # deprecated but will still work 
# will become
from nilearn.maskers import NiftiMasker
# and
from nilearn.input_data import fmriprep_confounds  # will not work anymore
# will become
from nilearn.interfaces.fmriprep import fmriprep_confounds
```

**Comment by htwangtw** [comment]
Should we remove `fmriprep` from the function name of `fmriprep_confounds` and `fmriprep_confounds_strategy`, as it's already in the import path?

```python3
from nilearn.interfaces.fmriprep import confounds   # or `load_confounds` to make it more explicit
from nilearn.interfaces.fmriprep import confounds_strategy  # or `load_confounds_strategy` 
```

**Comment by NicolasGensollen** [comment]
@htwangtw I had the same interrogation when writing the imports above, it feels a little redundant to have fmriprep twice indeed...

**Comment by pbellec** [comment]
The name of function/class is also featured in the code.

For `NiftiMasker`, apart from backwards compatibility, it makes for much readable code to have `Masker` in the name, even if it's imported from the `masker` module.

In the case of `confounds` I think it is readable enough without `fmriprep`. `load_confounds` is even better IMO. 

If ever multiple `confounds` (or `load_confounds`) emerged one day, say with bids, it would be easy to do 

``` 
from nilearn.interfaces import fmriprep
conf1 = frmriprep.load_confounds('fmriprep_confounds.tsv')

from nilearn.interfaces import bids
conf2 = bids.load_confounds('bids_confounds.tsv')
``` 
one could even `from nilearn.interfaces.fmriprep import load_confounds as fmriprep_confounds` if necessary.
