### ISSUE TITLE
Passing a 4D image to `SecondLevelModel` 

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#3058]
See this [Neurostars post](https://neurostars.org/t/nilearn-second-level-error-img-slicer/20659)

When passing a 4D image to `SecondLevelModel.fit()`, no error is raise although the documentation says that possible input values are either a list of `FirstLevelModel`, a list of images, or a pandas dataframe. When computing contrasts, this raises the following error:

```
TypeError: Cannot slice image objects; consider using `img.slicer[slice]` to generate a sliced image (see documentation for caveats) or slicing image array data with `img.dataobj[slice]` or `img.get_fdata()[slice]
```

which occurs when indexing the inputs here:

https://github.com/nilearn/nilearn/blob/5a740b1ce92da9c646cb6812f559ed73c2036f43/nilearn/glm/second_level/second_level.py#L124-L128

Nilearn version: 0.8.2.dev

### Steps and code to reproduce bug

```python
import pandas as pd
from nilearn.image import load_img
from nilearn.glm.second_level import SecondLevelModel
from nilearn.datasets import fetch_localizer_contrasts

n_samples = 16
data = fetch_localizer_contrasts(["left vs right button press"], n_samples,
                                 get_tmaps=True)
# This will fail:
# cmap_filenames = load_img(data.cmaps)
# This will work:
cmap_filenames = data.cmaps
design_matrix = pd.DataFrame([1] * n_samples, columns=['intercept'])
second_level_model = SecondLevelModel().fit(cmap_filenames, design_matrix=design_matrix)
z_map = second_level_model.compute_contrast(output_type='z_score')
```

### Fix

If 4D images are allowed, update the docs and fix the indexing. Otherwise raise an error when checking the inputs in `fit`

**Comment by bthirion** [comment]
Thx ! Maybe there was a reason for not accepting 4D images, but I can't remember this right now...

**Comment by Remi-Gau** [comment]
Would be tempted to be conservative and since contrasts cannot be computed on 4D at the moment, I would not allow 4D as inputs.

We can extend the scope of valid inputs later if users want it.

**Comment by Remi-Gau** [comment]
OK but I guess if we intend to support that for volumetric data then I should allow it for surface data as part of #4715
