### ISSUE TITLE
nilearn.plotting overrides the matplotlib backend, causing troubles on remote SSH development

### ISSUE THREAD

**Issue by RaphaelMeudec** [nilearn/nilearn#3063]
I am working on a remote settings, accessing a machine (drago/margaret for INRIA context) through a PyCharm Remote Interpreter.
I have been struggling to display nilearn figures in the scientific view of PyCharm, leading to a painful process of saving the image => rsync figures dir => visualize figures once there are on personal laptop.

I did a simple experiment drawing first a simple `plot(list(range(10)))` which is displayed and then a nilearn figure which does not show up (script at the end of the issue).

I found out the reason for this, which is that in `nilearn.plotting.__init__`, the matplotlib backend is set to `agg` if not in `[inline, agg]`, but the backend used initially (which is working for me) is `module://backend_interagg`.

Setting the backend to the initial value after importing `nilearn.datasets` fixes the problem.

I don't know exactly how those matplotlib backends work, if the list of accepted backends in `nilearn.datasets.__init__` could be extended or if we could have a more robust list of valid matplotlib backend. Also, I feel that nilearn shouldn't override matplotlib backend silently? 

Nilearn version: 0.7.1

### Expected behavior

Nilearn does not override matplotlib backend silently.

### Actual behavior

Nilearn sets backend to "agg" if not in ["inline", "agg"], causing trouble with remote SSH development.

### Steps and code to reproduce bug

Run the following script through SSH remote interpreter

```python
import matplotlib
initial_backend = matplotlib.get_backend().lower()
print(initial_backend)

import matplotlib.pyplot as plt
import numpy as np

arr = np.zeros((100, 100))
plt.figure()
plt.plot(list(range(10)))
plt.show()
# >> The show is displayed in PyCharm

from nilearn import datasets, plotting
print(matplotlib.get_backend().lower())
# >> Backend has switched to "agg"

sample_brain_map = datasets.fetch_neurovault_motor_task().images[0]
plotting.plot_stat_map(
    sample_brain_map,
    threshold=3,
    title="Before setting back the backend",
)

plt.show()
# >> Does not show up

matplotlib.use(initial_backend)
plotting.plot_stat_map(
    sample_brain_map,
    threshold=3,
    title="After setting back the backend",
)

plt.show()
# >> Shows up

```

**Comment by NicolasGensollen** [comment]
Thanks for opening this @RaphaelMeudec 

Linking the relevant part of the code:

https://github.com/nilearn/nilearn/blob/6fa1359d2ca9e8174e10f48a54d747a6382c6144/nilearn/plotting/__init__.py#L32-L38

As well as #2560 where some explanations for this can be found.

I believe there are two things here:

- Changing the backend silently is confusing for users
- Should we change the list of "authorized" backends to cover this use case

For the first point, I think that adding a warning when we change the backend would be useful. At least, users wouldn't have to spend hours understanding why their plots don't show up. 

For the second point, I'm less sure because this was added intentionally to avoid annoying failures at the end of scripts ran remotly as pointed out by @GaelVaroquaux in #2560.

Maybe we could add some way to configure a bypass for this, such that users who know what they're doing could setup nilearn to always use whatever backend they have? WDYT?

**Comment by RaphaelMeudec** [comment]
I would say if nilearn isn't silent anymore, it will easily guide users to eventually get back to a specific backend.

For the 2nd point, could it be possible to make sure that matplotlib isn't going to crash because of X server (according to @GaelVaroquaux's comment [here](https://github.com/nilearn/nilearn/issues/2560#issuecomment-682333518)), and if it is not crashing, accept the mpl backend even if it is not in [inline, agg]?

**Comment by GaelVaroquaux** [comment]
> For the 2nd point, could it be possible to make sure that matplotlib isn't going to crash because of X server (according to @GaelVaroquaux's comment here), and if it is not crashing, accept the mpl backend even if it is not in [inline, agg]?

Do you have a technical solution for that?

We could probably expand the list of backends known to be robust.

**Comment by RaphaelMeudec** [comment]
@jeromedockes I don't think this is a solution for what Gael is pointing out: if you set an incompatible backend in your matplotlibrc file, you can still have errors that show up only when you run plt.show()

**Comment by jeromedockes** [comment]
> What about forcing an early call to matplotlib.pyplot.switch_backend(matplotlib.get_backend())?

yes `switch_backend` does more checks but still it would be nice if we could describe more precisely and reproduce the error we are trying to address with this check

**Comment by RaphaelMeudec** [comment]
@GaelVaroquaux do you have precise examples of matplotlib errors that new users could have and show up on .show() only? We've been trying to generate some with @jeromedockes but did not succeed.

We think we could drop this custom matplotlib check as matplotlib has increased its own checks. But if you're not convinced, we can simply switch the current function to a call to `switch_backend` + add a warning for the user about the mpl backend switch. WDYT?

**Comment by RaphaelMeudec** [comment]
I started implemeting the fix on [this branch](https://github.com/RaphaelMeudec/nilearn/commit/4512da9bacecee01de6782c23f2b69f0a9f737d5). But my problem is that when I try to add some tests to it, I can't find any case where the error isn't caught by matplotlib.

Also I would not advise to use `plt.switch_backend` but rather stick to `matplotlib.use` as the switch_backend methods also [silently switch to default backends](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/pyplot.py#L239-L258), and users would still not be alerted about this.

**Comment by NicolasGensollen** [comment]
>I would not advise to use `plt.switch_backend` but rather stick to `matplotlib.use`

Isn't `use` calling `switch_backend` under the hood?

here : https://github.com/matplotlib/matplotlib/blob/9765379ce6e7343070e815afc0988874041b98e2/lib/matplotlib/__init__.py#L1139-L1147

**Comment by RaphaelMeudec** [comment]
It's a good point that you raised it, because if users import pyplot before nilearn.plotting, that will trigger the `switch_backend` method and hence silently switch the matplotlib backend. So I guess the best way to check whether or not we should raise the warning is to check backend value before and after calling `matplotlib.use`.

**Comment by NicolasGensollen** [comment]
>I guess the best way to check whether or not we should raise the warning is to check backend value before and after calling `matplotlib.use`.

You mean something like this:

```python
current_backend = matplotlib.get_backend().lower()
# Assume use() will handle errors and warnings
matplotlib.use(current_backend)
new_backend = matplotlib.get_backend().lower()
if new_backend != current_backend:
    warnings.warn(f"Backend changed to {new_backend}...")
```

I think that this would be the best approach indeed, but I'm not sure you'll be able to test the warning easily, will you?

**Comment by RaphaelMeudec** [comment]
This would change the behaviour of the `_set_mpl_backend` from setting default to agg to raising errors potentially. I'm not sure it goes with the spirit of the method (allowing new users not to be blocked by mpl backend stuff). 

To do so, maybe we could go for:

```python
current_backend = matplotlib.get_backend().lower()
# Assume use() will handle errors and warnings
try:
    matplotlib.use(current_backend)
except:
    matplotlib.use("Agg")
new_backend = matplotlib.get_backend().lower()
if new_backend != current_backend:
    warnings.warn(f"Backend changed to {new_backend}...")
```

WDYT?

For the testing part, maybe I could mock the `get_backend` calls to make sure the warning appear. Eventually, maybe mock the `.use` method to trigger an error? (I'm not sure that's possible?)

**Comment by bthirion** [comment]
> WDYT?

Sounds reasonable to me.

**Comment by jeromedockes** [comment]
That sounds good, although as we still haven't been able to reproduce the error we cannot be sure that this is necessary, nor that it is enough to fix it. mocking get_backend and use is definitely possible. One detail: I would maybe catch something more specific, at least `except Exception`
