### ISSUE TITLE
First Level From BIDS Refactoring

### ISSUE THREAD

**Issue by smeisler** [nilearn/nilearn#3068]
I'd like to request a few updates to `nilearn.glm.first_level.first_level_from_bids`

A good dataset that is applicable to both of the below changes is here: https://openneuro.org/datasets/ds003604/versions/1.0.4

1) The ability to treat different sessions separately as opposed to combining them into a single design matrix. This could take the form of making different matrices per session, or adding a session-coded covariate to the composite design matrix.
2) Adding robustness for different acquisition labels, given the same session, task, and run labels (see below for an example):
![image](https://user-images.githubusercontent.com/27028726/142661529-8a8deed9-5f8e-42ca-9381-ff988376ac96.png)
As you can see there are two acquisition for this subject in `ses-5`, `task-Gram`, `run-2`. This raises an error in `first_level_from_bids` even though it is technically BIDS valid.

### Benefits to the change
1) This could be more applicable to interventional or longitudinal studies.
2) More robust and in agreement with BIDS validity.

**Comment by NicolasGensollen** [comment]
Great! Thanks for opening the issue @smeisler :+1:

**Comment by Remi-Gau** [comment]
Note that with #3525 it should be possible to model a single session:

```python
models, m_imgs, m_events, m_confounds = first_level_from_bids(
                        bids_path, 'main',
                        space_label='MNI',
                        img_filters=[('ses', '01'), 
                                     ('desc', 'preproc')])  
```

or for a specific entity amongst (["acq", "ce", "dir", "rec", "echo", "res", "den"]):

```python
models, m_imgs, m_events, m_confounds = first_level_from_bids(
    dataset_path=bids_path,
    task_label="main",
    space_label="MNI",
    img_filters=[("desc", "preproc"), ("acq", "D1S8")],
)
```

**Comment by Remi-Gau** [comment]
For reference.

Sessions in BIDS do not automatically mean that data were acquired on different days, information regarding when a session or a run were acquired are contained within scans.tsv and sessions.tsv.

So I would very cautious regarding adding "an easy option" to "add a session-coded covariate to the composite design matrix" and I would definitely not make it a default.

**Comment by andreaboscutti** [comment]
I have another potential suggestion regarding the ability to access sessions with more granularity. The img_filters=[('ses', '01')] works great, but in some instances, a user may want to select specific subsets of sessions for different subjects. This would require some refactoring of the BIDS-related functions. I’d be happy to contribute if this is considered a useful addition.
