### ISSUE TITLE
Adding a vmin option to plot_stat_map plot_glass_brain functions

### ISSUE THREAD

**Issue by rvarrier** [nilearn/nilearn#3084]
Hi,
I see that there have been a couple of related issues in the past requesting a "vmin" parameter for the plot_stat_map and/or plot_glass_brain functions (e.g. [this](https://github.com/nilearn/nilearn/issues/2165) and [this](https://github.com/nilearn/nilearn/issues/1149)), and was wondering if this has been implemented/is being worked on. 

### Benefits to the change
While the current implementation (only one half of the spectrum for positive/negative values alone) is a great way to ensure that positive/negative activations maintain their separate colors, it will be very helpful to get the whole color spectrum (within a desired vmin/vmax) to present other data (e.g. timepoints at which certain events occur) . This is especially important if the data is skewed (i.e., several nodes have very low/high values). Example below:

![image](https://user-images.githubusercontent.com/17010698/145492472-4a94c696-0789-4d48-840d-8f5862f5cae5.png)

I'd like to get the whole range of the colormap 'viridis' on the brainmap - i.e., from dark blue to yellow, such as is possible with seaborn heatmaps (example below): 
![image](https://user-images.githubusercontent.com/17010698/145493301-a2b3e35a-dd49-49be-92a9-fb15f88d427b.png)

The suggested solutions that I found so far - setting symmetric_cbar to False or using the plot_img function instead of the ones  mentioned above won't suffice unfortunately.

Thanks in advance!

**Comment by bthirion** [comment]
Thx for bringing this back.
Note that in plot_stat_map, it is hard to see the lowest values, in a non-sparse setting, because the region with low values are masked visually by regions with high values.  
This being said, I don't remember well why we haven't kept the vmin argument. Maybe @jeromedockes remebers ?
Best,

**Comment by jeromedockes** [comment]
As mentioned by @bthirion  in both linked issues, for the case of `plot_stat_map`, using `plot_img` instead does suffice.
```python
from nilearn import plotting, datasets
plotting.plot_img(datasets.load_mni152_template(), colorbar=True, vmin=.5)
```

![plot_img](https://user-images.githubusercontent.com/9196501/145842570-2fccc231-96a2-4081-a682-aa4e7dd78c47.png)


For the case of `plot_glass_brain`, I agree there is a bug: there is a `vmin` parameter but it is ignored and its documentation is incorrect. We can start to implement its description and possibly add a `symmetric_cmap` parameter as in the `view_img` function

> Note that in plot_stat_map, it is hard to see the lowest values, in a non-sparse setting, because the region with low values are masked visually by regions with high values.

do you mean `plot_glass_brain` ?

**Comment by rvarrier** [comment]
Thank you for the replies! plot_img unfortunately doesn't seem to work when there are negative values in the range - for example, the data ranges from -.32 to 3, so the symmetric_cmap parameter switches back to True, as a result of which the vmin parameter is also ignored (see screenshot below).

![image](https://user-images.githubusercontent.com/17010698/145854264-55ece50a-36fb-49be-a317-4507fa123f00.png)

**Comment by jeromedockes** [comment]
The screenshot uses `view_img`. `plot_img` always allows setting any `vmin`:
```python
from nilearn import plotting, datasets
img = datasets.fetch_neurovault_motor_task()["images"][0]
plotting.plot_img(img, colorbar=True, vmin=-.5)
```

![plot_img_1](https://user-images.githubusercontent.com/9196501/145856704-ae9a2067-0d6f-49ed-828a-391faa8f48af.png)

**Comment by jeromedockes** [comment]
we could remove the check that forces the cmap to be symmetric in view_img when there are negative values, as symmetric_cmap=True is the default

**Comment by bthirion** [comment]
I think that this comes from historical reasons, but I indeed think that `plot_img_on_surf` shoudl accept a vmin argument.

**Comment by jeromedockes** [comment]
bthirion ***@***.***> writes:

> I think that this comes from historical reasons, but I indeed think that `plot_img_on_surf` shoudl accept a vmin argument.

I agree. ATM it relies on `plot_surf_stat_map`, it would have to use
`plot_surf` instead. A `symmetric_cmap` argument, true by default (as in
`view_surf` and `plot_surf`) would also proably have to be added.
