### ISSUE TITLE
`fetch_atlas_harvard_oxford` returns same object for `maps` and `filename`

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#3088]
This is also true for `fetch_atlas_juelich` since they both share the same internal logic.
`maps` should indeed be the `Nifti1Image`, but we should either remove `filename` or change it to be the path to the `Nifti1Image`.

Also, this is the only fetcher which returns a `Bunch` object without a `description`.

```python
from nilearn import datasets
b = datasets.fetch_atlas_harvard_oxford("cort-maxprob-thr0-1mm")
assert b.maps == b.filename
b.filename
```
```
<nibabel.nifti1.Nifti1Image at 0x7f1ff37a4280>
```
```python
b.maps
```
```
<nibabel.nifti1.Nifti1Image at 0x7f1ff37a4280>
```

**Comment by RaphaelMeudec** [comment]
From what I understand, the atlas image is loaded [here](https://github.com/nilearn/nilearn/blob/e1c2f8bd9cd22d9cce9028bb3a56ac7df73810b5/nilearn/datasets/atlas.py#L408) from the `_get_atlas_data_and_labels`.

The solution to expose the atlas filename would be to also return the filename defined [here](https://github.com/nilearn/nilearn/blob/e1c2f8bd9cd22d9cce9028bb3a56ac7df73810b5/nilearn/datasets/atlas.py#L584) in the `_get_atlas_data_and_labels` method.

Does that seem a fair solution to you? I might improve the according tests as well in the process.

**Comment by bthirion** [comment]
Sounds right.
