### ISSUE TITLE
Stop warning that `GLM` module is experimental

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#3097]
Since Nilearn 0.7.0, we have a warning saying that `nilearn.glm` is experimental and might be subject to change, as well as some warnings here and there in the docs.
Since we are about to reach 0.9.0, it could be time to remove these warnings.
There is no explicit end to these warnings though, so we can probably keep them a little longer if needed.
WDYT?

**Comment by bthirion** [comment]
Thx. I'd go for another cycle.

**Comment by alexisthual** [comment]
It's almost been a year now, maybe we could silence them :relaxed:
