### ISSUE TITLE
Replace installation HTML file with sphinx-tabs extension

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#3107]
I am looking to update the installation instructions as part of #2953, and working with HTML instead of MarkDown is a little difficult. I believe that the [sphinx-tabs](https://sphinx-tabs.readthedocs.io/en/latest/) extension could be used to replace the HTML file.

### Affected pages

- `introduction.rst` (https://nilearn.github.io/stable/introduction.html#installing-nilearn)

**Comment by NicolasGensollen** [comment]
I haven't looked in details, but I think `install_doc_components.html` does a few things, like pre-selecting the tab corresponding to your OS, which might not be possible with sphinx-tab (not sure though....).

**Comment by jeromedockes** [comment]
if it simplifies things I think it's ok to have a slightly less fancy display -- eg the same tabs for all OSes is fine; even not having tabs at all is acceptable IMO

**Comment by alexisthual** [comment]
I was working on the doc too, and came across [`sphinx-design`](https://sphinx-design.readthedocs.io/en/furo-theme/). It provides nice tabs for sphinx, among other things (like cards and buttons) and I thought we could be interested in adding this dependency :relaxed:

**Comment by bthirion** [comment]
No experience with it, but sounds reasonable. Thx,

**Comment by jeromedockes** [comment]
Might become part of #3122
