### ISSUE TITLE
Installation instructions are not suited to ubuntu 12.04

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#311]
2 problems:

- The "pre" flag does not seem to exist in old versions of pip

- When the package installs, it spits out a few errors/warnings that look ugly.

<pre>
$ pip install -U --pre --user nilearn
Usage: /usr/bin/pip install [OPTIONS] PACKAGE_NAMES...

/usr/bin/pip install: error: no such option: --pre

$ pip install -U --user nilearn
Downloading/unpacking nilearn
  Downloading nilearn-0.1a1.tar.gz (614Kb): 614Kb downloaded
  Running setup.py egg_info for package nilearn
    
    package init file 'nilearn/data/__init__.py' not found (or not a regular file)
    package init file 'nilearn/plotting/glass_brain_files/__init__.py' not found (or not a regular file)
    package init file 'nilearn/tests/data/__init__.py' not found (or not a regular file)
Installing collected packages: nilearn
  Found existing installation: nilearn 0.1-git
    Uninstalling nilearn:
      Successfully uninstalled nilearn
  Running setup.py install for nilearn
    package init file 'nilearn/data/__init__.py' not found (or not a regular file)
    package init file 'nilearn/plotting/glass_brain_files/__init__.py' not found (or not a regular file)
    package init file 'nilearn/tests/data/__init__.py' not found (or not a regular file)
    
Successfully installed nilearn
</pre>

**Comment by AlexandreAbraham** [comment]
Should we release it soon?

**Comment by GaelVaroquaux** [comment]
> Should we release it soon?

I think that we should: we should merge the few pending PRs that are
almost ready, and release.

**Comment by GaelVaroquaux** [comment]
I am closing this as fixed. It no longer belong to our tracker.
