### ISSUE TITLE
masker.generate_report doesn't center on ROI if overlaid on functional data

### ISSUE THREAD

**Issue by walkerped** [nilearn/nilearn#3110]
When using masker.generate_report(), if no functional data is given ROIs are plotted on the MNI template, and the cursor centers on one of the ROIs. However, if the masker is first fit to functional data, ROIs are plotted on the functional data, but the cursor does not center on any of the ROIs. If the atlas happens to fall outside of where the cursor is, you cant see any of the ROIs and can't tell if the alignment is good or not.

Nilearn version: 0.8.0

### Expected behavior
Figure generated by masker.generate_report() be centered somewhere on atlas, so alignment can be judged.

### Actual behavior
When functional data is used as the underlay, cursor is always at y=17, x=19, z=56, whether the atlas is visible in those slices or not.

![image](https://user-images.githubusercontent.com/63321511/147000740-44c08967-2f27-450f-9d74-82af79bd2596.png)

### Steps and code to reproduce bug
ROI attached, but I am not able to share functional image - any functional in MNI space should work.
```python
# load nilearn harvard oxford atlas
atlasI = nimg.load_img('/autofs/cluster/neuromod/personal_folders/walker_pedersen/BNSTmni/MNI152_T1_1mm-RBNST.nii.gz', dtype=int)
labelL = ['Background','RBNST']
# load atlas into masker
masker = input_data.NiftiLabelsMasker(
            atlasI, labels=labelL, standardize=False,
            verbose=0, detrend=False)
# visualize atlas ROIs
masker.fit()
report1 = masker.generate_report()
masker.fit(cleanI)
report2 = masker.generate_report()
```
[MNI152_T1_1mm-RBNST.nii.gz](https://github.com/nilearn/nilearn/files/7758303/MNI152_T1_1mm-RBNST.nii.gz)

**Comment by bthirion** [comment]
It sounds like the reason is that when a functional image, we determine the cut coords to best display the functional image.
It seems reasonable to revert to the same default as when  no image is used, given that the focus is not the functional data as such.

**Comment by walkerped** [comment]
Yeah, this sounds like it would be a helpful change.

**Comment by bthirion** [comment]
Do you want tot try and implement it ?
