### ISSUE TITLE
`image.load_img` unbearably slow?

### ISSUE THREAD

**Issue by dangom** [nilearn/nilearn#3112]
At my end nilearn image's `load_img` is almost 4 orders of magnitude slower than nibabel's `load` on a fresh install.

Nilearn version:

Latest on pip -> 0.8.1

### Expected behavior
`image.load_img` adds no noticeable overhead over nibabel's load.

### Actual behavior
`image.load_img` takes seconds instead of microseconds.

### Steps and code to reproduce bug

```sh
base ❯ conda --version
conda 4.11.0
base ❯ conda create -n ni python=3
base ❯ conda activate ni
ni ❯ pip install nilearn nibabel
ni ❯ python -m timeit -n 3 -s "from nilearn import image" 'image.load_img("bold.nii.gz")'
3 loops, best of 5: 6.36 sec per loop
ni ❯ python -m timeit -n 3 -s "import nibabel as nib " 'nib.load("bold.nii.gz")'
3 loops, best of 5: 885 usec per loop
```

```python
Python 3.10.1 | packaged by conda-forge | (main, Dec 22 2021, 01:39:03) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from nilearn import image
>>> image.__file__
'/Users/dangom/anaconda3/envs/ni/lib/python3.10/site-packages/nilearn/image/__init__.py'
>>> import nilearn
>>> nilearn.__version__
'0.8.1'
>>> import nibabel as nib
>>> nib.__file__
'/Users/dangom/anaconda3/envs/ni/lib/python3.10/site-packages/nibabel/__init__.py'
>>> nib.__version__
'3.2.1'
```

**Comment by dangom** [comment]
It seems the issue arises from calls to `image.load_img` being redirected to `nilearn._utils.concat_niimgs` where the data is actually loaded into memory and used to create a nifti object by calling `nilearn.image.new_img_like`. In contrast, nibabel lazy loads the nifti, such that later calls to get_data() will pay the load price (which is paid upfront by nilearn).
It doesn't seem like there is any way to have `image.load_img` lazy load images currently.

Since very now and then we may want to check the header or size of an image, or use its affine without having to load the data into memory directly, it'd be nice if image.load_img would default to lazy instead.

**Comment by GaelVaroquaux** [comment]
One of the reason for this complex architecture is to make the code
robust to many situations (giving the same output for a variety of
different inputs). This does make it harder to optimize.

Of course, I think that seeking optimization and improvements is a good
thing. However, we should keep in mind that falling back to
case-specific, lower-level nibabel should always be an option for the
more advanced user.

**Comment by dangom** [comment]
Right, that makes sense. I was also, wrong, the point where data is loaded when passing in a single string is here in [`load_img`](https://github.com/nilearn/nilearn/blob/570bf9efdbbc1b6ff9bd6db435b89b3906149f28/nilearn/_utils/niimg.py#L134):

```python
    if isinstance(niimg, str):
            # data is a filename, we load it
            niimg = nibabel.load(niimg)
            ...

   dtype = _get_target_dtype(_get_data(niimg).dtype, dtype)

    if dtype is not None:
        # Copyheader and set dtype in header if header exists
        if niimg.header is not None:
            niimg = new_img_like(niimg, _get_data(niimg).astype(dtype),
                                niimg.affine, copy_header=True)
            niimg.header.set_data_dtype(dtype)
        else:
            niimg = new_img_like(niimg, _get_data(niimg).astype(dtype),
                                niimg.affine)

```

Instead of having a call to `_get_data(niimg).dtype` we could have a call to `niimg.dataobj.dtype`. This would postpone loading the data unless an actual type conversion is required, or until it is used later on.
Would this make sense?

**Comment by GaelVaroquaux** [comment]
> Instead of having a call to _get_data(niimg).dtype we could have a call to niimg.dataobj.dtype.

Sounds like a great improvement indeed!
