### ISSUE TITLE
warn instead of raising error when affines differ (`math_img`)

### ISSUE THREAD

**Issue by dangom** [nilearn/nilearn#3115]
have two images, A and B, that are in the same space, but some of their affine entries differ by ~ 10^-7.  I'm still trying to sort that out, but I take that happens because of one them is the result of a registration that concatenates multiple transforms, so I imagine that affine difference is numerical error being propagated around.

In any case, if I try to multiply them with `image.math_img`, I'm not allowed because math_img only allows multiplying images where affines are all close.
I see why this is so, and how much that saves people from doing wrong things, but given this is python, maybe math_img could raise a warning instead of outright raising an error? Or maybe we could deactivate the checks by passing a ignore_fov=True flag?
Or even better, check for FOV differences by setting a distance limit in mm (say 1 micron), instead of on floating precision of the affine matrix?

### Benefits to the change
Avoid false positive errors.

**Comment by bthirion** [comment]
If anything, I'd be in favor of an `ignore_affine` flag that would be set to False by default. I don't want the library to take decisions based on hard-coded thresholds.

**Comment by jeromedockes** [comment]
Isn't it a bit of an edge case to justify adding an option to the
function signature? `math_img` is just for convenience and if it doesn't
work it is very easy to replace it with `get_data` then `new_img_like`.
So I wonder how often users will find out about and use the "ignore
affine" option.

If we add an option, for consistency we may want to check if it should
be done for other functions that may have a similar issue eg
`concat_imgs`.

Re. transforming the error into a warning, if the affines are really
different the function cannot do its job properly so raising an
exception is appropriate. also, quite often we don't read the warnings
attentively enough :)

**Comment by dangom** [comment]
It is definitely an edge case. It's the first time this happened to me, so I don't know how often people would come across this in the wild. As you point out, not sure a change in function signature makes sense, but replacing with get_data and new_img_like seems like overkill to overcome the current limitation.

With that said, searching through the repo I see there was already a [PR in the works](https://github.com/nilearn/nilearn/pull/2802/files) that proposed changing the affine compat. threshold to 10-9 from the current np.allclose.

**Comment by jeromedockes** [comment]
> replacing with get_data and new_img_like seems like overkill to overcome the current limitation.

I think it is simple enough, for the use case described in this issue
(multiplying 2 images) it is just:

  prod_img = new_img_like(img1, get_data(img1) * get_data(img2))

which is not much more complicated than

  prod_img = math_img("img1 * img2", img1=img1, img2=img2)

So using that instead of math_img in a situation that doesn't arise too
often seems acceptable.

**Comment by dangom** [comment]
I agree. I'll close this issue for now.
