### ISSUE TITLE
Move BIDS- and FSL-related functions from `_utils` to `interfaces` module

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#3118]
There are three functions in `nilearn._utils.glm` that I think could be moved to the new `nilearn.interfaces` module:

- [`nilearn._utils.glm.get_bids_files()`](https://github.com/nilearn/nilearn/blob/276959dd98d8ec6d2997680c0a5a9669e5c4d124/nilearn/_utils/glm.py#L338)
- [`nilearn._utils.glm.parse_bids_filename()`](https://github.com/nilearn/nilearn/blob/276959dd98d8ec6d2997680c0a5a9669e5c4d124/nilearn/_utils/glm.py#L434)
- [`nilearn._utils.glm.get_design_from_fslmat()`](https://github.com/nilearn/nilearn/blob/276959dd98d8ec6d2997680c0a5a9669e5c4d124/nilearn/_utils/glm.py#L479)

All three are user-facing functions, but since they're in the `_utils` module I believe the consensus is that they can be moved without issue.

This is related to #3014.

### Benefits to the change

Moving these functions would help fill out the new `interfaces` module, and would ensure that they stay relatively stable for users.

**Comment by bthirion** [comment]
Thx for the suggestion. Sounds reasonable to me.
