### ISSUE TITLE
Make `normalize_matrix_on_axis` and `orthonormalize_matrix` public or private

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#3121]
In file `nilearn/mass_univariate/permuted_least_squares.py`, these two functions look as if they are public but aren't exposed and included in the API docs: 

https://github.com/nilearn/nilearn/blob/78b09866b71c532552fd49e5cfd383db65b457b9/nilearn/mass_univariate/permuted_least_squares.py#L15-L27

We should either add them, or rename them with a "_" prefix.

**Comment by bthirion** [comment]
In my understanding, these functions are not meant to be made public. We should rename them.
