### ISSUE TITLE
Scipy deprication warning from `RegionExtractor`

### ISSUE THREAD

**Issue by htwangtw** [nilearn/nilearn#3129]
Warning message:
```
<decorator-gen-7>:2: DeprecationWarning: scipy.sparse.linalg.cg called without specifying `atol`. 
The default value will be changed in a future release. For compatibility, specify a value for `atol` explicitly, e.g., ``cg(..., atol=0)``, or to retain the old behavior ``cg(..., atol='legacy')``
```
Can trace to this line
https://github.com/nilearn/nilearn/blob/db596cbed3ccba56328453bd15cfd29ba05d7c04/nilearn/_utils/segmentation.py#L343

I am not sure what's the magnitude of impact of this. Can try to have a look.

**Comment by bthirion** [comment]
I would simply use `atol='legacy'`
