### ISSUE TITLE
Inconsistent behaviour of `inverse_transform()` in masker classes 

### ISSUE THREAD

**Issue by htwangtw** [nilearn/nilearn#3132]
Under the hood, `nilearn.masker.NiftiMasker` uses `nilearn.masking.unmask` to inverse transform the signal to image, and for `nilearn.masker.NiftiLabelMasker` it uses `nilearn.regions.signal_extraction.signals_to_img_labels`. There are some inconsistency on how to handle signal transformed from one nifti image.

`nilearn.masking.unmask` treats 1-d array as one session / one nifti image (?) automatically:
https://github.com/nilearn/nilearn/blob/1607b52458c28953a87bbe6f42448b7b4e30a72f/nilearn/masking.py#L900-L910

`nilearn.regions.signal_extraction.signals_to_img_labels` forces users to pass a 2-d array, no matter what:
https://github.com/nilearn/nilearn/blob/39d5ee4a1067486b3d0d72c70352bf0b1ac182fa/nilearn/regions/signal_extraction.py#L136-L148

This results in the `inverse_transform()` method behaving slightly differently and is potentially confusing for user who has used both type of maskers. It might not be a problem for data that was all processed with nilearn. We only ran into this issue when trying to plot some output from a DL model. 

Would it be useful to make sure there's some consistency? It might worth looking into other masker objects?

cc'd @anirudhk686

**Comment by bthirion** [comment]
Thx @htwangtw for raising this ! 
Yes, we probably have to look at all maskers in parallel to find how to design a more consistent API.  But this will probably lead to deprecation cycles.

**Comment by tsalo** [comment]
This seems related to #2724 and #2726.

**Comment by htwangtw** [comment]
> This seems related to #2724 and #2726.

This is fantastic! Glad some discussion has already happened and there seems to be an PR #2725
