### ISSUE TITLE
API of `nilearn.decomposition`

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#3138]
The `decomposition` module only exposes `CanICA` and `DictLearning` currently: https://nilearn.github.io/dev/modules/reference.html#module-nilearn.decomposition

Here are a list of objects that we should either add to the public API or rename to make it clear that they are private (we would also rename `base.py` into `_base.py`):

- `MultiPCA`

https://github.com/nilearn/nilearn/blob/c123b6126ef36dd5a08c20b780b773a80278b907/nilearn/decomposition/multi_pca.py#L13-L17

- `fast_svd`

https://github.com/nilearn/nilearn/blob/c123b6126ef36dd5a08c20b780b773a80278b907/nilearn/decomposition/base.py#L27-L29

- `mask_and_reduce`

https://github.com/nilearn/nilearn/blob/c123b6126ef36dd5a08c20b780b773a80278b907/nilearn/decomposition/base.py#L85-L92

- `BaseDecomposition`

https://github.com/nilearn/nilearn/blob/c123b6126ef36dd5a08c20b780b773a80278b907/nilearn/decomposition/base.py#L233-L237

- `explained_variance`

https://github.com/nilearn/nilearn/blob/c123b6126ef36dd5a08c20b780b773a80278b907/nilearn/decomposition/base.py#L539-L544

**Comment by bthirion** [comment]
I think I would rather make them private, given that we would otherwise need a great documentation effort for functions that are maybe not so meaningful for users.
`mask_and_reduce` maybe is useful enough to be made public.
