### ISSUE TITLE
Add notes about ICBM template and the relationship with fMRIprep default template

### ISSUE THREAD

**Issue by htwangtw** [nilearn/nilearn#3140]
It is not clear that the default template used by fMRPrep (https://github.com/templateflow/tpl-MNI152NLin2009cAsym) is the ICBM template.
This need to be make clear in the doc string.

### Affected pages

https://nilearn.github.io/modules/generated/nilearn.datasets.fetch_icbm152_2009.html#nilearn.datasets.fetch_icbm152_2009

Edit: wrong template flow link

**Comment by htwangtw** [comment]
After reading a bit more in detail, I found that the version in nilearn is not exactly the same as fMRIprep:
| | fmriprep | nilearn|
|-|-|-|
|Symmetric?| Asymmetric | Symmetric|
|Version?| c | a|

I also found out there's redundancy in the structural image.
The MNI template data in `nilearn.datasets` are the same one fetching from osf in `nilearn.datasets.fetch_icbm152_2009`.
Good news is nilearn is using the latest iteration of MNI152, not the old one shipped in FSL, but not the  most up to date one
Do we want to consider update / trim down the current data shipped in nilearn?
This is not going to have a huge impact when it comes to plotting, but for tissue segmentation it might be. I am not an expert on this one, please feel free to chip in.

Here's probably the cleanest summary of all the different template derived from MNI152 dataset: 
http://nist.mni.mcgill.ca/atlases/

**Comment by bthirion** [comment]
We have changed the template less than a year ago, so I think it is not a huge issue. But we should warn users ('the ICB template image will be changed in the  release R from XXX to YYY').
