### ISSUE TITLE
Add note for new `maskers` module in examples

### ISSUE THREAD

**Issue by NicolasGensollen** [nilearn/nilearn#3158]
In release `0.9.0` we moved all maskers from the `input_data` to the `maskers` module and updated the docs and examples accordingly. However, users with a nilearn version `< 0.9` reading the examples on the website might get confused when getting an error saying that the maskers module does not exist if they just copy paste the code.

See this [Neurostars post](https://neurostars.org/t/no-module-named-nilearn-maskers-nilearn-9-4-6/21467).

We should probably add a note in these examples saying that users should either upgrade to `>= 0.9`, or import `maskers` from `input_data`.

WDYT?

**Comment by alexisthual** [comment]
Maybe an [admonition note](https://pradyunsg.me/furo/kitchen-sink/demo/#admonitions) at the top of these examples would do the trick?

**Comment by bthirion** [comment]
+1 for warning. We should do it post-release fix quickly enough.

**Comment by NicolasGensollen** [comment]
I agree that adding a note at the top of all examples using a masker somewhere would be great.

I was thinking of adding something like this:

```rst
.. note::
 
     If you are using Nilearn with a version older than ``0.9.0``,
     then you should either upgrade your version or import maskers
     from the ``input_data`` module instead of the ``maskers`` module.
 
     That is, you should manually replace in the following example
     all occurences of:
 
     .. code-block:: python
 
         from nilearn.maskers import NiftiMasker
 
     with:
 
     .. code-block:: python
 
         from nilearn.input_data import NiftiMasker

```

But I don't want to copy-paste this into all the examples using maskers because there are quite a few, and it will be painful to maintain these notes afterwards.

So, I was aiming at having this note written once (for example in a file `examples/masker_note.rst`), and simply add an ``include`` directive in the relevant examples:

```python
"""
Example title
===========

Description of the example....

.. include:: ../masker_note.rst

"""

###############################
# Section 1
# ---------
# ....
```

But when trying this, it seems like the include doesn't work as expected (the note basically doesn't show up).

I'm probably missing something trivial here... :sweat: 

Any idea @alexisthual ?

**Comment by alexisthual** [comment]
I am not sure, but it could be that `sphinx-gallery` builds an rst file from your example and places it at a location where the relative path to `masker_note.rst` is no longer valid.
I think you should have a look at this rst file to gain some insight :slightly_smiling_face:

**Comment by NicolasGensollen** [comment]
Thanks for your reply @alexisthual ! 🥇 
You are right, I was linking relative to source files instead of the generated ones... 😓 
Seems to work fine, I'll submit a PR to add this note !

**Comment by glemaitre** [comment]
I arrive a bit late to the party after the ping of @bthirion
Discussing with @lesteve, the example should be generated from the `auto_examples` folder and thus a relative link might do the trick. Otherwise a copy/pasting of the note :)
