### ISSUE TITLE
`permuted_ols` and `non_parametric_inference` are not well documented

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#3159]
`permuted_ols` actually works for one-sample tests, which is not documented.
Also, the outputs are only -log_10( corrected_p_values), which is a bit limited too. It is also ill-documented.

**Comment by emdupre** [comment]
I'd guess we want to update [this page](https://nilearn.github.io/modules/generated/nilearn.mass_univariate.permuted_ols.html) and [this one](https://nilearn.github.io/modules/generated/nilearn.glm.second_level.non_parametric_inference.html), as well as (optionally) the linked examples. 


Other instances worth reviewing:
- [Searchlight user guide](https://nilearn.github.io/stable/decoding/searchlight.html#comparing-to-massively-univariate-analysis-f-score-or-spm)

**Comment by tsalo** [comment]
I also think there could be more information in the documentation about the differences between `permuted_ols`/`non_parametric_inference` and other multiple comparisons correction approaches (e.g., `threshold_stats_img` and `cluster_level_inference`).

**Comment by bthirion** [comment]
No, we can correct p-values, but we should not correct z-values to avoid confusing users imho.

**Comment by tsalo** [comment]
What other outputs would be useful? It would be great to have some kind of signed statistics, so users don't have to get the sign of the t-statistics and then multiply the -log10 p-values by those signs.

**Comment by bthirion** [comment]
But we have the option to do a signed test, do we ?
This being said, I agree that signed statistics would be handy.

**Comment by tsalo** [comment]
That's true, but the -log10 p-values are not signed, so users need to extract the signs from the t-statistic map.

What about adding an `output_type` parameter, as in `SecondLevelModel.compute_contrast`?

`permuted_ols` should be able to output parameter estimate (`effect_size`), variance (`effect_variance`), uncorrected t-statistic (`stat`), and uncorrected -log10 p-values (`p_value`), along with corrected -log10 p-values (additionally split based on the measure used for correction, in #3181).

**Comment by bthirion** [comment]
Note that currently, as p-values, we return p-values not -log10 p-values. I'd try to be consistent with that.
By contrast, it's OK to return  corrected -log10 p-values, since this is what we do for non-parametric inference.

**Comment by tsalo** [comment]
Now that the TFCE and cluster-level PRs have been merged, `permuted_ols` can return the following outputs:

- `t`
- `logp_max_t`
- `h0_max_t`
- `tfce`
- `logp_max_tfce`
- `h0_max_tfce`
- `size`
- `logp_max_size`
- `h0_max_size`
- `mass`
- `logp_max_mass`
- `h0_max_mass`

Is there anything else we want to return? Do we want to add `effect_size` and `effect_variance`?

**Comment by bthirion** [comment]
The documentation has not been reworked (e.g. the fact that it works for one-sample test).

**Comment by tsalo** [comment]
Oh right, I forgot about that. Thanks for clarifying. So we just need an example or other documentation covering a one-sample test in `permuted_ols`.
