### ISSUE TITLE
`fetch_abide_pcp` returns empty results

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#3160]
since #2829 `fetch_abide_pcp` returns empty results. This is due to the fact that the filters applied to phenotypic data expect this array to contain `bytes`: https://github.com/nilearn/nilearn/blob/1ebf6b70d79d88e6c3de6d9799c79309c6c99277/nilearn/datasets/func.py#L974  as this is what `np.recfromcsv` returns but it is now `str` since `pd.read_csv` is now used: https://github.com/nilearn/nilearn/blob/1ebf6b70d79d88e6c3de6d9799c79309c6c99277/nilearn/datasets/func.py#L1000

**Comment by bthirion** [comment]
... This kind of issue is not capture by tests, right ?

**Comment by jeromedockes** [comment]
> ... This kind of issue is not capture by tests, right ?

It should but the test only tests `fetch_abide_pcp(quality_checked=False)` (the default is `quality_checked=True`):
https://github.com/nilearn/nilearn/blob/1ebf6b70d79d88e6c3de6d9799c79309c6c99277/nilearn/datasets/tests/test_func.py#L285

**Comment by bthirion** [comment]
Thx for  raising it !
