### ISSUE TITLE
Don't always scale background maps when  plotting surfaces

### ISSUE THREAD

**Issue by alexisthual** [nilearn/nilearn#3169]
Users very often use background maps to generate better looking surface images.

However, here are two points which I think are confusing regarding the API for background maps:
1. `bg_map` will be used only if `bg_on_data` is set to `True`.
I find this redundant. Why not assume `bg_on_data` is `True` when `bg_map` is not `None`?
2. [`plotting.plot_surf()` automatically scales `bg_map`s to have values in [0, 1]](https://github.com/nilearn/nilearn/blob/e1c2f8bd9cd22d9cce9028bb3a56ac7df73810b5/nilearn/plotting/surf_plotting.py#L388-L391), which prevents generating [images where sulci and gyri are distinguished by using two different tones of gray](https://mne.tools/stable/_images/sphx_glr_30_cluster_ftest_spatiotemporal_001.png).
See an example below of how this could be achieved in `nilearn` if `bg_map`s were not scaled

### Suggested changes

1. deprecate `bg_on_data`
2. add `scale_bg_map`.
It would default to `True`, in which case the current scaling method would be applied.
In case it is set to `False`, `bg_map` would be used as is.

### Example illustrating the need to not always scale `bg_map`

```python
import matplotlib.pyplot as plt
from nilearn import datasets, plotting, surface
import numpy as np

# %% Load fsaverage5
fs5 = datasets.fetch_surf_fsaverage()

# %% Load sulc surface from fsaverage
sulc = surface.load_surf_data(fs5.sulc_left)
# Create binary map indicating sulci and gyri
sulc_sign = (np.sign(sulc) + 1) / 4

# %% Load random contrast map
motor_images = datasets.fetch_neurovault_motor_task()
surf = surface.vol_to_surf(motor_images.images[0], fs5.pial_left)

# %% Current default usage for bg_map
plotting.plot_surf(
    fs5.infl_left,
    surf,
    bg_map=sulc,
    bg_on_data=True,
)
plt.show()

# %% Try plotting binary tones for sulci and gyri
plotting.plot_surf(
    fs5.infl_left,
    surf,
    bg_map=sulc_sign,
    bg_on_data=True,
)
plt.show()
```

![Screenshot from 2022-02-20 15-50-50](https://user-images.githubusercontent.com/13835654/154848517-f29f30af-b8e9-4565-822c-d3f413b81e40.png)
![Screenshot from 2022-02-20 15-50-58](https://user-images.githubusercontent.com/13835654/154848522-19a9c49d-ced3-4d5f-b217-1d9d6c6546b7.png)

**Comment by bthirion** [comment]
You mean that you want to deprecate `bg_on_data` ?
Makes sense to me. I'd like to hear the opinion of @jeromedockes though.
OK also for the `scale_bg_map` argument.

**Comment by alexisthual** [comment]
> You mean that you want to deprecate `bg_on_data` ?

I want to remove this kwarg, as it seems to me that we can safely assume that `bg_on_data` is False when there is no `bg_map`, True otherwise. But maybe I am missing something!

**Comment by bthirion** [comment]
Agreed, but I think there is  typo in your above comment ("deprecate `bg_map`")

**Comment by alexisthual** [comment]
> Agreed, but I think there is typo in your above comment ("deprecate `bg_map`")

Ooops, my bad, you are right :slightly_smiling_face: I just edited this

**Comment by jeromedockes** [comment]
In all cases the background map is shown in the thresholded regions. `bg_on_data` also shows it in the non-thresholded parts by mixing it with the actual statistical map data. so we cannot assume `bg_on_data=True` whenever a bg map is provided; I think in most cases users will want `bg_on_data=False` because it modifies the colors representing the statistical data (note this is not offered in other surface or volume plotting functions)

I agree it would be very useful to have a way to prevent scaling the bg map

If you add it could you also check how this behaviour compares to the other surface plotting functions (view_surf and plot_surf with engine="plotly") and if these need to be updated to? I'm sorry I may not have a lot of time to look into it in detail during the next couple of weeks

**Comment by alexisthual** [comment]
Also, it seems to me that `engine="plotly"` in `plot_surf()` doesn't handle well `bg_on_data=True` as illustrated in images generated in #3171.
I'll investigate this later.
