### ISSUE TITLE
Allow for subject as a file filter in first_level_from_bids

### ISSUE THREAD

**Issue by walkerped** [nilearn/nilearn#3175]
It would be nice to be able to use subject as a filter variable for first_level_from_bids, to have it set up a first level GLM for just that subject. Often we run one subject at a time, as they are collected.  In addition, I like to send a job for each subject to our cluster, so they can be run in parallel, so that would help with this as well.

### Benefits to the change

More easily allow people to run one subject at a time, so subjects can be analyzed and evaluated as data is collected, to make it easier to split jobs per subject for cluster computing, and to allow for selecting one subject to reprocess if necessary.

### Pseudocode for the new behavior, if applicable

```python

```

**Comment by bthirion** [comment]
I'm +1 for that. Should not be too hard.

**Comment by erdalkaraca** [comment]
Seems to have some overlap with https://github.com/nilearn/nilearn/issues/3068
