### ISSUE TITLE
Conda install nilearn

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#318]
Conda handles dependencies better than pip so we could submit nilearn here. It would be easier to install for non-technical people.

**Comment by AlexandreAbraham** [comment]
Solved itself. `conda install -c=conda-forge nilearn`

**Comment by lesteve** [comment]
Should we advertise this in the doc, basically as single way to install nilearn?
```
conda install --channel conda-forge nilearn
```

Minor details:
* the way nibabel has been configured in conda-forge, it will install pydicom and h5py, which are optional dependencies in principle.
* I probably need to do something to have 0.2.5 available in conda-forge

**Comment by GaelVaroquaux** [comment]
> Should we advertise this in the doc, basically as single way to install nilearn?

Why? Pip works, why confuse users?

**Comment by AlexandreAbraham** [comment]
> I probably need to do something to have nilearn 0.2.5 available in conda-forge

https://conda-forge.github.io/#update_recipe

Basically, we just have to do a PR to increment a version number somewhere.

> Why? Pip works, why confuse users?

I would like to know if there is any benefit in using conda-forge. If not, we may advertise not to use it as we do not control the diffusion. If, during a tutorial, somebody uses anaconda to install nilearn and does not have the right version, I can't imagine what will happen if he uses pip on top of that to upgrade it.

**Comment by lesteve** [comment]
> I would like to know if there is any benefit in using conda-forge. If not, we may advertise not to use it as we do not control the diffusion

It looks like you are not aware of it: I am the one behind this ... it did not magically "fix itself".

**Comment by AlexandreAbraham** [comment]
No, I did not looked a the commits and, in conda-forge, I've seen a lot of packages that seems migrated automatically from pypi though an automated script. Also, I've missed a lot of team meetings recently ;).

OK, so, in that case, it's already in good hands.

**Comment by GaelVaroquaux** [comment]
You know, I wish that we would stick to pip. It's a community solution, that is the official one of Python. It has its limitations, but these are slowly addressed over time, with a documented process where everyone can discuss and improve things. These things have vastly improved in the last few years, with wheels, and now manylinux wheels.

From a pragmatic perspective, advertising conda as a way to install nilearn means that for people not under anaconda, it won't work. Hence we'll confuse users more.

**Comment by lesteve** [comment]
> From a pragmatic perspective, advertising conda as a way to install nilearn means that for people not under anaconda, it won't work. Hence we'll confuse users more.

Since we are telling users to use Anaconda in most cases I'd rather have them use conda when they can and pip when they have to. Having said that, I agree it is a tough one so let's keep the instructions as they are.

**Comment by GaelVaroquaux** [comment]
> Since we are telling users to use Anaconda in most cases I'd rather have them
> use conda when they can and pip when they have to.

We're telling users that don't have an install of Python to install
Anaconda.

Many users already have an install of scientific Python, especially in
neuroimaging institution, where sysadmins maintain a Python, and compiled
tools --AFNI, FSL, BrainVisa, or local tools-- linked to Python. Telling
users to install something new basically means nuking their install.

Everywhere that I have taught, the local sysadmin was maintaining an
install of Python. Only once (at Telecom) was it Anaconda.

**Comment by lesteve** [comment]
> Many users already have an install of scientific Python, especially in neuroimaging institution, where sysadmins maintain a Python, and compiled tools --AFNI, FSL, BrainVisa, or local tools-- linked to Python. Telling users to install something new basically means nuking their install. 

> Everywhere that I have taught, the local sysadmin was maintaining an install of Python. Only once (at Telecom) was it Anaconda.

Makes sense.
