### ISSUE TITLE
permuted_ols only returns h0_fmax for first regressor

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#3180]
When there is more than one regressor in `tested_vars`, `permuted_ols` returns only the null distribution of maximum t-statistics for the first regressor.

Here is the relevant code:

https://github.com/nilearn/nilearn/blob/e7804ebe858349781674c0d2b5c78e27afb52fa1/nilearn/mass_univariate/permuted_least_squares.py#L512

Nilearn version: `main` as of e7804ebe858349781674c0d2b5c78e27afb52fa1.

### Expected behavior

When `n_regressors` is >1, I would expect `h0_fmax` to have that number of rows.

### Actual behavior

`h0_fmax` is a 1D array, with one element per 

### Steps and code to reproduce bug

Here is some code, adapted from one of the permuted_ols tests, that should reproduce the bug.

```python
from sklearn.utils import check_random_state
from nilearn.mass_univariate import permuted_ols

random_state = 0
rng = check_random_state(random_state)

# design parameters
n_samples = 50
n_descriptors = 10
n_regressors = 2
n_covars = 2
n_perm = 10

# create design
target_vars = rng.randn(n_samples, n_descriptors)
tested_vars = rng.randn(n_samples, n_regressors)
confounding_vars = rng.randn(n_samples, n_covars)

neg_log10_pvals, own_scores, h0_fmax = permuted_ols(
    tested_vars,
    target_vars,
    confounding_vars,
    model_intercept=False,
    n_perm=n_perm,
    random_state=random_state,
)
assert own_scores.shape == (n_regressors, n_descriptors)
assert neg_log10_pvals.shape == (n_regressors, n_descriptors)
assert h0_fmax.shape == (n_regressors, n_perm)
# AssertionError, assert (10,) == (2, 10)
```

**Comment by bthirion** [comment]
But the problem is that the permutation scheme we use is invalid if we are to test several covariates (the error rate will not be controlled jointly for the two or more tests if we do them concurrently, because the model will test against a global null).
I think we should document the problem clearly, making this  a documentation issue.

**Comment by tsalo** [comment]
Should it just not support multiple `tested_vars` then? It seems like it should have a single `tested_var` and anything else should go into `confounding_vars`.

**Comment by bthirion** [comment]
Sorry, my comment above was wrong, because test_vars are tested independetly.
But then you're right, the output of the model is wrong, `p_values` shoudl have shape `(n_regressors, n_descriptors)`
