### ISSUE TITLE
Unclear documentation regarding `min_distance` in `reporting.get_clusters_table`

### ISSUE THREAD

**Issue by RaphaelMeudec** [nilearn/nilearn#3199]
The method `nilearn.reporting.get_clusters_table` which extracts peak statistics from an image accepts an argument which is `min_distance` described as "minimal distance between subpeaks in mm".

I find this docstring a bit confusing as the minimal distance is applied at the cluster-level and not at the image level. This results in a dataframe where peaks can actually be closer than `min_distance` if they belong to different clusters. 

Maybe this nuance was implied in the use of "subpeaks" instead of "peaks", but my opinion is that it should be a bit more explicit. WDYT?

Relevant portion of code [here](https://github.com/nilearn/nilearn/blob/1607b52458c28953a87bbe6f42448b7b4e30a72f/nilearn/reporting/_get_clusters_table.py#L234)

**Comment by bthirion** [comment]
PR welcome ;-)
