### ISSUE TITLE
Pass binary mask to `sample_masks` instead of indices

### ISSUE THREAD

**Issue by htwangtw** [nilearn/nilearn#3204]
> Just wondering: wouldn't it be more handy to give  a binary vector with length `n_scans` for  `sample_mask` ?

_Originally posted by @bthirion in https://github.com/nilearn/nilearn/pull/3193#discussion_r838897961_

I did some archaeology and found out why I implemented index, rather than binary vector. I think it was for staying consistent to the OG `sample_mask`:

>I had a look at the relevant code of `sample_mask` application for resolving #2777. Currently, the timeseries censoring is done in the `base_masker` module:
https://github.com/nilearn/nilearn/blob/4cdd8fe8aad085d21e5d8367ad5b94d8efbe5151/nilearn/input_data/base_masker.py#L71-L73

_Originally posted by @htwangtw in https://github.com/nilearn/nilearn/issues/1012#issuecomment-847064092_

And the old doc of `sample_mask`:
https://github.com/nilearn/nilearn/blob/4cdd8fe8aad085d21e5d8367ad5b94d8efbe5151/nilearn/input_data/nifti_masker.py#L172-L177

Here's all the back ground info I can find. We can change it to binary vector as we no longer use the `index_img` function, and is using `signal.clean` to handle things. Let me know how you think we should move forward, given these info. 

cc @pbellec as I know you raised the same question before.

**Comment by ymzayek** [comment]
Hi @htwangtw is this still feasible for you to do this week? If not just let me know, thanks!

**Comment by htwangtw** [comment]
Yes! should be ready to review by next week :)
