### ISSUE TITLE
Examples using FIAC dataset should have a better design matrix

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#3208]
Currently, the design matrices used to analyse the FIAC dataset are just numpy arrays. They should become full-fledged dataframes with meaningful column names
See e.g. in #3191
```
design_files = [data['design_matrix1'], data['design_matrix2']]
design_matrices = [pd.DataFrame(np.load(df)['X']) for df in design_files]
```

**Comment by tsalo** [comment]
It looks like there already was an issue about this: #2400.

**Comment by bthirion** [comment]
Sorry. Closing, then.
