### ISSUE TITLE
Add "add changelog entry" to auto-comment PR template

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#3218]
I think it would be great to add an item about adding a whatsnew/changelog entry to the checklist in the [auto-comment workflow](https://github.com/nilearn/nilearn/blob/0eb1340212c6db5aac07ae31b3061bde5c9f7432/.github/workflows/auto-comment.yml).

I am primarily requesting this because I often forget to add a whatsnew entry, and have to be reminded by my PRs' reviewers.

**Comment by NicolasGensollen** [comment]
I agree and it would be nice to also explain briefly the conventions we use for these entries (put the entry in the appropriate category, use a single line per entry, the entry should finish with the link to the PR and to the author's profile, for new contributors add their profile to `doc/changes/names.rst`, etc...)

**Comment by RaphaelMeudec** [comment]
I guess a simple way to add it to the CI would be [this Github Actions](https://github.com/marketplace/actions/verify-changed-files) which checks whether some files were changed or not. We could simply check if latest.rst has been modified.

**Comment by NicolasGensollen** [comment]
@RaphaelMeudec I think a first easy step would just be to add a line in the PR TODO list to remind contributors to write a what's new (I believe this is basically what @tsalo was suggesting).
We could do something fancier to automatically validate or not the addition of a what's new entry (the GitHub Action you suggested seems like a good tool for this indeed...).
The only problem I see with this, is that for some PRs (typically fixing typos or the CI) we don't currently add entries as this is not super interesting for users and it would add a lot of complexity to the logs.
