### ISSUE TITLE
`0.9.1` tests fail with 4 Assertion Errors in `nterfaces/fmriprep/tests/test_load_confounds.py`

### ISSUE THREAD

**Issue by TheChymera** [nilearn/nilearn#3232]
This is the full build and test log: https://ppb.chymera.eu/4a909d.log
The values seem to be off by quite a bit. Any idea what could be wrong?

**Comment by htwangtw** [comment]
It's likely due to how we simulated a short time series as test data. 

https://github.com/nilearn/nilearn/blob/932eee9c69cd8fbf40ee6af5cee77f8f93b25da3/nilearn/interfaces/fmriprep/tests/test_load_confounds.py#L46-L55

I will have a look soon.

**Comment by sanjayankur31** [comment]
We're also seeing these 4 fail on Fedora builds, but only for certain arches: s390x, ppc64le, aarch64. So I've skipped these tests on these arches for the time being. These tests pass on x86_64 and i686.

**Comment by htwangtw** [comment]
@sanjayankur31 what's the python version you are running the test on?

**Comment by sanjayankur31** [comment]
This is on Python 3.10 currently.

**Comment by htwangtw** [comment]
These tests didn't change between the two versions so I wouldn't expect any changes. Still, thanks for letting me know!

**Comment by sanjayankur31** [comment]
Yeh, the same tests fail on the same arches on Fedora rawhide (37): aarch64, s390x, ppc64le.
Here's a test build with logs:

https://koji.fedoraproject.org/koji/taskinfo?taskID=86638657

And here's one on F36 with armv7hl also enabled:

https://koji.fedoraproject.org/koji/taskinfo?taskID=86643728

**Comment by htwangtw** [comment]
Currently the length of the simulated signal is 300 volumes. 
I can try two things: 
1. increase the length of the simulated signal
2. investigate the collinearity in the simulated signal mixture and start from there...
@sanjayankur31 I will let you know if I will need your help with testing!

**Comment by sanjayankur31** [comment]
Sure, sounds good :+1:

**Comment by Remi-Gau** [comment]
This refers to a fairly old issue and we do not seen to still have the problem on more recent version so I will close.

reopen if you feel otherwise
