### ISSUE TITLE
'list' object cannot be interpreted for cut_coords in plot_roi

### ISSUE THREAD

**Issue by garincle** [nilearn/nilearn#3238]
Using the function 

plotting.plot_roi(atlas, view_type = "contours", bg_img=None, display_mode='z', cut_coords=[0, 20, 40, 60], annotate=False)

### Actual behavior
TypeError: 'list' object cannot be interpreted as an integer

When using  plot_stat_map  cut_coords=[0, 20, 40, 60], it works.

```python

```

**Comment by bthirion** [comment]
Thx. Here is a snippet to reproduce the bug:
```
from nilearn import datasets
from nilearn import plotting
dataset_ho = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm')
atlas = dataset_ho.filename
plotting.plot_roi(atlas, view_type = "contours", bg_img=None, display_mode='z', cut_coords=[0, 20, 40, 60], annotate=False)
```

**Comment by jeromedockes** [comment]
I'm surprised we didn't run into that one before. Something like this should fix it:
```diff
diff --git a/nilearn/plotting/displays/_slicers.py b/nilearn/plotting/displays/_slicers.py
index 6c02131b7..b19704808 100644
--- a/nilearn/plotting/displays/_slicers.py
+++ b/nilearn/plotting/displays/_slicers.py
@@ -1311,7 +1311,8 @@ class BaseStackedSlicer(BaseSlicer):
         if img is None or img is False:
             bounds = ((-40, 40), (-30, 30), (-30, 75))
             lower, upper = bounds['xyz'.index(cls._direction)]
-            cut_coords = np.linspace(lower, upper, cut_coords).tolist()
+            if isinstance(cut_coords, numbers.Number):
+                cut_coords = np.linspace(lower, upper, cut_coords).tolist()
         else:
             if (not isinstance(cut_coords, collections.abc.Sequence) and
                     isinstance(cut_coords, numbers.Number)):
```

(btw note  contours without a background image will probably not be super useful -- but the bug occurs also with a background image)

**Comment by garincle** [comment]
I would, but I have no idea how to do that correctly. If someone walk me through I would be happy to learn.

**Comment by bthirion** [comment]
Does the following help ?
https://github.com/nilearn/nilearn/blob/main/CONTRIBUTING.rst
If you feel it's too hard, simply let us know, somebody will take that one.
Best,

**Comment by garincle** [comment]
yeah, this is not a good time for me to dive into that (but I need to do it!). I will try to learn a bit more before I can contribute if that's ok?

**Comment by bthirion** [comment]
Sure.
