### ISSUE TITLE
CI service discussion

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3239]
This concerns opening a discussion around the use of CircleCI as our CI platform for documentation building and whether we should consider GitHub Actions. We should think about the pros and cons of each and see whether we can test GitHub Actions. Also just a note, we found out from talking to a circleci associate that there is an open-source version that we qualify for that should give us enough credit to run our build.

**Comment by ymzayek** [comment]
The circleci plan has been downgraded to the open-source version which indeed gives us way more than enough credits monthly to use the CI, however I noticed that full builds on main are getting canceled after 1 hour again. After looking into it a bit, it seems that all free plans, regardless of the amount of credit they provide, have a time limitation of 1h. I emailed a circleci associate to confirm and also inquire about any possible solutions from their end. 

Reference: https://support.circleci.com/hc/en-us/articles/4410707277083-Context-deadline-exceeded-after-1-hour-Build-timed-out-Free-tier-only-

I'm not sure I see a solution around this if we can't increase the time limit. I don't think the solutions proposed in the reference are of use to our workflow (using a larger resource class or parallelism). WDYT?

I will update when I hear back from circleci support. In the meantime, I can look into using GitHub Actions.

**Comment by bthirion** [comment]
Thx. I had forgotten about the 1hr limit. If need be, we can get back to the paid plan.

**Comment by ymzayek** [comment]
Another option is to mirror what scikit-learn does. They moved documentation building to github actions and use circleci to trigger the workflow and host the artificats. 
See https://github.com/scikit-learn/scikit-learn/pull/21137

**Comment by ymzayek** [comment]
I discussed this with one of the scikit learn developers and it seems worth it to get a profile of the build and see if we can optimize before deciding to migrate the CI. What I know is that a build takes ~1h37 if data is already downloaded and ~2h with downloading the data so we can already cut ~23min if we do the data download step as a separate job preceding a full build. 
Then there is still quite some time to cut to get it under an hour. I'm not sure how big of a job this would be. Has someone already done some kind of profiling or have some idea of what functions or examples are might be taking up the most amount of time? If not, this is what I'll do next.

Some things to think about is also that we already wanted to clean up our examples and get rid of some datasets so this aligns with this approach. Also having a faster doc build would be nice. But I also understand that it may not be possible to slim it down enough to meet CircleCI limits while still maintaining our rich documentation. I guess this would be due to difficulties optimizing long-running functions in our examples.

**Comment by bthirion** [comment]
Thx for these useful points.
Well, we've tried to compress the running time of the examples as far as possible. I think it will be hard to do much better (but I may be wrong).  I think that the way fw is to remove the most costly examples.
What is the problem with CI migration ? is it overly complex ? Just asking, I have no experience with it.

**Comment by ymzayek** [comment]
I was advised against it as a first solution if it can be avoided due to unforeseen difficulties that can pop up. So I just wanted to look at other options even if we might up needing to do it in any case. 

I did profile the build and from a general overview I can see that the example `nilearn/examples/02_decoding/plot_haxby_full_analysis.py` alone takes 20 minutes to finish particularly because of a loop that calls `decoder.fit()` method many times each of which takes about 25s. I wonder for instance if this example can be run in a more minimal way.

**Comment by bthirion** [comment]
Fair enough ! 
We might have to remove this example bzw.

**Comment by ymzayek** [comment]
Some of the next examples in terms of length are:

- `02_decoding/plot_haxby_different_estimators.py`: ~5m

And then there are a lot running for about 3min:

- `06_manipulating_images/plot_extract_rois_smith_atlas.py`: ~3m20s
- `07_advanced/plot_localizer_mass_univariate_methods.py`: ~3m20s
- `02_decoding/plot_haxby_glm_decoding`: ~3m20s
- `02_decoding/plot_haxby_frem.py`: ~3m10s
- `05_glm_second_level/plot_oasis.py`: ~2m50s
- `07_advanced/plot_age_group_prediction_cross_val`: ~2m50s

I suggest the next steps to be opening a PR to remove the 20m example and perhaps removing or simplifying some of these listed here and then another PR to separate the data downloading step.

**Comment by bthirion** [comment]
Thx for looking at it. Some examples will be hard to compress, we may want to remove them if their added value is limited.

**Comment by alexisthual** [comment]
> I did profile the build and from a general overview I can see that the example `nilearn/examples/02_decoding/plot_haxby_full_analysis.py` alone takes 20 minutes to finish particularly because of a loop that calls `decoder.fit()` method many times each of which takes about 25s. I wonder for instance if this example can be run in a more minimal way.

[In the current docs](https://nilearn.github.io/stable/auto_examples/02_decoding/plot_haxby_full_analysis.html#sphx-glr-auto-examples-02-decoding-plot-haxby-full-analysis-py), it seems that this example takes 3min 40s to build, is it because the machine we build the docs on is better than the CI machines?
![Screenshot from 2022-10-07 11-07-09](https://user-images.githubusercontent.com/13835654/194517466-67a75a83-4d40-49d5-afa3-53bf6328029a.png)

**Comment by ymzayek** [comment]
@alexisthual I noticed this yesterday and also noticed a similar runtimes (~3min) for this example when looking at a log of the full build with timestamps and when using `cProfile` to run the example. Running it in binder takes ~5min

...So yea I've been trying to figure out why the `py-spy` report shows such a huge difference. The thing with this report is it's very detailed showing exactly which calls took how long. I'll see if I can share it.

BTW I'm doing the profiling on the cluster using similar resources as the CI.

**Comment by ymzayek** [comment]
Indeed the earlier report is wrong. It seems to be that the plotting at the end of that example `02_decoding/plot_haxby_full_analysis.py` stalls the `py-spy` profiler. I ran it without the last line (`show()`) and it runs in the expected time. In the end, the longest examples take ~5-7min to run according to several profilers and the sphinx-build report so now I'm a bit less enthusiastic about being able to optimize the run that much and migrating the CI is looking like the best/only option.

**Comment by bthirion** [comment]
Yes, that's what I expected.
