### ISSUE TITLE
docstring of nilearn.glm.second_level.second_level.non_parametric_inference:129:Malformed table. Bottom/header table border does not match top border.

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#3240]
This follows from the inclusion of #3181 
@tsalo would you mind taking a look ? see 
https://app.circleci.com/pipelines/github/nilearn/nilearn/4385/workflows/5a1e8e0e-963f-49a0-9d03-b98c0d4b0709/jobs/9708

**Comment by tsalo** [comment]
Ah, yes I saw that yesterday. I can open a separate PR to fix it, but it is already fixed in #3196.

**Comment by bthirion** [comment]
Thx, closing, then.
