### ISSUE TITLE
Setting up nilearn development environment per instructions fails as tbb is not installed

### ISSUE THREAD

**Issue by JohnAtl** [nilearn/nilearn#3244]
Following [the instructions](https://nilearn.github.io/stable/development.html#contribution-guidelines) in the contribution guidelines fails because tbb is not installed.

Nilearn version: 0.9.1
macOS 12.3.1, Homebrew 3.4.10, Python 3.9.12

### Expected behavior

No errors.

### Actual behavior

```
PackagesNotFoundError: The following packages are missing from the target environment:
  - tbb
```

Which required `conda install tbb`.

**Comment by tsalo** [comment]
This is odd... it doesn't look like `tbb` is directly used anywhere in `nilearn`, so I'm guessing this is a problem with one of its requirements.

I'm unable to replicate the problem locally with `conda` (OSX 12.3.1, conda  4.10.3). Here's what I did:

```bash
conda create --name nilearndebug python=3.9.12
conda activate nilearndebug
cd Documents/tsalo/nilearn/
pip install -e '.[dev]'
```

This installed `tbb` as well, and `pip show tbb` indicates that `mkl` is what requires `tbb`. Is it possible that `mkl` is not installing correctly with homebrew?

**Comment by JohnAtl** [comment]
I'm not sure. I can't reproduce the problem now. It looks like mkl requires tbb, and tbb requires mkl.
Homebrew doesn't seem to know anything about mkl, but conda does.
I didn't know mkl existed until your reply, so I'm not much help.
I can try things if you like, or just call it a one-off and let it go.

**Comment by tsalo** [comment]
The maintainers met today and we are leaning toward removing `mkl` as a dependency.
