### ISSUE TITLE
Test `test_decoder_dummy_classifier` is failing

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#3251]
The test `nilearn/decoding/tests/test_decoder.py::test_decoder_dummy_classifier` is failing in #3248, #3249, and #3250, even though at least one of those PRs doesn't change any dependencies or relevant code.

Nilearn version: 0.9.2dev at [a547961](https://github.com/nilearn/nilearn/commit/a547961179ef2ce974cc2078e77574fd63f76fe4).

### Expected behavior

The test would pass.

### Actual behavior

It seems to fail on a subset of the CI jobs.

### Steps and code to reproduce bug

I'm having trouble reproducing the bug locally, but hypothetically one could do the following:

```bash
pytest test_decoder.py -k test_decoder_dummy_classifier
```

**Comment by NicolasGensollen** [comment]
I suspect this is due to the recent `1.1.0` release of scikit-learn. More precisely, this PR: https://github.com/scikit-learn/scikit-learn/pull/22866 which makes `get_scorer` return a copy which explains why the equality assertion is broken.
I'll work on a fix.
