### ISSUE TITLE
`TypeError: expected string or bytes-like object` when using `nilearn.input_data.NiftiMasker` with `memory` parameter.

### ISSUE THREAD

**Issue by TheChymera** [nilearn/nilearn#3256]
I get the following error from a downstream test function which used to work: https://ppb.chymera.eu/cc4f38.log

It gets fixed by changing:

```python
my_memory = Memory(path.abspath(path.expanduser('~/.nilearn_cache')))
masker = NiftiMasker(mask_img=roi, target_affine=ts_img.affine, memory=my_memory, memory_level=1)
```

to:

```python
masker = NiftiMasker(mask_img=roi, target_affine=ts_img.affine, memory_level=1)
```

Given that it seems to fail with a version comparison I suspect this is a fairly obvious issue with the installation? Any idea how to fix it, though?

**Comment by tsalo** [comment]
It looks like this also came up on NeuroStars: https://neurostars.org/t/typeerror-for-fit-transform/22458. Based on that thread, I don't think anyone knows how to fix it yet.

**Comment by htwangtw** [comment]
A member in my lab reported similar error from a customised masker built from nilearn maskers. 
I am trying to replicate this error but failing so far. (python version 3.8)

**Comment by bthirion** [comment]
Yep, we need to understand whether this comes from a change on the joblib side.
Thx for posting.

**Comment by tomMoral** [comment]
Looking at the logs, it seems to be a bug from `nilearn` side, specifically in the version check from the `_safe_cache`:
https://github.com/nilearn/nilearn/blob/main/nilearn/_utils/cache_mixin.py#L111-L117

The test fails because one of the module does not have a `str` version but a `list` one.

**Comment by bthirion** [comment]
Thx @tomMoral !

**Comment by htwangtw** [comment]
Here we have some progress - a virtual environment created on our HPC leads to this error but not on a local client machine.
AFAIK, on our cluster, pip will prioritise the system version for some packages, instead of fetching the latest. 
I don't have time to look into this issue further this week... Can revisit this in June.

**Comment by htwangtw** [comment]
Sorry I haven't had time to dig further @ymzayek 
This will be moved to my priority list once I have a paper wrapped up.

**Comment by bthirion** [comment]
Just for our organization: should we count it as part of the next release (0.10) ?

**Comment by jeromedockes** [comment]
from office hours discussion we may simply change the version check to make it handle the case where one version has incorrect type and say that they don't match in that case.

also that  function loops over a list of modules that only contains nibabel so it can be simplified.

we may want to investigate if we still need this check or if it was just a fix for some issue in old less stable versions of nibabel
