### ISSUE TITLE
Allow user to specify view angle explicitly (for surface plotting)

### ISSUE THREAD

**Issue by sambjohnson** [nilearn/nilearn#3258]
Allow users to pass (elev, azim) as a tuple or list (or generally, sequence of length 2), instead of only a string. 

### Benefits to the change
This will help for visualizing features not captured entirely in any of the limited number of default views. I generate many images, and it is infeasible to manually (interactively) select the appropriate view for each image individually. Rather, I would prefer to do this programatically. 

### Pseudocode for the new behavior, if applicable

```python
view = nilearn.plotting.plot_surf(mesh, map, view=(elev, azim))
```

I will submit a PR to this effect, but would appreciate nilearn maintainer's help in completing it.

**Comment by bthirion** [comment]
This is certainly a valid use case, thx for posting ! We'll try to provide feedback.
