### ISSUE TITLE
FirstLevelModel for volume on surface data

### ISSUE THREAD

**Issue by jyeatman** [nilearn/nilearn#3265]
Currently the GLM pipeline diverges substantially for surface vs volume data. It would be much more straightforward if the same functions operated on surface or volume data. It seems like the desirable functionality would be for FirtLevelModel to operate interchangeably on volume or surface data. I haven't gone under the hood but from the function description it seems like this would be a straightforward update

### Benefits to the change
Fewer errors if the same functions handle volume or surface

### Pseudocode for the new behavior, if applicable

```python

```

**Comment by bthirion** [comment]
Thx @jyeatman 
The main alternative to that is to develop a SurfaceFirstLevelModel that would be dedicated to surface-based analysis.
But it is highly possible that the two objects would share much of the functions, since volume/surface distinctions only make sense when it comes to input/output operations.
Any thought on this ?

**Comment by jyeatman** [comment]
My personal preference/bias is towards one function that flexibility handles different data types. Looking at the routines with FirstLevelModel it seems like very few (beyond reading the data) are specific to volume. So it seams that it would be more straightforward and less error prone for users to be able to, for example, use all the same code and try their analysis in the volume or the surface

**Comment by jeromedockes** [comment]
this is related to discussions in nilearn and nibabel on the representation of surface images; ideally with the right representation for surface data FirstLevelModel will be applicable directly to surface data just by using an appropriate masker

see https://nipy.org/nibabel/devel/biaps/biap_0009.html for a draft on the nibabel side

**Comment by Remi-Gau** [comment]
Will close this one as completed by #4126.

**Comment by Remi-Gau** [comment]
See examples:

    https://github.com/nilearn/nilearn/blob/main/examples/08_experimental/plot_localizer_new_surface_analysis_experimental.py
    https://github.com/nilearn/nilearn/blob/main/examples/08_experimental/plot_new_surface_bids_analysis_experimental.py

Feedbacks are welcome.
