### ISSUE TITLE
Optimize TFCE calculation or replace with probabilistic TFCE

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#3266]
The TFCE method we implemented in #3196 is very slow. The probabilistic TFCE measure implemented in MNE seems to be faster, although I haven't directly compared them. We should look into either speeding up the current implementation or replacing it with a probabilistic TFCE measure.

### Benefits to the change
Faster TFCE-based multiple comparisons correction.

### Pseudocode for the new behavior, if applicable

The `permuted_ols` and `non_parametric_inference` would be the same.

**Comment by bthirion** [comment]
I don't know about it, but I agree that it would be great.

**Comment by sahahn** [comment]
I'm not familiar with the probabilistic implementation of TFCE, but I spent some time today looking at the existing implementation and I think I see some areas which I could help to speed up. I can try a few different things, and if they help then I'll submit a PR ~

**Comment by ymzayek** [comment]
That sounds great, thx @sahahn !

**Comment by bthirion** [comment]
Let's close this one, then. Thx !
