### ISSUE TITLE
nilearn.interfaces.fmriprep.load_confounds not able to load compcor regressors

### ISSUE THREAD

**Issue by askieslinger** [nilearn/nilearn#3268]
When using fmriprep version > 21.0.0 and a confound strategy that attempts to load 'WM' or 'CSF' acompcor regressors, no regressors are loaded. 

The reason seems to be that the naming convention on fmriprep's side was changed in fmriprep version 21.0.0 (Dec 2021, see [fmriprep changelog](https://fmriprep.org/en/stable/changes.html#december-14-2021) "FIX: Split aCompCor into aCompCor, cCompCor, wCompCor (# 2523)"). The regressors for aCompCor on the anatomical masks 'WM' and 'CSF' have been renamed. 

Nilearn version:
0.9.2.dev
### Expected behavior
Load acompcor regressors computed on separate anatomical masks

### Actual behavior
return empty list

### Steps and code to reproduce bug

```python
confounds, _=fmriprep.load_confounds(
            img_path, strategy=['compcor','high_pass'],compcor='anat_separated')
# confounds does not contain acompcor regressors although they exist
```

Code that needs to be changed (?)
https://github.com/nilearn/nilearn/blob/a2bca9df73bd397894fca7bc193519904767bf79/nilearn/interfaces/fmriprep/load_confounds_compcor.py#L4-L6
````
prefix_compcor = {"temporal_anat": ["t", "a"],
                  "temporal": ["t"],
                  "anat": ["a","c","w"]}
````

**Comment by htwangtw** [comment]
Thanks for the thorough report @askieslinger!
I will need to further investigate the how compcor components are generated and fix it with a solution that's backwards compatible.
Do you happen to have data processed by 21.x series? 
The confound tsv and json are crucial for creating the test.

**Comment by askieslinger** [comment]
Thanks for the quick reply. 
[nilearn_example.zip](https://github.com/nilearn/nilearn/files/8805813/nilearn_example.zip)

This includes the confounds tsv and json file for one subject.
