### ISSUE TITLE
Update funding information

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#3270]
The funding support information displayed in https://nilearn.github.io/authors.html#funding is outdated and should be updated.

### Affected pages

https://nilearn.github.io/authors.html#funding

**Comment by NicolasGensollen** [comment]
@bthirion this page is outdated, it only exits because we didn't clean the `Nilearn.github.io` repo. The link for the stable version is this one: https://nilearn.github.io/stable/authors.html
The funding information are different but might still be outdated.

**Comment by bthirion** [comment]
Indeed, I just did a google search ;-)

**Comment by Remi-Gau** [comment]
What exactly is out of date on the funding section?

**Comment by ymzayek** [comment]
I just didn't properly use `closes` for this issue # in the linked PR
