### ISSUE TITLE
Shift centers of mass outside of clusters to closest in-cluster voxel in get_clusters_table

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#3278]
When presented with statistical maps with cluster-level statistics (i.e., one statistic across each cluster), `get_clusters_table` will identify the center of mass of the cluster. Sometimes, this center of mass will end up outside of the actual cluster, which currently leads to a warning and a NaN in the "Peak Stat" column. While the identified coordinate is the actual center of mass, it seems like it would be more useful to users if the function automatically found the closest voxel _in_ the cluster and reported that instead.

### Benefits to the change
Better support for cluster-level corrected statistical maps.

### Pseudocode for the new behavior, if applicable

The enhancement would sometimes change the values in the table, but the function signature would remain the same.

**Comment by bthirion** [comment]
No strong opinion on this.
My impression is that it makes the output more meaningful, but the behaviror of the function is slighlty more complex to explain.

**Comment by tsalo** [comment]
There may be more elegant ways to identify centers of mass of irregular shapes like clusters too, but I wasn't aware of any.

**Comment by clane9** [comment]
Hi there, I'm a fan of nilearn and I'm interested in contributing!

Maybe you could consider a "constrained" center of mass? Whereas the typical center of mass minimizes the sum of squared distances to the cluster points over the full space, the "constrained" center of mass would minimize just over the cluster points.

This is similar but not quite the same as the "projected" center of mass that @tsalo suggested. Not totally clear to me whether this is more or less intuitive. But could be worth considering.

```python
def constrained_center_of_mass(points, weight=None):
    """
    Find the center of mass of a set of points, constrained to the set of points.
    
    Args:
        points: array of points, shape (n, d)
        weight: optional array of point weights, shape (n,)
    
    Returns:
        The constrained center of mass, shape (d,)
    """
    if weight is None:
        weight = np.ones(len(points))

    loss = np.sum(weight * cdist(points, points, metric="seuclidean"), axis=1)
    ccom = points[np.argmin(loss)]
    return ccom
```

**Comment by tsalo** [comment]
@clane9 that sounds great to me!

**Comment by clane9** [comment]
Cool! Probably worth noting though that the projected center is more efficient to compute. (O(n) vs O(n^2), at least for this naive implementation of the constrained center.)

**Comment by clane9** [comment]
Ah, I think you are right they are equivalent. All the better.

I thought they would not be, since projecting an unconstrained solution does not give you a constrained solution in general. But because the center of mass "objective" is a very simple quadratic, the level sets are spheres and you get that the closest point to the barycenter is also the constrained barycenter.

**Comment by tsalo** [comment]
@clane9 I don't really have time to work on this at the moment, so it would be great if you are able to open a PR. I'll be happy to review it though.
