### ISSUE TITLE
Add package dependencies to a requirements.txt file

### ISSUE THREAD

**Issue by bcipolli** [nilearn/nilearn#328]
Great package here!

Not sure if I've done something improperly, but during both `pip install` and the development cloning process, I had dependency errors.  I came back and saw the dependencies and resolved them manually.

Rather than declaring dependencies in the `README.md` file, what about declaring in a `requirements.txt` file? ([documentation](https://pip.pypa.io/en/latest/user_guide.html#requirements-files)).

This should allow `pip` to resolve dependencies when installing the package, and should make getting the development version after cloning `nilearn` up and running more easily.

I'd be happy to do this, if it sounds good!

**Comment by GaelVaroquaux** [comment]
@bcipolli: did you have a look at how this could be done in the setup.py? Are you planning to send us a pull request?

**Comment by bcipolli** [comment]
@GaelVaroquaux I was planning to take a look at this after Jan. 15 (I have two things due then); would that work for you?

**Comment by GaelVaroquaux** [comment]
We are battling hard to release the 0.1 of nilearn, and I don't want to
let the release date slip, as I will need it for teaching.

**Comment by bcipolli** [comment]
OK.  If this is something you'd like in the release, just give me an idea of your timelines and I'll make time to do it!

**Comment by bcipolli** [comment]
I will take a look at this now.

**Comment by GaelVaroquaux** [comment]
> I will take a look at this now.

Thanks!

**Comment by bcipolli** [comment]
Pull request is all set.  Will be heading to bed shortly, but tried to document what I did in the PR.  Will be able to discuss / update with any requests in the morning!
