### ISSUE TITLE
Implement (port) basic aspects of Representational Similarity Analysis (RSA)

### ISSUE THREAD

**Issue by bcipolli** [nilearn/nilearn#329]
I'm not sure if y'all are famiilar with RSA [link](http://www.mrc-cbu.cam.ac.uk/methods-and-resources/toolboxes/), but I will be using it in my analyses here.  A nice [MATLAB toolbox](http://www.mrc-cbu.cam.ac.uk/methods-and-resources/toolboxes/) already exists (and is under rapid development).  I see that the [PyMVPA](http://www.pymvpa.org) team has done a [basic RSA example](http://www.pymvpa.org/examples/rsa_fmri.html), but I would like a more extensive port of the MATLAB toolbox.

Rather than writing code just for myself, it would be great to come up with a design that could be included here.  I believe the MATLAB RSA Toolbox's [license](http://www.mrc-cbu.cam.ac.uk/methods-and-resources/toolboxes/license/) would allow for such porting some of their functionality (but I would email them to check, if this proposal is acceptable here), and my quick look at the code makes me believe there isn't THAT much to port.

If this sounds interesting, I would go through their toolbox and make a specific proposal about what functions / modules of their code be ported to python and post it here.  At the same time, I would contact them to double-check that this would fit their license (and if we'd actually have to include their MATLAB code, or if just a reference to it would be sufficient).

**Comment by bthirion** [comment]
Nice feature waiting for contributors. Closing for now.
