### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by saiprasanna06** [nilearn/nilearn#3294]
My code was running perfectly few days ago. Today I am getting this error all of a sudden. The error shown is as follows. Please help me fix it.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [8], in <cell line: 9>()
      2 import nilearn.maskers
      4 masker = NiftiLabelsMasker(labels_img=atlas_filename, 
      5                            standardize=True, 
      6                            memory='nilearn_cache', 
      7                            verbose=1)
----> 9 time_series = masker.fit_transform(fmri_filenames)

File ~\anaconda3\lib\site-packages\nilearn\maskers\nifti_labels_masker.py:396, in NiftiLabelsMasker.fit_transform(self, imgs, confounds, sample_mask)
    392 def fit_transform(self, imgs, confounds=None, sample_mask=None):
    393     """ Prepare and perform signal extraction from regions.
    394 
    395     """
--> 396     return self.fit().transform(imgs, confounds=confounds,
    397                                 sample_mask=sample_mask)

File ~\anaconda3\lib\site-packages\nilearn\maskers\base_masker.py:197, in BaseMasker.transform(self, imgs, confounds, sample_mask)
    194 self._check_fitted()
    196 if confounds is None and not self.high_variance_confounds:
--> 197     return self.transform_single_imgs(imgs,
    198                                       confounds=confounds,
    199                                       sample_mask=sample_mask)
    201 # Compute high variance confounds if requested
    202 all_confounds = []

File ~\anaconda3\lib\site-packages\nilearn\maskers\nifti_labels_masker.py:492, in NiftiLabelsMasker.transform_single_imgs(self, imgs, confounds, sample_mask)
    489 params['target_shape'] = target_shape
    490 params['target_affine'] = target_affine
--> 492 region_signals, labels_ = self._cache(
    493     _filter_and_extract,
    494     ignore=['verbose', 'memory', 'memory_level']
    495 )(
    496     # Images
    497     imgs, _ExtractionFunctor(self._resampled_labels_img_,
    498                              self.background_label, self.strategy,
    499                              self._resampled_mask_img),
    500     # Pre-processing
    501     params,
    502     confounds=confounds,
    503     sample_mask=sample_mask,
    504     dtype=self.dtype,
    505     # Caching
    506     memory=self.memory,
    507     memory_level=self.memory_level,
    508     verbose=self.verbose)
    510 self.labels_ = labels_
    512 return region_signals

File ~\anaconda3\lib\site-packages\nilearn\_utils\cache_mixin.py:309, in CacheMixin._cache(self, func, func_memory_level, shelve, **kwargs)
    304     warnings.warn("memory_level is currently set to 0 but "
    305                   "a Memory object has been provided. "
    306                   "Setting memory_level to 1.")
    307     self.memory_level = 1
--> 309 return cache(func, self.memory, func_memory_level=func_memory_level,
    310              memory_level=self.memory_level, shelve=shelve,
    311              **kwargs)

File ~\anaconda3\lib\site-packages\nilearn\_utils\cache_mixin.py:240, in cache(func, memory, func_memory_level, memory_level, shelve, **kwargs)
    238 else:
    239     memory = Memory(location=None, verbose=verbose)
--> 240 cached_func = _safe_cache(memory, func, **kwargs)
    241 if shelve:
    242     cached_func = _ShelvedFunc(cached_func)

File ~\anaconda3\lib\site-packages\nilearn\_utils\cache_mixin.py:113, in _safe_cache(memory, func, **kwargs)
    111 my_versions = dict((m.__name__, m.__version__) for m in modules)
    112 commons = set(versions.keys()).intersection(set(my_versions.keys()))
--> 113 collisions = [
    114     m for m in commons if not _compare_version(
    115         versions[m], '==', my_versions[m]
    116     )
    117 ]
    118 # Flush cache if version collision
    119 if len(collisions) > 0:

File ~\anaconda3\lib\site-packages\nilearn\_utils\cache_mixin.py:114, in <listcomp>(.0)
    111 my_versions = dict((m.__name__, m.__version__) for m in modules)
    112 commons = set(versions.keys()).intersection(set(my_versions.keys()))
    113 collisions = [
--> 114     m for m in commons if not _compare_version(
    115         versions[m], '==', my_versions[m]
    116     )
    117 ]
    118 # Flush cache if version collision
    119 if len(collisions) > 0:

File ~\anaconda3\lib\site-packages\nilearn\version.py:158, in _compare_version(version_a, operator, version_b)
    153 if operator not in VERSION_OPERATORS:
    154     raise ValueError(
    155         "'_compare_version' received an unexpected "
    156         "operator {0}.".format(operator)
    157     )
--> 158 return VERSION_OPERATORS[operator](parse(version_a), parse(version_b))

File ~\anaconda3\lib\site-packages\pkg_resources\__init__.py:121, in parse_version(v)
    119 def parse_version(v):
    120     try:
--> 121         return packaging.version.Version(v)
    122     except packaging.version.InvalidVersion:
    123         warnings.warn(
    124             f"{v} is an invalid version and will not be supported in "
    125             "a future release",
    126             PkgResourcesDeprecationWarning,
    127         )

File ~\anaconda3\lib\site-packages\pkg_resources\_vendor\packaging\version.py:264, in Version.__init__(self, version)
    261 def __init__(self, version: str) -> None:
    262 
    263     # Validate the version and parse it into pieces
--> 264     match = self._regex.search(version)
    265     if not match:
    266         raise InvalidVersion(f"Invalid version: '{version}'")

TypeError: expected string or bytes-like object

**Comment by bthirion** [comment]
Please post this to Neurostars rather than in Nilearn issues.
Is the issue reproducible ?
How recent is your environment ?

**Comment by saiprasanna06** [comment]
I do not think this is a issue related to neurostars. I'm using nilearn on ABIDE dataset.
I am not sure if this issue is reproducible on another machine, the same code worked for me few days ago.
My environment has all the latest versions of dependencies, nilearn=0.9.1

**Comment by bthirion** [comment]
Yes, but Neurostars is the place where people discuss this kind of issues.
My best advice for now is to clean your cache directory and re-run.
Best,
Bertrand

**Comment by jeromedockes** [comment]
it seems one of the installed modules exposes a `__version__` that is not a `str` -- could you show the output of `pip freeze` and `conda list`, and try to reproduce in a new conda env? also please provide a script so we can try to reproduce the error.

As @bthirion mentioned the best place to ask for help troubleshooting this kind of issue is neurostars, so I would recommend posting there and closing this issue

**Comment by jeromedockes** [comment]
BTW we are using `pkg_resources` to parse version strings, but its use is deprecated in favor of `importlib_resources` and `importlib_metadata` -- https://setuptools.pypa.io/en/latest/pkg_resources.html

**Comment by jeromedockes** [comment]
closing for now as with only the traceback we have no way to reproduce the error. Feel free to repopen or ask on neurostars if you are still having trouble
