### ISSUE TITLE
Add `n_elements_` attribute to masker objects

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#3296]
It would be nice to have an attribute in masker objects that indicates the number of regions/voxels in the mask.

I am mostly opening this to gauge interest. In the past, I have lamented the fact that I don't have ready access to the number of regions/voxels in different types of maskers, and I thought it might be worth adding as an attribute.

### Benefits to the change

I think this would primarily benefit developers who rely on Nilearn, rather than users. The main benefit would be that it would be easier to preallocate arrays for transformed images without having to directly check the mask images.

### Pseudocode for the new behavior, if applicable

```python
from nilearn import datasets, maskers
dataset = datasets.fetch_development_fmri(n_subjects=1)
func_filename = dataset.func[0]

nifti_masker = maskers.NiftiMasker(mask_strategy='epi')
nifti_masker.fit(func_filename)
mask_img = nifti_masker.mask_img_
print(nifti_masker.n_elements_)
# 24256
```

**Comment by bthirion** [comment]
I don't see any downside to your suggestion so  +1

**Comment by tsalo** [comment]
@clane9 I'm sorry, I missed your comment, so I didn't realize you were willing to take this on. I opened #3311 for it today.

**Comment by clane9** [comment]
@tsalo, no worries! Glad to see your PR.
