### ISSUE TITLE
Seemingly random test failure with `test_temp_file_removing`

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3301]
There is a test that checks if a temporary file was removed correctly and it seems to fail randomly every once in a while. I am looking into it to see if I can improve the test. 
See [test here](https://github.com/nilearn/nilearn/blob/main/nilearn/plotting/tests/test_html_document.py)
See [failure here](https://dev.azure.com/Parietal/Nilearn/_build/results?buildId=4733&view=logs&j=8d5ac5f6-e89e-50f1-f198-d1a0983ad562&t=73659071-ebed-5a28-0af2-8b5a9c385fe0&l=11372)

**Comment by bthirion** [comment]
No clue about that. Maybe find related issues on internet.

**Comment by jeromedockes** [comment]
one first thing we could try is augment the `time.sleep(1.5)` to something a bit larger

**Comment by ymzayek** [comment]
Indeed giving more room would help deal with inaccuracies in the timing. Another potential solution is to replace the  `time.sleep(1.5)` line with `os.wait()` so that the process waits for the subprocess to finish before moving to the next line. WDYT? Any downsides?

**Comment by jeromedockes** [comment]
That's a good idea! the doc says `os.wait` is only available on unix. we could have `open_in_browser` return the process id of the process that removes the temp file, or store it as an attribute of the HTMLDocument (in the same way it has the `_temp_file` attribute), and use `os.waitpid`? for debugging and testing purposes rather than just the pid we may also want to hold onto the whole `Popen` object created in `_remove_after_n_seconds`

**Comment by ymzayek** [comment]
I am not sure how we can use `Popen.wait` here because as I understood it is usually used for the opposite of what I think we want to do here: it waits for the process to finish before continuing the subprocess which is useful when the subprocess relies on a return from the process. 

And good point about `os.wait`. I think using `os.waitpid` instead should work fine. I can open a PR to implement that and we can work from there.

**Comment by jeromedockes** [comment]
> Ok I see. I either interpreted something incorrectly or wrote the test
> wrong (or both). It does work indeed.

great!

> Will update the PR. In any case I didn't get `os.waitpid` to work for the windows tests and do not have a windows machine to test locally.

I think maybe the Popen attribute is the process _id_ whereas os.waitpid
wants the process _handle_ on windows
