### ISSUE TITLE
Suggestions for contributors to run code quality checks locally

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3308]
It might be a good idea to add some information about checking code quality locally in the contributing guidelines.
This relates to #2528 but it would just be optional suggestions to use e.g. pre-commit, black, etc. instead of adding dependencies directly to nilearn. At the very least we can suggest running flake8 on the diff locally and fixing PEP8 issues before committing and pushing code since that is already a dependency.

**Comment by jeromedockes** [comment]
+1 for showing how to easily run flake8 on the diff only and encouraging contributors to do so
-1 for optionally using black (it will format lines that aren't touched otherwise by the PR), and for using a pre-commit hook (1 more thing for new contributors to learn about), as mentioned in #2528

**Comment by htwangtw** [comment]
I agreed with @jeromedockes - also maintaining pre-commit will become a job itself as well. 
Black also mess with double quote and single quote if using it straight out of the box. I liked it for a bit but now I don't.

**Comment by ymzayek** [comment]
Thanks for the feedback! I agree with leaving out pre-commit. I think if we can run black only on the diff it might be also an option: https://github.com/nilearn/nilearn/issues/2528#issuecomment-902782489. Though I haven't tested this and can't guarantee it won't make spurious changes so ok for not including it for now.

> +1 for showing how to easily run flake8 on the diff only and encouraging contributors to do so

Great, we can start with that then.
