### ISSUE TITLE
Loading freesurfer outputs with nilearn.surface.load_surf_data

### ISSUE THREAD

**Issue by emaliemcmahon** [nilearn/nilearn#3310]
`nilearn.surface.load_surf_data` does not permit loading of all the surface files from the freesurfer output directly. Most critically, there are files included in the [fsaverage dictionary ](https://nilearn.github.io/stable/modules/generated/nilearn.datasets.fetch_surf_fsaverage.html) that cannot be loaded with `nilearn.surface.load_surf_data`, e.g. lh.inflated. I suggest allowing for the loading 

### Benefits to the change
Permits loading of all nilearn surface information from freesurfer outputs

### Pseudocode for the new behavior, if applicable
```
  or surf_data.endswith('inflated')
  or surf_data.endswith('pial')
  or surf_data.endswith('sphere')
  or surf_data.endswith('white')
```

**Comment by ymzayek** [comment]
@emaliemcmahon I believe that the file formats you list are surface mesh geometries and not surface data. To load these you need to use [`nilearn.surface.load_surf_mesh`](https://nilearn.github.io/stable/modules/generated/nilearn.surface.load_surf_mesh.html#nilearn.surface.load_surf_mesh). Let me know if that solves your issue.
If you need more guidance on the usage of the surface module please post your question to https://neurostars.org/tag/nilearn
