### ISSUE TITLE
Improve handling and managing of URLs

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3321]
Working on #3315 made me think that there might be a better way to handle URLs. For example, some links repeat many times making it hard to manage them. I think we should be able to make a mapping of URLs to keywords in one place and then create a sphinx role that would link the keywords. This would make it easier to fix broken links in the future and, if possible to use anchor text, would make the documentation more readable. This is useful for rendered docs and wouldn't necessarily apply to all URLs in the library.

**Comment by bthirion** [comment]
No strong opinion on this, but sounds very reasonable to me.

**Comment by emdupre** [comment]
Sorry, just to confirm : You mean this mostly in the context of URLs that refer to specific built files, is that right ? For example, having something that expands to `https://nilearn.github.io/stable/` that could be modified at e.g. the `conf.py` level if we buy a new domain.

**Comment by ymzayek** [comment]
Yes, initially it came from noticing that there were some internal URLs repeated many times and one in particular about a 100 times in rendered docstrings when I was adding the `/stable` path. Putting them in one place and then creating hyperlinks through sphinx roles will make them easier to manage.

**Comment by ymzayek** [comment]
I am not very familiar with sphinx but internal linking was easier than I thought and there is no need for mapping URLs. See the linked PR.

**Comment by emdupre** [comment]
Great ! I wanted to confirm that's what you meant :) Glad you found a solution !
