### ISSUE TITLE
How to display the visual difference between two groups using GLM?

### ISSUE THREAD

**Issue by G21R** [nilearn/nilearn#3325]
I am working with the BIDS data format for nirx group analysis.  I apologize for my English.I would like to know if it is possible to calculate the contrast for two different groups of the same experiment? I have two different groups (Those who do well in math and those who do poorly) they are undergoing one experiment. But how do I get visual information about the contrast and differences of these two groups?

**Comment by G21R** [comment]
I want to get something like that.The photo shows information about the contrast between different events in the same group. But as I wrote above, I need to get a contrast between two different groups (preferably both for the same events and for different ones)
![image](https://user-images.githubusercontent.com/101802504/182669386-f5c4e5e8-d403-459e-bb8b-96be406c74a9.png)

**Comment by bthirion** [comment]
Hi, thank you for asking, but this is typically a usage question, that should go to Neurostars.
You might want to consider the unpaired case in:
https://nilearn.github.io/stable/auto_examples/05_glm_second_level/plot_second_level_two_sample_test.html#sphx-glr-auto-examples-05-glm-second-level-plot-second-level-two-sample-test-py
HTH,

**Comment by G21R** [comment]
> Привет, спасибо, что спросили, но обычно это вопрос использования, который следует задать Neurostars. Возможно, вы захотите рассмотреть непарный случай в: https://nilearn.github.io/stable/auto_examples/05_glm_second_level/plot_second_level_two_sample_test.html#sphx-glr-auto-examples-05-glm-second-level-plot-second-level-two-sample-test-py HTH,

Please forgive me. Where should I ask the question can I get a link? That is, I understand correctly that there is no such functionality in mne and nilearn that I described above at the moment

**Comment by bthirion** [comment]
Such usage questions are better discussed in https://neurostars.org/

If I understand your point correctly, no, there is no high-level function that allows you to do what you want to.
The idea would be to design the model "manually", i.e. to supply the design matrix, as  in the above example.
HTH,

**Comment by G21R** [comment]
> Such usage questions are better discussed in https://neurostars.org/
> 
> If I understand your point correctly, no, there is no high-level function that allows you to do what you want to. The idea would be to design the model "manually", i.e. to supply the design matrix, as in the above example. HTH,

I am very grateful to you for your answer and I apologize for asking a question here again - this is very important to me. no one answered me on that site. But I would like to know why this model does not exist? On the nilearn website, I came across the following statement - _**The contrast is between responses to retinotopically distinct vertical versus horizontal checkerboards. At the individual level, these stimuli are sometimes used to map the borders of primary visual areas. At the group level, such a mapping is not possible. Yet, we may observe some significant effects in these areas**_. Do I understand correctly that this model for contrast difference does not exist due to certain theoretical justifications? Or it does not exist simply because no one has implemented it. I apologize if I force you to answer again, my English is bad

**Comment by ymzayek** [comment]
@G21R thanks for posting on Neurostars. Sometimes it might take us longer to respond and we have a lot of users from different time zones so it could be related to that. In any case, I am linking your question here so that the conversation can continue over there: https://neurostars.org/t/how-to-calculate-the-contrast-between-two-different-groups-based-on-glm/23232
It also helps to tag questions on Neurostars with nilearn so that we get notified about them.

**Comment by G21R** [comment]
> @G21R thanks for posting on Neurostars. Sometimes it might take us longer to respond and we have a lot of users from different time zones so it could be related to that. In any case, I am linking your question here so that the conversation can continue over there: https://neurostars.org/t/how-to-calculate-the-contrast-between-two-different-groups-based-on-glm/23232 It also helps to tag questions on Neurostars with nilearn so that we get notified about them.

Thank you very much, and I apologize for my emotionality, it's just that this question is very important to me, I will wait for an answer
