### ISSUE TITLE
Update organizational docs

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3329]
I listed some supporting documentation that seems to need some updating. Let me know your feedback and feel free to add anything I may have missed.

### Affected pages

- Our [license](https://github.com/nilearn/nilearn/blob/main/LICENSE) (includes old sphinx and jquery licenses)
- Update core dev info and funding in https://nilearn.github.io/dev/authors.html (also see #3270)
  - Remove triage section? (if so, see also [here](http://nilearn.github.io/dev/development.html#join-the-triage-team))
- ~~Update 'Development version' installation instructions in [introduction](https://nilearn.github.io/dev/introduction.html#installing-nilearn)~~
- Add Code of Conduct

**Comment by emdupre** [comment]
I'd cross-link this with https://github.com/nilearn/nilearn/issues/3264 , too !
