### ISSUE TITLE
Simple plotting example on first-page carroussel

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#333]
The carroussel on the index page should display and link to the simple plotting example, and not the lengthy one.

**Comment by lesteve** [comment]
I think this one is done. It's just that the website hasn't been updated since. Look at http://lesteve.github.io/ which is more up-to-date.

**Comment by GaelVaroquaux** [comment]
I don't think so. The docs/index.rst should be update. Neither the
website that you point to, nor the code in master seem to include this
change, IMHO.

**Comment by lesteve** [comment]
Basically, plot_demo_plotting.py has now become the simple example (so doc/index.rst didn't need to be updated). It shows the different plot_* functions. The advanced example is plot_demo_more_plotting.py and shows all the display modes + using add_edges and add_contours on a display object.

**Comment by GaelVaroquaux** [comment]
OK. It didn't seem that simple to me. Have you tried it upon our favorite
guinea pig: Baptiste?

**Comment by lesteve** [comment]
I haven't tried. Not sure how to simplify it further, besides creating one example by plot_ function.

**Comment by AlexandreAbraham** [comment]
I was thinking of one example of 5 lines for the glass brain only and one "advanced" with all the other plots. One example by plot function is only needed if we want to show the effect of different parameters.

**Comment by GaelVaroquaux** [comment]
> I was thinking of one example of 5 lines for the glass brain only and one
> "advanced" with all the other plots.

I'd say 3 examples: the 5-liner you mention, to catch people in, as the
glass brain is a clear selling point of the package, the current simple
example, and the current full example. The 5-liner would be on the
front page, but it would link (in the docstring) to the other examples.
