### ISSUE TITLE
Binder links are broken

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3334]
When trying to open binder I get a 404 error. This is probably due to the new file structure and cleaning of https://github.com/nilearn/nilearn.github.io in https://github.com/nilearn/nilearn.github.io/pull/3.

I am also curious about how many people find binder useful. In the past I have tried to use it but it was very slow.

**Comment by alexisthual** [comment]
> I am also curious about how many people find binder useful.

I personally never use binder 😅 (for `nilearn` or elsewhere).

**Comment by andreifoldes** [comment]
I do use it when quickly wanting to see what in a variable in a tutorial...

**Comment by GaelVaroquaux** [comment]
I use them when teaching: they avoid installation mess in the room.

**Comment by emdupre** [comment]
I use Binder to quickly showcase small examples ; it would be great to fix these links for the new doc format !

**Comment by ymzayek** [comment]
Thanks for the feedback and great to know that it is useful! Working on a solution
