### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by sachin-bsai** [nilearn/nilearn#3336]
I think the authors meant to describe ADHD but have written ADHD as AHDH. It is just a simple spelling or typographic error.

### Affected pages
1. https://nilearn.github.io/dev/auto_examples/04_glm_first_level/plot_adhd_dmn.html#sphx-glr-auto-examples-04-glm-first-level-plot-adhd-dmn-py
 2. https://nilearn.github.io/dev/glm/first_level_model.html#fitting-a-first-level-model

**Comment by ymzayek** [comment]
@sachin-bsai thanks for noticing! Would you be willing to open a pull request to fix it?

**Comment by sachin-bsai** [comment]
Yeah sure, I will try. If I fail somewhere, I will comment over here.

**Comment by ymzayek** [comment]
Sounds great! We also have some guidelines that may help you get started: https://nilearn.github.io/stable/development.html#pr-structure. Once the pull request is open we will review it and help you along the way

**Comment by sachin-bsai** [comment]
Hey @ymzayek , I am unable to find that particular code branch that has this issue. Would you help me out?

**Comment by nettle790** [comment]
I am able to correct the first link on spelling error AHDH to ADHD.shall I open a PR?

**Comment by ymzayek** [comment]
Hi @nettle790 thanks for your interest but @sachin-bsai has already opened a PR with the correction. You can take a look at the label https://github.com/nilearn/nilearn/labels/Good%20first%20issue for other issues that are good to start with.

**Comment by nettle790** [comment]
ok, not a problem
