### ISSUE TITLE
index_img / iter_img

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#335]
Preparing my course on nilearn, it is becoming clearer and clearer that we need something to index iter niimgs in the 4th direction.

I would suggest the following semantics:

<pre>
def index_img(niimgs, index):
     niimgs = niimgs.check_niimgs(niimgs)
     return nibabel.Nifti1Image(niimgs.get_data()[:, :, :, index], niimgs.get_affine(), header=niimgs.get_header())

def iter_img(niimgs):
     niimgs = niimgs.check_niimgs(niimgs)
     for i in range(_utils.get_shape(niimgs)[3]):
         yield nibabel.Nifti1Image(niimgs.get_data()[:, :, :, i], niimgs.get_affine(), header=niimgs.get_header())
</pre>

What do people think?

I am thinking that this may be something that we should prioritize before the 1.0 release.

**Comment by AlexandreAbraham** [comment]
I have these functions in my toolbox and use them all the time.

**Comment by banilo** [comment]
How about a cool nifti generator? :-P

https://github.com/nilearn/nilearn/pull/272

**Comment by GaelVaroquaux** [comment]
> How about a cool nifti generator? :-P

> https://github.com/nilearn/nilearn/pull/272

In essence, it is the same idea, which is probably a good thing: if the
same idea keeps coming up, it is probably useful.

One minor difference is the vocabulary in which it is formulated. I think
that a function (technicaly and generator function) rather than an
object, and avoiding the term "generator" in the name, makes things a bit
more friendly to Joe user.

**Comment by GaelVaroquaux** [comment]
@AlexandreAbraham : want to do a PR?
