### ISSUE TITLE
Update Juelich atlas to the newest parcellation

### ISSUE THREAD

**Issue by magdalenasabat** [nilearn/nilearn#3352]
The julich atlas has more up-to-date version with almost 3 times as many parcels  (including fsaverage surface) as the one included in nilearn.dtasets.fetch_atlas_juelich . If coordinate spaces are incompatible maybe neuromaps could be helpful? (https://github.com/netneurolab/neuromaps)

source for the parcellation: https://search.kg.ebrains.eu/instances/a8932c7e-063c-4131-ab96-996d843998e9

**Comment by bthirion** [comment]
Thx for the suggestion. I'd bin favor of keeping the old version with the current API for the sake of bw compatibility, but also giving access to the most recent one (e.g. with an additional keyword). Do people agree on this ?

**Comment by jeromedockes** [comment]
I believe we already have too many atlases; would the new atlas improve
the example gallery or help when teaching nilearn? If not I'm not sure
we need a new fetcher; users can download it separately or maybe with
templateflow -- see a discussion on the topic in
https://github.com/nilearn/nilearn/issues/3074 . The gist of it is that
nilearn has atlas fetchers mostly to help build its example gallery and
will not provide a comprehensive collection of atlases.

**Comment by bthirion** [comment]
Templateflow is probbaly the right place to handle all possible atlases.

**Comment by htwangtw** [comment]
It would be great to redirect these kind of request to templateflow. The have a [detailed guide](https://www.templateflow.org/contributing/guidelines/#are-you-allowed-to-share-the-template) for contributing atlas/template as well.

**Comment by jeromedockes** [comment]
to avoid duplicating the discussion on adding atlas fetchers I suggest we close this issue in favor of #3074 ?

**Comment by bthirion** [comment]
+1
