### ISSUE TITLE
Broken literalinclude in the docs

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#336]
In the following file:
http://nilearn.github.io/_sources/developers/dataset_download.txt

The literalinclude directives are broken.

**Comment by AlexandreAbraham** [comment]
This page is an old page that targeted developers and is not part of the documentation. It should have been deleted long ago.

**Comment by GaelVaroquaux** [comment]
> This page is an old page that targeted developers and is not part of the
> documentation. It should have been deleted long ago.

I sort of agree, but it's linked from the reference document (which means
the both the page and the link should be deleted).

**Comment by AlexandreAbraham** [comment]
Since the problem was straightforward to solve, I pushed directly into master.

**Comment by GaelVaroquaux** [comment]
Excellent. Thanks
