### ISSUE TITLE
Censoring (and interpolation) in `signal.clean`

### ISSUE THREAD

**Issue by butellyn** [nilearn/nilearn#3364]
Hi! I just attended the NiLearn office hours to learn more about how censoring works with `signal.clean`. Through inspecting the [source code](https://github.com/nilearn/nilearn/blob/9aa503f5/nilearn/signal.py#L460), it was determined that the volumes flagged with the `sample_masks` argument are censored, and then the uncensored volumes adjacent to the first and last censored volumes in a given censored block are treated as if they were collected one after another in subsequent processing steps (e.g., for the purposes of bandpass filtering). Conceptually, this seems like it may be problematic, but practically none of us in the NiLearn Office Hours knew if it causes problems/substantially changes results.

[Historically](https://github.com/GrattonLab/GrattonLab-General-Repo/blob/master/FCProcess/FCPROCESS_GrattonLab.m), I have seen the following steps performed: censoring, temporal interpolation (ideally power spectral matched), bandpass filtering, and then censoring again of the interpolated volumes prior to functional connectivity estimation. Power spectral matched temporal interpolation has the benefit of having realistic dummy volumes so that volumes adjacent to the censored volumes are not contaminated by unrealistic data during bandpass filtering, which is especially important in high motion subjects, considering linear interpolation over many volumes will not come close to approximating realistic data.

Has there been any side-by-side comparisons of these, and potentially other, censoring methods? If in fact it is better to utilize temporal interpolation, would it be possible to implement this in NiLearn? Also, if possible, it would be great to have more documentation about exactly what is happening with each of the processing steps after fMRIPrep and before functional connectivity estimation in NiLearn. A timeline of sorts would be awesome, especially for `NiftiLabelsMasker` (selfishly).

**Comment by butellyn** [comment]
Citation for the temporal interpolation/censoring scheme: Power, J. D., Mitra, A., Laumann, T. O., Snyder, A. Z., Schlaggar, B. L., & Petersen, S. E. (2014). Methods to detect, characterize, and remove motion artifact in resting state fMRI. Neuroimage, 84, 320-341.

**Comment by butellyn** [comment]
I realized the link for "Historically" isn't publicly available. [Here](https://github.com/NU-ACNLab/mwmh/blob/main/scripts/process/gratton/FCPROCESS_GrattonLab.m) is a publicly available version.

**Comment by htwangtw** [comment]
Nilearn only implemented a butterworth filter, and for DCT it's just the cosine regressors from fMRIPrep output. I am not implementing any extra filtering methods here.

**Comment by butellyn** [comment]
Ah, so the power spectral interpolation method isn't for filtering, it is for interpolating over censored volumes. What method of interpolation are you considering using?

**Comment by htwangtw** [comment]
I need to have a look to see if there's anything similar for interpolation in the existing code of nilearn (I am only worked with `signals.clean`). I am happy to fix the bug and will see if this needs to be break down into multiple PRs

**Comment by butellyn** [comment]
Thank you!

**Comment by butellyn** [comment]
Not sure if this is helpful, but I wrote my own function for cubic interpolation: https://github.com/NU-ACNLab/mwmh/blob/main/scripts/process/cubic_interp.py

**Comment by htwangtw** [comment]
I am more in favour of using the scipy implementation as it has been tested, but thank you for sharing the code! I am going to push the commit soon and I can tag you @butellyn if you would like to provide feedbacks

**Comment by butellyn** [comment]
I implemented it with scipy. Just created a wrapper function to loop over voxels and get the voxels to exclude based on fFD (which I mentioned [here](https://github.com/nilearn/nilearn/issues/3365)).

**Comment by htwangtw** [comment]
> 


> I implemented it with scipy

Thank you for pointing that out. 
What I meant was using `scipy.interpolate.CubicSpline`(https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.CubicSpline.html) rather than an own implementation of cubic spline using lower level scipy function. 
This way we only need to write test to check if nilearn code is interacting with `CubicSpline` correctly, rather than testing if an implementation actually does cubic spline interpolation correctly. If you have any question related to the design choices, it would be great if you can have a look at the PR. Let me know if you need help to make this process easier.
