### ISSUE TITLE
Add back stable/dev banners to website

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3367]
The green `stable` and red `dev` banners were not transferred over to the new documentation theme. 

To do:
- add banners back
- (optional) add a toggle to easily go back and forth between versions

**Comment by alexisthual** [comment]
Furo makes it easy to add an [announcement banner](https://pradyunsg.me/furo/customisation/announcement/): it would be a one-line change in our `conf.py`.

I guess we could try to have 2 configuration files (one for prod, one for dev builds) but it's a shame to duplicate files just for the sake of adding one line... Any idea on how to achieve this elegantly? :slightly_smiling_face:

**Comment by emdupre** [comment]
Could we infer [the version number](https://protips.readthedocs.io/git-tag-version.html) of `nilearn` and pass "Unstable" if it's at an untagged commit and "Stable" if it doesn't include a commit string ?

_Or_ we could just [pass an environmental variable](https://stackoverflow.com/questions/61216495/change-variable-in-sphinx-conf-py-as-part-of-build-command) during our "Stable" builds to control this ?

**Comment by alexisthual** [comment]
Oh nice, I like both ideas! I guess the first one is the most straightforward, as setting up different env variables depending on dev / prod builds might take more time (although we might like to have that in the long run).

**Comment by ymzayek** [comment]
Yes, I think the first option in good. `release` as a variable is already defined in `conf.py` and a similar thing is done with binder: https://github.com/nilearn/nilearn/blob/9eddcf0953e29e7782f1f29b32a0ec48e0a41573/doc/conf.py#L345-L348
