### ISSUE TITLE
datasets need 'description' entry (was datasets need DESCR entry)

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#337]
In datasets like the yeo atlas, or the craddock atlas, it is very hard to figure out which keys mean what.

These datasets need a 'DESCR' entry, describing that, and maybe the names of the keys could be improved.

**Comment by AlexandreAbraham** [comment]
What do you mean by DESCR? An additional section in the doc? Or maybe should we also provide a `__repr__` method?

**Comment by GaelVaroquaux** [comment]
> What do you mean by DESCR? An additional section in the doc?

Look at eg the iris dataset in sklearn.

I am not favourable to overriding __repr__. I find that it can easily
hide stuff from the user.

**Comment by AlexandreAbraham** [comment]
OK, so to make it clear : `DESCR` is a description of the dataset written in rst and added directly to the Bunch.
I'm :+1: for that!

**Comment by GaelVaroquaux** [comment]
> so to make it clear : DESCR is a description of the dataset written in rst
> and added directly to the Bunch.

That's exactly it.

**Comment by AlexandreAbraham** [comment]
I was just making it clear for the others, for example if someone wanted to take care of that :P.
