### ISSUE TITLE
test_get_clusters_table() fails

### ISSUE THREAD

**Issue by neurolabusc** [nilearn/nilearn#3370]
The test function `test_get_clusters_table` will fail because it does not correctly concatenate the [string](https://github.com/nilearn/nilearn/blob/52bba6e38c427f3f29fb68109bd2f16e404115ad/nilearn/reporting/tests/test_reporting.py#L127).

The existing code will generate an error regardless of if you use Python 2.7 or 3.x:

```
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

I also think the code should use the systems' defined file separator (eg `/` vs `\`).

I would suggest changing

```
    fname = str(tmp_path / "stat_img.nii.gz")
```

to read
```
import os
...
    fname =  os.path.join(tmp_path, "stat_img.nii.gz")
```

**Comment by tsalo** [comment]
I believe that [`tmp_path`](https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html#the-tmp-path-fixture), in this case, is a `pathlib.Path` object, which can be concatenated with strings or other `Path` objects, with the appropriate path delimiter selected automatically.

**Comment by jeromedockes** [comment]
@neurolabusc which version of pytest are you using?

**Comment by neurolabusc** [comment]
@tsalo I see. Feel free to close this issue. However, since Python uses dynamic typing it might be nice to document this expectation with the function arguments.

The following does work:

```
from pathlib import Path
tmp_path = Path('.')
fname = str(tmp_path / "stat_img.nii.gz")
```

**Comment by jeromedockes** [comment]
the function is not meant to be called directly in user code but by the pytest test runner. `tmp_path` is a pytest fixture: https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html#the-tmp-path-fixture it gets injected by pytest when running the test, and it is always a pathlib.Path

**Comment by jeromedockes** [comment]
'/' here is not a string representing the filesystem path separator, but the division operator, overloaded by `Path` to represent joining paths. If this hurts readability we can also use the `Path.joinpath` method instead ([discussion](https://mail.python.org/pipermail/python-ideas/2012-October/016544.html) about the choice of both the operator and the method name)

**Comment by neurolabusc** [comment]
I am not a Python expert and I am used to explicitly typed languages. The usage of `/` without the comma separators does look odd to my eyes. I realize my issue was simply with a test file, but it seemed like a good place to start for an example of how to use `get_clusters_table()`. Thanks for your quick response.

**Comment by jeromedockes** [comment]
I agree when we don't know the pathlib module it can be a bit puzzling
so an alternative is to write for example
`tmp_path.joinpath("subdirectory", "file.txt")`. However note Python's pathlib is
not alone in overloading an operator to join paths; for example the same
one (/) is used for C++ standard library filesystem::path -- https://en.cppreference.com/w/cpp/filesystem/path/operator_slash
Sorry I'm not sure what you mean about the comma separators?

Another good place to start seeing how a nilearn function is used is the
examples listed at the bottom of its reference documentation:
https://nilearn.github.io/dev/modules/generated/nilearn.reporting.get_clusters_table.html#examples-using-nilearn-reporting-get-clusters-table

**Comment by neurolabusc** [comment]
I don't have a problem with function overloading in general, but I do think it impairs readability in this case. Without knowing the type, it was hard to infer the behavior.

Thanks, yes I saw those examples but they were all far more involved. This is what I was looking for:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#Create a cluster table
# https://nilearn.github.io/dev/modules/generated/nilearn.reporting.get_clusters_table.html#examples-using-nilearn-reporting-get-clusters-table

#Example usage
# ./niiCluster.py ./spmMotor.nii.gz 0.5

import sys
from nilearn.reporting import get_clusters_table

def process_nifti(fname, threshold):
    cluster_table = get_clusters_table(fname, threshold, 0, two_sided=True)
    print(cluster_table)

if __name__ == '__main__':
    """Apply Gaussian smooth to image
    Parameters
    ----------
    fname : str
        Filename of NIfTI image for table
    stat_threshold : float
        Cluster forming threshold.
    """
    if len(sys.argv) < 3:
        print('No filename or threshold provided')
        sys.exit()
    fname = sys.argv[1]
    threshold = float(sys.argv[2])
    process_nifti(fname, threshold)
```

**Comment by jeromedockes** [comment]
Thanks! in that case it may be worth adding a short toy example in the "Examples" section of the reference documentation (the docstring), as done here for example: https://github.com/nilearn/nilearn/blob/9eddcf0953e29e7782f1f29b32a0ec48e0a41573/nilearn/image/image.py#L1078 for another function. The examples in the example gallery illustrate real use cases so it's true that they can be too long if you just want to see quickly how the function is called
