### ISSUE TITLE
display.add_edges could be made more 'fluid'

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#338]
While playing interactively with display.add_edges in ipython -pylab, I note the two following 'glitches':

```python
from nilearn import datasets, plotting, image
data = datasets.fetch_adhd()
mean_func = image.mean_img(data.func[1])
display = plotting.plot_epi(mean_func)
display.add_edges(image.mean_img(data.func[1]), color='w')
```

**Glitch 1:** once all the lines are executed the plot is not refreshed, to have the contour, I need to call manually 'plt.draw()'. We probably need to add a 'plt.draw_if_interactive()' at the end of the add_edges method (and we should check whether it is necessary for add_contour and add_overlay)

**Glitch 2:** In this setting, the alpha is too low, and thus the edges are not visible. I am in favor of removing the alpha (which I implemented in a hacky way with an alpha_cmap, and simply using a hard color).

**Comment by lesteve** [comment]
I noticed Glitch 1 for add_overlay so I am guessing the draw_if_interactive needs to be added to all the add_ functions.

About Glitch 2, just to make sure I read over the code correctly the edge array is supposed to contain only a single value?

**Comment by GaelVaroquaux** [comment]
> I noticed Glitch 1 for add_overlay so I am guessing the draw_if_interactive
> needs to be added to all the add_ functions.

I would guess too.

> About Glitch 2, just to make sure I read over the code correctly the
> edge array is supposed to contain only a single value?

I believe so.
