### ISSUE TITLE
Follow-up to multi-subject maskers 

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3384]
There are a few things that came up while working on pull request #3237 that still need to be improved for these new maskers as well as across the whole maskers module. These could be done in a single pr or multiple:
- - [x] Homogenize docstrings across all maskers
- - [ ] Refactor tests and modularize with pytest fixtures
- - [x] Address https://github.com/nilearn/nilearn/pull/3237#discussion_r994756264 and https://github.com/nilearn/nilearn/pull/3237#discussion_r994757493

**Comment by jeromedockes** [comment]
great, thanks!
I was also wondering if the new masker addresses [Gaël's concern](https://github.com/nilearn/nilearn/issues/1240#issue-170700100) about accepting both 4D and 4+1D data?
IIUC the new maskers can do everything their non-multi equivalent do _and_ additionally accept lists of 4D images?

**Comment by ymzayek** [comment]
@jeromedockes good point. They do accept both and actually I just noticed that the docstrings don't reflect that. I think it would be fair to make them only accept 4+1D data. I can add it to the to do list above if no one has any objections.

**Comment by jeromedockes** [comment]
> @jeromedockes good point. They do accept both and actually I just noticed that the docstrings don't reflect that. I think it would be fair to make them only accept 4+1D data. I can add it to the to do list above if no one has any objections.

for me both are ok:

1. mapsmasker accepts only 4d and multimapsmasker only 4+1d

note in that case multimapsmasker cannot be derived from mapsmasker --
it does not implement mapsmasker's interface

2. (current situation) mapsmasker accepts only 4d and multimapsmasker accepts both

in that case multimapsmasker has the complexity of accepting both types
of input, but at least users who don't need it can simply ignore it and
rely on the easier mapsmasker

**Comment by bthirion** [comment]
Given that the differences are hard to grasp for users, I find the second alternative quite well suited.
Best,

**Comment by ymzayek** [comment]
In the case of keeping it as is (second option), should the fact that the multisubject maskers accept both be reflected in the docstring? Currently it is not accurate. But I'm also wondering if it would confuse users about what to use if they only have 4D data but see that both classes accept this.

**Comment by bthirion** [comment]
I think that quite often we accept "3D or 4D" arguments to some fiunctions or methods. Basically, this is the same thing here, but "4D" or "5D".

**Comment by jeromedockes** [comment]
> I think that quite often we accept "3D or 4D" arguments to some fiunctions or methods. Basically, this is the same thing here, but "4D" or "5D". 
3D or 4D or 5D, no?

**Comment by bthirion** [comment]
Yes.
