### ISSUE TITLE
Nilearn is hiring!

### ISSUE THREAD

**Issue by jeromedockes** [nilearn/nilearn#3387]
**Developer position: Machine learning for Brain Neuroimaging**

- **Main topic:** Open-source software for neuroimaging data analysis
- **Keywords:** Brain imaging, machine learning
- **Research team:** [ORIGAMI Lab](https://neurodatascience.github.io/) (McGill University)
- **Contact:** Jean-Baptiste Poline, `jean-baptiste.poline@mcgill.ca`
- **Start and duration of contract:** 2022-11-01, for 2 years
- **Salary:** Depending on experience: between CAD 75K and CAD 95K / year
- **Application:** Send CV and motivation letter to `jean-baptiste.poline@mcgill.ca`

# The Nilearn Python library

We are looking for a programmer to help develop and maintain
[Nilearn](http://nilearn.github.io). Nilearn is one of the most widely
used Python libraries for neuroimaging and focuses on applying advanced
machine learning and signal processing to human brain images. If you are
hired for this position, you will join our research group, [the ORIGAMI
lab](https://neurodatascience.github.io/), at McGill University. You
will collaborate with Nilearn contributors at McGill University,
Université de Montréal, and around the world.

Statistical analysis of brain images, and in particular of functional
Magnetic Resonance Images (fMRI), provides many insights to basic and
clinical neuroscience. In recent years, large fMRI datasets became
publicly available and applying modern machine-learning techniques to
fMRI data has proven fruitful. Nilearn provides reliable and
user-friendly implementations of statistical methods developed by the
neuroimaging research community. The project unites researchers in
neuroscience, statistics and machine learning.

Nilearn is a key component of the open-source scientific software stack
for neuroimaging. Several aspects of the library are in active
development, such as the modules related to General Linear Models
(linear model fitting and hypothesis testing to identify associations
between mental tasks and neural activity). You will participate in
adding important new features, maintaining the existing codebase and
infrastructure, and interacting with Nilearn's dozens of active
contributors and hundreds of users.

# Job Offer description

## Long-term development

You will work on adding important new features to Nilearn. Which
features are prioritized will depend on your interests and skills, but
here are some of the most important development directions:

-   Improved support for GLM model fitting, the classical fMRI
    mass-univariate analysis.

-   Support for the [Brain Imaging Data
    Structure](https://bids-specification.readthedocs.io/en/stable/index.html),
    a standard for sharing neuroimaging datasets.

-   Improved analysis and visualizations for surface data -- brain
    activity represented as a signal on the surface of the cortex,
    rather than as a 3D full-brain image.

-   Interactive HTML reports to inspect fitted models and output of
    model validation experiments.

## Maintaining the codebase and infrastructure

You will share the responsibility of maintaining the library's usability
and code quality. This involves thorough reviews of Pull Requests
created by other core developers or community contributors, addressing
issues opened on the GitHub repository and fixing bugs, and maintenance
of the Continuous Integration configuration.

## Interacting with the community of users and contributors

You will help animate the community that has built up around Nilearn and
provide assistance to users and contributors. You will participate in
weekly drop-by hours (Q&A for users), monthly core-developer meetings,
and occasional social events such as Nilearn dev-days ([2021
edition](https://nilearn.github.io/dev-days-2021/)),
[brainhack](https://brainhack.org/), coding sprints, and training on
software development. You will answer issues in the GitHub repository
and usage questions in the
[NeuroStars](https://neurostars.org/tag/nilearn) forum.

# Skills and profile

We are looking for someone who :

-   is a competent software programmer who loves open-source and
    creating high-quality, well-tested and well-documented software,

-   is familiar with Python and the scientific Python stack used by
    Nilearn: Numpy, Scipy, Matplotlib (and ideally Scikit-learn),

-   is enthusiastic about providing a good experience and support for
    users and communicating with them in a friendly manner,

-   has interest in brain imaging and its applications.

# Working at McGill University

McGill is one of the best employers in Quebec and Canada, offering a
number of benefits. The University is ranked as one of the best in
Canada and worldwide. Montreal is a lively, safe and multicultural city.
McGill will be sponsoring the work permit if necessary. The ORIGAMI
laboratory is a friendly, collaborative and technically savvy
environment of about 12 students, post-doctoral fellows and developers.

**Comment by jeromedockes** [comment]
Here is the job description in case that is easier to send to some channels.
Please share widely!

[nilearn_montreal_developer_job_posting.pdf](https://github.com/nilearn/nilearn/files/9802943/nilearn_montreal_developer_job_posting.pdf)

**Comment by emdupre** [comment]
Should this be closed ? 😸

**Comment by jeromedockes** [comment]
I think so!

**Comment by RaphaelMeudec** [comment]
@jeromedockes maybe you can also unpin this issue from the issues page?
