### ISSUE TITLE
Add a fetch_harvard_oxford function

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#339]
On many computers, fsl is not installed, or install in an incorrect place. Thus, load_hardvard_oxford fails. We should add a "fecth_harvard_oxford" function that loads the harvard oxford from the FSL sources if available, and if not download the atlases from the net.

**Comment by AlexandreAbraham** [comment]
FSL is the official way that they chose to distribute Harvard Oxford. If you want to fetch it from the web, I see 2 options:
* directly download the fsl data package and extract it locally
* upload a copy of the atlas somewhere.

**Comment by GaelVaroquaux** [comment]
Can we grab it from the (neuro) debian sources?

**Comment by AlexandreAbraham** [comment]
This was option 1. Yes we can, for example: http://neurodebian.g-node.org/pool/non-free/f/fsldata/

**Comment by AlexandreAbraham** [comment]
Relying on an external source seems a bit dangerous to me. I would be in favor of uploading it to NITRC.

**Comment by GaelVaroquaux** [comment]
What are the legal aspects?

**Comment by AlexandreAbraham** [comment]
No license. They only ask to cite their paper if the atlas is used.
