### ISSUE TITLE
Supporting confounds in apply_mask

### ISSUE THREAD

**Issue by DasDominus** [nilearn/nilearn#3400]
I'm trying to extract the raw signals given a mask.
https://nilearn.github.io/stable/auto_examples/01_plotting/plot_visualization.html#applying-the-mask-to-extract-the-corresponding-time-series

This appears to be doing what I want, however, it does not support supplying confounds when extracting the signals.

**Comment by DasDominus** [comment]
ah Thanks @tsalo ! I must've missed a tutorial.

IIUC, the NiftiMasker simply spits out the raw signals (voxel X timepoints), with confounds removed if given, right?

**Comment by tsalo** [comment]
It does, though it can do much more than that, such as standardizing, smoothing, or filtering the data.

**Comment by DasDominus** [comment]
Thanks @tsalo ! I'll close this one then : D
