### ISSUE TITLE
The simple ICA example is somewhat toxic

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#341]
I am talking about the following example:
http://nilearn.github.io/auto_examples/connectivity/plot_ica_resting_state.html

People that want to run ICA using nilearn sometimes use it after googling. It is an example that was built to demonstrate pipelining with nilearn and scikit-learn, but it is certainly not a good ICA pipeline for fMRI. CanICA includes many small tricks that improve a lot model estimation.

We should probably move it to the advanced example section, and maybe replace ICA by something else, for which we have not integrated model.

**Comment by AlexandreAbraham** [comment]
The spectral clustering example I have somewhere is similar to this one. Do you think that it could work?
