### ISSUE TITLE
Opening parameter description missing from nilearn.masking.compute_multi_epi_mask documentation

### ISSUE THREAD

**Issue by clarkenj** [nilearn/nilearn#3411]
Description of the `opening` parameter is missing from the `nilearn.masking.compute_multi_epi_mask` [documentation](https://nilearn.github.io/stable/modules/generated/nilearn.masking.compute_multi_epi_mask.html?highlight=compute_multi#nilearn.masking.compute_multi_epi_mask).

It is included in the `nilearn.masking.compute_epi_mask` [documentation](https://nilearn.github.io/stable/modules/generated/nilearn.masking.compute_epi_mask.html?highlight=compute_epi_mask).

**Comment by bthirion** [comment]
Thx for raising this. Would you mind opening a PR to fiw this issue ?
Best,

**Comment by clarkenj** [comment]
Not at all!
Thanks
