### ISSUE TITLE
Note that Masker.inverse_transform only performs spatial unmasking in docstring

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#3416]
I vaguely recall a conversation a while back in which a user thought that `NiftiMasker.inverse_transform` would reverse the denoising steps performed by `transform` (e.g., bandpass filtering). Unfortunately, I can't find that conversation. However, it seems like we could reduce confusion by clarifying that `inverse_transform` only performs spatial unmasking.

As far as I can tell, this isn't already documented anywhere.

### Affected pages

- Maskers' API pages
- https://nilearn.github.io/stable/manipulating_images/masker_objects.html#inverse-transform-unmasking-data

**Comment by bthirion** [comment]
You're completely right.

**Comment by ymzayek** [comment]
+1 for making that explicit
