### ISSUE TITLE
how could i use brain atlas using nilear

### ISSUE THREAD

**Issue by Humagillani** [nilearn/nilearn#3419]
hi, i want apply brain atlas on fmri images how could i do that.

**Comment by bthirion** [comment]
Please ask this kind of usage question on Neurostars.

**Comment by Humagillani** [comment]
I want to know code about it
*Best regards,*
*Ms. Syeda Huma Jabeen *
Senior Lecturer, Department of Computer Science
DHA Suffa University, Karachi, Pakistan
PhD. Scholar in Computer Science ; UCAS China

**Comment by ymzayek** [comment]
@Humagillani thanks for reaching out to us but these types of questions belong on Neurostars: https://neurostars.org/tag/nilearn
Please ask your question there and tag nilearn. Also it would help if you can be more specific about what you are working on and what you would like to achieve.
