### ISSUE TITLE
group_sparse_covariance shouldn't be using logging to do progress report

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#342]
Right now, there is no proper verbosity control in the group_sparse_covariance module, as it relies on the logging module. As a result, the output is too verbose (typically in a IPython notebook as in http://nbviewer.ipython.org/github/GaelVaroquaux/nilearn_course/blob/master/rendered_notebooks/2_signal_extraction_for_connectomes.ipynb ).

This code needs to be adapted to the incremental verbosity policy.

**Comment by lesteve** [comment]
> Right now, there is no proper verbosity control in the group_sparse_covariance module, as it relies on the logging module.

@GaelVaroquaux not sure whether you meant the logging module, as in the standard library one, or the nilearn._utils.logger module. I don't think the former was used in GroupSparseCovariance and the latter does have a verbosity parameter. Maybe take a quick look at #550 to make sure it addresses the points you had in mind.

**Comment by lesteve** [comment]
Merged #550 so closing this one. @GaelVaroquaux do reopen if some of your points are not addressed.

**Comment by GaelVaroquaux** [comment]
This rocks. Thanks a lot.
