### ISSUE TITLE
`filter` option in `signal.clean` is not exposed to `nilearn.maskers.NiftiMasker` and potentially other masker objects

### ISSUE THREAD

**Issue by htwangtw** [nilearn/nilearn#3437]
> However, I don't think a filter option is provided for nilearn.maskers.NiftiMasker so seems it's using default aka butterworth

_Originally posted by @DasDominus in https://github.com/nilearn/nilearn/issues/3434#issuecomment-1333064573_

**Comment by emdupre** [comment]
I think this would need to be modified[here](https://github.com/nilearn/nilearn/blob/ffc0489b19b01b3231862846fc15ef72cfdbd249/nilearn/maskers/base_masker.py#L122-L137) and inherited by the masker objects.

But since `low_pass` isn't supported for `cosine` filtering, we might want to also add a check for sensible args ?

**Comment by TakshDhabalia** [comment]
Hey , Would like to know about this further and know more about this and if it is assigned or not. I am a beginner here so could you explain a bit more on this?

Thanks!

**Comment by bthirion** [comment]
IIUC, you can try and add the parameter, and then check possible inconsistencies that may arise.
For that you need to understand the hierarchy of class and functional calls. Maybe @ymzayek you could have a quick meeting together to review the question ?

**Comment by ymzayek** [comment]
@TakshDhabalia thanks for your interest in working on this! You can start as suggested by @emdupre on where to modify the code and additionally you need to include the argument in the maskers' class `__init__` method. You can start with just one masker for simplicity. Also what could help you get started is to take as an example another parameter of `signal.clean` that is already exposed in e.g. `nilearn.maskers.NiftiMasker` such as `low_pass` or `high_pass` and copy that implementation for `filter`. Does it make sense?

**Comment by TakshDhabalia** [comment]
yep , I agree with that but I need a little more time on reading the documentation as I am struggling a bit on this project as a whole , I will get started on it right away but if anyone wants to help , it would be very much appreciated

**Comment by ymzayek** [comment]
Hi @TakshDhabalia you can certainly take your time with this and we are here to help you along the way. If you have any specific questions whether it has to do with this issue or more generally about contributing to nilearn or how we structure our code, etc. we are happy to give you tips and point you to the right resources. You can already find a lot of information here to help you get started: https://nilearn.github.io/stable/development.html. And once you open a PR we can help you along the way with the code. You can also directly talk to us during our office hours meeting (info in the link above but check https://twitter.com/nilearn for the most up-to-date meeting information). We are very happy that you're interested in contributing to nilearn :)

**Comment by ekhella** [comment]
Hi everyone !

My name is Eric and I’m a French engineering student specializing in Software Engineering, and I’m excited to contribute to an open-source project as part of a school project. This issue interests me and I think about trying to contribute to it. I have read the comments and @emdupre and @ymzayek helped me understand it much better. Nonetheless, I have seen that @Remi-Gau removed the :Help_Wanted tag... Is there any help needed there or do I need to try focusing on another issue ?

**Comment by ekhella** [comment]
Hi @Remi-Gau !
Thanks a lot for your answer ! I have a few questions regarding the latter issue.

What type of filter are you aiming to expose? From the context, it seems like you are referring to a band-pass or Butterworth filter. Which one is it ? It it both ?

Do you want to expose multiple types of filters (e.g., low-pass, high-pass, band-pass) under the filter option, or should it be restricted to a specific one?

Should the filter parameter have a default value, and if so, what should that be? For instance, should it default to None if the user does not provide a value?

How do you envision the filter parameter being specified by the user?


Thanks a lot,

**Comment by Remi-Gau** [comment]
I think this is issue is actually not valid: one can pass the filter parameter to clean.

Adapted from https://nilearn.github.io/dev/auto_examples/03_connectivity/plot_sphere_based_connectome.html#extracts-signal-from-sphere-around-dmn-seeds


```python
from nilearn.maskers import NiftiSpheresMasker, NiftiMasker
from nilearn import datasets

dataset = datasets.fetch_development_fmri(n_subjects=10)

func_filename = dataset.func[0]

masker = NiftiMasker(
    detrend=True,
    standardize="zscore_sample",
    standardize_confounds="zscore_sample",
    low_pass=0.1,
    high_pass=0.01,
    t_r=2.0,
    memory="nilearn_cache",
    memory_level=1,
    verbose=2,
    clean__filter= "cosine", # < --------------------- SEE HERE !!!!!!!!!!!!!!!!!
    clean__butterworth__padtype="even",  # kwarg to modify Butterworth filter
)

time_series = masker.fit_transform(
    func_filename
)

dmn_coords = [(0, -52, 18), (-46, -68, 32), (46, -68, 32), (1, 50, -5)]

# same but with sphere masker
masker = NiftiSpheresMasker(
    dmn_coords,
    radius=8,
    detrend=True,
    standardize="zscore_sample",
    standardize_confounds="zscore_sample",
    low_pass=0.1,
    high_pass=0.01,
    t_r=2.0,
    memory="nilearn_cache",
    memory_level=1,
    verbose=2,
    clean__filter= "cosine",
    clean__butterworth__padtype="even",  # kwarg to modify Butterworth filter
)

time_series = masker.fit_transform(
    func_filename
)
```

@ekhella can you confirm that this makes sense?

**Comment by Remi-Gau** [comment]
**HOWEVER**

There seems to be a minor bug:

```python
from nilearn.maskers import NiftiMasker
from nilearn import datasets

dataset = datasets.fetch_development_fmri(n_subjects=10)

func_filename = dataset.func[0]

masker = NiftiMasker(
    detrend=True,
    standardize="zscore_sample",
    standardize_confounds="zscore_sample",
    low_pass=0.1,
    high_pass=0.01,
    t_r=2, # <---------------- pass an int and not a float.
    memory="nilearn_cache",
    memory_level=1,
    verbose=2,
    clean__filter= "cosine",
)

time_series = masker.fit_transform(
    func_filename
)
```

crashes

```
[get_dataset_dir] Dataset found in /home/remi/nilearn_data/development_fmri
[get_dataset_dir] Dataset found in /home/remi/nilearn_data/development_fmri/development_fmri
[get_dataset_dir] Dataset found in /home/remi/nilearn_data/development_fmri/development_fmri
[NiftiMasker.wrapped] Loading data from 
/home/remi/nilearn_data/development_fmri/development_fmri/sub-pixar123_task-pixar_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
[NiftiMasker.wrapped] Computing the mask
[Memory]0.0s, 0.0min    : Loading compute_background_mask...
[NiftiMasker.wrapped] Resampling mask
[Memory]0.3s, 0.0min    : Loading resample_img...
[NiftiMasker.wrapped] Finished fit
________________________________________________________________________________
[Memory] Calling nilearn.maskers.nifti_masker._filter_and_mask...
_filter_and_mask('/home/remi/nilearn_data/development_fmri/development_fmri/sub-pixar123_task-pixar_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz', 
<nibabel.nifti1.Nifti1Image object at 0x728db92a3f80>, { 'clean_kwargs': {'filter': 'cosine'},
  'detrend': True,
  'dtype': None,
  'high_pass': 0.01,
  'high_variance_confounds': False,
  'low_pass': 0.1,
  'reports': True,
  'runs': None,
  'smoothing_fwhm': None,
  'standardize': 'zscore_sample',
  'standardize_confounds': 'zscore_sample',
  't_r': 2,
  'target_affine': None,
  'target_shape': None}, memory_level=1, memory=Memory(location=nilearn_cache/joblib), verbose=2, confounds=None, sample_mask=None, copy=True, dtype=None)
[NiftiMasker.wrapped] Loading data from 
Nifti1Image('/home/remi/nilearn_data/development_fmri/development_fmri/sub-pixar123_task-pixar_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz')
[NiftiMasker.wrapped] Extracting region signals
[NiftiMasker.wrapped] Cleaning extracted signals
Traceback (most recent call last):
  File "/home/remi/github/nilearn/nilearn/tmp/filter_tmp.py", line 21, in <module>
    time_series = masker.fit_transform(
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/miniconda3/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/maskers/base_masker.py", line 307, in fit_transform
    return self.fit(X, **fit_params).transform(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/miniconda3/lib/python3.12/site-packages/sklearn/utils/_set_output.py", line 316, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/maskers/base_masker.py", line 254, in transform
    return self.transform_single_imgs(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/maskers/nifti_masker.py", line 583, in transform_single_imgs
    data = self._cache(
           ^^^^^^^^^^^^
  File "/home/remi/miniconda3/lib/python3.12/site-packages/joblib/memory.py", line 577, in __call__
    return self._cached_call(args, kwargs, shelving=False)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/miniconda3/lib/python3.12/site-packages/joblib/memory.py", line 532, in _cached_call
    return self._call(call_id, args, kwargs, shelving)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/miniconda3/lib/python3.12/site-packages/joblib/memory.py", line 771, in _call
    output = self.func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/maskers/nifti_masker.py", line 128, in _filter_and_mask
    data, affine = _filter_and_extract(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/maskers/base_masker.py", line 136, in _filter_and_extract
    region_signals = cache(
                     ^^^^^^
  File "/home/remi/miniconda3/lib/python3.12/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/signal.py", line 713, in clean
    filter_type = _check_filter_parameters(filter, low_pass, high_pass, t_r)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/signal.py", line 1124, in _check_filter_parameters
    raise ValueError(
ValueError: Repetition time (t_r) and low cutoff frequency (high_pass) must be specified for cosine filtering.t_r='2', high_pass='0.01'
```

This seems due to a too stringent check where `t_r` must be a float and canot an `int`.

https://github.com/nilearn/nilearn/blob/8c4e2e59fc25bedc46d196922751765cd881e3c6/nilearn/signal.py#L1121-L1128

**Comment by Remi-Gau** [comment]
> the clean part of masker is done in the base masker test:
> https://github.com/nilearn/nilearn/blob/main/nilearn/maskers/tests/test_base_masker.py

yeah but in this single case we have no extra arguments passed to clean in the dict: https://github.com/nilearn/nilearn/blob/6b2669120f28d449b4357a79d053a9457d7a2386/nilearn/maskers/tests/test_base_masker.py#L87

**Comment by ekhella** [comment]
Hi @Remi-Gau ,

Thanks a lot for the feedback and examples, I completely agree with your points regarding scikit-learn compliance, the need for additional tests for clean, and fixing the t_r parameter type check.

I’m now a bit unsure about the direction for this issue—should we close it and open a new one to focus on tests and compliance? Or should I continue working on this PR to make the changes?

Happy to adapt based on what you think is best.

Best regards,

**Comment by Remi-Gau** [comment]
> fixing the t_r parameter type check

I opened a PR to fix this

**Comment by Remi-Gau** [comment]
> open a new one to focus on tests

Yeah I will close this issue and let you open another one where we can start discussing adding tests to better cover the cleaning behavior of the maskers

**Comment by Remi-Gau** [comment]
- for compliance there is already this issue: https://github.com/nilearn/nilearn/issues/4538

**Comment by ekhella** [comment]
> > open a new one to focus on tests
> 
> Yeah I will close this issue and let you open another one where we can start discussing adding tests to better cover the cleaning behavior of the maskers

https://github.com/nilearn/nilearn/issues/4805 👍
