### ISSUE TITLE
Precision error in CanICA test in pre-release environment

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3441]
The test `nilearn/decomposition/tests/test_canica.py::test_canica_square_img` fails due to a precision error in ubuntu-latest (`ubuntu-22.04`) pre-release environment: https://github.com/nilearn/nilearn/actions/runs/3577698793/jobs/6017001262

See also: https://github.com/nilearn/nilearn/pull/3430#issuecomment-1331867028

We can look into improving the test.

**Comment by ymzayek** [comment]
I'm having trouble tracing the source of this error as well as similar errors now seen in other ubuntu runners with different python versions and another error `test_canica.py::test_percentile_range` on macos runner. See the following run for example: https://github.com/nilearn/nilearn/actions/runs/3684037424
I cannot reproduce any on my machine (`ubuntu-20.04`) or on `ubuntu-22.04` container. I've tried both pre-release environment and latest environment. Anyone have any ideas?

**Comment by bthirion** [comment]
Could you check with a macos user ? I guess there are some in the team. The problematic thing is that some components are not estimated or estimated with nans.
Among other things that could be tried, 
* set the rng
* add noise on the data generation, i.e. `_make_canica_test_data(noisy=True)`

**Comment by ymzayek** [comment]
I'll look into the noise parameter.
The seeding for the rng seems to be done correctly.
@tsalo I think uses a mac. If so, would you look into reproducing that error?

**Comment by tsalo** [comment]
I'll give it a shot.

**Comment by tsalo** [comment]
`test_canica_square_img` passed locally on my Mac (OSX 13.0.1), on a fresh 3.10 environment with only Nilearn (up-to-date with main) and its base and testing dependencies installed. Is there anything I need to modify, or should that have reproduced the error?

**Comment by ymzayek** [comment]
@tsalo thanks for trying. Can you look at the test `test_canica.py::test_percentile_range` because for macos this seems to be failing rather than `test_canica_square_img`
See the job failure here for more specifications about the setup: https://github.com/nilearn/nilearn/actions/runs/3684037424/jobs/6233303480

That being said I haven't been able to reproduce failure in `test_canica_square_img` locally but only tried to debug by ssh into the runner

**Comment by tsalo** [comment]
`test_percentile_range` failed once for me, but as soon as I started playing with the code it started passing. I have no clue why.
