### ISSUE TITLE
User Guide Latex errors 

### ISSUE THREAD

**Issue by AsliErdemli** [nilearn/nilearn#3443]
The https://nilearn.github.io/stable/glm/glm_intro.html#fmri-data-modelling page of the user guide is full of Latex compiling errors. 

Nilearn version:
The web page is displayed via Firefox 107.0 (64-bit) through Windows and Ubuntu. 
### Expected behavior
We expect the latex formulas to be readable

### Actual behavior
We see a paragraph full of Latex compiling errors

### Steps and code to reproduce bug

```python

```

**Comment by ymzayek** [comment]
Hi @AsliErdemli thanks for reporting. These are fixed in the development docs https://nilearn.github.io/dev/glm/glm_intro.html#fmri-data-modelling and will show up correctly in the stable docs in the new release that's coming up.

**Comment by ymzayek** [comment]
Closing this issue since the rendering has been fixed
