### ISSUE TITLE
Remove notes in docstrings of `nilearn.glm` classes and functions saying they are experimental

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3447]
Now that we removed the FutureWarning saying that `nilearn.glm` is experimental I think we can also remove the notes in the docstrings of the classes/functions under this module that say that they are experimental

### Affected pages
e.g. 
https://nilearn.github.io/stable/modules/generated/nilearn.glm.Contrast.html#nilearn.glm.Contrast
https://nilearn.github.io/stable/modules/generated/nilearn.glm.compute_contrast.html#nilearn.glm.compute_contrast

**Comment by bthirion** [comment]
Yes ! We can also remove alussion to switching from nistats to nilearn, that are outdated now.
Thx,
