### ISSUE TITLE
Remove ci-skip action from GitHub Actions workflows

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3448]
GitHub Actions now supports skipping workflows out of the box: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs and so the Action mstachniuk/ci-skip is deprecated and should be removed from all workflows before it starts failing.

**Comment by bthirion** [comment]
Sorry, I dont find the mstachniuk/ci-skip you're referring to ? Best,

**Comment by ymzayek** [comment]
It's used in some configurations in `nilearn/.github/workflows` such as `pep8.yml` and `testing.yml`

**Comment by ymzayek** [comment]
https://github.com/nilearn/nilearn/blob/fd44c36fb6f312933a684efff9a87122dfb6d7b7/.github/workflows/pep8.yml#L21

**Comment by bthirion** [comment]
Thx !
