### ISSUE TITLE
Function `non_parametric_inference` ignores any covariates

### ISSUE THREAD

**Issue by jrdalenberg** [nilearn/nilearn#3464]
The function [`non_parametric_inference`](https://github.com/nilearn/nilearn/blob/b556cd1a293e0f8396ea854b9a73214a8bbd1262/nilearn/glm/second_level/second_level.py#L593) extracts [a target contrast from the input design matrix](https://github.com/nilearn/nilearn/blob/b556cd1a293e0f8396ea854b9a73214a8bbd1262/nilearn/glm/second_level/second_level.py#L848) to perform a non-parametric test using the function [`permuted_ols`](https://github.com/nilearn/nilearn/blob/b556cd1a293e0f8396ea854b9a73214a8bbd1262/nilearn/glm/second_level/second_level.py#L854). However, any covariates/confounding variates are ignored here. So, currently, users are unable to perform non-parametric inference tests in the context of covariates.

Also see NeuroStars discussion: https://neurostars.org/t/dof-in-nilearns-non-parametric-inference/24416

**Comment by bthirion** [comment]
Thx !
