### ISSUE TITLE
binarize_img seems incorrect used on images with negative values

### ISSUE THREAD

**Issue by smeisler** [nilearn/nilearn#3467]
Hi Nilearn devs,
 I am working with kind of a strange ROI mask from a public dataset, where the background = -1 (black), cortical surface = 0 (dark gray), and ROIs of interest have values >= 1 (light gray and white). See the picture below.
<img width="462" alt="image" src="https://user-images.githubusercontent.com/27028726/212767285-f0c4a0d0-f7f4-4cb0-b28d-a5cdc665d39e.png">
Sure the numbering conventions are a bit odd, but I am just trying to extract the ROI masks, so thresholding at 0 with `binarize_img` should do the trick in theory.

Nilearn version: 0.10.0

### Expected behavior
Should result in an image with the ROI masks at value 1 and 0 everywhere else

### Actual behavior
The binarized image has 0s along the cortical surface (as expected), but 1s **everywhere** else (**background** and ROIs of interest). It appears that perhaps `binarize_img` may be using the magnitude of the values without considering the sign. Otherwise, why would the background (originally valued at -1) now survive 0-thresholding?
<img width="462" alt="image" src="https://user-images.githubusercontent.com/27028726/212768050-7257a425-3576-4e9c-9256-73b0aa879c7d.png">

### Steps and code to reproduce bug
```
roi = '/PATH/TO/lh.floc-bodies.nii.gz'
roi_binary = binarize_img(roi,threshold=0)
roi_binary.to_filename('ROI_check.nii.gz')
```
the ROI can be found here: https://drive.google.com/file/d/1EDNvsLolU496ur5ILe2hXv1CK80BjXs6/view?usp=sharing

Thank you,
Steven

**Comment by smeisler** [comment]
I see what is happening, looking at the [`binarize_img` code](https://github.com/nilearn/nilearn/blob/37f7b0b0/nilearn/image/image.py#L1044).

```
return math_img(
        "img.astype(bool).astype(int)",
        img=threshold_img(img, threshold, mask_img=mask_img)
    )
```
`bool(-1)` is TRUE, so the -1 values are treated the same as positive. Perhaps there's a more robust method than booleans that can be used here.

**Comment by bthirion** [comment]
It means that you want to threshold before binarizing. I'm wondering whether the best thing to do is not to document the behavior through an example (?).

**Comment by smeisler** [comment]
I was able to get around this by just using: `math_img("roi>0", roi=roi)` (where 0 is the threshold)

**Comment by bthirion** [comment]
Getting back to this, I find  this behavior awkward (and actually inconsistent with the docstring). We should fix that. Here is a small example to reproduce it:
```
from nilearn import datasets
from nilearn.image import binarize_img
from nilearn.plotting import plot_stat_map, plot_roi, show
stat_img = datasets.load_sample_motor_activation_image()
bin_img = binarize_img(stat_img, threshold=2.0)
cut_coords = (5, -26, 21)
plot_stat_map(stat_img, cut_coords=cut_coords)
plot_roi(bin_img, cmap='Paired', cut_coords=cut_coords)
show()
```

**Comment by bthirion** [comment]
@smeisler would you be interested in addressing it ?

**Comment by smeisler** [comment]
Sure!

**Comment by smeisler** [comment]
I was thinking of expanding the `binarize_img` to have more flexible operators (e.g., allow for `<` `>` `<=` comparisons, etc.) It is easy to implement if one removes the reliance on `threshold_img`, but then it becomes hard to keep the string usage (e.g., inputting `80%`). I am thinking if I change `threshold_img` to allow for more flexible operators instead, then changing `binarzing_img` would be simpler.

**Comment by bthirion** [comment]
But, then aren't you reinventing `math_img` ?

**Comment by smeisler** [comment]
Not quite, because if I were to just to apply the operator on an image, it would return a boolean image. The outputs of `binarize_image` are expected to be integers.

That being said, for now if we want to only fix `binarize_img` to work better with negative valued images, I think it would be as simple as passing `two_sided=False` into the `threshold_img` command, which would avoid negative values being counted. We could add a `two_sided` argument so one can do absolute value operations if requested. Of note is that for this change to not be a breaking change, `two_sided` will have to be `True` until presumable the default behavior is changed in a later release. Does that sound reasonable to you?
