### ISSUE TITLE
Haxby2001 Anat missing for Subject 6

### ISSUE THREAD

**Issue by eickenberg** [nilearn/nilearn#347]
I am having trouble recalling why this was. I would like to put a note in the docstring of the dataset fetcher in order to keep people from thinking they are doing something wrong. Was it broken or completely unavailable upstream already?

**Comment by GaelVaroquaux** [comment]
> Was it broken or completely unavailable upstream already?

I believe that's the case: it's an upstream problem.

**Comment by AlexandreAbraham** [comment]
I confirm.
