### ISSUE TITLE
image generated by `plot_surf_stat_map` has different aspect when saved in png vs pdf

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#3470]
The aspect of a saved 3d image depends on whether it was saved as pdf or png.
Could be a matplotlib bug.

### Expected behavior
The images should be identical

### Steps and code to reproduce bug

```python
from nilearn import datasets
from nilearn import surface
from nilearn import plotting

motor_images = datasets.fetch_neurovault_motor_task()
stat_img = motor_images.images[0]
fsaverage = datasets.fetch_surf_fsaverage()
texture = surface.vol_to_surf(stat_img, fsaverage.pial_right)

output_file = '/tmp/plop.pdf'
fig = plotting.plot_surf_stat_map(
    fsaverage.infl_right, texture, hemi='right',
    threshold=1., bg_map=fsaverage.sulc_right,
    output_file=output_file
)

output_file = '/tmp/plop.png'
fig = plotting.plot_surf_stat_map(
    fsaverage.infl_right, texture, hemi='right',
    threshold=1., bg_map=fsaverage.sulc_right,
    output_file=output_file
)
```

**Comment by ymzayek** [comment]
Hi @bthirion I do see a difference in the shadings that might be related to the quality. I think this is inherent in the file type but I do not know much about it.
If you meant the aspect ratio, I do not see a difference in that. (Sorry if I misunderstand the terminology!)

**Comment by jeromedockes** [comment]
Hi, same for me -- the pdf brain is transparent whereas the other one is not. aspect ratio seems the same. do these plots look like the ones you obtained @bthirion ?

![plop](https://user-images.githubusercontent.com/9196501/213671279-3ec8c18c-7dd8-460d-911e-acbac1df687a.png)

[plop.pdf](https://github.com/nilearn/nilearn/files/10465344/plop.pdf)

If the difference is the transparency of the background map, we are planning to get rid of that anyway as discussed in #3173

**Comment by jeromedockes** [comment]
I guess the bug is that the brain is transparent (and we see the wireframe) in the pdf image, even when we specify alpha=1 and it should be completely opaque?

**Comment by jeromedockes** [comment]
![screenshot_2023-01-20T07:22:25-03:00](https://user-images.githubusercontent.com/9196501/213672480-94b185f7-345f-4077-a07d-5d9236076a6f.png)

it seems like the triangles are opaque (as they should be), but we actually see through the edges/interstices between the triangles. we should probably look into how we can give a color to the wireframe edges, or set their width?

**Comment by bthirion** [comment]
> Hi, same for me -- the pdf brain is transparent whereas the other one is not. aspect ratio seems the same. do these plots look like the ones you obtained @bthirion ?
> 
> ![plop](https://user-images.githubusercontent.com/9196501/213671279-3ec8c18c-7dd8-460d-911e-acbac1df687a.png)
> 
> [plop.pdf](https://github.com/nilearn/nilearn/files/10465344/plop.pdf)
> 
> If the difference is the transparency of the background map, we are planning to get rid of that anyway as discussed in #3173

OK, thx.

**Comment by alishakodibagkar** [comment]
I can look into this

**Comment by alishakodibagkar** [comment]
An update, if we set, rasterized=True when plotting the mesh, the mesh is converted into pixels, which removes the gaps between the triangles when saving to a .pdf but also slightly decreases the quality of the image (similar quality to the .png)

[plop_not_rasterized.pdf](https://github.com/nilearn/nilearn/files/12113184/plop_not_rasterized.pdf)

[plop_rasterized.pdf](https://github.com/nilearn/nilearn/files/12113186/plop_rasterized.pdf)
