### ISSUE TITLE
Azure Pipelines test on Windows with Python 3.9 fails sometimes 

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3482]
The workflow is failing because it's timing out while running pytest. A possible solution is to set a timeout that exceeds 60m if the service allows it for free.

Also need to check if there are certain tests taking longer than usual for any particular reason since the testing runs in 38 minutes on successful runs.

Example failure:
https://dev.azure.com/Parietal/Nilearn/_build/results?buildId=5336&view=logs&j=57060dbb-acbf-556b-a6e6-e748b9693eea

**Comment by bthirion** [comment]
38 minutes seems huge. Some while ago, they were taking about 15 minutes. We have drifted ...
We should identify the longest tests and adapt them.

**Comment by ymzayek** [comment]
Yea maybe there can be some optimization. It does seem to differ per system also. Seems to take as long or a bit less on MacOS and about 10 minutes less on Ubuntu. Unfortunately the logs for Windows are limited to one month ago and they all seem to take around 40min or more.

**Comment by ymzayek** [comment]
I can trace this to this merge: https://github.com/nilearn/nilearn/commit/ca20d16a5e05d818fc5795715980f9a02451d5cb#diff-415749d8070e468d44ca7ca65fee86f625a7698878eac66afc6aa207b467e384
I think after changing the default resolution of the structural data fetchers to 1mm, tests that load this data without specifying a resolution are using higher resolution templates than before this was merged and this could be leading to the slow down. I think simply updating the tests so a low resolution template is provided would remedy this.

**Comment by bthirion** [comment]
Excellent point. yes, we have to do that.
