### ISSUE TITLE
Avoid that Sphinx full build exits with error as soon as first warning is encountered

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3493]
Sphinx is set to error out when encountering the first warning in a full build. We can set the flag `--keep-going` to let it finish the build and report all the warnings that may come after. It will still exit with an error and the build will fail but then we can quickly see all the warnings that need to be handled. See Sphinx build options: https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-keep-going

**Comment by Remi-Gau** [comment]
That'd be great.

I was seeing some minor warning in the doc build in CI and I wanted start cleaning up.

For example: https://github.com/nilearn/nilearn/actions/runs/4122627440/jobs/7119633978#step:33:323

**Comment by ymzayek** [comment]
Yes I see. Those are coming from numpydoc. They are not considered errors by the sphinx build but indeed we can resolve them. Maybe it can wait until these files are formatted with black if it will handle them but feel free to resolve separately anyways.

**Comment by Remi-Gau** [comment]
Tackling some of the content of the doc folder was next on my list: let's see how much black can fix and what else will actually need some elbow grease.

**Comment by Remi-Gau** [comment]
> formatted with black if it will handle them

FYI black does not autofix rst underline errors.

Had to do it manually in PR #3491
https://github.com/nilearn/nilearn/pull/3491/commits/18c9758cc74f76cf8a17c965ee699458f941c390

Let me know if I should open a separate issue to keep track of this.

**Comment by ymzayek** [comment]
I think we can try to fix them along with the reformatting of each module. And since they do not error out the build I think this is minor and can be handled at a later point. But if it helps you to track it feel free to open an issue.

**Comment by Remi-Gau** [comment]
Will open a separate issue. Better for my memory and also because it is different from #2528 as it cannot be automated.
