### ISSUE TITLE
Move _mix_colormaps() util function

### ISSUE THREAD

**Issue by alexisthual** [nilearn/nilearn#3499]
This is a follow-up issue from #3173.

`plotting.html_surface._mix_colormaps()` should be moved to `plotting._utils` or `plotting.cm` in order to be more easily accessed from the rest of the codebase.

**Comment by deepgohil** [comment]
I would like to solve this issue. can you specify path of this files

**Comment by alexisthual** [comment]
Hi @deepgohil!
#3173 hasn't been merged yet, so you can't work on this yet.
I can assign you to this issue and ping you when the previous PR gets merged if you want!

**Comment by ymzayek** [comment]
Hi @deepgohil would you still like to work on this? It's now possible
