### ISSUE TITLE
Renaming plotting.html_surface.one_mesh_info() and plotting.html_surface.full_brain_info()

### ISSUE THREAD

**Issue by alexisthual** [nilearn/nilearn#3500]
This is a follow-up issue from #3173.

`plotting.html_surface.one_mesh_info()` and `plotting.html_surface.full_brain_info()` should be renamed to `plotting.html_surface._one_mesh_info()` and `plotting.html_surface._full_brain_info()` respectively so that it becomes explicit that they're not in the public API.

**Comment by mehrdadbn9** [comment]
hi would you please assign me i would like to start contribute 
@alexisthual

**Comment by Rahul-Brito** [comment]
Tried to fix it here https://github.com/nilearn/nilearn/pull/3847
