### ISSUE TITLE
Deprecate darkness in surf_plotting functions

### ISSUE THREAD

**Issue by alexisthual** [nilearn/nilearn#3501]
This is a follow-up issue from #3173.

We should start a deprecation cycle for `darkness` in all functions in `plotting.surf_plotting`.
Indeed, this parameter is currently used to set a maximum value to a scaled background map (ie whose values are in [0,1]): `bg_map = darkness * bg_map`.
In the future, background maps will no longer be scaled by `nilearn`, so it no longer makes sense to have a `darkness` parameter.

**Comment by alishakodibagkar** [comment]
I can work on this!

**Comment by Remi-Gau** [comment]
@alishakodibagkar I assigned you to it.
Let me know if you need help

**Comment by ymzayek** [comment]
@alexisthual any reason not to also deprecate it in `html_surface._get_vertex_color` ?

**Comment by alexisthual** [comment]
I had a look at `html_surface.py` again and I think it should be deprecated there as well :)
I think you can deprecate it everywhere.
