### ISSUE TITLE
Document default values of parameters

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3519]
Regarding where to put the default value.
Had a small chat with @jeromedockes about this.
He rightly suggested another possibility: only keep the default value mentioned in the signature of the function which avoids any eventual inconsistency between the signature and the docstring.

_Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/issues/3491#issuecomment-1436694709_

Note that this stylistic decision should probably go along with an update of the documentation for contributors.

**Comment by ymzayek** [comment]
I can pick this up module by module following your reformatting trail

**Comment by bthirion** [comment]
I'm unsure what we should do here. This is typically a place where I would stick to standard conventions: shouldn't we stick to Numpydoc conventions ?

**Comment by Remi-Gau** [comment]
The problem is that I find the numpydoc convention is a bit underspecified:
https://numpydoc.readthedocs.io/en/latest/format.html#parameters

The only thing that feels "obligatory" is the 'optional'. Having the default along with the type or the description is a "can have"

Copy pasting the section below:

<hr>

For the parameter types, be as precise as possible. Below are a few examples of parameters and their types.

```python
  Parameters
  ----------
  filename : str
  copy : bool
  dtype : data-type
  iterable : iterable object
  shape : int or tuple of int
  files : list of str
```

If it is not necessary to specify a keyword argument, use optional:

```python
   x : int, optional
```

Optional keyword parameters have default values, which are displayed as part of the function signature. 
They can also be detailed in the description:

```python
  Description of parameter `x` (the default is -1, which implies summation
  over all axes).
```

or as part of the type, instead of optional. 

These are all equivalent:

```python
  copy : bool, default True
  copy : bool, default=True
  copy : bool, default: True
```

If the default value would not be used as a value, optional is preferred.

**Comment by bthirion** [comment]
I can see that sklearn put the default in the parameter description, but e.g. MNE does not.  I feel that we should at least be sure we have a consensus among coredevs on this.

**Comment by ymzayek** [comment]
Maybe I was too hasty to implement this. I think during the last coredev meeting discussion we did decide to keep them but to follow the numpydoc style (change their location to the type definition). But then the decision to remove them altogether came from a separate discussion during a drop-in hour.

During the coredev meeting it didn't seem anyone had a strong opinion one way or the other and the reasoning of @jeromedockes makes sense in terms of avoiding inconsistencies. Happy to put it back on the agenda for next time.

**Comment by kchawla-pi** [comment]
I +1 removing the defaults from docstrings. Reading the signature suffices. All tools when showing the docstrings, also show the signature & default args.

**Comment by Remi-Gau** [comment]
For the record.

Default should be kept in the doc strings mentioned after the parameter type rather than at the end of the docstring.

Some examples

```python
def Good(x, y=1, z=None):
    """Good

    Parameters
    ----------
    x : :obj:`int`
        X

    y : :obj:`int`. Default=1
        Default=1 is preferred to "Defaults to 1."

    z : :obj:`str`, optional
        Use optional for None

    """
    ...

def Meh(x, y=1, z=None):
    """Meh

    Parameters
    ----------
    x : :obj:`int`
        X

    y : :obj:`int`. optional
        Y. Default=1

    z : :obj:`str`, optional
        Z
    """
    ...    

def Bad(x, y=1, z=None):
    """Bad

    Parameters
    ----------
    x : :obj:`int`
        X

    y : :obj:`int`
        Y

    z : :obj:`str`
        Z
    """
    ...  
```

That being said, I have a related question regarding the "shortcuts" to document parameters that are kept in https://github.com/nilearn/nilearn/blob/main/nilearn/_utils/docs.py

- is it possible to "override" content mentioned in those template description? More specifically the type and the default values?

It is it possible to append a text at the end of those template: 

See for example here:
https://github.com/nilearn/nilearn/blob/492718f40982ffc05aba33113a80a19b383c10b0/nilearn/glm/first_level/first_level.py#L243-L244

So if it is not possible to override the content of those templates it may make things easier to keep the default value at the end of the docstring.

**Comment by ymzayek** [comment]
@Remi-Gau what we do instead of overriding from the respective docstring is define several versions using string substitutions like this:
https://github.com/nilearn/nilearn/blob/492718f40982ffc05aba33113a80a19b383c10b0/nilearn/_utils/docs.py#L18-L24

So you can move that default statement anywhere and sub in different values with the formatter. However, note that this could make it harder to track if default statements match the function signature. I think it should be ok if there isn't a big number of these and one parameter doesn't usually have a large number of different default values.

**Comment by Remi-Gau** [comment]
OK thanks for the explanation and I agree that it is better to minimize how many defaults those templates can accept.

But then we should start by moving the position of default to put it next to the types in `_utils.docs.py`? Feels like a good way to change the format in many places with less effort.

**Comment by ymzayek** [comment]
> But then we should start by moving the position of default to put it next to the types in `_utils.docs.py`? Feels like a good way to change the format in many places with less effort.
 
Yes sounds like a good plan!

**Comment by Remi-Gau** [comment]
This also sounds like an issue that can be split in many simple "good first issues" for the hackathon.

One contributor tackles one module per PR and first only deals with the public functions and methods because only those appear in the doc.

**Comment by mathdugre** [comment]
Hi, I can look into automating this process during the OHBM BrainHack.
