### ISSUE TITLE
Document all GitHub Actions workflows

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3543]
The [README.md](https://github.com/nilearn/nilearn/blob/main/.github/workflows/README.md) in `.github/workflows` only documents the documentation build workflow. It can be useful to comprehensively document all the GiHub Actions workflows here. 

Linking comments: https://github.com/nilearn/nilearn/pull/3536#pullrequestreview-1315426922 and https://github.com/nilearn/nilearn/pull/3536#issuecomment-1446297374

**Comment by Remi-Gau** [comment]
Would it make sense to also centralize all the "format + spelling" checkers into a single "validate" workflow with several jobs ?

May also reduce the number of entries in CI reports.

**Comment by ymzayek** [comment]
@Remi-Gau we could but I don't see why it's necessary and would make things a bit more "hidden". 

> May also reduce the number of entries in CI reports.

What do you mean?

**Comment by Remi-Gau** [comment]
> @Remi-Gau we could but I don't see why it's necessary and would make things a bit more "hidden". 
> 
> > May also reduce the number of entries in CI reports.
> 
> What do you mean?

Forget that. I was thinking of something else.
