### ISSUE TITLE
Update examples that use old atlas API to showcase new behavior

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3547]
After merge #3353, examples that use the now deprecated API for 3 atlases need to be updated.

Effected examples:
- examples/00_tutorials/plot_3d_and_4d_niimg.py
- examples/01_plotting/plot_multiscale_parcellations.py
- examples/01_plotting/plot_prob_atlas.py

**Comment by bthirion** [comment]
@achamma723 can you take care of that ?

**Comment by achamma723** [comment]
> @achamma723 can you take care of that ?

Hello @bthirion, sure I'll work on it!
