### ISSUE TITLE
flaky test: `/test_canica.py::test_masker_attributes_passing_masker_arguments_to_estimatort`

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3573]
Only seen it once so far

nilearn/decomposition/tests/test_canica.py::test_masker_attributes_with_fit
https://github.com/nilearn/nilearn/actions/runs/4346883155/jobs/7593499296#step:8:16213

---

EDIT after refactoring from https://github.com/nilearn/nilearn/pull/3572

test in question:

https://github.com/nilearn/nilearn/blob/main/nilearn/decomposition/tests/test_canica.py#L245

**Comment by bthirion** [comment]
That's weird.

**Comment by Remi-Gau** [comment]
More info here: 

[test_masker_attributes_with_fit](https://github.com/nilearn/nilearn/actions/runs/4346883155/jobs/7593499296#step:8:9752)

Note that I am refactoring the test in: https://github.com/nilearn/nilearn/pull/3572

**Comment by Remi-Gau** [comment]
> That's weird.

agreed

Cannot wrap my head as to why this would happen: I'd say let's wait and see how often it pops up before labelling it as flaky

**Comment by Remi-Gau** [comment]
closing this one for now as this never resurfaced in a month

**Comment by ymzayek** [comment]
I haven't looked into the test but it seems to only fail on macos so it could be a system related precision error

**Comment by Remi-Gau** [comment]
https://github.com/nilearn/nilearn/actions/runs/4786538398/jobs/8510594297

```
FAILED nilearn/decomposition/tests/test_canica.py::test_masker_attributes_passing_masker_arguments_to_estimator - ValueError: array must not contain infs or NaNs
```

**Comment by Remi-Gau** [comment]
previous failure was on MacOS too with python 3.10 as well.

**Comment by Remi-Gau** [comment]
reopening the issue as this seems but to be not a fluke even if VERY rare failure.

**Comment by Remi-Gau** [comment]
Another instance of this once in a blue moon flaky test: https://github.com/nilearn/nilearn/actions/runs/6250612134/job/16969857536#step:8:14562

from https://github.com/nilearn/nilearn/pull/3992

On MacOS with pyhon 3.10

<details>
<pre>

__________________ test_passing_masker_arguments_to_estimator __________________

canica_data = [<nibabel.nifti1.Nifti1Image object at 0x12e125720>, <nibabel.nifti1.Nifti1Image object at 0x12e127dc0>]

    def test_passing_masker_arguments_to_estimator(canica_data):
        dict_learning = DictLearning(
            n_components=3,
            target_affine=np.eye(4),
            target_shape=(6, 8, 10),
            mask_strategy="background",
        )
>       dict_learning.fit(canica_data)

nilearn/decomposition/tests/test_dict_learning.py:178: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
nilearn/decomposition/_base.py:452: in fit
    self._raw_fit(data)
nilearn/decomposition/dict_learning.py:283: in _raw_fit
    self._init_dict(data)
nilearn/decomposition/dict_learning.py:260: in _init_dict
    canica._raw_fit(data)
nilearn/decomposition/canica.py:294: in _raw_fit
    self._unmix_components(components)
nilearn/decomposition/canica.py:223: in _unmix_components
    results = Parallel(n_jobs=self.n_jobs, verbose=self.verbose)(
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/joblib/parallel.py:1863: in __call__
    return output if self.return_generator else list(output)
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/joblib/parallel.py:1792: in _get_sequential_output
    res = func(*args, **kwargs)
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/joblib/memory.py:353: in __call__
    return self.func(*args, **kwargs)
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/sklearn/utils/_param_validation.py:211: in wrapper
    return func(*args, **kwargs)
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/sklearn/decomposition/_fastica.py:337: in fastica
    S = est._fit_transform(X, compute_sources=compute_sources)
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/sklearn/decomposition/_fastica.py:647: in _fit_transform
    W, n_iter = _ica_par(X1, **kwargs)
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/sklearn/decomposition/_fastica.py:118: in _ica_par
    W1 = _sym_decorrelation(np.dot(gwtx, X.T) / p_ - g_wtx[:, np.newaxis] * W)
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/sklearn/decomposition/_fastica.py:61: in _sym_decorrelation
    s, u = linalg.eigh(np.dot(W, W.T))
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/scipy/linalg/_decomp.py:460: in eigh
    a1 = _asarray_validated(a, check_finite=check_finite)
../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/scipy/_lib/_util.py:240: in _asarray_validated
    a = toarray(a)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

a = array([[265.08192018,          nan,  -8.84412268],
       [         nan,          nan,          nan],
       [ -8.84412268,          nan, 352.84901275]])
dtype = None, order = None

    @set_module('numpy')
    def asarray_chkfinite(a, dtype=None, order=None):
        """Convert the input to an array, checking for NaNs or Infs.
    
        Parameters
        ----------
        a : array_like
            Input data, in any form that can be converted to an array.  This
            includes lists, lists of tuples, tuples, tuples of tuples, tuples
            of lists and ndarrays.  Success requires no NaNs or Infs.
        dtype : data-type, optional
            By default, the data-type is inferred from the input data.
        order : {'C', 'F', 'A', 'K'}, optional
            Memory layout.  'A' and 'K' depend on the order of input array a.
            'C' row-major (C-style),
            'F' column-major (Fortran-style) memory representation.
            'A' (any) means 'F' if `a` is Fortran contiguous, 'C' otherwise
            'K' (keep) preserve input order
            Defaults to 'C'.
    
        Returns
        -------
        out : ndarray
            Array interpretation of `a`.  No copy is performed if the input
            is already an ndarray.  If `a` is a subclass of ndarray, a base
            class ndarray is returned.
    
        Raises
        ------
        ValueError
            Raises ValueError if `a` contains NaN (Not a Number) or Inf (Infinity).
    
        See Also
        --------
        asarray : Create and array.
        asanyarray : Similar function which passes through subclasses.
        ascontiguousarray : Convert input to a contiguous array.
        asfarray : Convert input to a floating point ndarray.
        asfortranarray : Convert input to an ndarray with column-major
                         memory order.
        fromiter : Create an array from an iterator.
        fromfunction : Construct an array by executing a function on grid
                       positions.
    
        Examples
        --------
        Convert a list into an array.  If all elements are finite
        ``asarray_chkfinite`` is identical to ``asarray``.
    
        >>> a = [1, 2]
        >>> np.asarray_chkfinite(a, dtype=float)
        array([1., 2.])
    
        Raises ValueError if array_like contains Nans or Infs.
    
        >>> a = [1, 2, np.inf]
        >>> try:
        ...     np.asarray_chkfinite(a)
        ... except ValueError:
        ...     print('ValueError')
        ...
        ValueError
    
        """
        a = asarray(a, dtype=dtype, order=order)
        if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
>           raise ValueError(
                "array must not contain infs or NaNs")
E           ValueError: array must not contain infs or NaNs

../../../hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/numpy/lib/function_base.py:630: ValueError
</pre>
</details>

**Comment by Remi-Gau** [comment]
Another failure on main:

- On MacOS with pyhon 3.9

https://github.com/nilearn/nilearn/actions/runs/7286199100/job/19854475464

**Comment by Remi-Gau** [comment]
Not seen this one in a while.
Will close. Most likely this will cause it to reappear.
