### ISSUE TITLE
My picture is stretched in 'Making a surface plot of a 3D statistical map'.

### ISSUE THREAD

**Issue by nylsp** [nilearn/nilearn#3575]
Hi, everyone!

I'm trying to analyze the gliomas frequency in each imaging voxel. I first concatenated all the binary tumor mask(registered into MNI 512 space), and got the tumor frequency map(tumor_frequcency.nii). Then, I applied to the AAL3v1.nii  and averaged the frequency voxel in each brain subdivision to obtain each subdivision frequency(tumor_frequcency_AAL3v1.nii). The AAL3v1.nii spacing is 2*2*2mm.

Now, I want to plot tumor_frequcency_AAL3v1.nii onto a surface. The example is as below, but my result is stretched.

my result:
![5edf7ce3390243b7134964c24216810](https://user-images.githubusercontent.com/48861478/223392769-f37dacae-7c7e-4941-8c88-329af3f23985.png)
example:
![sphx_glr_plot_3d_map_to_surface_projection_006](https://user-images.githubusercontent.com/48861478/223392786-3bb78f9c-227a-49bc-bf4e-ab376dd4793e.png)

here is my code:
    tumor_map = nib.load('tumor_frequcency_AAL3v1.nii').get_fdata()
    fig = plotting.plot_img_on_surf(tumor_map,
                          views=['lateral', 'medial'],
                          hemispheres=['left', 'right'],
                          colorbar=True)
    plotting.show()

I don't know how to solve this problem. Given that the space of tumor_frequcency_AAL3v1.nii may be unmatch FreeSurfer's fsaverage5(nilearn default surface), I think I may create the AAL3v1.nii surface by Freesurfer. However, it seems that it isn't the usually way to relate anatomical template, AAL3, to Freesurfer, which more focus on the cortex parcellation.

**Comment by bthirion** [comment]
Hi,
I think that this type of discussion should rather got on Neurostars. As far as I understand, the figure shape does not depend on what is plotted. Do you resize/reshape the figure in some way ?

**Comment by nylsp** [comment]
> 
I test like this:
    tumor_map = nib.load('tumor_frequcency_AAL3v1.nii').get_fdata()
    plt.figsize(figsize=(10,5))
    fig = plotting.plot_img_on_surf(tumor_map, views=['lateral', 'medial'],
                                                   hemispheres=['left', 'right'], colorbar=True)
    plt.figsize(figsize=(10,5))
    plotting.show()
It doesn't work.

**Comment by nylsp** [comment]
I test plt.figure(figsize=(10,5))

It doesn't work.

**Comment by nylsp** [comment]
I test plt.figure(figsize=(10,5)).

It doesn't work.

**Comment by bthirion** [comment]
In the above script, if your replace your image by *any* image shipped in Nilearn, you don't have the same stretching effect, right ? If yes, it would be great that you share us the image you use (replacing all values by noise if you want to keep the information private, since this has no influence on the display anyway).
