### ISSUE TITLE
warn for BIDS events file with no `trial_type` column

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3588]
Technically `trial_type` columns in BIDS events.tsv files are optional.

https://bids-specification.readthedocs.io/en/latest/modality-specific-files/task-events.html

So it can happen to have valid BIDS dataset with either no `trial_type` column or trial type information stored under a different column.

See from the BIDS examples:
- https://github.com/bids-standard/bids-examples/blob/master/ds000117/sub-01/ses-mri/func/sub-01_ses-mri_task-facerecognition_run-01_events.tsv

The default behavior of `make_first_level_design_mat` to create dummy events makes sense when there is no `trial_type` column but may not be appropriate when trial type information is stored under another column.

https://github.com/nilearn/nilearn/blob/5ed3b2471038c1098412196aa38c5232e166e445/nilearn/glm/first_level/design_matrix.py#L269

It may be nice to warn users by throwing a warning when events are collected by `first_level_from_bids`.

Note that this should happen rarely so the number of users affected should be low and they may probably already know about it if they have explored the dataset they are working with.

**Comment by vaswin0** [comment]
@Remi-Gau   Could you please assign this to me?

**Comment by Remi-Gau** [comment]
Done. 😊

**Comment by vaswin0** [comment]
@Remi-Gau what exactly should be the warning string here ? That "trial_type" column should be correctly named "trial_type" in the "events.tsv" file ?

**Comment by Remi-Gau** [comment]
I would say that if there is only an onset and duration column then there is no point throwing a warning.
If there are other columns but none called trial_type I would tell users all rows will be considered a belonging to the same condition and that if there is column of the data frame  containing trial information they may consider renaming it to trial_type.

**Comment by Remi-Gau** [comment]
By the way given that the first_level_from_bids function is going through a big refactoring you may want to just write a simple function to perform that check on a pandas data frame and throw the warning.

It will be easier to write a test for and prevent annoying merge conflicts later on.
