### ISSUE TITLE
is travis CI still used?

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3593]
silly question but is travis CI still being used / run ?

I have not seen it in action in any PR yet it seems that all the config files are still there.

**Comment by ymzayek** [comment]
No it's not used. To run it you need to add "[arm64]" to a commit message but I'm not sure this even works. I haven't tested it nor have seen it used anywhere. For now we're not supporting this architecture but this could be up for discussion.

**Comment by Remi-Gau** [comment]
Will do a dummy PR to test it: so at least we know.

**Comment by Remi-Gau** [comment]
Don't think that it worked.

If we want to keep this travis CI then it may be better to have run automatically on a regular basis: could set up a github workflow to trigger it every 2 or 3 weeks.

**Comment by ymzayek** [comment]
Sure we can try it. And maybe we can move it to Azure? I think it now supports arm64

**Comment by Remi-Gau** [comment]
Never played with azure, so it could be my first time to try.

**Comment by bthirion** [comment]
I think the sklearn team uses Azure indeed.

**Comment by jeromedockes** [comment]
as we don't use travis anymore I vote for deleting those config files to remove clutter

**Comment by jeromedockes** [comment]
ATM we use Azure to run tests on windows: https://dev.azure.com/Parietal/Nilearn/_build?definitionId=2&_a=summary

**Comment by Remi-Gau** [comment]
> as we don't use travis anymore I vote for deleting those config files to remove clutter

good with me


FYI I remember looking into getting some inspiration from sklearn to set up testing `[arm64]`  architecture (as this is what travis was supposed to to).

It seems that cirrus is used in sklearn:
https://github.com/scikit-learn/scikit-learn/blob/09118d976ff6444e43e8069774caf4db274bf956/build_tools/cirrus/arm_tests.yml#L5

I am not sure it can be done with azure: a quick look in the doc said "yes" but I was not able to get very far in terms of making it work.
