### ISSUE TITLE
use github issue forms ?

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3606]
Would there be any interest in using the github issue forms for people to submit issues?

Example: 
https://github.com/bids-standard/bids-specification/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBUG%5D+

**Comment by bthirion** [comment]
What is the advantage ? Less customization ?

**Comment by Remi-Gau** [comment]
You can have clearly defined dedicated sections: some of you can make required to post the issue "have search the issue log before posting?". 

You can have dropdown menus: I usually use to help users find the software versions they encountered bug on.

In terms of UI / UX I tend to find them easier to read and navigate than commented markdown.

**Comment by ymzayek** [comment]
I find the example nice and agree that the text boxes separated like that are easier to read/navigate. +1 for adding a link to neurostars to redirect people

**Comment by Remi-Gau** [comment]
> Compared to the "soft" template, it also prevents users to do the good old "select-all-delete-all-write-whatever-I-want" style of bug reports.

Technically we have blank issues for that and people can still open an empty bug issue and then edit the top post to remove the whole content, but it is more work.
