### ISSUE TITLE
Adding an option to easily build specific examples in a pull request

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3612]
I would like to make it easier to build examples in a particular example directory or just one example and have that be built by the documentation builder CI in a pull request and hence hosted by CircleCI for easy access. This can probably be done by adding a commit tag option (like we do for full builds). 

At the moment it is only possible to do a partial build without building any examples (the default), running only changed examples if the example scripts are changed, or doing a full build with the commit tag `[full doc]`. However, if code is changed in nilearn modules that could affect an example or a set of examples, these won't be built by the CI. This will be useful to be able to point reviewers to possible visual changes in e.g. plots in an example.

As an example, something like this triggers building all examples in a particular example directory such as `01_plotting`:

```bash
sphinx-build -D sphinx_gallery_conf.examples_dirs="../examples/01_plotting/" -D sphinx_gallery_conf.run_stale_examples=True -b html -d _build/doctrees -v . _build/html
```

Or to build a specific example or several following a pattern:

```bash
sphinx-build -D sphinx_gallery_conf.filename_pattern="plot_decoding_tutorial.py" -D sphinx_gallery_conf.run_stale_examples=True -b html -d _build/doctrees . _build/html
```

Sphinx gallery configs reference: https://sphinx-gallery.github.io/stable/configuration.html

**Comment by bthirion** [comment]
This perfectly makes sense.
