### ISSUE TITLE
Improve guidelines for adding and organizing unit tests

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3613]
Maybe we can also add something to the contributing docs to this section https://nilearn.github.io/stable/development.html#tests about

- adding a docstring
- test data generation scope and location

_Originally posted by @ymzayek in https://github.com/nilearn/nilearn/issues/3570#issuecomment-1479383445_

**Comment by Remi-Gau** [comment]
related to this: there are instances where utility functions used only for tests are in the folder `X` in a module called something like `X/testing.py` whereas in most cases in the rest of the code base it can be found in `X/tests/_utils.py`

Examples

- nilearn/datasets/_testing.py
- nilearn/surface/testing_utils.py

**Comment by ymzayek** [comment]
The issues in the original post have been addressed here: https://nilearn.github.io/stable/development.html#coding-style
and here https://nilearn.github.io/stable/development.html#tests

I'll close this issue and open a new one for https://github.com/nilearn/nilearn/issues/3613#issuecomment-1511578081
