### ISSUE TITLE
make sure public / private functions in _utils to start without / with a leading underscore

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3628]
From what I understood anything in the _utils folder is considered "private" so the leading underscore does not have to be systematic

Yes I'd say that that is the case

> I am completely fine trying to homogenize this to all leading-underscore which would be nice because private / non-private status of the function would be in the filename rather than in the parent folder where its module can be found.

Indeed let's follow up on that in a separate issue as it's not really related to this PR

_Originally posted by @ymzayek in https://github.com/nilearn/nilearn/pull/3525#discussion_r1151533681_

**Comment by Remi-Gau** [comment]
I suspect it'd be worth checking that all functions in any other module called `_utils` also starts with a leading underscore.

**Comment by jeromedockes** [comment]
wouldn't that hint the function is private to the current module?

**Comment by Remi-Gau** [comment]
> wouldn't that hint the function is private to the current module?

That may be because I am still a python noob but I am not sure I understand the nuance you are making.

Can you tell me what you mean by "private to the current module"? Or point to a something t

**Comment by Remi-Gau** [comment]
related to #3319

**Comment by jeromedockes** [comment]
yes I think so!
basically repeating the same thing as what you said with another example:

```
nilearn
├── image.py             # part of public API
├── __init__.py
├── maskers              # part of public API
│   ├── __init__.py
│   ├── nifti_masker.py  # part of public API
│   └── _validation.py   # private to the maskers module
└── _utils.py            # private to the nilearn module
```

inside of `maskers._validation.py`:

```python
import numpy as np # not part of the public API

__all__ = ["check_mask_img", "ValidationError"] # all symbols in the public API


def check_mask_img(mask_img):
    """Public API of _validation module

    can be used in nifti_masker module
    but not the image module (which cannot import maskers._validation),
    unless maskers/__init__.py imports it and lists it in __all__ 
    to make it part of the maskers module's public API
    """
    return _check_mask_shape(mask_img) and _check_mask_values(mask_img)


def _check_mask_shape(mask_img):
    """Private internal of _validation, cannot be used in nifti_masker"""


def _check_mask_values(mask_img):
    """Private internal of _validation, cannot be used in nifti_masker"""


class ValidationError(Exception):
    """Public API of _validation module"""


class _Validator:
    """Private internal of the _validation module"""

    def validate(self, img):
        """Public API of _Validator"""

    def _validate_shape(self, img):
        """Private internal of the _Validator class.

        As we don't use the double leading underscore in nilearn we cannot
        infer from the name alone if it is considered to be exposed to
        subclasses or not.

        """
```

**Comment by ymzayek** [comment]
These guidelines sound reasonable to me! Is this something to include in the docs as well? Either in https://nilearn.github.io/stable/maintenance.html or https://nilearn.github.io/stable/development.html?

**Comment by Remi-Gau** [comment]
I think that it would be a good idea to even start by adding this into the guidelines to make sure we are all exactly on the same page and then slowly start applying the guidelines.

**Comment by ymzayek** [comment]
@Remi-Gau I noticed that the PRs https://github.com/nilearn/nilearn/pull/3943 and https://github.com/nilearn/nilearn/pull/3939 are already not following the structure laid out above. Namely that functions in private _utils module should begin without an underscore when shared across files within a module. If we still agree on this, I'll volunteer to open a PR and "set it in stone" in the docs.

**Comment by Remi-Gau** [comment]
Go for it.
Will fix the open pr.
And can open another pr to fix the one already merged.
Thanks for the reminder. 🤗
