### ISSUE TITLE
[ENH] Return z-maps by `compute_fixed_effects`

### ISSUE THREAD

**Issue by alpinho** [nilearn/nilearn#3629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

`compute_fixed_effects` provides t-maps only but not z-maps.

### Benefits to the change

Obtain standardized results, thus not dependent on the number of degrees of freedom.

### Pseudocode for the new behavior, if applicable

```python
# insert your code below

```

**Comment by ymzayek** [comment]
@alpinho there is already an issue and PR related to this. See https://github.com/nilearn/nilearn/issues/3194 and corresponding https://github.com/nilearn/nilearn/pull/3203. We can try to push it forward.

**Comment by alpinho** [comment]
Ah, ok. I had read the issue #3194 but I skipped the detailed description that indeed incorporates what I mention in this issue.

**Comment by Remi-Gau** [comment]
closed by #3194
