### ISSUE TITLE
Many warnings in test suite

### ISSUE THREAD

**Issue by bcipolli** [nilearn/nilearn#363]
These should be investigated and, if not a concern in the tests, turned off within the relevant test code.  That will make the test output more readable, and distinguish between expected and unexpected warnings.

Pasting the current warnings here for reference.

* /home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2499: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)

* nilearn.decoding.tests.test_searchlight.test_searchlight ... /usr/lib/python2.7/dist-packages/joblib/parallel.py:138: UserWarning: Scikit-learn version is too old. scoring argument ignored
  self.results = func(*args, **kwargs)

* /home/travis/build/bcipolli/nilearn/nilearn/input_data/multi_nifti_masker.py:196: UserWarning: [MultiNiftiMasker.fit] Generation of a mask has been requested (imgs != None) while a mask has been provided at masker creation. Given mask will be used.
  ' will be used.' % self.__class__.__name__)

* /home/travis/build/bcipolli/nilearn/nilearn/decomposition/multi_pca.py:301: UserWarning: Caching has been enabled (memory_level = 3) but no Memory object or path has been provided (parameter memory). Caching deactivated for function randomized_svd.
  memory_level=self.memory_level)(
/home/travis/build/bcipolli/nilearn/nilearn/masking.py:261: UserWarning: Caching has been enabled (memory_level = 2) but no Memory object or path has been provided (parameter memory). Caching deactivated for function _compute_mean.
  mean_epi, affine = cache(_compute_mean, memory)(epi_img,
/home/travis/build/bcipolli/nilearn/nilearn/masking.py:427: UserWarning: Caching has been enabled (memory_level = 2) but no Memory object or path has been provided (parameter memory). Caching deactivated for function _compute_mean.

* /home/travis/build/bcipolli/nilearn/nilearn/signal.py:52: DeprecationWarning: Implicitly casting between incompatible kinds. In a future numpy release, this will raise an error. Use casting="unsafe" if this is intentional.
  signals /= std
/home/travis/build/bcipolli/nilearn/nilearn/signal.py:125: DeprecationWarning: Implicitly casting between incompatible kinds. In a future numpy release, this will raise an error. Use casting="unsafe" if this is intentional.
  signals -= np.mean(signals, axis=0)
/home/travis/build/bcipolli/nilearn/nilearn/signal.py:130: DeprecationWarning: Implicitly casting between incompatible kinds. In a future numpy release, this will raise an error. Use casting="unsafe" if this is intentional.
  regressor -= regressor.mean()
/home/travis/build/bcipolli/nilearn/nilearn/signal.py:134: DeprecationWarning: Implicitly casting between incompatible kinds. In a future numpy release, this will raise an error. Use casting="unsafe" if this is intentional.
  regressor /= std
/home/travis/build/bcipolli/nilearn/nilearn/mass_univariate/tests/test_permuted_least_squares.py:142: DeprecationWarning: Implicitly casting between incompatible kinds. In a future numpy release, this will raise an error. Use casting="unsafe" if this is intentional.

* /home/travis/build/bcipolli/nilearn/nilearn/decomposition/multi_pca.py:253: UserWarning: Parameter memory of the masker overriden
  % param_name)
/home/travis/build/bcipolli/nilearn/nilearn/decomposition/multi_pca.py:253: UserWarning: Parameter memory_level of the masker overriden
  % param_name)

* /home/travis/build/bcipolli/nilearn/nilearn/input_data/base_masker.py:144: UserWarning: Affine is different across subjects. Realignement on first subject affine forced
  warnings.warn('Affine is different across subjects.'

* /home/travis/build/bcipolli/nilearn/nilearn/mass_univariate/permuted_least_squares.py:140: RuntimeWarning: divide by zero encountered in divide
  return beta_targetvars_testedvars * np.sqrt((dof - 1.) / rss)

* /home/travis/build/bcipolli/nilearn/nilearn/plotting/tests/test_find_cuts.py:54: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  cut_value = data[cut]
/home/travis/build/bcipolli/nilearn/nilearn/plotting/tests/test_find_cuts.py:56: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  cut_value = data[..., cut]

* /home/travis/build/bcipolli/nilearn/nilearn/_utils/cache_mixin.py:86: UserWarning: Incompatible cache in /tmp/tmpx2t5Cj/joblib: old version of nibabel.
  "old version of nibabel." % cachedir)
/home/travis/build/bcipolli/nilearn/nilearn/_utils/cache_mixin.py:66: UserWarning: Incompatible cache in /tmp/tmpx2t5Cj/joblib: old version of nibabel. Deleting the cache. Put nilearn.check_cache_version to false to avoid this behavior.
  % cachedir)

* /home/travis/build/bcipolli/nilearn/nilearn/datasets.py:626: UserWarning: An error occured while fetching pymvpa-exampledata/bald.nii.gz
  warnings.warn('An error occured while fetching %s' % file_)

* /home/travis/build/bcipolli/nilearn/nilearn/tests/test_masking.py:169: DeprecationWarning: numpy boolean negative (the unary `-` operator) is deprecated, use the bitwise_xor (the `^` operator) or the logical_xor function instead.
  unmasked4D[-mask, :] = 0
/home/travis/build/bcipolli/nilearn/nilearn/tests/test_masking.py:172: DeprecationWarning: numpy boolean negative (the unary `-` operator) is deprecated, use the bitwise_xor (the `^` operator) or the logical_xor function instead.
  unmasked3D[-mask] = 0
/home/travis/build/bcipolli/nilearn/nilearn/tests/test_masking.py:213: DeprecationWarning: numpy boolean negative (the unary `-` operator) is deprecated, use the bitwise_xor (the `^` operator) or the logical_xor function instead.

* nilearn.tests.test_region.test_signal_extraction_with_maps_and_labels ... /usr/lib/python2.7/dist-packages/scipy/ndimage/measurements.py:545: RuntimeWarning: invalid value encountered in divide
  return sum / numpy.asanyarray(count).astype(numpy.float)

* packages/scipy/signal/filter_design.py:268: BadCoefficients: Badly conditioned filter coefficients (numerator): the results may be meaningless
  "results may be meaningless", BadCoefficients)

* nilearn.tests.test_signal.test_high_variance_confounds ... /usr/lib/python2.7/dist-packages/scipy/stats/stats.py:1367: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return values[idx]

**Comment by lesteve** [comment]
Reducing the warnings noise is a worthwhile goal. I am wondering how painful this would be to get rid of the numpy/scipy warnings across all the supported versions.

**Comment by AlexandreAbraham** [comment]
I thing we should the pertinent ones. For example, `numpy boolean negative (the unary - operator) is deprecated`. Fixing all of them is a lost battle. Some of these warnings are normal and should be kept.

I think the one about the memory should be fixed. For example, if you run a NiftiMasker with default parameters, you will get a warning. This annoys me a lot.

**Comment by GaelVaroquaux** [comment]
> I think the one about the memory should be fixed. For example, if you run a
> NiftiMasker with default parameters, you will get a warning. This annoys me a
> lot.

Agree. We should not raise a warning with default settings.

**Comment by bcipolli** [comment]
Debugging Python 3.x errors and warnings is challenging, as they mix with these existing warnings.  After completing the output PR, I will work on resolving these next.

Note that some of the warnings are expected, and the tests simply need to be changed to catch and check the warnings (which seems like the right thing anyway!).

**Comment by AlexandreAbraham** [comment]
Closing as partially fixed. Thanks @bcipolli for spotting warnings that were hiding errors.
