### ISSUE TITLE
unknown archive file format: /data/home/nilearn_data/fsl/f46ad01e95960216e8befa3b5c1ed654/HarvardOxford.tgz[BUG] 

### ISSUE THREAD

**Issue by lindafei01** [nilearn/nilearn#3643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [ ] Mac
- [X] Windows

### Operating system version

- Windows 10

### Python version

- [ ] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8
- [X] 3.7

### nilearn version

0.9.1

### Expected behavior

from nilearn import datasets
dataset = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm')

the above is the code on the https://nilearn.github.io/dev/connectivity/functional_connectomes.html, but I got the error messages 'unknown archive file format'

### Current behavior & error messages

OSError: Fetching aborted: [Uncompress] unknown archive file format: /data/home/nilearn_data/fsl/f46ad01e95960216e8befa3b5c1ed654/HarvardOxford.tgz

### Steps and code to reproduce bug

from nilearn import datasets
dataset = datasets.fetch_atlas_harvard_oxford('cort-maxprob-thr25-2mm')

**Comment by ymzayek** [comment]
Hi @lindafei01 thanks for reporting. I cannot reproduce the error on Linux Ubuntu 20.04 (with nilearn 0.9.1 and python3.7). Maybe someone with a Windows 10 system can try.

Also can you provide the whole stack traceback?

**Comment by lindafei01** [comment]
Thank you so much! It works!
