### ISSUE TITLE
[ENH] add a `.git-blame-ignore-revs` to ignore formatting PR from git blame

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

Came across while browsing the black documentation:
https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html#avoiding-ruining-git-blame

One problem with all the reformating PRs is that they make reduce the usefulness (or at least add more friction) to the use of git blame to trace change was introduced when: black may end up touching many if not most lines in the code base and git blame may invariably point to one of those reformatting PRs when we use it, even though it very unlikely that a behavioral change came from them.

Using a `.git-blame-ignore-revs` could allow to "skip" to PR during a git blame call.

### Benefits to the change

Ideally this should facilitate the tracking down of changes in the code base by ignoring changes that pure reformatting and do not entail functional change.

**Comment by Remi-Gau** [comment]
Let me know what you think.

**Comment by ymzayek** [comment]
I already feel that it's a bit slower to track down changes so I would be for this, but I haven't used it before. What would be the downside if any?

**Comment by NicolasGensollen** [comment]
I never used it but I'm +1 on this. 
The risk and cost seem very small and I can clearly see the benefits of having a meaningful blame where @Remi-Gau isn't responsible for all the bugs of Nilearn 😉.

**Comment by Remi-Gau** [comment]
> I can clearly see the benefits of having a meaningful blame where @Remi-Gau isn't responsible for all the bugs of Nilearn

Rémi then proceeds to blame-ignore ALL the PRs he ever authored... 😜

**Comment by Remi-Gau** [comment]
Related to https://github.com/nilearn/nilearn/pull/3701#discussion_r1170076459

```bash
 git blame --ignore-revs-file .git-blame-ignore-revs nilearn/image/resampling.py 
```
copy paste of a comment from #3755 

Still shows content from 3651 event though it is supposed to be ignored:

```
# run isort and flake8 on the whole nilearn code base in CI (#3651)
44933309ecd09add795ce1c3ea5edaab4294da87
```

More annoyingly it is also still the case for:

```bash
 git blame --ignore-rev 44933309  nilearn/image/resampling.py
```

**Comment by ghisvail** [comment]
We use [one of these](https://github.com/aramis-lab/clinica/blob/dev/.git-blame-ignore-rev) in Clinica.

**Comment by ymzayek** [comment]
To add:

#4147 25c456f34d45409f07dcca560e45f892a05dde4b
#4146 724cd51672417fd7db1e11c0f755178130df9feb
#4145 e083dba365ebf6a60bc9cd2e6b979030c769e4bf
#4144 7d4d7f3a343c68ed44e0d356b65ba78af4444f3a

**Comment by Remi-Gau** [comment]
Thanks.
Though I am still at a loss to actually make this git blame ignore work as I think it should.

**Comment by ymzayek** [comment]
I'm also unsure of how to make it work :/ If I get a chance I'll look into it some more

**Comment by emdupre** [comment]
@Remi-Gau is this resolved ?

**Comment by Remi-Gau** [comment]
nope: I could never make git-blame to properly ignore things listed in the .git-blame-ignore-revs

**Comment by Remi-Gau** [comment]
Dug into this again. The mechanism in `.git-blame-ignore-revs` does work, but only for lines where the formatting commit changed *whitespace/style only*.

Example that works as expected:

```
$ git blame -L 97,97 nilearn/image/resampling.py
92c9bf1e5ce (Remi Gau 2023-03-07 08:18:45 +0100 97)     t[nin, nout] = 1.0

$ git blame --ignore-revs-file .git-blame-ignore-revs -L 97,97 nilearn/image/resampling.py
6e66c18c43f (Alexandre Abraham 2012-08-06 09:26:33 +0200 97)     t[nin, nout] = 1.0
```

Once `92c9bf1e5ce` (format image module #3548) is ignored, blame correctly falls back to the 2012 commit that actually introduced that line — the only change in #3548 was a stray-whitespace fix (`t[nin,   nout]` -> `t[nin, nout]`).

The case that looked broken in earlier comments (e.g. `nilearn/image/resampling.py:2`) is different: that line's content was genuinely changed by the formatting commit (a period was added to the docstring and a blank line was inserted), not just reformatted. `git blame --ignore-rev` can only fall back to a parent commit if it can find an equivalent (whitespace-aside) line there — if the formatting PR altered actual text, there is nothing to fall back to, so blame correctly still attributes that line to the formatting commit.

So: `.git-blame-ignore-revs` is correctly wired up and working as designed. The residual cases people hit are because some of the "formatting" PRs weren't purely whitespace-only (they also tweaked docstring wording, added/removed blank lines, etc.), which is a fundamental limit of `git blame --ignore-rev`, not a config issue on our side.

🤖 Generated with assistance from an LLM (Claude).

**Comment by Remi-Gau** [comment]
will consider this one as solved

also I don't remember git blame pollution due to automated reformating being such a concern.
