### ISSUE TITLE
Remove descriptions of deprecated datasets

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3656]
Not related to this PR but some datasets listed here have been deprecated, like cobre and nyu. And their description rst files is still in `nilearn/datasets/description`. Is there a reason to keep these or was this just missed when they were removed?

_Originally posted by @ymzayek in https://github.com/nilearn/nilearn/pull/3624#discussion_r1150467838_

**Comment by bthirion** [comment]
These  should be removed. Thx for pointing this.

**Comment by michellewang** [comment]
Hi, I can work on that. Datasets that haven't been deprecated should have a fetcher listed in https://nilearn.github.io/dev/modules/datasets.html, is that correct? 

And, out of curiosity, are the rst files in `nilearn/datasets/description` used when building the documentation (if that's the case then I can't find them in the documentation), or are they just for internal reference?
