### ISSUE TITLE
improve documentation of nilearn/reporting/_visual_testing/_glm_reporter_visual_inspection_suite_.py

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3665]
What does this do ?

_Originally posted by @bthirion in https://github.com/nilearn/nilearn/pull/3615#discussion_r1159024547_

Several functions in this script could benefit from better doc strings

**Comment by kchawla-pi** [comment]
> IIRC these are scripts to generate some example GLM reports and visually check if they display well; pinging @kchawla-pi 

Yes

**Comment by Remi-Gau** [comment]
> Under documented!! flushedfearful

If that helps I find that ANY code I wrote more than 6 months ago is under documented.
