### ISSUE TITLE
[ENH] remove or repurpose unused deprecation warning function

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

As far as I can tell this deprecation warning function is unused in the code base.

https://github.com/nilearn/nilearn/blob/17d4b53d2bdb3a7722530eef9be1d58b305c9a0d/nilearn/glm/regression.py#L31

I would suggest removing it or moving to more general purpose utility module to be used as a standardized way to throw deprecation warnings.

### Benefits to the change

Having a single function to throw typical deprecation warnings may help when the time comes to remove them.

Side note related to this:
- one of the deprecation warning I added recently used [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) instead of [FutureWarning](https://docs.python.org/3/library/exceptions.html#FutureWarning) that is apparently the one to use to warn users and not just developers.

https://docs.python.org/3/library/warnings.html#warning-categories

Note that there are a few other usage of DeprecationWarning in the codebase which from a quick read should probably be FutureWarning.

**Comment by ymzayek** [comment]
Yes, it seems they are used in an inconsistent fashion regarding the guidelines. Maybe even look into how `UserWarning` is used.

Regarding the function, maybe we can consolidate into `_utils.helpers` with the other deprecation related functions.

**Comment by jeromedockes** [comment]
I'm not sure I understand why those fit the `FutureWarning` better than `DeprecationWarning` description:
DeprecationWarning doc says:
> Base category for warnings about deprecated features when those warnings are intended for other Python developers

this sounds adequate, Python developers writing applications that use nilearn should know they are using a nilearn feature that will change

FutureWarning says:

> Base category for warnings about deprecated features when those warnings are intended for end users of applications that are written in Python.

I don't think it applies to us -- there's not much an end user could do about it anyway, and in any case nilearn is used mostly for scripting 

maybe the [PEP](https://peps.python.org/pep-0565/#additional-use-case-for-futurewarning) helps clarify a bit: 
deprecationwarning:
> [...] The intended audience is Python developers that are at risk of upgrades to their dependencies (including upgrades to Python itself) breaking their software (e.g. developers using Python to script environments where someone else is in control of the timing of dependency upgrades).

FutureWarning:
>  reported by default for all code. The intended audience is users of applications written in Python, rather than other Python developers (e.g. warning about use of a deprecated setting in a configuration file format).

> For library and framework authors that want to ensure their API compatibility warnings are more reliably seen by their users, the recommendation is to use a custom warning class that derives from DeprecationWarning in Python 3.7+, and from FutureWarning in earlier versions.

**Comment by Remi-Gau** [comment]
Thanks for looking more into this @jeromedockes 

It looks like I had things backward indeed.

**Comment by Remi-Gau** [comment]
Update:

the `_deprecation_warning` has been removed

maybe using the `_warn_deprecated_params` from here:
https://github.com/nilearn/nilearn/blob/a87b0b8f46bf3c0aa0107d505dc45c9094bc8a37/nilearn/_utils/helpers.py#L48

could be a way to "standardize" our deprecation warnings

**Comment by Remi-Gau** [comment]
From a look around all the deprecation warnings we have I think that this issue is now solved or obsolete.
