### ISSUE TITLE
codecov dependency missing

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3674]
`pip intall .[dev]` or `pip intall .[test]` will fail as codecov has been pulled from pypi.

https://pypi.org/project/codecov/

expect a lot of red in CI

**Comment by Remi-Gau** [comment]
seems that the repo was also archived: https://github.com/codecov/codecov-python

Maybe a good idea to use the github action?
https://github.com/marketplace/actions/codecov

**Comment by Remi-Gau** [comment]
seeing the CI it seems we are already using the github action, so it may very well be that this is an unneeded dependency.

see for example: https://github.com/nilearn/nilearn/blob/17d4b53d2bdb3a7722530eef9be1d58b305c9a0d/.github/workflows/testing.yml#L38

will open a PR to see what happens if it is removed

**Comment by ymzayek** [comment]
I think this will fail: https://github.com/nilearn/nilearn/blob/17d4b53d2bdb3a7722530eef9be1d58b305c9a0d/azure-pipelines.yml#L42

**Comment by Remi-Gau** [comment]
yup I just realized
updating the PR to use the codecov uploader in azure
