### ISSUE TITLE
[DOC] Use code blocks instead of doctests for rst files in `doc`

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

I noticed a bunch of doctests marked for skipping in some rsts. Why not just use code blocks? I'm guessing they are not run to avoid making the build more expensive but it's not clear why they should be written as doctests. It seems there is a mixture of the two formats in the same file anyways

### List any pages that would be impacted.

```bash
❯ grep -rl doc -e 'doctest: +SKIP'
doc/plotting/index.rst
doc/connectivity/functional_connectomes.rst
doc/connectivity/connectome_extraction.rst
doc/decoding/decoding_intro.rst
doc/manipulating_images/input_output.rst
doc/building_blocks/neurovault.rst
doc/building_blocks/manual_pipeline.rst
```

**Comment by psadil** [comment]
Hi! I'm interested in working on this

**Comment by Remi-Gau** [comment]
Assigned the issue to you: let us know if you need help with anything

**Comment by psadil** [comment]
Is the intention to replace cases like

https://github.com/nilearn/nilearn/blob/e002d2421584ee3f29499f0719a843bdac103054/doc/building_blocks/neurovault.rst?plain=1#L36-L39

with

```rst
Or if you want some images in particular, rather than whole 
collections : 
  
.. code-block:: python

     brainpedia_subset = fetch_neurovault_ids(image_ids=[32015, 32016]) 
```

and similarly to replace cases like (note `::` indicating a literal block)

https://github.com/nilearn/nilearn/blob/e002d2421584ee3f29499f0719a843bdac103054/doc/plotting/index.rst?plain=1#L386-L390

with 

```rst
to specify the `output_file` argument:

.. code-block:: python

     from nilearn import plotting 
     plotting.plot_stat_map(img, output_file='pretty_brain.png')
```

I'm mainly double-checking the expectation for the rendered output. For example, both of these would end up without the `>>>` prompt and also lose a blue vertical bar that's currently at the left of the block. This seems to match what's used in, e.g. [doc/building_blocks/manual_pipeline.rst](https://github.com/nilearn/nilearn/blob/e002d2421584ee3f29499f0719a843bdac103054/doc/building_blocks/manual_pipeline.rst#L140-L150), [rendered here](https://nilearn.github.io/stable/building_blocks/manual_pipeline.html#applying-a-mask). But there are also [instances of `code-block:: default`](https://github.com/nilearn/nilearn/blob/e002d2421584ee3f29499f0719a843bdac103054/doc/introduction.rst?plain=1#L45-L48C1), and those blocks [have the blue vertical bar](https://nilearn.github.io/stable/introduction.html#first-steps-with-nilearn) (still no prompt).

**Comment by ymzayek** [comment]
@psadil yes the examples you show using the `code-block` syntax are appropriate. I think we can go with the ones that have the vertical blue bar (so `code-block:: default`) so that it is consistent with our [example gallery](https://nilearn.github.io/stable/auto_examples/index.html). These are meant to be input and the ones without are output. I know in the docs it's probably inconsistent but that is another issue that we'd need to deal with separately.
