### ISSUE TITLE
add a logger to "first_level_from_bids"

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3686]
I am having to pass this verbose parameter around a bit too much to be able to control whether warnings, messages should be printed...

This should probably be handled better by implementing a logger in another PR.

_Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/pull/3605#discussion_r1152080917_

**Comment by jeromedockes** [comment]
could you give a few more details on what implementing a logger would look like? the `verbose` parameter for estimators is used throughout nilearn and scikit-learn so it would have to stay, but I guess you mean changing how the verbosity level is controlled in private functions?

**Comment by Remi-Gau** [comment]
> you mean changing how the verbosity level is controlled in private functions?

yes exactly: this would concern just the private functions that are specific to first_level_from_bids.
If it is calling another nilearn or sklearn function that has the usual verbose argument then it would be passed as usual.

if that helps to make things more concrete I can create a draft PR of how I would apply it to say one private function, you give me early feedback (as there may be future headaches that may follow from this that I have not foreseen) and then we decide whether this is worth pursuing further.

**Comment by jeromedockes** [comment]
sounds like a good plan!

**Comment by Remi-Gau** [comment]
closing in favor of #4443
