### ISSUE TITLE
extract dataset IDs in separate functions

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3704]
This isn't related to reformatting but I'm wondering whether we should have helper functions whose only responsibility is to return the list of ids for a given dataset fetcher.

So basically something like this:

```python
# In the fetcher
ids = _get_nki_ids()

# Helper function
def _get_nki_ids():
    return [....]
```

 It's not super important, but these massive lists are breaking the function logic and force the reader to scroll up and down which can be annoying...
WDYT ?

_Originally posted by @NicolasGensollen in https://github.com/nilearn/nilearn/pull/3695#discussion_r1170921752_

**Comment by jeromedockes** [comment]
a function or a global constant
