### ISSUE TITLE
Documentation builder failure on main

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3707]
https://github.com/nilearn/nilearn/actions/workflows/build-docs.yml

started occurring after merging #3698 (doubt it is related given the content of the PR)
https://github.com/nilearn/nilearn/actions/runs/4741116007

**Comment by ymzayek** [comment]
The problem comes from this [PR](https://github.com/nilearn/nilearn/pull/3693/files#diff-a7e51d164f44800beebb5ec50d42c9cb0bc7fe129ac72db066d129ccc825b93a) where the import of `fetch_atlas_pauli_2017` was removed from \_\_init__.py probably because it wasn't set in `__all__`
