### ISSUE TITLE
cancel concurrent CI workflows ?

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3718]
Some CI workflows (testing, doc build) take a long time to run.

Those are set to keep running even if new commits are pushed on a branch / PR that can render the end result of that workflow obsolete.

This also means that compulsive "git pusher" (I am one of them 🙈) tend to end up with many CI workflows queued for a given PR, which hogs resources and also potentially delays the start of workflows from other PRs / devs.

I'd be tempted to cancel concurrent previous workflows for testing and doc, the way it is done with the black / flake8 / isort workflows: https://github.com/nilearn/nilearn/blob/d50ee5201c1ad7f5d583c5c4d0ec0ea6d8ef6a5d/.github/workflows/isort.yml#L12

Wondering how others feel about this.

**Comment by ymzayek** [comment]
I would be for it though it's the case that sometimes it helps in the debugging process to be able to track which push commits passed and which didn't. But maybe the benefits outweigh the costs especially for these heavier jobs

**Comment by ymzayek** [comment]
Also, we probably would want to restrict this to PRs as applying it on main can make it more difficult to track sources of failures

**Comment by Remi-Gau** [comment]
> Also, we probably would want to restrict this to PRs as applying it on main can make it more difficult to track sources of failures

Agreed.

I think this has some info on how to set it up.
https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-fallback-value 

> I would be for it though it's the case that sometimes it helps in the debugging process to be able to track which push commits passed and which didn't. But maybe the benefits outweigh the costs especially for these heavier jobs

Yeah that's pretty much the trade-off that I had in mind too: though in most cases once a test fails in CI it is faster to git bisect locally to spot the guilty commit.

**Comment by bthirion** [comment]
I'm always worried to make the behavior of these objects more complicated --- for the sake of long-term maintenance.
That's why I think the current behavior is OK, though suboptimal in terms of resource use.

**Comment by ymzayek** [comment]
> Or we could try to make the test suite faster, but after playing around quite a bit in the test suite, I am not sure that we are going to make considerable gains on that front.

I think we should take another look at this proposition and prioritize it a bit. Even though it varies, the tests used to take 30-40 minutes to run on azure and now it seems closer to 1h which is going to start causing timeout failures like this one https://dev.azure.com/Parietal/Nilearn/_build/results?buildId=6386&view=results in PR #3720

This happened before because of an update related to a deprecation so first we should investigate if any of the recent changes have caused this slow down.

It's also possible that not all tests are as minimal as they can be.

**Comment by ymzayek** [comment]
@jeromedockes unfortunately the logs that I can access on Azure pipelines don't go back far enough to trace when this jump happened. I'll check if there were any updates or issues on Azure's side in early-mid April when this began to happen or see if I can contact their support. IIUC the test suite time has not increased on Ubuntu or macOS Github runners
