### ISSUE TITLE
Ugly side plots in doc

### ISSUE THREAD

**Issue by lesteve** [nilearn/nilearn#372]
They mask part of the code they are supposed to illustrate. See an example [here](http://nilearn.github.io/building_blocks/data_preparation.html#computing-the-mask).

![ugly-side-plots](https://cloud.githubusercontent.com/assets/1680079/5974579/266c30d8-a876-11e4-8830-febff99ed1dc.png)

**Comment by kshmelkov** [comment]
I am working on this.
