### ISSUE TITLE
improve handling of temporary files during testing

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3726]
so in order from short term to long term: 
1. fix this test by using `tmp_path` and `monkeypatch.chdir(tmp_path)` (edited: DONE)
2. add a parameter to the write_fake_fmri function to allow specifying the directory it uses 
3. see how we can avoid leaking open files after loading images

_Originally posted by @jeromedockes in https://github.com/nilearn/nilearn/pull/3525#discussion_r1173830469_

**Comment by Remi-Gau** [comment]
extracting this into a separate issue because I know I will otherwise forget about its existence if it is buried in a comment thread of a PR merged 2 months ago

**Comment by ymzayek** [comment]
Is this one done?

**Comment by Remi-Gau** [comment]
just checked and yup this is good
