### ISSUE TITLE
[DOC] Update and improve examples in nilearn documentation

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

Unrelated to the changes to this PR: I noticed some suboptimal outputs in some examples so I will open a separate issue to track them

_Originally posted by @ymzayek in https://github.com/nilearn/nilearn/issues/3720#issuecomment-1521902025_

This is a meta issue concerning nilearn examples and their rendering

#### Plotting (@ymzayek)

- [x] overlapping title
  - Known issue that appears in many examples so will not list here. See PR #2804 
- [x] Cut off titles or image
  - https://nilearn.github.io/dev/auto_examples/01_plotting/plot_demo_more_plotting.html 
  - https://nilearn.github.io/dev/auto_examples/07_advanced/plot_localizer_simple_analysis.html
  - https://nilearn.github.io/dev/auto_examples/07_advanced/plot_localizer_mass_univariate_methods.html
  - https://nilearn.github.io/dev/auto_examples/07_advanced/plot_haxby_mass_univariate.html
- [x] plots output shown on top of cell calling them (not a comprehensive list)
  - https://nilearn.github.io/dev/auto_examples/01_plotting/plot_haxby_masks.html  
  - https://nilearn.github.io/dev/auto_examples/01_plotting/plot_prob_atlas.html
  - https://nilearn.github.io/dev/auto_examples/02_decoding/plot_haxby_stimuli.html
  - https://nilearn.github.io/dev/auto_examples/03_connectivity/plot_simulated_connectome.html
  - https://nilearn.github.io/dev/auto_examples/04_glm_first_level/plot_design_matrix.html
- [x] Fix matrix plots titles

#### Output (@ymzayek)

- [x] print output
  - https://nilearn.github.io/dev/auto_examples/00_tutorials/plot_single_subject_single_run.html (first output block)

#### Other (@Remi-Gau)

- [x] These 2 examples are listed separately in the dropdown but are in fact in one file
  - https://nilearn.github.io/dev/auto_examples/01_plotting/plot_overlay.html#
  - https://nilearn.github.io/dev/auto_examples/01_plotting/plot_overlay.html#visualizing-a-probabilistic-atlas-with-plot-prob-atlas
- [x] License or author names render in first code block
  - https://nilearn.github.io/dev/auto_examples/02_decoding/plot_oasis_vbm.html
  - https://nilearn.github.io/dev/auto_examples/02_decoding/plot_simulated_data.html
  - https://nilearn.github.io/dev/auto_examples/05_glm_second_level/plot_oasis.html
  - https://nilearn.github.io/dev/auto_examples/05_glm_second_level/plot_second_level_association_test.html
  - https://nilearn.github.io/dev/auto_examples/07_advanced/plot_localizer_simple_analysis.html
  - https://nilearn.github.io/dev/auto_examples/07_advanced/plot_neurovault_meta_analysis.html
  - https://nilearn.github.io/dev/auto_examples/07_advanced/plot_localizer_mass_univariate_methods.html
  - https://nilearn.github.io/dev/auto_examples/07_advanced/plot_ica_neurovault.html
  - https://nilearn.github.io/dev/auto_examples/07_advanced/plot_haxby_mass_univariate.html
- [ ] Last 2 plots in https://nilearn.github.io/dev/auto_examples/05_glm_second_level/plot_second_level_association_test.html don't show any contrasts. Is that as expected?
- [x] Explanatory text is in code block
  - https://nilearn.github.io/dev/auto_examples/06_manipulating_images/plot_mask_computation.html

#### Time (according to one sphinx report at the bottom of the page of the examples)

- [x] https://nilearn.github.io/dev/auto_examples/01_plotting/plot_prob_atlas.html (4m23s)
  - Maybe don't plot all the atlases
- https://nilearn.github.io/dev/auto_examples/02_decoding/plot_haxby_frem.html (10m59s) (locally 6m29s)
- https://nilearn.github.io/dev/auto_examples/03_connectivity/plot_compare_decomposition.html (7m49s)

**Comment by Remi-Gau** [comment]
@ymzayek how do you want to proceed with this?
- one PR pr example?
- one PR pr line to fix in the list above?
- something else?

**Comment by ymzayek** [comment]
I'll probably start with one PR per sub grouping (e.g. Cut off titles or image). Maybe if the changes are really small then combine at a higher level

**Comment by Remi-Gau** [comment]
let me know how you want to split the load on this.

**Comment by ymzayek** [comment]
@Remi-Gau I'll start with the ones under Plotting and you can start with the ones under Other and we can see how to tackle the Time category after tackling these. Is it ok with you?

**Comment by ymzayek** [comment]
Oh I left Output out. I can take care of that too

**Comment by Remi-Gau** [comment]
Good with me: will add our username in the top message next to our sections

**Comment by Remi-Gau** [comment]
Regarding this:

> License or author names render in first code block 

Does it make sense to have the license in those files? We have one license for nilearn and it is expected to apply to all the code of the library and the examples, no?

**Comment by ymzayek** [comment]
I'm not sure about the author names but we can easily keep them without rendering them. I think just move the comment to the first line of the script

**Comment by Remi-Gau** [comment]
Actually we have the license mentioned in many other files, no?
It would make sense to remove it in other files as well.

Regarding authors, I tend to believe that version control should be enough to tell you who created and worked on the file, but that's not a hill I want to die on (today).

**Comment by ymzayek** [comment]
+1 regarding both of those points. Seems to me things that were just left behind over time. Maybe someone who has been around longer can judge better on why to leave them?

**Comment by Remi-Gau** [comment]
Seems that the kanban board automation is a bit too eager to automatically close things: let me change that

**Comment by Remi-Gau** [comment]
@ymzayek should we try to wrap this one up before the next milestone?

**Comment by ymzayek** [comment]
Sure maybe just the last 2 points under **Other** and not the **Time** ones. You take one and I take the other?

**Comment by Remi-Gau** [comment]
> Sure maybe just the last 2 points under **Other** and not the **Time** ones. 

Let's have the Time one in a separate issue ?

> You take one and I take the other?

I can try to figure out why we show contrasts with no activation.

**Comment by ymzayek** [comment]
Ok I'll handle the extraneous code block one. And I agree after we finish these two let's close this issue and open a new one for the **Time** examples

**Comment by Remi-Gau** [comment]
> * Last 2 plots in https://nilearn.github.io/dev/auto_examples/05_glm_second_level/plot_second_level_association_test.html don't show any contrasts. Is that as expected?

checked back all the way to version 0.8.0 this problem is still there

**Comment by Remi-Gau** [comment]
For comparison here is the original nistats example: https://nistats.github.io/auto_examples/03_second_level_models/plot_second_level_association_test.html#sphx-glr-auto-examples-03-second-level-models-plot-second-level-association-test-py

**Comment by Remi-Gau** [comment]
Showing no activation feels a bit underwhelming, no? Should we then just amend this example?

**Comment by bthirion** [comment]
We should handle that in a specific issue.  Need to check whether it's a random thing, a question of threshold or whatever.

**Comment by Remi-Gau** [comment]
will extract this into a specific issue.
