### ISSUE TITLE
Change thumbnail image for plot_adhd_covariance example

### ISSUE THREAD

**Issue by lesteve** [nilearn/nilearn#373]
Computation of covariance matrix between brain regions has a picture showing sparsity (mostly blue with a few red pixels) rather than correlations. http://nilearn.github.io/auto_examples/index.html. A picture with correlations would probably make the example easier to find when glancing at the gallery.

This picture for example seems more appropriate
http://nilearn.github.io/_images/plot_adhd_covariance_2.png

Since the first image plotted in the example is picked as the gallery thumbnail it is just a matter of changing the order of the plots in the example.

**Comment by kshmelkov** [comment]
I will do it also when I finish downloading all datasets =)
