### ISSUE TITLE
[DOC] improve instructions in "Default Mode Network extraction of ADHD dataset" example

### ISSUE THREAD

**Issue by mtorabi59** [nilearn/nilearn#3737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

It seems the instructions in [this example](https://nilearn.github.io/dev/auto_examples/04_glm_first_level/plot_adhd_dmn.html#default-mode-network-extraction-of-adhd-dataset) need some improvement. There was a confusion mentioned on [NeuroStar](https://neurostars.org/t/why-is-there-glm-for-resting-state-data/25841). After discussing with @Remi-Gau, we concluded that maybe we can add one or two lines saying that in this example we extract the activity of a seed region and then use the extracted signal as regressor in a GLM and this will yield the correlation of each region with the seed region.

### List any pages that would be impacted.

https://nilearn.github.io/dev/auto_examples/04_glm_first_level/plot_adhd_dmn.html#default-mode-network-extraction-of-adhd-dataset

**Comment by Remi-Gau** [comment]
yes
a couple of lines explaining the general idea of the analysis and maybe an additional plot of the time course of the seed region

wanna take care of it @mtorabi59 ?

**Comment by mtorabi59** [comment]
@Remi-Gau  Sure! Will do!
