### ISSUE TITLE
[BUG] first_level_from_bids confused by "res" filter when looking for confounds.tsv

### ISSUE THREAD

**Issue by andreifoldes** [nilearn/nilearn#3741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

CentOS Linux release 7.6.1810

### Python version

- [ ] 3.11
- [X] 3.10
- [ ] 3.9
- [ ] 3.8
- [ ] 3.7

### nilearn version

0.10.0

### Expected behavior

When running the command below one can expect the model_confounds to be found in a bids-valid directory.

(models,
    models_run_imgs,
    models_events,
    models_confounds,) = first_level_from_bids(data_dir, task_label, derivatives_folder=derivatives_folder,space_label=space_label,img_filters=[("desc", "preproc"),("res","2")], smoothing_fwhm=6, slice_time_ref=0.481, n_jobs=-1, signal_scaling=(0,1))

### Current behavior & error messages

This is what I got:
models_confounds were al None.

What I did to fix it was simply add an extra line in /nilearn/glm/first_level/first_level.py for removing "res" from the filters:

    supported_filters.remove("desc")
    **supported_filters.remove("res")**
    
    filters = _make_bids_files_filter(
        task_label=task_label,
        supported_filters=supported_filters,
        extra_filter=img_filters,
        verbose=verbose,
    )
    confounds = get_bids_files(
        derivatives_path,
        modality_folder="func",
        file_tag="desc-confounds*",
        file_type="tsv",
        sub_label=sub_label,
        filters=filters,
    )

### Steps and code to reproduce bug

```python
# Paste your code here


```

**Comment by Remi-Gau** [comment]
that seems like a bug indeed.

in theory fmriprep should give you a single confounds file:

https://github.com/nipreps/fmriprep/blob/39038a7071670d9ac0fc3d28cb7ae084a1138e72/.circleci/ds054_outputs.txt#L71

even if you have several `res` or `space` files

https://github.com/nipreps/fmriprep/blob/39038a7071670d9ac0fc3d28cb7ae084a1138e72/.circleci/ds054_outputs.txt#L73
https://github.com/nipreps/fmriprep/blob/39038a7071670d9ac0fc3d28cb7ae084a1138e72/.circleci/ds054_outputs.txt#LL82C5-L82C5
https://github.com/nipreps/fmriprep/blob/39038a7071670d9ac0fc3d28cb7ae084a1138e72/.circleci/ds054_outputs.txt#LL87C3-L87C3

I suspect this should also apply to the `den` entity that is mostly for surface outputs.
So maybe easier to not allow any of the derivatives entities and only add desc.

**Comment by andreifoldes** [comment]
Yes you're right!

**Comment by Remi-Gau** [comment]
There is a bit of sanity check around this: 
https://github.com/nilearn/nilearn/blob/6085633bc3ffed18feea47ff2e39c9f5fbebcfd5/nilearn/glm/first_level/first_level.py#L1366

But if no confounds is found then it does indeed not not do anything.

We could add a warning when no confound is found.

**Comment by Remi-Gau** [comment]
Minimal code to reproduce

```python
from pathlib import Path

from nilearn._utils.data_gen import (
    create_fake_bids_dataset,
)
from nilearn.glm.first_level import (
    first_level_from_bids,
)

n_sub = 1
n_ses = 1
tasks = ["main"]
n_runs = [1]

bids_path = create_fake_bids_dataset(
    base_dir=Path().cwd(),
    n_sub=n_sub,
    n_ses=n_ses,
    tasks=tasks,
    n_runs=n_runs,
    entities={"res": ["A", "B"]},
)

models, m_imgs, m_events, m_confounds = first_level_from_bids(
    dataset_path=bids_path,
    task_label="main",
    space_label="MNI",
    img_filters=[("desc", "preproc"), ("res", "A")],
    slice_time_ref=None,
)

print(models)
print(m_confounds)
```
