### ISSUE TITLE
test error for order of printed argument with python 3.11

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3750]
See in a few runs of CI

For [example](https://github.com/nilearn/nilearn/actions/runs/5244068680/jobs/9469564671?pr=3742#step:8:14623)

```
 FAILED nilearn/plotting/tests/test_matrix_plotting.py::test_sanitize_reorder_error[None] - AssertionError: Regex pattern did not match.
 Regex: "Parameter reorder needs to be one of {False, True, 'complete', 'single', 'average'}"
 Input: "Parameter reorder needs to be one of {False, True, 'single', 'complete', 'average'}."
FAILED nilearn/plotting/tests/test_matrix_plotting.py::test_sanitize_reorder_error[foo] - AssertionError: Regex pattern did not match.
 Regex: "Parameter reorder needs to be one of {False, True, 'complete', 'single', 'average'}"
 Input: "Parameter reorder needs to be one of {False, True, 'single', 'complete', 'average'}."
FAILED nilearn/plotting/tests/test_matrix_plotting.py::test_sanitize_reorder_error[2] - AssertionError: Regex pattern did not match.
 Regex: "Parameter reorder needs to be one of {False, True, 'complete', 'single', 'average'}"
 Input: "Parameter reorder needs to be one of {False, True, 'single', 'complete', 'average'}."
= 3 failed, 2587 passed, 7 skipped, 2 xfailed, 1311 warnings in 1693.15s (0:28:13) =
```

**Comment by Remi-Gau** [comment]
@ymzayek : I will have a look at this.

**Comment by Remi-Gau** [comment]
This is a zombie "bug" 🧟 (it comes back from the dead) or a unsinkable rubber bug (it keeps coming back up).

https://github.com/nilearn/nilearn/actions/runs/5269060267/jobs/9526640379#step:8:14682

**Comment by ymzayek** [comment]
Thought: do we have to treat VALID_REORDER_ARGS (and therefore also VALID_REORDER_VALUES) variable as a set? Can't it be a list or tuple? Can we mimick what the function above that (`_sanitize_tri`) is doing?

**Comment by Remi-Gau** [comment]
Pretty sure that this failure is now just due to some regular expression special character escaping so I am implementing your suggestion of using re.escape from #3751.
Will change it to a set so things are consistent within the module: you are correct that it may be confusing otherwise (Future us: "why tuple here and set there?")

**Comment by ymzayek** [comment]
Yea it's true that in any case you have to escape (e.g. escape the brackets for a list). I think re.escape is good as we want to have an exact match but if it's not working for whatever reason let's just go with a regex matching the first part of that warning which is what you initially implemented

**Comment by Remi-Gau** [comment]
OK: if I see that test fail one more time I will go with this. Sounds way more pragmatic.

**Comment by Remi-Gau** [comment]
OK pragmatism will prevail...
