### ISSUE TITLE
[DOC] Inconsistent description of return keys for `fetch_atlas_surf_destrieux`

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

The function `fetch_atlas_surf_destrieux` returns a dictionary with the keys 'labels', 'map_left', 'map_right', and 'description'. However, in the description, 'map_left' and 'map_right' are called 'annot_left' and 'annot_right'. These should be changed to be consistent with the API. The change should be made in [nilearn/datasets/description/destrieux_surface.rst](https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/description/destrieux_surface.rst).

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this

**Comment by ymzayek** [comment]
@tarunsamanta2k20 it's all yours :) Let us know if you need any help
