### ISSUE TITLE
[BUG] test_matrix_plotting.py:165: SyntaxWarning: assertion is always true, perhaps remove parentheses?

### ISSUE THREAD

**Issue by yurivict** [nilearn/nilearn#3778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

FreeBSD 13.2

### Python version

- [ ] 3.11
- [ ] 3.10
- [X] 3.9
- [ ] 3.8
- [ ] 3.7

### nilearn version

0.10.1.dev

### Expected behavior

n/a

### Current behavior & error messages

This warning is printed during the package build:
```
/usr/local/lib/python3.9/site-packages/nilearn/plotting/tests/test_matrix_plotting.py:165: SyntaxWarning: assertion is always true, perhaps remove parentheses?
```

### Steps and code to reproduce bug

Python-3.9

**Comment by bthirion** [comment]
Thw for opening this. Can you copy the assertion here ? I don't see an assert on l.165. Only on l.164 
https://github.com/nilearn/nilearn/blob/main/nilearn/plotting/tests/test_matrix_plotting.py#L164

**Comment by Remi-Gau** [comment]
Is the same as this flake8 warning in CI? 

https://github.com/nilearn/nilearn/actions/runs/5374787653/jobs/9750551456#step:5:13

**Comment by ymzayek** [comment]
That test is asserting a tuple and that is why it will always pass hence the warning. It should be rewritten as 
```python
    assert (
        reordered_labels[:3] == idx or reordered_labels[-3:] == idx
    ), "Clustering does not find block structure."
```

So the parentheses only enclose the `or` statement and not the whole `assert` statement

**Comment by bthirion** [comment]
Please open a PR !
