### ISSUE TITLE
[BUG] load_confounds on 0.10.1 does not detect the corresponding confound file

### ISSUE THREAD

**Issue by vytautasl1337** [nilearn/nilearn#3792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [ ] Mac
- [ ] Windows

### Python version

- [ ] 3.11
- [ ] 3.10
- [ ] 3.9
- [X] 3.8
- [ ] 3.7

### nilearn version

0.10.1.dev

### Expected behavior

load_confounds.py on 0.10.0 works as intended (just request to scrub the BOLD runs (3 in total). However, I had to switch to 0.10.1 to perform second level permutation testing (as 0.10.0 was not performing well, providing completely different results compared to FSL). But now load_confounds cannot locate the corresponding confound file, despite running the same script. 

### Current behavior & error messages

0.10.1 load_confounds.py gives me an error that corresponding confound file does not exist, despite it all working well in 0.10.0

### Steps and code to reproduce bug

```python
confounds_scrub, sample_mask = load_confounds(task_nii,strategy=["scrub"],
                                scrub=5,
                                fd_threshold=.9,
                                std_dvars_threshold=50,
                            )
```

task_nii is my path to my single functional file i analyze (filename including)

**Comment by tsalo** [comment]
Can you share the fMRIPrep version you used, as well as a filetree of your fMRIPrep derivatives?

**Comment by vytautasl1337** [comment]
I use fmriprep 22.0.2

Here are the subdirectories of one participant
log/
    20230601-095801_4fc3a418-9574-455c-9017-4d738146ac2f/
        fmriprep.toml
figures/
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_desc-validation_bold.html
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_desc-validation_bold.html
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_desc-validation_bold.html
    sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_desc-validation_bold.html
    sub-01_ses-PRISMA_desc-about_T1w.html
    sub-01_ses-PRISMA_desc-summary_T1w.html
    sub-01_ses-PRISMA_desc-conform_T1w.html
    sub-01_ses-PRISMA_dseg.svg
    sub-01_ses-PRISMA_run-2_fmapid-auto00002_desc-pepolar_fieldmap.svg
    sub-01_ses-PRISMA_run-1_fmapid-auto00001_desc-pepolar_fieldmap.svg
    sub-01_ses-PRISMA_run-1_fmapid-auto00000_desc-pepolar_fieldmap.svg
    sub-01_ses-PRISMA_space-MNI152NLin6Asym_T1w.svg
    sub-01_ses-PRISMA_space-MNI152NLin2009cAsym_T1w.svg
    sub-01_ses-PRISMA_run-3_fmapid-auto00003_desc-pepolar_fieldmap.svg
    sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_desc-sdc_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_desc-sdc_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_desc-sdc_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_desc-sdc_bold.svg
    sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_desc-flirtbbr_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_desc-flirtbbr_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_desc-flirtbbr_bold.svg
    sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_desc-compcorvar_bold.svg
    sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_desc-confoundcorr_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_desc-flirtbbr_bold.svg
    sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_desc-rois_bold.svg
    sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_desc-carpetplot_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_desc-compcorvar_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_desc-confoundcorr_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_desc-compcorvar_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_desc-carpetplot_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_desc-confoundcorr_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_desc-compcorvar_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_desc-confoundcorr_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_desc-rois_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_desc-carpetplot_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_desc-carpetplot_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_desc-rois_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_desc-rois_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_desc-aroma_bold.svg
    sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_desc-aroma_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_desc-summary_bold.html
    sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_desc-summary_bold.html
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_desc-aroma_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_desc-summary_bold.html
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_desc-aroma_bold.svg
    sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_desc-summary_bold.html
ses-PRISMA/
    anat/
        sub-01_ses-PRISMA_desc-preproc_T1w.nii.gz
        sub-01_ses-PRISMA_desc-preproc_T1w.json
        sub-01_ses-PRISMA_desc-brain_mask.nii.gz
        sub-01_ses-PRISMA_desc-brain_mask.json
        sub-01_ses-PRISMA_label-GM_probseg.nii.gz
        sub-01_ses-PRISMA_label-WM_probseg.nii.gz
        sub-01_ses-PRISMA_label-CSF_probseg.nii.gz
        sub-01_ses-PRISMA_dseg.nii.gz
        sub-01_ses-PRISMA_from-T1w_to-MNI152NLin2009cAsym_mode-image_xfm.h5
        sub-01_ses-PRISMA_from-T1w_to-MNI152NLin6Asym_mode-image_xfm.h5
        sub-01_ses-PRISMA_from-MNI152NLin2009cAsym_to-T1w_mode-image_xfm.h5
        sub-01_ses-PRISMA_from-MNI152NLin6Asym_to-T1w_mode-image_xfm.h5
        sub-01_ses-PRISMA_space-MNI152NLin2009cAsym_res-2_desc-preproc_T1w.nii.gz
        sub-01_ses-PRISMA_space-MNI152NLin2009cAsym_res-2_desc-preproc_T1w.json
        sub-01_ses-PRISMA_space-MNI152NLin2009cAsym_res-2_label-GM_probseg.nii.gz
        sub-01_ses-PRISMA_space-MNI152NLin2009cAsym_res-2_label-WM_probseg.nii.gz
        sub-01_ses-PRISMA_space-MNI152NLin2009cAsym_res-2_label-CSF_probseg.nii.gz
        sub-01_ses-PRISMA_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.nii.gz
        sub-01_ses-PRISMA_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.json
        sub-01_ses-PRISMA_space-MNI152NLin2009cAsym_res-2_dseg.nii.gz
    fmap/
        sub-01_ses-PRISMA_run-2_fmapid-auto00002_desc-coeff_fieldmap.nii.gz
        sub-01_ses-PRISMA_run-1_fmapid-auto00000_desc-coeff_fieldmap.nii.gz
        sub-01_ses-PRISMA_run-2_fmapid-auto00002_desc-epi_fieldmap.nii.gz
        sub-01_ses-PRISMA_run-1_fmapid-auto00001_desc-coeff_fieldmap.nii.gz
        sub-01_ses-PRISMA_run-2_fmapid-auto00002_desc-preproc_fieldmap.nii.gz
        sub-01_ses-PRISMA_run-2_fmapid-auto00002_desc-preproc_fieldmap.json
        sub-01_ses-PRISMA_run-1_fmapid-auto00000_desc-epi_fieldmap.nii.gz
        sub-01_ses-PRISMA_run-1_fmapid-auto00001_desc-epi_fieldmap.nii.gz
        sub-01_ses-PRISMA_run-1_fmapid-auto00000_desc-preproc_fieldmap.nii.gz
        sub-01_ses-PRISMA_run-1_fmapid-auto00000_desc-preproc_fieldmap.json
        sub-01_ses-PRISMA_run-1_fmapid-auto00001_desc-preproc_fieldmap.nii.gz
        sub-01_ses-PRISMA_run-1_fmapid-auto00001_desc-preproc_fieldmap.json
        sub-01_ses-PRISMA_run-3_fmapid-auto00003_desc-coeff_fieldmap.nii.gz
        sub-01_ses-PRISMA_run-3_fmapid-auto00003_desc-epi_fieldmap.nii.gz
        sub-01_ses-PRISMA_run-3_fmapid-auto00003_desc-preproc_fieldmap.nii.gz
        sub-01_ses-PRISMA_run-3_fmapid-auto00003_desc-preproc_fieldmap.json
    func/
        sub-01_ses-PRISMA_task-rest_dir-ap_run-1_from-scanner_to-T1w_mode-image_xfm.txt
        sub-01_ses-PRISMA_task-rest_dir-ap_run-1_from-T1w_to-scanner_mode-image_xfm.txt
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_from-scanner_to-T1w_mode-image_xfm.txt
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_from-T1w_to-scanner_mode-image_xfm.txt
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_from-scanner_to-T1w_mode-image_xfm.txt
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_from-T1w_to-scanner_mode-image_xfm.txt
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_from-scanner_to-T1w_mode-image_xfm.txt
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_from-T1w_to-scanner_mode-image_xfm.txt
        sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.gz
        sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.json
        sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_space-MNI152NLin2009cAsym_res-2_boldref.nii.gz
        sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.nii.gz
        sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.json
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.gz
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.json
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_space-MNI152NLin2009cAsym_res-2_boldref.nii.gz
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.nii.gz
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.json
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.gz
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.json
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_space-MNI152NLin2009cAsym_res-2_boldref.nii.gz
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.nii.gz
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.json
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.gz
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.json
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_space-MNI152NLin2009cAsym_res-2_boldref.nii.gz
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.nii.gz
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_space-MNI152NLin2009cAsym_res-2_desc-brain_mask.json
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_space-MNI152NLin6Asym_desc-smoothAROMAnonaggr_bold.nii.gz
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_space-MNI152NLin6Asym_desc-smoothAROMAnonaggr_bold.json
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_AROMAnoiseICs.csv
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_desc-MELODIC_mixing.tsv
        sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_AROMAnoiseICs.csv
        sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_desc-MELODIC_mixing.tsv
        sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_space-MNI152NLin6Asym_desc-smoothAROMAnonaggr_bold.nii.gz
        sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_space-MNI152NLin6Asym_desc-smoothAROMAnonaggr_bold.json
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_desc-confounds_timeseries.tsv
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-2_part-mag_desc-confounds_timeseries.json
        sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_desc-confounds_timeseries.tsv
        sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_desc-confounds_timeseries.json
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_AROMAnoiseICs.csv
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_desc-MELODIC_mixing.tsv
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_space-MNI152NLin6Asym_desc-smoothAROMAnonaggr_bold.nii.gz
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_space-MNI152NLin6Asym_desc-smoothAROMAnonaggr_bold.json
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_desc-confounds_timeseries.tsv
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-3_part-mag_desc-confounds_timeseries.json
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_AROMAnoiseICs.csv
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_desc-MELODIC_mixing.tsv
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_desc-confounds_timeseries.tsv
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_desc-confounds_timeseries.json
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_space-MNI152NLin6Asym_desc-smoothAROMAnonaggr_bold.nii.gz
        sub-01_ses-PRISMA_task-ROSETTA_dir-ap_run-1_part-mag_space-MNI152NLin6Asym_desc-smoothAROMAnonaggr_bold.json

**Comment by vytautasl1337** [comment]
fullpath I give to the script is '/mnt/scratch/PBCTI/BIDS/BIDS_dataset_20230531-1633/derivatives/fmriprep-22.0.2/sub-01/ses-PRISMA/func/sub-01_ses-PRISMA_task-rest_dir-ap_run-1_part-mag_space-MNI152NLin2009cAsym_res-2_desc-preproc_bold.nii.gz'
Only the run number is changing

**Comment by tsalo** [comment]
Thanks @vytautasl1337! It seems possible that `load_confounds` is having trouble with the `dir` or `part` entities specifically. I'll take a look at the code.

**Comment by Remi-Gau** [comment]
See #3020

**Comment by vytautasl1337** [comment]
Hi @tsalo. I managed to get to the last part of your code, but I get this error, any ideas how to fix it?

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mrhome/vytautasl/anaconda3/envs/mri/lib/python3.8/site-packages/nilearn/interfaces/fmriprep/load_confounds.py", line 343, in _load_single_confounds_file
    loaded_confounds, missing = _load_noise_component(
  File "/mrhome/vytautasl/anaconda3/envs/mri/lib/python3.8/site-packages/nilearn/interfaces/fmriprep/load_confounds.py", line 362, in _load_noise_component
    loaded_confounds = getattr(components, f"_load_{component}")(
AttributeError: module 'nilearn.interfaces.fmriprep.load_confounds_components' has no attribute '_load_s'

**Comment by htwangtw** [comment]
> any ideas how to fix it?
Change `strategy = "scrub"` to `strategy = ["scrub"]`

**Comment by vytautasl1337** [comment]
It worked @htwangtw , thank you :)
