### ISSUE TITLE
Replace resting_state == False by np.logical_not(resting_state) in examples

### ISSUE THREAD

**Issue by lesteve** [nilearn/nilearn#381]
This gives a PEP8 warning and np.logical_not(resting_state) seems more readable to me. We could also use an additional variable like `non_resting_state_mask = np.logical_not(resting_state)` because resting_state == False is used quite a few times in the examples:

Examples affected by this: 
```
~/dev/alt_nilearn $ git grep -n 'resting_state == False'
examples/decoding/plot_haxby_different_estimators.py:23:categories = np.unique(stimuli[resting_state == False])
examples/decoding/plot_haxby_different_estimators.py:26:session_labels = labels["chunks"][resting_state == False]
examples/decoding/plot_haxby_different_estimators.py:35:masked_timecourses = masker.fit_transform(func_filename)[resting_state == Fals
examples/decoding/plot_haxby_different_estimators.py:90:        classification_target = stimuli[resting_state == False] == category
examples/decoding/plot_haxby_different_estimators.py:137:masked_timecourses = masked_timecourses[condition_mask[resting_state == False
examples/decoding/plot_haxby_full_analysis.py:32:categories = np.unique(stimuli[resting_state == False])
examples/decoding/plot_haxby_full_analysis.py:35:session_labels = labels["chunks"][resting_state == False]
examples/decoding/plot_haxby_full_analysis.py:61:        func_filename)[resting_state == False]
examples/decoding/plot_haxby_full_analysis.py:68:        classification_target = stimuli[resting_state == False] == category
```

**Comment by GaelVaroquaux** [comment]
> ~resting_state seems more readable to me.

That's onlny because you know C (or matlab, actually). To a layman, it's
not readable at all. I like to push people to use np.logical_not in the
codebase.

**Comment by AlexandreAbraham** [comment]
> I like to push people to use np.logical_not in the codebase.

:+1:

**Comment by lesteve** [comment]
Fair enough, I switched the title to np.logical_not. Also for the sake of completeness I don't know matlab.

**Comment by GaelVaroquaux** [comment]
> Also for the sake of completeness I don't know matlab.

I am sorry. I didn't mean to insult you :)

**Comment by lesteve** [comment]
>> Also for the sake of completeness I don't know matlab.

> I am sorry. I didn't mean to insult you :)

No worries, no offense taken ;-).

**Comment by salma1601** [comment]
I am working on it
