### ISSUE TITLE
[ENH] using dictionary or ICA time course for correction / regression

### ISSUE THREAD

**Issue by garincle** [nilearn/nilearn#3813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

Hello, 
I would like to know if it would be possible to extract ICA or preferentially dictionary time course for BOLD signal correction.

By saying I mean putatively correcting the signal as in 
fsl_regfilt
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/MELODIC#fsl_regfilt_command-line_program

if yes, is their a way to extract the time course of the component selected as "artifact"  in the dictionnary learning analysis and then format the time course in the "melodic_mix" format (if it mathematically make sense mathematically to do so)

if it doesn't, is their another way to correct the original signal using the dictionary component labeled as "artifact"

this would be wonderful, as for me, dictionary learning gives way better results than ICA, allow to identify obvious artifact that I would like to remove to obtain a clean BOLD image.

Thank you!!

### Benefits to the change

Amazing feature to correct BOLD signal

### Pseudocode for the new behavior, if applicable

```python
# insert your code below

```

**Comment by bthirion** [comment]
Hi, thank you for the suggestion. To me what you propose sounds like an implementation of AROMA, that people would typically run when using FMRIPrep. I'm wondering why we should also have some features in Nilearn ? Is there any motivation not to use fMRIPrep ?
Just wondering.

**Comment by garincle** [comment]
Hi, thank you for your answer. I am working with non-human species so fMRI prep is not an option for me. Dictionary learning showed way better results than ICA in all the species I've studied so far. 
If adding that to nilearn is not an option (which I can totally understand), would you have an advise to code it myself? 
I guess that just regressing the mean time course of the most significant voxels of the component selected as "artifact" would not be a great option? 
or using the mean time course of  the most significant voxels of the component selected as "artifact" and feed it to fsl_regfilt either? 
I am sadly not knowledgeable enough to know what I would really doing "mathematically speaking" if am using this approach

**Comment by bthirion** [comment]
After running dictionary learning decomposition you can get the corresponding time courses through the transform method. 
E.g. after running https://github.com/nilearn/nilearn/blob/main/examples/03_connectivity/plot_compare_decomposition.py
```signals = dict_learning.transform(func_filenames)```
then select the signals that are artefactueal and regress them out from your data. Does that make sense ?

**Comment by garincle** [comment]
yes, thank you, that make sense, I was not really sure if it was mathematically correct =)
Clément
