### ISSUE TITLE
[BUG] `func.gii` files not recognized in `interfaces.fmriprep.load_confounds`

### ISSUE THREAD

**Issue by askieslinger** [nilearn/nilearn#3817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

SUSE Linux Enterprise Server 12 SP5

### Python version

- [ ] 3.11
- [ ] 3.10
- [ ] 3.9
- [X] 3.8
- [ ] 3.7

### nilearn version

0.10.1.dev

### Expected behavior

```     python
fmriprep.load_confounds(
                gii_path,
                strategy=['motion', 'wm_csf', 'global_signal', 'high_pass'],
                motion='basic',
                demean=False)[0]
```
should return confounds. 

### Current behavior & error messages

This is what I got: Returns error message "'need fMRIprep output with extension func.gii'".

Problem: My file is an fmriprep output and proper gifti file according to [bids](https://bids-specification.readthedocs.io/en/stable/05-derivatives/03-imaging.html#discrete-surface-segmentations). This states that identifier 'hemi' comes before identifier 'space'.
This is the other way around here ('space' before 'hemi'): https://github.com/nilearn/nilearn/blob/787d662116a0808d074b0dd40c9b4c2498712819/nilearn/interfaces/fmriprep/load_confounds_utils.py#L19-L24

Suggestion: change to 
```python
img_file_patterns = {
    "aroma": "_desc-smoothAROMAnonaggr_bold",
    "nii.gz": "(_space-.*)?_desc-preproc_bold.nii.gz",
    "dtseries.nii": "(_space-.*)?_bold.dtseries.nii",
    "func.gii": "_hemi-[LR](_space-.*)?_bold.func.gii",
}
```

I think this confusion stems from an error in the fmriprep documentation https://github.com/nipreps/fmriprep/issues/3054

### Steps and code to reproduce bug

```python
from nilearn.interfaces import fmriprep
image_file='/user/data/derivatives/fmriprep/sub-s1/ses-s1/func/sub-s1_ses-s1_task-t1_acq-acq1_run-5_hemi-R_space-fsnative_bold.func.gii'
fmriprep.load_confounds(
                image_file,
                strategy=['motion', 'wm_csf', 'global_signal', 'high_pass'],
                motion='basic',
                demean=False)


```

**Comment by Remi-Gau** [comment]
Indeed hemi comes before space.

https://github.com/OpenNeuroDerivatives/ds000001-fmriprep/blob/2c7938fa2871889803a89cd408e1f7db5a1a695b/sub-01/func/sub-01_task-balloonanalogrisktask_run-1_hemi-R_space-fsaverage5_bold.func.gii

Will open a PR to fix
