### ISSUE TITLE
Change setting of bug issue template to require nilearn version as text

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3818]
Issue template for bugs requires nilearn version from a dropdown menu. This is already out of date and since it has to be updated manually it is easy to forget. I suggest to make it a required text area instead

https://github.com/nilearn/nilearn/blob/3b0547377429b537ab788356e391103bbb8b2767/.github/ISSUE_TEMPLATE/bug.yml?plain=1#L59-L75

**Comment by Remi-Gau** [comment]
Fine with me. 👍🏾 
Let's see how creative users can be when they report version numbers. 😝
