### ISSUE TITLE
Silence standardize deprecation warnings not possible with functions that set parameter internally 

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3825]
One issue with silencing all instances of this warning in our examples gallery is that the ones that are still throwing the warning come from the functions `plot_carpet` and `ConnectivityMeasure.fit_transform` which call `signal.clean` with the parameter `standardize` equal to `True` or `"zscore"` internally so these are not exposed to the user. Hence the warning doesn't make sense for these cases as the user has no control and cannot call the new behavior. Probably best to open a new issue to see how to resolve this. Might need to add a deprecated parameter to allow the user to access the new behavior with these functions.

The relevant lines are:
https://github.com/nilearn/nilearn/blob/bce754beea677d4d4a51191e21c64d09002f1429/nilearn/connectome/connectivity_matrices.py#L497
and 
https://github.com/nilearn/nilearn/blob/bce754beea677d4d4a51191e21c64d09002f1429/nilearn/plotting/img_plotting.py#L1430

_Originally posted by @ymzayek in https://github.com/nilearn/nilearn/issues/3821#issuecomment-1625330400_

**Comment by liuzhenqi77** [comment]
Thanks for posting! 

This change for `standardize`, as well as for `standardize_confounds` in the original PR, might also influence default cases for `load_confounds()`? @htwangtw 

e.g. https://github.com/SIMEXP/fmriprep-denoise-benchmark/blob/b9d44504384b3641dbd1d063105cb6eb99713488/fmriprep_denoise/dataset/timeseries.py#L115

btw, specifically for `standardize_confounds=False`, there is a step to control the range of confounds implemented a few years ago before `load_confounds()`, I was wondering if it is still relevant (safe to use)?

https://github.com/nilearn/nilearn/blame/321494420f95c7a5e2172108400194b37a02e628/nilearn/signal.py#L784

**Comment by htwangtw** [comment]
> This change for `standardize`, as well as for `standardize_confounds` in the original PR, might also influence default cases for `load_confounds()`? @htwangtw
> 
> e.g. https://github.com/SIMEXP/fmriprep-denoise-benchmark/blob/b9d44504384b3641dbd1d063105cb6eb99713488/fmriprep_denoise/dataset/timeseries.py#L115

Yes technically it will, as now `True` is mapped to `zscore`, not `zscore_sample`, but I expect the influence to be at float point level. 

> btw, specifically for standardize_confounds=False, there is a step to control the range of confounds implemented a few years ago before load_confounds(), I was wondering if it is still relevant (safe to use)?

What this chunk of code is doing is just rescaling the confound values to +/-1. This is still relevant to confound that's ingested through `load_confounds`

**Comment by htwangtw** [comment]
> > btw, specifically for standardize_confounds=False, there is a step to control the range of confounds implemented a few years ago before load_confounds(), I was wondering if it is still relevant (safe to use)?
> 
> What this chunk of code is doing is just rescaling the confound values to +/-1. This is still relevant to confound that's _not_ ingested through `load_confounds`

@liuzhenqi77 I missed a critical word that changed the whole meaning of the sentence in my original response.... just letting you know
