### ISSUE TITLE
[DOC] `load_confounds` private function docstrings

### ISSUE THREAD

**Issue by htwangtw** [nilearn/nilearn#3826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

I feel the need to complete the docstrings of some private functions. 
Some private functions are complex enough that need docstrings for contributors to understand the logics.
And perhaps some typos.

### List any pages that would be impacted.

None. Just private functions.

**Comment by bthirion** [comment]
It's huge, isn't it ?

**Comment by htwangtw** [comment]
I can list a few functions as priorities. Definitely no need to do the whole thing
