### ISSUE TITLE
[DOC] Add cross-reference links to type definitions in public surface functions

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

Use sphinx cross-referencing where possible in surface module public functions so that rendered docstrings will link the types to their source documentation.

See functions https://nilearn.github.io/stable/modules/surface.html

Example: 
```python 
"""
  radius : float
    The size (in mm) of the neighbourhood... 
"""
```

becomes

```python
"""
    radius : :obj:`float`
        The size (in mm) of the neighbourhood... 
"""
```

For more examples check out docstrings in other modules where this was done like: 

https://github.com/nilearn/nilearn/blob/321494420/nilearn/interfaces/bids/query.py#L146

And the corresponding rendered version:

https://nilearn.github.io/stable/modules/generated/nilearn.interfaces.bids.get_bids_files.html#nilearn.interfaces.bids.get_bids_files

**Comment by Remi-Gau** [comment]
Sounds like another issue that could generate "siblings" for other modules if we need to create other issues during the hackathon.

**Comment by htwangtw** [comment]
I am going to have a first pass on this and see what's the process
