### ISSUE TITLE
[ENH] Surface GLM - Support multiple runs in a GLM

### ISSUE THREAD

**Issue by smeisler** [nilearn/nilearn#3846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

Related to neurostars post: https://neurostars.org/t/glm-on-surface-data-in-nilearn/22632

It would be good if Nilearn could run GLMs on surface data with multiple BOLD runs. Currently, the only way to run a GLM on surface data (`nilearn.glm.first_level.run_glm`), which only accepts one BOLD run and design matrix per instance.

### Benefits to the change

More flexible processing for multi-run surface analyses.

### Pseudocode for the new behavior, if applicable

I imagine an easiest, but not most stylish, change would be to have `run_glm` accept an iterable object for `[X]` and `[Y]`. If the length of these iterable objects are 1, then run the function as normal. If not, apply whatever fixed effect models are used for the multi-run GLMs on BOLD data.

Thoughts?

**Comment by bthirion** [comment]
Thx for opening  this. What we need is a SurfaceFirstLevelModel object that can has an API similar to the FirstLevelModel. We'll do that as soon as we have a decent SurfaceMasker.

**Comment by Remi-Gau** [comment]
Will close this one as completed by #4126.

See examples:
- https://github.com/nilearn/nilearn/blob/main/examples/08_experimental/plot_localizer_new_surface_analysis_experimental.py
- https://github.com/nilearn/nilearn/blob/main/examples/08_experimental/plot_new_surface_bids_analysis_experimental.py
 
Feedbacks are welcome.
