### ISSUE TITLE
[DOC] Add commands to get the version tags when forking in the contributing-setting up your env doc

### ISSUE THREAD

**Issue by FrancoisPgm** [nilearn/nilearn#3850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

To have the proper version attached to a fork it is required to add the source repo as upstream and fetch all the tags so that they can be used to display the current version. This is done by running the following commands :

`git remote add upstream git@github.com:nilearn/nilearn.git`
`git fetch --all`

These commands could be added to the doc in the setting up your environnement section of the contributing page.

### List any pages that would be impacted.

https://nilearn.github.io/dev/development.html#setting-up-your-environment

**Comment by Remi-Gau** [comment]
will update the doc
