### ISSUE TITLE
Provide examples of "gold standard" parts of codebase where contributors can model their code on

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3859]
Suggestion by @psadil to point to parts of the codebase which are the best examples of e.g. unit tests, function complexity, docstrings, etc. It is helpful to reference code when starting on a big codebase like this but since different parts of the codebase are in different states it would be nice to point people to specific files that have been recently refactored and formatted properly. This would entail adding some links with a brief explanation in the contributing docs. What do others think?

**Comment by Remi-Gau** [comment]
# YYYYYYYYYYYYYYEEEEEEEEEEEEEEEESSSSSSSSSSS  !!!!

# 🚀 

# ❤️

**Comment by bthirion** [comment]
Hm, I'm just afraid of providing comments on code quality that will be quickly outdated. Such information is hard to maintain up-to-date...

**Comment by ymzayek** [comment]
> Hm, I'm just afraid of providing comments on code quality that will be quickly outdated. Such information is hard to maintain up-to-date...

This is a good point and since we started adding guidelines with toy examples to the contributing docs I don't think we still need to do what is suggested in this issue. Closing for now
