### ISSUE TITLE
Apply black to the files still involved in other pull requests

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3861]
- realized that during the hackathon some people would use black and end up reformating files that should not have because they are still involved in other PRs
- some of the PRs with those files have been opened for a certain amount of time and it may still take some time for them to be finished

it would be nice to find a way to be able to apply black to the whole codebase and minimize merge conflicts on those old PRs

possible route: 

- apply black to a file in main
- use the same black config to reformat the file in the PR
- hopefully this should be easy (#FamousLastWords)

**Comment by bthirion** [comment]
No better suggestion. How far are we with black. I thought it was over (did not check carefully, sorry).

**Comment by Remi-Gau** [comment]
We are done for all the files not involved in PR.
The list of excluded files is in the pyproject.toml.
But during the hackathon we realized that those  excluded files can still lead to headaches if people's IDE is set to auto reformat or if they run black manually on some files.
So it is better to find a way to finish the job completely.

**Comment by bthirion** [comment]
We should try your approach in one submodule and see how well it goes.

**Comment by Remi-Gau** [comment]
Either that or do it PR by PR.

**Comment by ymzayek** [comment]
We can start with files in PRs opened by core devs

**Comment by Remi-Gau** [comment]
You read my mind.

**Comment by Remi-Gau** [comment]
started trying "fixing black" on some of the old PRs... it feels that it will prove a bit of headache in any case
will try with a couple more but it seems that there will always some merge conflicts to fix

**Comment by bthirion** [comment]
But "There is no alternative" as they put it...

**Comment by ymzayek** [comment]
I linked these latest PRs here but I misread the title of the issue. The new blacked files are NOT involved in pull requests

**Comment by Remi-Gau** [comment]
I would suggest to format the last few remaining files before the next release:

```
examples/01_plotting/plot_3d_map_to_surface_projection.py
nilearn/plotting/html_surface.py
nilearn/plotting/js_plotting_utils.py
nilearn/plotting/surf_plotting.py
nilearn/plotting/tests/test_surf_plotting.py
nilearn/surface/surface.py
nilearn/surface/tests/test_surface.py
```

many of them were not formatted due to some old PR related to surface handling
