### ISSUE TITLE
Revert to one plot per figure in plot_roi_extraction.py

### ISSUE THREAD

**Issue by lesteve** [nilearn/nilearn#387]
Having multiple plots per figure may look better when running the examples interactively but it makes the narrative documentation a lot more obscure.

For example:
* the [Smoothing](http://nilearn.github.io/building_blocks/manipulating_mr_images.html#smoothing) section has both the smoothed EPI and a p-values plot.

* the [Selecting features](http://nilearn.github.io/building_blocks/manipulating_mr_images.html#selecting-features) section has again the smoothed EPI and the p-values plot.

That also means that the numbering of the pngs in the rst will have to be changed accordingly. Remember to regenerate the doc to make sure everything looks fine.

**Comment by bthirion** [comment]
Just to clarify: are there other examples with the one you mentioned ? Do you suggest that the plots should be separated more systematically ?

**Comment by lesteve** [comment]
> Just to clarify: are there other examples with the one you mentioned ?

Those are the only ones I can remember.

> Do you suggest that the plots should be separated more systematically ? 

It the example is included in some narrative documentation it makes more sense to have one plot per figure because it makes the insertion of plots more seamless: i.e. code snippet - plot - code snippet - plot - etc ...

I think there were some discussion about this kind of things in other issues I'll have to find them again.

**Comment by banilo** [comment]
cf. 

#331 
#259

**Comment by salma1601** [comment]
doing this
