### ISSUE TITLE
[MAINT] Standardize tabs and spaces in pyproject.toml

### ISSUE THREAD

**Issue by emdupre** [nilearn/nilearn#3870]
Currently, the pyproject.toml has a mix of tabs and spaces, leading to `black` placing unevent alignment here:

https://github.com/nilearn/nilearn/blob/a95149b2162eff9bc4c0b6fe503533311a700f02/pyproject.toml#L58-L75

and here: 

https://github.com/nilearn/nilearn/blob/a95149b2162eff9bc4c0b6fe503533311a700f02/pyproject.toml#L92-L98

[Best-practice](https://peps.python.org/pep-0008/) would be to standardize to spaces. I'm happy to do this, but it also makes a good first issue 😸

**Comment by Remi-Gau** [comment]
there's a pre-commit hook for that: https://github.com/macisamuele/language-formatters-pre-commit-hooks

**Comment by emdupre** [comment]
There is one for everything 😸  It looks like you're going ahead and adding that rather than using this as a GFI, so I'll remove that label !

**Comment by Remi-Gau** [comment]
by the way I am noticing some inconsistencies in our yaml in terms of spacing... So given that there is pre-commit hook for everything... Should I just?
