### ISSUE TITLE
Choose better affine constant for plotting test data

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3874]
At the time I was "just" refactoring code and started adding fixtures when doing so. So I did not have a close look at the exact content.

Digging into this now I realize we may have some inconsistency.

```python
from nilearn.plotting.img_plotting import MNI152TEMPLATE
mni_affine = MNI152TEMPLATE.get_affine()
print(mni_affine)
```

gives
```
[[   2.    0.    0.  -98.]
 [   0.    2.    0. -134.]
 [   0.    0.    2.  -72.]
 [   0.    0.    0.    1.]]
```

which does not quite match that in conf.py

```python
MNI_AFFINE = np.array(
    [
        [-2.0, 0.0, 0.0, 90.0],
        [0.0, 2.0, 0.0, -126.0],
        [0.0, 0.0, 2.0, -72.0],
        [0.0, 0.0, 0.0, 1.0],
    ]
)
```

_Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/issues/3172#issuecomment-1662060133_

**Comment by bthirion** [comment]
OK for changing the one in conf.py.

**Comment by htwangtw** [comment]
One thing that I noticed from these numbers: These two affine metrics are derived from different templates.
 
The affine in the original `conf.py` is from the MNI 2mm template shipped with FSL (MNI152NLin6Asym on templateflow repo)
`MNI152TEMPLATE` is generated from function `load_mni152_template(resolution=2)` in `nilearn.datasets`. The behaviour of this function is resampling a MNI 1mm template.
I remember this caused some behaviour changes from almost 2 years ago, but perhaps not crucial enough that it when above my head....

**Comment by Remi-Gau** [comment]
Important to know though from working on #3882 it seems that the precise numbers used in some  tests should not make a big difference: many tests just need an image (any image) and would be equally fine with an "eye_affine" AFAICT.

Maybe I should try that as part of #3882: use eye_affine everywhere it can be used: otherwise it can people who read the test to think an "mni_affine" is needed.
