### ISSUE TITLE
[BUG] plot_event cannot handle events with 0 duration

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

For example one of the following:
- Linux Ubuntu 22.04
- Mac OS Version 12 "monterey"
- Windows 11

### Python version

- [X] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8
- [ ] 3.7

### nilearn version

0.10.2.dev

### Expected behavior

events with zero duration should be displayed by "delta functions"

### Current behavior & error messages

![Figure_2](https://github.com/nilearn/nilearn/assets/6961185/09c2f29e-c47d-4811-8788-c33d39f09136)

compare to when setting event duration to 1 second

![Figure_1](https://github.com/nilearn/nilearn/assets/6961185/5f413f21-504d-40f6-9daa-20b310823be8)

### Steps and code to reproduce bug

```python
from nilearn.plotting import plot_event
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

onsets = [
    0.0,   2.4,   8.7,   11.4,  15.0,  18.0,  20.7,  23.7,  26.7,  29.7
]
trial_types = ["foo" for _ in onsets]

# with duration = 1 sec
durations = np.ones_like(onsets)
events = pd.DataFrame(
    {
        "trial_type": trial_types,
        "onset": onsets,
        "duration": durations,
    }
)
plot_event(events)
plt.show()

# with duration = 0 sec
durations = np.zeros_like(onsets)
events = pd.DataFrame(
    {
        "trial_type": trial_types,
        "onset": onsets,
        "duration": durations,
    }
)
plot_event(events)
plt.show()
```

**Comment by bthirion** [comment]
I don't really see how we should handle events with null duration. Strictly speaking, these events have not taken place. I don't see how we should display them ?

**Comment by Remi-Gau** [comment]
Well... to the extend that they are convolved and will be included in the design matrix (see below) I think that we should probably display them somehow, no?

```python
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from nilearn.glm.first_level import make_first_level_design_matrix
from nilearn.plotting import plot_design_matrix

onsets = [0.0, 2.4, 11.4, 18.0, 20.7, 23.7, 26.7, 29.7]
trial_types = ["foo" for _ in onsets]

# with duration = 0 sec
durations = np.zeros_like(onsets)
events = pd.DataFrame(
    {
        "trial_type": trial_types,
        "onset": onsets,
        "duration": durations,
    }
)

tr = 1.0
n_scans = 40
frame_times = np.arange(n_scans) * tr

X1 = make_first_level_design_matrix(
    frame_times,
    events,
    drift_model="polynomial",
    drift_order=3,
    hrf_model="spm",
)

fig, (ax1, ax2) = plt.subplots(figsize=(10, 6), nrows=1, ncols=2)
plot_design_matrix(X1, ax=ax1)
ax1.set_title("Event-related design matrix", fontsize=12)
plt.plot(X1["foo"])
ax2.set_title("predicted time course of 'foo'", fontsize=12)
plt.show()
```

![Figure_1](https://github.com/nilearn/nilearn/assets/6961185/13637b2e-9eba-40df-af27-ac2e12398e06)

**Comment by bthirion** [comment]
Oops, this is a bug, we should get a warning and no foo regressor created :-(

**Comment by tsalo** [comment]
Typically events with durations of zero are modeled as stick functions, right? What about plotting them as vertical lines?

**Comment by Remi-Gau** [comment]
> Typically events with durations of zero are modeled as stick functions in tools like SPM, right? What about plotting them as vertical lines?

Yes this is my prior experience with 0 duration events as well hence why I raised the issue because it did not match my expectation.

Do we know what AFNI and FSL do?

It'd good to know if "most" softwares behave in a similar fashion and try to match that behavior.

If there is no consensus then... let's add to the pile of fun ways in which softwares may give different results... But let's burn that bridge when we get to it.

**Comment by bthirion** [comment]
The problem is that when you convolve these events with an hrf, you need to give them a duration, which is arbitrary (would be something like repetition_time / oversampling factor). And we're making silently a decision on data. So, I agree that we should try and match other software's behavior to minimize surprise, but I'm wary about arbitrary and undisclosed decisions

**Comment by Remi-Gau** [comment]
> (would be something like repetition_time / oversampling factor).

pretty sure this is what SPM does

I suspect that some duration is already given to those zero duration event in nilearn: we may just need to make that more explicit.

**Comment by Remi-Gau** [comment]
I asked for feedback on neurostars.

apparently (old) FSL behaves the same way.

**Comment by bthirion** [comment]
Yes, you're right
https://github.com/nilearn/nilearn/blob/main/nilearn/glm/first_level/hemodynamic_models.py#L431
If I has to do it from scratch I wouldn't do that, but I think it's better to remain bw-compatible, this will probably better meet user's expectations. But this requires a warning !

To get back to the initial discussion,  I agree with @tsalo 's suggestion.

**Comment by Remi-Gau** [comment]
OK 
agreed on the warning and using stick functions

Note to self: also check how are NaN and 'n/a' in events.tsv handled

**Comment by Remi-Gau** [comment]
@bthirion 
while working on this in #3943 I decided to test a few things to see if some errors or warnings would be thrown.

Adding the BIDS "status" for those: more for reference

- design with NaN onsets or NaN durations (technically disallowed in BIDS but it seems this is not caught by the BIDS validator): no warning, no error 

In my opinion:
- events with NaN onsets or durations: they should be dropped and at least throw a warning / maybe an error?

**Comment by bthirion** [comment]
Should be an error IMHO.

**Comment by Remi-Gau** [comment]
OK that sounds safer indeed

**Comment by hugofluhr** [comment]
Hi, I wanted to follow up on this:
I have events with null duration (button presses) and I do get the warning that you implemented but I can't find the information of how this null durations are handled, could you give me a pointer?

**Comment by Remi-Gau** [comment]
So null duration will be plotted with a stick function:

see this comment in the PR

https://github.com/nilearn/nilearn/pull/3943#issuecomment-1703862492

**Comment by Remi-Gau** [comment]
Also this example has some null duration events: https://nilearn.github.io/dev/auto_examples/04_glm_first_level/plot_write_events_file.html#sphx-glr-auto-examples-04-glm-first-level-plot-write-events-file-py

**Comment by Remi-Gau** [comment]
do you think we should update the documentation of the function to make this explicit?

**Comment by hugofluhr** [comment]
@Remi-Gau thanks for the references!
I think it might be nice to explicitly say how these 0 duration events are handled when creating a GLM but maybe that's because I'm not familiar with how it's done in other tools.
