### ISSUE TITLE
reorder plot_glass_brain args to conform to plot_roi, plot_stat_map examples

### ISSUE THREAD

**Issue by bcipolli** [nilearn/nilearn#390]
`plot_roi` and `plot_stat_map` are used in the examples using the 2nd positional arguments for the background image.  I tried the same with `plot_glass_brain`, and it failed.

For consistency, I believe the 2nd arg to `plot_glass_brain` should be `bg_img`.

An alternate change would be to do everything by `kwargs` in the examples, so there's no such expectation.

**Comment by bcipolli** [comment]
I'm an idiot.

**Comment by lesteve** [comment]
That must be one of the fastest resolved nilearn issue ever, good for our statistics :wink: !
