### ISSUE TITLE
dead code: decorator for deprecated arguments

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3903]
The decorator introduced in glm.regression in this commit seems now unused.

https://github.com/nilearn/nilearn/commit/e6591d8907ceae55eea6f04ce181acb6a12743b5

I wonder if it is better to remove it or to move it to _utils.helpers where other deprecation handling tools are located and to do some refactoring where possible to "standardize" how deprecation warnings are sent.

**Comment by bthirion** [comment]
I'd remove it.
