### ISSUE TITLE
Drop-in hours

### ISSUE THREAD

**Issue by ucigrangers** [nilearn/nilearn#3913]
Hello,

I am writing to hopefully confirm that there will be nilearn drop-in hours on 8/16 as the link here says https://arewemeetingyet.com/UTC/2023-01-18/16:00/w/Nilearn%20Drop-in%20Hours#eyJ1cmwiOiJodHRwczovL21lZXQuaml0LnNpL25pbGVhcm4tZHJvcC1pbi1ob3VycyJ9

Alternatively, will there be an upcoming 'drop-in' hours in September that will be scheduled? 

I have a series of questions about FirstLevelModeling parameters, designing SecondLevelModels to test differences between groups, and optimizing searchlight analyses. 

Thank in advance!

**Comment by emdupre** [comment]
Hi @ucigrangers !

Drop-in hours are paused until September, as noted in https://github.com/nilearn/nilearn/issues/3211

I'd encourage you to ask questions on [NeuroStars](https://neurostars.org) in the mean time, though, and folks will be able to answer questions there asynchronously !

**Comment by ymzayek** [comment]
Closing this issue as the drop-in hours will restart next week. That link has the right information.
