### ISSUE TITLE
Relax restriction on Sphinx version when a compatible version of sphinx gallery has been released

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3916]
Sphinx 7.2.0 has just been released and caused an [issue with the furo theme](https://github.com/pradyunsg/furo/discussions/693). This is documented in [this issue ](https://github.com/sphinx-doc/sphinx/issues/11608)on sphinx's github. Should we downgrade to sphinx 7.1.2 until this is patched?

**Comment by Remi-Gau** [comment]
thanks for looking into this: I would that capping the sphinx dependency at 7.1.2 until this bug is fixed makes sense.

**Comment by AA-Turner** [comment]
Please test with [Sphinx 7.2.2](https://pypi.org/project/Sphinx/7.2.2/).

A

**Comment by Remi-Gau** [comment]
thanks for the ping
just triggered a re run of the failed build on our main, let's see if it grabs the latest release and what happens

**Comment by Remi-Gau** [comment]
so far it did get the latest 7.2.2 and is building...

**Comment by Remi-Gau** [comment]
Ok with 7.2.2 it seems that the problem is with shpinx gallery

**Comment by Remi-Gau** [comment]
Related to this fix on sphinx gallery: https://github.com/sphinx-gallery/sphinx-gallery/pull/1176

Will pin our sphinx version to < 7.2.0 until there is a new sphinx gallery release

**Comment by Remi-Gau** [comment]
Renaming this issue so we remember to check for a new release of sphinx gallery
