### ISSUE TITLE
flaky `test_plotly_savefig` time-out on GHA workflow for tests on windows 

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3925]
Some examples:

- Windows 3.11: timing out on `nilearn/plotting/tests/test_surf_plotting.py::test_plotly_savefig` 
  - https://github.com/nilearn/nilearn/actions/runs/5957291727/job/16159723334

- Windows 3.9: timing out on `nilearn/plotting/tests/test_surf_plotting.py::test_plotly_savefig` 
  - https://github.com/nilearn/nilearn/actions/runs/5940176071/job/16108183249

- Windows 3.8: timing out on `nilearn/plotting/tests/test_surf_plotting.py::test_plotly_savefig` 
  - https://github.com/nilearn/nilearn/actions/runs/5927574875/job/16071361730

**Comment by bthirion** [comment]
Thx ! What could be the cause for that ?

**Comment by ymzayek** [comment]
I guess it could be a memory leak. Also we could think of updating tests like this one to use `tmp_path` instead of `tmpdir` seeing as the former is a pathlib.Path object.

**Comment by Remi-Gau** [comment]
The issue is still there: https://github.com/nilearn/nilearn/actions/runs/6012829224/job/16308959201

**Comment by Remi-Gau** [comment]
Seeing a lot more of this failure recently. More "annoying" is that re-running the failed workflow does not make the problem go away... So the workflow still fails after 6 hours but without more information than before...

**Comment by ymzayek** [comment]
Yes I'm also seeing it more often. I guess it's time to dig. I can try a few things and maybe it'll be easier to debug remotely now that it's failing often

**Comment by Remi-Gau** [comment]
unless this is is a shy bug and it starts hiding when start paying attention to it. #HeisenBug

**Comment by ymzayek** [comment]
Hm so it might be actually related to this bug on their side https://github.com/plotly/Kaleido/issues/110 and https://github.com/plotly/Kaleido/issues/126 and the solution is to downgrade kaleido for the moment

**Comment by ymzayek** [comment]
And more recent https://github.com/plotly/Kaleido/issues/134

**Comment by Remi-Gau** [comment]
nice catch!

well we got nothing to lose trying to see if pinning the kaleido dependency to an older version makes things less flaky

**Comment by ymzayek** [comment]
One little complication, I'm not able to install kaleido==0.1.0.post1 on my Ubuntu 22.04 machine but apparently you can on windows (https://github.com/plotly/Kaleido/issues/134#issuecomment-1778023639). But it should be fine to pin the older version in the workflow just for windows. I'll work on it

**Comment by Remi-Gau** [comment]
one possibility to test it: have dependencies conditional for certain OS ?

https://stackoverflow.com/questions/69890200/how-to-configure-os-specific-dependencies-in-a-pyproject-toml-file-maturin

**Comment by Remi-Gau** [comment]
related PEP: https://peps.python.org/pep-0631/
