### ISSUE TITLE
[DOC] Replace examples' block splitter symbols with code cell syntax

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#3937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

Currently the examples in our example gallery use >= 20 `#` symbols to split sections. This can be replaced with either `#%%` or `# %%` with no effect on the rendering of built examples. These alternative syntax have the extra benefit of being recognized as code cells which in some IDEs allow users to run them like jupyter notebooks from the python file.

Reference: https://sphinx-gallery.github.io/stable/syntax.html#embed-rest-in-your-example-python-files

### List any pages that would be impacted.

This would need to be changed in all the examples in https://github.com/nilearn/nilearn/tree/main/examples

**Comment by Remi-Gau** [comment]
that would be nice!
