### ISSUE TITLE
make doc: Tell gen_rst.py which examples to build

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#396]
OK, at times you just want to test the build of a particular example script , see how it integrates with the doc pages, and then move on with your life. This is not possible at present ...

I've made a one-line patch to the `gen_rst.py` which offers this feature. The default behaviour is as before.

Use like so: 
`DEMO_REGEXP="plot_(?:haxby_simple|haxby_space_net|nilearn_101|poldrack_space_net)" make doc`

If this is useful for someone else, then I'll PR it.

**Comment by GaelVaroquaux** [comment]
This should probably go in sphinx_gallery, where it should be documented.

**Comment by salma1601** [comment]
I have the same problem, will be interested by that
+1 for PR

**Comment by GaelVaroquaux** [comment]
The PR should go to the sphinx-gallery project that will be integrated to
nilearn

**Comment by AlexandreAbraham** [comment]
Not a nilearn problem, so I close it.
