### ISSUE TITLE
Update ORCID of contributors

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3966]
Will most likely move this to another PR but here is a little script that should help us consolidate the ORCID of some of our contributors

```python
"""list authors with no orcid id

ping the ORCID API to see what match we get
and only print when there are less than 5 results 
"""
import pandas as pd
import requests
from rich import print

from citation_cff_maint import read_citation_cff

citation = read_citation_cff()

author_list = []
orcid_list = []

for author in citation["authors"]:
    if "orcid" not in author:
        print(f"{author['given-names']} {author['family-names']}")

        url = f"https://pub.orcid.org/v3.0/search/?q=family-name:{author['family-names']}+AND+given-names:{author['given-names']}"

        response = requests.get(
            url,
            headers={
                "Accept": "application/json",
            },
        )

        if response.status_code == 200:
            resp = response.json()
            if resp["num-found"] > 0 and resp["num-found"] < 6:
                author_list.append(
                    f"{author['given-names']} {author['family-names']}"
                )
                orcid = [x["orcid-identifier"]["uri"] for x in resp["result"]]
                orcid_list.append(", ".join(orcid))

df = pd.DataFrame({"author": author_list, "orcid": orcid_list})
df.to_csv("orcid.tsv", index=False, sep="\t")
```

author	orcid
Alexandre Savio	https://orcid.org/0000-0002-6608-6885, https://orcid.org/0000-0002-6067-6606
Anne-Sophie Kieslinger	https://orcid.org/0000-0001-9240-4077
Aswin Vijayan	https://orcid.org/0000-0002-0564-0774, https://orcid.org/0000-0002-5039-957X, https://orcid.org/0000-0002-1905-4194
Audrey Duran	https://orcid.org/0000-0002-1037-5098
Christian Gerloff	https://orcid.org/0000-0003-2718-2089, https://orcid.org/0000-0002-6484-8882
Connor Lane	https://orcid.org/0009-0009-0164-5672, https://orcid.org/0000-0002-6456-6308, https://orcid.org/0009-0003-6723-8013, https://orcid.org/0000-0002-5527-4768
Céline Delettre	https://orcid.org/0000-0001-6568-0295
Danilo Bzdok	https://orcid.org/0000-0003-3466-6620
Elvis Dohmatob	https://orcid.org/0000-0003-1421-6972
Jake Vogel	https://orcid.org/0000-0002-9936-6832
Jean Kossaifi	https://orcid.org/0000-0002-4445-3429
Jean-Rémi King	https://orcid.org/0000-0002-2121-170X, https://orcid.org/0000-0003-0061-0872, https://orcid.org/0000-0001-9572-8210, https://orcid.org/0000-0001-5759-7985
Jeremy Lefort-Besnard	https://orcid.org/0000-0002-8033-4953, https://orcid.org/0000-0001-7127-7558
Jona Sassenhagen	https://orcid.org/0000-0002-9935-8621
Joshua Teves	https://orcid.org/0000-0002-7767-0067
Konstantin Shmelkov	https://orcid.org/0000-0002-1555-1126
Loic Tetrel	https://orcid.org/0000-0002-1501-331X
Martin Wegrzyn	https://orcid.org/0000-0001-8025-4075
Mehdi Rahim	https://orcid.org/0000-0002-9570-4144
Michael Eickenberg	https://orcid.org/0000-0003-0656-4803
Michael Waskom	https://orcid.org/0000-0002-9817-6869
Moritz Boos	https://orcid.org/0000-0002-1219-4901
Natasha Clarke	https://orcid.org/0000-0002-6547-8609, https://orcid.org/0000-0003-2375-4510, https://orcid.org/0000-0003-2455-3614, https://orcid.org/0000-0002-4508-6851
Neelay Shah	https://orcid.org/0000-0001-7950-1956, https://orcid.org/0000-0003-3667-4114
Paul Bogdan	https://orcid.org/0000-0002-4362-6084, https://orcid.org/0000-0003-2118-0816
Philippe Gervais	https://orcid.org/0000-0002-2656-3931, https://orcid.org/0000-0003-2172-879X, https://orcid.org/0000-0003-1622-6066
Pierre Glaser	https://orcid.org/0000-0003-4146-973X
Rahul Brito	https://orcid.org/0000-0003-0343-0455
Raphael Meudec	https://orcid.org/0000-0001-9970-5745
Roberto Guidotti	https://orcid.org/0000-0001-6487-3968, https://orcid.org/0000-0002-0807-6005
Ronald Phlypo	https://orcid.org/0000-0003-4310-7994
Ryan Hammonds	https://orcid.org/0000-0002-5032-3241
Sachin Patalasingh	https://orcid.org/0000-0001-5627-2249
Vasco Diogo	https://orcid.org/0000-0002-7965-9013, https://orcid.org/0000-0001-5732-9390, https://orcid.org/0000-0003-1793-4443

_Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/issues/3956#issuecomment-1714858240_

**Comment by htwangtw** [comment]
It might be a nightmare to find mine through the API.
Here's me://orcid.org/0000-0003-4078-2038

**Comment by Remi-Gau** [comment]
> It might be a nightmare to find mine through the API. Here's me: https://orcid.org/0000-0003-4078-2038

I have not check who the winner was but some names defo gave very "generous" responses...
