### ISSUE TITLE
Add version tags to the doc repo

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3982]
For this repo:
https://github.com/nilearn/nilearn.github.io

https://github.com/nilearn/nilearn.github.io/tags

As far as I can tell this is the only way where we can find what the doc for a specific release looked like.

The lack of associated git tags makes the git history rewinding enterprise more precarious than an archeology trip with indiana jones.

Relates to #3979

**Comment by ymzayek** [comment]
Agreed. We can start with adding git tags to the docs in the release process (specifically this [make command](https://github.com/nilearn/nilearn/blob/29bc87e7c683c4e485cdbb5e6bf132ed5392e788/doc/Makefile#L167)) and retroactively tagging stable releases (at least up to when the new doc theme was released)

**Comment by Remi-Gau** [comment]
> Agreed. We can start with adding git tags to the docs in the release process (specifically this [make command](https://github.com/nilearn/nilearn/blob/29bc87e7c683c4e485cdbb5e6bf132ed5392e788/doc/Makefile#L167)) and retroactively tagging stable releases (at least up to when the new doc theme was released)

Yup that's what I had in mind too.

**Comment by Remi-Gau** [comment]
`git log --oneline | grep install` in that repo should help identify the releases

**Comment by Remi-Gau** [comment]
the build and deploy of the doc should include a tagging step.

**Comment by ymzayek** [comment]
@Remi-Gau let me know if you want me to take over the retroactive tagging. Then happy to open a PR to add tagging to the release process

**Comment by Remi-Gau** [comment]
I was planning to get to it before I took a week off but if you feel like going for it, be my guest

**Comment by Remi-Gau** [comment]
Seems I cannot transfer to the issue to this repo: [nilearn.github.io](https://github.com/nilearn/nilearn.github.io)

**Comment by Remi-Gau** [comment]
hum actually checking the list of tags on the doc repo, it seems that most releases are there: did not realize you had added them @ymzayek

**Comment by ymzayek** [comment]
I added some yesterday. I went to version 0.6.0. Not sure it's necessary but I can tag the rest today. At least major/minor releases. I've ignored releases candidates and alpha and beta version

**Comment by Remi-Gau** [comment]
honestly you have done more than enough: already makes it easy to find obvious landmarks in the history. many thanks. 🤗
