### ISSUE TITLE
atlas fetchers return inconsistency 

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#3983]
Minor API detail but I ran across a user who was confused by this.

Several fetchers seem to return dictionary-like object with a `map` key instead of `maps` like our doc suggest they should: https://nilearn.github.io/stable/development.html#additional-cases

May be a good thing to keep it consistent.

- fetch_atlas_craddock_2012
- fetch_atlas_smith_2009
- fetch_atlas_basc_multiscale_2015

**Comment by bthirion** [comment]
Sure, with adequate deprecation cycles...

**Comment by ymzayek** [comment]
Oh I definitely missed that subtlety in PR https://github.com/nilearn/nilearn/pull/3353/files :/
I think since it's a FutureWarning and we are still 2 cycles away, shouldn't we be able to modify the key and maybe modify the warning if it makes sense and change the catergory to DeprecationWarning?

**Comment by Remi-Gau** [comment]
> Oh I definitely missed that subtlety in PR https://github.com/nilearn/nilearn/pull/3353/files :/

No worries. I would never had noticed had I not had an annoyed user sitting in front of me.

> I think since it's a FutureWarning and we are still 2 cycles away, shouldn't we be able to modify the key and maybe modify the warning if it makes sense and change the catergory to DeprecationWarning?

I would say yes otherwise the warning is going to be incomprehensible for users.

**Comment by Remi-Gau** [comment]
> I remember this came up several times in different context - it was meddled with discussion about whether to add new atlases or not.

Good reminder

**Comment by ymzayek** [comment]
> I would say yes otherwise the warning is going to be incomprehensible for users.

Ok will open a PR
