### ISSUE TITLE
ConnectivityMeasure FutureWarning 'default strategy for standardize'

### ISSUE THREAD

**Issue by teanijarv** [nilearn/nilearn#3988]
Why do I get this warning? In the documentation there is a note that there should be standardize parameter in the ConnectivityMeasure class, but I can't define standardize='zscore_sample'. I have nilearn version 0.10.1.

```
from nilearn.connectome import ConnectivityMeasure
import numpy as np

np.random.seed(42)
time_series_data = np.random.rand(10, 120)

connectome_measure = ConnectivityMeasure(kind='correlation')
connectivity_matrix = connectome_measure.fit_transform([time_series_data])[0]
```

`[/Users/to8050an/anaconda3/envs/mri/lib/python3.11/site-packages/nilearn/connectome/connectivity_matrices.py:495](https://file+.vscode-resource.vscode-cdn.net/Users/to8050an/anaconda3/envs/mri/lib/python3.11/site-packages/nilearn/connectome/connectivity_matrices.py:495): FutureWarning: The default strategy for standardize is currently 'zscore' which incorrectly uses population std to calculate sample zscores. The new strategy 'zscore_sample' corrects this behavior by using the sample std. In release 0.13, the default strategy will be replaced by the new strategy and the 'zscore' option will be removed. Please use 'zscore_sample' instead.
  covariances_std = [`

**Comment by ymzayek** [comment]
@teanijarv yes this is buggy behavior introduced when we deprecated a standardize strategy. See https://github.com/nilearn/nilearn/issues/3825 for details. It has been addressed in this PR https://github.com/nilearn/nilearn/pull/3927 so in the next release you will be able to silence it by passing `standardize='zscore_sample'` to `ConnectivityMeasure`

**Comment by Remi-Gau** [comment]
@teanijarv 

you can pre-test it already by installing from the main branch on github if you want: 

```bash
pip install git+https://github.com/nilearn/nilearn.git
```

Let us know if the warnings are still there. 😉

**Comment by teanijarv** [comment]
Thanks for the information!
