### ISSUE TITLE
[ENH] Provide option to dim values below threshold rather than making them transparent

### ISSUE THREAD

**Issue by eurunuela** [nilearn/nilearn#3999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

Highlight results, don't hide them.

I don't think there is currently a way to highlight significant results while not hiding non-significant voxels. I believe `nilearn` could benefit from giving the option to show values below a given threshold in a translucent, rather than opaque way.

Issue based on the following paper: https://www.biorxiv.org/content/10.1101/2022.10.26.513929v1

A practical example👇

<img width="1130" alt="CleanShot 2023-09-21 at 12 39 59@2x" src="https://github.com/nilearn/nilearn/assets/13706448/aacad346-0d63-473a-a8c0-8ef3dffefeb3">

### Benefits to the change

Non-significant values would not be hidden but rather dimmed, especially those close to the threshold.

### Pseudocode for the new behavior, if applicable

```python
# insert your code below
plotting.plot_img_on_surf(corr_img,
                          views=['lateral', 'medial'],
                          hemispheres=['left', 'right'],
                          colorbar=True, cmap='RdYlBu_r',
                          vmax=0.2, symmetric_cbar=True,
                          bg_on_data=True, title='Correlation',
                          threshold=1.96, transparent=False)
```

**Comment by eurunuela** [comment]
It is! I guess I searched for the wrong keywords and missed it.

Thank you Remi for letting me know ☺️

**Comment by Remi-Gau** [comment]
@eurunuela 
started a PR to work on this: https://github.com/nilearn/nilearn/pull/5151
