### ISSUE TITLE
[DOC] PPI Example in Nilearn

### ISSUE THREAD

**Issue by alpinho** [nilearn/nilearn#4004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

I think it would be very useful to create an Example of PPI (Psychophysiological Interaction) analysis in Nilearn. Maybe, in the same spirit of [this tutorial](https://dartbrains.org/content/Connectivity.html).

**Comment by Remi-Gau** [comment]
@alpinho 

Definitely not opposed to it.

Ideally it would have to be based on a dataset we already use for another example and also be a PPI that "makes sense" meaning that could represent what someone may do "in real life".

Any suggestions?
