### ISSUE TITLE
Explore system paths in fetch_harvard_oxford

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#401]
In `fetch_harvard_oxford`, we look for a path in `FSL_DIR`. We should also look into defautl fixed paths for all systems (eg /usr/share/fsl/data).

**Comment by banilo** [comment]
Have we not addressed this issue in
https://github.com/nilearn/nilearn/blame/master/nilearn/datasets.py#L1569
?

**Comment by AlexandreAbraham** [comment]
No because FSL_DIR is not set by default on most setup. Thus we should explore some hardcoded absolute paths.

**Comment by AlexandreAbraham** [comment]
Closing in favor of #486.
