### ISSUE TITLE
Try using Tox to simplify testing with different environments

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4019]
- could simplify the pyproject.toml 
- could simplify CI workflows by just calling the right tox recipe rather than setting environment variables and calling some bash script
- could move some of the recipes from the makefile to the tox.ini

**Comment by ymzayek** [comment]
I haven't used it myself but would be nice to see how that set up looks like.

**Comment by Remi-Gau** [comment]
same here but this seems like the textbook example of where tox is useful

**Comment by Remi-Gau** [comment]
>  I think that's a good idea. IIRC the part where it gets a bit tricky is collecting/merging the coverage results (btw I don't see them in the PR)

good catch: I think the coverage report are not generated so codecov does not return anything, I must have missed something

> * `install.sh` installs nilearn with `-e`, so it just creates symlink -- if the packaging was broken we wouldn't catch it

I think that the way I have configured the env in tox it would not be in editable mode

>     * pytest is invoked with `python -m pytest` instead of `pytest`. this adds the cwd to the sys.PATH, and it happens to contain the `nilearn` source directory which is at the root of the repo. as a result despite the `--pyargs` we test the source package rather than the installed one AFAICT

that would need to be changed indeed
