### ISSUE TITLE
cross_val_score with imgs

### ISSUE THREAD

**Issue by schwarty** [nilearn/nilearn#402]
`cross_val_score` does not work with images.  We would need that to support classifiers that use a `NiftiMasker` internally such as the future `Decoder` and `SpaceNet`. Possible solutions include creating  a slicable Niimg object, that could be passed as is to `cross_val_score`.

**Comment by KamalakerDadi** [comment]
I believe this can be fixed with PR #2000

**Comment by thomasbazeille** [comment]
The current tradeoff for all high level objects is to take niimg and masker (or masking parameters) as inputs, use _check_embedded_masker() and mask the images before proceeding. 

As we usually operate on Niimg before feeding them to cross-val-score at least with masking, this seems a sound way to do this.

Maybe these first steps until masking could be all refactorized in a one-liner but this is a different issue.


Can be closed I think
