### ISSUE TITLE
use  MNI152_T1_2009c+tlrc template with nilearn

### ISSUE THREAD

**Issue by SaqibMamoon** [nilearn/nilearn#4021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

Dear Team, 

I would like to ask to include the functionality to use [MNI152_T1_2009c+tlrc](https://afni.nimh.nih.gov/pub/dist/atlases/MNI_HCP/MNI_Glasser_HCP_2021_v1.0a/MNI152_T1_2009c+tlrc.HEAD) template for Glasser atlas conversion from fsaverage space to MN152 volumetric space, as there have been several discussions and articles that some earlier versions had poor alignment with any MNI space.

### Benefits to the change

It would be quite easy to use the Glasser Atlas for volumetric analysis and the right fit it into the ABIDE-I rsfMRI dataset. Now i my knowledge we can only use this with AFNI not python.

### Pseudocode for the new behavior, if applicable

```python
# insert your code below

```

**Comment by bthirion** [comment]
Thank you for posting ! 
I do not completely understand your issue ; Template images included with Nilearn are simply used for display , there is no specific computation  related to those. What would the addition of the volumetric template add to the library ? Sorry if I misunderstood.

**Comment by ymzayek** [comment]
Closing this as out of scope
