### ISSUE TITLE
[BUG] Interpolation of high motion volumes at the beginning/end scan

### ISSUE THREAD

**Issue by jhuguetn** [nilearn/nilearn#4024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

For example one of the following:
- Linux Ubuntu 22.04

### Python version

- [ ] 3.11
- [ ] 3.10
- [X] 3.9
- [ ] 3.8
- [ ] 3.7

### nilearn version

0.10.2

### Expected behavior

At scrubbing  (censoring high-motion volumes) step, the volumes at the beginning/end of the scan -if labelled as high-motion outliers- shouldn't be interpolated (*extrapolated*) but discarded before filtering.

### Current behavior & error messages

Currently, the function [_interpolate_volumes()](https://github.com/nilearn/nilearn/blob/b1fa2e0b9161a5055a900b708aed38aaab15866f/nilearn/signal.py#L779) uses a CubicSpline (scipy class) with `extrapolate` feature enabled by default. Asking the interpolation method to predict values outside the range of data available is -in my opinion- not a very good idea. The results of the interpolation, and further scrubbing, are not reliable. 

I am happy to open a PR for this with a fix proposal if there's consensus.

Example of signal interpolation as is and the disabling the `extrapolate` flag,
![image](https://github.com/nilearn/nilearn/assets/6368825/dd313474-fe42-456e-9f65-9b082e62cc7d)
![image](https://github.com/nilearn/nilearn/assets/6368825/019c4739-ae1c-400e-825a-497160863af8)
![image](https://github.com/nilearn/nilearn/assets/6368825/8606e533-d645-4200-be4c-4df55673b147)  

Thanks,
Jordi

### Steps and code to reproduce bug

```python
import numpy as np
from nilearn import signal
import nibabel as nib

data = nib.load("/tmp/xxx_desc-preproc_bold.nii.gz'').get_data()
volumes = np.transpose(data, (3, 0, 1, 2))

# dummy list of censored high-motion volumes
sample_mask = np.zeros(data_reshaped.shape[0], dtype=bool)
sample_mask[0:50] = 1
sample_mask[-50:] = 1
sample_mask = ~sample_mask

volumes = signal._interpolate_volumes(volumes, sample_mask, t_r=1.6)
```

**Comment by ymzayek** [comment]
@jhuguetn thanks for reporting! Tagging @htwangtw for input on this one

**Comment by htwangtw** [comment]
Thanks for opening the issue @jhuguetn!

> Asking the interpolation method to predict values outside the range of data available is -in my opinion- not a very good idea.

I agree and thanks for picking up on this!

If I understand the issue correctly, this change will only apply to when butterworth filter and scrubbing is applied? Also make sure the confounds reflects that you discarded the head and tail of the signal. 


Please open a PR to address this - I do not use butterworth as my preferred filtering methods so it would be great to have you working on this issue. I am happy to assist during code review :)

**Comment by jhuguetn** [comment]
Hi @htwangtw and sorry for the late reply. 

> If I understand the issue correctly, this change will only apply to when butterworth filter and scrubbing is applied?
Correct, see [here](https://github.com/nilearn/nilearn/blob/main/nilearn/signal.py#L819-L822).

Sure, no problem. I will now open a PR with a proposal then. Basically what I have in mind is disabling the data extrapolation by default but exposing the parameter just in case someone wants to change it to True or use a `periodic` extrapolation.
