### ISSUE TITLE
[ENH] Request for Inclusion of "KONG Networks" Option in Nilearn Function "nilearn.datasets.fetch_atlas_schaefer_2018()""

### ISSUE THREAD

**Issue by PuneetDheer** [nilearn/nilearn#4074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

I was hoping to find the KONG 7 or 17 Network atlas, as referenced in the following source:

[VERSION 3. Schaefer2018_<#ROIs>Parcels_Kong2022_17Networks_order]
https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal.

However, it seems that this atlas is not available through the nilearn function, as indicated here: https://nilearn.github.io/dev/modules/generated/nilearn.datasets.fetch_atlas_schaefer_2018.html#nilearn.datasets.fetch_atlas_schaefer_2018.

The current functionality only allows for the use of the "yeo_networks" parameter.

I kindly request that you consider adding the KONG 7 or 17 network option, which could be labeled as "kong_networks," similar to the existing "yeo_networks" parameter. 

Your consideration in this matter would be greatly appreciated.

### Benefits to the change

The inclusion of the "kong_networks" option would enhance the utility of the network atlas by providing access to a broader range of networks, notably, the auditory and language networks/parcels, which are not currently available through the "yeo_networks" parameter.

For reference, you can view the language and auditory parcels here: https://github.com/ThomasYeoLab/CBIG/blob/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/MNI/freeview_lut/Schaefer2018_1000Parcels_Kong2022_17Networks_order.txt. 

Your consideration of this valuable addition is sincerely appreciated.

### Pseudocode for the new behavior, if applicable

```python
# insert your code below

```

**Comment by htwangtw** [comment]
This is a common type of request and I would redirect you to this reply for another thread:

https://github.com/nilearn/nilearn/issues/4039#issuecomment-1752129186

**Comment by bthirion** [comment]
Thx for the suggestion.
We already have Schaefer atlas available. https://nilearn.github.io/stable/modules/generated/nilearn.datasets.fetch_atlas_schaefer_2018.html
Isn't it enough ?
Best,

**Comment by PuneetDheer** [comment]
Duplicate of #

**Comment by PuneetDheer** [comment]
Hi bthirion

You are absolutely correct in noting that the "Schaefer atlas" is indeed available. However, it appears that there is no parameter option to select the KONG 7 or 17 network within this atlas. Instead, the atlas only allows the use of the "yeo_networks" parameter.

For your specific needs, I would like to direct your attention to an alternative option: **[VERSION 3. Schaefer2018_<#ROIs>Parcels_Kong2022_17Networks_order](https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal#version-3-schaefer2018_roisparcels_kong2022_17networks_order)**. This version of the Schaefer 2018 atlas provides the capability to access the "Language" and "Auditory" parcels, which are not available when using the "yeo_networks" parameter with the Schaefer atlas. You can find further information on this version on the provided GitHub link.

Additionally, I would like to draw your attention to the image link [here](https://github.com/ThomasYeoLab/CBIG/blob/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/readme_figures/Schaefer2018_400parcel_parcellation_Kong2022_17_network_fslr32k.jpg), which displays the language and auditory parcels in the Schaefer2018_<#ROIs>Parcels_Kong2022_17Networks_order.

This Kong network option indeed offers access to the specific "Language" and "Auditory" parcels that are not available when using the "yeo_networks" parameter with the Schaefer atlas. For your convenience, you can find more details in the links provided.

Best,

**Comment by PuneetDheer** [comment]
Could you please look into it?

**Comment by bthirion** [comment]
We will discuss this in an upcoming coredev meeting. Best,

**Comment by Remi-Gau** [comment]
Was discussed at the last core dev meeting and decided that this is out of scope for Nilearn:

We have updated the documentation to make our policy regarding adding new atlases more obvious (note this is not a change in policy just trying to make it easier to point to) and also pointing to other projects that may accept atlas contribution: 

https://nilearn.github.io/dev/development.html#adding-atlases-and-datasets
