### ISSUE TITLE
[ENH] integrate `load_confounds` into `first_level_from_bids`

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

- Relates to https://github.com/nilearn/nilearn/issues/2425

Currently one can point `first_level_from_bids` to a bids dataset and get
- model object
- images paths
- events files content
- confounds files content

The whole of the confounds are loaded, it is left to the user to confound wrangling before they can fit their model.

Alternatively they can use the load_confounds function and pass it images paths to load the confounds with one of the strategy (scrubbing, motion...) it accepts.

It may be easier to pass directly some extra argument to `first_level_from_bids` and have it take care of call load_confounds returning only the subset of confounds requested.

### Benefits to the change

make it simpler to load a given set of confounds from a BIDS dataset when running a GLM

### Pseudocode for the new behavior, if applicable

currently

```python
from nilearn.glm.first_level import first_level_from_bids
from nilearn.interfaces.fmriprep import load_confounds

task_label = "stopsignal"
space_label = "MNI152NLin2009cAsym"
data_dir = "/home/bob/data/stop_signal_fmri/data"
derivatives_folder = "derivatives/fmriprep"

(
    models,
    models_run_imgs,
    models_events,
    _,
) = first_level_from_bids(
    data_dir,
    task_label,
    space_label,
    smoothing_fwhm=5.0,
    derivatives_folder=derivatives_folder,
)

# the following would actually have to be done for every subject
models_confounds = load_confounds(
    models_run_imgs[0],
    strategy=("motion", "wm_csf"),
    motion="full",
    scrub=1,
    fd_threshold=0.2,
    wm_csf="basic")
```

what I suggest

```python
from nilearn.glm.first_level import first_level_from_bids

task_label = "stopsignal"
space_label = "MNI152NLin2009cAsym"
data_dir = "/home/bob/data/stop_signal_fmri/data"
derivatives_folder = "derivatives/fmriprep"

(
    models,
    models_run_imgs,
    models_events,
    models_confounds,
) = first_level_from_bids(
    data_dir,
    task_label,
    space_label,
    smoothing_fwhm=5.0,
    derivatives_folder=derivatives_folder,
    strategy=("motion", "wm_csf"),
    motion="full",
    scrub=1,
    fd_threshold=0.2,
    wm_csf="basic")
```

**Comment by Remi-Gau** [comment]
@htwangtw any thought?

**Comment by bthirion** [comment]
This looks great. How much work does it represent ?

**Comment by ymzayek** [comment]
I would just be careful that the number of parameters of `first_level_from_bids` don't explode. But if the benefits outweigh this one downside I see then seems like a good idea.

**Comment by Remi-Gau** [comment]
Was thinking of using **kwargs.
Any policy against that?

**Comment by htwangtw** [comment]
I second @ymzayek's concern and would be in favour of using `**kwargs`

**Comment by Remi-Gau** [comment]
> How much work does it represent ?

Given how modular the code is, I would expect it would be relatively easy. #FamousLastWords

**Comment by bthirion** [comment]
I would be cautious not to hide the API behind kwargs. How shall a user know what kwargs are allowed ?

**Comment by Remi-Gau** [comment]
I would explicitly mention it in the doc.
If we do not do that we are going to duplicate both arguments and doc strings in 2 places.

**Comment by htwangtw** [comment]
Can we consider to adopt the way `clean_img` handles keyword arguments?
https://nilearn.github.io/stable/modules/generated/nilearn.image.clean_img.html
