### ISSUE TITLE
[DOC] experimental-plot-surface-image-and-maskers example does not render well

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#4098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

The decoding maps proposed at the end of the example are ugly and not informative. We probably need to tweak viz parameters.
https://nilearn.github.io/stable/auto_examples/08_experimental/plot_surface_image_and_maskers.html#sphx-glr-auto-examples-08-experimental-plot-surface-image-and-maskers-py

### List any pages that would be impacted.

https://nilearn.github.io/stable/auto_examples/08_experimental/plot_surface_image_and_maskers.html

**Comment by Remi-Gau** [comment]
not yet fixed
