### ISSUE TITLE
[DOC] Failing doc build on main due to examples failing

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#4106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

Examples:
plot_3d_and_4d_niimg
plot_neurovault_meta_analysis
plot_ica_neurovault
plot_extract_rois_statistical_maps

are failing the doc build on main. Looking into it

**Comment by Remi-Gau** [comment]
does not seem related to a PR merge: https://github.com/nilearn/nilearn/actions/workflows/build-docs.yml?query=branch%3Amain

**Comment by ymzayek** [comment]
Looks like Neurovault is down

**Comment by ymzayek** [comment]
Seems to be resolved
