### ISSUE TITLE
[DOC] GLM decoding does not specify what is being classified.

### ISSUE THREAD

**Issue by TamerGezici** [nilearn/nilearn#4109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

In [this ](https://nilearn.github.io/stable/auto_examples/02_decoding/plot_haxby_glm_decoding.html#sphx-glr-auto-examples-02-decoding-plot-haxby-glm-decoding-py)tutorial, at the bottom an accuracy value is written.

But it doesn't specify what is being classified. When I look at the labels, all conditions and all z-maps are given for classification. Does this mean this classification shows patterns of activity that are decoded for all these trial types? Thank you.

**Comment by bthirion** [comment]
You're right. IIRC this is one-vs-all classification. Can you open a PR to fix that ?
est,

**Comment by TamerGezici** [comment]
> You're right. IIRC this is one-vs-all classification. Can you open a PR to fix that ? est,

I am sorry, I can't find the link to this DOC.

The edit link at the documentation ends up in a dead link.

Searching the repository for terms within the page also returned nothing.

**Comment by bthirion** [comment]
The function to be changed is that one: https://github.com/nilearn/nilearn/blob/main/examples/02_decoding/plot_haxby_glm_decoding.py
Let us know if you can do it. We can discuss this at some future Nilearn open hour.

**Comment by TamerGezici** [comment]
> The function to be changed is that one: https://github.com/nilearn/nilearn/blob/main/examples/02_decoding/plot_haxby_glm_decoding.py Let us know if you can do it. We can discuss this at some future Nilearn open hour.

I should be able to do it. I will edit it based on my knowledge. Since it's a PR, if I do a mistake you can give me feedback. Or, I can try joining on the next office hour on Friday.

Thanks.

**Comment by bthirion** [comment]
It's great if you can open a PR. Note that the office hours are non Wednesday 4pm UTC.

**Comment by TamerGezici** [comment]
> It's great if you can open a PR. Note that the office hours are non Wednesday 4pm UTC.

Ah okay, thanks for the heads up.

**Comment by Remi-Gau** [comment]
> The edit link at the documentation ends up in a dead link.

- Yup that's a known issue: https://github.com/nilearn/nilearn/issues/3977

**Comment by ymzayek** [comment]
@TamerGezici if you haven't seen this already: https://nilearn.github.io/stable/development.html#how-to-contribute-to-nilearn, going through it might help you get started with the PR. And we will help you through the PR!

**Comment by TamerGezici** [comment]
I made a PR, but I was not sure conceptually what to write.
