### ISSUE TITLE
[BUG] GLM report ignore `threshold` parameter

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#4118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

For example one of the following:
- Linux Ubuntu 22.04
- Mac OS Version 12 "monterey"
- Windows 11

### Python version

- [ ] 3.12
- [X] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

Dev version

### Expected behavior

Report should change depending on the provided `threshold` parameter

### Current behavior & error messages

atm the geenrated report does not change when `threshold is changed`

### Steps and code to reproduce bug

```python
# Paste your code here
import numpy as np
import pandas as pd
from nilearn.datasets import func
from nilearn.image import mean_img
from nilearn.glm.first_level import FirstLevelModel
from os import getcwd, mkdir, path
from nilearn.reporting import make_glm_report

data = func.fetch_fiac_first_level()
fmri_img = [data['func1'], data['func2']]
mean_img_ = mean_img(fmri_img[0])
design_files = [data['design_matrix1'], data['design_matrix2']]
design_matrices = [pd.DataFrame(np.load(df)['X']) for df in design_files]

fmri_glm = FirstLevelModel(mask_img=data['mask'], minimize_memory=True)
fmri_glm = fmri_glm.fit(fmri_img, design_matrices=design_matrices)
n_columns = design_matrices[0].shape[1]
contrasts = {'Effects_of_interest': np.eye(n_columns)[:5]}
report1 = make_glm_report(fmri_glm,
                         contrasts,
                         bg_img=mean_img_,
                         )
report1.save_as_html('report1.html')
report2 = make_glm_report(fmri_glm,
                          contrasts,
                          bg_img=mean_img_,
                          threshold=2.
                          )
report2.save_as_html('report2.html')


```

**Comment by ymzayek** [comment]
@bthirion the problem comes from the way `threshold` is implemented in relation to `height_control`. The docstring for `threshold` reads:
```python
"""
    threshold : float, default=3.09
        Cluster forming threshold in same scale as `stat_img` (either a
        t-scale or z-scale value). Used only if height_control is None.
"""
```

And indeed if I set `height_control` to None (default is 'fpr') then the thresholding works.
Is this intended behavior?

**Comment by bthirion** [comment]
He, he, I should read the docs. Closing for now.
