### ISSUE TITLE
[BUG] `nilearn.plotting.plot_sur_stat_map` does not display the provided title

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#4119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

For example one of the following:
- Linux Ubuntu 22.04
- Mac OS Version 12 "monterey"
- Windows 11

### Python version

- [ ] 3.12
- [X] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

Dev version

### Expected behavior

Image itle should be displayed on the image

### Current behavior & error messages

It is actually missing.

### Steps and code to reproduce bug

This is visible in the documentation
https://nilearn.github.io/stable/auto_examples/01_plotting/plot_3d_map_to_surface_projection.html#sphx-glr-auto-examples-01-plotting-plot-3d-map-to-surface-projection-py

**Comment by ymzayek** [comment]
Seems to be the case for all examples with `plot_surf_stat_map` and probably anything that calls `plot_surf` as I also saw it with `plot_surf_roi`. Locally running the notebook displays the title so maybe it has to do with the interplay of sphinx and mpl
