### ISSUE TITLE
Adding cyclic analysis to nilearn.connectome.ConnectivityMeasure

### ISSUE THREAD

**Issue by WMDA** [nilearn/nilearn#4124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

Hi everyone,

I am working on implementing cyclic analysis in resting state fMRI and thought it would be really good to add this to nilearn. Cyclic Analysis is described in more detail here https://www.biorxiv.org/content/10.1101/2021.05.16.444387v2 and here https://ieeexplore.ieee.org/document/7798498, but basically it derives the pairwise temporal ordering of time series in the form of a lead lag matrix. The lead lag matrix is similar to other connectivity matrices, with values indicating strength of pairwise relationship and sign indicating direction of relationship.

It has been used in machine learning research with resting state fMRI to classify tinnitus patients successfully: (https://www.frontiersin.org/articles/10.3389/fncom.2019.00094/full 
https://direct.mit.edu/netn/article/3/1/67/2193/Dissociating-tinnitus-patients-from-healthy) and our group is applying it to classifying anorexia nervosa.

I propose adding to nilearn.connectome.ConnectivityMeasure the ability to do cyclic analysis, so that this class can produce the lead lag matrix from a given set of time series. 

Is this something that would be of interest to the nilearn community? 

### Benefits to the change

This would allow nilearn to do cyclic analysis which is a really interesting approach and is being used more and more in machine learning using rsfMRI. 

### Pseudocode for the new behavior, if applicable

```
class ConnectivityMeasure(BaseEstimator, TransformerMixin):
    ........
            elif self.kind == "cyclic":
                connectivities = [cylic_connectivity(x) for x in X]
            else:
                allowed_kinds = (
                    "correlation",
                    "partial correlation",
                    "tangent",
                    "covariance",
                    "precision",
                    "cyclic"
                )
```

```
def cylic_connectivity(time_series):
    """ Returns the lead lag matrix from a given time series

    Parameters
    ----------
    time_series : 2D numpy.ndarray
        The raw time series 

    Returns
    -------
    Lead lag matrix : 2D numpy.ndarray
        Lead Lag matrix.

    """
    # Do first order differencing in numpy 
    diff = np.insert(np.diff(time_series, axis=0), 0, 0, axis=0)
    A = time_series[:-1].T @ diff[1:]
    return np.array(0.5 * (A - A.T))
```

**Comment by bthirion** [comment]
Thx for sharing. We need to have a discussion with coredevs, since adding new estimators increases the long-term maintenance burden for the project, so that we need to weigh the cost/benefit tradeoff.

**Comment by WMDA** [comment]
Hi was wondering if there have been any discussions on this?

**Comment by Remi-Gau** [comment]
Sorry we've been swamped with everyday maintenance.

Adding this to the agenda of our next meeting.

**Comment by bthirion** [comment]
We had a discussion about it, and we are not sure that the benefit is large enough, in view of the additional maintenance cost. For this we would have to wait in the long term if the community adopts the tool. Meanwhile, it is of course possible for you to implement and share a Nilearn-compatible estimator.

**Comment by bthirion** [comment]
Closing for now.
