### ISSUE TITLE
Testing against numpy 2.0 

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#4129]
Suggestion to add a test in the CI to test against numpy 2.0 dev versions using their nightly releases at https://anaconda.org/scientific-python-nightly-wheels/numpy. 

Also see https://github.com/numpy/numpy/issues/24300

**Comment by bthirion** [comment]
Indeed ! 
Do you want to start this ?

**Comment by ymzayek** [comment]
Yes I'll set it up
