### ISSUE TITLE
Capitalisation of Ni{l,L}earn

### ISSUE THREAD

**Issue by lesteve** [nilearn/nilearn#413]
Looking at the docs, there is either Ni**l**earn (small l) or Ni**L**earn (capital l). Any strong preference between the two?

**Comment by bthirion** [comment]
Nilearn is easier to write. 

B

**Comment by agramfort** [comment]
nilearn all in small caps :)

**Comment by AlexandreAbraham** [comment]
I prefer nilearn too.

On Fri, Feb 6, 2015 at 9:46 AM, Alexandre Gramfort <notifications@github.com

**Comment by GaelVaroquaux** [comment]
Me too

**Comment by lesteve** [comment]
OK, nilearn it is then. I'll stick with capitals only at the start of a sentence.
