### ISSUE TITLE
[DOC] Don't set get_tmaps=True if tmaps aren't used

### ISSUE THREAD

**Issue by crossmanith** [nilearn/nilearn#4135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

Examples [Second-level fMRI model: true positive proportion in clusters - Nilearn](https://nilearn.github.io/dev/auto_examples/05_glm_second_level/plot_proportion_activated_voxels.html#sphx-glr-auto-examples-05-glm-second-level-plot-proportion-activated-voxels-py) and [Second-level fMRI model: two-sample test, unpaired and paired - Nilearn](https://nilearn.github.io/dev/auto_examples/05_glm_second_level/plot_second_level_two_sample_test.html#sphx-glr-auto-examples-05-glm-second-level-plot-second-level-two-sample-test-py) use `fetch_localizer_contrasts()` with `get_tmaps=True` but tmaps aren't used in the examples. So the default `get_tmaps=False` is fine and should be used.

### List any pages that would be impacted.

[Second-level fMRI model: true positive proportion in clusters - Nilearn](https://nilearn.github.io/dev/auto_examples/05_glm_second_level/plot_proportion_activated_voxels.html#sphx-glr-auto-examples-05-glm-second-level-plot-proportion-activated-voxels-py) 
[Second-level fMRI model: two-sample test, unpaired and paired - Nilearn](https://nilearn.github.io/dev/auto_examples/05_glm_second_level/plot_second_level_two_sample_test.html#sphx-glr-auto-examples-05-glm-second-level-plot-second-level-two-sample-test-py)

**Comment by ymzayek** [comment]
@crossmanith thanks for pointing this out. Would you open a pull request to improve the examples?

**Comment by crossmanith** [comment]
I've started a pull request, but only with one example modified. I'm struggling to amend the commit with the change to the second example. Any hints?
