### ISSUE TITLE
Relocate functions from datasets.utils

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4139]
Suggestion to do in a separate PR:
What do you think about deprecating this file and relocating these two functions? `load_sample_motor_activation_image` could go under `func.py`; not so sure yet about `get_data_dirs`. Or alternatively renaming `utils.py`
Not sure if it's worth it but something to think about if any confusion arises from having `_utils.py` and `utils.py`

_Originally posted by @ymzayek in https://github.com/nilearn/nilearn/pull/4086#discussion_r1384846240_

**Comment by bthirion** [comment]
move all function in `utils.py` into `_utils.py` ?

**Comment by Remi-Gau** [comment]
Pretty much except for the public functions that we would put into another module with some "redirecting" with a deprecation warning.
