### ISSUE TITLE
[DOC] improve surface related documentation 

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

Before I forget again...

- add surface related terms to the glossary
  - mesh
  - vertex
  - faces (triangles)
  - coordinates
  - geometry

When looking up during the last mini hackathon I found that the following would good targets: mesh, faces, vertex. They fairly regularly in the code base and the documentation to justify new entries.

- I was also looking for potential sources we could point to to describe how surface data is usually structured. I have not had a lot of success. Anyone knows any? If not it may be useful to have a page describing this in the user guide, no? Also basing this on my memory of the feeling that, when starting with MRI, volumetric data was easy to grok but surface data much less so.

### List any pages that would be impacted.

- glossary
- User guide?

**Comment by ymzayek** [comment]
Probably this section https://nilearn.github.io/stable/manipulating_images/index.html can be reworked a bit to mention SurfaceImage and SurfaceMasker and working with surface data within the context of nilearn

**Comment by Remi-Gau** [comment]
Agreed: I was thinking of adding some things somewhere in this page.

https://nilearn.github.io/stable/manipulating_images/input_output.html#understanding-neuroimaging-data
