### ISSUE TITLE
Feedback Request: Experimental Surface API in Nilearn 0.10.2

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#4158]
With the nilearn coredev team, we have recently released a surface API under an [experimental module](https://nilearn.github.io/stable/modules/experimental.html) and since you have been involved in working with developing surface support in nilearn we are interested in getting your feedback on this. It was released in version 0.10.2 and can already be tested minimally (it is not yet integrated into the stable API and so will not work in the context of the other modules). We have an example showcasing what can be done here: https://nilearn.github.io/stable/auto_examples/08_experimental/plot_surface_image_and_maskers.html#sphx-glr-auto-examples-08-experimental-plot-surface-image-and-maskers-py.

Tagging people involved in development and/ or discussion of surface support in nilearn in the past:
@sahahn 
@effigies 
@jyeatman
@smeisler 

Please feel free to tag more people who are working with surface analysis!

**Comment by emdupre** [comment]
cc @juhuntenburg !

**Comment by Remi-Gau** [comment]
I am going to close this as I think we are close enough to the being done with this.
