### ISSUE TITLE
[ENH] `test_clean_psc` includes a useless line

### ISSUE THREAD

**Issue by htwangtw** [nilearn/nilearn#4175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

https://github.com/nilearn/nilearn/blob/092c339ce1bedc435ede160bc6f9160551ab4438/nilearn/tests/test_signal.py#L890-L891

Some useless lines in the code - the last person who edited the test was me, but after looking into gitblame, it seems it has always been there, and the usage was unclear.

Probably just want to remove it.

### Benefits to the change

Prevent confusion.

### Pseudocode for the new behavior, if applicable

```python
# insert your code below

```

**Comment by bthirion** [comment]
Indeed, I don't understand what this tests.

**Comment by paul-reiners** [comment]
I want to work on this.  In fact, I already have the fix ready to push.

I get an error when I try to push (I don't know if that's to be expected):

```
(venv) bash-4.2$ git push --set-upstream origin feature-4175
ERROR: Permission to nilearn/nilearn.git denied to paul-reiners.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Remi-Gau** [comment]
@paul-reiners 

It looks like you did not fork the repo before pushing on a new branch.

Follow the set up instructions, to fix this.
https://nilearn.github.io/stable/development.html#setting-up-your-environment

You may have to:

- fork the repo

- rename the nilearn remote as "upstream"

```bash
git remote rename origin upstream
git remote remove origin
```

- add your fork as remote

```
git remote add upstream https://github.com/paul-reiners/nilearn
```

- push your branch to that remote

```
git push --set-upstream origin feature-4175
```

- open a pull request

**Comment by paul-reiners** [comment]
Thanks @Remi-Gau .  I am working on password problems.  I will do what you suggest later this evening.

**Comment by Remi-Gau** [comment]
No rush. Don't hesitate to ping us her or on our discord if you run into problems.

**Comment by paul-reiners** [comment]
@Remi-Gau I'm not sure what I'm doing wrong below.  Any assistance would be welcome.

```
(venv) (base) paulreiners@Pauls-MBP nilearn % git remote rename origin upstream
Renaming remote references: 100% (3/3), done.
(venv) (base) paulreiners@Pauls-MBP nilearn % git remote remove origin
error: No such remote: 'origin'
(venv) (base) paulreiners@Pauls-MBP nilearn % git remote add upstream https://github.com/paul-reiners/nilearn
error: remote upstream already exists.
(venv) (base) paulreiners@Pauls-MBP nilearn % git remote remove upstream                                     
(venv) (base) paulreiners@Pauls-MBP nilearn % git remote add upstream https://github.com/paul-reiners/nilearn
(venv) (base) paulreiners@Pauls-MBP nilearn % git push --set-upstream origin feature-4175
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Remi-Gau** [comment]
oops totally may fault (but looks like you still managed to open a PR 🚀 !


- add your fork as remote:

```
git remote add origin https://github.com/paul-reiners/nilearn
```

and not like above

```
git remote add upstream https://github.com/paul-reiners/nilearn
```

to make sure things are set up properly use `git remote -v`:

```
git remote -v 
origin  https://github.com/Remi-Gau/nilearn.git (fetch)
origin  https://github.com/Remi-Gau/nilearn.git (push)
upstream        https://github.com/nilearn/nilearn.git (fetch)
upstream        https://github.com/nilearn/nilearn.git (push)
```

- `origin` should "point" to your fork of nilearn
- `upstream` should "point" to official nilearn repository

> [!NOTE] 
> - The names `origin` and `upstream` are arbitrary and used mostly as conventions.
> - It is convenient to keep the `upstream` fork, to sync back your local code with what's on the nilearn code base
> - Depending on what Git tool you use, the `upstream` remote could be set up automatically when you `git clone` a fork, saving you all the headaches you had to go through to rename remotes correctly.

**Comment by paul-reiners** [comment]
I added the release note.  Is everything okay now?
