### ISSUE TITLE
`save_glm_to_bids` should save the output of each participant in a different folder

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4176]
Currently everything is left in flat structure.

See the example:
https://nilearn.github.io/stable/auto_examples/04_glm_first_level/plot_bids_features.html#saving-model-outputs-to-disk

```
derivatives
└── nilearn_glm
    ├── dataset_description.json
    ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_design.svg
    ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_stat-effect_statmap.nii.gz
    ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_stat-p_statmap.nii.gz
    ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_stat-t_statmap.nii.gz
    ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_stat-variance_statmap.nii.gz
    ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_stat-z_statmap.nii.gz
    ├── sub-10159_task-stopsignal_design.svg
    ├── sub-10159_task-stopsignal_design.tsv
    ├── sub-10159_task-stopsignal_stat-errorts_statmap.nii.gz
    ├── sub-10159_task-stopsignal_statmap.json
    └── sub-10159_task-stopsignal_stat-rSquare_statmap.nii.gz
```

Though it can be hard to decide how to structure several GLMs in a dataset (see this point in BIDS extension https://docs.google.com/document/d/1KHzp-yk8KXvkUIhtN71WU0m4P4kKT9C1yvI-i9_kNeY/edit?disco=AAAAZYC1rtw)
it should be fairly safe to assume that the date of each subject can go in a subfolder

**Comment by bthirion** [comment]
Not fully sure I undertsand: in the above example, there is only one glm fitted, right ? Do you mean that we should systematically have a "glm folder" in the output path ?

**Comment by Remi-Gau** [comment]
Let me give you examples. That may be clearer than my midnight rambling.

**Comment by Remi-Gau** [comment]
IMHO the bare minimum would be to have at least a subject level folder:

```
derivatives
└── nilearn_glm
    ├── dataset_description.json
    └── sub-10159
        ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_design.svg
        ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_stat-effect_statmap.nii.gz
        ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_stat-p_statmap.nii.gz
        ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_stat-t_statmap.nii.gz
        ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_stat-variance_statmap.nii.gz
        ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_stat-z_statmap.nii.gz
        ├── sub-10159_task-stopsignal_design.svg
        ├── sub-10159_task-stopsignal_design.tsv
        ├── sub-10159_task-stopsignal_stat-errorts_statmap.nii.gz
        ├── sub-10159_task-stopsignal_statmap.json
        └── sub-10159_task-stopsignal_stat-rSquare_statmap.nii.gz
```

**Comment by Remi-Gau** [comment]
But if someone wants tries different GLMs, they could want one dataset per GLM:

```
derivatives
├── nilearn_glm_1
│   ├── dataset_description.json
│   └── sub-10159
│       ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_design.svg
│       ├── ...
│       └── sub-10159_task-stopsignal_stat-rSquare_statmap.nii.gz
└── nilearn_glm_2
    ├── dataset_description.json
    └── sub-10159
        ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_design.svg
        ├── ...
        └── sub-10159_task-stopsignal_stat-rSquare_statmap.nii.gz
```

One dataset to store all GLMs:

```
derivatives
└── nilearn
    ├── dataset_description.json
    └── sub-10159
        ├── glm_1
        │   ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_design.svg
        │   ├── ...
        │   └── sub-10159_task-stopsignal_stat-rSquare_statmap.nii.gz
        └── glm_2
            ├── sub-10159_task-stopsignal_contrast-stopsuccessMinusGo_design.svg
            ├── ...
            └── sub-10159_task-stopsignal_stat-rSquare_statmap.nii.gz
```

I think it is at the moment Nilearn's job to arbitrate on this, but I would default to having at least a subject level folder in the output to prevent from having all files from say a 100 subjects all saved in one single folder.

**Comment by Remi-Gau** [comment]
@tsalo 
Any peculiar reason why this data structure was chosen?

**Comment by Remi-Gau** [comment]
Also noticing that the statsmap metadata looks like this, which is fine except that having a  `RepetitionTime` for a 3D image feels weird to me. Might be better to have this as metadata of the design matrix that without this may be hard to understand.

```
{
    "Description": "A statistical map generated by Nilearn.",
    "ModelParameters": {
        "drift_model": "cosine",
        "drift_order": 1,
        "fir_delays": [
            0
        ],
        "high_pass": 0.01,
        "hrf_model": "glover",
        "scaling_axis": 0,
        "signal_scaling": 0,
        "slice_time_ref": 0.0,
        "smoothing_fwhm": 5.0,
        "standardize": false,
        "target_affine": null,
        "target_shape": null
    },
    "RepetitionTime": 2
}
```

**Comment by bthirion** [comment]
Makes sense to me.

**Comment by Remi-Gau** [comment]
I meant to say.

I think it is NOT, at the moment, Nilearn's job to arbitrate on this,

**Comment by tsalo** [comment]
@Remi-Gau I believe we went with a flat structure to produce BIDS-like outputs without committing to making Nilearn a BIDS App. The idea was to make it easier to use Nilearn within BIDS Apps, like fitlins. Here's the original description from #2715:

>The goal of the new function(s) is not to implement a BIDS App, but to generate BIDS-compatible outputs that can be collected and integrated automatically within a BIDS App like fitlins. The output files won't use entities from the source files; they'll only have the new entities specific to the model. We also can't define the full derivative directory tree because the function(s) will be tied to an individual model, so we will output any top-level files (like dataset_description.json) within the one output directory.

That said, writing out more complete BIDS derivatives is definitely something I'm in favor of.

**Comment by bthirion** [comment]
To me just setting a BIDS-compatible folder tree is a good thing. The cost is limited.

**Comment by Remi-Gau** [comment]
> I believe we went with a flat structure to produce BIDS-like outputs without committing to making Nilearn a BIDS App. The idea was to make it easier to use Nilearn within BIDS Apps, like fitlins.

It seems that fitlins handles the saving to file and output file naming itself in any case:

https://github.com/poldracklab/fitlins/blob/35f9a0d440731f3ad5630c56bda2780878885794/fitlins/workflows/base.py#L142-L173

**Comment by tsalo** [comment]
It does, but I figured that following a recognizable filename pattern in Nilearn would make it easier to handle things on fitlins' side. Plus, with BIDS-like outputs, we can include sidecar files with useful metadata.
