### ISSUE TITLE
Show in example how does one get the the parameter estimates from compute_contrast

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4187]
Hello,
thank you so much for working on nilearn and improving the documentary!
I encountered the same problem as @mekman and was wondering if it would be possible to add a pointer here:
[tutorial](https://nilearn.github.io/dev/auto_examples/00_tutorials/plot_single_subject_single_run.html#detecting-voxels-with-significant-effects)

_Originally posted by @FabianRe1 in https://github.com/nilearn/nilearn/issues/2910#issuecomment-1877766340_

**Comment by Remi-Gau** [comment]
@FabianRe1 I moved your comment from the closed pull request where you had added it to its own issue to make sure it would be more visible.

**Comment by Remi-Gau** [comment]
@FabianRe1
- I think this may be a duplicate of the discussion in #2544
- I will close this issue as a duplicate next week but if you feel this is sufficiently different let us know and we can reopen it

**Comment by FabianRe1** [comment]
Hi Remi, 
yes indeed - I had exactly the same question. Thank you for the pointer!

**Comment by Remi-Gau** [comment]
Closing this but feel free to add more comment in that other issue @FabianRe1
