### ISSUE TITLE
Ensure all examples output to their files to a git ignored directory

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4209]
Not a big issue but I am slowly getting irritated of reverting commits because I committed 50 niftis to the repo.

This may also simplify our .gitignore to avoid things like:

```
# examples
examples/**/*.pdf
examples/**/results/
examples/results/
results/
examples/*.nii
examples/*.nii.gz
examples/*.png
examples/04_glm_first_level/derivatives
```

**Comment by bthirion** [comment]
I don't mind much about .gitignore, but we can probably fo better indeed. The problem is for future developers to keep in memory that they should only output stuff into gitignored directories.
