### ISSUE TITLE
[BUG] contrast matrices figures are not displayed properly when handling unpadded contrasts

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

For example one of the following:
- Linux Ubuntu 22.04

### Python version

- [ ] 3.12
- [X] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

dev

### Expected behavior

- from the GLM reports from examples/04_glm_first_level/plot_fiac_analysis.py

![image](https://github.com/nilearn/nilearn/assets/6961185/20ec9d40-52f0-4061-a9ff-0a068bbb0731)

### Current behavior & error messages

- from the GLM reports from generated with unpadded contrasts in #3191

![image](https://github.com/nilearn/nilearn/assets/6961185/7c3454e5-06cd-488c-943d-0c6600ad2b6e)

### Steps and code to reproduce bug

```python
# Paste your code here

# Will add soon

```

**Comment by bthirion** [comment]
Oops, indeed.
