### ISSUE TITLE
[ENH] the compcor option for `load_confound_strategy` should allow overall global signal regressor

### ISSUE THREAD

**Issue by htwangtw** [nilearn/nilearn#4223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

This is change will be more inline with the fmriprep recommendation: 
![image](https://github.com/nilearn/nilearn/assets/13743617/1f108821-e299-4462-9fdb-63987b2a11de)

### Benefits to the change

allow user to use the gsr option when using the default. 
This will not effect people who wish to use the bare bone `load_confounds`.

### Pseudocode for the new behavior, if applicable

Change from
```python
"compcor": {
    "strategy": ("high_pass", "motion", "compcor"),
    "motion": "full",
    "n_compcor": "all",
    "compcor": "anat_combined",
    "demean": True,
},
```
to
```python
"compcor": {
    "strategy": ("high_pass", "motion", "compcor"),
    "motion": "full",
    "n_compcor": "all",
    "compcor": "anat_combined",
    "global_signal": None,
    "demean": True,
},
```

**Comment by htwangtw** [comment]
I can address this with #4222 in one PR

**Comment by bthirion** [comment]
Good with me. Note that we cut a release versy soon.
