### ISSUE TITLE
[BUG] Backward incompatible change in Decoder

### ISSUE THREAD

**Issue by ymzayek** [nilearn/nilearn#4226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

- Linux Ubuntu 22.04

### Python version

- [ ] 3.12
- [ ] 3.11
- [X] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

0.11.dev

### Expected behavior

The doc build on main is failing because merge of #4188 broke one example. `decoder.decision_function` is called on a list of file paths which is not acceptable input. This input is neither documented nor tested on any of the decoder methods unless I missed something

### Current behavior & error messages

This is what I got:

Calling `decoder.predict` with a list of filepaths will pass this input to `decoder.decision_function` and fail

### Steps and code to reproduce bug

See https://nilearn.github.io/dev/auto_examples/02_decoding/plot_oasis_vbm.html#sphx-glr-auto-examples-02-decoding-plot-oasis-vbm-py

**Comment by bthirion** [comment]
@ymzayek do you want to work on it ?

**Comment by ymzayek** [comment]
Working on it now. Will open a PR asap
