### ISSUE TITLE
title of figure overlaps with progress bar in `plot_first_level_details` example

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4228]
minor issue

see in 
https://nilearn.github.io/dev/auto_examples/04_glm_first_level/plot_first_level_details.html

![image](https://github.com/nilearn/nilearn/assets/6961185/0f31c1fe-751f-40f1-acd4-9427b08c48d3)

note also that the name of the different conditions overlap

I think we should have:

"left - right button press"
"audio - visual"
"computation - sentences"
"horizontal-vertical"

**Comment by ymzayek** [comment]
Might be enough to just increase the figsize in `plt.figure(figsize=(11, 3))`

**Comment by ymzayek** [comment]
That is the figsize in the example's `plot_contrast` function

**Comment by Remi-Gau** [comment]
yup: was doing just that.

but then the brain slices and `L - R` is hidden by the title... 🤷🏾 

still better than not seeing the title

![Figure_1](https://github.com/nilearn/nilearn/assets/6961185/c86077e3-313e-4171-ba91-8ec8df209d65)

**Comment by ymzayek** [comment]
and if you increase the height a bit as well?

**Comment by Remi-Gau** [comment]
> and if you increase the height a bit as well?

that did it
