### ISSUE TITLE
New failing circleci pipeline

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4236]
CircleCI Pipeline. Never seen this one before.

https://app.circleci.com/pipelines/gh/nilearn/nilearn/11312

![image](https://github.com/nilearn/nilearn/assets/6961185/8b62535d-56dc-49d2-bb83-93d9c7bb8899)

**Comment by bthirion** [comment]
Hi, can you specify the origin of the failure ?

**Comment by Remi-Gau** [comment]
no real idea so far

never seen before and we did not change anything on our end, so maybe something on the circle CI end?

I got a hunch so will probably try something to see if this makes it go away

**Comment by Remi-Gau** [comment]
OK just realized that the the PR I have opened today do not show this.

Closing for now.
