### ISSUE TITLE
update maintenance doc related to doc pushing

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4245]
Minor detail.

Current version says

> Once the new version tag of a release is pushed upstream following the step above, the Github Actions workflow release-docs.yml will be triggered automatically to build the stable docs and push them to our github pages repository nilearn/nilearn.github.io.

Should probably say to the workflow will be triggered when creating a new **github** release.

**Comment by Remi-Gau** [comment]
seems that the doc and the release doc workflow are missing a `git push` command to actually deploy a stable version of the doc

in any case the latest version of the doc is now up: https://nilearn.github.io/stable/changes/whats_new.html

**Comment by ymzayek** [comment]
@Remi-Gau have you checked the permissions? The automatic workflow did work already with the push to github io when i tested from my fork so thats why im thinking whether or not i set up the permissions correctly. Btw the push command is in the make install recipe for the release docs and for the dev doc build it's actually in the circleci workflow.

**Comment by Remi-Gau** [comment]
The errors I was seeing in CI were affecting both stable and dev Doc, so I suppose it is some new shenanigans.

**Comment by Remi-Gau** [comment]
Need to double check but it seems that the push in the make install only pushes the tags, no?

**Comment by ymzayek** [comment]
Not sure I understand.  A `git push --tags` will push any commits that are referenced by tags. It cannot just push a tag if the commit doesn't exist on remote. Perhaps it can be made more precise by including the specific tag and the name of the remote and branch but it should work as is.

**Comment by Remi-Gau** [comment]
True.
Not sure what happened but I had to make a manual `git push` to trigger the deploy of the stable doc.

**Comment by Remi-Gau** [comment]
will try to rerun the 0.10.3 stable doc deploy locally when I get some idle time on my machine, to see what's happening
