### ISSUE TITLE
Doc build failure

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4248]
Seems to affect the main branch but also affected the automated build of the doc the last release.

Will build the latter locally and push it as we did previously.

Will investigate why the build is failing on main.

Failed doc build on main
https://github.com/nilearn/nilearn/actions/runs/7694595800/job/20965695723

Failed automated build of the doc of 0.10.3
https://github.com/nilearn/nilearn/actions/runs/7693816818/job/20967498354

**Comment by ymzayek** [comment]
It could be related to neurovault being down (i haven't looked in detail but I've seen that before). Try triggering the dev build on main another day or locally make sure you delete the data in wherever example data gets downloaded and run the build with a complete build of any one example that uses neurovault data and you should get the same failure if it's still down.

**Comment by Remi-Gau** [comment]
Good catch

I saw an issue on neurovault for the website being down but had not made the link

**Comment by Remi-Gau** [comment]
things are back to normal so most likely due to neurovault. Good catch @ymzayek

**Comment by Remi-Gau** [comment]
Reopening mostly book keeping as doc builds are failing on main because neurovault seems to be down again.

**Comment by rwblair** [comment]
So there were a variety of issues causing instability on Neurovault. Server its running on only has 2 cores, celery would run two workers by default. Those workers are responsible for generating surface files when new images are uploaded. This could cause celery to choke out python wsgi server(gunicorn) from cpu time causing http requests to timeout.

I set a max number of requests for a gunicron worker to handle before restarting. There were times when the server would run out of ram, not positive if it was a memory leak or legitamate use, but this should prevent the memory leak scenario.

Sometimes the NFS mount for the EFS dive would become unreachable.There was a demon that monitored the NFS mount where images are stored that didn't get started when we provisioned the server, thats running now.

Let me know if you see any more issues with the site.

**Comment by Remi-Gau** [comment]
@rwblair 

Sometimes when you explain the problem and its solution, I wonder whether you are not just [turbo-encabuling](https://www.youtube.com/watch?v=Ac7G7xOG2Ag) me or trying to explain the brain the way [John Cleese would](https://www.youtube.com/watch?v=FQjgsQ5G8ug&t=2s) (turn the caption for the latter and see AI loses its mind).
