### ISSUE TITLE
Refactor nifti masker code

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#425]
Since we are at it, how about refactoring all the nifti masker classes into a single python file?

More concretely, how about unifying the code of...
```python
- base_masker.py
- nifti_masker.py
- nifti_region.py
- multi_nifti_masker.py
```

**Comment by GaelVaroquaux** [comment]
I tend to like the organization where there is one major class per file,
and the file name is the snake_case version of the CamelCase class name.

**Comment by AlexandreAbraham** [comment]
> I tend to like the organization where there is one major class per file, and the file name is the snake_case version of the CamelCase class name.

So should we split nifti_region into nifti_labels_masker and nifti_maps_masker?

**Comment by banilo** [comment]
> split nifti_region into nifti_labels_masker and nifti_maps_masker

This seems to make sense for the sake of consistency.

**Comment by GaelVaroquaux** [comment]
> So should we split nifti_region into nifti_labels_masker and
> nifti_maps_masker?

IMHO Yes. I find that such organization of the codebase makes it very
easy to find where a class is defined.

**Comment by AlexandreAbraham** [comment]
@banilo, do you volunteer? ;)

If not, I'll find 10 minutes to do that during the week end. Given that we have released, I think that this kind of change should be done ASAP.

**Comment by banilo** [comment]
I volunteer - will do it this afternoon.
