### ISSUE TITLE
Reorganize documentation

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#428]
The current documentation was built organically as the code grew. I propose a refactor of the structure, to make it easier to understand. Here are the notes and proposed layout from brainstorming with @banilo and @AlexandreAbraham :

# Introduction: nilearn, how and what for?

## Nilearn: MVPA and machine learning for neuroimaging

Here: define and relate to other things that people know

Set the problem, use the right words and give our added value

Right words: functional connectivity, parcellation, connectomes, MVPA, decoding, ...

Have a table/list linking sections of the docs to different modalities (VBM, Task, resting state)

Our added value:

- very simple (a few lines of code) access to advanced methods
- we scale (fast, memory usage...)
- we enable easy prototyping for experimentation and method development
- what we provide in the wider problem of learning on brain images is
  really feature engineering

## Installing nilearn

# Decoding: predicting from brain images

## Advanced methods

# Functional connectivity and resting state

## Clustering: learning a brain parcellation

# Image manipulation and visualization

## Loading images and NiftiMasker

Explain here that the concept of loading images doesn't really exist in nilearn: you can just pass file names to functions. Define what a niimage is

## Datasets integrated in nilearn

- Example datasets
- Atlases

# Advanced usage: pipelines and scaling up

**Comment by lesteve** [comment]
Before I forget, there are a few URLs in docstrings that will need to be amended if the doc moves around. Off the top of my head:
* Niimg-like description URL in a lot of docstrings
* installation instructions URL in the import error message in nilearn/version.py

There may be others, easy enough to git grep for nilearn.github.io.

**Comment by GaelVaroquaux** [comment]
I am working on the issue on the branch https://github.com/GaelVaroquaux/nilearn/tree/doc_rework

**Comment by AlexandreAbraham** [comment]
Thanks Gael! I close this one as I think that a new rework of the doc should be done in another issue.
