### ISSUE TITLE
[BUG] Location of individual spheres does not match the "all spheres plot" in NiftiSpheresMasker reports

### ISSUE THREAD

**Issue by cbedetti** [nilearn/nilearn#4282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

Operating system used to build the stable documentation (2024-02-22)

### Python version

- [ ] 3.12
- [ ] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

nilearn version used to build the stable documentation (2024-02-22)

### Expected behavior

Location of individual spheres should match the "all spheres plot" in NiftiSpheresMasker reports

### Current behavior & error messages

See the report in the stable documentation [here](https://nilearn.github.io/stable/auto_examples/03_connectivity/plot_sphere_based_connectome.html#display-spheres-summary-report)

**Comment by Remi-Gau** [comment]
Good catch. Thanks a bunch for reporting.
Will check if this is a new problem or if this was always there.

**Comment by Remi-Gau** [comment]
For the record here how it looked in the doc:

![image](https://github.com/nilearn/nilearn/assets/6961185/690fc0b4-58bb-4791-8416-1af8ed19dc44)


![image](https://github.com/nilearn/nilearn/assets/6961185/09895f7a-957b-4e89-a57e-9c91a093c2de)
