### ISSUE TITLE
[BUG] Colorbar is unreadable with plot_stat_map in mosaic mode

### ISSUE THREAD

**Issue by tsalo** [nilearn/nilearn#4283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [X] Mac
- [ ] Windows

### Operating system version

- Mac OS Version 14.2.1 "Sonoma"

### Python version

- [ ] 3.12
- [ ] 3.11
- [ ] 3.10
- [X] 3.9
- [ ] 3.8

### nilearn version

0.10.3

### Expected behavior

I would expect the colorbar to be thick enough to interpret, with labels large enough to read.

### Current behavior & error messages

No error message, but here is an example figure:
![image](https://github.com/nilearn/nilearn/assets/8228902/99a4ba4a-b4e5-4f6b-9165-f60a708e4115)

### Steps and code to reproduce bug

```python
from nilearn import datasets, plotting

stat_img = datasets.load_sample_motor_activation_image()
display = plotting.plot_stat_map(stat_img, display_mode="mosaic", annotate=False, output_file="test.png")
```

**Comment by Remi-Gau** [comment]
youch!
indeed not the best!
