### ISSUE TITLE
Render masker report as part of the documentation 

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4290]
- just like was done for the GLM reports in https://github.com/nilearn/nilearn/pull/4267
---

- [x] MultiNiftiLabelsMasker
- [x] MultiNiftiMapsMasker
- [x] MultiNiftiMasker
- [x] NiftiLabelsMasker
- [x] NiftiMapsMasker
- [x] NiftiMasker
- [x] NiftiSpheresMasker

**Comment by emdupre** [comment]
I'm not sure if we want to make these standalone pages, or include them in the relevant example builds. We had previously tried to use the latter approach; e.g., here : https://nilearn.github.io/stable/auto_examples/06_manipulating_images/plot_nifti_simple.html

Personally, I think it's more useful to include them directly in the examples rather than on a standalone page.

**Comment by Remi-Gau** [comment]
Useful for whom is the question.

As a maintainer I can barely keep track of where to find what in the Nilearn codebase + doc.

Having all types of reports generated by a single script and centralized in one page makes it way easier to check them locally or in the doc to confirm that they look as expected.

For the users, the code snippets used to generate the reports in that standalone scripts are taken from examples that already show them how to generate the reports: so at most it is a duplication. I am defo not planning to remove them from the examples.

**Comment by bthirion** [comment]
The question is thus whether we think that duplication is bad vs more systematically checking the quality of the different generated reports.  What is true is that so far we were not monitoring well the rendering of the reports.

**Comment by emdupre** [comment]
Thanks for clarifying !

Personally, I'm fine with duplication (so long as it does not significantly impact build time), but I wanted to make sure that we weren't planning to point out from the examples to the generic reports page(s). If we have to choose, I'd rather see them on the example pages 😸 

Given :
> If we generate the GLM reports on every doc build it would add 4 minutes to the doc build time: https://github.com/nilearn/nilearn/actions/runs/7888150339/job/21524981188?pr=4267#step:34:1588
(from https://github.com/nilearn/nilearn/pull/4267#issuecomment-1941694375)

Do we have a time estimate for how long it takes to generate the new maskers report page(s) ?

**Comment by Remi-Gau** [comment]
I has added some timeit to the script that builds the reports so we can more easily monitor this.

Masker reports took [150 seconds to build](https://output.circle-artifacts.com/output/job/7bc0efe2-ec96-41a2-b35d-dabbfd289cef/artifacts/0/dev/modules/generated_reports/masker_reports_examples.html).
GLM reports took [80 seconds](https://output.circle-artifacts.com/output/job/7bc0efe2-ec96-41a2-b35d-dabbfd289cef/artifacts/0/dev/modules/generated_reports/masker_reports_examples.html).

So let's say 4 minutes.

At the fastest the full build on main took 65 minutes.

https://github.com/nilearn/nilearn/actions/workflows/build-docs.yml?query=branch%3Amain+is%3Asuccess

So that's a 6% increase in build time. Not great. Not Terrible.

**Comment by bthirion** [comment]
I'm surprised that the masker takes that much time. I guess that this is because of resampling operations. There might be ways to avoid this.
