### ISSUE TITLE
[BUG] MultiNiftiMapsMasker reports are empty

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

For example one of the following:
- Linux Ubuntu 22.04

### Python version

- [ ] 3.12
- [X] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

dev

### Expected behavior

to have non empty reports

### Current behavior & error messages

This is what I got:

![image](https://github.com/nilearn/nilearn/assets/6961185/3b0cc2fb-3ebf-4268-bc83-452d99573b76)

![image](https://github.com/nilearn/nilearn/assets/6961185/391cde29-9fbc-43de-9f72-6dfc4f99052e)

### Steps and code to reproduce bug

```python
from pathlib import Path
from nilearn import datasets
from nilearn.maskers import (
    MultiNiftiMapsMasker
)

REPORTS_DIR = Path().cwd()

difumo = datasets.fetch_atlas_difumo(
    dimension=64, resolution_mm=2, legacy_format=False
)

data = datasets.fetch_development_fmri(n_subjects=2)

masker = MultiNiftiMapsMasker(
    maps_img=difumo.maps,
    standardize="zscore_sample",
    standardize_confounds="zscore_sample",
    memory="nilearn_cache",
    n_jobs=2,
)

masker.fit()
report = masker.generate_report()
report.save_as_html(REPORTS_DIR / "multi_nifti_maps_masker_atlas.html")

_ = masker.fit_transform(data.func, confounds=data.confounds)
report = masker.generate_report()
report.save_as_html(REPORTS_DIR / "multi_nifti_maps_masker_fitted.html")
```

**Comment by bthirion** [comment]
Oops, indeed.
