### ISSUE TITLE
Standardize footer of reports

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4300]
The GLM reports mention Nilearn and links to the repo.

This should be extended to all reports

![image](https://github.com/nilearn/nilearn/assets/6961185/02df06fd-8d13-43f8-8ffa-d91c1a3a4754)

**Comment by emdupre** [comment]
Does it make sense to extend it to all reports ? For the standalone HTML pages, I could see the need, but would you also add it e.g., to a jupyter cell output of a NiftiMasker report ? In the latter case, I don't think we'd want a footer.

**Comment by Remi-Gau** [comment]
> In the latter case, I don't think we'd want a footer.

Can you tell me more about why you'd think it'd be an issue if the report in that cell output had a footer?

**Comment by emdupre** [comment]
The standalone HTML reports were designed to be distributed independently, but the within-jupyter calls will be distributed within a notebook (by definition) that will also contain the originating code. 

So, in the case of standalone pages, the footer will help to keep provenance --- which is great, I think ! But in the within-jupyter case, it's at best redundant and at worst distracting for those working in a notebook.

**Comment by Remi-Gau** [comment]
@emdupre 
This convo makes me realize that we may want to have some code to run some notebook to check that the reports still look good in a notebook. 
Maybe as a follow up to #4295

**Comment by Remi-Gau** [comment]
> But in the within-jupyter case, it's at best redundant and at worst distracting for those working in a notebook.

**Comment by Remi-Gau** [comment]
Related to improving how reports looks in notebooks:

- GLM reports
  - different styling as the masker reports
  - too wide and the color bar is hidden on the right of the contrast plots
- Masker reports
  - why are the maskers reports so narrow by default?

**Comment by bthirion** [comment]
When I download the nb I can't see the report...

**Comment by Remi-Gau** [comment]
Hum... I must have messed something. Will check tomorrow.

**Comment by bthirion** [comment]
> * why are the maskers reports so narrow by default?

No idea. These reports were probably a bit minimalist at the origin, hence a narrow layout would be OK.
