### ISSUE TITLE
Add an example with plotting of 4D images (was Plotting doesn't allow slicing in 4D image)

### ISSUE THREAD

**Issue by surchs** [nilearn/nilearn#431]
Hi,

I started testing the plotting tools which seem very cool but ran into an issue when trying to overlay my statistical maps which are all 4D images (with the 4th dimension being different tests). I am wondering if there are plans to support slicing in loaded 4D images in the future - dumping each file to 3D individually is possible but seems a bit cumbersome.

Best,
Seb

**Comment by GaelVaroquaux** [comment]
Use 'index_img':

from nilearn.image import index_img
plot_stat_map(index_img('my_file', 1))

We should do an example on this.

**Comment by surchs** [comment]
Awesome. This is what I needed. I'm happy to help with the example. Let me know how I could help.

Best,
Seb

**Comment by lesteve** [comment]
> We should do an example on this.

There are a few examples using index_img and iter_img. 

```
$ git grep -lP 'index_img|iter_img' examples/
examples/connectivity/plot_canica_resting_state.py
examples/connectivity/plot_ica_resting_state.py
examples/decoding/plot_haxby_searchlight.py
examples/manipulating_visualizing/plot_mask_computation.py
examples/plot_nifti_simple.py
```

Are you saying we should add something like this in a simpler example for example the plot_nilearn_101.py one?

**Comment by GaelVaroquaux** [comment]
Yes,  I have in mind a specific example for that: plotting 4d images.

**Comment by lesteve** [comment]
> Yes,  I have in mind a specific example for that: plotting 4d images.

@surchs you are more than welcome to put together an example showing how to plot 4d images with index_img and possibly iter_img.

It should go in examples/manipulating_visualizing and you can use datasets.fetch_nyu_rest (as in examples/plot_nifti_simple.py) to have a 4d image that you can then slice.

**Comment by AlexandreAbraham** [comment]
@surchs, from what I can see in your github profile, you seem to be studying the brain. If one of your study is based on publicly available data, we can consider adding it as a nilearn example. This is a long term goal and we should all discuss about that but your input is welcome. If you want to do so, please create a specific issue for this matter.

**Comment by GaelVaroquaux** [comment]
I am closing this issue, as the following example solves it:
https://github.com/nilearn/nilearn/blob/master/examples/manipulating_visualizing/plot_probabilistic_atlas.py
