### ISSUE TITLE
[DOC] Update drop-in hour information on contributing page

### ISSUE THREAD

**Issue by man-shu** [nilearn/nilearn#4317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

Minor update.

Currently [this section](https://nilearn.github.io/stable/development.html#how-to-get-help) points to an outdated [GitHub issue](https://github.com/nilearn/nilearn/issues/2882) about drop-in hours and does not mention weekly posts on X.

Should replace [GitHub issue](https://github.com/nilearn/nilearn/issues/2882) with [this link](https://tinyurl.com/nilearn-drop-in-hour) and add a sentence mentioning the X posts.

### List any pages that would be impacted.

`CONTRIBUTING.rst`

**Comment by bthirion** [comment]
Thx for opening. Can you address this ?

**Comment by man-shu** [comment]
Yes done! Resolved in #4318
