### ISSUE TITLE
Extend/improve support for pathlib.Path

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4327]
> [!TIP]
> # **💻 🍁  For the [hacktoberfest](https://hacktoberfest.com/) contributors 🍁 💻**
>
> Make sure to:
> - read our [contributing guidelines](https://nilearn.github.io/stable/development.html#contribution-guidelines)
>
> If this is your first time contributing to Nilearn, add your details in the [CITATION.cff file](https://github.com/nilearn/nilearn/blob/dcd92aa357ab3a751161aeea2edfa3a775ae644f/CITATION.cff#L42).
>
> For your pull request to be valid, you should fix some of [the "path" errors flagged by the ruff checker](https://docs.astral.sh/ruff/rules/#flake8-use-pathlib-pth).
>
> Steps to follow:
> 1. delete one of the ignored `PTH` error from [the ruff configuration in the pyproject.toml](https://github.com/nilearn/nilearn/blob/dcd92aa357ab3a751161aeea2edfa3a775ae644f/pyproject.toml#L136) by deleting it.
> 2. install pre-commit with `pip install pre-commit` and install the pre-commit "hooks" with `pre-commit install`
> 3. let pre-commit run ruff and autofix as many errros as possible with: `pre-commit run -a`
> 4. manually fix the remaining errors

List and number of error instances to fix

- [x] 213    `PTH118`  [ ] os-path-join - assigned to @michellewang 
- [x] 108    `PTH123`  [ ] builtin-open
- [x]  62    `PTH110`  [ ] os-path-exists - assigned to @PrakharJain1509
- [x]  35    `PTH120`  [ ] os-path-dirname - assigned to @hndgzkn 
- [x]  30    `PTH107`  [ ] os-remove - assigned to @PrakharJain1509
- [x]  18    `PTH102`  [ ] os-mkdir - assigned to @PrakharJain1509
- [x]  18    `PTH113`  [ ] os-path-isfile - assigned to @PrakharJain1509
- [x]  17    `PTH100`  [ ] os-path-abspath - assigned to @hndgzkn 
- [x]  12    `PTH119`  [ ] os-path-basename - assigned to @hndgzkn 
- [x]  10    `PTH103`  [ ] os-makedirs - assigned to @hndgzkn 
- [x]   9    `PTH111`  [ ] os-path-expanduser - assigned to @PrakharJain1509
- [ ]   6    `PTH207`  [ ] glob
- [x]   4    `PTH101`  [ ] os-chmod - assigned to @PrakharJain1509
- [x]   4    `PTH112`  [ ] os-path-isdir - assigned to @hndgzkn 
- [x]   3    `PTH202`  [ ] os-path-getsize - assinged to @hndgzkn 
- [x]   2    `PTH201`  [*] path-constructor-current-directory - assigned to @PrakharJain1509
- [x]   2    `PTH203`  [ ] os-path-getatime - assinged to @hndgzkn 
- [x]   2    `PTH204`  [ ] os-path-getmtime - assinged to @hndgzkn 
- [x]   1    `PTH106`  [ ] os-rmdir - assinged to @hndgzkn 
- [x]   1    `PTH109`  [ ] os-getcwd - assigned to @PrakharJain1509
- [x]   1    `PTH114`  [ ] os-path-islink - assigned to @hndgzkn 
- [x]   1    `PTH115`  [ ] os-readlink - assigned to @PrakharJain1509
- [x]   1    `PTH117`  [ ] os-path-isabs - assigned to @hndgzkn 
- [x]   1    `PTH122`  [ ] os-path-splitext - assigned to @hndgzkn 

---

**Older note**

On that note, it may be worth checking in the public API that users can also pass a Path in places where they can pass a string to a file.

I have not checked but it seems that many functions require a string and that Paths are not supported (or at least the doc string is not necessarily explicit - or I missed it).

May be done as some internal refactoring to rely more on pathlib rather than os (where relevant) - to be discussed.

_Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/pull/4323#discussion_r1529050599_

**Comment by Remi-Gau** [comment]
- This should be made easier after #4574 is in. #4574 silences several errors to enforce the use of `pathlib.Path` over `os.path` with ruff. After this we could unsilence a single rule and apply to the whole code base and introduce better support for path one rule at a time.

**Comment by michellewang** [comment]
@Remi-Gau I can take this one :)

**Comment by Remi-Gau** [comment]
Don't take them all!!!

**Comment by Remi-Gau** [comment]
Don't hesitate to open one PR by error type you fix.
Should help with the review.

**Comment by Remi-Gau** [comment]
@hndgzkn @michellewang 
since you are both tackling those issues in parallel I am going to ask you to review each other's PR so that you can also anticipate any eventual merge conflict this may create between your work.

**Comment by PrakharJain1509** [comment]
@Remi-Gau  I have resolved 102, 107, 110, 113, 100, 111, 101, 201, 109, 114, 115, 117. Can you please assign them to me and then I can send you a PR.

**Comment by PrakharJain1509** [comment]
@Remi-Gau Fixed all the PTH issues assigned to me and created a PULL request.
Please review it and update me if any changes required

**Comment by PrakharJain1509** [comment]
Are there any other PTH issues remaining on which I can work on?

**Comment by Remi-Gau** [comment]
At the moment, I would say no. Most of the remaining errors I think are concentrated in the same place and @hndgzkn and @michellewang are on them already. So that if we get more people to work on them, it may create a lot of merge conflicts and headaches.

Will remove the hacktoberfest for now and may add it again later if there is still some work left and the dust settles.

**Comment by hndgzkn** [comment]
Can I continue with `PTH123`?

**Comment by Remi-Gau** [comment]
yup or deal with those 

https://github.com/nilearn/nilearn/blob/646ecfaac61aa940533ae50f18b9dce8464dfa01/pyproject.toml#L196

**Comment by hndgzkn** [comment]
@Remi-Gau Ok to continue with `PTH123`?

**Comment by Remi-Gau** [comment]
> Ok to continue with `PTH123`?
@hndgzkn Go for it but maybe split in several PR (work by subpackage?)

**Comment by hndgzkn** [comment]
I had already started actually, my commits are packagewise. Is it ok? If not, I can divide the PR packagewise, no problem.

I haven't touched `nilearn/datasets` yet. I am waiting the PR of @michellewang to avoid conflicts. I'll do a rebase after it is merged.

**Comment by Remi-Gau** [comment]
> I had already started actually, my commits are packagewise. Is it ok? If not, I can divide the PR packagewise, no problem.

Open a PR with what you got: am just afraid of a 1000 lines PR 😜

**Comment by michellewang** [comment]
@Remi-Gau I can fix the `PTH207` errors if no one is already working on it

**Comment by michellewang** [comment]
There is also the `PTH123` errors for `nilearn.datasets` -- I can also take that one

**Comment by Remi-Gau** [comment]
> There is also the `PTH123` errors for `nilearn.datasets` -- I can also take that one

Start with this one because I am already sort of working on 207 in #4658

**Comment by Remi-Gau** [comment]
Also we need to see if can have private functions `get_dataset_dir` and `fetch_single_file` return Path
and adapt things downstream.

- https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/_utils.py#L193

- https://github.com/nilearn/nilearn/blob/main/nilearn/datasets/_utils.py#L495

**Comment by michellewang** [comment]
Another thing is to be improved is the `"/".join()` calls for path-building in `nilearn.datasets.func`: https://github.com/search?q=repo%3Anilearn%2Fnilearn%20%22%2F%22.join&type=code. I brought this up in a previous PR but adding it here in case we forget
