### ISSUE TITLE
Standardize "nilearn" atlases

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4329]
- ensuring that nilearn atlases have a "standardized" data structure
  (for example that each fetcher returns a list of labels as a list of strings)
- checking the label types passed to the constructor of NiftiLabelMasker
  and throw errors if they do not pass
  instead of warnings like they do here.

_Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/pull/4289#discussion_r1530968406_

**Comment by Remi-Gau** [comment]
Note that the list of labels should also include "background" (or "Background")

**Comment by Remi-Gau** [comment]
Even though working on this should fix #4330 and #4331, it will change what it returned by some of the fetchers (some even if not an API change, it would be a behavior change that should probably go through a deprecation cycle - not 100% about this).

For example, the Destrieux fetcher would return 'labels' as list of strings and not a numpy.recarray containing the names of the ROIs.

So this feels like a bit of an "invasive" change to include into 0.10.4 that should be a bug fix release. So I suggest making that change after 0.10.4 is out.

@bthirion @man-shu what's your take on this?

**Comment by Remi-Gau** [comment]
> Note that the list of labels should also include "background" (or "Background")

Was checking on the templateFlow atlases and not all of them explicitly includes "background" in their list of labels so I would not make this required for Nilearn list of labels (for example by throwing an error if a user passed a list of labels to NiftiLabelMasker that did not include "background".

**Comment by bthirion** [comment]
Indeed, we need to go through deprecation cycles for that one.

**Comment by Remi-Gau** [comment]
Will close this in favor of @4335 (that is more detailed).

Will move people's comments over there.
