### ISSUE TITLE
`first_level_from_bids` should throw warnings and not errors when failing to process one subject if some files are missing

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4332]
Is the problem that your code then just errors and does not proceed to the next subject in your dataset?
If that's the case, I should probably change some of the errors thrown by `first_level_from_bids` into warnings.

_Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/issues/4280#issuecomment-1958915631_

**Comment by Remi-Gau** [comment]
If a dataset has 10 subjects and subject 02 is missing some files (say some events.tsv) and `first_level_from_bids` will loop over all subjects but won't proceed further than subject 02 because it will throw an error.

A nicer behavior would be to :  
- throw a warning when some files are missing for a subject
- skip that subject
- throw another recap warning at the end listing all the skipped subjects

**Comment by bthirion** [comment]
I understand well the use case and you're probably right.
Still, I'm wondering whether this will not "hide" issues for users. People don't care much about warnings...

**Comment by Remi-Gau** [comment]
Yeah I am not 100% sure about this either.

Especially that the function allows you to select which subject to run this on, so you can always "skip" problematic subjects manually.

I'd say that given this is not mission critical, let's wait until we get more complaints on this before changing this. But at least there will be an issue where we can collects complaints and grievances.

**Comment by Remi-Gau** [comment]
will close this for now but we can revisit if users complain that the current way of doing things has too much friction
