### ISSUE TITLE
Documentation describing the intended relationship between nipy and nilearn

### ISSUE THREAD

**Issue by bcipolli** [nilearn/nilearn#434]
On the nilearn homepage, it says nilearn is part of the nipy ecosystem.  However, there seems to be a lot of conceptual overlap between nilearn and nipy, and I'm confused about the intended interaction / organization of the two packages.

For example, how do the nilearn masking tools relate to [nipy's masking tools](http://nipy.org/nipy/stable/labs/mask.html)?  How to interop the `algorithms.statistics` tools in nipy with those here?  And when implementing new code, how to understand what should be a pull request here vs. over at nipy?

Some clarification in the docs about how these issues would be really helpful to a newbie like me, and perhaps people who are familiar with nipy and new to nilearn as well.

**Comment by AlexandreAbraham** [comment]
The _nipy ecosystem_ does not refer to the nipy module, but to the group of tools developped to do neuroimaging in Python (the nipy module is one of them). More details here: http://nipy.org/

**Comment by bcipolli** [comment]
I understand that, thanks!  The interaction with most packages in the nipy ecosystem is clear enough for me (one question about including `clean` here vs. in `nitime`).  The intended interaction with the nipy package itself is the one that's most unclear to me.  Thanks!

**Comment by GaelVaroquaux** [comment]
The way I would put it, is that we want to minimize dependencies on other
packages (to make installation easy). Thus we do embark a bit of
functionality that could be in other packages (masking in nipy, clean in
nitime). This is a fairly common setting: if every package dependent of
every other package, there would be a complex network of dependency.
