### ISSUE TITLE
[DOC] Error in docstring for `nilearn.glm.first_level.first_level_from_bids`

### ISSUE THREAD

**Issue by michellewang** [nilearn/nilearn#4342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

The autodocs for [`nilearn.glm.first_level.first_level_from_bids`](https://nilearn.github.io/dev/modules/generated/nilearn.glm.first_level.first_level_from_bids.html) say to use kwargs prefixed with `confound_`, which will be passed to [`nilearn.interfaces.fmriprep.load_confounds`](https://nilearn.github.io/dev/modules/generated/nilearn.interfaces.fmriprep.load_confounds.html), but that is incorrect as it should be `confounds_` (plural). Also:
1. No error is raised if the wrong prefix is used (and it is unclear what happens to kwargs not starting with `confounds`)
2. The rendering of some parts of the docstring does not look good (see screenshot below)

<img width="517" alt="Screenshot 2024-03-26 at 2 48 36 PM" src="https://github.com/nilearn/nilearn/assets/29051929/2f037e3a-e6ba-474b-bcc7-2e6b69c59423">

### List any pages that would be impacted.

https://nilearn.github.io/dev/modules/generated/nilearn.interfaces.fmriprep.load_confounds.html

**Comment by bthirion** [comment]
Thx for opening. I'm pretty sure you can fix it ;-)
