### ISSUE TITLE
[ENH] Throw error when extra kwargs are given to `glm.first_level.first_level_from_bids`

### ISSUE THREAD

**Issue by michellewang** [nilearn/nilearn#4357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

`nilearn.glm.first_level.first_level_from_bids` takes kwargs, and passes kwargs that have the `confounds_` prefix to another function. However, the remaining kwargs are not checked and nothing happens if for example the confound kwargs are not given correctly (e.g. with typo `confound_` instead of `confounds_`).

I think it would be nice/useful to throw a runtime error or something when that happens (first mentioned in PR #4352). Would be happy to work on this too.

### Benefits to the change

Better debugging when invalid/unknown kwargs are given.

**Comment by Remi-Gau** [comment]
@michellewang 
I assigned the issue to you so that "no one else" (😉) gets started on it.
