### ISSUE TITLE
Suggestions for masker documentation.

### ISSUE THREAD

**Issue by bcipolli** [nilearn/nilearn#436]
1. Please add `intersect_masks` to `NiftiMasker`'s "related functions" would be appreciated.

2. I suggest adding to the docstring of fit, to reminds users that only `mask_args` and `mask_strategy` are used for fitting.  It's specified in the class docstring, but not on the `fit` function docstring.

3. Lastly, I would find it helpful to specify (here or in transform) that:
    * Parameters (detrend, standardize) are computed from the images passed to transform (i.e. not computed and stored from fit)
    * Whether the inverse of these parameters is applied when inverse_transform is called (not sure if they are, for detrend, standardize, and confounds).

    My reasoning for this: my lab does computer vision, and the setup here differs from how our lab (and I believe others in this area) preprocess our datasets.  We compute and store whitening transforms for our training set, then apply them to test and validation sets (which are assumed to come from the same distribution of images as the training set).  I think very clear documentation about the use of these maskers could help avoid confusion for people like me coming from other fields as to the intended use of these maskers.

**Comment by AlexandreAbraham** [comment]
Duplicate #355.
