### ISSUE TITLE
[DOC] Minor discrepancy in comparing means example

### ISSUE THREAD

**Issue by man-shu** [nilearn/nilearn#4363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

Using a movie watching dataset as an example but calling it "resting state" in several places

### List any pages that would be impacted.

The "comparing means of images with `math_img`" example: https://nilearn.github.io/stable/auto_examples/06_manipulating_images/plot_compare_mean_image.html

**Comment by Remi-Gau** [comment]
yup that's an easy fix
