### ISSUE TITLE
first_level_from_bids - More granularity in subject/session selection

### ISSUE THREAD

**Issue by andreaboscutti** [nilearn/nilearn#4380]
I have another potential suggestion regarding the ability to access sessions with more granularity. The img_filters=[('ses', '01')] works great, but in some instances, a user may want to select specific subsets of sessions for different subjects. This would require some refactoring of the BIDS-related functions. I’d be happy to contribute if this is considered a useful addition.

_Originally posted by @andreaboscutti in https://github.com/nilearn/nilearn/issues/3068#issuecomment-2053192630_

**Comment by bthirion** [comment]
Thx for the suggestion. I think that we need to decide how far we want to push BIDS support in Nilearn. I would assume that people use other frameworks for fine-grain BIDS control, but maybe not ?

**Comment by Remi-Gau** [comment]
@andreaboscutti could you provide an example where the current API is adding too much friction for you?

**Comment by Remi-Gau** [comment]
@andreaboscutti 
I am closing this but reopen if you can give more details on this or an example of what the API should look like.
