### ISSUE TITLE
doc build fails on data download

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4389]
I think this is mostly a data availibility issue but the fact that the data download happens during the doc build and not in one step before makes is hard to debug or relaunch the worklow.

Will try to see if I can separate the data download in a previous step.

**Comment by bthirion** [comment]
That's a known hurdle of our framework. Pre-downloading may help but is there a price to pay in terms of code complexity ?

**Comment by Remi-Gau** [comment]
I will try something and you let me know.
