### ISSUE TITLE
`verbose` parameter not passed from MultiPCA to MultiNiftiMasker

### ISSUE THREAD

**Issue by bcipolli** [nilearn/nilearn#442]
https://github.com/nilearn/nilearn/blob/master/nilearn/decomposition/multi_pca.py#L219

if a masker is constructed in `MultiPCA`, it does not provide the `verbose` flag.  

On my machine, this causes the first 60+ seconds of the `connectivity/plot_canica_resting_state.py` example to proceed in silence, despite `verbose=10` being passed to `CanICA`.

I have made the change locally on my machine; happy to submit a PR.

**Comment by lesteve** [comment]
Good catch! From what I remember from other places the mask is generally getting a verbose parameter like `max(0, self.verbose - 1)`. That would definitely make sense to do the same here.

**Comment by bcipolli** [comment]
Fixed in #445
