### ISSUE TITLE
[BUG] get_cmap removed in matplotlib 3.9.0

### ISSUE THREAD

**Issue by jdkent** [nilearn/nilearn#4420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

N/A

### Python version

- [ ] 3.12
- [ ] 3.11
- [X] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

N/A

### Expected behavior

N/A

### Current behavior & error messages

This is what I got:

```bash
# Paste the error message here
`AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'`

```

### Steps and code to reproduce bug

```python
# Paste your code here


```

**Comment by Remi-Gau** [comment]
Just reread the release notes:

![image](https://github.com/nilearn/nilearn/assets/6961185/92e9fdae-2180-4521-864b-a6fbc8df90e3)

> The [matplotlib.pyplot.get_cmap](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.get_cmap.html#matplotlib.pyplot.get_cmap) function will stay available for backward compatibility.

So I think we can just try to make sure we rely on `pyplot.get_cmap`.

- opening a new PR from #4419 to do this

**Comment by Remi-Gau** [comment]
Closing as per the discussion in #4419.

**Comment by Remi-Gau** [comment]
Also realizing late (more a note to myself) that we do have automated tests that run on the latest version of matplotlib so we should in general see failures in our test if something we use gets deprecated.
