### ISSUE TITLE
[DOC] Update possible `estimator` values and corresponding sklearn objects in `nilearn.decoding.Decoder` API ref

### ISSUE THREAD

**Issue by man-shu** [nilearn/nilearn#4434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

The description for the `estimator` parameter should reflect the following:
- when `estimator="logistic"` or `"logistic_l1"` or `"logistic_l2"`, `LogisticRegressionCV` is used instead of `LogisticRegression`.
- ~`estimator="ridge_regressor"` is not mentioned but is available, uses `RidgeCV`.~
- ~`estimator="svr"` is not mentioned but is available, uses `SVR(kernel="linear", max_iter=10000)`.~
- ~`estimator="lasso"` and `"lasso_regressor"` are not mentioned but are also available, using `LassoCV()`.~

**EDIT**: The regressor objects can be used with `nilearn.decoding.DecoderRegressor`. So only the first point is valid.

### List any pages that would be impacted.

https://nilearn.github.io/stable/modules/generated/nilearn.decoding.Decoder.html

**Comment by bthirion** [comment]
Simply add that the estimators used rely on internal cross validation ?

**Comment by man-shu** [comment]
Yes I plan on explaining that in the example in #4437.
For the API ref it would be quicker to just add a ...CV here
<img width="601" alt="Screenshot 2024-06-06 at 12 18 07 PM" src="https://github.com/nilearn/nilearn/assets/35485429/e0726da0-7cc8-491c-8933-4a74b4be3019">
