### ISSUE TITLE
Suggested enhancements for the `plot_adhd_covariance` example

### ISSUE THREAD

**Issue by bcipolli** [nilearn/nilearn#446]
Some suggestions after working through the example:

**Stronger suggestions:**
* `n_subjects` is defined midway through the file and not used.  I suggest to move the definition to the top of the file (where other editable parameters are defined), and to pass it to the call to `datasets.fetch_adhd`
* The `NiftiMapsMasker` is constructed on every loop, and `fit_transform` is used.  This suggests to the user that the mask depends on the input data, but it does not.  I suggest moving the masker construction out of the loop, and calling `fit` with no parameters.

**Milder suggestions:**
* An atlas is used to create the connection matrix, but is never shown.  I suggest showing the atlas to the user, as the connection matrices are uninterpretable without it.  Or, probably much better, plot the centroids of the ROIs on a single mask via the (coming!) connectome plotting.
* `verbose` is passed to some functions, but not others (GraphLassoCV).  Add it to all.
* Caching directory is set to `"."`.  Set it to the standard `nilearn_cache`.

**Comment by bcipolli** [comment]
I removed the comment about abstracting `verbose` to a script parameter.  I agree that the examples tend to be more readable with fewer variables / more hard-coded values.

**Comment by lesteve** [comment]
> An atlas is used to create the connection matrix, but is never shown. I suggest showing the atlas to the user, as the connection matrices are uninterpretable without it. Or, probably much better, plot the centroids of the ROIs on a single mask via the (coming!) connectome plotting.

Just a heads up: I actually have done that in the PR #441 commit is [here](https://github.com/lesteve/nilearn/commit/c9c602f3d69d4594fa10da553ba1c049b2185c1e).

**Comment by AlexandreAbraham** [comment]
:+1: for the stronger suggestions.

**Comment by GaelVaroquaux** [comment]
> :+1: for the stronger suggestions.

All these suggestions seem good to me. Part of them need to connectome
plotting to move forward, but this will happen soon.
