### ISSUE TITLE
[DOC] Providing design matrices as CSV files?

### ISSUE THREAD

**Issue by kimsin98** [nilearn/nilearn#4464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

It is possible to provide design matrices for `FirstLevelModel.fit` as str paths to CSV files, but this behavior is not documented anywhere. Is this a feature that still needs work or just needs to be documented?

Things that should be clarified:
* Formats supported (csv, tsv, etc.)
* What header row, index column should look like
* Data types supported

edit: Might be good to clarify these for the input DataFrame even if reading CSV files directly shouldn't be possible

### List any pages that would be impacted.

https://nilearn.github.io/dev/modules/generated/nilearn.glm.first_level.FirstLevelModel.html#nilearn.glm.first_level.FirstLevelModel.fit
and possibly all the other functions that take design_matrix input

**Comment by man-shu** [comment]
It looks like, independent of what table we are loading (events, confounds, or design matrices), the same workflow is followed (via the ` _check_run_tables` function).

The doc does mention that path strings are accepted for events and confounds, but skips that for design matrices for some reason. So, indeed, the docs should be updated to reflect that.

What seems to be missing is checking whether the final loaded data frame is in the required format for each of these use cases.

**Comment by kimsin98** [comment]
In the user guide and examples, the recommended way of making design matrices is using `nilearn.glm.first_level.make_first_level_design_matrix` function, which also has the details on the expected design matrix components. Perhaps just mentioning this function in API docs for other functions would be sufficient.

**Comment by man-shu** [comment]
Sounds good! So I guess mentioning path strings and pointing to `nilearn.glm.first_level.make_first_level_design_matrix` for the expected format should be enough. 

Would you to like to open a PR for this?

**Comment by Remi-Gau** [comment]
There is "some" info scattered in some places regarding headers or supported formats:
- for events https://nilearn.github.io/dev/auto_examples/04_glm_first_level/plot_write_events_file.html
- for design matrices: https://nilearn.github.io/dev/auto_examples/04_glm_first_level/plot_design_matrix.html

but it VERY implicit and should be made clearly explicit in the API doc indeed

also the fact that you can load a design matrix seems indeed to not be documented anywhere

though the fact that you can load a design matrix from FSL is: https://nilearn.github.io/stable/modules/generated/nilearn.interfaces.fsl.get_design_from_fslmat.html#nilearn.interfaces.fsl.get_design_from_fslmat

**Comment by bthirion** [comment]
Thx for reporting that one !
