### ISSUE TITLE
signal.clean adds mean when using Butterworth filter

### ISSUE THREAD

**Issue by gurraburra** [nilearn/nilearn#4466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [X] Mac
- [ ] Windows

### Operating system version

For example one of the following:
- Mac OS Version 14.5 "Sonoma"

### Python version

- [ ] 3.12
- [X] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

0.10.4

### Expected behavior

Using signal.clean with only lowpass filtering the mean of the signal should not change.

### Current behavior & error messages

Signal.clean now adds the mean to the signal if filtered with Butterworth, ending up with a signal twice the mean of the original signal when using lowpass filtering.

### Steps and code to reproduce bug

```python
from nilearn.signal import clean
import numpy as np

y = np.random.random(100) + 10
y_lowpass = clean(y, tr = 1, low_pass=0.1, detrend=False, standardize=False)
y_highpass = clean(y, tr = 1, high_pass=0.1, detrend=False, standardize=False)

print(y.mean(), y_lowpass.mean(), y_highpass.mean())
```

**Comment by Remi-Gau** [comment]
I can reproduce

ran git bisect with this script:

```python
from nilearn.signal import clean
import numpy as np
from rich import print

def main():
    y = np.random.random(100) + 10

    try:
        y_lowpass = clean(y, t_r = 1, low_pass=0.1, detrend=False, standardize=False)
        y_highpass = clean(y, t_r = 1, high_pass=0.1, detrend=False, standardize=False)

        print(y.mean(), y_lowpass.mean(), y_highpass.mean())
        assert y_lowpass.mean() < 20
        print("good")
        return 0
    except AssertionError:
        print("bad")
        return 1
    except Exception:
        print("skipped")
        return 125

if __name__ == "__main__":
    exit(main())
```

The change of behavior was introduced in this PR: https://github.com/nilearn/nilearn/pull/4116

@htwangtw pinging you to see what your take is on this one.

**Comment by Remi-Gau** [comment]
Side note:

`clean` does not have a `tr` parameter but it has a `t_r` one.

https://nilearn.github.io/stable/modules/generated/nilearn.signal.clean.html#nilearn.signal.clean

The script in the top message does not fail beacause of the `kwargs` to pass parameters to butterworth but no check is done on the kwargs to validate them. This should be improved, also because the test introduced in #4116 also uses `tr` and not `t_r`.

In general I would also recommend making sure that nilearn code ONLY uses `t_r`: it is the most frequent in the code base and in the doc.
Will probably need to go through a deprecation cycle for some of the public API.

**Comment by htwangtw** [comment]
The reason we didn't catch this behaviour is that when we set the high pass filter cutoff to the regular range recommended in the literature (0.008–0.01Hz), everything performed as it should be. Nilearn doesn't check if the value is valid or not and I have not checked what is the behaviour of the scipy function. Idealy, I would imagine that we need an extra check to see if the value need to add the mean back, not just based on the filtering method used?

**Comment by htwangtw** [comment]
@gurraburra have you got some time to look at this again?
The most sensible change that I can do is to return the signal immediately if `standardize=False`.

**Comment by gurraburra** [comment]
> [@gurraburra](https://github.com/gurraburra) have you got some time to look at this again? The most sensible change that I can do is to return the signal immediately if `standardize=False`. After diving to the relevant issue / pr, I am also thinking just tighten the logic before applying standardization in general, like only adding the mean back when `high_pass` has a value [#4116](https://github.com/nilearn/nilearn/pull/4116) [#4087](https://github.com/nilearn/nilearn/issues/4087)

My thinking is that the mean should never be added. If you apply a high-pass filter (or band-pass filter), you expect the mean to be removed since the frequency of a constant signal is 0. If you as user would want to keep the mean then you would have to add it yourself in a separate step. Perhaps add an argument `keep_mean` if you want to give users the option to apply a high-pass filter and keep the mean, but this should not be the default behavior because users, like me, will be surprise if you apply a high-pass filter and the mean is not removed.

**Comment by htwangtw** [comment]
We only intend to add the mean back when percent signal change was used as the standardization option but things are certainly falling through some cracks... 
Please see #4504 
I need to think of some tests to make this more robust for sure.
Thanks for raising this to our attention!
