### ISSUE TITLE
feature request: pass args to vol_to_surf used in plot_img_on_surf

### ISSUE THREAD

**Issue by codyvd** [nilearn/nilearn#4472]
https://github.com/nilearn/nilearn/blob/ef33ae97858e290555a6224699e675d9b3de77e7/nilearn/plotting/surf_plotting.py#L1467C1-L1472C6

It would be helpful to pass arguments to vol_to_surf here to change some of the defaults of how the surface data extraction is done (such as interpolation, etc., which are currently left as their defaults).

**Comment by Remi-Gau** [comment]
Also I am wondering if this could not be better handled with our new experimental surface object.

See https://github.com/nilearn/nilearn/issues/4448

**Comment by codyvd** [comment]
The surface object would be pretty useful! I find myself writing similar code often as well...

**Comment by Remi-Gau** [comment]
Currently with the new SurfaceImage object, here is the way you would do this in a way that allows you to control how the vol_to_surf projection happens.

```python
from nilearn import datasets
from nilearn.experimental.plotting import plot_surf_stat_map
from nilearn.experimental.surface import (
    SurfaceImage,
    PolyData,
    load_fsaverage,
)

from nilearn.surface import vol_to_surf

# load data
stat_img = datasets.load_sample_motor_activation_image()

fsaverage_meshes = load_fsaverage()

# projection
texture_left = vol_to_surf(stat_img, fsaverage_meshes["pial"].parts["left"])
texture_right = vol_to_surf(stat_img, fsaverage_meshes["pial"].parts["right"])

# surface image instance
img = SurfaceImage(
    mesh=fsaverage_meshes["pial"],
    data=PolyData(left=texture_left.T, right=texture_right.T),
)

# plot 
fig = plot_surf_stat_map(
    stat_map=img,
    surf_mesh=fsaverage_meshes["inflated"],
    hemi="right",
    title="Surface with matplotlib",
    colorbar=True,
    threshold=1.0,
)
fig.show()
```

this does not call plot_img_on_surf, but goes to plot_surf_stat_map directly (which plot_img_on_surf actually calls in the end).

**Comment by Remi-Gau** [comment]
Note that it is possible to instantiate SurfaceImages directly with a nifti image

```python
from nilearn import datasets
from nilearn.experimental.surface import (
    SurfaceImage,
    load_fsaverage,
)


# load data
stat_img = datasets.load_sample_motor_activation_image()

fsaverage_meshes = load_fsaverage()

# surface image instance
img = SurfaceImage(
    mesh=fsaverage_meshes["pial"],
    data=stat_img,
)
```

But at the moment the projection to the surface is done behind the scene with the default of vol_to_surf: I want to keep API pretty simple for now.

**Comment by Remi-Gau** [comment]
An API inconsistency has been brought to my attention that makes me weight in favor of implementing this:

> it should be possible to specify the radius [to pass to ˋvol_to_surfˋ] to the higher level ˋplot_img_on_surfˋ function (it is possible to do it to the
ˋview_img_on_surfˋ function, so why not its
non-interactive counterpart?)

**Comment by Remi-Gau** [comment]
OK given that the new SurfaceImage can:
- be instantiated from a nifti image with call to [from_volume](https://nilearn.github.io/dev/modules/generated/nilearn.surface.SurfaceImage.html#nilearn.surface.SurfaceImage.from_volume) with extra arguments that are passed to `vol_to_surf`
- an that this instance can now be diectly used with the surface plotting function of nilearn I will consider that the feature requested in here has been adressed

reopen if you feel otherwise
