### ISSUE TITLE
Update the plot_atlas_comparison example to show how to run connectivity on one hemisphere only

### ISSUE THREAD

**Issue by whsu2s** [nilearn/nilearn#4473]
> [!TIP]
> # **💻 🍁  For the [hacktoberfest](https://hacktoberfest.com/) contributors 🍁 💻**
>
> Make sure to:
> - read our [contributing guidelines](https://nilearn.github.io/stable/development.html#contribution-guidelines)
>
> If this is your first time contributing to Nilearn, add your details in the [CITATION.cff file](https://github.com/nilearn/nilearn/blob/dcd92aa357ab3a751161aeea2edfa3a775ae644f/CITATION.cff#L42).
>
> For your pull request to be valid, you complete the following task(s):

- [ ] update the [03_connectivity/plot_atlas_comparison.py](https://github.com/nilearn/nilearn/blob/main/examples/03_connectivity/plot_atlas_comparison.py) to show how run a connectivity analysis on only one hemisphere. The code to add is already mostly shown in this comment:  https://github.com/nilearn/nilearn/issues/4473#issuecomment-2194704166

---

Original message

Hi, I have some questions about the Yeo parcellation. It may be related to [#1602](https://github.com/nilearn/nilearn/pull/1602), as I've been trying to plot the brain connectivity using the Yeo atlas.

When calculating the coordinates of ROIs using "nilearn.plotting.find_parcellation_cut_coords", we need to specify "label_hemisphere." I understand that it makes sense to analyze the left and right hemisphere separately, but it seems the BOLD signals are extracted from both hemispheres when using the "nilearn.maskers.NiftiLabelsMasker", as some ROIs are on both sides and the extracted signals are the average within each ROI. Did I understand correctly? If yes, then the calculated connectivity is not accurate. If no, then are there ways to choose the side of signals to extract, or to consider both hemispheres?

**Comment by Remi-Gau** [comment]
Can you provide a code snippet (preferably one that only uses nilearn data) to show us what you mean?

maybe by adapting this example
https://github.com/nilearn/nilearn/blob/main/examples/03_connectivity/plot_atlas_comparison.py

**Comment by whsu2s** [comment]
Hi Remi, thanks for your reply! Sure, here is an example:

The Yeo atlas parcellates the whole brain, as shown here

```python
from nilearn.connectome import ConnectivityMeasure
from nilearn.maskers import MultiNiftiLabelsMasker

plotting.plot_roi(yeo.thick_7, title='Yeo atlas', colorbar=True)
```

![yeo](https://github.com/nilearn/nilearn/assets/22023623/08f08616-1dda-45ab-a331-869ae2cb7197)

```python
yeo = datasets.fetch_atlas_yeo_2011()
data = datasets.fetch_development_fmri(n_subjects=3)

connectome_measure = ConnectivityMeasure(
    kind="correlation",
    standardize="zscore_sample",
)

masker = MultiNiftiLabelsMasker(
    labels_img=yeo["thick_17"],
    standardize="zscore_sample",
    standardize_confounds="zscore_sample",
    memory="nilearn_cache",
    n_jobs=2,
)

time_series = masker.fit_transform(data.func, confounds=data.confounds)
correlation_matrices = connectome_measure.fit_transform(time_series)
mean_correlation_matrix = connectome_measure.mean_

coordinates = plotting.find_parcellation_cut_coords(labels_img=yeo["thick_17"], label_hemisphere='left')

plotting.plot_connectome(
    mean_correlation_matrix,
    coordinates,
    edge_threshold="80%",
    title="Yeo Atlas 17 thick (func)",
)
```

By changing the argument ```label_hemisphere='left'``` to ```label_hemisphere='right'``` in the function ```plotting.find_parcellation_cut_coords()```, you can get the plots as shown below:

![left](https://github.com/nilearn/nilearn/assets/22023623/b33fec1f-fbb1-4f0b-8729-cefd574ea413)
![right](https://github.com/nilearn/nilearn/assets/22023623/9c02dcab-8164-4346-918b-6a706c8c192f)

The connectome only shows either the left or right hemisphere using Yeo parcellation, but the correlation matrix is actually calculated by taking the signals from both the right and left hemispheres. That's why the left and the right connectomes look the same as shown above while they should be different. 

My questions are:
1. Does nilearn use the averaged signals from both hemispheres to plot the connectome in one hemisphere? Or I missed something in the calculation using nilearn?
2. Are there any ways to plot the holistic connectome on the whole brain using the Yeo parcellation?

Sorry for my poor explanation. Hope that you understand what I'm trying to explain.

**Comment by Remi-Gau** [comment]
for the case you presented I would do this

```python
import nibabel as nb
import numpy as np

from nilearn import datasets, plotting
from nilearn.connectome import ConnectivityMeasure
from nilearn.image import get_data
from nilearn.image.resampling import coord_transform
from nilearn.maskers import MultiNiftiLabelsMasker

yeo = datasets.fetch_atlas_yeo_2011()

connectome_measure = ConnectivityMeasure(
    kind="correlation",
    standardize="zscore_sample",
)

label_image = nb.load((yeo["thick_17"]))

labels_data = get_data(label_image)
labels_affine = label_image.affine

# Grab hemispheres separately
x, y, z = coord_transform(0, 0, 0, np.linalg.inv(labels_affine))

left_hemi = get_data(label_image).copy()
left_hemi[: int(x)] = 0
label_image_left = nb.Nifti1Image(left_hemi, labels_affine)

right_hemi = get_data(label_image).copy()
right_hemi[int(x) :] = 0
label_image_right = nb.Nifti1Image(right_hemi, labels_affine)

for hemi, img in zip(["right", "left"], [label_image_right, label_image_left]):

    masker = MultiNiftiLabelsMasker(
        labels_img=img,
        standardize="zscore_sample",
        standardize_confounds="zscore_sample",
    )

    data = datasets.fetch_development_fmri(n_subjects=3)
    time_series = masker.fit_transform(data.func, confounds=data.confounds)

    report = masker.generate_report()
    report.open_in_browser()

    correlation_matrices = connectome_measure.fit_transform(time_series)
    mean_correlation_matrix = connectome_measure.mean_

    coordinates = plotting.find_parcellation_cut_coords(
        labels_img=img, label_hemisphere=hemi
    )

    plotting.plot_connectome(
        mean_correlation_matrix,
        coordinates,
        edge_threshold="80%",
        title=f"Yeo Atlas 17 thick (func) - {hemi}",
    )

plotting.show()
```

The results are now slightly different between hemispheres.

![right](https://github.com/nilearn/nilearn/assets/6961185/714da6cf-78fe-4263-85e9-434dfef5f3ae)

![left](https://github.com/nilearn/nilearn/assets/6961185/2f5baabf-ffc2-409c-a3c6-a249452649dc)

**Comment by Remi-Gau** [comment]
Please double check my code before using this in your analysis. I coded that a tad quickly.

**Comment by Remi-Gau** [comment]
Glad it helped.
I think at best we can update the documentation about the yeo parcellation and the example we worked on in this issue to show how to do it, but I would not "change" the parcellation.

**Comment by Remi-Gau** [comment]
@bthirion 
do you think it would make sense to update this example:
https://github.com/nilearn/nilearn/blob/main/examples/03_connectivity/plot_atlas_comparison.py

to show how to use Nilearn to keep only one hemisphere of the yeo parcelation?

**Comment by bthirion** [comment]
I think that this is  a good idea. Since it makes the example longer, it should be clear in the sectioning that this is another  functionality independent from the others.

**Comment by Remi-Gau** [comment]
Updating the top message of this issue to reflect this.

**Comment by victoris93** [comment]
> to show how to use Nilearn to keep only one hemisphere of the yeo parcelation?

I thought the issue was mainly the absence of an example where we plot both hemispheres at once.
Would two more examples (right hemi, whole brain) as separate snippets following [this one](https://github.com/nilearn/nilearn/blob/dcd92aa357ab3a751161aeea2edfa3a775ae644f/examples/03_connectivity/plot_atlas_comparison.py#L57) be ok? Also I was thinking dividing this snippet into smaller chunks would look less overwhelming for first time users.

**Comment by Remi-Gau** [comment]
Definitely smaller code snippets would be good.

I think we should at least demonstrate how to extract one hemisphere from an image (an atlas in this case).

Not sure we should create more examples (for now): though I would not be opposed to have more but smaller examples that can read like a "how to do X".
