### ISSUE TITLE
build doc fail on main: data type <class 'numpy.object_'> not inexact

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4474]
2 examples are failing with the same error

https://github.com/nilearn/nilearn/actions/runs/9667098813/job/26755326067#step:13:14419

```
    ../examples/08_experimental/plot_surf_stat_map_experimental.py failed leaving traceback:

    Traceback (most recent call last):
      File "/home/runner/work/nilearn/nilearn/examples/08_experimental/plot_surf_stat_map_experimental.py", line 114, in <module>
        stat_map[i] = stats.pearsonr(seed_timeseries, timeseries[i])[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/scipy/stats/_stats_py.py", line 4837, in pearsonr
        threshold = xp.finfo(dtype).eps ** 0.75
                    ^^^^^^^^^^^^^^^
      File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/numpy/_core/getlimits.py", line 519, in __new__
        raise ValueError("data type %r not inexact" % (dtype))
    ValueError: data type <class 'numpy.object_'> not inexact

    ../examples/01_plotting/plot_surf_stat_map.py failed leaving traceback:

    Traceback (most recent call last):
      File "/home/runner/work/nilearn/nilearn/examples/01_plotting/plot_surf_stat_map.py", line 107, in <module>
        stat_map[i] = stats.pearsonr(seed_timeseries, timeseries[i])[0]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/scipy/stats/_stats_py.py", line 4837, in pearsonr
        threshold = xp.finfo(dtype).eps ** 0.75
                    ^^^^^^^^^^^^^^^
      File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/numpy/_core/getlimits.py", line 519, in __new__
        raise ValueError("data type %r not inexact" % (dtype))
    ValueError: data type <class 'numpy.object_'> not inexact
```

**Comment by Remi-Gau** [comment]
Can reproduce locally by trying to run the examples alone using that very specific set of dependencies:

<details>
<summary>requirements</summary>
<pre>
alabaster==0.7.16
Babel==2.15.0
beautifulsoup4==4.12.3
certifi==2024.6.2
charset-normalizer==3.3.2
contourpy==1.2.1
cycler==0.12.1
docutils==0.21.2
fonttools==4.53.0
furo==2024.5.6
idna==3.7
imagesize==1.4.1
Jinja2==3.1.4
joblib==1.4.2
kaleido==0.2.1
kiwisolver==1.4.5
latexcodec==3.0.0
lxml==5.2.2
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.0
mdit-py-plugins==0.4.1
mdurl==0.1.2
memory-profiler==0.61.0
myst-parser==3.0.1
nibabel==5.2.1
numpy==2.0.0
numpydoc==1.7.0
packaging==24.1
pandas==2.2.2
pillow==10.3.0
plotly==5.22.0
psutil==6.0.0
pybtex==0.24.0
pybtex-docutils==1.0.3
Pygments==2.18.0
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
requests==2.32.3
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
scikit-learn==1.5.0
scipy==1.14.0
setuptools==70.1.1
six==1.16.0
snowballstemmer==2.2.0
soupsieve==2.5
Sphinx==7.3.7
sphinx-basic-ng==1.0.0b2
sphinx-copybutton==0.5.2
sphinx-gallery==0.16.0
sphinx_design==0.6.0
sphinxcontrib-applehelp==1.0.8
sphinxcontrib-bibtex==2.6.2
sphinxcontrib-devhelp==1.0.6
sphinxcontrib-htmlhelp==2.0.5
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.7
sphinxcontrib-serializinghtml==1.1.10
sphinxext-opengraph==0.9.1
tabulate==0.9.0
tenacity==8.4.2
threadpoolctl==3.5.0
tzdata==2024.1
urllib3==2.2.2
</pre>
</details>

**Comment by Remi-Gau** [comment]
using exactly the same depedencies but dropping back to scipy 0.13.1 makes the crash disappear.

**Comment by Remi-Gau** [comment]
minimal code to reproduce

```python
import numpy as np
from scipy import stats

from nilearn import datasets, surface

nki_dataset = datasets.fetch_surf_nki_enhanced(n_subjects=1)

destrieux_atlas = datasets.fetch_atlas_surf_destrieux()
parcellation = destrieux_atlas["map_left"]
labels = destrieux_atlas["labels"]

timeseries = surface.load_surf_data(nki_dataset["func_left"][0])

pcc_region = b"G_cingul-Post-dorsal"
pcc_labels = np.where(parcellation == labels.index(pcc_region))[0]

seed_timeseries = np.mean(timeseries[pcc_labels], axis=0)

stat_map = np.zeros(timeseries.shape[0])
for i in range(timeseries.shape[0]):
    stat_map[i] = stats.pearsonr(seed_timeseries, timeseries[i])[0]

```

**Comment by bthirion** [comment]
So, this is specific to NKI  data?

**Comment by Remi-Gau** [comment]
not sure

I have not checked the other dataset but I would not be surprised if we had similar issues.
