### ISSUE TITLE
[DOC] non_parametric_inference outputs dict when tfce is True, not False.

### ISSUE THREAD

**Issue by arovai** [nilearn/nilearn#4479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

In the documentation for non_parametric_inference, in the description of the returns, it is said that it returns a dict when tfce is False. I think this is a mere typo:
"This is returned if tfce is False or threshold is not None."
should be changed to 
"This is returned if tfce is True or threshold is not None."

**Comment by bthirion** [comment]
Indeed. Thx for raising. PR welcome !
