### ISSUE TITLE
[DOC]  Decoder's default cross-validation scheme not explained properly

### ISSUE THREAD

**Issue by man-shu** [nilearn/nilearn#4490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

The docstring currently simply says the following:
<img width="479" alt="Screenshot 2024-07-05 at 5 22 50 PM" src="https://github.com/nilearn/nilearn/assets/35485429/be01e9a0-78e0-4fef-8a39-8f4f8fb4e3bb">
It is unclear what 10 means here.

Turns out it is a bit more involved, as explained in a comment buried inside the `_BaseDecoder`.
<img width="682" alt="Screenshot 2024-07-05 at 5 26 23 PM" src="https://github.com/nilearn/nilearn/assets/35485429/8521c3d2-8c05-4d54-b563-2e05dab05184">

### List any pages that would be impacted.

Decoder object's docstring: https://nilearn.github.io/stable/modules/generated/nilearn.decoding.Decoder.html

**Comment by bthirion** [comment]
You simply want to better highlight the decision process ?
