### ISSUE TITLE
[BUG] threshold_img yields negative cut-off even when two-sided is set to True

### ISSUE THREAD

**Issue by gurraburra** [nilearn/nilearn#4497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [X] Mac
- [ ] Windows

### Operating system version

Mac OS Version 14.5 "sonoma"

### Python version

- [X] 3.12
- [ ] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

0.10.4  

### Expected behavior

When thresholding an image with both negative and positive values and setting the argument `two_sided = True`, the variable `cutoff_threshold` should be a positive number otherwise no voxels will be thresholded in the following snipped code from the function:
```python
if two_sided:
        img_data[np.abs(img_data) < cutoff_threshold] = 0.0
```

### Current behavior & error messages

Thresholding with argument `two-sided = True` is implemented wrong. The `cutoff_threshold`should be calculated on the absolute values of img_data:

```python
if two_sided:
    cutoff_threshold = check_threshold(
            threshold,
            np.abs(img_data),
            percentile_func=scoreatpercentile,
            name="threshold",
        )
else:
    cutoff_threshold = check_threshold(
            threshold,
            img_data,
            percentile_func=scoreatpercentile,
            name="threshold",
        )
```

### Steps and code to reproduce bug

```python
import numpy as np
from nilearn import image, datasets

# generate random 3x3x3 image with negative and postive values
img = image.new_img_like(datasets.load_mni152_template(), np.random.normal(size=(3,3,3)))
# threshold image at 1%
img_thresholded = image.threshold_img(img, threshold="1%", two_sided=True)
# see if threshold did anything
assert np.all(img.get_fdata() == img_thresholded.get_fdata()) == False
```

**Comment by man-shu** [comment]
Thanks for spotting the bug @gurraburra !

I could reproduce the issue; however, I disagree with the proposed solution.

I think the issue arises in the following line:
https://github.com/nilearn/nilearn/blob/4412c4210d07c02fe45a17ef0f64131292a7e892/nilearn/image/image.py#L1028

and so we:
- first need to get absolute `cutoff_threshold` 
- and then set everything greater than the (negative) `cutoff_threshold` and everything smaller than the (positive) `cutoff_threshold` to zero like this:
```python
cutoff_threshold = np.abs(cutoff_threshold)
img_data[(-cutoff_threshold < img_data) & (img_data < cutoff_threshold)] = 0.0
```

Let me know what you think.
Here's some code and plot to visualize things:
![issue_4497](https://github.com/user-attachments/assets/996fa8ec-cb3a-404d-9bed-31cc2617db43)
```python
import numpy as np
from nilearn import image, datasets
from nilearn._utils.niimg import safe_get_data
from scipy.stats import scoreatpercentile
from nilearn._utils.param_validation import check_threshold
import matplotlib.pyplot as plt
from numpy.random import RandomState

rng = RandomState(100)
# generate random 3x3x3 image with negative and postive values
img = image.new_img_like(
    datasets.load_mni152_template(), rng.normal(size=(10, 10, 10))
)

### following the logic in nilearn.image.threshold_img

# get the image data
img_data = safe_get_data(img)
# create a copy of the image data to later threshold
thresholded = img_data.copy()
# currently implemented conversion from percentile to threshold
current_thresh = check_threshold(
    "10%",
    img_data,
    percentile_func=scoreatpercentile,
    name="threshold",
)
# proposed conversion from percentile to threshold
prop_thresh = check_threshold(
    "10%",
    np.abs(img_data),
    percentile_func=scoreatpercentile,
    name="threshold",
)
### this is the fix
# get the absolute value of the current threshold
cutoff_threshold = np.abs(current_thresh)
thresholded[(-cutoff_threshold < img_data) & (img_data < cutoff_threshold)] = (
    0.0
)
###
# plot
plt.hist(img_data.ravel(), bins=10, alpha=0.5, label="img_data", density=True)
plt.axvline(
    x=current_thresh, color="r", linestyle="--", label="current threshold"
)
plt.axvline(
    x=prop_thresh, color="g", linestyle="--", label="proposed threshold"
)
plt.hist(
    thresholded.ravel(),
    bins=10,
    alpha=0.5,
    label="ideal thresholded img_data",
    density=True,
)
plt.legend()
plt.savefig("issue_4497.png")
plt.close()

```

**Comment by gurraburra** [comment]
The problem with your solution is that the cutoff_threshold is being calculated as the percentile of the signed data, so that a threshold value of 10% means that 10% of voxels has a signed value less that the computed cutoff value. This does not mean that 10% of the absolute value of the voxels will have a value less that this cutoff. In fact, if you have a symmetrical distribution around, your solution will threshold away (50-10) * 2 = 80% of the data. You can see this if you add the following line to your code: `np.sum(thresholded == 0) / thresholded.size * 100`

**Comment by bthirion** [comment]
I agree that in the two-sided case, it makes more sense to compute the cutoff on the absolute value of the data.
Thx for reporting.
@gurraburra  Can you open a PR ?

**Comment by gurraburra** [comment]
I found another bug I think with the implementation: When using a mask, the function sets all values outside mask to zero, but those voxels will still affect the percentile calculation and hence lead to unexpected behavior. As an example: you thresholding a small region in the brain with a 80%-threshold by using a mask containing 10% of all the voxels in the brain. Because 90% of all voxels are outside the mask, the threshold will return always return 0.

Example:

`import numpy as np
from nilearn import image, datasets
from nilearn._utils.niimg import safe_get_data
from scipy.stats import scoreatpercentile
from nilearn._utils.param_validation import check_threshold
import matplotlib.pyplot as plt
from numpy.random import RandomState

rng = RandomState(100)
# generate random 3x3x3 image with negative and postive values
img = image.new_img_like(
    datasets.load_mni152_template(), rng.normal(size=(10, 10, 10))
)

### following the logic in nilearn.image.threshold_img

# get the image data
img_data = safe_get_data(img)
# create a copy of the image data to later threshold
thresholded = img_data.copy()

# create mask
tmp = np.zeros((10, 10, 10))
tmp[:5, :5, :4] = 1 
print(f"percentage voxels inside mask: {np.sum(tmp) / tmp.size * 100}%")
mask_img = image.new_img_like(
    datasets.load_mni152_template(), tmp
)
mask_data, _ = masking.load_mask_img(mask_img)
# Set as 0 for the values which are outside of the mask
img_data[mask_data == 0.0] = 0.0

# currently implemented conversion from percentile to threshold
current_thresh = check_threshold(
    "80%",
    img_data,
    percentile_func=scoreatpercentile,
    name="threshold",
)

print(f"threshold: {current_thresh}")`

**Comment by bthirion** [comment]
Is this a feature or a bug ? In your call of check_threshold, this function has no concept of masking. It just returns a certain quantile of the image data values. 
To have the behavior you expect, we would need to pass an additional mask argument to `check_threshold` but it does not exist in the current API.
One cannot expect that the function implicitly interprets 0 values as being "out of mask".

**Comment by gurraburra** [comment]
> Is this a feature or a bug ? In your call of check_threshold, this function has no concept of masking. It just returns a certain quantile of the image data values. To have the behavior you expect, we would need to pass an additional mask argument to `check_threshold` but it does not exist in the current API. One cannot expect that the function implicitly interprets 0 values as being "out of mask".

The code I have written is partly snipped code from with in nilearn.image.threshold_img, this function does have an argument ‘mask_img’. It’s the implementation of masking in this function I was trying to highlight.

**Comment by bthirion** [comment]
Oh, I see. You're right, the function should indeed exclude out-of-mask values, instead of simply adding zeros.
Let me suggest to address that in another PR.
