### ISSUE TITLE
[BUG] `image.binarize_img` emits a `UserWarning` about 64-bit ints when provided images that have other `dtypes`

### ISSUE THREAD

**Issue by psadil** [nilearn/nilearn#4498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [X] Mac
- [ ] Windows

### Operating system version

For example one of the following:
  System Version:	macOS 14.5 (23F79)
  Kernel Version:	Darwin 23.5.0

### Python version

- [ ] 3.12
- [X] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

0.10.4

### Expected behavior

When working with `float64` images, I did not expect warnings about `int64`.

### Current behavior & error messages

This is what I got when calling `image.binarize_img`:

```bash
UserWarning: Data array used to create a new image contains 64-bit ints. This is likely due to creating the array with numpy and passing `int` as the `dtype`. Many tools such as FSL and SPM cannot deal with int64 in Nifti images, so for compatibility the data has been converted to int32.
  return new_img_like(niimg, result, niimg.affine)
```

That seems to make sense, because `binarize_img` is passing `int` as `dtype`: https://github.com/nilearn/nilearn/blob/4412c4210d07c02fe45a17ef0f64131292a7e892/nilearn/image/image.py#L1244-L1254

### Steps and code to reproduce bug

```python
> import numpy as np
> from nilearn import image, datasets

> img = image.new_img_like(datasets.load_mni152_template(), np.random.normal(size=(3,3,3)))
> img.get_data_dtype()
dtype('<f8')

> image.binarize_img(img)
```

**Comment by bthirion** [comment]
Thx for opening the discussion. The suggestion is to cast to int8 then ?

**Comment by psadil** [comment]
Yes, if that sounds okay 
```python
"img.astype(bool).astype(np.int8)", 
```

**Comment by bthirion** [comment]
Do you mind opening  a PR ? Thx,
