### ISSUE TITLE
[ENH] Change Butterworth filtering in nilearn.signal.clean to use 'sos' output

### ISSUE THREAD

**Issue by gurraburra** [nilearn/nilearn#4509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed enhancement in detail.

[Scipy documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.butter.html) recommends 'sos' output over 'ba' output when using Butterworth filtering due to numerical issues. I have experience these numerical issus I would therefore suggest updating the Butterworth implementation in signal.clean.

### Benefits to the change

More robust temporal filtering which is less sensitive to numerical issues.

### Pseudocode for the new behavior, if applicable

```python
# insert your code below
sos = sp_signal.butter(
        order,
        critical_freq,
        btype=btype,
        output="sos",
        fs=sampling_rate,
    )

signals = sp_signal.filtfilt(
            sos.
            signals,
            axis=0,
            padtype=padtype,
            padlen=padlen,
        )
```

**Comment by bthirion** [comment]
I have no opinion on this, I trust your experience and scipy recommendations :-)

**Comment by Remi-Gau** [comment]
- Started working on this in #4510

@gurraburra if maybe you have a simple example of the issue you encountered I could write a small test to go with this pull request.
