### ISSUE TITLE
Adapt plot_haxby_searchlight_surface example to work with the new surface image API

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4511]
- Currently blocked by https://github.com/nilearn/nilearn/pull/4205

**Comment by bthirion** [comment]
But the images of Haxby dataset are not correctly spatially normalized. So the projection to fsaverage will return misleading stuff.

**Comment by Remi-Gau** [comment]
Yet that's what we already do in this example. Should we add a warning in this example then?

https://nilearn.github.io/stable/auto_examples/02_decoding/plot_haxby_searchlight_surface.html#sphx-glr-auto-examples-02-decoding-plot-haxby-searchlight-surface-py

**Comment by bthirion** [comment]
I think we should.

**Comment by Remi-Gau** [comment]
Also would require running searchlight on the surface which I do not think we have at the moment: https://github.com/nilearn/nilearn/pull/4205#issuecomment-2386033946

**Comment by bthirion** [comment]
Maybe we should think of replacing Haxby dataset with another one on which we could run surface-based analysis ?
