### ISSUE TITLE
[DOC] a small typographical error on nilearn.interfaces.fmriprep.load_confounds_strategy page

### ISSUE THREAD

**Issue by psyzxy** [nilearn/nilearn#4543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your proposed suggestion in detail.

https://nilearn.github.io/stable/modules/generated/nilearn.interfaces.fmriprep.load_confounds_strategy.html#nilearn.interfaces.fmriprep.load_confounds_strategy
I believe there is a little typographical error on this page where "scrubbing" has been written as "srubbing." Specifically, in this section: " denoise_strategy[str](https://docs.python.org/3.9/library/stdtypes.html#str), default=”simple” ....  **_‘srubbing’:_** Load confounds for scrubbing described in Power et al.[[2]](https://nilearn.github.io/stable/modules/generated/nilearn.interfaces.fmriprep.load_confounds_strategy.html#footcite-power2012). This approach can reliably remove the impact of high motion volumes in functional connectome, however, it might not be suitable with subjects with high motion (more than 50% timeseries flagged as high motion)."

**Comment by Remi-Gau** [comment]
yup thanks for spotting it

I noticed there is actually another similar typo: will fix
