### ISSUE TITLE
Consider replacing flake8, black, isort, pyupgrade... with ruff

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4552]
https://docs.astral.sh/ruff/faq/#which-tools-does-ruff-replace

Could reduce the number of linting tools and speed up linting.

**Comment by bthirion** [comment]
See also my comment #4523 
Things don't run on my box, which sounds a bit like an alarm to me.

**Comment by Remi-Gau** [comment]
you are still getting this on main after reseting to upstream ?
I thought this was solved, sorry.

**Comment by bthirion** [comment]
Inded it works now. Sorry for the noise.

**Comment by Remi-Gau** [comment]
never seen that one before

2 things I would try to clean the cache:

https://pre-commit.com/#pre-commit-clean

```bash
pre-commit clean
```

https://pre-commit.com/#pre-commit-gc


```bash
pre-commit gc
```

**Comment by bthirion** [comment]
Didn't work :-(

**Comment by Remi-Gau** [comment]
Anything out of the ordinary on `git status`.

**Comment by Remi-Gau** [comment]
@bthirion 
do you still face issues?

**Comment by bthirion** [comment]
Not with my tatest maptop, with a new ubuntu.
