### ISSUE TITLE
[BUG] Radiological view on plotting function not working when annotation off

### ISSUE THREAD

**Issue by mathrip** [nilearn/nilearn#4553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

Linux Ubuntu 18.04.5 LTS

### Python version

- [ ] 3.12
- [ ] 3.11
- [ ] 3.10
- [X] 3.9
- [ ] 3.8

### nilearn version

nilearn 0.10.2

### Expected behavior

I am using the plotting.plot_anat() function with the radiological flag True (as below). I am expecting to visualise a T1 brain image in the radiological view 

``` python
display = plotting.plot_anat(
                    T1_file, colorbar=False, cut_coords=coordinates, 
                    draw_cross=False, radiological=True, annotate=False,
                    figure=fig, axes=ax, vmax=vmax
                )
```

### Current behavior & error messages

This is what I got:

The T1 brain image is not in the radiological view when the flag _annotate_ is False (see command below) but display the correct radiological view when the flag _annotate_ is True 

With the command below the brain displayed is in radiological view
```python
display = plotting.plot_anat(
                    T1_file, colorbar=False, cut_coords=coordinates, 
                    draw_cross=False, radiological=True, annotate=True,
                    figure=fig, axes=ax, vmax=vmax
                )
```

With the command below the brain displayed is not in radiological view (R and L flipped)
```python
display = plotting.plot_anat(
                    T1_file, colorbar=False, cut_coords=coordinates, 
                    draw_cross=False, radiological=True, annotate=False,
                    figure=fig, axes=ax, vmax=vmax
                )
```

I think maybe there is an issue with the annotate flag which prevent the radiological view

### Steps and code to reproduce bug

```python
display = plotting.plot_anat(
                    T1_file, colorbar=False, cut_coords=coordinates, 
                    draw_cross=False, radiological=True, annotate=True,
                    figure=fig, axes=ax, vmax=vmax
                )
```

**Comment by Remi-Gau** [comment]
Thanks for the report.

I can reproduce the bug with plot_anat and plot_stat_map: would not be surprised if all plotting functions were affected.

```python
import matplotlib.pyplot as plt
from nilearn.datasets import (
    fetch_spm_auditory,
    load_sample_motor_activation_image,
)
from nilearn.plotting import plot_anat, plot_stat_map, show

subject_data = fetch_spm_auditory()

fig, axes = plt.subplots(
    2,
    2,
    figsize=(20, 10),
)
for annotate, ax_row in zip([True, False], axes):
    for ax, radiological in zip(ax_row, [True, False]):
        plot_anat(
            subject_data.anat,
            title=f"plot_anat: {radiological=} {annotate=}",
            cut_coords=[36, -27, 66],
            annotate=annotate,
            radiological=radiological,
            figure=fig,
            axes=ax,
        )

stat_img = load_sample_motor_activation_image()

fig, axes = plt.subplots(
    2,
    2,
    figsize=(20, 10),
)
for annotate, ax_row in zip([True, False], axes):
    for ax, radiological in zip(ax_row, [True, False]):
        plot_stat_map(
            stat_img,
            threshold=3,
            title=f"plot_stat_map: {radiological=} {annotate=}",
            cut_coords=[36, -27, 66],
            annotate=annotate,
            radiological=radiological,
            figure=fig,
            axes=ax,
        )

show()
```

![Figure_2](https://github.com/user-attachments/assets/b9e6c540-6234-4a99-afd5-e9a6ce4a0a22)

![Figure_1](https://github.com/user-attachments/assets/16c62c9c-f3db-4c15-b632-6ab450cd2287)

**Comment by Remi-Gau** [comment]
was implemented here: https://github.com/nilearn/nilearn/pull/3172

**Comment by bthirion** [comment]
Indeed, line https://github.com/nilearn/nilearn/blob/main/nilearn/plotting/displays/_axes.py#L119
is executed only of `annotate=True`
@mathrip would you be interested in contibuting the fix ?
