### ISSUE TITLE
[DOC] Better document how 0 duration events are handled

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4562]
I think it might be nice to explicitly say how these 0 duration events are handled when creating a GLM but maybe that's because I'm not familiar with how it's done in other tools.

_Originally posted by @hugofluhr in https://github.com/nilearn/nilearn/issues/3884#issuecomment-2373645905_
            
places to check for improvement:
- design matrices construction
- plotting events
- associated examples

**Comment by bthirion** [comment]
Indeed
