### ISSUE TITLE
[BUG] Resampling with nearest interpolation spending majority of time checking array values condition

### ISSUE THREAD

**Issue by kaitj** [nilearn/nilearn#4563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

Ubuntu 22.04.5 LTS

### Python version

- [X] 3.12
- [ ] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

`0.10.5.dev101+gbfa801e23`

### Expected behavior

If `interpolation_order == 0` in `nilearn.image.resampling._resample_one_img`, continue on with rest of the function call.

### Current behavior & error messages

When calling `nilearn.image.resampling.resample_img` with an interpolation_order = 0 (`nearest`), the [logic](https://github.com/nilearn/nilearn/blob/263ec16553757ef1ba18f76b003b16af264e9fbd/nilearn/image/resampling.py#L292) of internal function that gets called (`_resample_one_img`) is spending about half of the time checking the first condition (probing whether the data contains only `[0, 1]`s) before continuing on as the second condition is not met (`interpolation_order != 0)`. Switching the order of these two conditions should bring some minor improvements in performance.

There is also some redundancy in calling `sorted(list(np.unique))` in the same check with `np.unique` already returning the values in sorted order.

### Steps and code to reproduce bug

```python
import nibabel as nib
import numpy as np
from nilearn.image.resampling import resample_img, _resample_one_image
from scipy.spatial.transform import Rotation

# Generate random 4D data to test
data = np.random.randn(100, 100, 100, 100)
img = nib.Nifti1Image(data, np.eye(4))
rot = Rotation.from_rotvec(np.random.randn(3))
target_affine = np.eye(4)
target_affine[:3, :3] = rot.as_matrix()

resample_img(img, target_affine=target_affine, interpolation="nearest")
```

Some sample code that was used to profile `resample_img` and `_resample_one_img` with.

**Comment by bthirion** [comment]
All right, this is not a bug structly speaking, but I understand that you propose to make this function more efficient.
PR welcome !
Best,
