### ISSUE TITLE
`first_level_from_bids` should return subjects in order 

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4581]
If subjects labels are passe, then `first_level_from_bids` will loop over subjects in a random order (uses `set` to avoid duplicates):

https://github.com/nilearn/nilearn/blob/51778dd58d78036afdef7b47ae3137ff0dbda290/nilearn/glm/first_level/first_level.py#L1684

But if no subjects are passed then they are run in a sorted manner:

https://github.com/nilearn/nilearn/blob/51778dd58d78036afdef7b47ae3137ff0dbda290/nilearn/glm/first_level/first_level.py#L1669

It'd be preferable if the behavior is consistent.

Brought to my attention by @TrevorKMDay a while ago but forgot to fix it.

> [!TIP]
> # **💻 🍁  For the [hacktoberfest](https://hacktoberfest.com/) contributors 🍁 💻**
>
> Make sure to:
> - read our [contributing guidelines](https://nilearn.github.io/stable/development.html#contribution-guidelines)
>
> If this is your first time contributing to Nilearn, add your details in the [CITATION.cff file](https://github.com/nilearn/nilearn/blob/dcd92aa357ab3a751161aeea2edfa3a775ae644f/CITATION.cff#L42).
>
> For your pull request to be valid, you should do the following:

- [ ] Remove this line (only sort things once at the return statement):

https://github.com/nilearn/nilearn/blob/51778dd58d78036afdef7b47ae3137ff0dbda290/nilearn/glm/first_level/first_level.py#L1669C22-L1669C51

- [ ] Replace the following line

https://github.com/nilearn/nilearn/blob/51778dd58d78036afdef7b47ae3137ff0dbda290/nilearn/glm/first_level/first_level.py#L1684

By:

```python
return sorted(set(sub_labels))
```

- [ ] add a test to make sure subject are always returned sorted

**Comment by tharun634** [comment]
Hey! I'd like to pick this up

**Comment by Remi-Gau** [comment]
Sure will assign it to you.

**Comment by Remi-Gau** [comment]
Actually @tharun634, I just created the issue but I will add one item to the TODO, which is adding a test to enforce behavior consistency.
