### ISSUE TITLE
[API] SurfaceImage constuct from a volume image

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4587]
Briefly discussed with @jeromedockes.

Currently the SurfaceImage can do 

```python
img = SurfaceImage(mesh, data: PolyData | dict[str, Mesh | str | Path] | Nifti1Image | str | Path)
```

if Nifti1Image | str | Path is passed then `vol_to_surf` will be used under the hood to project nifti image on the mesh.

But none of the options of `vol_to_surf` can be passed as extra parameters to the constructor of SurfaceImage.

So maybe it'd be better to have:

```python
img = SurfaceImage(mesh, data: PolyData | dict[str, Mesh | str | Path])
img = SurfaceImage.from_volume(mesh, data: Nifti1Image | str | Path, vol_to_surf_kwargs: dict[str, Any])
```

**Comment by jeromedockes** [comment]
I don't think we can have a surfaceimage without data ATM, so `SurfaceImage.from_volume(mesh, nifti)` might be better to avoid the `SurfaceImage(mesh)`
