### ISSUE TITLE
Running GLM on surface does not warn that smoothing is not applied

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4588]
Smoothing on surface is not implemented yet.

Yet when running a GLM on surface with some smoothing requested no warning is thrown.

```python
from nilearn import datasets
import pandas as pd
from nilearn.experimental.surface import SurfaceImage, load_fsaverage
from nilearn.glm.first_level import FirstLevelModel

t_r = 2.4
slice_time_ref = 0.5

data = datasets.fetch_localizer_first_level()
fmri_img = data.epi_img

events_file = data.events
events = pd.read_table(events_file)

fsaverage5 = load_fsaverage()
image = SurfaceImage(
    mesh=fsaverage5["pial"],
    data=fmri_img,
)

glm = FirstLevelModel(
    t_r,
    slice_time_ref=slice_time_ref,
    smoothing_fwhm=6,
    hrf_model="glover + derivative",
).fit(image, events)
```

**Comment by Remi-Gau** [comment]
I suspect that should be checked also at the masker level.

**Comment by Remi-Gau** [comment]
@emdupre 
Not sure how far you are on this one.
Feel free to open a draft PR and let me taking over if you do not have the bandwidth.

**Comment by emdupre** [comment]
Incoming tomorrow, sorry for the delay !

**Comment by Remi-Gau** [comment]
no worries at all: I can imagine you must be busy 😉 !

**Comment by emdupre** [comment]
OK, this is a pretty small edit AFAICT. 

> I suspect that should be checked also at the masker level.

Since `SurfaceMasker` is inheriting from `BaseEstimator` rather than `BaseMasker`, it doesn't seem like anything needs to change at that level, at least from my read-through. But obviously very happy to take pointers on other places that changes should be made ! Current PR is at #4666

**Comment by emdupre** [comment]
Unless you meant that we should also be handling this if `smoothing_fwhm` is based to `SurfaceMasker` ? I could move the warning there directly to handle it for all cases, rather than specifically for the GLM.

**Comment by Remi-Gau** [comment]
Thanks for taking care of that one. 
I think you are correct, there is no explicit smoothing parameters for the SurfaceMasker so let's only do that at the GLM level for now.
