### ISSUE TITLE
[BUG] Surface plotting function should use the mesh of SurfaceImage

### ISSUE THREAD

**Issue by bthirion** [nilearn/nilearn#4594]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating system

- [x] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

For example one of the following:
- Linux Ubuntu 22.04

### Python version

- [ ] 3.12
- [ ] 3.11
- [x] 3.10
- [ ] 3.9

### nilearn version

Dev version

### Expected behavior

No need to supply a mesh when you call e.g. plot_surf_stat_map with a SurfaceImage, since a mesh is included in the the SurfaceImage.

### Current behavior & error messages

Current APi still requires a mesh to be provided

**Comment by bthirion** [comment]
The feature exists but was somewhat hidden. Closing for now.

**Comment by Remi-Gau** [comment]
wonder if we may still want to have a few other plotting functions be able to handle being passed only a SurfaceImage object
