### ISSUE TITLE
Colorbar width uses figure size to determine width

### ISSUE THREAD

**Issue by bcipolli** [nilearn/nilearn#461]
It should use the current axis width, not the figure width.  This is causing downstream errors when using subplot.

Not adding much info as I'm investigating (hitting this via #212)

Current behavior: 
![image](https://cloud.githubusercontent.com/assets/4072455/6359961/5e86de3c-bc2b-11e4-89d0-f99db5665060.png)

**Comment by bcipolli** [comment]
There are actually two issues here.  First, the colorbar width is not scaled according to the width of the axes.  Second, something about how the colorbar axis is placed is pushing the brain image far to the left.  The issue can lead to the above error.

I have a fix for the first, but a bit stuck on the second.  I welcome any advice there.

**Comment by bcipolli** [comment]
Found the issue; it was in `OrthoSlicer._locator`.  There are other lingering issues with the colorbar.  I will create a PR for tomorrow.

With all the fixes, I get this:
![image](https://cloud.githubusercontent.com/assets/4072455/6362518/d22d5dea-bc42-11e4-9274-3766d1a0f119.png)
![image](https://cloud.githubusercontent.com/assets/4072455/6362528/ec6d22da-bc42-11e4-989b-13e5125cc288.png)
![image](https://cloud.githubusercontent.com/assets/4072455/6362513/ba5d937e-bc42-11e4-992c-fe6dad4b3ab1.png)

 For reference (old, when working):
![image](https://cloud.githubusercontent.com/assets/4072455/6362557/3195cb0a-bc43-11e4-82ab-a7985713416b.png)

**Comment by bcipolli** [comment]
This was fixed in #464

**Comment by GaelVaroquaux** [comment]
Thanks for fixing the problem and on top of this closing the issue.
