### ISSUE TITLE
support 2nd level GLM analysis of SurfaceImage objects

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4617]
Realizing that we do not support 2nd level analysis of SurfaceImage objects?

@bthirion This is something we want to have, right?

_Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/issues/4603#issuecomment-2397105199_

**Comment by bthirion** [comment]
Yes, we do !

**Comment by Remi-Gau** [comment]
yeah cluster-level and TFCE would not be in the next release

**Comment by Remi-Gau** [comment]
may be worth also updating the example to use proper SecondLevelModel: https://nilearn.github.io/dev/auto_examples/08_experimental/plot_new_surface_bids_analysis_experimental.html#group-study
