### ISSUE TITLE
iter_img on a list of 3D images duplicates the first image

### ISSUE THREAD

**Issue by bcipolli** [nilearn/nilearn#462]
```python
from nilearn import datasets
from nilearn.image import iter_img, index_img

haxby_dataset = datasets.fetch_haxby_simple()
func_img_1 = index_img(haxby_dataset.func, 0)
print list(iter_img([func_img_1]))
```

**Expected:**
a list of one image.

**Current Behavior:**
The image is duplicated.
`[<nibabel.nifti1.Nifti1Image object at 0x10bcf4f90>, <nibabel.nifti1.Nifti1Image object at 0x10bcf4f90>]`

**Notes:**
I believe this problem may be deeper rooted (and more severe than just this example).  I found this while debugging `check_niimgs`, which I believe has a bug with how it deals with iterators.  But I don't have time to dig deeper into this.

**Comment by AlexandreAbraham** [comment]
Works for me on nilearn/master :+1: 
```
In [7]: print list(iter_img([func_img_1]))
[<nibabel.nifti1.Nifti1Image object at 0x7fe511a81890>]
```

**Comment by bcipolli** [comment]
Lemme try that again :)

**Comment by AlexandreAbraham** [comment]
I would have waited for somebody else to try before closing (since we all have different software environments) but if you think you can check by yourself, it's fine!

**Comment by bcipolli** [comment]
@AlexandreAbraham User error :)  I thought I had moved off of my local branch to test this on upstream/master, but I had not.  The real issue is in #463... and that's on upstream/master :)
