### ISSUE TITLE
[DOC] inconsistent Doc style for classes

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4633]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe your proposed suggestion in detail.

Classes where parameters for instanciation are documented after the constructor.

For example Contrasts 

https://nilearn.github.io/dev/modules/generated/nilearn.glm.Contrast.html#nilearn-glm-contrast

And those where they are documented right after the summary doc string.

https://nilearn.github.io/dev/modules/generated/nilearn.decoding.Decoder.html#nilearn-decoding-decoder

The latter is the official numpy doc style.

https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring

### List any pages that would be impacted.

Not sure but will make a list once I am in front of computer and not on a mattress in a climbing gym.

**Comment by bthirion** [comment]
No emergency, but yes we have to do it at some point.mask_to_mesh_ratio < screening_percentile
