### ISSUE TITLE
[DOC] doc of some "modules" list functions before classes

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4634]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe your proposed suggestion in detail.

Most of our modules doc list classes before functions.

That of the regions "module" does not.

https://nilearn.github.io/dev/modules/regions.html

### List any pages that would be impacted.

At least one page.
Maybe others have not checked systematically.

**Comment by bthirion** [comment]
No emergency, but to be fixed indeed.
