### ISSUE TITLE
Clean-up pytest fixtures for creating sample surface images/masks

### ISSUE THREAD

**Issue by man-shu** [nilearn/nilearn#4638]
Yes it does look like we need better fixtures for creating sample surface images.

I was super confused as well because I could not import any of the existing fixtures for making sample surface masks. 

Then I noticed the same thing with sample surface images, and there was an existing `make_mini_img` being used repeatedly. So I created a similar one for masks.

_Originally posted by @man-shu in https://github.com/nilearn/nilearn/pull/4630#discussion_r1799772743_

---

## TODOs

- [x] make sure that surface related contain `surf` to easily distinguish them from the volume one:
- [ ] when cleaning the test suite we should have a fixture that creates very small gifti files to disk to test this with rather than relying on datasets.
  _Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/pull/4589#discussion_r1799843886_
            

--- 

- closes none but relates to #4568

**Comment by man-shu** [comment]
I am working on this one.

**Comment by Remi-Gau** [comment]
will add some explicit TODOs in the top message

**Comment by man-shu** [comment]
While working on this, I am learning how Surface-related objects within Nilearn really work. 
Maybe this is a good opportunity to write some docs side-by-side?

Probably adding sub-sections to: https://nilearn.github.io/stable/manipulating_images/input_output.html#understanding-neuroimaging-data

See the discussion in #4161. We could reopen that issue.

WDYT @Remi-Gau @bthirion

**Comment by Remi-Gau** [comment]
> Maybe this is a good opportunity to write some docs side-by-side?

Yup.

There is a checkbox for that in there
https://github.com/nilearn/nilearn/issues/4027

I think we can get started on this, though I would not make it a blocker for the next release.

My 2-cents so far:
- it should maybe a separate page in the user guide
- let's open a side issue for this rather than reopen an old one

**Comment by man-shu** [comment]
> I think we can get started on this, though I would not make it a blocker for the next release.

Yeah, I agree! Would probably take a while to get everything in there, we could just merge whatever is ready by then and continue working on that after.

> let's open a side issue for this rather than reopen an old one
Cool will do!
