### ISSUE TITLE
Rename `get_mask_volume` to signify both -- calculation of volume for Nifti image and vertices for Surface image

### ISSUE THREAD

**Issue by man-shu** [nilearn/nilearn#4639]
```
    mask_n_vertices = get_mask_volume(mask)
```

we will have to rename this private function or split its behavior because something called get_mask_volume that returns a number of vertices is confusing

_Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/pull/4630#discussion_r1799770140_

**Comment by man-shu** [comment]
How about we call it `get_mask_size`? 
What we mean by "size" can be described in the docstring.

**Comment by bthirion** [comment]
Maybe `get_extent` because size has a precise definition in the Numpy world.
