### ISSUE TITLE
always run tests in random order

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4647]
Currently we have one workflow that runs once a month to run our test suite in a random order to potentially detect test pollution:

https://github.com/nilearn/nilearn/actions/workflows/detect_test_pollution.yml

test pollution: dependency between tests where test B passes if run after test A because A changes some state that makes B pass. If run in a the order B then A then B would fail.

- When working on the test suite (for example https://github.com/nilearn/nilearn/issues/3570) it may takes us a month to realize that we have added dependency between our tests.

I would suggest getting rid of the monthly workflow and always run tests with pytest-random-order

https://github.com/nilearn/nilearn/blob/2e25896c4d05ab4521293acc74557aa01111482a/tox.ini#L138-L146

**Comment by bthirion** [comment]
OK, I don't see any drawback in applying it systematically.
