### ISSUE TITLE
allow to skip specific part of the CI

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4669]
Makes me think it would be nice to be able to skip specific part of the CI.

Now we can either run all of CI (test + doc) (with the option of donc a full build) or none of it.

It'd be nice to be able to at least skip the tests when the PR is only on the doc.

@man-shu what do you think?

_Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/pull/4650#discussion_r1804518148_

**Comment by man-shu** [comment]
I was just thinking about that yesterday. Like a button we an click after pushing a commit to skip running the checks

**Comment by Remi-Gau** [comment]
You can always skip the entire CI on github with specific commit message: https://github.com/nilearn/nilearn/blob/main/.github/workflows/README.md#skip-ci

But this is all or nothing and having more granularity would be nice.

See how scikit learn has some ways to control their CIby including some strings in their commit message:
https://scikit-learn.org/dev/developers/contributing.html#commit-message-markers

**Comment by man-shu** [comment]
Ah yes indeed
