### ISSUE TITLE
[STY] Remove `line-length = 79`

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [nilearn/nilearn#4739]
How about discarding this line? 
https://github.com/nilearn/nilearn/blob/b5a19af89677545388a1b365c9d9b0224e99e9e6/pyproject.toml#L124

Stop following that PEP8 recommendation and instead use the black/ruff default value of [`line-length`](https://docs.astral.sh/ruff/settings/) which is 88.

Also, how about disabling  `E501` as recommended in the [`line-length`](https://docs.astral.sh/ruff/settings/#line-length) documentation? See also [Conflicting lint rules](https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules).

**Comment by bthirion** [comment]
No strong opinion on that one. If there is a consensus for extending line length to 88, I'm good with it. We should just avoid getting back and forth on this !

**Comment by Remi-Gau** [comment]
I suggest we circle back to this one after the 0.11 release

**Comment by Remi-Gau** [comment]
I would be tempted to keep the things as they are:
- current line length indirectly forces us to avoid deeper block nesting (an if within an if within a loop...) which helps readability
- silencing E501 would allow to have super long doc strings on a single line, no? I don't see this as a good thing
- more narrow code helps reading it on a narrower screen: that is especially true if one wants to read the examples on a phone. We already have some weird annoying line breaks as it is: wider lines will make it worse.

![Image](https://github.com/user-attachments/assets/d72d355c-4a5f-4287-b35e-4137d17402cf)

**Comment by DimitriPapadopoulos** [comment]
* There are pros and cons. Shorted lines may also force meaningless variable names. Those who suggested changing the line length from 79 to 88 have obviously already thought about these issues and discussed them. I'd rather refer to existing discussions such as:
  * [The _Black_ code style](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length)
    > You probably noticed the peculiar default line length. _Black_ defaults to 88 characters per line, which happens to be 10% over 80. This number was found to produce significantly shorter files than sticking with 80 (the most popular), or even 79 (used by the standard library). In general, [90-ish seems like the wise choice](https://youtu.be/wf-BqAjZb8M?t=260).
* I do not suggest disabling `E501`.
* Reading code on a phone might be a niche use case, a little bit like editing code with ed. Whether the length is 79 or 88, it won't work well on a phone, but 10% longer lines shouldn't significantly worsen the problem. While the specific value of 79 might have been derived from older terminals, the rationale for short lines is readability. For prose, the optimal line length is usually considered to be 50–75 characters/line. See for example [Readability: The Optimal Line Length](https://baymard.com/blog/line-length-readability). For code, slightly larger line lengths may actually improve readability, with 100-120 characters being the really upper limit.

**Comment by Remi-Gau** [comment]
> I do not suggest disabling `E501`.

but your top message said

> Also, how about disabling E501 as recommended in the [line-length](https://docs.astral.sh/ruff/settings/#line-length) documentation?

# 😉

**Comment by Remi-Gau** [comment]
> Reading code on a phone might be a niche use case

Yes but reading documentation on a phone is much less so: so maybe have some specific guidelines for the example section.

**Comment by Remi-Gau** [comment]
Adding this as a point to discuss at the next dev meeting.

If we go through with this, I would suggest reapplying the new guideline to the codebase all at once because otherwise we will start having very heterogeneous code style.

**Comment by Remi-Gau** [comment]
OK we talked about it yesterday at the core dev meeting and decided to leave things as is.
