### ISSUE TITLE
use pre-commit CI to run checks and update hooks

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4760]
- would only require to grant access to the repository there: https://pre-commit.ci/
- would replace the following workflows:
  -   update hooks: https://github.com/nilearn/nilearn/blob/main/.github/workflows/update_precommit_hooks.yml
  -   check style guide: https://github.com/nilearn/nilearn/blob/main/.github/workflows/check_style_guide.yml

in general pre-commit CI is done even before github has even started and given that we are limited to 20 concurrent jobs on github, that would be one less to run on every PR: https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#usage-limits

**Comment by bthirion** [comment]
Is there any additional requirement on the developer side ?

**Comment by Remi-Gau** [comment]
nope

I will set it up so that we have our current style check and pre-commit CI run in parallel: just to show and then we can decide if we want to fully switch

**Comment by Remi-Gau** [comment]
- example from https://github.com/nilearn/nilearn/pull/4724

![Image](https://github.com/user-attachments/assets/3846cd34-e70c-4fc3-af26-e41259138e54)

**Comment by Remi-Gau** [comment]
Report can accessed by clicking on the "details": https://results.pre-commit.ci/run/github/1235740/1732003996.kUjgSMxWQTSrA-bCSOlWNg

**Comment by Remi-Gau** [comment]
ha one thing I forgot to mention: pre-commit CI will autofix PR.

if a pre-commit hook can autofix something, pre-commit CI will push a commit with the fixes:

see https://github.com/nilearn/nilearn/pull/4756/commits/5eebb40b8aa4119d29804491402004d55db8beb9

![Image](https://github.com/user-attachments/assets/2bc05f95-17a5-42b8-8713-24207160da6b)

from
https://github.com/nilearn/nilearn/pull/4756/commits

this may be confusing as one may have to pull before being to push on one's own branch (or `git push --force`). I used to be cautious of using pre-commit CI because I was afraid this may confuse git beginners: in practice on the several repos where I use pre-commit CI I have not seen it being a problme (yet)

**Comment by Remi-Gau** [comment]
note also that this behavior can be disabled: https://pre-commit.ci/#configuration

**Comment by emdupre** [comment]
> note also that this behavior can be disabled: https://pre-commit.ci/#configuration

light +1 to disabling the additional commits by pre-commit-ci[bot] ; happy to be overruled, though

**Comment by Remi-Gau** [comment]
adding this to the next dev agenda: should be a quick discussion

**Comment by Remi-Gau** [comment]
added a `pre-commit.ci autofix` label to the repo:

it seems that adding it a PR can tell pre-commit ci to autofix a PR and manually override the CI config

just uses it on this PR

https://github.com/nilearn/nilearn/pull/4948

![Image](https://github.com/user-attachments/assets/323b8f6b-f30c-4ee3-85d8-71cefad1e543)

pretty nifti feature
