### ISSUE TITLE
[ENH] Move/remove/drop support for old surface-related stuff

### ISSUE THREAD

**Issue by man-shu** [nilearn/nilearn#4789]
Had a quick chat with @jeromedockes, and he mentioned that it is a bit confusing to know which objects are old and which ones are new because we have both old and new surface objects in the same module right now.

Old surface image:
https://github.com/nilearn/nilearn/blob/e897ec4196015a05ea216b3b6e665a0c8ae46149/nilearn/surface/surface.py#L29

New surface image:
https://github.com/nilearn/nilearn/blob/e897ec4196015a05ea216b3b6e665a0c8ae46149/nilearn/surface/surface.py#L1674

Should we move or remove them from here?

**Comment by Remi-Gau** [comment]
Confusing for whom is the question.

They were not and are still not part of the public API at least as far as the doc is concerned:
- dev: https://nilearn.github.io/dev/modules/surface.html
- stable: https://nilearn.github.io/stable/modules/surface.html

Given how thin they are I'd be ok to remove them.

**Comment by man-shu** [comment]
> They were not and are still not part of the public API at least as far as the doc is concerned:

Ok I didn't look at the docs. Only checked the `__init__.py` of the surface module and they are there:
https://github.com/nilearn/nilearn/blob/b6bfb7159248b1630c7ce9f3d6d66ce7221d2074/nilearn/surface/__init__.py#L9

**Comment by Remi-Gau** [comment]
@man-shu 
do you want to give a stab at removing it?

**Comment by man-shu** [comment]
Yep, will look into it!
