### ISSUE TITLE
connectome_plotter fails with nan's in adjacency matrix 

### ISSUE THREAD

**Issue by amadeuskanaan** [nilearn/nilearn#479]
returns ''ValueError: 'adjacency_matrix' should be symmetric''

**Comment by lesteve** [comment]
Off the top of my head, the symmetricity check is just checking (adjacency_matrix == adjacency_matrix.T).all().

I guess we need it a bit more clever than that.

**Comment by eickenberg** [comment]
Make the comparison with `nan_to_num`? E.g.
`tmp=np.nan_to_num(adjacency_matrix)`
 and `all_close(tmp, tmp.T)` (I don't think there is a function
`nan_equals`)? Or is this too ugly?

**Comment by lesteve** [comment]
I thought of that, but there is the edge case of having a NaN in the element (i, j) and a zero in the (j, i) element. The nan_to_num solution won't catch that. In any case it should be fairly simple to fix.

**Comment by GaelVaroquaux** [comment]
> I thought of that, but there is the edge case of having a NaN in the
> element (i, j) and a zero in the (j, i) element. The nan_to_num
> solution won't catch that. In any case it should be fairly simple to
> fix.

I think that casting nans to zero is a safe bet.

**Comment by AlexandreAbraham** [comment]
> I think that casting nans to zero is a safe bet.
:+1:
