### ISSUE TITLE
Indicate to people to install the Python 64 anaconda version

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#480]
In Leipzig, several people had downloaded the 32 bit. Many examples crash in this situation. We need to push users towards the 64bit.

**Comment by AlexandreAbraham** [comment]
Do you have a log of the crash? Something related to memory I guess. If the error cannot be catched (this is the case I guess) we should put a refernce to that issue somewhere so that people can google it.

**Comment by lesteve** [comment]
MemoryError is the likely culprit. Off the top of my head, on Windows there is something like a 2GB limit on 32 bit processes, which is very likely to be exceeded by nilearn.

**Comment by GaelVaroquaux** [comment]
Fixed by #581
