### ISSUE TITLE
[ENH] `concat_imgs` should be able to concatenate surface images

### ISSUE THREAD

**Issue by pbarbarant** [nilearn/nilearn#4808]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe your proposed enhancement in detail.

As for now `concat_imgs ` expects only niimgs. Since it is a common operation, it would be nice to be able to concatenate surface signals expressed on similar meshes. The following code:
```python
concat_imgs([surf_img(4), surf_img(3)])
```
returns:
```python
Exception has occurred: TypeError
Data given cannot be loaded because it is not compatible with nibabel format:
<SurfaceImage (9, ...
  File "/Users/plbar/Code/nilearn/nilearn/_utils/niimg.py", line 126, in load_niimg
    raise TypeError(
  File "/Users/plbar/Code/nilearn/nilearn/_utils/niimg_conversions.py", line 315, in check_niimg
    niimg = load_niimg(niimg, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/plbar/Code/nilearn/nilearn/image/image.py", line 1549, in concat_imgs
    first_niimg = check_niimg(next(literator), ensure_ndim=ndim)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/plbar/Code/fmralign/fmralign/tests/test_preprocessing.py", line 197, in <module>
    concat_imgs([surf_img(4), surf_img(3)])
TypeError: Data given cannot be loaded because it is not compatible with nibabel format:
<SurfaceImage (9, ...
```

### Benefits to the change

Improve the seamless interface between nifti and surface handling.

### Pseudocode for the new behavior, if applicable

```python
# insert your code below

```

**Comment by Remi-Gau** [comment]
yeah we have a private function for this at the moment: https://github.com/nilearn/nilearn/blob/8318065a433186d0553db281fcf634f21c46ca48/nilearn/maskers/_utils.py#L94

I think after the coming release we will do some refactoring and better integrate some of those utility function with the rest of the code base.

**Comment by pbarbarant** [comment]
> yeah we have a private function for this at the moment:
> 
> [nilearn/nilearn/maskers/_utils.py](https://github.com/nilearn/nilearn/blob/8318065a433186d0553db281fcf634f21c46ca48/nilearn/maskers/_utils.py#L94)
> 
> Line 94 in [8318065](/nilearn/nilearn/commit/8318065a433186d0553db281fcf634f21c46ca48)
> 
>  def concatenate_surface_images(imgs): 
> I think after the coming release we will do some refactoring and better integrate some of those utility function with the rest of the code base.

Thx a lot!

**Comment by Remi-Gau** [comment]
If you are in the mood to work on this a PR is always welcome...

Just sayin' ! 😜

**Comment by Remi-Gau** [comment]
I will close this one in favor of the more generic #4879
