### ISSUE TITLE
Faster / smaller datasets to download

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#481]
Experience from the Leipzig teaching: we need smaller / faster download.

Specifically, 

1. we should have a zip file for fetch_adhd(n_subjects=1) to download only one subject.

2. fetch_habxy(n_subjects=1) should download as little as posible: no stimuli and only 1 subject.

**Comment by AlexandreAbraham** [comment]
> we should have a zip file for fetch_adhd(n_subjects=1) to download only one subject.

What is doable:
* split every subject in a single file
* create another fetcher for ADHD versions preprocessed by the neurobureau. They have 200 subjects and provide directly timeseries for given atlases

> fetch_habxy(n_subjects=1) should download as little as posible: no stimuli and only 1 subject.

This is what `fetch_haxby` does by default. Some masks are also downloaded by default but they are very small.

**Comment by bcipolli** [comment]
Two of the examples use only one subject from the haxby dataset, but don't pass the `n_subjects=1` argument.  Seems this would be an issue as well.

**Comment by GaelVaroquaux** [comment]
> Two of the examples use only one subject from the haxby dataset, but
> don't pass the n_subjects=1 argument. Seems this would be an issue as
> well.

I think that n_subjects=1 should be the default, based on my experience
teaching yesterday.

**Comment by AlexandreAbraham** [comment]
Shouldn't we postpone this one? We'll have no time to solve it before the release.

**Comment by GaelVaroquaux** [comment]
> Shouldn't we postpone this one?

Yes, :-$

**Comment by AlexandreAbraham** [comment]
FYI, dividing ADHD in smaller chunks should not be difficult, I can at least do this one if you want.

**Comment by GaelVaroquaux** [comment]
This issue is important. It is screwing up our workshop again.

**Comment by AlexandreAbraham** [comment]
can you be more specific ? which dataset is problematic ?

**Comment by GaelVaroquaux** [comment]
Haxby. We need to break it up in subjects and download only 1 subjects by default.

**Comment by AlexandreAbraham** [comment]
This is already the case.

**Comment by AlexandreAbraham** [comment]
If you need one dataset to be broken into pieces or moved to nitrc, I can hack it right now. But I have to be sure to target the right ones ;).

**Comment by GaelVaroquaux** [comment]
Don't hack anything. It not that urgent. For it to be beneficial we need to release. It won't happen today.

**Comment by AlexandreAbraham** [comment]
See #605. If the mirroring system proposed in this PR is validated, I will be able to move on this issue.

**Comment by AlexandreAbraham** [comment]
See also #608. Used with the NiftiSpheresMasker, you get an atlas at no cost.

**Comment by banilo** [comment]
+1 for increasing scalability of dataset fetchers

**Comment by AlexandreAbraham** [comment]
#637 make ADHD downloadable subject by subject.

**Comment by AlexandreAbraham** [comment]
We broke down the datasets to the smallest chunks possible. I close this issue. Please re-open one for a specific dataset when you encounter a similar problem.
