### ISSUE TITLE
Rename examples

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4816]
- is there any reason why ALL our examples start with `plot_`? because if the example is not specifically about plotting then it can actually be confusing
- also could we have names that are closer to the actual title of the example: the lack of correspondence adds friction when wanting to find what exemple in the repo corresponds to an rendered example in the doc.

**Comment by man-shu** [comment]
I always thought it had to do something with the sphinx gallery?

**Comment by Remi-Gau** [comment]
it is actually: https://sphinx-gallery.github.io/stable/configuration.html#parsing-and-executing-examples-via-matching-patterns

but we could change this, no?

**Comment by man-shu** [comment]
Yes, I guess we could, but it seems we would still need some sort of pattern to tell Sphinx Gallery which `.py` scripts it can turn into examples.

**Comment by Remi-Gau** [comment]
call me crazy but I was just going to say any `.py` should be fine: if there are some examples that do not need to be run then maybe we could have some prefix but I thihnk we are going to keep running them.

**Comment by man-shu** [comment]
any `.py` in the `examples` directory then

**Comment by bthirion** [comment]
I don't feel it is an issue, but I don't really care.

**Comment by Remi-Gau** [comment]
OK will close this: I think that's a level of friction I can live with
