### ISSUE TITLE
Nilearn tried to store in -/usr/share/fsl/5.0/harvard_oxford

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#484]
A user at the workshop had the fsldir variable set, and got the following error when running the datasets.fetch_harvard_oxford:

<pre>
$ echo $FSLDIR
/usr/share/fsl/5.0

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-3508c846c5eb> in <module>()
      1 from nilearn import datasets
----> 2 atlas_filename, labels = datasets.fetch_harvard_oxford('cort-maxprob-thr25-2mm')

/home/chris/.local/lib/python2.7/site-packages/nilearn/datasets.pyc in
fetch_harvard_oxford(atlas_name, data_dir, symmetric_split, resume, verbose)
   1579     data_dir = _get_dataset_dir(dataset_name, data_dir=data_dir,
   1580                                 lookup_defaults=(data_dir is None),
-> 1581                                 verbose=verbose)
   1582     opts = {'uncompress': True}
   1583     atlas_file = os.path.join('HarvardOxford',

/home/chris/.local/lib/python2.7/site-packages/nilearn/datasets.pyc in
_get_dataset_dir(dataset_name, data_dir, lookup_defaults, verbose)
    259
    260     raise OSError('Nilearn tried to store the dataset in the following '
--> 261             'directories, but:' + ''.join(errors))
    262
    263

OSError: Nilearn tried to store the dataset in the following directories, but:
 -/usr/share/fsl/5.0/harvard_oxford (Permission denied)
</pre>

**Comment by AlexandreAbraham** [comment]
Bug spotted and fixed. Adding a non-regression test will be a bit more difficult.

**Comment by GaelVaroquaux** [comment]
Thanks! That was fast
