### ISSUE TITLE
change some of the default colormap used by nilearn

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4848]
In general we should try to use perceptually uniform colormaps as much as possible to avoid generating figures that show differences that are not really there.

> For many applications, a perceptually uniform colormap is the best choice; i.e. a colormap in which equal steps in data are perceived as equal steps in the color space. Researchers have found that the human brain perceives changes in the lightness parameter as changes in the data much better than, for example, changes in hue. Therefore, colormaps which have monotonically increasing lightness through the colormap will be better interpreted by the viewer. 
>
> from [matplolib doc](https://matplotlib.org/stable/users/explain/colors/colormaps.html#overview)

### current plot_epi

https://nilearn.github.io/stable/auto_examples/01_plotting/plot_visualization.html#visualization

![Image](https://github.com/user-attachments/assets/df82acd3-9167-42bb-9813-9181eb9546ee)

### current plot_img

https://nilearn.github.io/stable/auto_examples/00_tutorials/plot_nilearn_101.html#simple-image-manipulation-smoothing

![Image](https://github.com/user-attachments/assets/d5dfd58c-3317-4cb4-8f1d-358fa3ef860c)

### current view_img

https://nilearn.github.io/stable/auto_examples/00_tutorials/plot_decoding_tutorial.html#visualizing-the-fmri-volume

![Image](https://github.com/user-attachments/assets/d851608a-5aff-4e0d-8fdf-fcbb89f3c339)

### report for label masker

https://nilearn.github.io/dev/modules/generated_reports/masker_reports_examples.html#nifti-labels-masker

![Image](https://github.com/user-attachments/assets/74effb72-d50b-49d2-a410-6220a1c90593)

## default diverging maps should diverge TO different colors

The cold_hot map we use in a lot of places goes (if properly centered) from black = 0 to white for its maximum AND minimum values. 

It can make it ambiguous because it may mean that for example 7 and -7 will have the same color in the figure.

Using one of the recommended diverging maps from matplotlib seems preferable: https://matplotlib.org/stable/users/explain/colors/colormaps.html#diverging

In those maps, the colormap diverges from white to 2 different colors.

## preferentially use sequential maps for some plots

When plotting non diverging values (like probabilities in a map mask) would be better to use one of the uniform colormaps: https://matplotlib.org/stable/users/explain/colors/colormaps.html#sequential

### report MultiNiftiMapsMasker

https://nilearn.github.io/dev/modules/generated_reports/masker_reports_examples.html#nifti-maps-masker

![Image](https://github.com/user-attachments/assets/51e8dce2-ab30-4144-b86d-05460cb3f464)

**Comment by Remi-Gau** [comment]
In general the colormap example page should also link to (and probably be organized like) the matploblib doc for colormaps.

https://nilearn.github.io/dev/auto_examples/01_plotting/plot_colormaps.html#sphx-glr-auto-examples-01-plotting-plot-colormaps-py

It should probably contain a section "on colormaps you should not probably not use" (like jet)

**Comment by Remi-Gau** [comment]
also examples should be thoroughly checked for appropriate use of the right colormap to avoid things like this 

![Image](https://github.com/user-attachments/assets/ad4fa8e3-9284-46b6-ae23-786538cb3317)

https://nilearn.github.io/dev/auto_examples/06_manipulating_images/plot_roi_extraction.html#build-a-statistical-test-to-find-voxels-of-interest

**Comment by bthirion** [comment]
Maybe I would maintain a  difference btw anatomical data that are more geenrally seen in grey scale from EPi images  that may be seen in cold/hot color scale.
