### ISSUE TITLE
[BUG] SurfaceImage doesn't allow different "n_timepoints" across hemispheres

### ISSUE THREAD

**Issue by man-shu** [nilearn/nilearn#4871]
> Wouldn't it be better to have different numbers of regions per hemisphere ?

Hmm... I agree that's a possibility in maps images, but I don't think we allow having different "n_timepoints" across hemispheres in SurfaceImage as of now. See:

https://github.com/nilearn/nilearn/blob/5271b3234ba450205060349b7cd401044d099220/nilearn/surface/surface.py#L1219

_Originally posted by @man-shu in https://github.com/nilearn/nilearn/pull/4830#discussion_r1869041841_

**Comment by man-shu** [comment]
Ok now I don't think we should allow different n_timepoints across hemispheres anymore:

For probabilistic atlases I think if there is a region that only exists in, say, right hemisphere (because the data for vertices in right hemisphere > 0) then the data corresponding to that region would still exist in left hemisphere -- they would just all be zeros.

This means that they should still have the same n_timepoints always...

**Comment by man-shu** [comment]
I'll be closing this one now...

**Comment by bthirion** [comment]
I'm not sure I undertsand the whole story. 
My initial point is that if we handle atlases, there are chance we find situations wherte the numebr of entities/regions is not that same in the two hemipsheres. We should make sure that we support it. By contrast, I don't think that literally having different `n_timespoints` for both hemispheres makes sense.

**Comment by man-shu** [comment]
> By contrast, I don't think that literally having different `n_timespoints` for both hemispheres makes sense.

Yes, I learned that the hard way...

Maybe looking at this commit might help clarify (https://github.com/nilearn/nilearn/pull/4830/commits/4ee6f484cf614e0c23978c7e77bfa47202725e19)

What I thought having different regions across meant earlier (left, in red) vs. How they would actually be (right, in green):
![Image](https://github.com/user-attachments/assets/bed5c6c1-2cc3-485f-965c-241409c70b21)

In the red, I simply added one more column to the right hemisphere -- making `.shape[1]` different between the two hemispheres -- which ended up breaking stuff.
In the green, I realized we should add a corresponding column in the left hemisphere too (but with zeros) -- keeping the `.shape[1]` the same between the two hemispheres -- but the two hemispheres still have different number of regions.

**Comment by bthirion** [comment]
I think that we don't want 0-padding.

**Comment by Remi-Gau** [comment]
> I think that we don't want 0-padding.

so you are saying that we should allow:

- `data.parts["left"].shape(n_vertices_left, m)`
- `data.parts["left"].shape(n_vertices_left, n)`
- with m != n

**Comment by bthirion** [comment]
For an atlas, I think it makes sense.

**Comment by man-shu** [comment]
But not having the padding seems to open a whole can of worms:

The first one I came across was: What the shape of a surface image should be if the two hemispheres have different n_timepoints/n_regions?

For example, if we have `left.shape = (4, 5)` and `right.shape = (5, 6)` where the shape is (n_vertices, n_timepoints/n_regions).
Then, should the shape of the SurfaceImage be `image.shape =  (4+5, 5+6)`?

It might be ok for an atlas to just add the n_regions across hemispheres but we can't do that when it's a time series... simply because the sample was collected at the same timepoint across both hemispheres.

**Comment by Remi-Gau** [comment]
> seems to open a whole can of worms

strong agree with @man-shu on this one

I would start by keeping the data structure constraint we have for now until we have good evidence it adds too much friction for us or for users.

**Comment by man-shu** [comment]
On the other hand, one thing to consider might be if the results (e.g., from `SurfaceMapsMasker.transform()`) are different depending on whether or not we have the padding.

Because if we have different shapes across hemispheres, we'd have to compute region signals separately for each hemisphere. Would that change the computed signals?

**Comment by man-shu** [comment]
That's also why I wanted to get a surface probabilistic atlas to see how people store it. 
And from the atlas in #4874, it seems they also do the padding...
