### ISSUE TITLE
[ENH] Validate input dimensions in SurfaceLabelsMasker

### ISSUE THREAD

**Issue by man-shu** [nilearn/nilearn#4873]
Added this function to validate the dimensions of input images, and I noticed we are not doing that in SurfaceLabelsMasker.

_Originally posted by @man-shu in https://github.com/nilearn/nilearn/pull/4830#discussion_r1869181091_

**Comment by man-shu** [comment]
I know we still have a few things to add to `SurfaceLabelsMasker. 
Are we keeping track of those somewhere? If so, we can close this one and add it to the list there...

**Comment by Remi-Gau** [comment]
I think we may as well open a new "meta" issue to help us roadmap the follow up for the Surface stuff
