### ISSUE TITLE
add min and max properties to PolyData and SurfaceImage

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4878]
Wopuld help to have a sortcut to find the max and min across hemispheres:

Would help avoid this:

https://github.com/nilearn/nilearn/blob/9492ea67cce7f1f62281adef4469f3e7f2b0d0bf/examples/07_advanced/plot_surface_image_and_maskers.py#L77-L80

and do

```python
vmax = np.absolute([mean_img.max, mean_img.min]).max()
```

**Comment by ricor07** [comment]
Hello, I'd like to join the project contributing to this issue.

**Comment by Remi-Gau** [comment]
For context we discussed that this type of public method may not be ideal and we should make it easier to access the data instead.
