### ISSUE TITLE
[DOC] [BUG] No plots in reports for surface maskers on Chromium browsers

### ISSUE THREAD

**Issue by man-shu** [nilearn/nilearn#4886]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe your proposed suggestion in detail.

The plots in the reports of SurfaceMasker and SurfaceLabelsMasker are not visible on Chromium browsers:

![Image](https://github.com/user-attachments/assets/5e554420-e495-4525-a943-324020722414)

They do show up on Firefox, apparently.

**Comment by man-shu** [comment]
On Firefox mobile:
![Screenshot_20241204-182126.png](https://github.com/user-attachments/assets/9108696f-e445-4827-9d64-446a4b9d9ae9)

**Comment by Remi-Gau** [comment]
My hunch or something to investigate: how the figure are converted before embedding.

# Surface masker

this is done during the building of the report in the surface masker code

https://github.com/nilearn/nilearn/blob/d1eb079e61bda736ffdcefe0978ad494bfb57ec9/nilearn/maskers/surface_masker.py#L440

# Nifti masker

The masker code creates a list of figures: 

https://github.com/nilearn/nilearn/blob/d1eb079e61bda736ffdcefe0978ad494bfb57ec9/nilearn/maskers/nifti_masker.py#L403

and the conversion is done by the reporting code:
https://github.com/nilearn/nilearn/blob/d1eb079e61bda736ffdcefe0978ad494bfb57ec9/nilearn/reporting/html_report.py#L292

At the moment it is VERY unclear what types are expected by the "embedding" in reporting.

I would suggest trying to have better tests at the reporting level to try to reproduce this bug outside of the masker context.

**Comment by man-shu** [comment]
> At the moment it is VERY unclear what types are expected by the "embedding" in reporting.

Indeed! It's also a bit different when you look at NiftiMapsMasker:
https://github.com/nilearn/nilearn/blob/d1eb079e61bda736ffdcefe0978ad494bfb57ec9/nilearn/maskers/nifti_maps_masker.py#L348

The `_embed_img` function uses `figure_to_png_base64` internally but extracts the figure from the display:
https://github.com/nilearn/nilearn/blob/d1eb079e61bda736ffdcefe0978ad494bfb57ec9/nilearn/reporting/html_report.py#L71

**Comment by Remi-Gau** [comment]
go for it
