### ISSUE TITLE
Remove duplicate code already present in nibabel.

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#490]
As far as I understood, we are dropping the idea of supporting any `niimg-like` object and will rely on `nibabel`. If we do so, I see no reason to keep reimplementing features already coded in nibabel.

Namely:
* `nilearn.image.resampling.reorder_img` is a duplicate of `nibabel.func.as_closest_canonical`
* several usage of `nilearn._utils.niimg_conversion.concat_niimgs` are covered by `nibabel.funcs.concat_images`.
* `nilearn._utils.niimg_conversion._index_niimgs` can be rewritten using `nibabel.funcs.four_to_three`

There may be other modifications that I don't know of.

**Comment by AlexandreAbraham** [comment]
As a sidenote, we could support SpatialImage type from nibabel (that supersedes Nifti1, Nifti2, Analyze...).

**Comment by GaelVaroquaux** [comment]
> As a sidenote, we could support SpatialImage type from nibabel (that
> supersedes Nifti1, Nifti2, Analyze...).

Yes. Agreed.

**Comment by AlexandreAbraham** [comment]
As nibabel functions do not exactly what we do (lazy loading, etc), I close this issue.
