### ISSUE TITLE
Add landscape.io to nilearn

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#492]
See https://github.com/scikit-learn/scikit-learn/commit/9c24e1a120aaf0a4eaa801b0b36db2a8403fc459

**Comment by lesteve** [comment]
Just double-checking: can people see that: https://landscape.io/github/nilearn/nilearn?

If yes I close this issue.

**Comment by AlexandreAbraham** [comment]
I can see it.

**Comment by lesteve** [comment]
> I can see it.

Thanks.

**Comment by GaelVaroquaux** [comment]
> Just double-checking: can people see that:
> https://landscape.io/github/nilearn/ nilearn?

I can see that.

I scikit-learn, the way we have it set up, it adds a report to the PRs,
like travis, which is awesome. It would be great if someone could port
that to nilearn.

**Comment by lesteve** [comment]
> I scikit-learn, the way we have it set up, it adds a report to the PRs, like travis, which is awesome

I think it should be set-up for nilearn too. It doesn't seem to be working very well for scikit-learn at the moment though https://github.com/scikit-learn/scikit-learn/pull/4372#issuecomment-78054010 ...

From a little bit of reading it looks like:

1. the landscape report is done as a comment. When the same thing was enabled for coveralls, people were pretty annoyed by the automatic emails that ensued each time somebody pushed into a PR branch.
2. there is a landscape.io github issue about using the github status API which is far less intrusive but not sure how likely this is going to happen in the near future.

**Comment by GaelVaroquaux** [comment]
>  2. there is a landscape.io github issue about using the github status API
>     which is far less intrusive but not sure how likely this is going to happen
>     in the near future.

OK, let's wait then.

**Comment by amueller** [comment]
We'll see how annoying the comments get once they are enabled ;)

**Comment by GaelVaroquaux** [comment]
> We'll see how annoying the comments get once they are enabled ;)

Hey Andy, you are here too :). You are everywhere :)

**Comment by amueller** [comment]
Currently I feel the bot is having too many issues to be very useful.

**Comment by GaelVaroquaux** [comment]
> Currently I feel the bot is having too many issues to be very useful.

It's noisy indeed.

**Comment by lesteve** [comment]
> Currently I feel the bot is having too many issues to be very useful.

Thanks for letting us know. FWIW the bot comments have been disabled for nilearn a few days ago.
