### ISSUE TITLE
[BUG] errors when loading filepaths with forward slashes

### ISSUE THREAD

**Issue by paulcbogdan** [nilearn/nilearn#4922]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating system

- [ ] Linux
- [ ] Mac
- [x] Windows

### Operating system version

I can't load my images due to a change in #4620: [[STY] Resolve several PTH issues (](https://github.com/nilearn/nilearn/commit/a8511a24b4525003c4b9df252d8c7174067664a2)https://github.com/nilearn/nilearn/pull/4620[)](https://github.com/nilearn/nilearn/commit/a8511a24b4525003c4b9df252d8c7174067664a2)

At that point, this line of `niimg_conversions.py`: `filenames = sorted(glob.glob(os.path.expanduser(niimg)))` was changed to `filenames = sorted(glob.glob(str(Path(niimg).expanduser())))`

On my Windows 11 PC, on Python 3.12, and with the current version of NiLearn (0.11.0), that change causes an error here:

```Python
from nilearn import image
fps = [r'C:/test.nii']
image.load_img(fps)
```

Error: 
```
File "...\Lib\site-packages\nilearn\_utils\niimg_conversions.py", line 301, in check_niimg
    raise ValueError(f"File not found: '{niimg}'")
ValueError: File not found: 'C:/test.nii'
```

However, I do not get an error here:

```Python
from nilearn import image
fps = [r'C:\test.nii']
image.load_img(fps)
```

When I go into `niimg_conversions.py`, and I change the line as I mentioned above (`filenames = sorted(glob.glob(str(Path(niimg).expanduser())))`) to now be:

```Python
import os
filenames = sorted(glob.glob(os.path.expanduser(niimg)))
```

I no longer get any error for either slash format.

I assume this wasn't intentional, and NiLearn should work with either slash format? I don't know anything about `glob` or why one of the lines works while the other doesn't. I tried looking up my glob version but I don't see anything listed with conda, presumably because this is now a default part of the Python library? Either way, I'm happy to share more info about my setup.

### Python version

- [ ] 3.13
- [x] 3.12
- [ ] 3.11
- [ ] 3.10
- [ ] 3.9

### nilearn version

0.11.0

### Expected behavior

To load my image

### Current behavior & error messages

An error!

**Comment by Remi-Gau** [comment]
> assume this wasn't intentional, and NiLearn should work with either slash format? 

Thanks for the report

Pretty sure I messed that one up.

> I don't know anything about `glob` or why one of the lines works while the other doesn't. I tried looking up my glob version but I don't see anything listed with conda, presumably because this is now a default part of the Python library?

Yeah glob is part of the standard library.

We got another bug that I would file as major so we will try to push bug fix release rather sooner than later.

**Comment by paulcbogdan** [comment]
Thanks, a fix might be to update below `elif [niimg] == filenames` to `elif [str(Path(niimg))] == filenames`

**Comment by Remi-Gau** [comment]
looking into this I am running into another bug:

check_niimg seems unable to handle "user home shortcuts" `~/` eventhough the code clearly suggests it should be able to.

```python
def test_check_niimg_user_expand(img_3d_mni):
    """Test"""
    filename = Path("~/test.nii")
    img_3d_mni.to_filename(filename.expanduser())
    assert filename.expanduser().exists()
    assert_array_equal(
        get_data(check_niimg(filename)),
        get_data(img_3d_mni),
    )    
```

this test fails on main at the moment.

**Comment by Remi-Gau** [comment]
working on this and there is something I don't understand

here is the bit of code that fails:

https://github.com/nilearn/nilearn/blob/04be71faa15194e41e9455ca87d3b4427580ff42/nilearn/_utils/niimg_conversions.py#L277-L302

You are getting an error at line 301 but you introduce your fix in an if block that is not entered given the error you have:

```python
if isinstance(niimg, str):
    if wildcards and ni.EXPAND_PATH_WILDCARDS:
        # Ascending sorting + expand user path
        filenames = sorted(glob.glob(str(Path(niimg).expanduser())))  # <--- FIX HERE

        # processing filenames matching globbing expression
        if len(filenames) >= 1 and glob.has_magic(niimg):
            niimg = filenames  # iterable case
        # niimg is an existing filename
        elif [niimg] == filenames:
            niimg = filenames[0]
        # No files found by glob
        elif glob.has_magic(niimg):
            # No files matching the glob expression, warn the user
            message = (
                "No files matching the entered niimg expression: "
                f"'{niimg}'.\n You may have left wildcards usage "
                "activated: please set the global constant "
                "'nilearn.EXPAND_PATH_WILDCARDS' to False to "
                "deactivate this behavior."
            )
            raise ValueError(message)
        else:
            raise ValueError(f"File not found: '{niimg}'")
    elif not Path(niimg).exists():
        raise ValueError(f"File not found: '{niimg}'") # <--- ERROR HERE
```

shorter version for readability


```python
if isinstance(niimg, str):
    if wildcards and ni.EXPAND_PATH_WILDCARDS:
        # Ascending sorting + expand user path
        filenames = sorted(glob.glob(str(Path(niimg).expanduser())))  # <--- FIX HERE

        ...
        
    elif not Path(niimg).exists():
        raise ValueError(f"File not found: '{niimg}'") # <--- ERROR HERE
```

**Comment by Remi-Gau** [comment]
so in short I am not sure how your fix prevented this error: I must be missing something

**Comment by Remi-Gau** [comment]
FYI: I am working on this from this branch https://github.com/Remi-Gau/nilearn/tree/fix/4922

I don't have access to a windows machine yet to make debugging easier so in case you can try testing from my branch

```python
pip install git+https://github.com/Remi-Gau/nilearn@fix/4922 
```

**Comment by paulcbogdan** [comment]
Sorry if I was unclear, the error comes from the higher one. I think you were referring to line 302  in the bit of code you sent but my "file not found error" was in line 300. As in, the "(A)" here is the error, so the fix (`            # elif [str(Path(niimg))] == filenames:`) is within it:

```Python
    if isinstance(niimg, str):
        if wildcards and ni.EXPAND_PATH_WILDCARDS:
            # Ascending sorting + expand user path
            # filenames = sorted(glob.glob(str(Path(niimg).expanduser())))
            # import os
            # filenames = sorted(glob.glob(os.path.expanduser(niimg)))
            filenames = sorted(glob.glob(str(Path(niimg).expanduser())))
            # processing filenames matching globbing expression
            if len(filenames) >= 1 and glob.has_magic(niimg):
                niimg = filenames  # iterable case
            # niimg is an existing filename
            # elif [str(Path(niimg))] == filenames:
            #     niimg = filenames[0]
            elif [niimg] == filenames:
                niimg = filenames[0]
            # No files found by glob
            elif glob.has_magic(niimg):
                # No files matching the glob expression, warn the user
                message = (
                    "No files matching the entered niimg expression: "
                    f"'{niimg}'.\n You may have left wildcards usage "
                    "activated: please set the global constant "
                    "'nilearn.EXPAND_PATH_WILDCARDS' to False to "
                    "deactivate this behavior."
                )
                raise ValueError(message)
            else:
                raise ValueError(f"File not found (A): '{niimg}'")
        elif not Path(niimg).exists():
            raise ValueError(f"File not found (B): '{niimg}'")
```

**Comment by paulcbogdan** [comment]
Sorry about my initial post saying line 301. I must've added a line to the code before I reran it to generate the message. It should be line 300

**Comment by paulcbogdan** [comment]
When I use the code here (https://github.com/Remi-Gau/nilearn/tree/fix/4922), the image loads fine for me

```Python
from nilearn import image
from pathlib import Path

fps = [r'C:/test.nii',
       r'C:\test.nii',
       Path(r'C:/test.nii'),
       Path(r'C:\test.nii'),
       ]
for fp in fps:
    image.load_img(fp)
```

No error

**Comment by Remi-Gau** [comment]
cool so then this must have been some path expansion issue!!!
