### ISSUE TITLE
Update Niimage documentation to say that we accept any SpatialImage

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#495]
Related to #478. Must be done after #483.

**Comment by GaelVaroquaux** [comment]
Care should be taken addressing this issue: this is nibabel jargon that will not mean anything to 99% of users.  We should not let this make our docs harder to understand or scare users.

**Comment by AlexandreAbraham** [comment]
I think that we should say to the users that we accept any format read by nibabel. The, in a (wiki) developper page, precise that any type derived from SpatialImage is accepted. We could also enlarge that to any type compatible with spatialimage (get_data, get_affine, get_header, to_filename...).

**Comment by GaelVaroquaux** [comment]
> I think that we should say to the users that we accept any format read by
> nibabel.

Just say 'formats read by nibabel' without 'any'. That way it is vague.
In a footnote be more precise.

**Comment by AlexandreAbraham** [comment]
Since we don't really know if we accept all formats, I suggest that we stick to Nifti1Image for the moment. See #579 for further developments.
