### ISSUE TITLE
csf/wm confounds with nilearn

### ISSUE THREAD

**Issue by juhuntenburg** [nilearn/nilearn#496]
Complementary to image.high_variance_confounds, is there a nilearn way to extract components most descriptive of csf/wm signal (respective masks provided)?

**Comment by GaelVaroquaux** [comment]
I would use the NiftiMapsMasker or NiftiLabelsMasker depending on whether
you have probabilistic segmentations or hard masks to describe csf + wm.

**Comment by AlexandreAbraham** [comment]
What are you trying to do exactly? The solution provided by Gael will give you the mean of the signal in the wm/csf masks. If you want to consider them and regress them out, then you should use a NiftiMasker to mask WM (resp. CSF) data ans then use ` image.high_variance_confounds`. Also, it is better to have your own WM/CSF masks, but if you don't, you can use `datasets.fetch_icbm152_2009` to generic ones.

**Comment by juhuntenburg** [comment]
Thanks for the quick replies! Yes, I want to use the wm and csf signal as confound regressors, but also the highest variance signal (similar to both acompcor and tcompcor in Behzadi 2007). So you would just run image.high_variance_confounds once on the unmasked data and then again on only wm/csf regions?

**Comment by AlexandreAbraham** [comment]
Yes. You should mask your data using a WM mask, extract hv confounds on it and use them as confounds on your data extracted full brain. Feel free to close the issue if you think that you had the answer to your question ;)

**Comment by juhuntenburg** [comment]
Thanks, but not sure if I understand you right: my question is whether it makes sense to extract hv confounds both on the complete data (similart to tcompcor) and additionally on the wm/csf masked data (similar to acompcor)? But I admit this might not strictly be a nilearn question..

**Comment by GaelVaroquaux** [comment]
Hi Julia,

I must admit that I have no strong opinion. In a way, it is not
meaningless to extract also on a WM mask. But in another way, compcorr on
the full image should also get these signals.

**Comment by juhuntenburg** [comment]
Hi Gael, yes, that is basically what I was thinking about, too. Also, that I would have twice as many regressors if I extract e.g. 5 components without and with mask. But I see there is probably no definite answer. 

Thanks for your helpful comments, both of you, though!
