### ISSUE TITLE
plotting: Transparency / thresholding broken in master

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#509]
In master transparency or thresholding of statistical maps is now broken (I've checked: this is not a problem of my matplotlib version: it works on the doc_rework branch).

One example is the plot_demo_plotting.py example that now gives
![plotting_broken](https://cloud.githubusercontent.com/assets/208217/6738200/b429ff02-ce70-11e4-9185-d8b24fa4a3b0.png)
To be compared to
http://nilearn.github.io/auto_examples/manipulating_visualizing/plot_demo_plotting.html

**Comment by AlexandreAbraham** [comment]
Again, cannot reproduce this one. Given this issue and the other you opened, I'm afraid that this is due to your particular configuration. Can you post the content of a `pip freeze`?

**Comment by AlexandreAbraham** [comment]
Reproduced on Mehdi's box.

**Comment by AlexandreAbraham** [comment]
My fault apparently, investigating.

**Comment by AlexandreAbraham** [comment]
Fixed by bb2de3e612022bcae0c4959cc739badfa4bb7540
