### ISSUE TITLE
plotting with vmax=nan crashes with a useless error

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#519]
We should handle this gracefully: warn, but still run as if no vmax was passed.

**Comment by banilo** [comment]
I can take care of that.

**Comment by GaelVaroquaux** [comment]
> I can take care of that.

Thanks!

**Comment by AlexandreAbraham** [comment]
Well, you had what you deserved :P

**Comment by AlexandreAbraham** [comment]
What is the usecase? Your tried to compute vmax yourself and your image had nans?

**Comment by GaelVaroquaux** [comment]
> What is the usecase? Your tried to compute vmax yourself and your image had
> nans?

Not me, but the student with whom I am working did that.

**Comment by AlexandreAbraham** [comment]
OK. Do you think that the error message should advise the user to use `np.nan_max` rather than `np.max`?

**Comment by GaelVaroquaux** [comment]
> OK. Do you think that the error message should advise the user to use
> np.nan_max rather than np.max?

Yes, but I'd like to not have crasher, because sometimes there is a nan
in the data, and everything crashes which is a problem when you are
trying to analyse data.

**Comment by GaelVaroquaux** [comment]
> Closed #519 via #520.

Thank you team!!!
