### ISSUE TITLE
No documentation about vmax (was: upper limit on image)

### ISSUE THREAD

**Issue by satra** [nilearn/nilearn#524]
the plotting routines should allow a vmin/vmax like option. currently only the threshold acts as vmin.

use case:

one is plotting a set of maps. without being able to set the limits, the maps cannot be visually compared.

**Comment by satra** [comment]
turns out i can pass vmax - it's not noted in the documentation anywhere.

**Comment by GaelVaroquaux** [comment]
> it's not noted in the documentation anywhere.

I'll reopen the issue for this reason. I am wondering if we should not
add it explicitely, rather than having it in the hidden kwargs.

**Comment by AlexandreAbraham** [comment]
I think we should fix this problem ASAP since other people reported it.

**Comment by lesteve** [comment]
Unfortunate timing: just saw that it has been assigned to Kamalaker but I actually started working on it this morning ...

**Comment by AlexandreAbraham** [comment]
So assign it to yourself!
