### ISSUE TITLE
Massive plot_stat_map calls crash a MacBookPro

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#526]
As a tentative bug report: I used a combination of plot_stat_map() + plt.subplots() + plt.savefig() several thousand times in a script. This used up several hundred MB of disk space and slowed my computer down until crash. Commenting out just the plotting-loop solved all these problems.

Is it possible that plot_stat_map does not cleanup some figure handles or something like that?

**Comment by GaelVaroquaux** [comment]
Yes it does not. As stated in the documentation, you need to close the figure when you are done with it. This is done automatically when you specify an output_file argument.

**Comment by AlexandreAbraham** [comment]
Yes. matplotlib does not release the memory of the plot if you don't close it. call pylab.close() or matplotlib.pyplot.close() after saving your figure. Or use the option in plot_stat_map to directly save in a file.

**Comment by banilo** [comment]
Thanks @Galex !

**Comment by AlexandreAbraham** [comment]
Nota: check your logs but marplotlib usually output a warning xhen mre than 20 figures are opened at the same time.
