### ISSUE TITLE
Fix datasets.fetch_harvard_oxford quirks

### ISSUE THREAD

**Issue by lesteve** [nilearn/nilearn#540]
Two quirks I just spottted:

* it does not return a Bunch in contrary to all the other fetch_ functions but a tuple
* it does not use the standard nilearn_data location to fetch the data but the current working directory instead

**Comment by AlexandreAbraham** [comment]
> it does not return a Bunch in contrary to all the other fetch_ functions but a tuple

Yes, I've seen that already

> it does not use the standard nilearn_data location to fetch the data but the current working directory instead

Works for me. It may be due to your environment configuration. Can you download with verbosity enabled so that we can have more information?

**Comment by GaelVaroquaux** [comment]
>   • it does not return a Bunch in contrary to all the other fetch_ functions
>     but a tuple

I agree that this should be changed.

**Comment by AlexandreAbraham** [comment]
Please refer to #486 for further comments on this.
