### ISSUE TITLE
add matrix plotting function

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#547]
Hi,

Can we add a function for plotting a connectivity matrix with the regions labels as the one in the example connectivity/plot_signal_extraction.html and with a colorbar ? I'm wondering if we can not put this function in _utils or plotting.

**Comment by AlexandreAbraham** [comment]
It is not planned for the moment. In the meantime, you can use seaborn: http://stanford.edu/~mwaskom/software/seaborn/examples/network_correlations.html

**Comment by AlexandreAbraham** [comment]
I you have one function, you can submit it to [nilearn_sandbox](https://github.com/nilearn/nilearn_sandbox).

**Comment by AlexandreAbraham** [comment]
No plan to do this for the moment, I close it.

**Comment by GaelVaroquaux** [comment]
I was actually thinking that we were getting closer to being able to do
that, and wondering whether it should be in the week's sprint :)

**Comment by AlexandreAbraham** [comment]
OK, reopened then !

**Comment by KamalakerDadi** [comment]
Any idea about placing this function ```plot_matrix``` ? May be in ```img_plotting.py``` ?

**Comment by AlexandreAbraham** [comment]
a matrix is not an img, si it would not fit. Maybe a new module dedicated to connectome plotting ? There would be some other valuable viz to add in there, like the circle viz made by Elvis.

**Comment by KamalakerDadi** [comment]
Isn't this issue talking about a simple matrix plotting function ? You mean @dohmatob is already on this ?

**Comment by AlexandreAbraham** [comment]
This issue is talking about a connectivity matrix plotting function. Ie, a connectome. Another way to visualize it is with the circle diagrame like this:

![connectome](https://cloud.githubusercontent.com/assets/1647301/17324459/e4002104-58a6-11e6-92ce-c12f7d87b84d.jpg)

Given that both are representation of a connectome, I think that we can put them altogether.

**Comment by KamalakerDadi** [comment]
I thought this issue only mentions a simple matrix plotting like in here as you posted http://stanford.edu/~mwaskom/software/seaborn/examples/network_correlations.html

**Comment by AlexandreAbraham** [comment]
What other matrices do we have to plot? Given the focus of nilearn, we should target the usage of the plotting functions.

Also, the description states:

> Can we add a function for plotting **a connectivity matrix** with the regions labels

I am not against having a general matrix plotting function. I am just wondering if it is useful.

**Comment by KamalakerDadi** [comment]
description also explicitly stated about example.

**Comment by GaelVaroquaux** [comment]
> Any idea about placing this function plot_matrix ? May be in img_plotting.py ?

Probably in a new file.

**Comment by GaelVaroquaux** [comment]
I've uploaded some code that I have used in the past for that:
https://gist.github.com/GaelVaroquaux/872679a0972ee1afc759e5af130fc02b

**Comment by KamalakerDadi** [comment]
>I've uploaded some code that I have used in the past for that:

This code is much better than mine.

**Comment by KamalakerDadi** [comment]
Closing this one in #1408
