### ISSUE TITLE
glassbrain: correspondence between image values and colormap

### ISSUE THREAD

**Issue by f4bry** [nilearn/nilearn#548]
Hi all,

I am trying to plot a map with values going from 0 to 1 (in theory), in a glass brain. 0 should be blue and 1 red. My problem is that the max of this map is 0.8 and it is plotted as maximum, so red. I would like to keep the color range fix and, for example, to plot values equal to 0.8 in orange, even if 1 values doesn't really exist in this particular map. The reason is because I have other maps where I want the 1s appearing in red.
Is this possible?

Thank you in advance,
fab

**Comment by AlexandreAbraham** [comment]
Try `vmax=1.`. Does that fix your problem?

**Comment by f4bry** [comment]
Seems so! Thank you!
fab
