### ISSUE TITLE
Doc does not build

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#554]
Am I the only one?

```
Exception occurred:
  File "/home/aa013911/work/nilearn/doc/sphinxext/sphinxgallery/docs_resolv.py", line 348, in embed_code_links
    gallery_dir = os.path.join(app.builder.srcdir, gallery_conf['gallery_dir'])
KeyError: 'gallery_dir'
The full traceback has been saved in /tmp/sphinx-err-sePU7r.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
```

**Comment by lesteve** [comment]
Just launched a clean doc generation from master, will let you know.

Does your error happens after or before the examples are run ?

**Comment by AlexandreAbraham** [comment]
I've done a noplot, so no build of examples.

**Comment by lesteve** [comment]
I get the same error with `cd doc && make html-noplot`

**Comment by lesteve** [comment]
Looks like this is a bug related to noplot, app.config.sphinxgallery_conf is not properly updated when plot_gallery is False.

@Titan-C, I think the only thing is to move the `if not plot_gallery: return` after this [line](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinxgallery/gen_gallery.py#L25)

**Comment by GaelVaroquaux** [comment]
I get the same problem. We need to address this fast: currently master is somewhat broken.

**Comment by lesteve** [comment]
This has been fixed in sphinx-gallery master [here](https://github.com/sphinx-gallery/sphinx-gallery/commit/6e944e29e8b23a85025b6bf44ebb6d39907d1875). 

I was thinking we could have a 0.9 sphinx-gallery release to fix this.

cc @Titan-C.

**Comment by AlexandreAbraham** [comment]
Is it doable fast enough? Because I am not against a quickfix in our copy of sphinx in the meantime.

**Comment by Titan-C** [comment]
Done in PR #559 and available dev-release in github and pypi.

**Comment by GaelVaroquaux** [comment]
Thanks Oscar!
