### ISSUE TITLE
Perceptually improved colormap

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#555]
A while ago, I implemented in matplotlib perceptually improved colormaps from this website: https://mycarta.wordpress.com/color-palettes/

I find some of them quite useful. Do you think it would be interesting to add them in nilearn?

(Here they are with they lightness represented in grayscale below)

![cubicl](https://cloud.githubusercontent.com/assets/1647301/7249542/53ac1420-e81b-11e4-84d6-c2b34c2b949c.png)
![cubicyf](https://cloud.githubusercontent.com/assets/1647301/7249546/53ccd5ac-e81b-11e4-8fab-9e76d54bd90c.png)
![isoaz](https://cloud.githubusercontent.com/assets/1647301/7249547/53cce150-e81b-11e4-9196-32f1ac07c661.png)
![isoaz180](https://cloud.githubusercontent.com/assets/1647301/7249548/53cd3434-e81b-11e4-9683-11ace5fdedcf.png)
![isol](https://cloud.githubusercontent.com/assets/1647301/7249544/53ca3cf2-e81b-11e4-8f78-5099013637bd.png)
![linearl](https://cloud.githubusercontent.com/assets/1647301/7249545/53ccc0e4-e81b-11e4-9105-f19051c1d7d3.png)
![linlhot](https://cloud.githubusercontent.com/assets/1647301/7249543/53bdbf7c-e81b-11e4-9ded-c8f779726755.png)
![swtth](https://cloud.githubusercontent.com/assets/1647301/7249549/53cf2f14-e81b-11e4-9eea-a6b387e5e06d.png)

**Comment by GaelVaroquaux** [comment]
I think that this should be addressed in matplotlib, and not in nilearn.
The only reason that we have colormaps in nilearn is because we needed bivalued colormaps with black in the center. Maybe we should ask matplotlib if they are interested in having these, and we could move them upstream.

**Comment by banilo** [comment]
Those look nice :)

**Comment by GaelVaroquaux** [comment]
> Those look nice :)

Yes, but feature creep.

**Comment by banilo** [comment]
> feature creep

Cool, I did not know this expression.

**Comment by AlexandreAbraham** [comment]
OK, closing!
