### ISSUE TITLE
masker.transform() on 4d image crashes computer

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#560]
I tried to use NiftiMasker.transform() on a 3600-sample 4d nifti image (~6GB of memory). This does freeze my computer (16GB memory) when trying to apply transform() on the full 4d image, yet does not when transforming individual 3d images of the 4d nifti image successively. Mask and 4d nifti are in the same space (i.e., no resampling). Sorry for the anecdotal evidence.

Might there be a memory issue in NiftiMasker.transform()?

**Comment by AlexandreAbraham** [comment]
My guess is that NiftiMasker.transform() will force loading of the data in memory instead of using memmapped data, blowing up your memory.

**Comment by GaelVaroquaux** [comment]
I am sorry. My crystal ball is not working currently. I'll try to call
the 33 to have it fixed.

**Comment by banilo** [comment]
Until the crystal ball is working again, I could provide a tar ball with the used files to reproduce...

**Comment by GaelVaroquaux** [comment]
> Until the crystal ball is working again, I could provide a tar ball with the
> used files to reproduce...

And code

**Comment by banilo** [comment]
Here is code + data.

https://dl.dropboxusercontent.com/u/4403154/mtransform.zip

Hope it helps

**Comment by AlexandreAbraham** [comment]
Should be fixed by #614. Can you try?

**Comment by AlexandreAbraham** [comment]
Superseded by #715. Closing this one as the other has more discussions.
