### ISSUE TITLE
Expose new_img_like

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#566]
I find myself using new_img_like (good job @AlexandreAbraham). I suggest that we expose it in image. 

Also, I suggest that we make "affine" optional in it: by default, the affine of the reference image would be used and we would check that the shapes of the data match.

Finally, I suggest that we change the signature to (data, ref_img, affine=None, ...), ie inverse the position of ref_img and data compared to the current situation. I find that it makes more sense.

If people agree with those changes, I am offering to implement them.

**Comment by eickenberg** [comment]
For reference https://github.com/nilearn/nilearn/blob/master/nilearn/_utils/niimg.py#L57

+1 for exposing. Should take into account  #380 as best as possible.

However, to me the signature should rather stay as it is (or even be `new_img_like(ref_img, data=None, affine=None, copy_header=)`, but I am not sure whether this default is useful in any way). The command reads like a phrase: `new_img_like` *what*, so the *what* should be the first argument.

**Comment by GaelVaroquaux** [comment]
> However, to me the signature should rather stay as it is (or even be
> new_img_like(ref_img, data=None, affine=None, copy_header=), but I am not sure
> whether this default is useful in any way). The command reads like a phrase:
> new_img_like what, so the what should be the first argument.

OK.

**Comment by AlexandreAbraham** [comment]
> I find myself using new_img_like

Me too.

> I suggest that we make "affine" optional in it

Same remark, I was planning to do a PR about that later.

> I suggest that we change the signature

I prefer to keep data and affine next to each other if possible, makes more sense to me. If we are to change the signature, I suggest that we change the name because I think of this function call as a sentence "I want a new image like `param1` containing data `param2`". And it would make less sense the other way around.

**Comment by lesteve** [comment]
> new_img_like what, so the what should be the first argument.

Agreed.

**Comment by AlexandreAbraham** [comment]
Didn't read Michael's comment first, sorry for repetition.

**Comment by AlexandreAbraham** [comment]
I think that this issue is not very time-consuming and people are strongly asking for it. When do you plan to do the PR?

**Comment by GaelVaroquaux** [comment]
> I think that this issue is not very time-consuming and people are strongly
> asking for it. When do you plan to do the PR?

It's not going to happen any time soon. I have a lot of other urgent
matters to attend to.

**Comment by AlexandreAbraham** [comment]
Should we delegate to somebody else, @KamalakerDadi for example ?

**Comment by AlexandreAbraham** [comment]
@banilo, would you like to take care of that?

**Comment by banilo** [comment]
Sure, I would be happy to take care of it, if nobody objects.

2015-05-18 11:45 GMT+02:00 Alexandre Abraham <notifications@github.com>:

> @banilo <https://github.com/banilo>, would you like to take care of that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/issues/566#issuecomment-102997841>.
>



-- 
Viele Grüße,
Danilo

**Comment by GaelVaroquaux** [comment]
> Sure, I would be happy to take care of it, if nobody objects.

Go for it!

**Comment by AlexandreAbraham** [comment]
You are now officially assigned :rocket:

**Comment by banilo** [comment]
This issue should essentially have been addressed.
