### ISSUE TITLE
Remove MultiNiftiMasker

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#569]
Following the introduction of `iter_img`, the MultiNiftiMasker is even less useful than it used to be. It has a low added value and high maintenance cost as we should make one for each of the existing maskers.

**Comment by dohmatob** [comment]
+1000

On Mon, May 4, 2015 at 10:30 AM, Alexandre Abraham <notifications@github.com
> wrote:

> Following the introduction of iter_img, the MultiNiftiMasker is even less
> useful than it used to be. It has a low added value and high maintenance
> cost as we should make one for each of the existing maskers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/issues/569>.
>



-- 
DED

**Comment by banilo** [comment]
So everybody ok with me removing this class from nilearn?

**Comment by arthurmensch** [comment]
I am using `MultiNiftiMasker` to load large datasets, it is especially useful as it provides seemless parallelization. Should we make it an option and add parallelization to NiftiMasker ?

**Comment by banilo** [comment]
> I am using MultiNiftiMasker to load large datasets, it is especially useful as it provides seemless parallelization. Should we make it an option in NiftiMasker and add parallelization to NiftiMasker ?

Sounds good. Or even in some broader framework, add an iter_img-ish function that helps perform various image manipulations in a multi-process context...?
