### ISSUE TITLE
Flip signs of components in CanICA

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#570]
We should have a heuristic that flips the sign of components in CanICA to have more positive values than negative values, for instance by making sure that the largest value is positive.

**Comment by dohmatob** [comment]
This issue was brought to my attention by jennifer (and so she has test data). I can roll a quick heuristic fix.

**Comment by GaelVaroquaux** [comment]
> This issue was brought to my attention by jennifer (and so she has test data).
> I can roll a quick heuristic fix.

It would be awesome. It's a question of doing something like:

<pre>
for component in self.components_:
   if component.max() < -component.min():
      component *= -1
</pre>

With an associated test

**Comment by eickenberg** [comment]
Isn't there a generic fix for this in scikit-learn? I remember Kyle having
some issues with that for incrementalPCA

**Comment by eickenberg** [comment]
sklearn.utils.extmath.svd_flip

used here
https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/decomposition/incremental_pca.py#L219

The question is whether it gives the right results with respect to what
Gael proposes, which looks like it is neuro-imaging-informed.

**Comment by eickenberg** [comment]
OK it does the same thing https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/utils/extmath.py#L533

Except that it takes both sides of the SVD. It may be able to take `1` as the input for `v` in which case it would be reusable. Otherwise it will have to be cherry-picked.

**Comment by dohmatob** [comment]
Seems to me the manual solution proposed by @GaelVaroquaux  is more transparent. Note also that the values of the components are not (and should not be) open to interpretation, and the issue raise here is just for visualization purposes.

**Comment by eickenberg** [comment]
I have no opinion. It was just fyi

**Comment by dohmatob** [comment]
OK, I've just checked with @jennifer and the PR produces the expected outcome.

![comp_2](https://cloud.githubusercontent.com/assets/634068/7516029/76d6f0a6-f4cc-11e4-8bb3-85b0f8f89c5a.png)

Without the PR, the signs where flipped and the DMN appeared de-activated.

**Comment by GaelVaroquaux** [comment]
Forgive me for being stubborn, but the fact that it works for the DMN is not a strong argument.

I would really like to stress that the interpretation of the max heuristic is more clear than that of the sum. In particular, take a network with only one small blob, the sum will be fragile: the background will be contributing more to the decision than the blob. This argument is based on a long experience of running ICA and related algorithms on fMRI.

I'd really like the max heuristic, as mentioned in the description of the issue, rather than the sum heuristic.

**Comment by eickenberg** [comment]
https://github.com/nilearn/nilearn/pull/571/files#diff-02bccf8e53c6acb92641f710373ebf63R191

this looks like `max` to me

**Comment by GaelVaroquaux** [comment]
Oops! Please forgive me.

**Comment by dohmatob** [comment]
Yes, indeed the change from `sum` to `max` has already been made, a few days ago (with appropriate commit messages)

@GaelVaroquaux: The update about the DMN was just meant to show that the PR solves the problem which triggered the issue in the first place...

**Comment by GaelVaroquaux** [comment]
> Yes, indeed the change from sum to max has already been made, a few days ago
> (with appropriate commit messages)

Yes, my infinit apologies. This was a complete brain fart.

**Comment by dohmatob** [comment]
No offence taken :)

**Comment by AlexandreAbraham** [comment]
Fixed by #571

**Comment by GaelVaroquaux** [comment]
Hey @dohmatob :

Thanks a lot, the CanICA example now looks much better:
http://nilearn.github.io/auto_examples/connectivity/plot_canica_resting_state.html

**Comment by dohmatob** [comment]
Nice :)

On Tue, May 12, 2015 at 11:48 AM, Gael Varoquaux <notifications@github.com>
wrote:

> Hey @dohmatob <https://github.com/dohmatob> :
>
> Thanks a lot, the CanICA example now looks much better:
>
> http://nilearn.github.io/auto_examples/connectivity/plot_canica_resting_state.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/issues/570#issuecomment-101217292>.
>



-- 
DED
