### ISSUE TITLE
[ENH] add auto-binarization option to _load_mask_img()

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#572]
Simply put, I find myself converting non-binary masks to binary masks all the time. An addition option to do this automatically would be nice.

**Comment by AlexandreAbraham** [comment]
Additional detail: this PR concerns masks for which np.unique(mask) > 2.

**Comment by AlexandreAbraham** [comment]
I think that what you are looking for is `compute_epi_mask`.

**Comment by AlexandreAbraham** [comment]
Closing as what you are looking for is in another function.
