### ISSUE TITLE
Create a wikipedia page for nilearn

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#586]
And reference it in http://en.wikipedia.org/wiki/List_of_functional_connectivity_software and in http://en.wikipedia.org/wiki/List_of_neuroimaging_software.

**Comment by GaelVaroquaux** [comment]
I am not sure it is worth creating a wikipedia page. I would just add a
reference on the pages on neuroimaging software.

**Comment by AlexandreAbraham** [comment]
For me, it is a way to look more "serious" (even if the page is small) and it is the only way to get a link to the website.

**Comment by AlexandreAbraham** [comment]
Page not created but nilearn referenced in the software lists.

**Comment by bthirion** [comment]
Thx @AlexandreAbraham

**Comment by GaelVaroquaux** [comment]
Thank you! Closing the issue.

**Comment by AlexandreAbraham** [comment]
No problem, I wanted to get rid of these annoying Wikipedia tabs in my browser ;).
