### ISSUE TITLE
Functional connectome tutorial prose does not match code

### ISSUE THREAD

**Issue by mwaskom** [nilearn/nilearn#594]
Just browsing this tutorial: http://nilearn.github.io/connectivity/functional_connectomes.html#brain-parcellations

In section 3.1.1.1, the prose says "For instance to retrieve the Yeo 2011 cortical parcelation into 17 regions, with a thick cortical model:"

but the code is

```python
from nilearn import datasets
atlas_filename, labels = datasets.fetch_harvard_oxford('cort-maxprob-thr25-2mm')
```

**Comment by GaelVaroquaux** [comment]
:). Good catch. We need to fix that. Please keep on sending anything else that you find.

**Comment by GaelVaroquaux** [comment]
Fixed
