### ISSUE TITLE
add explicit plotting argument for upper color bound (instead of vmax in kwargs)

### ISSUE THREAD

**Issue by tyarkoni** [nilearn/nilearn#596]
The plotting functions take a threshold argument, but don't provide an explicit way to set an upper bound on the color range. This is useful when, for example, one wants to display multiple images on the same scale. I might be missing some other way to do this, but in any case, since the plotting functions pass kwargs to imshow, it's easy to do by setting the vmax. I wonder if this would be worth turning into an explicit argument in plotting calls? Users who aren't familiar with the imshow API might otherwise think there's no way to limit the range, and it seems important enough to make explicit. Maybe via a range argument that takes a tuple of (min, max)? Then min could simply be aliased to threshold and max to vmax.

**Comment by eickenberg** [comment]
What version are you on? And which specific functions are you using?

Because this issue or something very related was raised here
https://github.com/nilearn/nilearn/issues/524
and adressed with this
https://github.com/nilearn/nilearn/pull/562

Could you check if the arguments appear when you update?

**Comment by tyarkoni** [comment]
D'oh, sorry--I searched on 'upper' before posting, but forgot to check closed issues :P

I was running an older version; after upgrading, vmax shows up in the explicit arg list. Thanks!

**Comment by eickenberg** [comment]
:) 

cool, glad it works! And thanks anyway for reporting!
