### ISSUE TITLE
Plotting thresholds are ignored for images whose affine contains a rotation

### ISSUE THREAD

**Issue by mwaskom** [nilearn/nilearn#599]
I've run into an issue trying to use nilearn to visualize data in native space. This came up when trying to plot ROIs:

```python
plot_roi(roi_img, epi_img)
```
![4jxsfhcftoutz on44aeto5 amrliyfontmfmzgztu1pwycbeokebeeliotdtslqgp4eqqgghlwwnbkiiiyquguejqgghhbscngzcccgefijgaygeeeikqaobeeiiiywg0uaiiysqqtboiiqqqkghadqqqgghpba0ggghhbbscbonhbbccckejqzcccgefijgaygeeeikqaobeeiiiywg0uaiiysqqtboiiqqqkghadqqqgghpba0gggh](https://cloud.githubusercontent.com/assets/315810/7950342/2d7a5150-094e-11e5-938d-dca4053718fa.png)

(where `roi_img` and `epi_img` are `nibabel.Nifti1Image` objects).

This issue does not appear to occur with the example [haxby data](https://nilearn.github.io/auto_examples/manipulating_visualizing/plot_roi_extraction.html).

Something similar is happening with a continuous statistical map:

```python
plot_stat_map(z_img, epi_img, threshold=9)
```
![nu3t7u8rkyrl bt89cviofaqfqvnxy6pvq4ybgqgjvlw84vps0lkjuljykgtk5 cbxv1dxvbt27p6lkycbgaas6kxsvglfy82d udhx9xexm5li9fruvxrysnj0c5otlyuvzq7ozm6ruwdxaaalac5gabaadliqabaadliqabaadliqabaadliqabaadliqabaadliqabaadliqabaadliqabaadliqabaadliqabaadliqabaadliqaba](https://cloud.githubusercontent.com/assets/315810/7950385/bd969a78-094e-11e5-9a31-d6d7939d7108.png)

I've tracked down the issue to [this line of code](https://github.com/nilearn/nilearn/blob/0.1.3/nilearn/plotting/displays.py#L532). The `img` object that goes into the `reorder_img` function has a masked data array, but the `img` that comes out of it just has a bare float array of 1s and 0s (in the case of the ROI image).

My native space images have a LPS orientation; presumably the mask  information is getting lost somewhere as the data are reordered to RAS. Presumably that step is skipped for the Haxby data, which are already oriented properly, and that is why the examples look fine.

I'm using nilearn 1.3.

**Comment by lesteve** [comment]
Can you provide an example reproducing the problem? It's not entirely obvious to me what the problem is by just looking at the plots. In particular in the plot_stat_map case, it does look like the threshold=9 is applied.

I checked whether `reorder_img` was getting rid of the mask when the input image in in LPS orientation but this doesn't seem to be the case.

```python

import numpy as np
import nibabel as nib

from nilearn import image, plotting

data = np.random.randn(20, 20, 20)
data = np.ma.masked_less(data, 0.)

# This should be LPS hopefully
affine = np.array([[-3., 0., 0., 1.],
                   [0., -3., 0., -2.],
                   [0., 0., 3., 3.],
                   [0., 0., 0., 1.]])
img = nib.Nifti1Image(data, affine)

reordered_img = image.reorder_img(img)

print('Consistent mask:',
      np.sum(data.mask) == np.sum(reordered_img.get_data().mask))

# The plotting seems fine too AFAICS
plotting.plot_stat_map(img, threshold=0.5)

```

**Comment by mwaskom** [comment]
> Can you provide an example reproducing the problem? It's not entirely obvious to me what the problem is by just looking at the plots.

Do you mean the images themselves? Sure I can do that when I get to school. 

> In particular in the plot_stat_map case, it does look like the threshold=9 is applied.

Why do you say that? I would have expected much of the overlay would be transparent (z = 9 is a high threshold) and that we would see the gray colormapped mean epi image in those spots.

> I checked whether reorder_img was getting rid of the mask when the input image in in LPS orientation but this doesn't seem to be the case.

What happens when you make an affine with rotations?

**Comment by lesteve** [comment]
> What happens when you make an affine with rotations?

Good point, I can reproduce the problem, the reordered_img lose the mask for some reason which needs to be elucidated:

```python
import numpy as np
import nibabel as nib

from nilearn import image, plotting

data = np.random.randn(20, 20, 20)
data = np.ma.masked_less(data, 0.)

# matrix with rotation
affine = np.array([[-3., 1., 0., 1.],
                   [-1., -3., 0., -2.],
                   [0., 0., 3., 3.],
                   [0., 0., 0., 1.]])
img = nib.Nifti1Image(data, affine)

reordered_img = image.reorder_img(img, resample='continuous')
print('img data type:', type(img.get_data()))  # numpy.ma.core.MaskedArray
print('reordered_img data type:', type(reordered_img.get_data()))  # numpy.ndarray
```

This seems more related to affine with rotations rather than LPS vs RAS by the way.

**Comment by GaelVaroquaux** [comment]
> This seems more related to affine with rotations rather than LPS vs RAS by the
> way.

It's going to be the resampling.

One thing that we could do would be to move this reordering before we
apply the threshold. The other option is to resample the mask, but that's
going to be ugly (resampling discrete info is not something that I like).

**Comment by lesteve** [comment]
> One thing that we could do would be to move this reordering before we apply the threshold

From a quick look at the code, it does look like it is feasible.

**Comment by mwaskom** [comment]
> One thing that we could do would be to move this reordering before we
apply the threshold.

That sounds like the right order of operations to me, although I am (much) less familiar with the codebase.

**Comment by GaelVaroquaux** [comment]
> That sounds like the right order of operations to me,

Quite clearly. This was an oversight.

G

**Comment by AlexandreAbraham** [comment]
What if the user gives us data that is already masked?

**Comment by GaelVaroquaux** [comment]
> What if the user gives us data that is already masked?

That means trouble! How about a little note saying that in this case (ie
non affine with rotation) we don't support user masks.
