### ISSUE TITLE
image.index_img fails with single element list input

### ISSUE THREAD

**Issue by sanmik** [nilearn/nilearn#601]
dataset object e.g. haxby_dataset["func"] returns a single element list and image.index_img(hb_dataset["func"]) fails with single element list input

**Comment by AlexandreAbraham** [comment]
`index_img` is meant to iterate over one image, not a list of image. `image.index_img(hb.func[0], 0) will work. What do you want to do exactly?

**Comment by GaelVaroquaux** [comment]
> index_img is meant to iterate over one image, not a list of image.
> `image.index_img(hb.func[0], 0) will work. What do you want to do exactly?

I don't think that we dispute that there is a user error. The point is
rather that the error message is quite useless.

**Comment by AlexandreAbraham** [comment]
In fact there is no check of the dimensionality of the first image! I'll do a quickfix.

**Comment by AlexandreAbraham** [comment]
I still think that there was a misuse of the function in the first place. Maybe the doc of `index_img` is not clear enough. After my PR, the error message is: `TypeError: Data must be a 3D Niimg-like object but you provided an image of shape (40, 64, 64, 1452). See http://nilearn.github.io/building_blocks/manipulating_mr_images.html#niimg.`

This is not the best error message but still better than the previous one.

**Comment by GaelVaroquaux** [comment]
Wait. .. This is a very surprising error message. The question is not whether there has been a misuse of the function, but rather that the error message makes it hard to figure things out. 

Gaël
