### ISSUE TITLE
displays.add_edges error : Cannot reorder the axes

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#616]
displays.add_edges used to plot edges of the same image sometimes gives an error
Cannot reorder the axes: the image affine contains rotations

**Comment by banilo** [comment]
See also #368

**Comment by lesteve** [comment]
As discussed with @salma1601 it looks like we need to add a resample_interpolation in the reorder_img call in add_edges.

The only question is whether resample_interpolation='continuous' makes sense for all cases, e.g. how likely is it to call add_edges with a label img (in which case resample_interpolation='nearest' would make sense)?

**Comment by GaelVaroquaux** [comment]
Agreed with @lesteve : we can safely assume that resample interpolation will always be continuous.

**Comment by lesteve** [comment]
Fixed in ab6689a.

**Comment by GaelVaroquaux** [comment]
Stop closing all the issues! Or the only thing left to do for the sprint
will be drinking beers :).

OK, we'll find things.

**Comment by AlexandreAbraham** [comment]
I have plenty of issues to open if you want!

**Comment by GaelVaroquaux** [comment]
> I have plenty of issues to open if you want!

If they are easy, go for it!
