### ISSUE TITLE
Explanation of affine matrix has disappeared from the docs?

### ISSUE THREAD

**Issue by surchs** [nilearn/nilearn#617]
Hey,

I was just looking for the very nice and thorough explanation on affine matrices and how they can be used to resample data that you had on your github.io documentation. It seems that the site has been restructured (very nice btw) and I can no longer find it. Not sure if you know what I am talking about but this was a very good document and I'd be happy if someone could point me to it.

Many thanks,
Seb

**Comment by eickenberg** [comment]
Do you mean this?

http://nilearn.github.io/auto_examples/manipulating_visualizing/plot_affine_transformation.html#example-manipulating-visualizing-plot-affine-transformation-py

**Comment by surchs** [comment]
No. This I found. If I remember right it was about a four page article with
a lot of basics.

**Comment by lesteve** [comment]
Not sure to be honest. I thought it might have disappeared during the doc refactoring by Gaël as you said [here](https://github.com/nilearn/nilearn/pull/483/files) but that doesn't seem to be the case.

I tried to find it on archive.org to no avail. Maybe you can try yourself, especially if you happen to still know the old URL.

**Comment by surchs** [comment]
My apologies, I have confused nilearn with [nibabel](http://nipy.org/nibabel/coordinate_systems.html), probably because of the sphynx format. So nothing disappeared.
