### ISSUE TITLE
Cannot import nilearn on Macos yosemite

### ISSUE THREAD

**Issue by orchid666** [nilearn/nilearn#618]
Basically when i launch ipython and tries to import nilearn i get this:
ImportError: No module named nilearn

Note that i can import nipy, nibabel and sklearn.
Note also that i have this issue on my lab computer with several users (I have admin privileges) but i dont have this issue on my personal computer on which im the only user (Also on MacOS)

Any ideas?

**Comment by eickenberg** [comment]
by which method did you install it?

**Comment by orchid666** [comment]
I used 
sudo pip install -U --user nilearn

install went well as far as i can tell.

**Comment by AlexandreAbraham** [comment]
`sudo` and `--user` should not be used together: it installs nilearn for root only.

**Comment by orchid666** [comment]
You were right, that was the issue,
i uninstalled nilearn (sudo pip uninstall nilearn) then reinstalled it (sudo pip install nilearn).
It's working now.
Thanks a lot!
