### ISSUE TITLE
July 2015 sprint: organization

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#625]
This issue a discussion thread for the 2015 sprint. It's meant to act as a mailing list thread, and not an actual issue leading to code. It will be closed after the sprint.

Related is the wiki page for the sprint: https://github.com/nilearn/nilearn/wiki/July-2015-sprint

**Comment by GaelVaroquaux** [comment]
One thing that we should do ASAP, is a bit of issue triaging / labeling. To have a more clear picture of what people can work on. In particular attributing the 'Easy' label to what is easy.

**Comment by AlexandreAbraham** [comment]
I suggest that we create a "2015_july_sprint" label or milestone to
properly tag the issues.

**Comment by GaelVaroquaux** [comment]
> I suggest that we create a "2015_july_sprint" label or milestone to
> properly tag the issues.

I created a milestone for that
