### ISSUE TITLE
Reorganize datasets.py into submodules

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#626]
`datasets.py` has had such a success that it has grown into a 2700+ lines file. However, we had no convention and finding the dataset we want is a bit tedious.

A first step twoard usability has been made in #610. All atlas fetching functions are now starting with `fetch_atlas` and the old ones are still working but raise a warning when they're called.

**Comment by banilo** [comment]
cf. #647

**Comment by AlexandreAbraham** [comment]
Closed by #697.
