### ISSUE TITLE
Create an example using Power + NiftiSpheresMasker and Destrieux atlases.

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#627]
Optional: use also Yeo atlas since it's also a functional atlas.

The goal is to have an example using several functional atlases. Using ABIDE or ADHD seems like a good idea to me.

**Comment by GaelVaroquaux** [comment]
You have in mind a connectome example?

We might need to develop helper functions to get the center of ROIs from
a label img, to use more easily plot_connectome.

**Comment by KamalakerDadi** [comment]
Will this something to do a 4D plotting example ? Since we plan to include alll atlases with Power atlas and Destrieux.

**Comment by KamalakerDadi** [comment]
Forget about the comment. Destrieux isn't a 4D image. Mistaken.

**Comment by banilo** [comment]
Sorry to crash the party, but what does "Power" refer to, here?

**Comment by souravsingh** [comment]
I wish to work on this issue.How do I start?

**Comment by lesteve** [comment]
@AlexandreAbraham is this issue related to this open PR #645 ?

**Comment by KamalakerDadi** [comment]
AFAIK, Yes it is. But the proposal is using only Power atlas.

**Comment by souravsingh** [comment]
So Would my PR create any conflict with the existing PR?

**Comment by KamalakerDadi** [comment]
This example satisfies the criteria. It has Power and Dosenbach with NiftiSpheresMasker
https://nilearn.github.io/auto_examples/03_connectivity/plot_sphere_based_connectome.html#sphx-glr-auto-examples-03-connectivity-plot-sphere-based-connectome-py

**Comment by GaelVaroquaux** [comment]
OK. Thanks for finding this @KamalakerDadi . Let's close this issue
