### ISSUE TITLE
Add score function to CanICA

### ISSUE THREAD

**Issue by arthurmensch** [nilearn/nilearn#629]
I think it would be great to have a score method added to CanICA (and future DictLearning), that would output explained variance ratio (based on `components_` and time serie covariance)

**Comment by GaelVaroquaux** [comment]
Like the one that is in the parietal-python code base?

**Comment by arthurmensch** [comment]
Yes, except it could be cleaned using sklearn.covariance

**Comment by banilo** [comment]
> score

Why would you call it a ``score`` method? Would it not be better to stick with scikit learn conventions, such as ``sklearn.decomposition.PCA.explained_variance_``

**Comment by arthurmensch** [comment]
It could be used to score test sets decomposed over fitted maps. I was more thinking about `log_likelihood` of a Gaussian fit.

We could also provide a `explained_variance_` attribute that would hold the explained variance of the maps over the training set

**Comment by bthirion** [comment]
Note that ICA does not change the Gaussian likelihood of the model (it works on making it non-Gaussian, while holding mean/covariance fixed) and does not consider explained variance (unlike most DL formuations). So I don't think that it makes sense to use this criterion. Sorry if I misunderstood.

**Comment by arthurmensch** [comment]
This is true, doesn't it make sense to consider explained variance (and Gaussian log likelihood) for hierarchical PCA ?

**Comment by bthirion** [comment]
It does. Note that explained variance is easy to compute, while the Gaussian lig likelihood is not always. The explained variance remains well defined even if your data are not Gaussian distributed.

**Comment by dangom** [comment]
Hi guys, I see this thread has been idle for some time, but I figured my question would fit nicely in here.

Consider a single-subject ICA analysis. If we were to use CanICA as a substitute for FSL Melodic, for example, how would we mimic FSL's component sorting by variance explained?

**Comment by bthirion** [comment]
I don't see any major issue with this idea.

**Comment by KamalakerDadi** [comment]
PR #1890 should close this.

**Comment by KamalakerDadi** [comment]
Closing with #2577
