### ISSUE TITLE
File handlers are not supported for file input

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#631]
CSV files can be arrays, or strings but we can't give directly a file handler. Not sure if it is useful though.

**Comment by GaelVaroquaux** [comment]
> CSV files can be arrays, or strings but we can't give directly a file handler.
> Not sure if it is useful though.

Not sure either. Do you have a specific usecase?

**Comment by lesteve** [comment]
@AlexandreAbraham apparently you are the one who wrote this one and not @KamalakerDadi ... Do you remember more about the context ?

**Comment by AlexandreAbraham** [comment]
Nothing important. Closing.
