### ISSUE TITLE
Add region extraction methods

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#633]
Integrate the methods presented in [Abraham et al. 2013](https://hal.inria.fr/hal-01093944) in a nilearn-friendly interface along with example, test and documentation.

Diffculties:
* my code is generic but very ugly and I'm not happy with it. It needs love.
* random walker and region growing approaches rely completely on the (great) scikit image code for region segmentation. I don't think that we should do our own code (a naive implementation is way slower and writing an optimized implementation takes time) so we have to decide if we add the code in nilearn.externals (the solution I chose so far) or put a dependency on scikit image for that.
* a lot of work in doc and example is also required.

**Comment by GaelVaroquaux** [comment]
> Integrate the methods presented in Abraham et al. 2013 in a nilearn-friendly
> interface.

Not all of the methods. Just the one or two that works best.

**Comment by KamalakerDadi** [comment]
See PR #651

**Comment by lesteve** [comment]
Closing since RegionExtractor has reached master probably via #898 and a push in master.
