### ISSUE TITLE
Add dictionary learning

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#634]
Add Multi subject dictionary learning based on [Varoquaux et al. 2011](https://hal.inria.fr/inria-00588898/) along with tests, example and documentations.

**Comment by GaelVaroquaux** [comment]
Let's start with a simple l1-penalized dict learning, before full blown
MSDL.

G

On Sat, Jul 04, 2015 at 05:50:55PM -0700, Alexandre Abraham wrote:
> Add Multi subject dictionary learning based on Varoquaux et al. 2011 along with
> tests, example and documentations.

> —
> Reply to this email directly or view it on GitHub.*


-- 
    Gael Varoquaux
    Researcher, INRIA Parietal
    NeuroSpin/CEA Saclay , Bat 145, 91191 Gif-sur-Yvette France
    Phone:  ++ 33-1-69-08-79-68
    http://gael-varoquaux.info            http://twitter.com/GaelVaroquaux

**Comment by AlexandreAbraham** [comment]
I've coded simple dictionary learning based on sklearn online dictionary learning a very long time ago. I was planning to merge it after the spectral clustering PR was merged but it never was. I can rehabilitate it though.

**Comment by GaelVaroquaux** [comment]
> I've coded simple dictionary learning based on sklearn online dictionary
> learning a very long time ago. I was planning to merge it after the spectral
> clustering PR was merged but it never was. I can rehabilitate it though.

Talk to Arthur!

**Comment by arthurmensch** [comment]
I have a working branch with simple dict learning working. Should I make it a PR already ?

**Comment by GaelVaroquaux** [comment]
> I have a working branch with simple dict learning working. Should I make it a
> PR already ?

I think you should.

**Comment by AlexandreAbraham** [comment]
> I think you should.

:+1:

**Comment by lesteve** [comment]
Closing since #693 has been merged.
