### ISSUE TITLE
Let SpaceNet examples integrate with the generated documentation

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#635]
Let SpaceNet (PR #219) examples integrate with the generated documentation. This means reformatting the examples' docstrings, etc.

**Comment by dohmatob** [comment]
![screenshot from 2015-07-14 17 44 34](https://cloud.githubusercontent.com/assets/634068/8677550/03459a98-2a50-11e5-99f8-fdb1813adc29.png)

**Comment by dohmatob** [comment]
![screenshot from 2015-07-14 18 07 54](https://cloud.githubusercontent.com/assets/634068/8678192/7c1c75ba-2a53-11e5-9d49-d3ad1eb5f279.png)

**Comment by AlexandreAbraham** [comment]
@dohmatob I think that it is the case now, right? Can we close this one?

**Comment by dohmatob** [comment]
Ya @AlexandreAbraham. Closing.
