### ISSUE TITLE
Add NeuroVault downloader.

### ISSUE THREAD

**Issue by chrisfilo** [nilearn/nilearn#640]
As part of the datasets and/or examples.

**Comment by bcipolli** [comment]
if y'all want to do this, feel free to assign to me. @chrisfilo can you add some info about docs / APIs / endpoints for download?

**Comment by chrisfilo** [comment]
API: http://neurovault.org/api-docs
pyneurovault (example implementation by @vsoch, although I doubt @GaelVaroquaux will let it be a dependency): https://github.com/NeuroVault/pyneurovault

**Comment by vsoch** [comment]
Yes, pyneurovault as a dependency is not something I would do. Let us know if there is functionality missing that you would want.

**Comment by bcipolli** [comment]
Cool, thanks. Do you have a cool example in mind? From my experience, showing off some new aspect of `nilearn` (new plot, new analysis function/object, or new approach) with an example is a great way to get an example considered.

**Comment by vsoch** [comment]
Wasn't the glass brain updated this morning to show negative values? That would be nice to show off, even if it's simple.

**Comment by chrisfilo** [comment]
You can grab a single map and just plot it, but it would be cool to run ICA
on a bunch of maps. You can restrict the set to task fMRI maps from
collections with DOIs.

**Comment by GaelVaroquaux** [comment]
@bcipolli : do you still have this in mind? It would be awesome to have this in nilearn.

**Comment by bcipolli** [comment]
@GaelVaroquaux yes, though it's low on my priority list at the moment, especially as I didn't know there's interest in it. Would be glad to work on it after SfN.

The data download should be straightforward; there are good docs and examples from https://github.com/NeuroVault/pyneurovault . Just need to port things to nilearn's downloading framework, which I'm well familiar with.

Settling on a reasonable example is the most important thing. Glad to have suggestions, or to run with @chrisfilo 's idea of running ICA on some number of maps with DOIs.

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux yes, though it's low on my priority list at the moment,
> especially as I didn't know there's interest in it. Would be glad to
> work on it after SfN.

OK. Great. It's good to have you in the loop. Keep us posted on this.

> Settling on a reasonable example is the most important thing. Glad to
> have suggestions, or to run with @chrisfilo 's idea of running ICA on
> some number of maps with DOIs.

I really like his suggestion, actually. I think that it's a great example
of using nilearn (and maybe SparsePCA will give us cooler maps :P).

**Comment by chrisfilo** [comment]
I agree that ICA would be the way to go. We should filter the maps (via the
API)  to only get unthresholded ones.

**Comment by vsoch** [comment]
Example here:

https://github.com/NeuroVault/pyneurovault/blob/master/examples/download_example.py#L18

It's basically a pandas data frame, and you can do traditional filtering on
it, if the pyneurovault filter function is not suitable. Please post issue
for functionality that would be desired but is not yet offered!

On Thu, Oct 15, 2015 at 5:27 AM, Chris Filo Gorgolewski <
notifications@github.com> wrote:

> I agree that ICA would be the way to go. We should filter the maps (via the
> API) to only get unthresholded ones.
> On Oct 14, 2015 9:23 AM, "Gael Varoquaux" <notifications@github.com>
> wrote:
>
> > > @GaelVaroquaux yes, though it's low on my priority list at the moment,
> > > especially as I didn't know there's interest in it. Would be glad to
> > > work on it after SfN.
> >
> > OK. Great. It's good to have you in the loop. Keep us posted on this.
> >
> > > Settling on a reasonable example is the most important thing. Glad to
> > > have suggestions, or to run with @chrisfilo 's idea of running ICA on
> > > some number of maps with DOIs.
> >
> > I really like his suggestion, actually. I think that it's a great example
> > of using nilearn (and maybe SparsePCA will give us cooler maps :P).
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nilearn/nilearn/issues/640#issuecomment-148065558>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/issues/640#issuecomment-148370651>.
>



-- 
Vanessa Villamia Sochat
Stanford University
(603) 321-0676

**Comment by GaelVaroquaux** [comment]
nilearn doesn't have a pandas dependency so far, but I am happy adding
one.

**Comment by bcipolli** [comment]
I started working on this. It's worth mentioning that code for download and ICA analyses are already available ( https://github.com/NeuroVault/neurovault_analysis ); I believe it's just a matter of cleaning them up and formatting them for `nilearn` here.

I've got an initial downloader (with filters and caching of both images and metadata) working (initial version). The example is a bit trickier to distill to basics, as there's a bit of data cleaning necessary. May work on this more tomorrow or early next week.

**Comment by GaelVaroquaux** [comment]
> I started working on this. It's worth mentioning that code for download and ICA
> analyses are already available ( https://github.com/NeuroVault/
> neurovault_analysis ); I believe it's just a matter of cleaning them up and
> formatting them for nilearn here.

Yes :). I'd like to make these things more reproducible. In the "CircleCI
automates and generate docs at each commit" sense of reproduciblity.

> I've got an initial downloader (with filters and caching of both images
> and metadata) working (initial version). The example is a bit trickier
> to distill to basics, as there's a bit of data cleaning necessary. May
> work on this more tomorrow or early next week.

Thanks heaps. Maybe it's useful to split the work, and get first an
example with the data cleaning.

I think that this application is a bit "paradigmatic" in the sense that
it shows a rich data preparation pipeline, and we should design nilearn
so that pipeline is as easy as it can be.

**Comment by bcipolli** [comment]
Cool. I will be giving a "citizen science" talk at a public library in San Diego on Nov. 15; I hope I could have this ready to present for then. So, hope to have a PR done today or tomorrow and iterate with y'all then.

**Comment by AlexandreAbraham** [comment]
Gael will be off this week end but I'll be there ;).

**Comment by KamalakerDadi** [comment]
Closing in favour of #1182
