### ISSUE TITLE
Basic authentication header should only be sent using HTTPS

### ISSUE THREAD

**Issue by bcipolli** [nilearn/nilearn#650]
Basic authentication exposes username/password as unencrypted (base64 encoded, which has no encryption). Because of this, it is only appropriate to send over secure connections (HTTPS).

In the current code, I don't believe there is any such check:
 https://github.com/nilearn/nilearn/blob/b89a84aa9790651c27e02c738623c8086b637589/nilearn/datasets.py#L498

I suggest making that check :)

**Comment by GaelVaroquaux** [comment]
Sounds good to me!

Gaël

**Comment by AlexandreAbraham** [comment]
You are totally right.
