### ISSUE TITLE
Create linear alignment module in utils

### ISSUE THREAD

**Issue by arthurmensch** [nilearn/nilearn#655]
I am quite sure that a lot a people has bits of code written to perform hungarian algorithm on contrast / decomposition maps to do comparison across technics / subjects / experience setting. Wouldn't it be interesting to explicitly integrate it into `nilearn.image` ?

I could use it on dict learning vs canica example (PR #638); Right now I use sklearn code in the middle of the script, which makes it too difficult for the non expert neuroscientist.

**Comment by banilo** [comment]
I think @dohmatob has also implemented some global image comparison algos, perhaps check back with him.

**Comment by GaelVaroquaux** [comment]
> I am quite sure that a lot a people has bits of code written to perform
> hungarian algorithm on contrast / decomposition maps to do comparison across
> technics / subjects / experience setting.

I believe only a handful of methods geeks. When performed across methods,
this is really something that only methods researchers would do. Across
subjects, it's really something that shouldn't be done.

The framework that we are trying to push to compare subjects with
functional connectivity is to use decomposition methods to learn regions,
and then to use a connectome comparison method on the corresponding set
of regions.

**Comment by AlexandreAbraham** [comment]
@arthurmensch, what I've done is that I have a nilearn-sandbox repo where I keep nilearn compatible extensions that are not in the scope of nilearn (but may be someday). You can do the same.

In the meantime, I close this one.

**Comment by GaelVaroquaux** [comment]
> I have a nilearn-sandbox repo where I keep nilearn compatible
> extensions that are not in the scope of nilearn (but may be someday).
> You can do the same.

Maybe we should have a public one?

**Comment by AlexandreAbraham** [comment]
> Maybe we should have a public one?

It could be a mess, but it could be funny too. I have no strong opinion about that but I would contribute in it.

**Comment by GaelVaroquaux** [comment]
> It could be a mess, but it could be funny too.

Chances are that it would be a mess. I don't see why it would be more
successful that Parietal-Python. But it would also be accessible to
external researchers, which is a good thing.

**Comment by AlexandreAbraham** [comment]
Let's go then!

**Comment by AlexandreAbraham** [comment]
We just have to be careful that good stuff doesn't go into the sandbox because people does not want to pass the PR reviewing process of the official repo.

**Comment by AlexandreAbraham** [comment]
I just created it here: https://github.com/nilearn/nilearn_sandbox

Please update the README file with what you think necessary.
