### ISSUE TITLE
Rename the atlas downloading functions in the reference documentation

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#656]
The various atlas downloading functions have been renamed (this is already done), and the old one deprecated. However, in the reference documentation, this change has not been done. The file doc/modules/reference.rst must be modified to put it up to date.

**Comment by MartinPerez** [comment]
I will take care of this.

**Comment by banilo** [comment]
> I will take care of this.

+1

**Comment by MartinPerez** [comment]
its done... I made the pull request

**Comment by AlexandreAbraham** [comment]
Closed by #661.
