### ISSUE TITLE
Add debian package to docs

### ISSUE THREAD

**Issue by hanke** [nilearn/nilearn#660]
Once the debian package is propagated to repositories, we should add it to the installation instructions.

(Original issue below)

The sources of the Debian packaging are available here:

https://github.com/hanke/nilearn/tree/debian

The packaging is self-contained in the debian/ directory. The only other change to the source tree is the removal of source-less javascript libraries. This modification is performed by the `dfsg-source-tree` target implemented in the debian/rules (Make)file. For this reason, this branch should be kept separate permanently.

**Comment by GaelVaroquaux** [comment]
Thank Michael. I have pushed the debian branch to origin.

We'll also have to update our install instructions (rename the issue to
that).
