### ISSUE TITLE
Drop sklearn 0.12 compatibility

### ISSUE THREAD

**Issue by arthurmensch** [nilearn/nilearn#667]
Version packaged in neurodebian repository for ubuntu 12.04 is 0.14.1. I think we should drop compatibility

**Comment by lesteve** [comment]
The rationale for scikit-learn 0.12.1 was given [here](https://github.com/nilearn/nilearn/pull/397#issuecomment-73740450) by @GaelVaroquaux:

>>  In particular does scikit-learn 0.12.1 have a special meaning?

> No. It's a configuration that's 2 years old, and we felt that 2 years old
was a good time.

Personally I am always in favour of dropping support for old versions but I doubt anything has changed significantly since last February ...

**Comment by GaelVaroquaux** [comment]
Let's do it!

YeaaaaAAAAAh!

**Comment by lesteve** [comment]
Woohoooo !

**Comment by AlexandreAbraham** [comment]
:email::email::email::email::email::email::email::+1::+1::email::email::email::email::email::email::email:
:email::email::email::email::email::email::email::+1::+1::+1::email::email::email::email::email::email:
:email::email::email::email::email::email::email::+1::+1::+1::email::email::email::email::email::email:
:email::email::email::email::email::email::email::+1::+1::+1::email::email::email::email::email::email:
:email::email::email::email::email::email::email::+1::+1::+1::email::email::email::email::email::email:
:email::email::email::email::email::email::+1::+1::+1::+1::email::email::email::email::email::email:
:email::email::email::email::email::email::+1::+1::+1::+1::email::email::email::email::email::email:
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:

**Comment by AlexandreAbraham** [comment]
:email::email::email::email::email::email::email::+1::+1::email::email::email::email::email::email::email:
:email::email::email::email::email::email::email::+1::+1::+1::email::email::email::email::email::email:
:email::email::email::email::email::email::email::+1::+1::+1::email::email::email::email::email::email:
:email::email::email::email::email::email::email::+1::+1::+1::email::email::email::email::email::email:
:email::email::email::email::email::email::email::+1::+1::+1::email::email::email::email::email::email:
:email::email::email::email::email::email::+1::+1::+1::+1::email::email::email::email::email::email:
:email::email::email::email::email::email::+1::+1::+1::+1::email::email::email::email::email::email:
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::email:
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:
:+1::+1::+1::+1::+1::+1::+1::+1::smoking::smoking::smoking::smoking::smoking::smoking::smoking::smoking:
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:
:+1::+1::+1::+1::+1::+1::+1::+1::smoking::smoking::smoking::smoking::smoking::smoking::smoking::smoking:
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:
:+1::+1::+1::+1::+1::+1::+1::+1::smoking::smoking::smoking::smoking::smoking::smoking::smoking::smoking:
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::email:

**Comment by GaelVaroquaux** [comment]
https://www.youtube.com/watch?v=KFP9VChYl0E
