### ISSUE TITLE
plot_localizer_mass_univariate_methods.py seems not to be building

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#670]

**Comment by KamalakerDadi** [comment]
I can see the output by running the file. Is that what you are not saying ?

**Comment by lesteve** [comment]
It seems to be building fine for me too ...

**Comment by lesteve** [comment]
Possibly related to #678 since this example is using the localizer dataset.

**Comment by GaelVaroquaux** [comment]
> Possibly related to #678 since this example is using the localizer dataset.

Good point, indeed. That would explain why we cannot reproduce.

**Comment by GaelVaroquaux** [comment]
Closing, as this is related to #678
