### ISSUE TITLE
brainomics datasests download times out upon 

### ISSUE THREAD

**Issue by chrisgorgo** [nilearn/nilearn#678]
see https://circleci.com/gh/chrisfilo/nilearn/17

Use the following line to replicate:

```
localizer_dataset = datasets.fetch_localizer_contrasts(
    ["left vs right button press"],
    n_subjects=2,
    get_anats=True,
    get_tmaps=True)
```

**Comment by lesteve** [comment]
Yep I get the same locally.

**Comment by lesteve** [comment]
It looks like https://brainomics.cea.fr/ is not accessible at the moment ...

**Comment by lesteve** [comment]
FWIW you can use the verbose parameter to get the HTTP request.

```python

 localizer_dataset = datasets.fetch_localizer_contrasts(
    ["left vs right button press"],
    n_subjects=2,
    get_anats=True,
    get_tmaps=True, verbose=100)
```

Downloading data from http://brainomics.cea.fr/localizer/brainomics_data_30.zip?rql=Any%20X,XT,XL,XI,XF,XD%20WHERE%20X%20is%20Scan,%20X%20type%20XT,%20X%20concerns%20S,%20X%20label%20XL,%20X%20identifier%20XI,%20X%20format%20XF,%20X%20description%20XD,%20S%20identifier%20%3C%3D%20%22S02%22,%20X%20type%20IN(%22c%20map%22,%20%22t%20map%22),%20X%20label%20%22left%20auditory%20%26%20visual%20click%20vs%20right%20auditory%26visual%20click%22&vid=data-zip

**Comment by lesteve** [comment]
Hmmm there was a planned computer outage for maintenance, not sure whether that affects brainomics.cea.fr. The servers are supposed to be back up beginning of the afternoon today.

**Comment by AlexandreAbraham** [comment]
Yes, brainomics was supposed to be shut down.

**Comment by lesteve** [comment]
Working now.

**Comment by GaelVaroquaux** [comment]
I am reopening this, because it happens too often, and we need to hold a static version of this download on nitrc.

**Comment by AlexandreAbraham** [comment]
I have no time to take care of this one but, if anybody is willing to write the code and point me the URL to cache, I can upload the corresponding files on NITRC.

**Comment by choldgraf** [comment]
FYI this appears to be down again...

**Comment by KamalakerDadi** [comment]
@GaelVaroquaux Shall I upload all the brainomics_localizer data (n_subjects=94) on NITRC ?

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux Shall I upload all the brainomics_localizer data (n_subjects=94) on NITRC ?

Please do.

Thanks a lot.

**Comment by kchawla-pi** [comment]
Down since This morning at least.
What's the downside to moving this to Open Science Framework?
@bthirion

**Comment by bthirion** [comment]
No really. I wanted to have the formal agreement of the people who provide this dataset. This is taking time.

**Comment by KamalakerDadi** [comment]
An issue related to brainomics.

**Comment by bthirion** [comment]
Brainomics is no longer used.
