### ISSUE TITLE
NiftiMasker embedding in estimator code is producing spaghetti code

### ISSUE THREAD

**Issue by arthurmensch** [nilearn/nilearn#688]
@dohmatob @ahoyosid @AlexandreAbraham 

Alloowing the user to give either the mask or masker parameters to estimator object (i.e decomposition, spectral clustering, space net), is producing code copy. I think we should at least have a mixin for this, if we want to keep being able to have `fit(imgs, confound)` signature in estimators.

**Comment by AlexandreAbraham** [comment]
This is related to #194. I think that any initiative to refactor this code is welcome since we already have 3 people struggling with it and making different versions of the same code.

**Comment by bthirion** [comment]
Stalled. Closing.
