### ISSUE TITLE
Check that 'python setup.py develop' raises a understandable error with missing dependencies

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#695]
It seems that, when we are missing dependencies, we are not raise good errors on 'develop', only on 'install'.

**Comment by lesteve** [comment]
That was pushed silently into master ...

**Comment by lesteve** [comment]
https://github.com/nilearn/nilearn/commit/ab89077bb1b7e9cd16a18a4e155439b674088161

**Comment by lesteve** [comment]
I see what you are doing here, getting to shame myself publicly :wink:

**Comment by GaelVaroquaux** [comment]
No, that's gr8. Thanks a lot.
