### ISSUE TITLE
Internal function _get_plot_stat_map_params in img_plotting does not work properly

### ISSUE THREAD

**Issue by juhuntenburg** [nilearn/nilearn#699]
The function is used to derive the value limits for the colormap and colorbar depending on whether a symmetric colorbar is requested or not. But when the symmetric_cbar option is set to False (or chosen to be False by the 'auto' option), the colormap is still forced to be symmetric, while the colorbar is correctly unsymmetric:

symmetric_cbar=True
![symmetric_thr_2](https://cloud.githubusercontent.com/assets/6514016/8745042/227b5578-2c7c-11e5-8354-a35bd08936fe.png)

symmetric_cbar=False
![nonsymmetric_thr_2](https://cloud.githubusercontent.com/assets/6514016/8745056/3f6c6f96-2c7c-11e5-89a5-a6a5f7cdf4fd.png)

**Comment by juhuntenburg** [comment]
I am working on this.

**Comment by eickenberg** [comment]
I'm slow.

> the colormap is still forced to be symmetric

Could you explain what this means?

On Fri, Jul 17, 2015 at 12:08 PM, Julia Huntenburg <notifications@github.com

**Comment by juhuntenburg** [comment]
vmin is set to -vmax

**Comment by eickenberg** [comment]
Got it.

Yes.

Easy to fix, but points again to the deeper problem that hacking the cbar
as we did was probably not a good idea to begin with ;)

On Fri, Jul 17, 2015 at 12:17 PM, Julia Huntenburg <notifications@github.com

**Comment by juhuntenburg** [comment]
symmetric_cbar=False after the fix in PR #705
![nonsymmetric_thr_2_new](https://cloud.githubusercontent.com/assets/6514016/8750517/28f7bf64-2ca8-11e5-9fa3-fce4309e8fb2.png)

**Comment by juhuntenburg** [comment]
Turns out the logic was correct in the beginning and I was only confused by the doc string of plot_stat_map / plot_glass_brain. So the resolution to this issue is simply updating the doc string.
