### ISSUE TITLE
Slow test: nilearn.image.tests.test_resampling.test_resample_img_segmentation_fault 

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#700]
This test is much much too slow. Someone should look at it and see if we can make it faster.

**Comment by lesteve** [comment]
Basically you need a big array to trigger the segfault. Not sure we can do much about that ...

**Comment by lesteve** [comment]
More context: https://github.com/nilearn/nilearn/pull/392

**Comment by AlexandreAbraham** [comment]
Linked to #736. By using ulimit, we can reduce the memory available and maybe trigger the segfault faster.

**Comment by lesteve** [comment]
> Linked to #736. By using ulimit, we can reduce the memory available and maybe trigger the segfault faster.

Not entirely sure this is true. The segmentation fault is due to an int32 array index wrapping over IIRC.

**Comment by AlexandreAbraham** [comment]
OK, my bad!
