### ISSUE TITLE
Tweaks to new installation instructions

### ISSUE THREAD

**Issue by lesteve** [nilearn/nilearn#701]
### Linux tab
* Then simply install nilearn through Neurodebian. I guess we should put the full apt-get install command
* Ctrl-Alt-T to open a terminal may not work for everyone (Ubuntu or GNOME is probably a requirement, doesn't work on Kubuntu for example)

**Comment by lesteve** [comment]
Also I am wondering out of curiosity do you detect the platform 32 bit vs 64 bit automatically. I am talking about the recommendation of using 64bit Anaconda.

**Comment by GaelVaroquaux** [comment]
> Also I am wondering out of curiosity do you detect the platform 32 bit vs 64
> bit automatically. I am talking about the recommendation of using 64bit
> Anaconda.

That recommendation is necessary because basic examples run out of memory
on 32 bit.

But there are pretty much no 32 bit systems around any more. And people
doing 32 bits cannot do nilearn.

**Comment by GaelVaroquaux** [comment]
>   • Then simply install nilearn through Neurodebian. I guess we should put the
>     full apt-get install command

Actually, we didn't do that by design because on modern systems, you can
use the ubuntu software center without root privilege. Maybe we should
point people to the ubuntu software center.

**Comment by lesteve** [comment]
> Actually, we didn't do that by design because on modern systems, you can use the ubuntu software center without root privilege. Maybe we should point people to the ubuntu software center.

Maybe just explicitly mention the name of the nilearn package, I am guessing "python-nilearn".

**Comment by GaelVaroquaux** [comment]
> Maybe just explicitly mention the name of the nilearn package, I am guessing
> "python-nilearn".

Yes. But then the link says all this.

**Comment by lesteve** [comment]
I guess it is a bit confusing that both "Neurodebian" link actually links to the python-nilearn package page on neurodebian: http://neuro.debian.net/pkgs/python-nilearn.html. 

![neurodebian_snapshot](https://cloud.githubusercontent.com/assets/1680079/8750208/619887ba-2ca6-11e5-8aa1-82ff49b238da.png)

Splitting hair quite a bit here, I think the first Neurodebian link should go to the neurodebian landing page. And then I would use a wording like this:

Then simply install the python-nilearn (link to python-nilearn neurodebian package page) package through Neurodebian (no link).

**Comment by MartinPerez** [comment]
I will wait for more tweaks to update everything together

**Comment by MartinPerez** [comment]
@lesteve I implemented what I think is the only tweak in this thread?. Also @GaelVaroquaux  the changes of the CSS look great! #687

**Comment by lesteve** [comment]
Looks good, thanks! Closing this issue.
