### ISSUE TITLE
Add an AAL downloader

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#706]
The best URL to grab it is
http://www.gin.cnrs.fr/AAL-217

This should be added to nilearn/datasets/atlas.py where other loaders for atlases are.

It should be a drop-in replacement for other atlases.

**Comment by MartinPerez** [comment]
Im on it

**Comment by MartinPerez** [comment]
@GaelVaroquaux By "a drop-in replacement for other atlases" do you mean something in addition to the implementation of the fetch_atlas function and documentation

**Comment by AlexandreAbraham** [comment]
Fixed by #758.
