### ISSUE TITLE
Migrate to the new travis build infrastructure

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#711]
Following instructions on
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

For this, we need neurodebian to be added to travis's whitelist, aka the following PR to be merged by the travis devs:
https://github.com/travis-ci/apt-source-whitelist/pull/10

**Comment by thomasbazeille** [comment]
can be closed
