### ISSUE TITLE
Add Netmats Megatrawl dataset

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#717]
http://humanconnectome.org/about/pressroom/project-news/netmats-megatrawl-released/

**Comment by GaelVaroquaux** [comment]
Totally, that would be awesome!

**Comment by AlexandreAbraham** [comment]
I just browsed quickly and I see no way to get the data. Did you mean that you want the parceallations to be downloaded and the study re-run?

**Comment by AlexandreAbraham** [comment]
I guess that what you wanted were the correlation matrices.

**Comment by GaelVaroquaux** [comment]
> I just browsed quickly and I see no way to get the data. Did you mean that you
> want the parceallations to be downloaded and the study re-run?

I couldn't find it either, but Steve Smith claims it's easy. For a
certain definition of easy I guess.

There's supposed to be a download link. If we can't find it, we'll have
to ask Steve.

**Comment by GaelVaroquaux** [comment]
> I guess that what you wanted were the correlation matrices.

Yes

**Comment by AlexandreAbraham** [comment]
Found it. It is really not obvious. Select any run (I take 3T_Q1-Q6related468_MSMsulc_d25_ts3).
Click on "nodes+edges 2" to get the netjs graph.
Sniff a little bit, find that "main.js" do the job.
Open it: https://db.humanconnectome.org/megatrawl/3T_Q1-Q6related468_MSMsulc_d25_ts2/netjs/js/main.js
Find the matrices, eg : https://db.humanconnectome.org/megatrawl/3T_Q1-Q6related468_MSMsulc_d25_ts2/netjs/data/dataset1/Znet2.txt

The files are very light, we can totally include them directly into nilearn. However, they have a user agreement that we must include.

Most of the work will be to understand dataformat and load it in a user-friendly fashion.

I let anybody motivated take it from here ;).

**Comment by AlexandreAbraham** [comment]
Sidenote: the netjs visualization if very pretty and they basically did most of the work to adapt it to our usecase. It shouldn't be too much work to generate it from our data. PR welcome in `nilearn_sandbox` ;).

**Comment by KamalakerDadi** [comment]
> I let anybody motivated take it from here ;)

What about me ? I can try to address this. If not, I announce it here.

**Comment by AlexandreAbraham** [comment]
I'm OK with you working on it but you already have a lot of battles to fight.
