### ISSUE TITLE
"threshold" has no bounds in CanICA

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#721]
threshold can clearly not be above the number of maps. Yet, we don't check that anywhere. I think we should do it and fail with a user-friendly error message.

**Comment by AlexandreAbraham** [comment]
We should put the bound in the doc too.

**Comment by banilo** [comment]
I can do this.

**Comment by arthurmensch** [comment]
I also think that this `threshold` parameter is confusing for the user, something between 0 and 1 would maybe be easier to understand.

**Comment by GaelVaroquaux** [comment]
> I also think that this threshold parameter is confusing for the user,
> something between 0 and 1 would maybe be easier to understand.

But it cannot be between 0 and 1. The maps are not bound between zero and
one.

**Comment by arthurmensch** [comment]
Then I guess we could rename it and call it active_ratio or something
similar. Right now the end user has probably no clue on why he should set
the threshold between zero and n_components.
Le 6 oct. 2015 4:47 PM, "Gael Varoquaux" <notifications@github.com> a
écrit :

**Comment by souravsingh** [comment]
I wish to work on this.How do I start?

**Comment by lesteve** [comment]
We don't have documentation for contributing to nilearn unfortunately but you can check the [scikit-learn](http://scikit-learn.org/dev/developers/contributing.html#how-to-contribute) one. It has some relevant information about how to clone the nilearn repo on your local computer, run the tests, open a PR (Pull Request), etc ...

The basics is to try to understand the issue and open a PR with a tentative fix/solution which we can then discuss.

**Comment by KamalakerDadi** [comment]
Closing with #1428
