### ISSUE TITLE
SpaceNet: About `plot_mixed_gambles_space_net.py`

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#725]
line 5, @GaelVaroquaux : 

Please explain here that you are using the regressor object given that the task is to predict a continuous variable, the gain of the gamble.

Also, maybe we should leave out some data and show a prediction power (if it somewhat works).

**Comment by dohmatob** [comment]
Fixed.

**Comment by GaelVaroquaux** [comment]
Where is the fix? I don't see the example in master having a prediction power.

**Comment by dohmatob** [comment]
I was talking about the first part. I've already commented about the second part elsewhere...

**Comment by dohmatob** [comment]
See lines 19 to 21 of the script. Closing.
