### ISSUE TITLE
SpaceNet: fetch_mixed_gambles

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#726]
Changes the name of `return_raw_data` by something like `preprocessed_data`.

**Comment by dohmatob** [comment]
I had this discussion with @GaelVaroquaux and we retained the current naming. I think we should close this.

**Comment by GaelVaroquaux** [comment]
I don't have a clear opinion. If people feel another naming is better,
I'll go with the flow.

**Comment by AlexandreAbraham** [comment]
No strong feeling either, I was just stating the issue here. Closing.
