### ISSUE TITLE
Improve nilearn memory consumption, test it

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#736]
Nilearn's code has growth a lot since the last time we audited it. New patterns, such as `new_img_like` that loads an img, may sometimes encourage object persistence when they are not really needed and their memory could be freed.

It would be a good thing to do a pass on the code to check that.

Also, it would be really awesome to have memory tests. Using `ulimit` linux command, it is easy to set a bound to memory consumption and thus check that we are not leaking.

**Comment by banilo** [comment]
How should we debug when we exceed the preset memory limit?

**Comment by AlexandreAbraham** [comment]
You can get the stack trace using pdb. You can also set a breakpoint using the memory profiler.

**Comment by GaelVaroquaux** [comment]
Testing could be done by having a specific suite of test (not the main one), run by the CI system and relying on either ulimits, or https://pypi.python.org/pypi/memory_profiler
