### ISSUE TITLE
New label: quality

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#737]
I would like to add a "Quality" label to the issues because we have no label to target things like improvement of error messages.

**Comment by GaelVaroquaux** [comment]
> I would like to add a "Quality" label to the issues because we have no
> label to target things like improvement of error messages.

Sounds good.

**Comment by AlexandreAbraham** [comment]
Cool!

**Comment by AlexandreAbraham** [comment]
Sidenote: for the next sprint, it think it would be crucial to have a team working on quality / benchs.
