### ISSUE TITLE
Improve task mask pattern in examples

### ISSUE THREAD

**Issue by lesteve** [nilearn/nilearn#741]
```python
classification_target = stimuli[
    np.logical_not(resting_state)] == category
```

From #740, @AlexandreAbraham  said:

> I already found this line hard to understand before (I particularly dislike playing with the priority of operators = and ==) but now the new_line make it even more obscure. Maybe we could change by:

> ```
task_mask = np.logical_not(resting_state)  # or sample_mask?
classification_target = (stimuli[task_mask] == category)
```

Quickly git-grepping it looks like this pattern is both present in:
examples/decoding/plot_haxby_different_estimators.py
examples/decoding/plot_haxby_full_analysis.py

They may be other places where this is used.

**Comment by lesteve** [comment]
Maybe one for @KamalakerDadi if you want an easy one to take your mind off  your bigger AutoExtractor PR.

**Comment by KamalakerDadi** [comment]
Please assign it. I will do it.
