### ISSUE TITLE
Bad except clauses order (TypeError is an ancestor class of DimensionError)

### ISSUE THREAD

**Issue by lesteve** [nilearn/nilearn#743]
#### Occurred on:
+ **Commit**:  a6fa5848930c40a59652231a47b7f6d4a9edefc5
+ **File**:    [nilearn/_utils/niimg_conversions.py](https://github.com/nilearn/nilearn/blob/a6fa5848930c40a59652231a47b7f6d4a9edefc5/nilearn/_utils/niimg_conversions.py)
+ **LineNum**: [140](https://github.com/nilearn/nilearn/blob/a6fa5848930c40a59652231a47b7f6d4a9edefc5/nilearn/_utils/niimg_conversions.py#L140)
+ **Code**:    `        except DimensionError as exc:`

    
#### Currently on:
+ **Commit**:  5b5d8d206c03c3c65ee22896d2850bbb886b333a
+ **File**:    [nilearn/_utils/niimg_conversions.py](https://github.com/nilearn/nilearn/blob/5b5d8d206c03c3c65ee22896d2850bbb886b333a/nilearn/_utils/niimg_conversions.py)
+ **LineNum**: [149](https://github.com/nilearn/nilearn/blob/5b5d8d206c03c3c65ee22896d2850bbb886b333a/nilearn/_utils/niimg_conversions.py#L149)

It looks like this is a real issue since it was caught by landscape.io too.

**Comment by AlexandreAbraham** [comment]
Wow, effectivement !

**Comment by lesteve** [comment]
BTW as a general announcement I just set up Codacy which looks quite good. It should add a new status for code quality in PR, let's see how useful this is.

One reason to love Codacy even if you have no clue what it does: it rates nilearn as an A project: https://www.codacy.com/app/lesteve/nilearn/dashboard.

**Comment by lesteve** [comment]
Also you can create issue from Codacy which is what I did here, hence the very detailed template (no I didn't do the history research and type that in).

**Comment by AlexandreAbraham** [comment]
Can you exclude sphinx gallery from Codacy? It raises most of the issues.

**Comment by lesteve** [comment]
I just tried but I am not sure if/when this is going to have an effect. FWIW you can filter by language, severity, or type, for the Codacy issues.

**Comment by lesteve** [comment]
I see that you have pushed a fix in master, thanks! There is something I don't understand though shouldn't it have been caught by the tests?

I seem to remember that we checked the error message to make sure it mentioned 4d rather than 3d or something like that.

**Comment by AlexandreAbraham** [comment]
> I seem to remember that we checked the error message to make sure it mentioned 4d rather than 3d or something like that.

We check that the number of dimensions asked is the right one "Data must be 4D but you provided" but we don't check the number of dimensions given by the user.

**Comment by AlexandreAbraham** [comment]
Well, apparently I was wrong. This is indeed check in some cases... This is weird. Anyway i added more precise check in #749. Closing this one once travis has passed.
