### ISSUE TITLE
should include full mask in haxby_dataset

### ISSUE THREAD

**Issue by poldrack** [nilearn/nilearn#745]
the whole-brain mask is included in the haxby_dataset_simple download, but not in the haxby_dataset download.  seems like both of them should include the full mask

**Comment by lesteve** [comment]
> seems like both of them should include the full mask

Seems like an oversight indeed!

**Comment by AlexandreAbraham** [comment]
The whole-brain mask is shipped with the haxby example. The archive is 100MB, which is a lot to download for a single mask. Plus, we have no guarantee that this mask is suited for the whole dataset. @GaelVaroquaux, do you think we should upload it on NITRC and make it available with the full dataset?

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux, do you think we should upload it on NITRC and make it
> available with the full dataset?

+1

**Comment by AlexandreAbraham** [comment]
This one is fast. I take care of it while drinking my coffee.
