### ISSUE TITLE
inconsistencies of returned values for haxby datasets

### ISSUE THREAD

**Issue by poldrack** [nilearn/nilearn#746]
datasets.haxby_dataset returns the file names as a list:
'anat': ['/Users/poldrack/nilearn_data/haxby2001/subj1/anat.nii.gz'],
whereas datasets.haxby_dataset_simple returns them as strings:
'func': '/Users/poldrack/nilearn_data/haxby2001_simple/pymvpa-exampledata/bold.nii.gz',

would be good to be consistent and return as lists as well from haxby_dataset_simple

**Comment by lesteve** [comment]
I *think* this is because fetch_haxby can return multiple subjects data. 

For n_subjects=1 (which is the default), we could potentially transform single-element list into its element. What do you think @AlexandreAbraham?

**Comment by AlexandreAbraham** [comment]
> would be good to be consistent and return as lists as well from haxby_dataset_simple

Agreed.

> I think this is because fetch_haxby can return multiple subjects data. 

Yes, `fetch_haxby_simple` does not return lists for historical reasons. We should return lists everytime.

**Comment by lesteve** [comment]
> Yes, fetch_haxby_simple does not return lists for historical reasons. We should return lists everytime.

Fine with me.

**Comment by lesteve** [comment]
@KamalakerDadi are you up for this one?

**Comment by KamalakerDadi** [comment]
Yes. I will.

**Comment by AlexandreAbraham** [comment]
Since it's fast and it modifies one of the most used dataset, please put it at the top of your todo list.

**Comment by KamalakerDadi** [comment]
I am afraid that I have insertions and editions in another branch ```AutoExtractor```. I will soon commit and push these and shift to haxby.
