### ISSUE TITLE
NiftiMapsMasker behavior is strange for some people

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#754]
People tried to use NiftiMapsMasker and, as a test, put the same ROI several times. The results is that the signal is divided by the number of overlapping ROIs, which is logic because we use a least square. However, the user expected to have the mean signal for each map.

**Comment by eickenberg** [comment]
Shouldnt the least-squares part then just be moved to the inverse_transform
(provided there is one)?

On Thu, Aug 6, 2015 at 10:45 AM, Alexandre Abraham <notifications@github.com

**Comment by AlexandreAbraham** [comment]
I don't get your comment. In any case, we have to decide on the strategy used to extract the signals.

**Comment by eickenberg** [comment]
Then maybe it is not applicable.

I understood that the transformer uses least squares to assign signal to
each ROI and that overlapping ROIs then have to share energy.

But one can also simply extract, and give the mean value. In that case, the
scaling, which was induced by the current transformer, would have to move
to the inverse transform.

I couldn't make sense of the code, so this remains the idea in my head.
Maybe I am wrong about how this works.


On Fri, Aug 7, 2015 at 10:45 PM, Alexandre Abraham <notifications@github.com

**Comment by thomasbazeille** [comment]
Maybe this discussion can be closed for now ?
