### ISSUE TITLE
Docs: Clarify that NiftiLabelMasker extracts the average signal from an ROI.

### ISSUE THREAD

**Issue by danlurie** [nilearn/nilearn#761]
This is of course expected behavior, but it's not explicitly stated anywhere that I could find in the docs.

**Comment by bthirion** [comment]
Dear Daniel,

Thank you for pointing this. If you can, you're kindly invited to update the documentation and send a pull request.

**Comment by thomasbazeille** [comment]
This seems to me to be in the [description of the class](https://nilearn.github.io/modules/generated/nilearn.input_data.NiftiLabelsMasker.html) right now.

So I guess this can be closed ?
