### ISSUE TITLE
plot_stat_map fails with non informative error if image is uint8

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#762]
Code:
```python
from nilearn.datasets import fetch_atlas_harvard_oxford
from nilearn.image import index_img
from nilearn.plotting import plot_stat_map


ho = fetch_atlas_harvard_oxford('cort-prob-2mm')
plot_stat_map(index_img(ho.maps, 31))
```

Error: `ValueError: minvalue must be less than or equal to maxvalue`

**Comment by lesteve** [comment]
I am slightly confused. Wasn't https://github.com/nilearn/nilearn/pull/643 supposed to fix that?

**Comment by AlexandreAbraham** [comment]
Yes. But apparently, it didn't work.

**Comment by lesteve** [comment]
Looks like this [line](https://github.com/nilearn/nilearn/blob/b38d6d4fb27e85e0b9e165fefdd74efb21bc6883/nilearn/plotting/img_plotting.py#L872-L872) is missing the 'auto' dtype. This matters for the vmin/vmax computation which is done next.

The 'auto' dtype in _plot_img_with_bg comes too late ...
