### ISSUE TITLE
Have the niimgs checking function optionally convert globbing

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#763]
SHould we expand it? It would be more convenient for me but I don't know if it's YAGNI or not.

**Comment by dohmatob** [comment]
I think it's YAGNI, and we'll bring us more trouble than the anticipated good it might do for users. Let them expand their paths themselves. Also, ``nilearn.plotting`` is not supposed to be a unix shell environment ;)

**Comment by GaelVaroquaux** [comment]
I think that it might be useful, but let's tackle this later: I'd like to
have the niimgs checking function optionally convert globbing: the reason
is that when you have begining users, having to import glob actually
looses them.

Of course, we would need an option (with an API as a np.seterr, and a
context manager) to turn this off.

**Comment by GaelVaroquaux** [comment]
Can I rename the issue, and edit it's description to set this as a new goal?

**Comment by GaelVaroquaux** [comment]
To sum up the work to be done:

- Have check_niimg optionally use glob (and sort if using glob) (with the default being true)

- Have a constant at the level of nilearn.__init__ to control this behavior

- Have a very clear error message if a glob returns an empty list, that explains what is going on, and assumes that the user might have made a glob by mistake (thus points out the above constant).

**Comment by AlexandreAbraham** [comment]
Maybe this behavior should be restricted to `check_niimg_4d`?

**Comment by GaelVaroquaux** [comment]
> Maybe this behavior should be restricted to check_niimg_4d?

Well, if we want to expand '~' we can do it in check_niimg. But for the
rest, I agree.

**Comment by banilo** [comment]
I agree with Gael that glob-integration could increase comfort of nilearn users. After all, we do glob.glob before loading anyways.

**Comment by aabadie** [comment]
>To sum up the work to be done:
>
> * Have check_niimg optionally use glob (and sort if using glob) (with the default being true)
>
> * Have a constant at the level of nilearn.init to control this behavior
> 
> * Have a very clear error message if a glob returns an empty list, that explains what is going on, and > assumes that the user might have made a glob by mistake (thus points out the above constant).

@GaelVaroquaux, I pushed 419019a that should address this feature. A test is missing though.

**Comment by KamalakerDadi** [comment]
@aabadie  It would be nice if you do PR tagged as **[WIP]** and ping somebody if you need help.

**Comment by lesteve** [comment]
> @aabadie It would be nice if you do PR tagged as [WIP] and ping somebody if you need help.

:+1: in general commenting on commits is not a really good idea, because comments tend to be completely lost if there is a rebase. It is a lot better to start a PR so that the discussion happens all in one place.
