### ISSUE TITLE
Function name fetch_atlas_aal_spm_12 is too specific

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#764]
If we want to update the atlas to a new version, we will break all the existing scripts. We should change it to `fetch_atlas_aal_spm` or `fetch_atlas_aal`.

**Comment by MartinPerez** [comment]
Originally I wrote fetch_atlas_aal. But I was told to make it more specific,  I guees if a new aal spm version is included, it would be as a separate atlas function. Actually the file structure is so different between versions that it might be better to just have them in separate fetch functions.

**Comment by AlexandreAbraham** [comment]
>  But I was told to make it more specific

If I remember well, I told you to make the name of dataset folder more specific, not the name of the function itself. My concern is that, if a new version of SPM is released, we will probably drop the support of the old one. As a consequence, we will break all the scripts that uses `fetch_aal_spm_12`. An option would be to have a `fetch_aal` function and a `version="spm12"'` parameter for which we can change the default value (this is an example).

We'll wait for Gael to come back to take a final decision.

**Comment by MartinPerez** [comment]
ahhh, i really understood you wanted me to change everything, actually i was passing a version parameter at the beginning, I would completely agree with that, If you want I can implement the change, its a second... 

Then the parameter would be used also to create the dataset folder with the version attached, nonetheless I think it would be misleading for a user to have the parameter in the function exposed when at the moment there is no download of other versions, so maybe we would also need to point out in the docs that other versions are not downloadable yet?

**Comment by AlexandreAbraham** [comment]
I really don't know what is the right behavior here. So I suggest that we wait for Gaël's opinion before moving forward ;).

**Comment by AlexandreAbraham** [comment]
Ping @GaelVaroquaux

**Comment by GaelVaroquaux** [comment]
> Ping @GaelVaroquaux

.... @GaelVaroquaux is alive.

More seriously: fetch_atlas_aal is good. People don't even realize that
there is an SPM version of the AAL.
