### ISSUE TITLE
control of background image intensity in plotting.plot_stat_map

### ISSUE THREAD

**Issue by poldrack** [nilearn/nilearn#778]
currently there does not appear to be a way to control the intensity of the background image when using plot_stat_map - this leads to background images that are often too dark. it would be nice to have a separate knob to control intensity of the bg image.

**Comment by bthirion** [comment]
I've encountered this issue several time when preparing slides; So far the official solution was to use the 'backstage' function _plot_img_with_bg, and use the bg_vmax argument like in the following script:

from nilearn.plotting.img_plotting import _plot_img_with_bg, _load_anat
bg_img, black_bg, bg_vmin, bg_vmax = _load_anat(
        anat_img, dim=True, black_bg='auto')
display = _plot_img_with_bg(
        img=os.path.join(write_dir, 'weight_%03d.nii' % n_subjects),
        bg_img=bg_img,
        display_mode='z', 
        cut_coords=[0],
        threshold=0,
        figure=fig, vmax=3., bg_vmax=.8, bg_vmin=bg_vmin,
        black_bg=black_bg, resampling_interpolation='continuous')

The question is to have a compromise between a simple API on the one hand and allowing these tweaks for nice rendering. Given that plot_stat_map API is fairly complex already, your request is not a big change through.

**Comment by poldrack** [comment]
thanks! yes, I think it would be good to add it into the plot_stat_map function directly
cheers
rp

> On Sep 9, 2015, at 1:18 PM, bthirion <notifications@github.com> wrote:
> 
> I've encountered this issue several time when preparing slides; So far the official solution was to use the 'backstage' function _plot_img_with_bg, and use the bg_vmax argument like in the following script:
> 
> from nilearn.plotting.img_plotting import plot_img_with_bg, _load_anat
> bg_img, black_bg, bg_vmin, bg_vmax = _load_anat(
> anat_img, dim=True, black_bg='auto')
> display = _plot_img_with_bg(
> img=os.path.join(write_dir, 'weight%03d.nii' % n_subjects),
> bg_img=bg_img,
> display_mode='z', 
> cut_coords=[0],
> threshold=0,
> figure=fig, vmax=3., bg_vmax=.8, bg_vmin=bg_vmin,
> black_bg=black_bg, resampling_interpolation='continuous')
> 
> The question is to have a compromise between a simple API on the one hand and allowing these tweaks for nice rendering. Given that plot_stat_map API is fairly complex already, your request is not a big change through.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/nilearn/nilearn/issues/778#issuecomment-139034518>.
> 

—
Russell A. Poldrack
Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by GaelVaroquaux** [comment]
We should do this during the sprint.

**Comment by bthirion** [comment]
I can do that one  i think.

**Comment by bthirion** [comment]
Hm, I've just realized that the `dim` parameter simply does the trick.  I'm just going to add relevant documentation.

**Comment by lesteve** [comment]
But dim also affects the anat i.e reducing the contrast in the anat, doesn't it?

**Comment by GaelVaroquaux** [comment]
> But dim also affects the anat i.e reducing the contrast in the anat,
> doesn't it?

It affects only the anat, but I think that this is what we want here.
