### ISSUE TITLE
cache through spyder

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#783]
I used caching through spyder and when I run my code outside spyder it is recomputing everything. Is this expected behaviour ?

**Comment by lesteve** [comment]
> Is this expected behaviour ?

No. Do you have a self-contained example that reproduces the problem on your machine ?

**Comment by salma1601** [comment]
```python
import nilearn.datasets
import nilearn.input_data
atlas = nilearn.datasets.fetch_atlas_msdl()
dataset = nilearn.datasets.fetch_adhd()
masker = nilearn.input_data.NiftiMapsMasker(
    atlas.maps, resampling_target="maps", detrend=True,
    low_pass=None, high_pass=.01, t_r=2.5, standardize=False,
    memory='nilearn_cache', memory_level=1, verbose=2)
time_series = masker.fit_transform(dataset.func[0])
```
The output in spyder 
```python
[NiftiMapsMasker.fit_transform] loading regions from /home/sb238920/nilearn_data/msdl_atlas/MSDL_rois/msdl_rois.nii
[Memory]    0.0s, 0.0min: Loading filter_and_extract...
```
and when I run it outside spyder
```python
[NiftiMapsMasker.fit_transform] loading regions from /home/sb238920/nilearn_data/msdl_atlas/MSDL_rois/msdl_rois.nii
________________________________________________________________________________
[Memory] Calling nilearn.input_data.base_masker.filter_and_extract...
filter_and_extract('/home/sb238920/nilearn_data/adhd/data/0010042/0010042_rest_tshift_RPI_voreg_mni.nii.gz', 
```
etc.

**Comment by arthurmensch** [comment]
Spyder probably adds the current working directory to your Python path.
Check that the directory where you work contains your nilearn_cache
directory (as you probably use cache default behaviour).

**Comment by salma1601** [comment]
Yes, thanks !
spyder created nilearn_cache in the same folder where the code is located.

**Comment by salma1601** [comment]
I wasn't aware that setting memory='nilearn_cache' creates the nilearn_cache folder in the current directory. I thought it was always the same place.

**Comment by lesteve** [comment]
All right closing then.

I guess you can use an absolute path in your case. Not sure what best practices are, people who use joblib more than me can comment if they wish.
