### ISSUE TITLE
Image reordering still not robust :(

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#786]
...does still not seem to work properly in all scenarios. With ``interpolation=continuous`` I am still getting what looks like spline ringing effects.

**Comment by GaelVaroquaux** [comment]
> ...does still not seem to work properly in all scenarios. With
> interpolation= continuous I am still getting what looks like spline
> ringing effects.

But that's expected. Interpolation will create ringing. There are
ringing-free interpolation schemes but they are very costly and have
other problems.

**Comment by lesteve** [comment]
Closing then. Feel free to reopen if you feel strongly about this one but please provide a stand-alone script and a a picture to show more precisely what you mean.
