### ISSUE TITLE
Haxby dataset (Stimuli)

### ISSUE THREAD

**Issue by p-ghaemmaghami** [nilearn/nilearn#788]
Dear All,

I have some concerns about haxby (2001) dataset regarding stimuli presentation and decoding pipeline:

1) According to here: https://openfmri.org/dataset/ds000105, the number of presented stimuli is 48. Well, actually when someone download the dataset, there are 48 images per stimuli category (excluding “shoes” which is 47). However, in the description, it is written that, for each subject, per each run, all categories of stimuli (8 categories) were presented and each category was presented 24 sec in each run. Given the fact that the duration of the stimulus presentation is 500 ms with 1500 ms interval. this gives us 2400 ms/(500+1500) ms = 12 stimulus per each category in each run. Since every subject had undergone 12 runs. So the number of stimuli that subject had seen for each category is 12 (run) \* 12 (number of stimulus per object category for each run) = 144, and the total number of stimuli would be 144*8 = 1152. However it is said that subject were seen 48 stimuli !! 

2) Decoding pipeline code that is provided here: http://nilearn.github.io/auto_examples/plot_haxby_simple.html which is one-vs-one classification (face vs cat). In this example, they use voxels as features and volumes as samples. so for each category (e.g. face) we have 9 (volumes)*12(runs)=108 samples. based on these samples they did one vs one classification (using linear SVM). I have some concerns about the code! 
- we should assume that fMRI volumes are independent from each other. (otherwise the samples are not i.i.d)
- we should assume that presented stimulus for each volume is different. (otherwise the samples in training can be used in test in cross-validation)

plz correct me on these issues if I’m wrong on this!

3) For my ongoing project, i need to know the exact correspondence between the presented stimulus and the fMRI volume for all subjects. To explain it better i want to know what would subject x has seen at every specific time (or every specific volume). In fact i need to have the presented stimuli per volume. Since i need to extract the visual information from the presented stimulus, i need to have the stimulus (i.e. knowing the category would not be enough for what I’m doing now). Do you know if such information is available?

Thank you in advance. 

Best,
Pouya

**Comment by thomasbazeille** [comment]
Since this issue as been stalled for a while and the example using the dataset seems to work ok, maybe it can be closed ?
