### ISSUE TITLE
The docstring of nilearn.__init__ should list subpackages

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#789]
In the docstring of nilearn, we should list the subpackage (aside from _utils) with a short description of what's in it. The goal is to make it easier to users to know where to look to find a functionality.

The docstring of scipy could be an inspiration.

**Comment by aabadie** [comment]
I took the docstring of scipy as an example for documentating the top level __init__.py file. As mentionned here (https://docs.python.org/3.4/tutorial/modules.html#importing-from-a-package), I also defined and filled the __all__ attribute with the "public" submodules of nilearn.

We could also go further by writing the all docstring in all submodules.

**Comment by lesteve** [comment]
> We could also go further by writing the all docstring in all submodules.

I think it's probably overkill for now.

A couple of tips:
* double underscore does emphasis (aka bold) in markdown so you want to use backquotes to escape them, see this [link](https://guides.github.com/features/mastering-markdown/) for more details.
* using Fix #number in a PR description does automatically close the issue #number once the PR is merged
