### ISSUE TITLE
nilearn.check_cache_version => nilearn.CHECK_CACHE_VERSION

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#792]
nilearn.check_cache_version is a constant. As such, it should be ALLCAPS. The title says it all (and I think that we shouldn't worry about backward compatibility, given that it is probably not used very much).

**Comment by banilo** [comment]
I brought the same C-motivated argument a while ago. But last time, we decided against having all constant in capital letters because that is not Python-like, if I remember correctly.

**Comment by GaelVaroquaux** [comment]
> I brought the same C-motivated argument a while ago. But last time, we
> decided against having all constant in capital letters because that is
> not Python-like, if I remember correctly.

Quite the contrary: PEP8 agrees with me:
https://www.python.org/dev/peps/pep-0008/#constants

**Comment by banilo** [comment]
Great, I like big-lettered constants!

2015-10-13 22:41 GMT+02:00 Gael Varoquaux <notifications@github.com>:

**Comment by aabadie** [comment]
@GaelVaroquaux This one sounds (very) easy, I can work on it !

**Comment by aabadie** [comment]
2ef67d2 is small contribution to this issue.
