### ISSUE TITLE
copy_img has a side effect on image

### ISSUE THREAD

**Issue by arthurmensch** [nilearn/nilearn#793]
This is due to the use of non safe `get_data` in `copy_img`.

Typically this invalidate cache:

```python

def f(img):
    print('Not cached')

mem = Memory(cache_dir='nilearn_cache')
img = NiftiImage(np.ones(10, 10, 10, 10), affine=np.ones(4))

mem.cache(f)(img)
mem.cache(f)(img)
img2 = copy_img(img)
mem.cache(f)(img)
```

Output:
```
Not cached
Not cached
```

**Comment by GaelVaroquaux** [comment]
Good catch!

A PR to fix this would be great.

**Comment by arthurmensch** [comment]
Fix is straight forward, I just need to write a test and I will push it

**Comment by GaelVaroquaux** [comment]
> Fix is straight forward,

It is indeed, because you understand the package :)

**Comment by GaelVaroquaux** [comment]
@arthurmensch : can you either do this today, or help Aina do it

**Comment by GaelVaroquaux** [comment]
Cc @ainafp : I think that this is something that you could work on.

The idea is to use nilearn._utils.niimg._safe_get_data instead of the get_data method.

**Comment by ainafp** [comment]
@GaelVaroquaux @arthurmensch :

I changed it but it still creates a new image because it uses new_img_like() from nilearn.image.image
I can substitute the whole line and return just _safe_get_data(img). 
Is this fine? In this case, instead of 
```new_img_like(img, img.get_data().copy(), img.get_affine().copy(),  copy_header=True)```
it just makes a deep copy
```img = copy.deepcopy(img)```
if it is not cached inside _safe_get_data. 

If you agree I change it. I wrote the test based on what Arthur did.

**Comment by ainafp** [comment]
In new_img_like() in from nilearn.image.image, when copy_header is set to true, changing  header['scl_slope'], header['scl_inter'],  header['cal_max'] or header['cal_max'] change the value of the hash. 
``` 
img = Nifti1Image(np.ones((2, 2, 2, 2)), affine=np.eye(4))
joblib.hash(img)
img2 = new_img_like(img, np.ones((2, 2, 2, 2)), img.get_affine().copy(), copy_header=True)
joblib.hash(img)  
```

**Comment by ainafp** [comment]
Nevermind. It was just a copy.copy of the header inside new_img_like(). I changed it to copy.deepcopy()

**Comment by lesteve** [comment]
Have you opened a PR. This is the easiest way to comment on your changes.

**Comment by ainafp** [comment]
Done!
