### ISSUE TITLE
Use the new sphinx-gallery notebook-style example

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#796]
Now that sphinx-gallery has been merged in nilearn (hurray!!). We can start converting some example to use the notebook-style example.

The first candidate is probably the plotting examples.

**Comment by GaelVaroquaux** [comment]
For reference: the corresponding sphinx-gallery docs: http://sphinx-gallery.readthedocs.org/en/latest/tutorials/index.html#notebook-styled-examples

**Comment by lesteve** [comment]
Should we not do a sphinx-gallery release, revive #592 and merge it before we can think about using notebook-style examples in nilearn ?

**Comment by GaelVaroquaux** [comment]
> Should we not do a sphinx-gallery release, revive #592 and merge it before we
> can think about using notebook-style examples in nilearn ?

I don't know. I lost track :$

**Comment by lesteve** [comment]
Let's ask @Titan-C what he remembers !

**Comment by Titan-C** [comment]
yes we are missing a PyPI realease of sphinx-gallery with the notebook examples.
The we can rebase #592 to correctly adopt the images and references naming convention that meanwhile got adopted when the notebook examples pull request passed.

**Comment by lesteve** [comment]
It's probably worth looking at the issues (and me at my notes if I can find them) to see whether there were still things to iterate on before the next sphinx-gallery release. I seem to remember the naming conventions still weren't that consistent but I could be wrong.

**Comment by Titan-C** [comment]
I'm having a look. Some of your current examples already have the notebook sintax

**Comment by GaelVaroquaux** [comment]
I did this over the week end. Closing.
