### ISSUE TITLE
Small Rodent Neuroimaging plots in Python

### ISSUE THREAD

**Issue by TheChymera** [nilearn/nilearn#797]
I am looking for some python solutions to plot neuroimaging data from mice and rats.

I was pleased (and surprised) to see that nilearn offers some apparently quite nice plotting functions (at least for human data). I am wondering:
- Why does it make sense to package these plotting functions together with functions better described by ni_learn_? Would it not be more intuitive (and perhaps make the plotting function modules more readily recognisable as such)  to package them as "niplot" or something of the sort?
- Is there any (more-or-less) easy way to plot some rodent data with the functions currently offered by nilearn?

**Comment by AlexandreAbraham** [comment]
> Would it not be more intuitive (and perhaps make the plotting function modules more readily recognisable as such) to package them as "niplot" or something of the sort?

This has been discussed and the code is not mature enough to be separated from the core.

> Is there any (more-or-less) easy way to plot some rodent data with the functions currently offered by nilearn?

You can customize the background image used for regular plotting functions. For `plot_glass_brain`, the background template can be customized but it is not trivial for the moment.

What do you need exactly ?

**Comment by TheChymera** [comment]
Something liktthis would be really nice:

![mouse_fMRI](https://cloud.githubusercontent.com/assets/950524/10575113/abbf6ee6-765a-11e5-8c42-63c338b6c70a.jpg)

**Comment by GaelVaroquaux** [comment]
If you have a mouse anatomy and statistical maps as nifti files, you can use plot_stats_maps to do what you want.

**Comment by TheChymera** [comment]
what about the glass brain? Is drawing a set of contours myself the best way to go about it? any advice on how to do that?

**Comment by GaelVaroquaux** [comment]
The glass brain is going to be specific to realigned humain brain.

Sorry, there is no ways outlines can be automatized.

**Comment by eickenberg** [comment]
> what about the glass brain? Is drawing a set of contours myself the best
way to go about it? any advice on how to do that?

Glass Brain was made by hand. Take a look at

nilearn/nilearn/plotting/glass_brain_files/*.svg

You will see that there are three vector drawings. If you can create these
for the main gyri/sulci of the mouse brain, you can have a mouse glass
brain.

So it depends on how much effort you want to put into it.

Michael

**Comment by AlexandreAbraham** [comment]
I have met people that would like to substitute the SVG file by freesurfer images. Maybe we should allow that.

**Comment by GaelVaroquaux** [comment]
> I have met people that would like to substitute the SVG file by freesurfer
> images. Maybe we should allow that.

With what king of input format?

**Comment by AlexandreAbraham** [comment]
Replacing it with a PNG should be fairly easy. The user just has to be sure that the image is aligned with the original SVG (which is difficult in the case of a rodent... I agree).

**Comment by TheChymera** [comment]
I am here partly because I want to get away from freesurfer - which almost all modern plotting functionalities seem to depend on. For what it's worth I would recommend against depending on it, it depends onvery outdated versions of minc, and upstream is very non-responsive - even by scientific software standards...

**Comment by GaelVaroquaux** [comment]
In theory, I would be +1 for input of background as a PNG.

However, I worry a lot about people not realigning their backgrounds
well, and publishing plots that are incorrect.

Also, I am afraid that this feature is going to generate a lot of user
support problems (my brain is not well aligned, please help).

I am a bit unsure whether it is wise to open this pandora box.

**Comment by AlexandreAbraham** [comment]
> However, I worry a lot about people not realigning their backgrounds well, and publishing plots that are incorrect. 

This is already the case with the current background: we have no guarantee that the data provided is aligned with it.

Maybe we can give a choice at least between the SVG and a 3D image?

**Comment by TheChymera** [comment]
So if I want a rodent glass brain, "all" I have to do is take one outer and one inner structural  slice for each axis, import it into inkscape, draw some contours on top of it, delete the imported bitmap objects, and save teh documents? Is there anything I am missing about this which would make it particularly non-trivial?

What would the advantage of a PNG over a SVG be here? why would aligning to a PNG be more difficult than aligning to a SVG?

**Comment by eickenberg** [comment]
On Mon, Oct 19, 2015 at 2:20 PM, Horea Christian <notifications@github.com>
wrote:

> So if I want a rodent glass brain, "all" I have to do is take one outer
> and one inner structural slice for each axis, import it into inkscape, draw
> some contours on top of it, delete the imported bitmap objects, and save
> teh documents? Is there anything I am missing about this which would make
> it particularly non-trivial?
>
Yes, you choose a slice of your normalized rodent brain (if this exists)
and use inkscape to draw the contours of relevance. For your purposes you
may just replace the human glass brain with yours. Otherwise the code needs
to be changed to allow different options.


> What would the advantage of a PNG over a SVG be here? why would aligning
> to a PNG be more difficult than aligning to a SVG?
>
I don't see a difference. It would just be to support more background
images. There is no realignment: The image is considered to be in MNI space
for human brains. It is then resampled if necessary to the right resolution
and plotted.

**Comment by GaelVaroquaux** [comment]
> Maybe we can give a choice at least between the SVG and a 3D image?

Maybe just a 3D mask image and we compute the online of it (easy, just
compute the max along the direction and do a contour in matplotlib?

This would be open for contributions, but I don't see my team investing
in it in the short term, though, given how overcommitted we are.

**Comment by TheChymera** [comment]
Ok, so I will be working with [this](http://chymera.eu/nie/QBI_atlas100.nii) mouse brain template - and I would like to draw a glass brain for it.

I see that the human glass brain `.svg` graphics fill the "pages" of the respective documents to the brim. As you can easily see, my mouse brain template has a bit of black padding around the edges. Should I preserve this in my glass brain `svg`?

**Comment by TheChymera** [comment]
Also, once I finish drawing the images - how can I actually use them for plotting?

**Comment by TheChymera** [comment]
Does this look like a passable coronal projection to you guys?

http://chymera.eu/img/coronal.svg
