### ISSUE TITLE
Failing tests on windows

### ISSUE THREAD

**Issue by aabadie** [nilearn/nilearn#809]
As reported in #808, a lot of nilearn tests are failing on windows. There's an issue with the path ot the datasets.

Here is one of the failing ci run : https://ci.appveyor.com/project/aabadie/nilearn/build/job/htt98au0b1j0hxnq

**Comment by lesteve** [comment]
The path problems should be easy to fix.

The `nilearn.tests.test_signal.test_clean_confounds` one not so sure.

**Comment by aabadie** [comment]
> The path problems should be easy to fix

It seems the environ variables are not correctly set on windows. Trying to fix this.

**Comment by aabadie** [comment]
> It seems the environ variables are not correctly set on windows. Trying to fix this.

Forget about this. The problem is in the logic of _get_dataset_dir

**Comment by lesteve** [comment]
Also chatting with @GaelVaroquaux you want to set-up the tests on a 64bit architecture and forget about the 32bit ones. You are going to be very limited memory-wise if you want to use nilearn on a 32bit platform.

**Comment by aabadie** [comment]
> You are going to be very limited memory-wise if you want to use nilearn on a 32bit platform

I'm testing locally using a 64 bit version of python and also have the same "OverflowError: Python int too large to convert to C long" issue.

I could hopefully fix the path related issues.

**Comment by aabadie** [comment]
I created PR #814 

Remaining issues:
* "OverflowError: Python int too large to convert to C long" raised in mass_univariate "permuted_ol" function. Some help will be greatly appreciated for this one.
* More problematic is the one concerning the access to multiple opened file at the same time on windows. For example:
```python
with tempfile.NamedTemporaryFile(suffix='.txt') as fp:
    f = open(fp.name, 'w+b')
    f.write('toto')
    f.close()
```
will fail with the error message: """PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ALEXAN~1\\AppData\\Local\\Temp\\tmpuuihk6z6.txt"""
Same story with:
```python
with tempfile.NamedTemporaryFile(suffix='.txt') as fp:
    with open(fp.name, 'w+b') as fpp:
        f.write('toto')
```
And this strategy is used intensively in nilearn/plotting/tests/test_img_plotting.py. I could fix the issue here using a temporary string variable and process the filename outside the "with" block.
But it's the same kind of context manager behavior used with the function write_tmp_imgs in _utils/testing.py to remove the temporary files on the fly. Here it breaks quite a few tests.

**Comment by GaelVaroquaux** [comment]
> with tempfile.NamedTemporaryFile(suffix='.txt') as fp:
>     f = open(fp.name, 'w+b')
>     f.write('toto')
>     f.close()

I think that this code is wrong. It should be:

<pre>
with tempfile.NamedTemporaryFile(suffix='.txt', mode='w+b') as f:
    f.write('toto')
    f.close()
</pre>

**Comment by aabadie** [comment]
@GaelVaroquaux, I agree. But now in the test (see test_img_plotting.py, function test_plot_anat), we use it like what I described above:
```python
with tempfile.TemporaryFile(suffix='.png') as fp:
    z_slicer.savefig(fp.name) # savefig open another descriptor internally => permission error
```

Using the code below works (of course) but I need a confirmation of the solution:
```python
filename = ""
with tempfile.TemporaryFile(suffix='.png') as fp:
    filename = fp.name

# tempfile has been removed when exiting the previous context
z_slicer.savefig(filename) # Opens and creates the file again
os.remove(filename)
```

**Comment by aabadie** [comment]
@GaelVaroquaux, about the overflow error, I made a simple test:
```python
import numpy as np
a = np.arange(10)
print(a.dtype)
```
* result on windows (using anaconda python 3.4, 64 bits): int32
* result on linux (using same anaconda python 3.4, 64 bits): int64

I think built numpy/scipy provided by anaconda are 32 bits on windows which explains this issue.

**Comment by GaelVaroquaux** [comment]
> print(a.dtype)

>   • result on windows (using anaconda python 3.4, 64 bits): int32
>   • result on linux (using same anaconda python 3.4, 64 bits): int64

> I think built numpy/scipy provided by anaconda are 32 bits on windows which
> explains this issue.

Can you try with a = np.zeros(10) and tell us what you get?

**Comment by aabadie** [comment]
> Can you try with a = np.zeros(10) and tell us what you get?
float64...I'm lost

**Comment by GaelVaroquaux** [comment]
> filename = ""
> with tempfile.TemporaryFile(suffix='.png') as fp:
>     filename = fp.name

> # tempfile has been removed when exiting the previous context
> z_slicer.savefig(filename) # Opens and creates the file again
> os.remove(filename)

I think that in this situation you should use tempfile.mktemp. Now this
is not a context manager, so you will also have to use a try/finally
block to make sure that the file is removed.

**Comment by GaelVaroquaux** [comment]
>     float64...I'm lost

OK, so it's indeed a 64bit install, but the default integer is 32bit.
Interesting.

**Comment by aabadie** [comment]
> OK, so it's indeed a 64bit install, but the default integer is 32bit.
> Interesting.

I created #819 which hopefully (and magically) fixed the issue

**Comment by GaelVaroquaux** [comment]
With the 2 PRs merged, is there still something failing under Windows?

**Comment by aabadie** [comment]
> With the 2 PRs merged, is there still something failing under Windows?


@GaelVaroquaux, yes PR #814 is still pending. There are still other problems with context manager in _create_tmp_imgs test utility function that I want to fix.

**Comment by GaelVaroquaux** [comment]
OK, I just merged #814 
I'll let you tackle the rest and create a PR.

**Comment by aabadie** [comment]
We are getting closer to complete this issue. Just a summary of what is remaining:
* Lots of remaining issues like: 
```
  File "C:\softs\src\nilearn\nilearn\_utils\testing.py", line 144, in write_tmp_imgs
    os.remove(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ALEXAN~1\\AppData\\Local\\Temp\\nilearn_iu926ggu.nii'
```
I tried what @GaelVaroquaux suggested IRL without success. I also tried to remove the contextlib decorator and get the filenames using list(write_tmp_imgs()) but then it breaks the initial test logic. I need some help on those ones.
* Appveyor raises 3 other issues with py27 but I can't reproduce them locally, see the 3 last ones [here](https://ci.appveyor.com/project/nilearn-ci/nilearn/build/1.0.14/job/nlmqm87exiihnss6)
* I fixed a couple of other ones : one write permission issue was remaining and there was an issue with some the mode parameter of some call to np.memmap.

**Comment by aabadie** [comment]
@GaelVaroquaux, all tests are passing now on Windows. Just to let you know, we disabled matplotlib as it makes the python interpreter crash at exit with python 3.4. I cannot reproduce this behavior on my system. It's a bit weird.

All the rest is ok.

Maybe we can close this issue (along with #804 until the webhook is added to github).

**Comment by lesteve** [comment]
> Maybe we can close this issue (along with #804 until the webhook is added to github).

For the record, I have added the AppVeyor webhook but it doesn't show in the PR at the moment. I need to investigate more ...

**Comment by aabadie** [comment]
> For the record, I have added the AppVeyor webhook but it doesn't show in PRs at the moment. I need to investigate more

I confirmed the request sent to nilearn-ci (it uses my personal email). Is it ok now ?

**Comment by lesteve** [comment]
To make a long story short, I had to give nilearn-ci write permission in github, revoke the github link you made in AppVeyor and reauthorize it as nilearn-ci.

One of the resource that was actually helpful:
http://help.appveyor.com/discussions/kb/4-show-multiple-statuses-in-github-pull-requests#comment_36808437

I think this should be OK now, look at https://github.com/nilearn/nilearn/pull/613 (The failure is expected by the way)

**Comment by lesteve** [comment]
Closing this one I'll open a new issue about the matplotlib segmentation fault on AppVeyor.
