### ISSUE TITLE
Globbing should be advertised in doc/examples.

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#810]

**Comment by lesteve** [comment]
It is already in doc/manipulating_visualizing/manipulating_images.rst. Mentioning where it could be added would help.

**Comment by aabadie** [comment]
> It is already in doc/manipulating_visualizing/manipulating_images.rst. Mentioning where it could be added would help.

+1 ;)

**Comment by AlexandreAbraham** [comment]
@GaelVaroquaux, have you some specific location in mind?

**Comment by GaelVaroquaux** [comment]
> It is already in doc/manipulating_visualizing/manipulating_images.rst.
> Mentioning where it could be added would help.

Maybe in the "Getting started", where we talk about plotting, say, in a
sidebar.

We need to put ourselves in the shoes of the user. How does the user
discover this feature? I am not saying that it is easy to figure this
out, but we need to think about it.

**Comment by man-shu** [comment]
Reviving this discussion, I think [this introductory example](https://nilearn.github.io/stable/auto_examples/00_tutorials/plot_3d_and_4d_niimg.html) would be a good candidate.

As of now, the plotting is shown on a single file fetched from neurovault, but to glob we need to fetch several files, for example, with [`nilearn.datasets.fetch_mixed_gambles`](https://nilearn.github.io/stable/modules/generated/nilearn.datasets.fetch_mixed_gambles.html#nilearn-datasets-fetch-mixed-gambles). So if this sounds good I could:

- swap the [`datasets.fetch_neurovault_motor_task`](https://nilearn.github.io/stable/modules/generated/nilearn.datasets.fetch_neurovault_motor_task.html#nilearn.datasets.fetch_neurovault_motor_task) with [`datasets.fetch_mixed_gambles`](https://nilearn.github.io/stable/modules/generated/nilearn.datasets.fetch_mixed_gambles.html#nilearn-datasets-fetch-mixed-gambles) for `n` subjects.
- show possibility of globbing over these subjects (other than the dictionary the fetcher already returns) with `image.mean_img` and plotting this mean stat map.

**Comment by Remi-Gau** [comment]
That sounds good though "a bit abstract" (sorry I have not had my second coffee yet), so maybe open a quick draft PR to show what you mean.

**Comment by man-shu** [comment]
Yes, on it!
