### ISSUE TITLE
Globbing should expand user.

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#811]
Globbing is good but we should also expand `~` to user home directory.

**Comment by GaelVaroquaux** [comment]
Cc @aabadie : do you want to do this during the sprint (and add it to the docs).

**Comment by aabadie** [comment]
@GaelVaroquaux, I'll take it.

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux, I'll take it.

No hurry, by the way. I don't think that we should try to squeeze this in
for the 0.2 release.
