### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ignatenkobrain** [nilearn/nilearn#815]
Hi, is there any plans to support python 3? At least 3.4. I'd want to have it because I'm packaging some stuff for Fedora which uses nilearn and I'd want to provide python2 and python3 in the same time.

**Comment by GaelVaroquaux** [comment]
Python 3 is supported. As you can see, the tests pass under Python 3:
https://travis-ci.org/nilearn/nilearn/builds/88787892

With regards to packaging, thanks a lot! We are hoping to release version
0.2 in a few weeks.

**Comment by GaelVaroquaux** [comment]
Closing, but feel free to continue the discussion if something is unclear.

**Comment by ignatenkobrain** [comment]
```python
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic'
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    _VERSION_GLOBALS = load_version()
  File "setup.py", line 22, in load_version
    exec(fp.read(), globals_dict)
  File "/usr/lib64/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 116: ordinal not in range(128)
error: Bad exit status from /var/tmp/rpm-tmp.8WC5xi (%build)
```

**Comment by ignatenkobrain** [comment]
Ah, I got it. I need to set LC_ALL="en_US.UTF-8". Thanks!

**Comment by GaelVaroquaux** [comment]
> Ah, I got it. I need to set LC_ALL="en_US.UTF-8". Thanks!

OK, this is interesting. Let me try to reproduce the problem. What's your
local? "LC_ALL=ru_RU.UTF-8" ?

**Comment by ignatenkobrain** [comment]
`'SHELL': '/bin/bash', 'TERM': 'vt100', 'LANG': 'en_US.utf8', 'LC_MESSAGES': 'C'`

**Comment by GaelVaroquaux** [comment]
> 'SHELL': '/bin/bash', 'TERM': 'vt100', 'LANG': 'en_US.utf8', 'LC_MESSAGES': 'C'

Darn, I cannot reproduce. I must be missing something

**Comment by ignatenkobrain** [comment]
don't worry. that envvars in chroot for building RPM package, in user environment it's okay by default =)

**Comment by GaelVaroquaux** [comment]
OK, I've tried harder, but I cannot reproduce. Let's hope that nobody
else will hit this.

**Comment by ignatenkobrain** [comment]
Do you want me to provide environment for you ?)

**Comment by ignatenkobrain** [comment]
I already saw this issue with other pkgs so likely issue in mock utility for rpm

**Comment by GaelVaroquaux** [comment]
> Do you want me to provide environment for you ?)

Only if it's super easy. I would have liked to fix that in our codebase.
