### ISSUE TITLE
cannot fetch atlas_harvard_oxford

### ISSUE THREAD

**Issue by cinvro** [nilearn/nilearn#826]
dataset = datasets.fetch_atlas_harvard_oxford("cort-maxprob-thr0-1mm")

give following errors: 

URLError: urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

**Comment by GaelVaroquaux** [comment]
This is an SSL certificate problem.

@AlexandreAbraham : should be simply using the HTTP URL, instead of the HTTPS one? I checked and it works.

**Comment by AlexandreAbraham** [comment]
I fixed the URL. @cinvro, could you try again with the last version of the code?

**Comment by cinvro** [comment]
It works now. Thank you @AlexandreAbraham @GaelVaroquaux .

**Comment by GaelVaroquaux** [comment]
OK, so I close the issue.
