### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#830]
In #826, a user could not download an atlas because of SSL certificate verification error. He was probably behind a reverse proxy.

First, I think that we should favorize HTTP over HTTPS. I will make a PR to remove it where it is not necessary.

Second, it is possible to tell Python to ignore SSL verification. Should we do that? Ping @GaelVaroquaux .

**Comment by GaelVaroquaux** [comment]
> First, I think that we should favorize HTTP over HTTPS. I will make a PR to
> remove it where it is not necessary.

+1

> Second, it is possible to tell Python to ignore SSL verification.
> Should we do that? Ping @GaelVaroquaux .

+1

**Comment by KamalakerDadi** [comment]
> First, I think that we should favorize HTTP over HTTPS. I will make a PR to remove it where it is not necessary.

If you haven't started, can I address this in Megatrawls PR ?

**Comment by AlexandreAbraham** [comment]
You can take care of it but in a separated PR.

**Comment by KamalakerDadi** [comment]
I would replace all https to http? Is it not necessary for all of them ?

**Comment by AlexandreAbraham** [comment]
In a first time, we can replace the URLs that works in http, typically nitrc ones. In a second time, we can disable the certificate checking directly into the download request.

**Comment by KamalakerDadi** [comment]
Ok Thanks.

**Comment by GaelVaroquaux** [comment]
@aabadie : maybe you can take this one over?

**Comment by AlexandreAbraham** [comment]
@aabadie : I'll take a quick look at it.

**Comment by AlexandreAbraham** [comment]
A cross-version solution is described in this thread: http://stackoverflow.com/questions/19268548/python-ignore-certicate-validation-urllib2

I'll switch task for the moment and come back at it afterward. Do not hesitate to solve the problem if you have time.

**Comment by AlexandreAbraham** [comment]
I'm on it.

**Comment by AlexandreAbraham** [comment]
I am in favor of closing this one: I was not able to replicate the original error (the behavior is very random depending on the certificate problem) and there is no trivial cross-version solution. The python package requests, used to simplify the handling of HTTP requests, has a flag to disable SSL verification. THe best option if we want to get rid of these errors may be to rely on it.

**Comment by aabadie** [comment]
+1 for Requests. The API is great.

**Comment by GaelVaroquaux** [comment]
-1 on dependencies.

Let's close this.
