### ISSUE TITLE
circular importing errors

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#835]
problem when trying to port code from `RegionExtractor` to `nilearn.image.image`. Because of this "global imports" problem, I have imported internally whichever necessary. It worked.

But, I think we should fix this problem. To not to get the same problem to others. 
Discussions and ideas are welcome.

This is out of box but if anybody wants why I am doing this. please have a look at my `RegionExtractor` PR to-do list.

**Comment by lesteve** [comment]
This would be great to fix that. This just needs a bit of thought about which direction the dependency should flow between packages/modules and probably some moving around.

Maybe something to do after the release so that we have more time to catch bugs.

**Comment by AlexandreAbraham** [comment]
I see the problem for `masking` but I am doubtful for `reampling`. However, these problems are known. Let's move on and fix that later.

**Comment by lesteve** [comment]
>> Maybe something to do after the release so that we have more time to catch bugs.

> Let's move on and fix that later.

Looks like we agree ...

**Comment by KamalakerDadi** [comment]
Should we target this for 0.2.1 release ?
