### ISSUE TITLE
Segmentation fault on AppVeyor when installing matplotlib

### ISSUE THREAD

**Issue by lesteve** [nilearn/nilearn#836]
The segmentation fault happens after running the tests. I was able to reproduce it on my laptop.

For now we don't install matplotlib on AppVeyor meaning that the plotting tests are not run. This was a stop-gap solution to get the AppVeyor continuous integration up and running.

A few of suggestions:
* try to install matplotlib with conda rather than pip. Full disclosure I had trouble when doing that on my laptop (unable to import matplotlib._png if I remember correctly), but it's worth a try.
* try to install different matplotlib/numpy versions to see whether the problem persists.

**Comment by aabadie** [comment]
If you agree, I'll have a look at this issue in the coming days

**Comment by GaelVaroquaux** [comment]
> If you agree, I'll have a look at this issue in the coming days

That would be great. Maybe report upstream on the matplotlib tracker, if
you can get a good reproducible case and a c-level stack trace.
