### ISSUE TITLE
Add fetch AAL2 for SPM12

### ISSUE THREAD

**Issue by alexsavio** [nilearn/nilearn#840]
Are you interested in a `dataset.fetch_atlas_aal2_spm12` function?
http://www.gin.cnrs.fr/AAL2

**Comment by GaelVaroquaux** [comment]
What are the differences in terms of the Atlas?

**Comment by alexsavio** [comment]
It has an "Implementation of a new parcellation of the orbitofrontal cortex in the automated anatomical labeling atlas". Rolls ET, Joliot M & Tzourio-Mazoyer N (2015) . NeuroImage 0.1016/j.neuroimage.2015.07.075.
![the new parcellation](http://www.gin.cnrs.fr/IMG/png/figure_aal2.png)

I am having a small issue working on these AAL2 files though. The voxel values in the .txt labels file don't match the voxel values. The voxel values have a '01' or '02' "appended" to them depending if it is left or right hemisphere. Does this sound familiar to you?

On the other hand, my boss says that AAL is not very precise (I'm not the physician to argue), in fact I will be using the Hammer atlas instead. This is from http://www.brain-development.org/
AFAIK adding this to nilearn requires a license acceptance though.

**Comment by GaelVaroquaux** [comment]
> On the other hand, my boss says that AAL is not very precise (I'm not the
> physician to argue),

Yes, it's horrible. We have it because it is standard.

> in fact I will be using the Hammer atlas instead. This is
> from http://www.brain-development.org/
> AFAIK adding this to nilearn requires a license acceptance though.

:(

It's thus probably not possible to have it, unless they are willing to do
a specific arrangement.

**Comment by alexsavio** [comment]
For me it is not an issue. It would be nice to have it here though.
Would you like to add it to the `datasets` module? I don't mind contacting them.

**Comment by GaelVaroquaux** [comment]
> Would you like to add it to the datasets module? I don't mind
> contacting them.

It would be fantastic if you would contact them. We can put a note in the
documentation stipulating the conditions of use. We cannot put something
where there is an action from the user, as things need to be able to run
without user intervention, eg on clusters.

**Comment by alexsavio** [comment]
We tried, but he is not responding anymore. :/

Thanks for the intention.
