### ISSUE TITLE
gzipGzipFile.max_read_chunk does not exist in Python 3.5

### ISSUE THREAD

**Issue by bcipolli** [nilearn/nilearn#843]
See https://github.com/nipy/nibabel/issues/209 for more info. This property seems to have been removed in Python 3.5, so read performance likely will revert to the unacceptably slow speed.

in https://github.com/nilearn/nilearn/blob/master/nilearn/__init__.py#L48 :

```
# Monkey-patch gzip to have faster reads on large gzip files
if hasattr(gzip.GzipFile, 'max_read_chunk'):
    gzip.GzipFile.max_read_chunk = 100 * 1024 * 1024  # 100Mb
```

**Comment by GaelVaroquaux** [comment]
Indeed, we have observed very slow I/O at the lab.

That explains it.

We'll need to find a solution (I have no idea which one, though :$), because something like the human brain project becomes untractable.

**Comment by lesteve** [comment]
> Indeed, we have observed very slow I/O at the lab.

> That explains it.

:confused: Is any one using Python 3.5 for research at the lab?

**Comment by AlexandreAbraham** [comment]
> We'll need to find a solution (I have no idea which one, though :$)

If I'm not mistaken, it has been replaced by `io.DEFAULT_BUFFER_SIZE`.

**Comment by GaelVaroquaux** [comment]
> If I'm not mistaken, it has been replaced by io.DEFAULT_BUFFER_SIZE.

Great!!!!! Let's fix it, then.

**Comment by GaelVaroquaux** [comment]
> :confused: Is any one using Python 3.5 for research at the lab?

@arthurmensch is, I believe

**Comment by AlexandreAbraham** [comment]
> ￼ Is any one using Python 3.5 for research at the lab?

I use 3.4.

> Great!!!!! Let's fix it, then.

This is not 100% sure but I have no time to test it. I just happened to have python3.5 source code on my box so I took a quick glance.

**Comment by lesteve** [comment]
For the record, the commit removing max_read_chunk is: python/cpython@845155b. Haven't tried to look into it more than that.

**Comment by arthurmensch** [comment]
A nibabel fix now permits to read > 4GB gz files (e.g. HCP) on Python 3. Performance is similar to the one in python 2, should we fix the monkey patching ?

**Comment by GaelVaroquaux** [comment]
> should we fix the monkey patching ?

Yes. We should strive to always be performant with as little user
intervention as possible.

**Comment by GaelVaroquaux** [comment]
Has this been fixed? It has in nibabel, but how about our monkey patching?

**Comment by bthirion** [comment]
Fixed AFAIK.
