### ISSUE TITLE
Implement fslmaths operators like : -add, -sub, -mul, -div, -mean, -std, etc.

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#847]
In the spirit of the mean_img, iter_img, handy functions which are now part of nilearn, It'll be nice to have the full `fslmaths`  stack of operators implemented. We do such operations all the time on niimgs.

**Comment by AlexandreAbraham** [comment]
The easiest way would be to extend all numpy operators to niimg (just by applying them on the arrays if they have the same affine).

**Comment by eickenberg** [comment]
or more generally the same underlying voxel grid

I like the idea. I am assuming people coming from fsl would really like to
see this. Has there been any demand from outside for this?

**Comment by GaelVaroquaux** [comment]
What's the signature you have in mind for the function?

We could try to have something that takes an expression. For instance

<pre>
math_img(formula, **variables)
</pre>

where "formula" would be evaluated in a numpy context merge with
**variables, enabling the following

<pre>
z_diff_img = math_img("np.mean(img1, axis=-1) / np.std(img1, axis=-1) "
	    " - np.mean(img2, axis=-1) / np.std(img2, axis=-1) ",
            img1=img1, img2=img2)
</pre>

**Comment by dohmatob** [comment]
I had something very basic in mind. For example,

`div_img(img1, img2)`: returns voxel-wise division of `img1` by `img2`
`sub_img(img1, img2)`: ...
`std_img(img1)`: ...
`add_img(im1, img2)`: ...

**Comment by GaelVaroquaux** [comment]
My proposal isn't hard to implement, and it avoids an explosion of
functions (think that users start wanting the log, or the
exponentional...)

**Comment by eickenberg** [comment]
and having a subset of these in `__add__`, `__mul__`, `__rmul__`, etc:
advisable or not?

**Comment by AlexandreAbraham** [comment]
The problem is that a list of img is a valid img so you would have to override list operators.

**Comment by dohmatob** [comment]
- If users ask for `log` and `softmax`, we simply say No.
- Really, all I had mind was do something along the the spirit of the `mean_img` by implementing: add_img, sub_img, std_img, and add_img. Not implement a sandbox for executing arbitrary lambda functions :). This looks like overkill, and answers a different question.

**Comment by GaelVaroquaux** [comment]
> and having a subset of these in `__add__`, `__mul__`, `__rmul__`, etc:
> advisable or not?

No. Implicit is better than explicite. We don't want users to confuse
niimgs with arrays.

**Comment by GaelVaroquaux** [comment]
> No. Implicit is better than explicit.

I mean "explicit is better than implicit" :)

**Comment by GaelVaroquaux** [comment]
>   • If users ask for log and softmax, we simply say No.

Until you, as a user want it, and then you'll open an issue asking if it
can be implemented :).

>   • Really, all I had mind was do something along the the spirit of the
>     mean_img by implementing: add_img, sub_img, std_img, and add_img.
>     Not implement a sandbox for executing arbitrary lambda functions
>     :). This looks like overkill, and answers a different question.

I disagree. Why is 'sub' more imortant than log? Why aren't
multiplication and division not on your list? Where is the cutoff?

**Comment by dohmatob** [comment]
They're there. See the list I first posted:
`div_img(img1, img2)`: returns voxel-wise division of `img1` by `img2`
`sub_img(img1, img2)`: ...
`std_img(img1)`: ...
`add_img(im1, img2)`: ...

mul is more basic than log. The cutoff is: div, std, add, sub. Anything else can be constructed from these (including log) :)

**Comment by dohmatob** [comment]
OK, maybe these are very specific needs, and the general good doesn't seem apparent. The issue may be ignored.

**Comment by GaelVaroquaux** [comment]
No, I think that it's a good suggestion, and we need to talk it like
fslmath: with a fairly general solution. It's actually very easy to code.
It just requires an 'eval', after checking that every is on a common
affine.

**Comment by AlexandreAbraham** [comment]
> OK, maybe these are very specific needs, and the general good doesn't seem apparent. The issue may be ignored.

I don't think so. These functions could help shortening the code in several functions. I also had this idea but I was not sure about how to implement it. The "formula" proposition of Gael is tempting but I'm afraid of the amount work in the handling of errors, etc...

**Comment by bcipolli** [comment]
I like this suggestion, but I kind of lean towards having the simple functions. They're much more readable than their `math_img` counterparts. I worry less about function bloat; they can all be contained in a subpackage. `numpy` has the same issue (function bloat), and we just use the docs.

All of the basic functions could be thin wrappers around `math_img`. It would also avoid having different interfaces for math operations on lists (e.g. individual functions, like `mean_img`) and single images (`math_img`).

**Comment by GaelVaroquaux** [comment]
> I worry less about function bloat; they can all be contained in a
> subpackage. numpy has the same issue (function bloat), and we just use
> the docs.

But then we need to maintain them :(.

Generating them won't be easy, because we'll have to encode the signature
of all functions. This is I guess feasible, but it won't give trivially
easy code, and will thus have a maintainance burden.

**Comment by KamalakerDadi** [comment]
```math_img``` does this requirement.

**Comment by thomasbazeille** [comment]
As Kamalaker said, this could be closed, there are posts on Neurostars about this. Maybe the solution to usual requirements could be made more explicit in documentation but this is clearly a different issue
