### ISSUE TITLE
Undocumented SpaceNet attributes

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#848]
At least the following attributes have no documentation in the docstring:  `best_model_params_` and `alpha_grids_`

**Comment by banilo** [comment]
Good! Additionally, it is perhaps not sufficiently clear whether and how specifying a list to ``l1_ratios`` performs hyperparameter tuning. The practical question could be what the difference is to running ``SpaceNet*`` wrapped by sklearn's GridSearchCV.

**Comment by dohmatob** [comment]
By doing  cross val on `l1_ratios` ourselves, we fill more holes on the joblib computation grid. Of course you can always do GridSearchCV with SpaceNet as the estimator. Note that the alpha grid is dependent on which `l1_ratio` you're looking at.

**Comment by ainafp** [comment]
I'm on this one. 

Few issues found already:
* ```cv_scores_``` shape was wrongly documented
* ```alpha_grids_``` doc missing
* ```best_model_params_``` doc missing and format list(list()) to be changed to ndarray
* ```alpha_``` is no longer an attribute
* ```all_coef_ , classes_ , coef_img_ , mask_ , memory_ , n_classes_ , w_ , ymean_ , Xmean_ , Xstd_ ``` attributes are missing

**Comment by KamalakerDadi** [comment]
Closing this one as this is fixed with PR #1573
