### ISSUE TITLE
Move nilearn.group_sparse_covariance in nilearn.connectome

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#850]
Now that the tangent space PR is merged, we have a 'nilearn.connectome' namespace.

We should move the group_sparse_covariance file in it, and import the objects in nilearn/connectome/__init__.py (and also move tests, and update the docs).

The goal would be to make nilearn.connectome a one-stop entry point to dealing with connectivity matrices.

**Comment by KamalakerDadi** [comment]
I will take care of this.

**Comment by GaelVaroquaux** [comment]
Thanks, @KamalakerDadi . I am assigning it to you.

**Comment by AlexandreAbraham** [comment]
Fixed.
