### ISSUE TITLE
Binarize image option for nilearn.image

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#859]
Often times we need to convert floating point images to corresponding binarize 0-1 image. It would just be fantastic to have a neat nilearn function to do this in various flavors.

**Comment by KamalakerDadi** [comment]
I think I am missing the priority here. May be before this we need to address this circular importing error #835 ?

**Comment by AlexandreAbraham** [comment]
This is linked to #847, we should probably propose a set of tools for image manipulation.

**Comment by thomasbazeille** [comment]
Was solved by #982 as #847 so it can be closed.

For common questions see also https://neurostars.org/t/how-can-i-binarize-and-threshold-images-in-nilearn/396
