### ISSUE TITLE
Switch all Haxby examples to use the 2nd subject rather than the 1st

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#860]
The first subject in the Haxby dataset is an unusually good subject. Prediction with this subject is too easy compared to any usual situation.

This is not the case for the second one. We should be using the second in our examples.

The drawback is that, that we would need to switch the default of fetch_haxby from n_subjects=1 to n_subjects=2, which will entail more download, and thus a heavier load during group tutorial. I think that it is worth it.

**Comment by AlexandreAbraham** [comment]
I am not against having an additional parameter to download a given subject.

**Comment by GaelVaroquaux** [comment]
> I am not against having an additional parameter to download a given subject.

That's a good idea. Deprecating n_subjects, and replacing it by an
argument 'subjects' that would take a list, and would be '(2, )' by
default.

I am +1 on such proposal.
