### ISSUE TITLE
Add globbing to nilearn._utils.niimg_conversions._iter_check_niimg

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#866]
We should add globbing to nilearn._utils.niimg_conversions._iter_check_niimg

We should also add a specific error message to this function when the list is empty raising a valueerror saying explicitly that an empty list was given.

**Comment by GaelVaroquaux** [comment]
Cc @aabadie

**Comment by aabadie** [comment]
I'll have a look (sorry I missed it)

**Comment by aabadie** [comment]
Looking at the code  `_iter_check_niimg` internally calls `check_niimg`. If no file is found when consuming the generator, a ValueError is raise by `check_niimg`.

**Comment by lesteve** [comment]
Thinking about it, what is wrong with `nilearn._utils.check_niimg('~/*.nii', return_iterator=True)` or its check_niimg_4d equivalent?

**Comment by aabadie** [comment]
> Thinking about it, what is wrong with nilearn._utils.check_niimg('~/*.nii', return_iterator=True) or its check_niimg_4d equivalent?

`_iter_check_niimg` also do some resampling if needed.

**Comment by GaelVaroquaux** [comment]
> Thinking about it, what is wrong with nilearn._utils.check_niimg('~/*.nii',
> return_iterator=True) or its check_niimg_4d equivalent?

You are however right that we need to add seealsos in the docstring of
these guys. Seealsos are useful for developers, not only for users, as I
had not in mind the equivalence between these guys.

**Comment by aabadie** [comment]
> You are however right that we need to add seealsos in the docstring of these guys. Seealsos are useful for developers, not only for users, as I had not in mind the equivalence between these guys.

Should this be added to the corresponding PR?

**Comment by GaelVaroquaux** [comment]
> Should this be added to the corresponding PR?

I think that it would be great. I would certainly make the codebase
better.

**Comment by lesteve** [comment]
Can we try to have the discussion only in only one place about `_iter_check_niimg` vs `check_niimg(..., return_iterator=True)`, i.e. the associated PR.

**Comment by aabadie** [comment]
> Can we try to have the discussion only in only one place

+1

**Comment by GaelVaroquaux** [comment]
I'd rather simply not have this discussion now, and focus on releasing the
0.2.

**Comment by lesteve** [comment]
> I'd rather simply not have this discussion now, and focus on releasing the 0.2.

Same thing.
