### ISSUE TITLE
Contours on glass brain

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#868]
This is possible but we should advertise it in an example.

**Comment by GaelVaroquaux** [comment]
> This is possible but we should advertise it in an example.

We need to add it to plot_demo_glass_extensive.py, using a new
'notebook-style' cell.

**Comment by KamalakerDadi** [comment]
Addressed this issue. Closing.
For reference See:
http://nilearn.github.io/auto_examples/01_plotting/plot_demo_glass_brain_extensive.html#sphx-glr-auto-examples-01-plotting-plot-demo-glass-brain-extensive-py
