### ISSUE TITLE
Better breakdown of the examples

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#884]
We are starting to have a lot of examples, which is a good thing, but can easily lead to getting lost in the information.

I suggest a new breakdown of examples:

* General: just a handful of examples

* Decoding: what we currently have

* Functional connectivity: what we currently have

* Plotting

* Manipulation of brain images

* Advanced

Basically, it would entail breaking up our current 'visualizing_and_manipulating' into 'plotting', 'manipulating' and 'advanced'. Advanced is just another word for 'other', in a certain sense. We would put things like the low-level ICA stuff, or the mass-univariate stuff. Ie things that we don't really want to advertise strong to end users.

One strong reason for me to separate out the plotting examples is that it seems that our users do not use the full breadth of the plotting options, and do not find them.

This is an issue labelled 'discussion', please do comment here on what you think about this plan.

**Comment by lesteve** [comment]
Sounds reasonable to me.

**Comment by bthirion** [comment]
Sounds good in general, but I wonder what you put in 'Manipulation of brain images' ?

**Comment by GaelVaroquaux** [comment]
> Sounds good in general, but I wonder what you put in 'Manipulation of brain
> images' ?

An example extracting ROIs from a statistical map (@KamalakerDadi has a
great one almost ready), examples about computing masks (we have a few),
the resampling example. Maybe more later, as we are finding that it is
very important to teach people to do efficient yet simple manipulations
of their data.

**Comment by bthirion** [comment]
OK, the name and content may be further specified in the future anyhow.

**Comment by KamalakerDadi** [comment]
Breaking concept is nice to me. 

As @GaelVaroquaux  mentioned especially I am reshaping sub section 4.3.5 in Section 4 considering my example on ROI extraction on statistical maps.

@GaelVaroquaux Do you need this for 0.2.1 or 0.2 release ?

**Comment by GaelVaroquaux** [comment]
> @GaelVaroquaux Do you need this for 0.2.1 or 0.2 release ?

Let's do it for 0.2.1, and not 0.2, as I don't want to delay the release.
