### ISSUE TITLE
Broken links in docstrings

### ISSUE THREAD

**Issue by mrahim** [nilearn/nilearn#886]
Typically this one :
http://nilearn.github.io/building_blocks/manipulating_mr_images.html#niimg
I'm wondering if we can have a tool that checks automatically all links.

**Comment by GaelVaroquaux** [comment]
> I'm wondering if we can have a tool that checks automatically all links.

make linkcheck.

But won't don't want it in CI, as it has a lot of false positives.

**Comment by mrahim** [comment]
Ok, should we fix it right now before the 0.2 ?

**Comment by GaelVaroquaux** [comment]
> Ok, should we fix it right now before the 0.2 ?

Yes

**Comment by lesteve** [comment]
Thanks @mrahim for remembering this to us! Do you want to do it, i.e. basically do you have a good way to do a search and replace in all the nilearn files rather than by hand? Otherwise I'll do it.
