### ISSUE TITLE
Cache directory in SpaceNet examples

### ISSUE THREAD

**Issue by mrahim** [nilearn/nilearn#889]
In the examples :
* `examples/decoding/plot_mixed_gambles_space_net.py`
* `examples/decoding/plot_haxby_space_net.py`

`memory="nilearn_cache"` should be used rather than `memory="cache"`
As it is, I have two cache folders in `example/decoding`.  

ping @dohmatob

**Comment by dohmatob** [comment]
OK, agreed there is some uniformaization to be done here. Thanks. Do you think you can do a PR for this ?

**Comment by mrahim** [comment]
Yes
