### ISSUE TITLE
Feature Request: Structured Sparse PCA

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#892]
Given that there is now sparse PCA and (sparse) dictionary learning, how about implementing *structured* sparse PCA into the nilearn arsenal in the future?

cf.
http://arxiv.org/abs/0909.1440

**Comment by bthirion** [comment]
I would not make this a priority, because efficiency should be improved before going to more complex versions of sparse PCA. Also, it unclear to me what is the best suited structured dictionary: why not TV-l1 regularized ?

**Comment by banilo** [comment]
SSPCA could be interesting for unsupervised questions and TV-l1 for
supervised questions.

2015-12-04 22:10 GMT+01:00 bthirion <notifications@github.com>:

**Comment by GaelVaroquaux** [comment]
SSPCA is something very very costly. We have dabbled with it in the past, but pretty gave up because of the computational cost.

MSDL has structure at a much reduced cost, still significantly higher than SPCA.
