### ISSUE TITLE
Fix dict_init doc in DictLearning

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#893]
"Initial estimation" does not make sense.

**Comment by Remi-Gau** [comment]
Need to double check but I think there is no occurrence of this in the code base anymore.

**Comment by bthirion** [comment]
Agreed.

**Comment by Remi-Gau** [comment]
One occurrence only in a doc string:
https://github.com/nilearn/nilearn/blob/1471ba887c1109d8ee8986179e0a229823a25eb6/nilearn/decomposition/dict_learning.py#L71

I still think this is an OK description of the parameter.

**Comment by bthirion** [comment]
Sounds OK to me.
