### ISSUE TITLE
Fix links in resting_state_networks.rst

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#894]
See #693

**Comment by lesteve** [comment]
Does this issue implicitely include CircleCI broken in master (make html-strict has errors see [here](https://circleci.com/gh/nilearn/nilearn/890?utm_campaign=build-failed&utm_medium=email&utm_source=notification) for example) ?

**Comment by AlexandreAbraham** [comment]
Fix pushed in master.

**Comment by GaelVaroquaux** [comment]
Sorry, @AlexandreAbraham, I short cutted you. You should have pushed directly to master.

**Comment by AlexandreAbraham** [comment]
That's what I've done ! This is an issue, not a PR. I pushed the fix last night.
