### ISSUE TITLE
Change the default number of subjects in fetch_adhd from 40 to 30

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#897]
The rational is to avoid blowing the cache of dowloads in circleCI.

**Comment by salma1601** [comment]
Can we do this while keeping the same ratio ADHD/controls ?
Also, the sites are not ordered when loading ADHD dataset but I don't know if this was done on purpose ...

**Comment by GaelVaroquaux** [comment]
> Can we do this while keeping the same ratio ADHD/controls ?

We need to check. That's a good point!

**Comment by GaelVaroquaux** [comment]
CircleCI is downloading data over and over again. We should address this issue.

**Comment by KamalakerDadi** [comment]
> We need to check. That's a good point!
@GaelVaroquaux with 30 subjects ratio is adhd/control 17/13

If we need to keep strict ordering, then we have to change the ordering according to the sites. Otherwise, I am ready with PR. Just that I changed ```n_subjects = max_subjects``` to ```n_subjects = 30``` and will change documentation accordingly.

**Comment by aabadie** [comment]
> The rational is to avoid blowing the cache of dowloads in circleCI.

Looking at circle ci output from PR #970, the download of haxby2001 is also quite big and make the output very verbose. It's currently fetching around 300MB of data.

**Comment by GaelVaroquaux** [comment]
> Looking at circle ci output from PR #970, the download of haxby2001 is also
> quite big and make the output very verbose. It's currently fetching around
> 300MB of data.

Yes :(. Do you think that there is a way of improving things?

G

**Comment by AlexandreAbraham** [comment]
I was going to ask if the problem was still on. I have several ideas to reduce the amount of data downloaded, but all of them will make the figures generated by CircleCI irrelevant.

**Comment by GaelVaroquaux** [comment]
> I was going to ask if the problem was still on. I have several ideas to
> reduce the amount of data downloaded, but all of them will make the
> figures generated by CircleCI irrelevant.

OK, let's punt for now.

**Comment by AlexandreAbraham** [comment]
I think we should discuss that during a coffee break.

**Comment by aabadie** [comment]
I think there are 2 problems:
* a too big amount of data is downloaded (this issue)
* the output the downloads is too verbose (issue #948)

fetch functions have a `verbose` parameter that is `True` maybe using `verbose=False` in the examples will make the output more readable. A possible solution could be to use `functools.partial` to override this default value (I don't know how to transparently activate it on circle ci though).
