### ISSUE TITLE
Plotting anatomical images

### ISSUE THREAD

**Issue by TheChymera** [nilearn/nilearn#900]
I am trying to plot the `.nii` file located [here](http://chymera.eu/NIhelp/nilearn_plot0/6_restore_maths.nii.gz), with this script:

```
from nilearn import image, plotting

def plot_nii(file_path, slices):
    plotting.plot_anat(file_path, cut_coords=slices, display_mode="y", annotate=False, draw_cross=False)

if __name__ == '__main__':
    plot_nii("6_restore_maths.nii.gz", (-50,0,4,5))
    plotting.show()
```

The resulting image looks like this:
![figure_1](https://cloud.githubusercontent.com/assets/950524/11745019/47a5207e-a015-11e5-869c-b0a977100131.png)

I have two issues with that:
- My image only has 14 coronal slices. Mapping the slices via some other unit of measurement (btw, what is it?) is annoying and unwieldy - as you can see, an increment of up to four displays the same slice, and then suddenly, via an increment of just one, I go to the next.
- The caudal slices are cut off at the top. Why? my data is not cut off like that (as you can see when plotting the image via FSLView or MRIcron.

**Comment by GaelVaroquaux** [comment]
Data is plotted in brain space (mm), not in voxel space. This explains
all what you are seeing. It's a design choice.

**Comment by TheChymera** [comment]
how does this explain my caudal-most slices getting cut off?

**Comment by bthirion** [comment]
Would you mind sharing such an image ? I have ne explain simple explanation for the cropping effect.

**Comment by TheChymera** [comment]
@bthirion yes, I uploaded my NIfTI file and posted a link in my initial post.

**Comment by bthirion** [comment]
OK, you need to realize that nilearn interpolates you image along cuts z=-50, z =0 etc.
Your initial image is not samples along the canonical axis (the affine --se below-- is not diagonal), meaning that the slice z=50 simply gets out of your image. It looks like fslview ignores the affine when displaying the image.

import nibabel as nib
nib.load('6_restore_maths.nii.gz').get_affine()
Out[13]: 
array([[  1.66661203e+00,  -5.85196307e-03,   1.41516961e-02,
         -1.00595535e+02],
       [ -4.91110049e-03,  -7.50039890e-02,   6.46738625e+00,
         -4.78150864e+01],
       [ -1.25762308e-02,  -7.46217310e-01,  -6.50162637e-01,
          5.06253510e+01],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.00000000e+00]])

**Comment by TheChymera** [comment]
Ok, two questions then:

* Wouldn't that mean that on each slice the top voxels would be taken from the next one caudally? Since my image is so sparsely sampled I would expect that to be noticeable (bot for the other two slices I plot above it seems all of the voxels are indeed from the same slice.
* How can I get nilearn to plot my image according to its own affines? If not is there a simple way to align the image with nilearn's expected orientation before plotting?

**Comment by danlurie** [comment]
I agree it would be really useful to have the option of forcing Nilearn to take the header affine into account when plotting. 

Also useful would be a note to the plotting docs to at least mention the automatic interpolation. I'm happy to do this part, but it will have to wait until after the SFN deadline

**Comment by banilo** [comment]
> I agree it would be really useful to have the option of forcing Nilearn to take the header affine into account when plotting.

I agree

**Comment by TheChymera** [comment]
@danlurie @banilo Are you sure we are talking about the same thing? What I wanted to do is plot an image slice per slice as it is written in the matrix. To my understanding that equates to ignoring any affine rather than taking the header affine into consideration. No?

**Comment by MartinPerez** [comment]
@TheChymera if I understand what you want. Then maybe you just need to do this? 

# cutting on the x axis:
data = nib.load(img).get_data()
fig, axes = plt.subplots(1, data.shape[0])
for idx, ax in enumerate(axes):
    plt.sca(ax)
    plt.imshow(data[idx, :, :])

does that help?

**Comment by oesteban** [comment]
> I agree it would be really useful to have the option of forcing Nilearn to take the header affine into account when plotting.

This is actually what's happening here - I've opened #2525 with some ideas and one more situation where this is problematic.

**Comment by bthirion** [comment]
Superseded by #2525.
