### ISSUE TITLE
[discussion]: PSC unit in NiftiMapsMasker

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#902]
I am in favour of replacing the argument standardize by normalize which would be one of `{'psc', 'std', None}` for the scaling of the raw time-series.
`'psc'`: percent signal change to force temporal mean within each ROI to 100.
`'std'`: standardized to force temporal standard deviation of each ROI to 1.
`None`: no scaling at all

But may be it is annoying to change the type and name of a parameter ?

**Comment by bthirion** [comment]
I like the idea.

**Comment by AlexandreAbraham** [comment]
+1

**Comment by banilo** [comment]
+1

**Comment by GaelVaroquaux** [comment]
+1

**Comment by bthirion** [comment]
Solved AFAIK.
