### ISSUE TITLE
Rewrite region extraction example to use DictLearning instead of CanICA.

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#904]
Example
http://nilearn.github.io/auto_examples/connectivity/plot_extract_regions_canica_maps.html#sphx-glr-auto-examples-connectivity-plot-extract-regions-canica-maps-py
should be rewritten to use DictLearning instead of CanICA

**Comment by KamalakerDadi** [comment]
I can take care of this.

**Comment by GaelVaroquaux** [comment]
> I can take care of this.

Awesome. Thanks!

**Comment by GaelVaroquaux** [comment]
Done. Closing
