### ISSUE TITLE
Inconsistent and undocument return types for plot_stat_map (and probably other such API)

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#911]
- Stuff returned by  `plot_stat_map` is no documented (it seems a Slicer object is returned by default)
- if output_file is passed, then a None object is returned instead

It would be nice to have the return type documented, and also we should always return the same object type (e.g a Slicer).

**Comment by lesteve** [comment]
There is something in the html doc somewhere, have you checked?

**Comment by dohmatob** [comment]
I don't understand the remark. I'm talking about function docstrings.

**Comment by lesteve** [comment]
> I don't understand the remark. I'm talking about function docstrings.

Not everything has to be documented in the docstring. If you feel strongly about adding a 'Returns' section for all the plotting functions saying that it returns a display object, feel free to open a PR.

By the way the html doc explains all that [here](http://nilearn.github.io/manipulating_visualizing/plotting.html#adding-overlays-edges-and-contours) in some details.

**Comment by dohmatob** [comment]
On Tue, Dec 15, 2015 at 6:34 PM, Loïc Estève <notifications@github.com>
wrote:

> I don't understand the remark. I'm talking about function docstrings.
>
> Not everything has to be documented in the docstring
>
This doesn't address the problem. How can you justify missing doc by
pointing to some html page ? Do you mean users can't figure out what a
function takes-in, outputs, etc. without having internet connection and
going over the project webpage, etc. ?

>
>
If you feel strongly about adding a 'Returns' section for all the plotting
> functions saying that it returns a display object, feel free to open a PR.
>
If this if it's not apparent that this is an issue (inhomogeneous return
types / value + undocumented return types / value), please feel free to
close it.

> By the way the html doc explains all that here
> <http://nilearn.github.io/manipulating_visualizing/plotting.html#adding-overlays-edges-and-contours>
> in some details.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nilearn/nilearn/issues/911#issuecomment-164834027>.
>



-- 
Elvis Dohmatob,
*sent from my  potato...*
http://dohmatob.blogspot.fr/, https://team.inria.fr/parietal/elvis/,
https://github.com/dohmatob

**Comment by bthirion** [comment]
I think that this kind of high-level and probably highly-used function should be well-documented.
@dohmatob can you issue a PR ?

**Comment by banilo** [comment]
I would like to agree that a) consistency across plotting API and b) mentionning the output variable type in the docstring appears reasonable.

**Comment by GaelVaroquaux** [comment]
I agree about documenting the return.

With regard to not returning the display object when the file is saved,
this is by design. Indeed, these duisplay objects can accumulate and
create memory leakage. We are trying to garbage collect them ASAP when
they are not needed. It's actually the sole goal of the output_file
argument.

**Comment by lesteve** [comment]
> This doesn't address the problem. How can you justify missing doc by pointing to some html page ? Do you mean users can't figure out what a function takes-in, outputs, etc. without having internet connection and going over the project webpage, etc. ?

I am just saying that you have to find the right trade-off between what you put in docstrings and what you put in your online doc. In this particular case, adding a 'Returns' section sounds reasonable. IMHO having some detailed explanation in the docstring similarly to http://nilearn.github.io/manipulating_visualizing/plotting.html#displaying-or-saving-to-an-image-file, not that much.

**Comment by ymzayek** [comment]
I can work on this
