### ISSUE TITLE
utils to check for more verbose error message in sphinx doc errors

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#912]
This might be useful, from sphinx google discussions:

``` python
from docutils.core import publish_parts
publish_parts(myfunc.__doc__)
```

``` python
help(myfunc)
```

Could somebody share if they have other clever utils to deal with this doc problems ?
Currently, I have documentation errors with megatrawls data fetcher.  For instance "Unexpected indentation". I assume that it is because I used 5 References in my doc ?

Does somebody have any clue on what `54` represents ?
`<string>:54: (ERROR/3) Unexpected indentation.`

**Comment by KamalakerDadi** [comment]
This issue is just trying to acquire some information.

**Comment by lesteve** [comment]
Out of interest, can you give the link you find this tip from.

**Comment by KamalakerDadi** [comment]
[sphinx-dev] "Unexpected indentation." with no explainable cause

 Google groups. https://groups.google.com/forum/#!topic/sphinx-users/Xa-73qn-6Bo
