### ISSUE TITLE
plot_stat_map(..., cut_coords=some_int, display_mode="ortho") throws criptic error

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#913]
`plot_anat("funky.nii.gz", display_mode="ortho", cut_coords=6)`

```
TypeError: object of type 'int' has no len()
```

We should check when `cut_coords` is an int and `display_mode` is `"ortho"` and then take best possible action (with appropriate warning) or fail gracefully.

**Comment by lesteve** [comment]
Not a great error message ! I would just go for a ValueError with a message like "with display_mode='ortho', 'cut_coords' needs to be a list of 3d world coordinates. You provided 'cut_coords=...' instead." or something better phrased.

**Comment by GaelVaroquaux** [comment]
> Not a great error message ! I would just go for a ValueError with a
> message like "with display_mode='ortho', 'cut_coords' needs to be a
> list of 3d world coordinates. You provided 'cut_coords=...' instead."
> or something better phrased.

+1 indeed. PR welcomed.

**Comment by KamalakerDadi** [comment]
Anybody on this ? I can take care of this.

**Comment by dohmatob** [comment]
I don't think anybody is on it.
