### ISSUE TITLE
Downloader for multiscale parcellations

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#916]
https://figshare.com/articles/
Group_multiscale_functional_template_generated_with_BASC_on_the_Cambridge_sample
/1285615

Via @pbellec, who might be able to answer questions about these parcellations.

**Comment by pbellec** [comment]
Thanks @GaelVaroquaux for opening this issue. I had a look at what's involved. Looks like it needs
 1. a description file urchs_2015.rst under datasets/description
 2. the code to actually download the dataset should be added in datasets/atlas.py
 3. a test to check the integrity of the download should be added in tests/test_atlas.py

Can you please confirm I am not missing anything? I can certainly draft (1). Could give a shot at (2) and (3) by adapting code for other templates, let me know what you think.

**Comment by AlexandreAbraham** [comment]
Fixed in #984
