### ISSUE TITLE
Fetcher for AICHA: Atlas of Intrinsic Connectivity of Homotopic Areas

### ISSUE THREAD

**Issue by AlexandreAbraham** [nilearn/nilearn#921]
This is an atlas generated using ICA + K-Means. I could be interested by trying it but, if it is not fitted for nilearn, I can put it in the sandbox.

http://www.ncbi.nlm.nih.gov/pubmed/26213217

**Comment by banilo** [comment]
cf. https://en.wikipedia.org/wiki/Journal_of_Neuroscience_Methods
