### ISSUE TITLE
find_xyz_cut_coords crashes on some compact binary images

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#922]
...trace back is:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-44-802cef648458> in <module>()
----> 1 plotting.find_xyz_cut_coords(nib.load(roi_paths[2]))

/git/nilearn/nilearn/plotting/find_cuts.py in find_xyz_cut_coords(img, mask, activation_threshold)
     90         return .5 * np.array(data.shape)
     91     mask = largest_connected_component(mask)
---> 92     slice_x, slice_y, slice_z = ndimage.find_objects(mask)[0]
     93     my_map = my_map[slice_x, slice_y, slice_z]
     94     mask = mask[slice_x, slice_y, slice_z]
```

The image on which this crashes is attached.

[dmpfc-3.nii.zip](https://github.com/nilearn/nilearn/files/66476/dmpfc-3.nii.zip)

**Comment by bthirion** [comment]
The issue is that the image that you provided is 4D (with the last dimension=1). if you remove the last dimension form your image, it is OK.
plotting.find_xyz_cut_coords(nib.four_to_three(nib.load('dmpfc-3.nii'))[0])

Should we support this kind of case ?

**Comment by banilo** [comment]
Ok, merci pour le conseil.

It would be nice to support the case because the 3D and Pseudo-4D images contain the same information and the optimal x, y and z cut planes can be expected to be the same. That appears intuitive to me.

**Comment by AlexandreAbraham** [comment]
As all functions working on img directly (not niimg), it assumes that the input has the right dimension. This has been done because this function is not "opened to public". So, two options:

* you use the regular way to load your image, meaning `check_niimg_3d`. It will convert your 4d image to 3d automatically
* We call `check_niimg_3d` at the beginning of `find_xyz_cut_coords`. It will then work natively on all niimg

**Comment by GaelVaroquaux** [comment]
These days it is exposed to the public. We should probably add a checker
in the input. Is there a downside?

**Comment by AlexandreAbraham** [comment]
Well, a small computational overhead because we check the input data, that's all.

**Comment by GaelVaroquaux** [comment]
> Well, a small computational overhead because we check the input data,

It's probably tiny compared to the time of the funtion.

@banilo: do you want to do a PR?

**Comment by banilo** [comment]
Sure, I'd be happy to.

As the find_* function is probably typically called for plotting, it should
not be called excessively and thus not typically cause a big overhead.

2015-12-20 15:08 GMT+01:00 Gael Varoquaux <notifications@github.com>:

**Comment by AlexandreAbraham** [comment]
@banilo I think this is important for 0.2.2. Are you working on it?

**Comment by banilo** [comment]
I will do it this weekend
