### ISSUE TITLE
Harvard Oxford reloaded if FSLDIR not specified

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#926]
Again the fetch_atlas_harvard_oxford does not see my HO atlas in /usr/share/fsl. I added the FSLDIR to my .bashrc and now it works fine. Is this what it is adviced to do ?
Thanks !

**Comment by AlexandreAbraham** [comment]
You need to be in an FSL environment to use its data automatically. On a standard install `source /etc/fsl.sh`.
