### ISSUE TITLE
161 times series in fetch_abide_pcp with derivatives rois_dosenbach160

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#927]
I think it is an issue in the CPAC pipeline. Seems to me that the last region is not in the Dosenbach atlas but just an intersection between regions 108 (-5, -52, 17) and 115 (-11, -58, 17) which are too close.

**Comment by AlexandreAbraham** [comment]
Please report your issue to the Preprocessed Connectome Project: https://github.com/preprocessed-connectomes-project
