### ISSUE TITLE
Plots won't show up

### ISSUE THREAD

**Issue by neurotronix** [nilearn/nilearn#929]
Hi everyone,

using nilearn on OSX El Capitan, when executing the example scripts like plot_demo_glass_brain.py no plots will show up. PiP and iPython linked to the same folders, matplotlib alone does show plots. All dependencies are up-to-date and installed. Don't really know how to fix this.

**Comment by GaelVaroquaux** [comment]
How do you execute these scripts?

**Comment by neurotronix** [comment]
I tried "python script_name.py" and "ipython script_name.py", respectively

**Comment by GaelVaroquaux** [comment]
OK, "Python script_name.py" should work, but it might be an OSX thing, I don't know anything about OSX.

How do you get matplotlib to show plots?

**Comment by neurotronix** [comment]
I just tested trivial things in the ipython environment like:
```
import matplotlib.pyplot as plt
plt.plot(range(10), range(10))
plt.show()
```
just to test whether matplotlib works properly

**Comment by GaelVaroquaux** [comment]
Then just run the example using "%run filename.py" in the IPython
environnement where things work well.

**Comment by neurotronix** [comment]
Ok, didn't try to run it from within python. Now plots show, but I also get following error:
```
/Users/Stephan/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:1350: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.
```

**Comment by neurotronix** [comment]
plots only show when I open ipython via `ipython --matplotlib` but then I get the error from above. When I open it with without `--matplotlib` flag, no plots and no error

**Comment by GaelVaroquaux** [comment]
Out of curiosity, can you tell use what do the following return in
python:

<pre>
import os
print(os.name)
print('DISPLAY' in os.environ')
</pre>

**Comment by neurotronix** [comment]
sure:
```
In [1]: import os

In [2]: print os.name
posix

In [4]: print('DISPLAY' in os.environ)
False
```

**Comment by GaelVaroquaux** [comment]
I am starting to understand better what you are experiencing. Can you
also give us the output of:

<pre>
print(os.uname())
import matplotlib
print(matplotlib.get_backend())
</pre>

**Comment by neurotronix** [comment]
cool, thanks for your help man. here is the output:
```
In [5]: print(os.uname())
('Darwin', 'KH-Lees-Macbook.local', '15.0.0', 'Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64', 'x86_64')

In [7]: print(matplotlib.get_backend())
MacOSX
```

**Comment by GaelVaroquaux** [comment]
OK. You can work in the "ipython --matplotlib" environment; it won't be any problem.

The rest are things that we can fix based on your feedback, so that it works seemlessly in all situations. We'll release a fix soon; Thanks!

**Comment by neurotronix** [comment]
Many thanks, have a good day!

**Comment by GaelVaroquaux** [comment]
Note for self (I know how to fix this, and will submit a PR soon): sampling of MacOSX installs:

* os.name is always posix
* os.uname()[0] is always 'Darwin':
* "'DISPLAY' in os.environ": True 2 out of 3
* matplotlib.get_backend():
    - 'TkAgg' (on @ogrisel's computer)
    -  'MacOSX' on the two others

**Comment by ogrisel** [comment]
Also:

```python
sys.platform == 'darwin'
```

this is the canonical way to detect OSX.

**Comment by GaelVaroquaux** [comment]
> sys.platform == 'darwin'

> this is the canonical way to detect OSX.

Thanks! I was missing that.

**Comment by lesteve** [comment]
@neurotronix your problem should be fixed in master. Could you please double-check and reopen this issue if this isn't the case ?

**Comment by neurotronix** [comment]
@lesteve Looking good so far. Plots now show up when scripts are called from shell. thanks!

**Comment by GaelVaroquaux** [comment]
> @lesteve Looking good so far. Plots now show up when scripts are called from shell. thanks!

That's excellent news. Thanks for your help diagnosing this.

**Comment by LLouedKhen** [comment]
Hi, 
I had the same problem running scripts from conda (Spyder) using OSX Mojave. For whatever reason, importing nilearn libraries changes the backend matplot lib uses, such that plot displayed nothing after importing nilearn.plotting
You can check by calling:

`matplotlib.get_backend()`

before and after 

`from nilearn import plotting`

to see if and how your backend changes. 
Then explicitly change the backend to the one that displays plots properly, eg
`matplotlib.use("[workingBackEnd]")`

**Comment by GaelVaroquaux** [comment]
The code that changes the backend is here:
https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/__init__.py#L12

It is needed so that people can plot even without an X server (eg on an
ssh connection). However, it seems that it is not making the right choice
here.

We'd love help in improving the detection of the right backend.

**Comment by LLouedKhen** [comment]
Hi, 
I am new to nilearn but I have now installed it on 3 separate computers (1 MacOs Mojave, 1 MacOs Sierra, 1 Dell/ Windows 10). Plotting after importing nilearn only fails in the first. 
In looking at the code above, it would seem it forces the user to use a specific backend on line 33

`matplotlib.use('Agg')`

but maybe a more general solution would be to obtain the default backend that works. 

The message below on stack exchange helped some:
https://stackoverflow.com/questions/56656777/userwarning-matplotlib-is-currently-using-agg-which-is-a-non-gui-backend-so/56658510

Cheers, 
L.

**Comment by GaelVaroquaux** [comment]
@LLouedKhen : can you run the following code for me (before import nilearn):
```
import matplotlib
matplotlib.get_backend()
```
and tell me the result.

I might be able to fix this problem with #2302

**Comment by LLouedKhen** [comment]
Sure
`Out[3]: 'module://ipykernel.pylab.backend_inline'`

Cheers, 
L.

**Comment by tashrifbillah** [comment]
Same problem on Windows 10.
Even switching backend to the functional does not help.
By the way, a trivial matplotlib plot opens up for me like folks reported before.

More info:
```python
>>> os.name
'nt'
>>> 'DISPLAY' in os.environ
False
```

**Comment by tashrifbillah** [comment]
Okay, I may have found a solution to this. I had to explicitly call `pyplot.show()` after nilearn plotting:

```python
from matplotlib import pyplot
from nilearn.plotting import plot_img
plot_img('your/nifti/image.nii.gz')
pyplot.show()
```
@LLouedKhen , would you like to give it a try?

@GaelVaroquaux , can you rationalize it?

**Comment by jeromedockes** [comment]
yes, all the example scripts are missing a call to `plt.show`. I think this was mentioned in a couple of issues but can't remember which.
This is very easy to fix and I think a PR would be welcome

**Comment by LLouedKhen** [comment]
I had tried explicitly calling the plot but it made no difference. It was specific to the backend used. 
Cheers,
L.
