### ISSUE TITLE
Have a uniform representation of labels for atlases

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#930]
We should do the work of grabbing the labels of the atlases in the downloaders and expose them uniformely. It would make the life of the users easier.

**Comment by AlexandreAbraham** [comment]
What do you mean?

**Comment by GaelVaroquaux** [comment]
Return in-memory labels, loaded from the CSV file. The code to load
labels in Harvard Oxford and MSDL are very different.

**Comment by AlexandreAbraham** [comment]
OK, you mean that labels are not loaded in MSDL. They are loaded in Harvard Oxford.

**Comment by GaelVaroquaux** [comment]
> OK, you mean that labels are not loaded in MSDL. They are loaded in Harvard
> Oxford.

Good point.

**Comment by banilo** [comment]
Perhaps in form of an additional option in ``NiftiLabelsMasker`` and ``NiftiMapsMasker`` ?

**Comment by GaelVaroquaux** [comment]
> Perhaps in form of an additional option in NiftiLabelsMasker and
> NiftiMapsMasker ?

I'd rather not for now.

**Comment by banilo** [comment]
+1 for unifying label meta-data!
