### ISSUE TITLE
Deprecated function in an example in documentation

### ISSUE THREAD

**Issue by MrFDA** [nilearn/nilearn#932]
The example provided in the documentation for extracting signals of a probabilistic atlas of rest functional regions (https://nilearn.github.io/auto_examples/connectivity/plot_probabilistic_atlas_extraction.html#sphx-glr-auto-examples-connectivity-plot-probabilistic-atlas-extraction-py) uses a deprecated function (fetch_msdl_atlas()).

**Comment by KamalakerDadi** [comment]
Thanks for reporting. But, we have fixed this in nilearn master. It will be perfect for next release.

**Comment by lesteve** [comment]
Thanks @KamalakerDadi, closing then.
