### ISSUE TITLE
Wrapper object for sklearn estimators ?

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#934]
It'll be nice to have a wrapper object for sklearn estimators (SVC, Ridge, Lasso, etc.). The idea would be to mask the data (NiftiMasker, etc.) to get (X, y), run the sklearn estimator, and then unmask the coefs to get a brain image

This is useful, at least for benchmarks / comparisons, and such situations are quite frequent.

**Comment by eickenberg** [comment]
Along the lines of https://github.com/nilearn/nilearn/pull/698 or different?

**Comment by dohmatob** [comment]
Ya, definitely along those lines. Almost forgot about the meta-estimator PR. I was thinking of something really light, that does nothing trickier than wrap sklearn estimators. But #698 is probably aiming bigger.

**Comment by eickenberg** [comment]
I agree with you that something really slim could be very useful -- with
something like that one could easily compare nilearn-native methods which
can deal with niimg objects to wrapped sklearn-estimators using exactly the
same interface. (I just started adding SVM to the mixed gambles example and
there is a lot of boiler plate to write which should be much less with the
type of object you propose)

**Comment by dohmatob** [comment]
+1. Same thing here.

**Comment by dohmatob** [comment]
Something like https://github.com/dohmatob/nilearn/blob/ohbm2016/sklearn2nilearn.py. Used here https://github.com/dohmatob/nilearn/blob/ohbm2016/examples/decoding/plot_haxby_space_net.py#L87

**Comment by bthirion** [comment]
I think that this would be a step forward. +1

**Comment by banilo** [comment]
+1, a general-purpose sklearn estimator wrapper that works in most cases could effectively improve the sklearn-nilearn interface.

**Comment by bthirion** [comment]
Solved with Decoder object.
