### ISSUE TITLE
Hemisphere separation mode for glass brain

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#942]
It would be great to have a mode for the glass brain that separates hemispheres in the lateral view.

It would look like:
![sphx_glr_plot_demo_glass_brain_001](https://cloud.githubusercontent.com/assets/208217/12269780/57486890-b953-11e5-9cc4-122f1cebc3f0.png)

and it would project on one side of the brain only activations with x > 0, and on the other side only activations with x < 0.

For plot_connectome, it would do the same thing with points, and in terms of lines it would not draw lines that cross the hemispheric border (which is a bug or a feature depending on how you see it).

**Comment by banilo** [comment]
+1 for the idea.

Should not be that hard to implement.

**Comment by MartinPerez** [comment]
+1. What about also having the option of projecting in each hemisphere only its own activation, would be nice for the type of contrasts strongly lateralized like the language network and motor activations

**Comment by GaelVaroquaux** [comment]
> +1. What about also having the option of projecting in each hemisphere only its
> own activation,

That's the goal. That's why I said "only x > 0"

**Comment by GaelVaroquaux** [comment]
This was implemented in #1034. Closing.
