### ISSUE TITLE
Add a canonical brain mask

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#945]
We need a canonical brain mask. Maybe also one only of gray matter.

If they are very small, we should include them in the codebase (hence with a "load_brain_mask" function in datasets). If not, we need to create a "fetch_brain_mask" function in the downloaders.

If we choose to obtain it from the MNI template, eg doing:
<pre>
target_img = datasets.load_mni152_template()
grey_voxels = (target_img.get_data() > 0).astype(int)
mask_img = new_img_like(target_img, grey_voxels)
</pre>
we don't need to store anything addition. That might be the simplest / best solution.

**Comment by banilo** [comment]
In what settings would the canonical brain mask appear within the nilearn code?

**Comment by GaelVaroquaux** [comment]
> In what settings would the canonical brain mask appear within the
> nilearn code?

It appeared as useful in an example downloading data from neurovault.

**Comment by KamalakerDadi** [comment]
> In what settings would the canonical brain mask appear within the nilearn code?

In future, it can also be appeared in function which computes out of brain mask confounds.

**Comment by GaelVaroquaux** [comment]
> In future, it can also be appeared in function which computes out of
> brain mask confounds.

That's a good point.

**Comment by KamalakerDadi** [comment]
Does this issue also demands for grey matter mask ?

Or

simply a canonical brain mask as done in PR #1103

**Comment by AlexandreAbraham** [comment]
Hmm, asking for both... We should maybe rename it to grey matter or open a new one for the gray matter mask.

**Comment by KamalakerDadi** [comment]
> Hmm, asking for both

How does it go with grey matter mask ? We simply compute it from ICBM ['gm'] and resample to MNI template and return it, [like here!](https://github.com/NeuroVault/neurovault_analysis/blob/master/compute_gm_mask.py)

**Comment by AlexandreAbraham** [comment]
I guess so, yes.

**Comment by KamalakerDadi** [comment]
Ok, then I would integrate it in the same PR.
Thanks.

**Comment by GaelVaroquaux** [comment]
This was implemented in #1103. Closing.
