### ISSUE TITLE
 SearchLight doesn't support memory parameter

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#947]
We should be able to cache the backend call to the `search_light` function, etc. to save time.

**Comment by AlexandreAbraham** [comment]
True!

**Comment by banilo** [comment]
In each searchlight (with each a different center in the brain), the learners are probably called with different arguments every time. On the other hand, it is less likely that the whole SL procedure will be performed more than once on the same data in a real-world pipeline. ...just thinking.

**Comment by GaelVaroquaux** [comment]
> In each searchlight (with each a different center in the brain), the learners
> are probably called with different arguments every time. On the other hand, it
> is less likely that the whole SL procedure will be performed more than once on
> the same data in a real-world pipeline. ...just thinking.

I actually agree with you. I wonder what parts of the code are rerun
several times while doing an explorative data analysis.

**Comment by dohmatob** [comment]
There are certainly parts of the searchlight machine which can be cached. Otherwise is a design problem...

**Comment by GaelVaroquaux** [comment]
> There are certainly parts of the searchlight machine which can be cached.

They "can", the question is whether it is useful.

**Comment by banilo** [comment]
> There are certainly parts of the searchlight machine which can be cached.
> They "can", the question is whether it is useful.

Well, let's just make a list of what elements of the code could be cached.

**Comment by bthirion** [comment]
Unclear what should be done.
