### ISSUE TITLE
Turn down verbosity on CircleCI

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#948]
Currently, it is impossible to understand anything of the logs of circleCI. We need to turn down the verbosity of the downloads in the logs.

For example, see https://circleci.com/gh/nilearn/nilearn/1028

**Comment by lesteve** [comment]
You can look at log.txt in the artifacts tab:
https://circle-artifacts.com/gh/nilearn/nilearn/1028/artifacts/0/home/ubuntu/log.txt

**Comment by GaelVaroquaux** [comment]
> You can look at log.txt in the artifacts tab:
> https://circle-artifacts.com/gh/nilearn/nilearn/1028/artifacts/0/home/ubuntu/
> log.txt


Good point. Thanks!

**Comment by GaelVaroquaux** [comment]
Closing in favor of #972
