### ISSUE TITLE
building docs takes so long

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#953]
Each time I switch branch (even not changing any file) it takes me 1hour to rebuild the docs.
I don't know if this is an expected behaviour.

**Comment by AlexandreAbraham** [comment]
This is a known behavior. The problem is that the cache is invalidated for no reason. PR welcome.

**Comment by GaelVaroquaux** [comment]
> This is a known behavior. The problem is that the cache is invalidated for no
> reason. PR welcome.

No need to do a PR: the new version of sphinx-gallery will solve this.
We'll need to backport it nilearn as soon as it is released.

**Comment by AlexandreAbraham** [comment]
> No need to do a PR: the new version of sphinx-gallery will solve this. We'll need to backport it nilearn as soon as it is released.

I didn't know! Great work!

**Comment by GaelVaroquaux** [comment]
> I didn't know! Great work!

Yup, we need to thank @Titan-C

**Comment by salma1601** [comment]
Great ! Thanks for the explanation.
