### ISSUE TITLE
Unclear provenance of datasets

### ISSUE THREAD

**Issue by banilo** [nilearn/nilearn#957]
For some datasets, such as ADHD200 (:baby:), it does not seem to be entirely clear where the to-be-fetched data exactly came from. If the original website for ADHD for example does not provide a preprocessed version of the data (http://fcon_1000.projects.nitrc.org/indi/adhd200/index.html), then it might be worth it pointing out in the `description` where the actually obtained variant of the open dataset came from (Neurobureau in this case?, http://neurobureau.projects.nitrc.org/ADHD200/Data.html, is it Athena, Burner, NIAK, CIVET).

**Comment by GaelVaroquaux** [comment]
+1! Especially for the classic ADHD and Haxby.

I was just running into these problems with a user.

**Comment by GaelVaroquaux** [comment]
It's mostly a question of adding URLs in the notes section of the
docstrings

**Comment by cinvro** [comment]
I wonder if the ADHD dataset wrapped by nilearn normalized?  
The [group ICA example] (http://nilearn.github.io/auto_examples/03_connectivity/plot_canica_resting_state.html#sphx-glr-auto-examples-03-connectivity-plot-canica-resting-state-py) apply CanICA on all 40 subjects in this ADHD dataset. 

Is that okay to do so without normalization?

**Comment by thomasbazeille** [comment]
this was solved apparently, url is in its place
