### ISSUE TITLE
Harmonize anat_img and bg_image params across plotting functions

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#965]
For example `plot_stat_map` call the background param `bg_img` whilst `plot_prob_atlas` calls it `anat_img`. Is this disparity intended ? The docstrings can also be harmonized.

**Comment by eickenberg** [comment]
and call it background_img while we're at it?

**Comment by lesteve** [comment]
> and call it background_img while we're at it?

No strong feeling about the naming but I am guessing we want to ensure backward-compatibility with a DeprecationWarning if people use named arguments e.g. `plot_img(..., bg_img=bla)`.

**Comment by GaelVaroquaux** [comment]
> No strong feeling about the naming but I am guessing we want to ensure
> backward-compatibility with a DeprecationWarning if people use named arguments
> e.g. plot_img(..., bg_img=bla).

I think that I am OK skipping that, we are still early in the development
of the project. But we would need to do that for the 0.3 relase.
