### ISSUE TITLE
plot_canica_resting_state.py useless smoothing_fwhm=6

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#966]
This example script creates an CanICA instant specifying `smoothing_fwhm=6`, but this is already the default value. We need to check that this (potential) source of confusion is not present in other examples.

**Comment by GaelVaroquaux** [comment]
> This example script creates an CanICA instant specifying smoothing_fwhm=6, but
> this is already the default. We need to check that this (potential) source of
> confusion is not present in other examples.

I'm not sure that this is a source of confusion. For me it is good
because it makes the default explicit. Users may not be aware of it.

**Comment by dohmatob** [comment]
OK, agreed. Especially as we're talking about smoothing (which is often controversial).
