### ISSUE TITLE
[discussion] illustrate masker operations

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#967]
It seems to me that people using a masker for functional connectivity may not understand what it does exactly. Another point is that they may need exploratory feedback to make decisions (what sphere radius to choose, which filtering bandwidth, which confounds to remove) and to feel reassured that everything is going as expected during this somehow black box masker operations.
I was thinking about adding a functional connectivity example that demos the different masker operations and gives some visual/quantitative feedback before arriving to the connectivity matrix. Some examples can be (may be people have better ideas)
- signal rescaling: just illustrating the need
- confound removal: amount of variance explained by a given confound, which locations are heavily correlated with this confound
- filtering: some spectral decomposition of the correlation coefficient to visualize which frequencies contribute
- NiftiSpheresMasker radius: some measure of homogeneity of signals within the sphere or simply a correlation map between the mean signal and the voxels time series within the sphere.

I don't know if this is along the ongoing strategy, because the masker is somehow hiding all this.

**Comment by KamalakerDadi** [comment]
That's a good initiation. Could you provide any work around example if you have along with some outputs ? It would be great and particularly useful to me.

**Comment by salma1601** [comment]
Ok, coming soon.

**Comment by banilo** [comment]
> I was thinking about adding a functional connectivity example that demos the different masker operations and gives some visual/quantitative feedback before arriving to the connectivity matrix.

I completely agree and have tried to make the same suggestion in the past. It is still tricky to understand and use the NiftiMaskers with little exposure the nilearn world.

**Comment by bthirion** [comment]
Stalled.
