### ISSUE TITLE
Decrease verbosity of download progress on CI

### ISSUE THREAD

**Issue by GaelVaroquaux** [nilearn/nilearn#972]
The logs of circleCI are very hard to work with, because the progress log of the downloaders drowns the information:
https://circleci.com/gh/nilearn/nilearn/1097

I am in favor of introducing an environment variable that decreases by something like 50 the number of times that the progress is printed. It would be checked in the datasets code, and set in the circleCI build scripts.

**Comment by aabadie** [comment]
I'll have a look at this asap.

**Comment by GaelVaroquaux** [comment]
Thanks!
