### ISSUE TITLE
BUG Neurodebian build failed on travis

### ISSUE THREAD

**Issue by aabadie** [nilearn/nilearn#975]
This morning travis ci is failing with neurodebian. The `traceroute` package cannot be fetched from the ubuntu precise repository.

See the error message:
```
+sudo apt-get install net-tools traceroute coreutils
Reading package lists... Done
Building dependency tree       
Reading state information... Done
net-tools is already the newest version.
coreutils is already the newest version.
The following NEW packages will be installed:
  traceroute
0 upgraded, 1 newly installed, 0 to remove and 91 not upgraded.
Need to get 53.1 kB of archives.
After this operation, 162 kB of additional disk space will be used.
Err http://us-central1.gce.archive.ubuntu.com/ubuntu/ precise/universe traceroute amd64 1:2.0.18-1
  503  Service Unavailable [IP: 104.197.12.55 80]
Failed to fetch http://us-central1.gce.archive.ubuntu.com/ubuntu/pool/universe/t/traceroute/traceroute_2.0.18-1_amd64.deb  503  Service Unavailable [IP: 104.197.12.55 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Is traceroute really mandatory ?

**Comment by lesteve** [comment]
The `apt-get install traceroute` comes from the neurodebian install script from http://neuro.debian.net/_files/neurodebian-travis.sh.

Seems more like a problem with Travis.

**Comment by lesteve** [comment]
I pushed a temporary work-around in master. The work-around was found in https://github.com/travis-ci/travis-ci/issues/5285#issuecomment-164464865.

**Comment by GaelVaroquaux** [comment]
I have no idea what the workaround does :(

**Comment by AlexandreAbraham** [comment]
It patches the apt sources to point toward a server that is responding and has traceroute.

**Comment by lesteve** [comment]
Looks like the problem has been fixed since so I reverted the temporary work-around in master.
