### ISSUE TITLE
ConnectivityMeasure(kind='tangent') should be cached

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#983]
It takes too long time to compute kind='tangent' with big matrices / too much subjects.

**Comment by FL33TW00D** [comment]
Yes, they take too long to compute.
The core functionality should be implemented in C and then imported.

**Comment by bthirion** [comment]
It is hard to make an efficient C implementation of such an algorithm, and awful to maintain. We won't introduce that into Nilearn.
Closing.
