### ISSUE TITLE
Memory profiling test function fails from time to time

### ISSUE THREAD

**Issue by aabadie** [nilearn/nilearn#986]
The memory profiling test function fails sporadically : sometimes the measured memory consumption is equal to 0.0, thus the  ̀test_memory_usage` fails.
The issue is related to `memory_profiler` measures accuracy, maybe it could be fixed by performing several measures and returning the max.

**Comment by GaelVaroquaux** [comment]
If the test is fast, I am :+1: on performing several measures (3?) and returning the max.

**Comment by aabadie** [comment]
> If the test is fast, I am ￼ on performing several measures (3?) and returning the max.

I'm also +1 with this proposition. I already tried it with success when working on memory profiling.
