### ISSUE TITLE
MultNiftiMasker should propose lazy transform with shelving

### ISSUE THREAD

**Issue by arthurmensch** [nilearn/nilearn#990]
This would be great for algorithms that are sequential with a large IO bottleneck. The way I see it would be to have a ```MultiNiftiMasker.transform(imgs, lazy=True```), which would return a list of MemorizedFunctions with a method ```.get()```, using ```call_and_shelve``` from joblib.

This is quite expert usage, but
- it would be great for developing new estimators
- it would be great for users that build their own pipeline as well

the parmaeter ```lazy``` could be a class parameter, which would preserve the API of ```transform```

**Comment by GaelVaroquaux** [comment]
Agreed on the general idea. I think that @AlexandreAbraham uses this in
his MSDL code.

Wether it should be a new method or a class parameter, I don't know. Any
opinions?

G

**Comment by bthirion** [comment]
As suggested by Arthur, a class parameter sounds more natural imho.

**Comment by AlexandreAbraham** [comment]
> Agreed on the general idea. I think that @AlexandreAbraham uses this in his MSDL code.

Yes I have, I also already have a branch that adds it to the maskers.

Actually, the issue already exists #203 and some code to fix it also already exists #278. The problem is that is we enable it now, we have to propagate everywhere. Meaning `compute_multi_epi_mask` should use it, `CanICA` should use it, etc.

+1 for the class parameter.

**Comment by arthurmensch** [comment]
Should we keep the shelved result list as an attribute in MultiNiftiMasker ?

**Comment by AlexandreAbraham** [comment]
Shelving is implemented but not exposed, not to confuse the non-technical users. I think we can consider this issue as solved.
