### ISSUE TITLE
test_atlas.test_fail_fetch_atlas_harvard_oxford fails without sudo privileges

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#993]
On my labtop this test runs OK with sudo privileges and fails without sudo

May be it is because it relies on fake atlas with 5 labels created for this test but without sudo privileges data is not created. Then `data_dir` for the function `fetch_atlas_harvard_oxford` is `None` so it loads my real atlas in FSL DIR which has 97 labels.

Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/home/salma/CODE/Parietal/nilearn/nilearn/datasets/tests/test_atlas.py", line 143, in test_fail_fetch_atlas_harvard_oxford
assert_equal(len(ho.labels), 5)
AssertionError: 97 != 5
'97 != 5' = '%s != %s' % (safe_repr(97), safe_repr(5))
'97 != 5' = self._formatMessage('97 != 5', '97 != 5')
raise self.failureException('97 != 5')

**Comment by AlexandreAbraham** [comment]
Fixed in 2d806ec1507b4f7b5cd742aedb71d8467b58c572

Can you pull master and check?

**Comment by salma1601** [comment]
Yes it's OK now, thanks !

**Comment by AlexandreAbraham** [comment]
Cool. Thanks for reporting!
